### ISSUE TITLE
Log Selected Endpoint

### ISSUE THREAD

**Issue by Kahbazi** [microsoft/reverse-proxy#102]
Is it good to Log which Endpoint is selected in `ProxyInvokerMiddleware`?

**Comment by Tratcher** [comment]
We'll want to do a holistic look at the logs at some point. E.g. What does the end-to-end look like at different log levels. 

In this example, we don't want redundant logging from LoadBalancerMiddleware, ILoadBalaner, ProxyInvokerMiddleware, and HttpProxy, only one should log at an info level which endpoint was proxied to. Maybe at the debug level they do have some duplication, but each would probably log different details.

**Comment by karelz** [comment]
Covered in #158
