### ISSUE TITLE
Expose cipher suites from TlsFrameInfo

### ISSUE THREAD

**Issue by davidfowl** [microsoft/reverse-proxy#1023]
### What should we add or change to make your life better?

We've had requests to expand the information in TlsFrameInfo to include the cipher suites sent from the client. 

### Why is this important to you?

The ability to reject the connection based on the cipher suites is important to some reverse proxies.

cc @Tracher @wfurt

**Comment by karelz** [comment]
Triage: @wfurt mentioned we need to extend the parser to handle this as well.
