### ISSUE TITLE
Documentation: Proxying Headers, what you need to consider

### ISSUE THREAD

**Issue by samsp-msft** [microsoft/reverse-proxy#1028]
*Feedback from the header review*
Documentation topic for what apps need to consider in terms of header transforms when a proxy is fronted for a site.

Headers:
- Cookie - possibly needs to change if it is tied to a specific domain
- Host - we default to use the destination address - may need to specify the original
- Location - Proxy will (by default) pass back to the caller, so it needs to be relative for the end user, not the proxy
- Server - Proxy will by default use Kestrel, but app can change what they want to send instead (if at all)
- X-Powered-By - same as for "Server"
- X-Forwarded-* - Proxy will by default replace with values from the client / back end

**Comment by Tratcher** [comment]
Also cover the headers we remove for functional or security reasons:
https://github.com/microsoft/reverse-proxy/blob/51d797986b1fea03500a1ad173d13a1176fb5552/src/ReverseProxy/Forwarder/RequestUtilities.cs#L61-L83
