### ISSUE TITLE
Measure performance impact of passive health checks

### ISSUE THREAD

**Issue by alnikola** [microsoft/reverse-proxy#1033]
We need to understand what is the overhead of having passive health checks enabled. One of suspicious places to take closer look is in [TransportFailureRateHealthPolicy.EvaluateProxiedRequest](https://github.com/microsoft/reverse-proxy/blob/51b3a7df9f54f848d6ee9028dc5a7cfb9ee48d02/src/ReverseProxy/Service/HealthChecks/TransportFailureRateHealthPolicy.cs#L60) which takes destination-scoped lock on each request.

**Comment by MihaZupan** [comment]
Duplicate of #1033?

**Comment by alnikola** [comment]
Oh, you are right. I forgot about the old one.

**Comment by alnikola** [comment]
Duplicate of #538
