### ISSUE TITLE
Ability to determine the Proxied Destination before proxying

### ISSUE THREAD

**Issue by brentnewbury-work** [microsoft/reverse-proxy#1051]
### What should we add or change to make your life better?
It would be very helpful to determine the proxied destination before we actually proxy. Maybe this can be done with a method on the `IReverseProxyFeature` (or something accessible via `IReverseProxyFeature`) that would determine the proxy destination and then use this value when proxying the request.

### Why is this important to you?
I'd like to output a `Via` response header that contains some information about where the request was proxied to. I can't use `IReverseProxyFeature.ProxiedDestination` as this property is only available after the request has been proxied and no headers can be added as the request has already started.

**Comment by Tratcher** [comment]
You can (and should) do this in response transforms, you'd have full access to the request and response at that point.
https://microsoft.github.io/reverse-proxy/articles/transforms.html#extensibility

Alternatively, you can do this in middleware. Place the middleware after LoadBalancing and then look at IReverseProxyFeature.AvailableDestinations. There should only be one left at that point and that's the one that will be proxied to.

**Comment by brentnewbury** [comment]
I was just thinking that my idea wouldn't work because of the built in middleware, e.g. health check middleware, that could filter out the "pre-determined" destination between the call to my proposed method and the request being proxied. It would still work for me as I'm not using them, but it wouldn't work for others, at least not nicely.

I think response transforms may be the way to go. I'll take a look tomorrow, but as long as I have access to the `IReverseProxyFeature` with the `ProxiedDestination` set, I think it'll be a winner 👍

The middleware idea wouldn't work in my scenario as I could be left with multiple AvailableDestinations and not know which one would be picked by the proxy prior to sending.

**Comment by Tratcher** [comment]
> I was just thinking that my idea wouldn't work because of the built in middleware, e.g. health check middleware, that could filter out the "pre-determined" destination between the call to my proposed method and the request being proxied. It would still work for me as I'm not using them, but it wouldn't work for others, at least not nicely.

That's a matter of ordering. Session affinity goes before load balancing, where your component would go after.

> The middleware idea wouldn't work in my scenario as I could be left with multiple AvailableDestinations and not know which one would be picked by the proxy prior to sending.

You should be using LoadBalancing to address that. The default behavior is to log a warning and pick randomly if there are still multiple available destinations when you reach the end of the middleware pipeline.

> I think response transforms may be the way to go. I'll take a look tomorrow, but as long as I have access to the IReverseProxyFeature with the ProxiedDestination set, I think it'll be a winner 

It is, but you shouldn't need it since you'll have direct access to the proxy request and response and their RequestUrl.

**Comment by brentnewbury** [comment]
I'm going to be using the proxy to route tenant requests to their data sovereign regions. LoadBalancing doesn't seem like it's going to be much use to me just yet.

I'm glad I'll have access to the `IReverseProxyFeature` as the proxy request and it's URL isn't much use. 

To give more context of what I'm doing to achieve, I want to output a `Via` header that looks something like:
```Via: HTTP/1.1 eu (a:2;f:1;d:us)```
This should adhere to the HTTP spec, but more importantly; it'll tell me that the request hit the EU proxy (`eu`), (`a` for "all") there were 2 destinations in `AllDestinations`, (`f` for "filtered") there was 1 destination in `AvailableDestinations` (we have middleware that filters `AllDestinations`), then finally (`d` for "destination") the request was proxied to the US region (`us` would be the destination identifier).

Thanks for your help, I'll reply back tomorrow after I've tried a response transform. 👍 I'm also happy to have a call to talk about our use-case if you're interested.

**Comment by Tratcher** [comment]
Interesting. I'd have expected tenant routing to be handled at the routing layer, and each data sovereign region to be its own cluster. What field(s) on the request do you use to identify the tenant?

**Comment by brentnewbury** [comment]
We're going to be using a claim in the JWT to determine the tenant region. I did want to have each region be a cluster but I couldn't work out a way to do that. The examples given were of filtering destinations in a given cluster. Do you have any suggestions?

**Comment by Tratcher** [comment]
Ah, routing by claim would be hard, especially since we normally decide what auth to apply after routing.

**Comment by brentnewbury** [comment]
No worries, what we've got so far is working and appears to be working well. Let me know if you'd like any further information or if there's any way I can help.

I'll update you tomorrow when I've tried out the response transform, but I'm hopeful.

**Comment by samsp-msft** [comment]
> We're going to be using a claim in the JWT to determine the tenant region. I did want to have each region be a cluster but I couldn't work out a way to do that. The examples given were of filtering destinations in a given cluster. Do you have any suggestions?

@Tratcher - we had talked about this scenario of being able to change the way that routes are mapped to clusters and destinations. Can he replace the existing mapping and just provide his own collection of available destinations?

**Comment by brentnewbury-work** [comment]
Fyi, using a `ResponseTransform` appears to work. 👍

However, my only issue now is unit testing it as I can't create a new `ResponseTransformContext` and initialise the `HttpContext` property in a .NET Core 3.1 app as the property is `init` only. There's no interface for me to implement and provide my own implementation to the `ResponseTransform.Apply(ResponseTransformContext)` method, e.g. `IResponseTransformContext`. I can't create a child of `ResponseTransformContext` and hide the `HttpContext` property with the `new` keyword as the `ResponseTransform.Apply(ResponseTransformContext)` method only see's the hidden property which will always be `null`.

Please be careful with `init` only properties as .NET Core 3.1 apps don't support them (locked to lang version 8.0, `init` was added in 9.0) and if there's no interface that I can implement to provide my own implementation, e.g. `IReverseProxyFeature`, I'm stuck.

**Comment by brentnewbury-work** [comment]
If the backend destination fails to respond, e.g. a timeout or some other issue, the `ResponseTransform` won't be called. This breaks a very important scenario for me. I still want the `Via` header to be included in the response, but I can't seem to figure out how to do that.

**Comment by brentnewbury-work** [comment]
It really would be useful to have something like:
```csharp
services.AddReverseProxy(options => 
{
    OnBeforeProxy = (context) =>
    {
        // This would be called somewhere just prior to https://github.com/microsoft/reverse-proxy/blob/2fd46596c7cc370660f024e442ac3c8c00b88acf/src/ReverseProxy/Proxy/ProxyInvokerMiddleware.cs#L80
    }
});
```

**Comment by Tratcher** [comment]
> Please be careful with `init` only properties as .NET Core 3.1 apps don't support them (locked to lang version 8.0, `init` was added in 9.0) and if there's no interface that I can implement to provide my own implementation, e.g. `IReverseProxyFeature`, I'm stuck.

See https://github.com/microsoft/reverse-proxy/issues/837, there are C# 9.0 options for 3.1.

**Comment by Tratcher** [comment]
> If the backend destination fails to respond, e.g. a timeout or some other issue, the `ResponseTransform` won't be called. This breaks a very important scenario for me. I still want the `Via` header to be included in the response, but I can't seem to figure out how to do that.

The lack of transforms on response failures is an interesting gap. Right now many response transforms can be marked as "Always" or "Success", but at the moment "Always" doesn't include a failure to respond. I'm going to open a separate issue for that.

> It really would be useful to have something like:
> 
> ```cs
> services.AddReverseProxy(options => 
> {
>     OnBeforeProxy = (context) =>
>     {
>         // This would be called somewhere just prior to invoking the proxy, e.g.
>         // https://github.com/microsoft/reverse-proxy/blob/2fd46596c7cc370660f024e442ac3c8c00b88acf/src/ReverseProxy/Proxy/ProxyInvokerMiddleware.cs#L80
>     }
> });
> ```

You could do that with a request transform, it gives you the HttpContext and the content you want to add doesn't depend on the actual response.

**Comment by brentnewbury** [comment]
Thanks, Chris. I did install the .NET 5.0 SDK in the build pipeline, but then I had an error with the test project, so I just ended up switching the solution over to .NET 5.0.

I'm doing something similar with the request transform, but I'm stuck with it not being called when the backend fails to respond. :( Which is a real pain because that's exactly the type of issue where I'd want to see a Via header in a HAR file or network trace and see which backend they were routed to.

On a more positive note: Yarp is a really great tool. You're doing a good job. I'm really excited about using it.

**Comment by Tratcher** [comment]
> I'm doing something similar with the request transform, but I'm stuck with it not being called when the backend fails to respond.

? Request transforms are called before sending the request, they should always run. If there's a response failure you'll get a 502/503, but any extra response headers you added before that should still be sent.

**Comment by brentnewbury** [comment]
Sorry, my bad, I meant response transform.

**Comment by brentnewbury** [comment]
Yep, that works. Thank you very much. 👍

**Comment by Tratcher** [comment]
> > We're going to be using a claim in the JWT to determine the tenant region. I did want to have each region be a cluster but I couldn't work out a way to do that. The examples given were of filtering destinations in a given cluster. Do you have any suggestions?
> 
> @Tratcher - we had talked about this scenario of being able to change the way that routes are mapped to clusters and destinations. Can he replace the existing mapping and just provide his own collection of available destinations?

Routes are hard coded to a cluster right now, but what you can do in middleware is completely replace the `IReverseProxyFeature` if you want to re-route. You could use `IClusterChangeListener` to collect clusters to choose from.

At that point you have to ask if using IHttpProxy directly would be simpler.

**Comment by brentnewbury** [comment]
I'm fine with having a single cluster with multiple destinations configured, then using middleware to filter the destinations.

But I imagine there being a requirement to dynamically choose a cluster for a given route. It's not an issue for me because the destinations are in Azure and we can scale out to achieve high availability/load balancing.

**Comment by karelz** [comment]
Triage: Seems to be answered, closing.
