### ISSUE TITLE
No response transforms if the destination fails to respond

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#1056]
https://github.com/microsoft/reverse-proxy/issues/1051#issuecomment-854811689 (@brentnewbury-work)

### Describe the bug
Response transforms are skipped if the destination fails to respond due to a connection issue or timeout. A fixed status code is set and processing exits:
https://github.com/microsoft/reverse-proxy/blob/2fd46596c7cc370660f024e442ac3c8c00b88acf/src/ReverseProxy/Proxy/HttpProxy.cs#L134-L143
https://github.com/microsoft/reverse-proxy/blob/2fd46596c7cc370660f024e442ac3c8c00b88acf/src/ReverseProxy/Proxy/HttpProxy.cs#L460-L477

Some response transforms like ResponseHeader have the setting to run on "Success" or "Always", but always does not currently include the failure-to-respond scenario. It might even make sense to add a "Failure" mode to only run transforms for 5xx and connection failures. 

I'm mainly concerned about the "Always" case since people expect it run and generate consistent output. Failure cases can already be handled by the caller, but you don't want to duplicate logic for the Always scenario.

We would want to make the ProxyError value available to these transforms.

**Comment by karelz** [comment]
Triage: If we do that, we should do it in 1.0 to avoid breaking in future.
We need to harden our transforms for that.
We may have to extend couple of transforms (as mentioned above).

**Comment by alnikola** [comment]
Submitted #1256 to cover "Failure" mode.
