### ISSUE TITLE
All X-Forwarded-* transforms should replace rather than append values, strip values if x-forwarded is disabled.

### ISSUE THREAD

**Issue by samsp-msft** [microsoft/reverse-proxy#1070]
Default action needs to change.

**Comment by Tratcher** [comment]
Related: There should also be an option to remove x-forwarded headers even if you're not using them.

**Comment by Tratcher** [comment]
Re-opening to track an remaining question: Should `Forwarded` be removed when `X-Forwarded` is used and vice versa?

**Comment by Tratcher** [comment]
Design notes:

In the default scenario we should add X-Forwarded-* headers (SET) like we do today, but also Remove the Forwarded header.

If someone manually configures X-Forwarded, we should still Remove the Forwarded header.

If someone manually configures Forwarded, we should Remove the X-Forwarded headers.

If someone in the future wants both then we'll need more input on how they expect them to interact. One future mitigation might be adding a flag to each of these transforms like `RemoveAlternatives` that defaults to true (the behavior described above), but would allow them to opt-out.
