### ISSUE TITLE
YARP request queuing or latency

### ISSUE THREAD

**Issue by mgnoonan** [microsoft/reverse-proxy#1079]
### Describe the bug

My use case is to setup YARP as a drop-in replacement for 3 of our API services, which are migrating to APIM/app services in Azure. This allows our internal clients to maintain existing configuration, but still get data from our services in Azure. The flow is:
`YARP -> Express Route -> APIM -> Region 1/Region 2 app services`

I have been conducting some load tests, and I see some behavior that I cannot explain. Looking at the screen cap from App Insights, I see the proxy call begin, but then nothing happens for ~22s, then the call hits Azure and completes in ~1.2s, but the overall time taken is 24s.
![image](https://user-images.githubusercontent.com/3255096/121784891-a6d48800-cb84-11eb-98aa-bdd6e31518db.png)

Looking at the test run overall, the timings on the YARP proxy servers looks good to start, but then hits a wall and suddenly the slowest calls regularly start to hit the 30s timeout (as set in the config).
![image](https://user-images.githubusercontent.com/3255096/121784936-e69b6f80-cb84-11eb-82ad-e4e026ae0638.png)

I do not see any corresponding slow responses in the downstream calls, so I don't see how this is a reflection of problems with other systems. It seems more like the requests are being queued, or there is some kind of throttling or connection latency that kicks in during the test.

Do I need to set the MaxConnectionsPerServer? Any insights you have are greatly appreciated. Love the project, I just need to get over this hurdle.

### To Reproduce

I can't provide the exact steps as this is a performance test customized for my API and built using VS Test. The target goals are 1200 req/sec, and the automation ramps up the number of users to 27k over the course of the test.

Here is a redacted version of my appSettings.json:
```json
"ReverseProxy": {
    "Routes": {
      "route-instore": {
        "ClusterId": "cluster1",
        "Match": {
          "Path": "{**catch-all}",
          "Hosts": [ "appservice1" ]
        },
        "Transforms": [
          { "PathPrefix": "/svc1" }
        ]
      },
      "route-auth": {
        "ClusterId": "cluster1",
        "Match": {
          "Path": "{**catch-all}",
          "Hosts": [ "appservice2" ]
        },
        "Transforms": [
          { "PathRemovePrefix": "/api" },
          { "PathPrefix": "/svc2" }
        ]
      },
      "route-api": {
        "ClusterId": "cluster1",
        "Match": {
          "Path": "{**catch-all}",
          "Hosts": [ "appservice3" ]
        }
      }
    },
    "Clusters": {
      "LoadBalancingPolicy": "PowerOfTwoChoices",
      "cluster1": {
        "HttpClient": {
          "SslProtocols": [
            "Tls12"
          ]
        },
        "HttpRequest": {
          "RequestTimeout": "00:00:30"
        },
        "HealthCheck": {
          "Active": {
            "Enabled": "true",
            "Interval": "00:00:05",
            "Timeout": "00:00:05",
            "Policy": "ConsecutiveFailures",
            "Path": "/healthz"
          }
        },
        "Metadata": {
          "ConsecutiveFailuresHealthPolicy.Threshold": "3"
        },
        "Destinations": {
          "cluster1/destination1": {
            "Address": "https://region1.azure-apim.net/"
          },
          "cluster1/destination2": {
            "Address": "https://region2.azure-apim.net/"
          }
        }
      }
    }
  }
```
Program.cs
```cs
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace NewProxy
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers();
            services.AddReverseProxy()
                .LoadFromConfig(Configuration.GetSection("ReverseProxy"));
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseRouting();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
                endpoints.MapReverseProxy();
            });
        }
    }
}
```

This is the exception I see in App Insights but I'm pretty sure it's from the proxy timeout setting of 30 secs.
```
System.Threading.Tasks.TaskCanceledException:
   at System.Net.Http.HttpConnection+<SendAsyncCore>d__56.MoveNext (System.Net.Http, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Net.Http.HttpConnectionPool+<SendWithRetryAsync>d__72.MoveNext (System.Net.Http, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Yarp.ReverseProxy.Service.Proxy.HttpProxy+<ProxyAsync>d__6.MoveNext (Yarp.ReverseProxy, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
Inner exception System.IO.IOException handled at System.Net.Http.HttpConnection+<SendAsyncCore>d__56.MoveNext:
   at System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.ThrowException (System.Net.Sockets, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
   at System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.GetResult (System.Net.Sockets, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
   at System.Net.Security.SslStream+<ReadAsyncInternal>d__181`1.MoveNext (System.Net.Security, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Net.Http.HttpConnection+<SendAsyncCore>d__56.MoveNext (System.Net.Http, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
Inner exception System.Net.Sockets.SocketException handled at System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.ThrowException:
```
### Further technical details

`<PackageReference Include="Yarp.ReverseProxy" Version="1.0.0-preview.11.21223.5" />`
.NET 5.0 running under IIS
4 Windows VMs, 8 cores x 8GB, mix of Server 2012 and 2016

**Comment by alnikola** [comment]
@mgnoonan Could you please collect the networking traces (using the command below) from the YARP machine when this issue is happening?

```
dotnet trace collect --providers System.Net.Http,System.Net.Sockets,System.Net.Security,System.Net.NameResolution -o yarp.longlatency.nettrace -p <YARP process ID>
```

**Comment by mgnoonan** [comment]
@alnikola We are running another perf test today, I have the tool installed and I'll try to get a capture if we see the same issue again. Is there a way to get the trace file to you without posting publicly?

**Comment by alnikola** [comment]
There are 2 options available
1. Upload the file on your OneDrive and send me the link via email
2. Send the encrypted file via email

Please, find my email in the GitHub profile.

**Comment by karelz** [comment]
Triage: Looks like a problem at the endpoint -- waiting on final confirmation, then we should be able to close.

**Comment by mgnoonan** [comment]
Waiting on the post-mortem of the latest performance testing, but it is looking like a downstream system issue. Will post the results here.

**Comment by mgnoonan** [comment]
I can confirm that this is indeed a problem with downstream systems and not an issue with YARP at all. We reconfigured our testing parameters and put the full load of the calls against YARP (which is not our production situation) and we not only hit our target levels but surpassed them by 2-5x in some cases while using less app instances than we do in production. Because of this new test profile, we were able to identify a number of issues in the downstream systems that were reflected in the proxy.

![image](https://user-images.githubusercontent.com/3255096/122604372-da5f5880-d043-11eb-8cdf-353e9ec394d9.png)

Looking at the struggling downstream system (AKS based), you can see one of our node pools becomes CPU-bound at roughly the same timestamp.

![image](https://user-images.githubusercontent.com/3255096/122604474-0084f880-d044-11eb-8717-9752525d5b74.png)

So YARP is only reflecting problems that originate in our Azure systems, and is not the cause at all. I am closing this issue. Thanks again to @alnikola and @MihaZupan for their analysis and identifying the issue.

**Comment by alnikola** [comment]
Thank you for confirming this.
