### ISSUE TITLE
Enforce Reactivation Period >= Detection Window in TransportFailureRateHealthPolicy

### ISSUE THREAD

**Issue by alnikola** [microsoft/reverse-proxy#1082]
TransportFailureRateHealthPolicy measures the share of the failed request out of the total request made do destination happened in the time period defined as Detection Window. Once a destination's passive health is set to `Unhealthy`, such destination gets scheduled for a reactivation after the defined Reactivation Period. Reactivation means changing the passive health status from `Unhealthy` to `Unknown` which again makes destination eligible for receiving traffic.

We need to ensure that Reaction Period >= Detection Window to avoid cases when a reactivated destination gets marked as `Unhealthy` right after the first request.

**Comment by alrz** [comment]
This basically makes setting reactivation period a no-op and you must make sure to set the detection period as well which imo is misleading. Would it make sense to automatically reduce detection period to match <= reactivation period?
