### ISSUE TITLE
Can I use this for ARR and url rewrite replacement ?

### ISSUE THREAD

**Issue by natilux2** [microsoft/reverse-proxy#109]
This project seems good for ARR and rewrite module replacement. Should I  ?

**Comment by Tratcher** [comment]
Can you? Probably. Should you? That's up to you. We would certainly like you to try it and let us know if you find anything that prevents you from using it as a replacement.

**Comment by davidfowl** [comment]
Yes that’s the intent. So if we have feature gaps you need, let us know as @Tratcher said

**Comment by natilux2** [comment]
Thanks, I will give a try
