### ISSUE TITLE
DestinationId not unique for Stateful services

### ISSUE THREAD

**Issue by keira369** [microsoft/reverse-proxy#1103]
### What should we add or change to make your life better?
During our service development with Yarp, we realized that the destinationId is replicaId for each destination. However, for stateful services, multiple partitions can have the same primary replicaId, which causes Yarp to return only one destination for one replicaId. We believe that it would solve the problem if we could have destinationId be the concatenation of partitionId and replicaId instead.

### Why is this important to you?
Currently we can't use destinationId to filter out the right availableDestinations for stateful services because of the above reason, instead, we need to loop through the services which increases the latency. If the destinationId is unique for each destination in stateful services, it would really make our life much easier!

**Comment by davidni** [comment]
+1. The original SF integration code made the wrong assumption that ReplicaId's / InstanceId's were globally unique. Looks like they aren't, and the proposal above seems reasonable:

> We believe that it would solve the problem if we could have destinationId be the concatenation of partitionId and replicaId instead
