### ISSUE TITLE
How to write an apiservice-agent with spdy

### ISSUE THREAD

**Issue by wenzj-code** [microsoft/reverse-proxy#1108]
### Why is this important to you?

How to write an apiservice-agent with spdy, just like kubectl->apiservice-agent-> k8s-apiservice
I just want to achieve this function like "kubectl exec "

Is there has an example ?

thanks

**Comment by karelz** [comment]
Triage: It is not clear how the question is related to YARP.

BTW: SPDY is supported as a protocol by YARP.

**Comment by karelz** [comment]
Triage: No reply for a week, closing. Feel free to reopen if there is more info available.
