### ISSUE TITLE
YARP should have an option for an allow list of headers

### ISSUE THREAD

**Issue by samsp-msft** [microsoft/reverse-proxy#1114]
Some places that YARP will be used will want to be very explicit with respect to http headers. They will only accept certain headers and so will want to switch YARP from using an accept-by-default model to a deny-by-default model with an allow list for the headers that are needed.
This should be possible through configuration without needing to rebuild YARP or hard code the lists in code.

**Comment by Tratcher** [comment]
To do this today you'd need to set the RequestHeadersCopy transform to false and then write a transform that copied only the headers you want. Same for the response. Transforms that reference specific headers like X-Forwarded would still run and could append to existing values.

A first class transforms for this would be something like:
```
// Disables Request/ResponseHeadersCopy and only copies the allowed list of headers
{ "RequestHeadersAllow": "HeaderName1;HeaderName2;" }
{ "ResponseHeadersAllow": "HeaderName1;HeaderName2;" }
```
