### ISSUE TITLE
Any WIP on routing to SF partitions?

### ISSUE THREAD

**Issue by WhitWaldo** [microsoft/reverse-proxy#1121]
### Some details
I see from the docs that the Service Fabric integration doesn't yet have any partition support. I'm looking for a solution that can use YARP to effectively load balance against a partitioned stateful service round-robin (e.g. don't need to be able to route to a specific partition based on some external value, but needs to be able to resolve and send the request to a valid partition),

Is there anything currently in progress on this? It's unclear what the current state of things are with the Service Fabric integration and I'd like to help out if I can.

**How many backends are in your application?**

- [ ] 1-2
- [ ] 3-5
- [ ] 6-10
- [X] 10+

**How do you host your application?**

- [ ] Kubernetes
- [ ] Azure App Service
- [ ] Azure VMs
- [ ] Other Cloud Provider (please include details below)
- [X] Other Hosting model (please include details below)
   Azure Service Fabric

### What did you think of YARP?
Excellent solution so far. We're just using it as a simple proxy (on a stateless service with a static port) so it can route to other internal stateless services assigned to dynamic ports, but I'd increasingly like to replace our dependence on Azure App Gateway (which is unaware of SF) with YARP (which is service-aware)

**Comment by Tratcher** [comment]
FYI: https://github.com/microsoft/reverse-proxy/discussions/1091#discussioncomment-884640

**Comment by Tratcher** [comment]
SF work has moved to https://github.com/microsoft/service-fabric-yarp
