### ISSUE TITLE
How To Set ServerCertificateCustomValidationCallback?

### ISSUE THREAD

**Issue by Kahbazi** [microsoft/reverse-proxy#113]
What is the appropriated way to set `ServerCertificateCustomValidationCallback` for each backend?

**Comment by anurse** [comment]
Hmm, not sure there is a built-in way yet. It should be something we enable in code at least.

We should consider having some basic config options to set predefined validation patterns, like:

- Allow untrusted certain
- Allow specific thumbprints
- Allow any cert that chains to one with a specific thumbprint

Using the proxy in a custom public key infrastructure will be fairly common.

**Comment by samsp-msft** [comment]
@scalablecory @karelz @wfurt

**Comment by Tratcher** [comment]
For reference, the handler is created here: https://github.com/microsoft/reverse-proxy/blob/bc9298322206f35e7d658183464cdf806280143f/src/ReverseProxy.Core/Service/Proxy/Infra/ProxyHttpClientFactory.cs#L33-L42 and doesn't currently have access to any route/backend/endpoint config options.

**Comment by karelz** [comment]
Covered as larger task in #137
