### ISSUE TITLE
Dynamic backends issue and variables

### ISSUE THREAD

**Issue by sergiobortsov** [microsoft/reverse-proxy#1138]
Hi all!
Sorry if I missed this subject somewhere in the issues list, please just point me there if it's answered already.
I have a lot of GRPC backends running and part of them is dynamically changing due to hibernation flow. It means the backends quantity is constantly changing. If I put the list of Destination on yarp appsettings.json it's perfectly working till some backend is down, so I'm getting 502 errors due to DNS issue (Name or host is unknown). Is it possible to configure yarp to ignore the "dead" backends or even better to change configuration on-the-fly, like haproxy templates do - have backends names as variable and add the servers by DNS resolver.
Thanks.

**Comment by Tratcher** [comment]
Is it a stable list of endpoints except for the fact that some of them go down (hibernate) and come back up later at the same address? If so then you should try active and passive [health checks](https://microsoft.github.io/reverse-proxy/articles/dests-health-checks.html). These will catch when your destinations go down and pull them out of rotation. They'll automatically go back into rotation later when they come back up.

Or is the list of destinations completely dynamic, as in they are destroyed and new ones created on new addresses? If that's the case then you'll want to switch from appsettings.json to either [code based config](https://microsoft.github.io/reverse-proxy/articles/config-providers.html) or [direct forwarding](https://microsoft.github.io/reverse-proxy/articles/direct-forwarding.html) to allow you to discover the destinations dynamically.

**Comment by sergiobortsov** [comment]
super cool, thanks for your reply @Tratcher 
I'm not actually a developer, just a devops :)  so may I ask some help about Health Checks in YARP. Would it be enough to add it in configuration or I also need to put something in the code?
thanks

**Comment by Tratcher** [comment]
Health checks can be enabled in the config. See the linked doc.
