### ISSUE TITLE
Proxy can be customized with middleware to enable advanced scenarios

### ISSUE THREAD

**Issue by ryudice** [microsoft/reverse-proxy#114]
### What should we add or change to make your life better?
From looking at the source code I can see that you can add custom middlewares to the reverse proxy pipeline but I dont see any documentation outlining how to do it.
### Why is this important to you?
I think many of the people looking at the project is because they need to do some customization at the pipeline level and they want to avoid having to do it in another language like Lua in the case of Kong. Having this documentation would be very useful.

**Comment by Tratcher** [comment]
We'll certainly need docs for the whole project. The pipeline feature was just added last week :grin:. You can find an example here: https://github.com/microsoft/reverse-proxy/blob/00c4e7c77059b7c4a9912a4c89c9a05026d55628/samples/ReverseProxy.Sample/Startup.cs#L49-L60
And here's a middleware. It's a normal ASP.NET Core middleware with the addition of proxy features like BackendInfo and IAvailableBackendEndpointsFeature:
https://github.com/microsoft/reverse-proxy/blob/00c4e7c77059b7c4a9912a4c89c9a05026d55628/src/ReverseProxy.Core/Middleware/LoadBalancingMiddleware.cs#L38-L61

Did you have a specific scenario in mind?

**Comment by ryudice** [comment]
Thanks for the reply. Yeah the scenario I was specifically looking at is doing request transformations before passing it on to the backend. The reason we have this usecase is because we have legacy applications which are costly to modify, and in order to avoid being limited by them we use proxies to transform old request format into the new request format.

**Comment by Tratcher** [comment]
Makes sense. We're designing transforms as a first class feature over at https://github.com/microsoft/reverse-proxy/issues/21.

**Comment by gaumery** [comment]
thank u actually I really don't understand what you saying I'm just brainstorming cos I'm a kind of human being never stop learning
