### ISSUE TITLE
Redesign/remove IOperationLogger

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#115]
https://github.com/microsoft/reverse-proxy/blob/00c4e7c77059b7c4a9912a4c89c9a05026d55628/src/ReverseProxy.Core/Middleware/LoadBalancingMiddleware.cs#L47-L49

Using the IOperationLogger allocates a closure per call per request. We need to re-think how to write these start/stop/failed logs.

**Comment by anurse** [comment]
Perhaps if there's `Execute<T>(string, Action<T> callback, T state)`? That would allow the func passed in to be `static`.

**Comment by davidfowl** [comment]
We should avoid this pattern in general.

**Comment by halter73** [comment]
What about a `using` based pattern with IDisposable structs/pooled objects? The downside is it wouldn't be able to log errors.

Or do we just give up on the idea of having a helper for logging the start and end of an operation and have everyone do it manually.

**Comment by davidfowl** [comment]
> What about a using based pattern with IDisposable structs/pooled objects? The downside is it wouldn't be able to log errors.

It should be explicit.

> Or do we just give up on the idea of having a helper for logging the start and end of an operation and have everyone do it manually?

I'd prefer that.

The issue with callbacks are the ones we all hate:
- Breaks control flow
- Creates closures, which then need a state object to be worked around
- Need async versions of the callback, now it's harder to optimize for the non-async code paths

**Comment by Tratcher** [comment]
@MihaZupan this directly relates to your diagnostics work this milestone, I'll assign it to you for tracking.

**Comment by MihaZupan** [comment]
Closing this issue as the problem discussed above ("Redesign/remove IOperationLogger") has been dealth with by #501.

Opening a new issue for the user story.
