### ISSUE TITLE
Support for Substitutions

### ISSUE THREAD

**Issue by say25** [microsoft/reverse-proxy#1150]
### What should we add or change to make your life better?

Maybe I just don't know how to use YARP well enough yet, but I'd love something like NGINX Substitutions - https://www.nginx.com/resources/wiki/modules/substitutions/.

### Why is this important to you?

I want to use a Reverse Proxy as a way to add JavaScript and CSS to the site that I am proxying.

**Comment by Tratcher** [comment]
Manipulating request and response bodies is a non-goal for YARP, it's an extremely specialized problem and almost impossible to do in a performant way. 

See https://github.com/microsoft/reverse-proxy/discussions/447 for discussion on how to write custom middleware to manipulate bodies.
