### ISSUE TITLE
Healthchecks for destinations running on HTTP1.1 and HTTP/2

### ISSUE THREAD

**Issue by sergiobortsov** [microsoft/reverse-proxy#1153]
I use the YARP as gRPC balancer based on of course on HTTP/2. My destinations gRPC server are not using TLS as all of them is internal. So that's why I have the following settings in YARP config
```json
"HttpRequest": {
       "Version": "2",
       "VersionPolicy": "RequestVersionExact"
      },
```
But an endpoints for healthchecks are done as REST API with HTTP1.1 (on dotnet 5.0). So that's why I'm getting the
The HTTP/2 server sent invalid data on the connection. HTTP/2 error code 'PROTOCOL_ERROR' (0x1)

Can I somehow workaround it on the YARP side?
Thanks

**Comment by Tratcher** [comment]
See https://microsoft.github.io/reverse-proxy/articles/dests-health-checks.html#iprobingrequestfactory

**Comment by Tratcher** [comment]
Additional clarifications to add to the doc:
The default IProbingRequestFactory uses the same HttpRequest configuration as proxy requests, to customize that implement your own IProbingRequestFactory and register it in DI: `services.AddSingleton<IProbingRequestFactory, CustomProbingRequestFactory>();`

**Comment by sergiobortsov** [comment]
thanks @Tratcher

**Comment by sergiobortsov** [comment]
quick question: what if the destination is completely down, like
 System.Net.Sockets.SocketException (0xFFFDFFFF): Name or service not known
 Would it considered Unhealthy after Policy checks passed? Or it will return 5xx?
 thanks

**Comment by Tratcher** [comment]
That's considered unhealthy by both active and passive checks. If a passive check were the first to notice then the first few responses would still get 503s before it was pulled out of rotation. If you don't have any healthy destinations left then subsequent requests will also get 503s.

**Comment by MihaZupan** [comment]
Is there something else that should be done here or can we close this as answered?

**Comment by Tratcher** [comment]
> Is there something else that should be done here or can we close this as answered?

There's a doc update proposed here: https://github.com/microsoft/reverse-proxy/issues/1153#issuecomment-880137670
