### ISSUE TITLE
Css and js not loading when we use PathRemovePrefix

### ISSUE THREAD

**Issue by naveenkv66** [microsoft/reverse-proxy#1156]
Hello Everyone , kindly help us to resolve the below issue  if someone faced this issue before.
My goal:
path based routing
https://yarphost:90/app1 => destination is app1 (hosted 10.10.8.1)
https://yarphost:90/app2 =>  destination is app2(hosted 10.10.8.2)

How currently works:
i am using path remove prefix  transform(to remove app1 or app2 from route url)

https://yarphost:90/app1 => https://app1host:5000/  (Works fine)
https://yarphost:90/app1/home => https://app1host:5000/home  (Works fine)

https://yarphost:90/app2 => https://app2host:5001/ (Works fine)
https://yarphost:90/app2/home => https://app2host:5001/home  (Works fine)

when comes to css and js
from DOM below requests are initiated after app rendered in browser
https://yarphost:90/app1style.css => getting 404
https://yarphost:90/app2style.css => getting 404
instead of pointing destination it tries to render it from Reverse proxy server host.

Any workaround for this, we dont want change any routing rules in our backend (its legacy application maintained by other vendors, our client is not ready to change the backend application) 

![image](https://user-images.githubusercontent.com/39585519/126096129-ed971640-271f-49f3-abf9-78b9a2183a23.png)
![image](https://user-images.githubusercontent.com/39585519/126096250-6d994beb-1c07-4148-83cc-3e1ba421ccdd.png)

**Comment by karelz** [comment]
@naveenkv66 so what is the key problem here?
Is it the missing path separator in app1syle.css? (should be app1/style.css)
Or is it something different?

**Comment by Tratcher** [comment]
Inspect the resulting html where it references the css files. It's likely using absolute paths like `/app1style.css`, which will always be relative to the host. It's easiest to fix in the application by changing it to relative paths like `./app1style.css` or `../../app1style.css`.

It's much harder to fix in the proxy layer. YARP does not directly support response content rewriting, though you can do it in middleware. You have to intercept the response body stream, decode it, parse it, edit it, and then forward it to the client. See https://github.com/microsoft/reverse-proxy/discussions/520

**Comment by samsp-msft** [comment]
The easiest way to debug this is probably to hit F12 in your browser and switch to the tab that shows network traffic. That will then show which URLs are actually being requested by the browser.

**Comment by karelz** [comment]
Triage: No response, closing. If there is more info, feel free to reopen.

**Comment by TechAspirant** [comment]
@naveenkv66 Did you solve the problem ? I am having similar problem. For js and css I am getting 404.
