### ISSUE TITLE
Request body maximum size

### ISSUE THREAD

**Issue by sergiobortsov** [microsoft/reverse-proxy#1161]
### What should we add or change to make your life better?
We need to have a possibility to send by grpc a bigger files (8-10 Mbytes). It looks like there is some default limitations enabled by default in YARP code. It it true? To be honest, I couldn't catch an exact exception in yarp logs. I got just strange stuck state on the grpc client. But it only happened for bigger messages. Could be the case with YARP? Or I should dig in another direction?
Thanks

**Comment by MihaZupan** [comment]
There are no limits on the gRPC size imposed by YARP.

There is a [~29 MB limit in Kestrel](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.kestrel.core.kestrelserverlimits.maxrequestbodysize) by default, but YARP will disable it for streaming requests such as gRPC.

Is it possible that the client you are using / backend service have their limits?

**Comment by karelz** [comment]
Triage: We need more info to make it actionable. Were you able to find anything on the backend @sergiobortsov

**Comment by adityamandaleeka** [comment]
Triage: Closing since we haven't gotten more info. Let us know here if you have more information.
