### ISSUE TITLE
Header transform "Set": "" now empties the header instead of removing it (1.0.0-preview.12)

### ISSUE THREAD

**Issue by christianrondeau** [microsoft/reverse-proxy#1167]
### Describe the bug
Between 1.0.0-preview.11 and 1.0.0-preview.12, there is a breaking change that empties headers instead of removing them. I think this was updated in the documentation, so you may want to close this issue (though it would be very nice to add this to the breaking changes list)

### To Reproduce
In `appsettings.json`:

```json
{
  "ReverseProxy": {
    "Routes": {
      "some-blob" : {
        "ClusterId": "some-cluster",
        "Match": {
          "Path": "/proxy/{*any}"
        },
        "Transforms": [
          { "PathPattern": "/{any}" },
          {
            "RequestHeader": "Authorization",
            "Set": ""
          }
        ]
      },
    },
    "Clusters": {
      "some-cluster": {
        "Destinations": {
          "some-cluster/destination": {
            "Address": "https://some-azure-blob-url/"
          }
        }
      }
    }
  }
}
```

With a controller like this:

```c#
        [HttpGet("capture/{*path}")]
        public IActionResult Capture()
        {
            return Ok(new
            {
                authorization = Request.Headers.Authorization.Count == 0 ? "NONE" : Request.Headers.Authorization[0]
            });
        }
```

With version 11:

```bash
λ  curl http://localhost:5000/proxy/hello -H "Authorization: Test"
{"path":"hello","value":null,"authorization":"NONE"}
```

With version 12:

```
λ  curl http://localhost:5000/proxy/hello -H "Authorization: Test"
{"path":"hello","value":null,"authorization":""}
```

### Further technical details

- Include the version of the packages you are using: `1.0.0-preview12`
- The platform (Linux/macOS/Windows): `Windows`
- .NET Version: `net6.0` (preview 6), though it works with preview 6 and YARP preview11.

**Comment by Tratcher** [comment]
Where do you see that double encoding reported? In the logs I still see:
```
info: Yarp.ReverseProxy.Forwarder.HttpForwarder[9]
      Proxying to https://example.org/?q=000%3A000
```

**Comment by christianrondeau** [comment]
You're right, let me isolate the problem and make an actual repro project

**Comment by christianrondeau** [comment]
So I was misled, the issue is not actually related to encoding by rather to the fact that the `"Set": ""` now sets the header to empty instead of not sending the header at all. Sorry about that, I'll update the description and example to be more precise, and provide more info to repro.

**Comment by Tratcher** [comment]
Ah, that was intentional. We added a new transform that removes headers instead.
https://microsoft.github.io/reverse-proxy/articles/transforms.html#requestheaderremove

**Comment by christianrondeau** [comment]
Yes, I indeed just figured it out while trying to find the documentation reference from which I made the initial appsettings :)

So I guess this issue can be closed, however this is a subtle change so I would suggest a dedicated breaking change point in the preview.12 release notes!

Thanks!

**Comment by Tratcher** [comment]
Fair. I see we have `New transforms added: RequestHeaderRemove, ResponseHeaderRemove, ResponseTrailerRemove.` but no mention of the change to the `RequestHeader` transform.

**Comment by christianrondeau** [comment]
(This being said, I think having a Remove transform makes more sense than using ""!)

**Comment by Tratcher** [comment]
Updated.

**Comment by christianrondeau** [comment]
Thanks! Now for some reason the new header doesn't work for me (I think this is when appsettings has multiple routes), I'll investigate and create a new issue...

```
System.InvalidOperationException: Unable to load or apply the proxy configuration.
 ---> System.ArgumentException: Unknown transform: RequestHeaderRemove
```
with

```json
        "Transforms": [
          { "PathPattern": "/{any}" },
          {
            "RequestHeaderRemove": "Authorization"
          }
        ]
```

Something's weird when looking in the TransformBuilder, it looks like the _factories iterator just skips. I'll try and make a repro.

**Comment by Tratcher** [comment]
Woops. That was https://github.com/microsoft/reverse-proxy/pull/1135 which I thought was in p12 but it's actually in the latest branch still. You can get that fix in our daily builds:
https://github.com/microsoft/reverse-proxy/blob/main/docs/DailyBuilds.md

**Comment by christianrondeau** [comment]
Ah so no need to create another issue nor a repro then? Thanks for letting me know :)
