### ISSUE TITLE
Yarp.ReverseProxy.Kubernetes.Protocol Package

### ISSUE THREAD

**Issue by archonandrewhunt** [microsoft/reverse-proxy#1171]
The sample Yarp.ReverseProxy.Kubernetes.Ingress is not reproducible in my own project because the Yarp.ReverseProxy.Kubernetes.Protocol classes are not available in a package that my project can use. Are there any plans to produce such a package, similar to the Yarp.ReverseProxy.ServiceFabric package that exists for that integration?

**Comment by Tratcher** [comment]
Eventually, yes, but not for 1.0 since those components are still experimental. For now you need to build the package from src in the repo.
