### ISSUE TITLE
IHttpForwarder extensions for basic request transforms

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#1172]
Doing any transforms with IHttpForwarder requires creating a derived HttpTransformer instance.

Here's a comparison with go:
https://gist.github.com/davidfowl/cf68de7da1f6cb4d7dcbedd6e1a9c6a4

We have some extension methods already:
https://github.com/microsoft/reverse-proxy/blob/34fe0134ecd290b5d17b7ccaba15f0715ae902d4/src/ReverseProxy/Forwarder/IHttpForwarderExtensions.cs#L23-L24

We can provide extension methods for simple request transforms:
```
public static ValueTask<ForwarderError> SendAsync(this IHttpForwarder forwarder, HttpContext context, string destinationPrefix,
            HttpMessageInvoker httpClient, Action<HttpRequestMessage> requestTransform)
```
Note TransformRequestAsync takes several parameters that aren't needed in the simple case:
https://github.com/microsoft/reverse-proxy/blob/34fe0134ecd290b5d17b7ccaba15f0715ae902d4/src/ReverseProxy/Forwarder/HttpTransformer.cs#L38

Which / how many overloads should we provide?

Requested by @davidfowl

**Comment by adityamandaleeka** [comment]
Triage: Maybe we could prototype these by putting them in the sample.

**Comment by Tratcher** [comment]
These were merged into the sample. Re-opening to consider moving into the product.
