### ISSUE TITLE
Get Event for incoming client request

### ISSUE THREAD

**Issue by TechAspirant** [microsoft/reverse-proxy#1174]
Is their any event in YARP which gets fired when incoming client request comes ? Event should get fired before forwarding the request to the destination If configuration exists else add dynamic configuration and then forward the request.

**Comment by MihaZupan** [comment]
What are you trying to achieve?

If you want to add your own logic before the the forwarding happens, you can insert a middleware before/in `MapReverseProxy`. See [an example from the samples](https://github.com/microsoft/reverse-proxy/blob/9cc305e83523841fbcc164e056e55e58691fa570/samples/ReverseProxy.Code.Sample/Startup.cs#L48).

**Comment by TechAspirant** [comment]
I want to start my application (ASP.NET Web application) programmatically If not started before the forwarding happens.

**Comment by MihaZupan** [comment]
You want to lazily spin up the destination server/app as the request for it comes into YARP?

You could do so from a middleware I mentioned above. In the [sample](https://github.com/microsoft/reverse-proxy/blob/9cc305e83523841fbcc164e056e55e58691fa570/samples/ReverseProxy.Code.Sample/Startup.cs#L100), the custom step is filtering destinations, but you could use it to start a service instead.

**Comment by TechAspirant** [comment]
I will also get the client request information in the middleware. As I also want to validate the client request is of specific pattern or not.

**Comment by MihaZupan** [comment]
The `HttpContext` contains the request information.

**Comment by TechAspirant** [comment]
Ok, Thanks. Will check and see If I can adapt as per my needs.
