### ISSUE TITLE
Question: How to add route and cluster from Custom Proxy Middleware?

### ISSUE THREAD

**Issue by TechAspirant** [microsoft/reverse-proxy#1176]
How to add route and cluster from Custom Proxy Middleware ?

```
public Task CustomProxyMiddleware(HttpContext context, Func<Task> next)
{
    //Client request received before forwarding
    //Add route and cluster
   return next();
}
```

**Comment by Tratcher** [comment]
Is this a remote configuration endpoint, or are you trying to affect the routing of the current request?

If it's the former, implement an IProxyConfigProvider something like this one:
https://github.com/microsoft/reverse-proxy/blob/main/samples/ReverseProxy.Code.Sample/InMemoryConfigProvider.cs
https://microsoft.github.io/reverse-proxy/articles/config-providers.html

If it's the latter, the config isn't designed to be modified per-request. You should instead use direct-forwarding:
https://microsoft.github.io/reverse-proxy/articles/direct-forwarding.html

**Comment by TechAspirant** [comment]
If proxy server receives request from http://x.x.x.x:5000/Session1 which needs to be forwarded to http://y.y.y.y:6000/ then,
Check If current route contains match for 'Session1' If yes forward to respective cluster
else add route and cluster for 'Session1' and then forward.

**Comment by Tratcher** [comment]
Config updates are meant to react to environment changes, but there's some delay before it applies to incoming requests. Direct-forwarding is better for per-request routing decisions.

**Comment by TechAspirant** [comment]
If I understood right I can use InMemoryConfigProvider.cs for updating my routes and clusters as I want.
As direct forwarding will not differentiate between '/Session1' and '/Session2' routes.

**Comment by Tratcher** [comment]
InMemoryConfigProvider updates routes and clusters on demand, but that's a background update and there's no guarantee it will apply to the current request.

Direct forwarding enables _you_ to differentiate between  '/Session1' and '/Session2' routes and select the destination.

**Comment by TechAspirant** [comment]
Can you please share an example or sample piece of code for Direct forwarding for my scenario '/Session1' and '/Session2' ?

**Comment by Tratcher** [comment]
Starting with this example:
https://github.com/microsoft/reverse-proxy/blob/9cc305e83523841fbcc164e056e55e58691fa570/samples/ReverseProxy.Direct.Sample/Startup.cs#L53-L55

I changed it to the following:
```
                endpoints.Map("/{**catch-all}", async httpContext =>
                {
                    var destination = "https://y.y.y.y:6000";
                    if (httpContext.Request.Path.StartsWithSegments("/session1"))
                    {
                        destination = "https://y.y.y.y:6001";
                    }
                    else if (httpContext.Request.Path.StartsWithSegments("/session2"))
                    {
                        destination = "https://y.y.y.y:6002";
                    }

                    var error = await forwarder.SendAsync(httpContext, destination, httpClient, requestOptions, transformer);
                    // Check if the proxy operation was successful
                    if (error != ForwarderError.None)
                    {
                        var errorFeature = httpContext.Features.Get<IForwarderErrorFeature>();
                        var exception = errorFeature.Exception;
                    }
                });
```

When working with direct forwarding, how you decide which path maps to which destination is completely up to you.

**Comment by TechAspirant** [comment]
Thanks, I was trying to add Transforms programmatically in case of direct forwarding like below.
How can I add 'PathRemovePrefix' transform programmatically ?

Via appsettings.json
```
"Transforms": [
          { "PathRemovePrefix": "/Session1" },
          {
            "RequestHeader": "X-Forwarded-Prefix",
            "Set": "/Session1"
          }
        ]
```
Via Code
private class CustomTransformer : HttpTransformer
{
public override async ValueTask TransformRequestAsync(HttpContext httpContext, HttpRequestMessage proxyRequest, string destinationPrefix)
{
	await base.TransformRequestAsync(httpContext, proxyRequest, destinationPrefix);
	proxyRequest.RequestUri = new Uri(destinationPrefix);
	proxyRequest.Headers.Add("X-Forwarded-Prefix", "/Project01");
}
}

**Comment by Tratcher** [comment]
One option is to do this:
https://github.com/microsoft/reverse-proxy/blob/9cc305e83523841fbcc164e056e55e58691fa570/testassets/ReverseProxy.Direct/Startup.cs#L43-L49

The other is to do simple transforms in code like you're doing. Trimming the request path looks something like this:
```
	await base.TransformRequestAsync(httpContext, proxyRequest, destinationPrefix);        
	proxyRequest.RequestUri = new Uri(destinationPrefix + httpContext.Request.Path.ToString().SubString("/Project01".Length));
	proxyRequest.Headers.Add("X-Forwarded-Prefix", "/Project01");
```

**Comment by samsp-msft** [comment]
No comment in 10d, closing. Please re-open if its still an issue.
