### ISSUE TITLE
[HTTP/2] Exception in POST with 100-Continue when server returns 4XX before reading the request body

### ISSUE THREAD

**Issue by alnikola** [microsoft/reverse-proxy#1200]
While implementing, the functional tests for Except: 100-Continue scenarios, it was discovered that in some cases the server can resets the HTTP/2 stream with the error code 'PROTOCOL_ERROR' that is propagated as `IOException` on the original client. This happens when the test returns a 4XX error without reading the request body first. The issue can be reproduced by [this test](https://github.com/microsoft/reverse-proxy/blob/c67c25b7b14165d0c3b406b71e6145238dca86fc/test/ReverseProxy.FunctionalTests/Expect100ContinueTests.cs) using the following test arguments:

1. proxyProtocol: Http1, destProtocol: Http2, useContentLength: True, hasResponseBody: True, destResponseCode: 400
```
System.Net.Http.HttpRequestException : Error while copying content to a stream.
    ---- System.IO.IOException : The response ended prematurely.
```
2. proxyProtocol: Http2, destProtocol: Http2, useContentLength: True, hasResponseBody: True, destResponseCode: 400
```
System.Net.Http.HttpRequestException : Error while copying content to a stream.
    ---- System.IO.IOException : The request was aborted.
    -------- System.Net.Http.Http2StreamException : The HTTP/2 server reset the stream. HTTP/2 error code 'PROTOCOL_ERROR' (0x1).
```

**Comment by alnikola** [comment]
The fix is applied in the runtime's main branch.

**Comment by karelz** [comment]
@alnikola what are we tracking by this issue then? Should we make the test conditional to run on 7.0+?
Anything else left?

**Comment by alnikola** [comment]
We need:
1. Add the relevant tests
2. Make them run on 7.0+ only because they will fail on older versions

**Comment by karelz** [comment]
Ah, I thought you already added some tests ... that makes sense.
Pity we don't have "Type: Tests" label ...

**Comment by Tratcher** [comment]
How about `Type: Task`?
