### ISSUE TITLE
Support for HTTP/3

### ISSUE THREAD

**Issue by samsp-msft** [microsoft/reverse-proxy#1208]
Now that HTTP/3 support is included in Kestrel and HttpClient in Preview 7 of .NET 6, we should make sure that YARP will support HTTP/3.

> **Note: HTTP/3 support is dependent on support from the underlying .NET**
> YARP is going to require at least .NET 6, possibly .NET 7 depending on what issues are found and where in the stack they need to be fixed. The HTTP/3 RFC is not yet final, and so may also require additional changes. The support for HTTP/3 in .NET 6 is preview, so is not considered complete, and there will likely be issues as it gets stressed. HTTP/3 support may be updated by patches to .NET 6 but that is not guaranteed.  

In conversations amongst the team, we think there is a possibility it might just work if http/3 is [enabled](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/http3?view=aspnetcore-6.0) for Kestrel and HttpClient, but the devil is going to be in the detail. 

Things that need to be checked:
- [ ] Does header filtering account correctly for HTTP/3
- [x] Connection count management accounts for the fact that you *should* only need 1 http/3 connection, as multiple requests should be multiplexable
- [x] What happens if an upgrade fails due to firewalls preventing QUIC connections

**Comment by karelz** [comment]
Triage: It should just work in theory -- we should give it a try. Even on .NET 6.0.

**Comment by Tratcher** [comment]
There are a few spots where we explicitly check for HTTP/2 / gRPC that might not be forward compatible with HTTP/3.
https://github.com/microsoft/reverse-proxy/blob/95c0b15c95252330d481184a9a99ff998acff2d9/src/ReverseProxy/Forwarder/HttpForwarder.cs#L111

**Comment by MihaZupan** [comment]
We have some logic that's specific to HTTP/2 in `HttpForwarder`:
https://github.com/microsoft/reverse-proxy/blob/b6477b184191613db69c2826611c392cde07ba62/src/ReverseProxy/Forwarder/HttpForwarder.cs#L112

Should this be updated to handle `Http2OrGreater`?

It looks like it's also used in our downgrade log:
https://github.com/microsoft/reverse-proxy/blob/b6477b184191613db69c2826611c392cde07ba62/src/ReverseProxy/Forwarder/HttpForwarder.cs#L138-L143

This should likely be updated to notify on downgrade from HTTP/3 as well.
