### ISSUE TITLE
WebSockets insights

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#1209]
```
EstablishedTime
ClientCloseTime
ServerCloseTime
CleanupTime
ClientTcpDisconnectTime
MessagesRead
MessagesWritten
BytesRead
BytesWritten
```

Some systems like ARR give you the above stats at the end of a WebSocket request. Today with YARP you'd only be able to get the following because WebSockets are proxied in an opaque way:
```
EstablishedTime (request start time)
BytesRead
BytesWritten
CleanupTime (request end time)
```

To get others we'd have to parse out the WebSocket frames, count messages, and look for the close messages in each direction. We do not want to fully parse messages, or deal with other complexities like masking or compression, so we should not try to do anything based on the full WebSocket API.

Proposal:
- Create an opt-in middleware.
- Have it wrap and replace the IHttpUpgradeFeature kindof like what the [WebSockets middleware](https://github.com/dotnet/aspnetcore/blob/d2c48ca1a7d97ab136dcdf029e96e38ebb16ba21/src/Middleware/WebSockets/src/WebSocketMiddleware.cs#L68-L71) does, except without implementing the IHttpWebSocketFeature.
- On upgrade, verify a WebSockets were negotiated, and then return a wrapper stream around the opaque upgrade stream.
- The wrapper stream acts as a pass through observer and doesn't have its own buffers.
  - The Read code path observes the read result, tracks the frame boundaries, counts the messages, and looks for close frames.
  - The Write code path observes the write calls, tracks the frame boundaries, counts the messages, and looks for close frames.
- Emit the event data at the end of the request.

**Comment by karelz** [comment]
Triage: It is blocking one of the v1 customers. We need it.
Should be fairly straightforward.
