### ISSUE TITLE
Kubernetes MessageConfigProvider Doesn't Support Multiple Ingress

### ISSUE THREAD

**Issue by archonandrewhunt** [microsoft/reverse-proxy#1210]
### Describe the bug
Right now if you configure multiple ingress the kubernetes protocol only updates the config to the last message received from the controller. Fundamentally this issue seems to stem from the fact that the `MessageConfigProvider` class as it is implemented today does not handle incremental updates to the config as they are provided. Furthermore, the controller reconciler only ever sends `Update` events, there is no handling should an ingress go away.

### To Reproduce
1. Configure two separate ingresses
2. Only one of the ingress will actually end up configured on the yarp-ingress service.

**Comment by archonandrewhunt** [comment]
Seems like the RouteId being set in `YarpParser` is also not right. It's using the path, which in my case is just "/" on multiple ingresses. This results in the route getting overwritten.

It also seems to be creating multiple routes with the same config when you have an ingress pointing to a cluster of multiple instances.

See the YARP config generated in the case of a single ingress with 2 instances in the deployment:

```{
  "MessageType": "Update",
  "Key": "default:deploymentname",
  "Routes": [
    {
      "RouteId": "/",
      "Match": {
        "Methods": null,
        "Hosts": [
          "hostnamexyxz.com"
        ],
        "Path": "/{**catch-all}",
        "Headers": null
      },
      "Order": null,
      "ClusterId": "deploymentname:80",
      "AuthorizationPolicy": null,
      "CorsPolicy": null,
      "Metadata": null,
      "Transforms": null
    },
    {
      "RouteId": "/",
      "Match": {
        "Methods": null,
        "Hosts": [
          "hostnamexyxz.com"
        ],
        "Path": "/{**catch-all}",
        "Headers": null
      },
      "Order": null,
      "ClusterId": "deploymentname:80",
      "AuthorizationPolicy": null,
      "CorsPolicy": null,
      "Metadata": null,
      "Transforms": null
    }
  ],
  "Cluster": [
    {
      "ClusterId": "deploymentname:80",
      "LoadBalancingPolicy": null,
      "SessionAffinity": null,
      "HealthCheck": null,
      "HttpClient": null,
      "HttpRequest": null,
      "Destinations": {
        "http://172.17.248.102:80": {
          "Address": "http://172.17.248.102:80",
          "Health": null,
          "Metadata": null
        },
        "http://172.17.248.21:80": {
          "Address": "http://172.17.248.21:80",
          "Health": null,
          "Metadata": null
        }
      },
      "Metadata": null
    }
  ]
}```

**Comment by dpbevin** [comment]
@archonandrewhunt could you post the two ingress yaml files please?

**Comment by majstorki88** [comment]
+1 for this, same scenario on my side.

**Comment by archonandrewhunt** [comment]
@dpbevin here's a fully reproducible example which I just tested against the latest ingress-controller, and ingress sample locally. In my testing, I am only able to get yarp to route me to repro-deployment-2.

https://gist.github.com/archonandrewhunt/9f437e106dbe1fa05448eefa363ae878 

Please note I am also discussing this similar issue with @Tratcher in my draft PR #1218 where I fix this behaviour. Seems to be some confusion about current expected behaviour vs what is actually happening.

**Comment by dpbevin** [comment]
Here's another draft PR that I've got working locally: https://github.com/microsoft/reverse-proxy/pull/1253

**Comment by dpbevin** [comment]
This should be fixed by #1253.

**Comment by dpbevin** [comment]
The fix has been merged. This should be good to close now.

**Comment by archonandrewhunt** [comment]
Can confirm this has been fixed.
