### ISSUE TITLE
Is it possible to override the Host value of request?

### ISSUE THREAD

**Issue by mohsenShakiba** [microsoft/reverse-proxy#1212]
### Describe the bug
I want to override the Host value of the request programmatically. 
The transform `RequestHeaderOriginalHost` will set the original host but what if I want to change the value to something else?
I've tried using `WithTransformRequestHeader("Host", "example.net")` but it doesn't work.
I've also consulted the documentation but I couldn't find anything.

**Comment by Tratcher** [comment]
Which preview are you on? We fixed some issues here in preview11:
https://github.com/microsoft/reverse-proxy/issues/859

**Comment by mohsenShakiba** [comment]
My bad, I'll update the package
