### ISSUE TITLE
path percent encoding - wierdness

### ISSUE THREAD

**Issue by schmitch** [microsoft/reverse-proxy#1219]
### Describe the bug
currently if a path is (double) percent encoded, it will be decoded by yarp, but unfortunatly yarp will try to sent the unencoded path to the backend server

### To Reproduce
send the following path:

```
GET /encoded%2520path
```

yarp should now send the following to the backend:

```
GET /encoded%2520path
```

what it does send:
```
GET /encoded%20path
```

whoever we actually used double percent encoding in some places of our code and this completly breaks it

it would be good if there was a option to keep the path as-is.

btw. we can fix it by using (or by using a HttpTransformer):
```c#
    public class PercentEncodingTransform : RequestTransform
    {
        public override ValueTask ApplyAsync(RequestTransformContext context)
        {
            context.ProxyRequest.RequestUri = new Uri(
                new Uri(context.DestinationPrefix),
                Uri.EscapeUriString(context.HttpContext.Request.GetEncodedPathAndQuery()));
            return ValueTask.CompletedTask;
        }
    }
```

but it's probably strange that a proxy rewrite's the path. (btw. we use double percent encoding because the framework's and routers which we use is a little bit wierd and this fixed it)

not sure if that is even fixable since it depends on `PathString` which always change the behavior. maybe a good idea would be to expose a RawRequestPath in dotnet and allow yarp to have a config to use RawRequestPath instead of `context.Path` for the backend

### Further technical details

- 1.0.0-preview12
- platform: macOS

**Comment by Tratcher** [comment]
Yeah, we're looking into some round tripping issues here.

For triage: this needs to be mitigated for 1.0. This might help:
https://github.com/microsoft/reverse-proxy/commit/dc82e060e95498fdb0d16d426688c4848a3c893a

**Comment by schmitch** [comment]
@Tratcher took me a while to test it, but your branch works, fyi.
