### ISSUE TITLE
Is there a simpler way to customize the configuration if generics are supported

### ISSUE THREAD

**Issue by saber-wang** [microsoft/reverse-proxy#1248]
### What should we add or change to make your life better?
  Configure inverse sequences and get support generics
### Why is this important to you?
  At present, when you want to customize the proxy behavior or middleware, some customization items can only be obtained from metadata. If it is a complex object, each request also needs to be deserialized.
  Possible related APIs:
```c#
  public interface IProxyConfigProvider<TRouteConfig,TClusterConfig> where TRouteConfig:RouteConfig,where TClusterConfig:ClusterConfig
    {
        IProxyConfig<TRouteConfig,TClusterConfig> GetConfig();
    }

  HttpContext.GetReverseProxyFeature<CustomizeRouteConfig,CustomizeClusterConfig>()
```
Or is there any other recommended implementation method?

**Comment by Tratcher** [comment]
Design: That generic would be viral through the entire code base.

One compromise we've tried is to cache the deserialized metadata. See:
https://github.com/microsoft/reverse-proxy/blob/d31b3886d3c5150ed46b2c1ffb4813e6c77b0588/src/ReverseProxy/Utilities/ParsedMetadataEntry.cs#L9
https://github.com/microsoft/reverse-proxy/blob/c68da3c0c8df08a1f661fec6ace9fa54aa16da5a/src/ReverseProxy/Health/TransportFailureRateHealthPolicy.cs#L32
https://github.com/microsoft/reverse-proxy/blob/c68da3c0c8df08a1f661fec6ace9fa54aa16da5a/src/ReverseProxy/Health/TransportFailureRateHealthPolicy.cs#L60
