### ISSUE TITLE
HttpForwarder can return 400 Bad Request

### ISSUE THREAD

**Issue by narcis-ro** [microsoft/reverse-proxy#1249]
### Describe the bug
During investigation of some production issues, we've noticed that sometimes the reverse-proxy can return 400 Bad Request.

This can be seen in the [source code](https://github.com/microsoft/reverse-proxy/blob/main/src/ReverseProxy/Forwarder/HttpForwarder.cs#L426) of `HttpForwarder` as well as in it's tests [here](https://github.com/microsoft/reverse-proxy/blob/main/test/ReverseProxy.Tests/Forwarder/HttpForwarderTests.cs#L1041).

The api client expects 400 Bad Request to have a particular format. The reverse proxy should not never return these type of client  http error codes.

### Further technical details

- Include the version of the packages you are using
- The platform (Linux/macOS/Windows)

**Comment by Tratcher** [comment]
That code path is supposed to handle client disconnect scenarios, the status code is more for logging purposes. Are you actually seeing that 400 reach the client?

**Comment by narcis-ro** [comment]
@Tratcher after further investigation it turned the logs were misinterpreted the gateway does return 502. Sorry for the wrong info.,
