### ISSUE TITLE
YARP Direct Proxy - default HttpForwarder behavior not retained

### ISSUE THREAD

**Issue by AAATechGuy** [microsoft/reverse-proxy#1270]
### Describe the bug

From the link https://github.com/microsoft/reverse-proxy/tree/main/samples/ReverseProxy.Direct.Sample, 
![image](https://user-images.githubusercontent.com/3484074/135707084-63a0f26b-4900-43c2-9554-2c86e64ec8a9.png)

This is not true. 

1. When using the HttpForwarder class directly, removing the original Host header and adding X-Forwarded-For, are not done by default. 
2. To unblock, cannot reuse existing code, for e.g., `TransformBuilder.Create` OR `StructuredTransformer`, because they are marked as internal. I will have to reimplement the logic for X-Forwarded-For etc. ?

### To Reproduce

This is the configuration used. 
```
app.MapWhen(
                httpContext => true,
                app =>
                {
                    app.UseRouting();
                    app.UseEndpoints(endpoints =>
                    {
                        endpoints.Map(
                            "/{**catch-all}",
                            async httpContext => await forwarder.SendAsync(httpContext, ReverseProxyDestinationPrefix, httpClient, forwarderRequestConfig, HttpTransformer.Default));
                    });
                });
```

Sending a WCF request to `https://10.214.72.87:3089/clientcenter/mt` which needs to be redirected via YARP on asp.net core towards `https://localhost:3489/clientcenter/mt` WCF service throws following error: 
```
<BODY>
	<h2>Bad Request - Invalid Hostname</h2>
	<hr>
	<p>HTTP Error 400. The request hostname is invalid.</p>
</BODY>
```

I also noticed `X-Forwarded-For` is not updated for incoming request at 3489. 

### Further technical details

- Include the version of the packages you are using
Using NuGet `<PackageReference Update="Yarp.ReverseProxy" Version="1.0.0-preview.12.21451.3" />`

- The platform (Linux/macOS/Windows)
Windows Server 2019

- Tried following, but doesn't seem to work for direct proxy. 
```
        public static IServiceCollection ConfigureService_ReverseProxy(this IServiceCollection services)
        {
            services.AddReverseProxy()
                .AddTransforms(builderContext =>
                {
                    builderContext.CopyRequestHeaders = true;
                    builderContext.AddOriginalHost(useOriginal: false);
                    builderContext.UseDefaultForwarders = true;
                });

            return services;
        }
```

- I was able to fix the error with following though, 
```
        private class RedirectHttpTransformer : HttpTransformer
        {
            public override async ValueTask TransformRequestAsync(HttpContext httpContext, HttpRequestMessage proxyRequest, string destinationPrefix)
            {
                await base.TransformRequestAsync(httpContext, proxyRequest, destinationPrefix);
                proxyRequest.Headers.Host = null;
            }
        }
```
However, I'm unable to use `X-Forwarded-For` extensions/ existing code, in a meaningful way.

**Comment by Tratcher** [comment]
This was a recent fix that hasn't shipped in a preview yet. https://github.com/microsoft/reverse-proxy/issues/1093. https://github.com/microsoft/reverse-proxy/pull/1246.  You can get that version from the daily builds:
https://github.com/microsoft/reverse-proxy/blob/main/docs/DailyBuilds.md

Alternatively, you can add the transforms yourself like this:
https://github.com/microsoft/reverse-proxy/blob/c5f1607cd6142ed066a3f4e4fb1362ca09fd1fe7/testassets/ReverseProxy.Direct/Startup.cs#L43-L49
