### ISSUE TITLE
Remove path pattern using transform

### ISSUE THREAD

**Issue by TechAspirant** [microsoft/reverse-proxy#1275]
How can I remove path pattern using transform ?
/foo/Id01
/foo/Id02
/foo/Id03
```json
"Route1": {
        "ClusterId": "Cluster_01",
        "Match": {
          "Path": "/foo/{**catch-all}"
        },
        "Transforms": [
          { "PathRemovePrefix": "/foo/Id{Iteration Number}" } 
        ]
        }
```

**Comment by Tratcher** [comment]
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-5.0#complex-segments
Try this:
```
    "Route1": {
        "ClusterId": "Cluster_01",
        "Match": {
          "Path": "/foo/id{n}/{**catch-all}"
        },
        "Transforms": [
          { "PathPattern": "/{catch-all}" } 
        ]
     }
```

**Comment by TechAspirant** [comment]
Thanks, will check.
Can I add query parameter dynamically say ?Guid=new Guid before forwarding the request to available destination.

**Comment by Tratcher** [comment]
Yes, with a little code.
Start here for adding a request transform:
https://github.com/microsoft/reverse-proxy/blob/95c0b15c95252330d481184a9a99ff998acff2d9/samples/ReverseProxy.Transforms.Sample/Startup.cs#L49

That will have a query you can manipulate:
https://github.com/microsoft/reverse-proxy/blob/95c0b15c95252330d481184a9a99ff998acff2d9/src/ReverseProxy/Transforms/RequestTransformContext.cs#L44
https://github.com/microsoft/reverse-proxy/blob/95c0b15c95252330d481184a9a99ff998acff2d9/src/ReverseProxy/Transforms/QueryTransformContext.cs#L49

**Comment by adityamandaleeka** [comment]
Triage: seems answered

**Comment by suntereo** [comment]
> https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-5.0#complex-segments Try this:
> 
> ```
>     "Route1": {
>         "ClusterId": "Cluster_01",
>         "Match": {
>           "Path": "/foo/id{n}/{**catch-all}"
>         },
>         "Transforms": [
>           { "PathPattern": "/{catch-all}" } 
>         ]
>      }
> ```

This solves it for me
