### ISSUE TITLE
Rename Endpoint, Backend

### ISSUE THREAD

**Issue by Kahbazi** [microsoft/reverse-proxy#128]
Since Endpoint is already a concept in ASP.NET and right now Routes (from config) are being mapped to an Endpoint (ASP.NET) and Endpoints (from config) are referred to backend servers. 

I suggest renaming _Endpoint_ to _Server_ or _Resource_ and renaming _Route_ to _Endpoint_.

So this
```json
"ReverseProxy": {
  "Backends": {
    "backend1": {
      "Endpoints": {
        "Green": {
          "Address": "https://localhost:10001/"
        }
      }
    }
  },
  "Routes": [
    {
      "RouteId": "backend1/route1",
      "BackendId": "backend1",
      "Match": {
        "Methods": [ "GET", "POST" ],
        "Host": "localhost",
        "Path": "/{**catchall}"
      }
    }
  ]
}
```

would change to 
```json
"ReverseProxy": {
  "Backends": {
    "backend1": {
      "Servers": {
        "Green": {
          "Address": "https://localhost:10001/"
        }
      }
    }
  },
  "Endpoints": [
    {
      "EndpointId": "backend1/route1",
      "BackendId": "backend1",
      "Match": {
        "Methods": [ "GET", "POST" ],
        "Host": "localhost",
        "Path": "/{**catchall}"
      }
    }
  ]
}
```

**Comment by Tratcher** [comment]
Yeah, the terminology could be improved, many of these terms are used in too many different contexts.

That said, endpoints is already an overloaded term (used by kestrel, routing, and the proxy). At least routes are a unique term. I don't see renaming routes to endpoints as an improvement.

I would like to rename backend endpoints to something to limit the overloading. Servers is also an overloaded term, we already have a server in the app at the front end. `Destination(s)`? `Backend(s)` could also work if we found a better group name for what we currently call backends (e.g. a group of endpoints).

**Comment by davidni** [comment]
Comparing terminology with other proxies may help:

Product|YARP `Endpoint`|YARP `Backend`|YARP `Route`
-|:-|:-|:-
[Envoy](https://jvns.ca/blog/2018/10/27/envoy-basics/)|`host`|`cluster`|`route`
[Traefik v2](https://docs.traefik.io/routing/services/)|`server`|`service`|`router`
[Ocelot](https://ocelot.readthedocs.io/en/latest/features/routing.html)|`ReRoute.DownstreamHostAndPorts`|--|`ReRoute`

**Comment by guibirow** [comment]
I think *nginx* and *haproxy* terminology should also be taken into account, given they are most used and popular proxies and many people have prior experience with these for many years. Envoy and Traffic just became popular into kubernetes ecosystem, so that t will make easier for people coming from outside k8s to grasp.

Regarding the name change from route to endpoint, I honestly prefer route, given endpoint can be confusing as inbound endpoint or outbound endpoint.

**Comment by davidni** [comment]
@guibirow added based on quick reading of docs (linked to in the table), please advise if anything seems inaccurate.

**Comment by Tratcher** [comment]
An NGinx server does not map to a YARP endpoint, it maps to a Kestrel endpoint.
An NGinx location maps to a YARP endpoint.

**Comment by guibirow** [comment]
The server in NGINX can be misleading, given it is used to define any server, either upstream or downstream, like shown[here](https://www.nginx.com/resources/wiki/start/topics/examples/loadbalanceexample/) and [here](https://www.nginx.com/resources/wiki/start/topics/examples/full/). Probably the right terminology should be `upstream.server`, like you did for ocelot.

**Comment by guibirow** [comment]
```
http {                       // Same as Kestrel

  upstream myproject {       // same as backend
    server 127.0.0.1:8000;   // same as endpoint
    server 127.0.0.1:8001;
    server 127.0.0.1:8002;
    server 127.0.0.1:8003;
  }

  server {             // this concept does not exist here, I've suggested on #134 
    listen 80;
    server_name www.domain.com;
    location / {       //same as route
      proxy_pass http://myproject;
    }
  }
}
```

**Comment by Tratcher** [comment]
From the above data `route` seems like a solid choice.

For `backend` there does not seem to be consistent terms and the only alternative that seems more descriptive is `cluster` since it's explicitly a group of resources.

While `server` does seem to be common to describe backend resources, it's still overloaded and conflicts with the inbound server. `server` might still be better than `endpoint` here since `endpoint` also has internal conflicts with endpoint routing.

**Comment by davidni** [comment]
Have we considered `BackendServer` to replace what we currently call `Endpoint`? A bit more verbose, but also less ambiguous than either `Server` or `Endpoint`.

**Comment by Tratcher** [comment]
Team discussion proposals:
Route -> Route
Backend -> Cluster
Endpoint -> Destination

```
"ReverseProxy": {
  "Clusters": {
    "cluster1": {
      "Destinations": {
        "Destination1": {
          "Address": "https://localhost:10001/"
        },
        "Destination2": {
          "Address": "https://localhost:10002/"
        }
      }
    }
  },
  "Routes": [
    {
      "RouteId": "backend1/route1",
      "ClusterId": "cluster1",
      "Match": {
        "Methods": [ "GET", "POST" ],
        "Host": "localhost",
        "Path": "/{**catchall}"
      }
    }
  ]
}
```

@davidni @kahbazi how's that look?

**Comment by davidni** [comment]
+1 for Route, Destination. But I greatly dislike Cluster due to conflicts with well established terminology for the compute abstraction: `Service Fabric Clusters` are a top level Azure resource. [AKS](https://docs.microsoft.com/en-us/azure/aks/) defines itself in one sentence using the terms `Kubernetes cluster in Azure`.

What's wrong with `Backend`? The terms `Frontend` and `Backend` are pretty self explanatory and common in proxies.

**Comment by Tratcher** [comment]
The preference for cluster over backend was about clarifying it represents a group of resources rather than an individual resource. None of the other terms from the other proxies communicate that. Other suggestions? Or is that not a distinction that needs to be made in the name?

**Comment by Tratcher** [comment]
I decided to write this out narratively to see if it made more sense.

You select a Route and follow it through a ________ to one of many Destinations.
- Backend
- Cluster
- Neighborhood
- Zone
- Domain
- Warren

**Comment by anurse** [comment]
> * Warren

Rathole 😆

I still like Cluster 😄

**Comment by Tratcher** [comment]
Endpoint was renamed to Destination in #150. Now we just need to decide what to do about Backend.

With how much churn renaming Endpoints caused, and the lack of agreement around a good name for Backends, I'm inclined not to change it.

**Comment by davidni** [comment]
I am changing my stance from `greatly dislike` to just `dislike` the name `cluster`. I still think it would create unnecessary confusion due other meanings of `cluster`, but I reckon the confusion would be trivial to address through docs, and hence not such a big deal.
