### ISSUE TITLE
Implement Forwarded Headers

### ISSUE THREAD

**Issue by anurse** [microsoft/reverse-proxy#13]
* X-Forwarded-Proto
* X-Forwarded-Host
* X-Forwarded-For
* X-Client-Cert
* Forwarded (yes, there's a chicken-and-egg problem but I see no reason we can't break that cycle by implementing it).

**Comment by Tratcher** [comment]
Planning notes: We need a minimal implementation of this for preview1. E.g. automatically append forwarders without any configurability.

**Comment by davidni** [comment]
I can help with the minimal implementation. I already have it coded up to append `X-Forwarded-For`, `X-Forwarded-Host`, `X-Forwarded-Host`, `X-Forwarded-Proto`, as well as [RFC7239](https://tools.ietf.org/html/rfc7239) `Forwarded`.

Because of possible URL transformations, we also add a non-standard header with the full original incoming url.

**Comment by Tratcher** [comment]
I did the minimal work for preview1 in #133. Moving this out of the preview1 milestone for further development.

**Comment by Tratcher** [comment]
Design: I expect this to overlap heavily with the request transformation infrastructure we're designing in https://github.com/microsoft/reverse-proxy/issues/21. We wouldn't necessarily ask you to define these headers in config (though nginx does), but we would use the same infrastructure to actually do the transformations.

**Comment by Tratcher** [comment]
Yes this does align with the transforms, but we don't need another middleware to add transforms per request. We can pre build the transforms when building the config for each route/backend, then we can run them per request with minimal overhead.

**Comment by damianh** [comment]
I think you should also consider supporting `X-Forwarded-PathBase`. It is first class supported in ProxyKit for reasons described in this readme: https://github.com/ProxyKit/HttpOverrides . If this deserves it's own issue, let me know.

**Comment by Tratcher** [comment]
@damianh PathBase makes sense, you can't properly generate public urls without it.

**Comment by damianh** [comment]
@Tratcher Yes am aware of the at-startup approach, however I am suggesting per-request should be supported.

**Comment by Tratcher** [comment]
@damianh sending x-forwarded-PathBase was implemented in YARP as part of #225. Filed https://github.com/dotnet/aspnetcore/issues/23263 for receiving it.

**Comment by damianh** [comment]
Excellent!
