### ISSUE TITLE
YARP v1.0 RC has been published

### ISSUE THREAD

**Issue by samsp-msft** [microsoft/reverse-proxy#1314]
With a goal to releasing YARP 1.0 in the November 2021 timeframe, we have just published the [1.0 Release Candidate](https://github.com/microsoft/reverse-proxy/releases/tag/v1.0.0-rc.1) which can be downloaded from [Nuget](https://www.nuget.org/packages/Yarp.ReverseProxy/1.0.0-rc.1.21520.4). What this means is that we consider YARP to be feature complete for v1, and are not expecting any more API changes at this point.

Please test/deploy this build as its very very close to what we expect to release for 1.0. At this point we are looking for ship blockers, or issues that have to be fixed for 1.0, so as they say at weddings "Speak up now or forever hold your peace."&#x2020;

A big shout out and thank you to @Tratcher  & @MihaZupan for the flurry of activity the last week to get us to this stage.

Next step: release.

_&#x2020; Ok, it's not quite that bad, we can service/update 1.0, but we generally only service for security issues or really bad bugs._

**Comment by karelz** [comment]
RC shipped, we are close to GA, closing.
