### ISSUE TITLE
Change ILoadBalancingPolicy to be async

### ISSUE THREAD

**Issue by lischach** [microsoft/reverse-proxy#1345]
### What should we add or change to make your life better?

In LoadBalancingMiddleware there is a call to PickDestination method from ILoadBalancingPolicy.

https://github.com/microsoft/reverse-proxy/blob/52b31103f6a25f881282d7ceb5f285ca9f09d26e/src/ReverseProxy/LoadBalancing/LoadBalancingMiddleware.cs#L53

 
can you change this to be async method?

### Why is this important to you?
we have some calls there to external API to decide the destination according to tenant geo region and we think using sync method might cause scaling\resources issues later

**Comment by Tratcher** [comment]
Making an external API call to load balance every request will also be a significant scaling limiter.

Possible alternatives:
- Caching and syncing in the background
- Custom middleware. The LoadBalancingMiddleware is there for convenience, it doesn't provide any unique functionality.
https://github.com/microsoft/reverse-proxy/blob/a6b19a913dd5f6c0d6b68e923d0f36baa6e2f037/samples/ReverseProxy.Code.Sample/Startup.cs#L100-L119

**Comment by karelz** [comment]
Triage: There are workarounds.
We do not believe it is a good idea to do it directly in YARP, because it will create too much pressure on pipeline and would create a bottleneck.
Given that it would be a breaking change, we are unlikely to take it after 1.0.

**Comment by lischach** [comment]
Thank you @Tratcher - your suggestion solved my issue
