### ISSUE TITLE
Hi, how to config multiple workers/threads for the listener?

### ISSUE THREAD

**Issue by ianrenUipath** [microsoft/reverse-proxy#1349]
### Some details

**How many backends are in your application?**

- [x] 1-2

**How do you host your application?**

- [x] Azure VMs

Hi, how to config multiple workers/threads for the listener?

Like in Envoy proxy (https://www.envoyproxy.io/docs/envoy/latest/operations/cli#cmdoption-concurrency), there is "--concurrency " so that user can config # of threads/workers for listeners.

**Comment by karelz** [comment]
@ianrenUipath can you please help me understand why do you need the config?
Is the default not working well for you?
Or what is your motivation?

**Comment by Tratcher** [comment]
> Once a connection is accepted by a listener, the connection spends the rest of its lifetime bound to a single worker thread.

ASP.NET and YARP do not work like this. Threading in .NET is highly dynamic. Async work is queued to the threadpool and additional threadpool threads are created on-demand.

There should be no need to configure concurrency settings in ASP.NET/YARP unless you're hitting some upper load limits on your hardware and want to limit how many connections and requests are accepted. See settings like:
- [MaxConcurrentConnections](https://github.com/dotnet/aspnetcore/blob/c440ebcf49badd49f0e2cdde1b0a74992af04158/src/Servers/Kestrel/Core/src/KestrelServerLimits.cs#L210-L222)
- [MaxConcurrentUpgradedConnections](https://github.com/dotnet/aspnetcore/blob/c440ebcf49badd49f0e2cdde1b0a74992af04158/src/Servers/Kestrel/Core/src/KestrelServerLimits.cs#L235-L248)
- [MaxStreamsPerConnection](https://github.com/dotnet/aspnetcore/blob/c440ebcf49badd49f0e2cdde1b0a74992af04158/src/Servers/Kestrel/Core/src/Http2Limits.cs#L26-L32)
- [SocketTransportOptions](https://github.com/dotnet/aspnetcore/blob/main/src/Servers/Kestrel/Transport.Sockets/src/SocketTransportOptions.cs)

**Comment by ianrenUipath** [comment]
> @ianrenUipath can you please help me understand why do you need the config? Is the default not working well for you? Or what is your motivation?

I am doing a load testing to compare the performance of YARP and some other reverse proxies. like envoy.

On my proxy server, I should make use of all the cores to listen to the requests.

**Comment by ianrenUipath** [comment]
> > Once a connection is accepted by a listener, the connection spends the rest of its lifetime bound to a single worker thread.
> 
> ASP.NET and YARP do not work like this. Threading in .NET is highly dynamic. Async work is queued to the threadpool and additional threadpool threads are created on-demand.
> 
> There should be no need to configure concurrency settings in ASP.NET/YARP unless you're hitting some upper load limits on your hardware and want to limit how many connections and requests are accepted. See settings like:
> 
> * [MaxConcurrentConnections](https://github.com/dotnet/aspnetcore/blob/c440ebcf49badd49f0e2cdde1b0a74992af04158/src/Servers/Kestrel/Core/src/KestrelServerLimits.cs#L210-L222)
> * [MaxConcurrentUpgradedConnections](https://github.com/dotnet/aspnetcore/blob/c440ebcf49badd49f0e2cdde1b0a74992af04158/src/Servers/Kestrel/Core/src/KestrelServerLimits.cs#L235-L248)
> * [MaxStreamsPerConnection](https://github.com/dotnet/aspnetcore/blob/c440ebcf49badd49f0e2cdde1b0a74992af04158/src/Servers/Kestrel/Core/src/Http2Limits.cs#L26-L32)
> * [SocketTransportOptions](https://github.com/dotnet/aspnetcore/blob/main/src/Servers/Kestrel/Transport.Sockets/src/SocketTransportOptions.cs)

Thanks! From [MaxConcurrentConnections](https://github.com/dotnet/aspnetcore/blob/c440ebcf49badd49f0e2cdde1b0a74992af04158/src/Servers/Kestrel/Core/src/KestrelServerLimits.cs#L210-L222), I think when a large number of concurrent requests hitting the YARP, multiple threads will be started to handle concurrent requests. Am I right?

**Comment by Tratcher** [comment]
Correct, ASP.NET & YARP will automatically scale up to handle load. 

See https://aka.ms/aspnet/benchmarks page 16 (Proxies) for performance comparisons.

**Comment by ianrenUipath** [comment]
Thanks!
