### ISSUE TITLE
File Scoped Namespaces

### ISSUE THREAD

**Issue by Kahbazi** [microsoft/reverse-proxy#1351]
Is there plan to use C# 10 File Scoped Namespaces?

**Comment by Tratcher** [comment]
FYI we decided to do this for aspnetcore. https://github.com/dotnet/aspnetcore/pull/38076 

This requires the .NET 6 SDK, which we are now using.

**Comment by MihaZupan** [comment]
I assume this change is only visible internally - consumers of our packages would still be able to use the 5.0 SDK and not be forced to 6.0?

**Comment by Tratcher** [comment]
Right, this change is only local/style. We'll have to be careful about what other C# 10 features we use though, especially ones that affect public API.

**Comment by karelz** [comment]
Triage: Yes for code. We should leave samples as they are -- see comment  in PR #1352

**Comment by Tratcher** [comment]
- [x] ReverseProxy
- [x] Tests
- [ ] Kubernetes
- [ ] OperatorFramework
- [ ] TestAssets
- [ ] ~Samples & Docs~ Not while we support 3.1/5.0.
- [ ]
