### ISSUE TITLE
Do we support UnixSocket forwarding?

### ISSUE THREAD

**Issue by Aloento** [microsoft/reverse-proxy#1369]
Currently, "Clusters" -> "Address" should be a URL like "http://www.example.com".
So I want to ask that could this filled with something like "path/to/unix_socket"?

**Comment by Tratcher** [comment]
Not currently. @MihaZupan could they do this themselves using the SocketsHttpHandler.ConnectCallback?
https://github.com/dotnet/runtime/blob/26c045b556010bb68fc21722ed6bf76683028d79/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/SocketsHttpHandler.cs#L398

**Comment by MihaZupan** [comment]
Yes, it should work with the `ConnectCallback`

Some (untested) code for example:
```c#
services.AddReverseProxy()
    .LoadFromConfig(_configuration.GetSection("ReverseProxy"))
    .ConfigureHttpClient((context, handler) =>
    {
        if (context.NewMetadata.TryGetValue("UnixSocket", out var unixSocket))
        {
            handler.ConnectCallback = async (context, cancellation) =>
            {
                var socket = new Socket(AddressFamily.Unix, SocketType.Stream, ProtocolType.IP) { NoDelay = true };
                try
                {
                    await socket.ConnectAsync(new UnixDomainSocketEndPoint(unixSocket), cancellation);
                    return new NetworkStream(socket, ownsSocket: true);
                }
                catch
                {
                    socket.Dispose();
                    throw;
                }
            };
        }
    });
```

And add the `UnixSocket` to the cluster's metadata:
```json
"MetaData": {
  "UnixSocket": "path/to/unix_socket"
}
```

**Comment by Tratcher** [comment]
Nice.

> And add the `UnixSocket` to the cluster's metadata:

You mean the destination's metadata?

**Comment by Aloento** [comment]
@MihaZupan 
I am thinking since YARP can be configured HttpClient, that WebHost can not be configured HttpClient?
Because I see that ConnectCallback is required to return a Stream, so can a MemoryStream be passed from Kestrel in the same process?

My application scenario is a program with multiple Kestrel are responsible for different Web, the same program’s YARP in front of the responsible forwarding. UnixSocket is a good solution but not the best, so I asked.

**Comment by samsp-msft** [comment]
> My application scenario is a program with multiple Kestrel are responsible for different Web, the same program’s YARP in front of the responsible forwarding. UnixSocket is a good solution but not the best, so I asked.

If YARP is in the same process as the web server, then YARP routes will combine with ASP.NET routes that are also configured against the same endpoint, so they don't need to be routed through YARP. AFAIK you could also delegate a request to ASP.NET to handle it if you need it to.

**Comment by Aloento** [comment]
Maybe there is something wrong with my description.
In my case, there are multiple IHosts listening to different endpoints in a .NET VM. This is a bit like Web Hosting (cPanel).
So this obviously needs a proxy.
I'll try to find a better solution, thanks, guys.

**Comment by MithunChopda** [comment]
> [@MihaZupan](https://github.com/MihaZupan) I am thinking since YARP can be configured HttpClient, that WebHost can not be configured HttpClient? Because I see that ConnectCallback is required to return a Stream, so can a MemoryStream be passed from Kestrel in the same process?
> 
> My application scenario is a program with multiple Kestrel are responsible for different Web, the same program’s YARP in front of the responsible forwarding. UnixSocket is a good solution but not the best, so I asked.

The solution suggested by @MihaZupan  works but with minor change. This is for Windows. I have not tested it on Linux.
The only changes are
- On windows, the path should not start with http://unix: but should be only the path of socket file. There some documents that suggest using http://unix:<path to socket file>.
- Setting NoDelay fails with unsupported configuration exception. So remove it.
