### ISSUE TITLE
Modifying responses from proxied requests

### ISSUE THREAD

**Issue by davidkeaveny** [microsoft/reverse-proxy#1371]
Is it possible to modify the response from a proxied request? For instance, if I am implementing a level 3 REST API which returns hypermedia as part of the response, and certain endpoints use YARP to proxy the request to a microservice API, can YARP update the returned hypermedia to use the hostname of the main API rather than the hostname of the microservice?

So, imagine I call my REST API using `GET https://my.api.com/get-some-data`, this gets proxied through to `http://service-a.internal.network/get-some-data` (because I am SSL terminating at the load balancer), which returns:

```
HTTP/1.1 200 OK
{
  "id": 12345,
  "links": {
    "self": { "href": "http://service-a.internal.network/get-some-data/12345" }
}
```

I would like YARP to be able modify the response so that it becomes:

```
HTTP/1.1 200 OK
{
  "id": 12345,
  "links": {
    "self": { "href": "https://my.rest.api/get-some-data/12345" }
}
```

**Comment by Tratcher** [comment]
Modifying the response body is not directly supported and would be discouraged for this scenario regardless.

https://microsoft.github.io/reverse-proxy/articles/middleware.html#what-not-to-do-with-middleware

Instead, use https://microsoft.github.io/reverse-proxy/articles/transforms.html#x-forwarded to generate the correct urls in the destination app.
