### ISSUE TITLE
Net 6. It's time to update the document. The direct agent will not modify this place without this attribute.

### ISSUE THREAD

**Issue by bbhxwl** [microsoft/reverse-proxy#1380]
Net 6. It's time to update the document. The direct agent will not modify this place without this attribute.

![image](https://user-images.githubusercontent.com/26525599/141655719-4f143204-79ef-42eb-8a25-5965bdecd447.png)

**Comment by karelz** [comment]
@bbhxwl can you please clarify what you mean?
Which agent, which attribute?

**Comment by bbhxwl** [comment]
> @bbhxwl can you please clarify what you mean? Which agent, which attribute?

An example of an online document cannot run on net6. Because there is no forwarder object

![image](https://user-images.githubusercontent.com/26525599/141675333-69088779-dcb6-4ffe-9a3f-f30d901e5beb.png)
![image](https://user-images.githubusercontent.com/26525599/141675397-7528912f-71e9-40e5-8e64-b68274dff3ab.png)

**Comment by bbhxwl** [comment]
Net6 does not have the following method. Cannot define ihttpforwarder

public void Configure(IApplicationBuilder app, IHttpForwarder forwarder)

**Comment by Kahbazi** [comment]
Since you are using the new minimal hosting and you have to get `IHttpForwarder` yourself from the `ServiceProvider`.

```csharp
var forwarder = app.Services.GetService<IHttpForwarder>();
app.Map("/{**catch-all}", async httpContext =>
{
    var error = await forwarder.SendAsync(...);
    ...
}
```

**Comment by bbhxwl** [comment]
> Since you are using the new minimal hosting and you have to get `IHttpForwarder` yourself from the `ServiceProvider`.
> 
> ```cs
> var forwarder = app.Services.GetService<IHttpForwarder>();
> app.Map("/{**catch-all}", async httpContext =>
> {
>     var error = await forwarder.SendAsync(...);
>     ...
> }
> ```
In addition, why doesn't matching routing work? I want to keep my controller and areas. Dynamic reverse proxy


![image](https://user-images.githubusercontent.com/26525599/141676194-9aa9208d-6b03-48e0-bad7-3ac4eddd5d4e.png)
![image](https://user-images.githubusercontent.com/26525599/141676210-15249812-98da-4a4b-be63-5ed70fe13d07.png)
![image](https://user-images.githubusercontent.com/26525599/141676247-3848888c-800d-4ad5-8ab1-8a8178672185.png)
![image](https://user-images.githubusercontent.com/26525599/141676254-42eefcb1-80be-459b-b6ba-0bbe2ca85b65.png)

**Comment by bbhxwl** [comment]
![image](https://user-images.githubusercontent.com/26525599/141676272-3259f8b2-1d0d-4dca-b402-ec9441a31b7c.png)

**Comment by bbhxwl** [comment]
> Since you are using the new minimal hosting and you have to get `IHttpForwarder` yourself from the `ServiceProvider`.
> 
> ```cs
> var forwarder = app.Services.GetService<IHttpForwarder>();
> app.Map("/{**catch-all}", async httpContext =>
> {
>     var error = await forwarder.SendAsync(...);
>     ...
> }
> ```

I want to enter home / index to change my rules, but I don't seem to set the routing template. Only when all / {* * catch all} is set, other routes are 404

**Comment by bbhxwl** [comment]
![image](https://user-images.githubusercontent.com/26525599/141676330-63444ee9-457a-437d-a53c-ae4d47ca3d29.png)

**Comment by bbhxwl** [comment]
@karelz

**Comment by Tratcher** [comment]
You can also inject the IHttpForwarder directly into your action:
```
app.Map("/{**catch-all}", async (HttpContext httpContext, IHttpForwarder forwarder) =>
```

**Comment by Tratcher** [comment]
Please don't share screenshots, instead copy and past the actual code, urls, and error messages.

**Comment by Tratcher** [comment]
> In addition, why doesn't matching routing work? I want to keep my controller and areas. Dynamic reverse proxy
> 
> ![image](https://user-images.githubusercontent.com/26525599/141676194-9aa9208d-6b03-48e0-bad7-3ac4eddd5d4e.png) ![image](https://user-images.githubusercontent.com/26525599/141676210-15249812-98da-4a4b-be63-5ed70fe13d07.png) ![image](https://user-images.githubusercontent.com/26525599/141676247-3848888c-800d-4ad5-8ab1-8a8178672185.png) !

Your request reached nginx so your request was routed. Note that matching the "hello" route does not remove "hello" from the request path before routing. Is your nginx app prepared to handle "hello"? If not you can remove that from the request path by adding a transform. See https://microsoft.github.io/reverse-proxy/articles/transforms.html#pathremoveprefix

**Comment by Tratcher** [comment]
> @Kahbazi ![image](https://user-images.githubusercontent.com/26525599/141676272-3259f8b2-1d0d-4dca-b402-ec9441a31b7c.png)

Where's the code for `HomeController`? It looks like you tried to inject `InMemoryConfigProvider`, but in DI it's registered as `IProxyConfigProvider`. You'd have to resolve `IProxyConfigProvider` and cast to `InMemoryConfigProvider`.

**Comment by bbhxwl** [comment]
@Tratcher   
```
using System.Net;
using Yarp.ReverseProxy.Forwarder;
using Yarp.ReverseProxy.Transforms;

var builder = WebApplication.CreateBuilder(args);


builder.Services.AddControllersWithViews();

builder.Services.AddHttpForwarder();
var app = builder.Build();


if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Home/Error");
}
app.UseStaticFiles();

app.UseRouting();

app.UseAuthorization();

var httpClient = new HttpMessageInvoker(new SocketsHttpHandler()
{
    UseProxy = false,
    AllowAutoRedirect = false,
    AutomaticDecompression = DecompressionMethods.None,
    UseCookies = false
});



var requestOptions = new ForwarderRequestConfig { ActivityTimeout = TimeSpan.FromSeconds(100) };

app.Map("/test", async (HttpContext httpContext, IHttpForwarder forwarder) =>
{

    var error = await forwarder.SendAsync(httpContext, "https://cn.vuejs.org/", httpClient, requestOptions,
        static (context, proxyRequest) =>
        {
                          
                            var queryContext = new QueryTransformContext(context.Request);
            //Convert relative path
            PathString p = new PathString(context.Request.Path.Value.Replace("/test/","").Replace("/test", ""));
                            proxyRequest.RequestUri = RequestUtilities.MakeDestinationAddress("https://cn.vuejs.org/", p, queryContext.QueryString);
                            proxyRequest.Headers.Host = null;

            return default;
        });

    if (error != ForwarderError.None)
    {
        var errorFeature = httpContext.Features.Get<IForwarderErrorFeature>();
        var exception = errorFeature.Exception;
    }
});
app.MapControllerRoute(
    name: "default",
    pattern: "{controller=Home}/{action=Index}/{id?}");

app.Run();

```

![image](https://user-images.githubusercontent.com/26525599/141875270-6c8bd509-d240-4b13-b5e9-4445c7eed0ec.png)

**Comment by bbhxwl** [comment]
> You can also inject the IHttpForwarder directly into your action:
> 
> ```
> app.Map("/{**catch-all}", async (HttpContext httpContext, IHttpForwarder forwarder) =>
> ```

The above is all my net6 code. Do you know where there is an active net6 exchange forum? Few people in China use net6. I don't know where to communicate

**Comment by bbhxwl** [comment]
> You can also inject the IHttpForwarder directly into your action:
> 
> ```
> app.Map("/{**catch-all}", async (HttpContext httpContext, IHttpForwarder forwarder) =>
> ```

In the following picture, the path is correct, but it will not be converted automatically


![image](https://user-images.githubusercontent.com/26525599/141876835-abf13aef-3de5-487b-a274-7de5ae7a64c9.png)
![image](https://user-images.githubusercontent.com/26525599/141876878-27487323-fd90-4469-be52-74104d457e6d.png)

**Comment by bbhxwl** [comment]
```

using System.Net;
using Yarp.ReverseProxy.Forwarder;
using Yarp.ReverseProxy.Transforms;

var builder = WebApplication.CreateBuilder(args);


builder.Services.AddControllersWithViews();

builder.Services.AddHttpForwarder();
var app = builder.Build();


if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Home/Error");
}
app.UseStaticFiles();

app.UseRouting();

app.UseAuthorization();

var httpClient = new HttpMessageInvoker(new SocketsHttpHandler()
{
    UseProxy = false,
    AllowAutoRedirect = false,
    AutomaticDecompression = DecompressionMethods.None,
    UseCookies = false
});



var requestOptions = new ForwarderRequestConfig { ActivityTimeout = TimeSpan.FromSeconds(100) };

app.Map("test/{**catch-all}", async (HttpContext httpContext, IHttpForwarder forwarder) =>
{

    var error = await forwarder.SendAsync(httpContext, "https://cn.vuejs.org/", httpClient, requestOptions,
        static (context, proxyRequest) =>
        {
                          
                            var queryContext = new QueryTransformContext(context.Request);
            //Convert relative path
            string u = context.Request.Path.Value.Replace("/test/", "").Replace("/test", "");
            if (!u.StartsWith('/'))
            {
                u=u.Insert(0,"/");
            }
            PathString p = new PathString(u);
            //context.Request.PathBase = new PathString("/test");
                            proxyRequest.RequestUri = RequestUtilities.MakeDestinationAddress("https://cn.vuejs.org/", p, queryContext.QueryString);
                            proxyRequest.Headers.Host = null;

            return default;
        });

    if (error != ForwarderError.None)
    {
        var errorFeature = httpContext.Features.Get<IForwarderErrorFeature>();
        var exception = errorFeature.Exception;
    }
});
app.MapControllerRoute(
    name: "default",
    pattern: "{controller=Home}/{action=Index}/{id?}");

app.Run();

```

**Comment by Tratcher** [comment]
> The above is all my net6 code. Do you know where there is an active net6 exchange forum? Few people in China use net6. I don't know where to communicate

Try https://stackoverflow.com/questions/tagged/asp.net-core

**Comment by bbhxwl** [comment]
> > The above is all my net6 code. Do you know where there is an active net6 exchange forum? Few people in China use net6. I don't know where to communicate
> 
> Try https://stackoverflow.com/questions/tagged/asp.net-core

Are you still there? Can you solve it for me?

https://github.com/microsoft/reverse-proxy/issues/1384

**Comment by karelz** [comment]
Triage: Questions in this issue have been answered.

For general usage questions, we recommend to use StackOverflow or [Discussions on GH](https://github.com/microsoft/reverse-proxy/discussions).
For bug reports, we recommend to focus on just 1 problem in each issue to make it clearer and isolate the real underlying problem.
Thanks!
