### ISSUE TITLE
I want to implement the example of dynamic operation. What should I do?

### ISSUE THREAD

**Issue by bbhxwl** [microsoft/reverse-proxy#1381]
Path a reverse proxy a website, path B reverse proxy B website.

![image](https://user-images.githubusercontent.com/26525599/141678249-e7edb584-8664-497a-9abc-0d8f7402b1f0.png)

**Comment by bbhxwl** [comment]
The following code will not set the correct local resource path.


var forwarder = app.Services.GetService<IHttpForwarder>();

app.Map("/test/a", async httpContext =>
{
    var error = await forwarder.SendAsync(httpContext, "https://cn.vuejs.org/", httpClient, requestConfig,
        static (context, proxyRequest) =>
        {

            var queryContext = new QueryTransformContext(context.Request);
            PathString p = new PathString(context.Request.Path.Value.Replace("/test/a", ""));
            proxyRequest.RequestUri = RequestUtilities.MakeDestinationAddress("https://cn.vuejs.org/", p, queryContext.QueryString);
            proxyRequest.Headers.Host = null;
            return default;
        });

    // Check if the proxy operation was successful
    if (error != ForwarderError.None)
    {
        var errorFeature = httpContext.Features.Get<IForwarderErrorFeature>();
        var exception = errorFeature.Exception;
    }
});

**Comment by Tratcher** [comment]
Note `Map` already moves "/test/a" from the Request.Path to Request.PathBase.

What was the input url, the resulting RequestUri, and your expected value?

**Comment by bbhxwl** [comment]
> Note `Map` already moves "/test/a" from the Request.Path to Request.PathBase.
> 
> What was the input url, the resulting RequestUri, and your expected value?

If you directly use request.path, the requesturi will become https://cn.vuejs.org/test/a

But it makes https://cn.vuejs.org/ All internal resource 404 errors.

**Comment by bbhxwl** [comment]
> Note `Map` already moves "/test/a" from the Request.Path to Request.PathBase.
> 
> What was the input url, the resulting RequestUri, and your expected value?

It seems that you can only use the reverse proxy URL of the top-level domain name? If MVC exists, setting the path of the reverse proxy to a node seems to be impossible.

**Comment by bbhxwl** [comment]
> Note `Map` already moves "/test/a" from the Request.Path to Request.PathBase.
> 
> What was the input url, the resulting RequestUri, and your expected value?


I want to visit the website http://localhost:5000/google Achieve the effect of nginx instead of http://localhost:5000/
```
  location / {
        proxy_pass https://www.google.com;
    proxy_http_version 1.1;
 # 替换指定字符串
            sub_filter                          www.google.com google.test.com;
          
            sub_filter_once                     off;

            # 指定头部：
            proxy_set_header  Host              "www.google.com";
            proxy_set_header  Referer           $http_referer;
            proxy_set_header  X-Real-IP         $remote_addr;
            proxy_set_header  User-Agent        $http_user_agent;
            # 防止谷歌返回压缩的内容，因为压缩的内容无法替换字符串
            proxy_set_header  Accept-Encoding   "";

            #把 cookie 的作用域替换成你的域名
            proxy_cookie_domain                 www.google.com google.test.com;
            #传固定的 cookie 给谷歌，是为了禁止即时搜索，因为开启即时搜索无法替换内容
            proxy_set_header  Cookie           "PREF=ID=047808f19f6de346:U=0f62f33dd8549d11:FF=2:LD=en-US:NW=1:TM=1325338577:LM=1332142444:GM=1:SG=2:S=rE0SyJh2W1IQ-Maw";

    }
```

**Comment by Tratcher** [comment]
> It seems that you can only use the reverse proxy URL of the top-level domain name? If MVC exists, setting the path of the reverse proxy to a node seems to be impossible.

See https://github.com/microsoft/reverse-proxy/discussions/1373 for information about sharing routing with MVC.

**Comment by bbhxwl** [comment]
> > It seems that you can only use the reverse proxy URL of the top-level domain name? If MVC exists, setting the path of the reverse proxy to a node seems to be impossible.
> 
> See #1373 for information about sharing routing with MVC.

I think this is based on the configuration file, but my English may not be good enough. I can't see whether it is supported or not? I don't know how to modify it if I'm based on the code?

**Comment by Tratcher** [comment]
Setting the order in code is harder for Map, it looks like this:
```
app.Map("/test/a", httpContext =>
{
    return Task.CompletedTask;
}).Add(b => ((RouteEndpointBuilder)b).Order = -100000);
```

**Comment by adityamandaleeka** [comment]
I think this has been answered. Closing issue.
