### ISSUE TITLE
Replace resource error & reverse proxy error

### ISSUE THREAD

**Issue by bbhxwl** [microsoft/reverse-proxy#1384]
The following code contains all my errors.

1：/vue/{**catch-all}      request  http://localhost:5180/vue   404   error
2：:Replace the requested resource, the data obtained is garbled

https://github.com/bbhxwl/TestYarp

**Comment by Tratcher** [comment]
The garbled content you're asking about is here? https://github.com/microsoft/reverse-proxy/issues/821#issuecomment-969679216

That looks like compression. YARP disabled response decompression by default for performance reasons. See DecompressionMethods when you set up the client:

```
var httpClient = new HttpMessageInvoker(new SocketsHttpHandler()
{
    UseProxy = false,
    AllowAutoRedirect = false,
    AutomaticDecompression = DecompressionMethods.None,
    UseCookies = false
});
```

**Comment by Tratcher** [comment]
1：/vue/{**catch-all} request http://localhost:5180/vue 404 error

Do you mean that `/vue/{**catch-all}` doesn't match requests to `http://localhost:5180/vue`? That's expected. Slashes are significant. You'll need a second route for `/vue` if you want to match just that part.

**Comment by bbhxwl** [comment]
> 1：/vue/{**catch-all} request http://localhost:5180/vue 404 error
> 
> Do you mean that `/vue/{**catch-all}` doesn't match requests to `http://localhost:5180/vue`? That's expected. Slashes are significant. You'll need a second route for `/vue` if you want to match just that part.

http://localhost:5180/vue  proxy   https://cn.vuejs.org/
http://localhost:5180/google proxy   https://www.google.com/

**Comment by bbhxwl** [comment]
> The garbled content you're asking about is here? [#821 (comment)](https://github.com/microsoft/reverse-proxy/issues/821#issuecomment-969679216)
> 
> That looks like compression. YARP disabled response decompression by default for performance reasons. See DecompressionMethods when you set up the client:
> 
> ```
> var httpClient = new HttpMessageInvoker(new SocketsHttpHandler()
> {
>     UseProxy = false,
>     AllowAutoRedirect = false,
>     AutomaticDecompression = DecompressionMethods.None,
>     UseCookies = false
> });
> ```

yes, 
```
using System.Net;
using System.Text;
using Yarp.ReverseProxy.Forwarder;
using Yarp.ReverseProxy.Transforms;

var builder = WebApplication.CreateBuilder(args);


builder.Services.AddControllersWithViews();

builder.Services.AddHttpForwarder();
var app = builder.Build();


if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Home/Error");
}
app.UseStaticFiles();

app.UseRouting();

app.UseAuthorization();

var httpClient = new HttpMessageInvoker(new SocketsHttpHandler()
{
    UseProxy = false,
    AllowAutoRedirect = false,
    AutomaticDecompression = DecompressionMethods.None,
    UseCookies = false
});

CustomTransformer c = new CustomTransformer();

var requestOptions = new ForwarderRequestConfig { ActivityTimeout = TimeSpan.FromSeconds(100) };

app.Map("/vue/{**catch-all}", async (HttpContext httpContext, IHttpForwarder forwarder) =>
{

    var error = await forwarder.SendAsync(httpContext, "https://cn.vuejs.org/", httpClient, requestOptions,
     c);

    if (error != ForwarderError.None)
    {
        var errorFeature = httpContext.Features.Get<IForwarderErrorFeature>();
        var exception = errorFeature.Exception;
    }
});
app.MapControllerRoute(
    name: "default",
    pattern: "{controller=Home}/{action=Index}/{id?}");

app.Run();


public class CustomTransformer : HttpTransformer
{
    public override async ValueTask TransformRequestAsync(HttpContext httpContext, HttpRequestMessage proxyRequest, string destinationPrefix)
    {
        await base.TransformRequestAsync(httpContext, proxyRequest, destinationPrefix);
        var queryContext = new QueryTransformContext(httpContext.Request);
        proxyRequest.RequestUri = new Uri(destinationPrefix + httpContext.Request.Path + queryContext.QueryString);
        proxyRequest.Headers.Host = null;
    }

    public override async ValueTask<bool> TransformResponseAsync(HttpContext httpContext, HttpResponseMessage? proxyResponse)
    {

        if (proxyResponse == null)
        {
            return false;
        }
        string body = await proxyResponse.Content.ReadAsStringAsync();
        body = body.Replace("<title>Vue.js</title>", "<title>bbhxwl</title>");
        var content = new StringContent(body, Encoding.UTF8, "text/html");
        httpContext.Response.ContentLength = body.Length;
        proxyResponse.Content?.Dispose();
        proxyResponse.Content = content;
        return await base.TransformResponseAsync(httpContext, proxyResponse);
    }
  

}
```

**Comment by bbhxwl** [comment]
> The garbled content you're asking about is here? [#821 (comment)](https://github.com/microsoft/reverse-proxy/issues/821#issuecomment-969679216)
> 
> That looks like compression. YARP disabled response decompression by default for performance reasons. See DecompressionMethods when you set up the client:
> 
> ```
> var httpClient = new HttpMessageInvoker(new SocketsHttpHandler()
> {
>     UseProxy = false,
>     AllowAutoRedirect = false,
>     AutomaticDecompression = DecompressionMethods.None,
>     UseCookies = false
> });
> ```

AutomaticDecompression = DecompressionMethods.All,    
This seems to be OK.

But the path mapping is still wrong

**Comment by bbhxwl** [comment]
> 1：/vue/{**catch-all} request http://localhost:5180/vue 404 error
> 
> Do you mean that `/vue/{**catch-all}` doesn't match requests to `http://localhost:5180/vue`? That's expected. Slashes are significant. You'll need a second route for `/vue` if you want to match just that part.

https://github.com/bbhxwl/TestYarp

I updated the code, or 404. How should this be mapped?

**Comment by Tratcher** [comment]
```
app.Map("/vue/{**catch-all}", async (HttpContext httpContext, IHttpForwarder forwarder) =>
{

    var error = await forwarder.SendAsync(httpContext, "https://cn.vuejs.org/", httpClient, requestOptions,
```

This pattern is not going to work well. The initial client request to `http://localhost:5180/vue/` will return an HTML page full of resource links without the `/vue/` prefix so all of the resource requests will 404. Trying to rewrite all of those resource urls in the HTML is a lot of work.

**Comment by bbhxwl** [comment]
> ```
> app.Map("/vue/{**catch-all}", async (HttpContext httpContext, IHttpForwarder forwarder) =>
> {
> 
>     var error = await forwarder.SendAsync(httpContext, "https://cn.vuejs.org/", httpClient, requestOptions,
> ```
> 
> This pattern is not going to work well. The initial client request to `http://localhost:5180/vue/` will return an HTML page full of resource links without the `/vue/` prefix so all of the resource requests will 404. Trying to rewrite all of those resource urls in the HTML is a lot of work.

Does that mean you need to do a lot of work in transformresponseasync? There is no simpler way at present?

**Comment by Tratcher** [comment]
Correct. YARP is not designed for body transformation scenarios like this. You should consider using a routing design that does not use path prefixes like this.

**Comment by bbhxwl** [comment]
> Correct. YARP is not designed for body transformation scenarios like this. You should consider using a routing design that does not use path prefixes like this.

I want to reverse proxy multiple different pages on one page.

**Comment by adityamandaleeka** [comment]
@bbhxwl It sounds like what you're trying to do is impractical without the cooperation of the destination site; trying to use a reverse proxy (YARP or otherwise) to accomplish this will be extremely difficult.

I think your other questions here have been answered though, so I will close this issue. Feel free to open another one if you encounter any other issues.
