### ISSUE TITLE
Pass context between reverse proxies services

### ISSUE THREAD

**Issue by Meir017** [microsoft/reverse-proxy#139]
### What should we add or change to make your life better?

different services in the proxy chain require different information from the request that a previous service extracted from the request without performing that same logic

### Why is this important to you?

In my team we have a scenario where we have multiple reverse proxies, each one performs some logic on the request and then passes it on to the next one and the last proxy passes the request to the upstream.

**Comment by Tratcher** [comment]
> where we have multiple reverse proxies,

These are distinct HTTP applications running in separate processes or servers? Or just chained modules in one instance?

What proxy software do you use today and how to you flow this state there?

**Comment by Meir017** [comment]
our current design is to have for each of these HTTP services to run inside the same AKS cluster, each one is a different process

We are still not sure what would be the best way to pass a request-context between these services

**Comment by Tratcher** [comment]
How complex is the state?

Out-of-process your options are pretty limited. You can add custom headers to a request, or push state to a shared cache/database.

**Comment by samsp-msft** [comment]
Why are you doing things this way? I'm assuming there is a good reason that each step is a different process - understanding that will shed more light on the scenario and alternatives.

**Comment by Meir017** [comment]
> How complex is the state?

each service has a different outgoing state that it adds to the request, usually a few properties, string/int/boolean

> Why are you doing things this way?

each service performs different logic that is unique to that service and this is how we broke down our previous monolith service which did everything

**Comment by Meir017** [comment]
Is a scenario similar to this going to be supported here?

**Comment by karelz** [comment]
Triage: We need more info - @samsp-msft will follow up.
Naively this seems like something that should be captured in headers.

**Comment by samsp-msft** [comment]
We don't have an out of band mechanism for proxy instances to talk to each other. It would need to be either by the headers or body of the message. We don't really want to crack the body and try to understand the content - so that leaves the header.

A pipeline module will be able to read/write headers as request/responses pass through. If that is what you need then great - if not then its sounding less like a reverse proxy and more like an API gateway, or service.
