### ISSUE TITLE
What happened to HttpClient.ClientCertificate

### ISSUE THREAD

**Issue by cbmek** [microsoft/reverse-proxy#1394]
In _preview.11_ I could configure client certificate per cluster using `ClientCertificate` in `ProxyHttpClientOptions`.
Now `ProxyHttpClientOptions` became `HttpClientConfig` and it doesn't have `ClientCertificate`.

I know I can still do global configuration for proxy:
```csharp
    var clientCert = new X509Certificate2("path");
    services.AddReverseProxy()
        .ConfigureHttpClient((context, handler) =>
        {
            handler.SslOptions.ClientCertificates.Add(clientCert);
        })
```
...but how to configure different certs (or no cert) per cluster?

Also in sample configuration file, there is still `ClientCertificate` option: https://github.com/microsoft/reverse-proxy/blob/release/1.0/samples/ReverseProxy.Config.Sample/appsettings.json#L112

**Comment by Tratcher** [comment]
See https://github.com/microsoft/reverse-proxy/pull/994/. Note that ConfigureHttpClient is called per cluster, you can get the cluster information from the context.
https://github.com/microsoft/reverse-proxy/blob/main/src/ReverseProxy/Forwarder/ForwarderHttpClientContext.cs

We should update the sample config.
