### ISSUE TITLE
Is there a possibility to add new Body based MatcherPolicy ?

### ISSUE THREAD

**Issue by samanthwal** [microsoft/reverse-proxy#1399]
### What should we add or change to make your life better?
I want to execute something like this as custom matcher as late as possible in the pipeline.
Though it would have some performance implication as this is reading the body but that would be once per unique request otherwise it would be cached expression or route being used.
```
  "ReverseProxy": {
    "Routes": {
      "route1": {
        "ClusterId": "cluster1",
        "Match": {
          "Path": "/app1/{**path}",
          **"Body": {
            "expression": "XYZ",
             "MatcherFunction" :  "MyCustomMatcher"  // this would execute that custom expression based on request body
           }**
        }
      }
      
    },
    "Clusters": {
      "cluster1": {
        "Destinations": {
          "cluster1/destination1": {
            "Address": "https://localhost:6200"
          }
        }
      }
    }
  }
}
```
### Why is this important to you?

https://cloud.spring.io/spring-cloud-gateway/reference/html/#naming-custom-filters-and-references-in-configuration
though this is not a apple to apple comparison   but this  gives that ability to inject any custom filter in the request processing pipeline and filter the request how ever you want.
Given that hook , would open other possibilities to do dynamic routing based on body messages

**Comment by samsp-msft** [comment]
Routing is the first stage in processing requests for YARP - as YARP is integrating its route table in with other entries created for ASP.NET. It could probably be one of the last stages of disambiguation if its only applying to a specific path.

You indicate that you want to do process this once per request - YARP is generally stateless - each request is processed individually - there needs to be extra state that indicates how it is to be processed - for example sessions typically use cookies or custom headers, but each request will need to have that data - so what are you thinking here?

Processing bodies is likely to require caching so that the whole body can be read in, processed and then handed off to the forwarder. This will impact memory usage and performance.

Could you supply more details about what you are trying to accomplish and why?

**Comment by Tratcher** [comment]
Have you considered using middleware instead?
https://microsoft.github.io/reverse-proxy/articles/middleware.html

Middleware can buffer/read the body and make decisions. Selecting a destination within the current cluster is easy, but selecting a route/cluster is harder. Or you could combine middleware with direct forwarding.
https://microsoft.github.io/reverse-proxy/articles/direct-forwarding.html

**Comment by samanthwal** [comment]
Thanks @Tratcher  , Selecting a destination within a cluster works by replacing "AvailableDestinations " in the middleware that I had already tried out  but not sure how to select cluster /route by combining middleware and IHttpForwarder.

**Comment by samanthwal** [comment]
> Routing is the first stage in processing requests for YARP - as YARP is integrating its route table in with other entries created for ASP.NET. It could probably be one of the last stages of disambiguation if its only applying to a specific path.
> 
> You indicate that you want to do process this once per request - YARP is generally stateless - each request is processed individually - there needs to be extra state that indicates how it is to be processed - for example sessions typically use cookies or custom headers, but each request will need to have that data - so what are you thinking here?
> 
> Processing bodies is likely to require caching so that the whole body can be read in, processed and then handed off to the forwarder. This will impact memory usage and performance.
> 
> Could you supply more details about what you are trying to accomplish and why?

Thanks @samsp-msft 
Currently  I have a SOAP based router which also takes routing decisions based on SOAP message and now I am seeing the possibility to replace that with YARP for RESTful microservices.
I am seeing the possibilities to inject the middleware in the YARP pipeline to select Cluster /route based on Request Body without loosing the benefits of HealthCheck and Load Balancing.

When I add a middleware into the ReverseProxy pipeline by that time it has already selected the cluster/route so maximum I can do is to filter endpoints within the same cluster.

**Comment by samsp-msft** [comment]
If you really need to examine the request bodies then I would agree with @Tratcher - this is probably a case where I would advise using direct forwarding. If you *can* find a way to use the url or headers instead to route, then you should find better performance etc. If these are new services, where you have the ability to encode the parameters you need to switch upon as part of the URL it will be better.

**Comment by Tratcher** [comment]
> Thanks @Tratcher , Selecting a destination within a cluster works by replacing "AvailableDestinations " in the middleware that I had already tried out but not sure how to select cluster /route by combining middleware and IHttpForwarder.

When working directly with IHttpForwarder you don't use routes or clusters, you make the decisions in middleware and then call IHttpForwarder with the determined forwarder url.

**Comment by adityamandaleeka** [comment]
@samanthwal Do you have any further questions or can this issue be closed?

**Comment by samanthwal** [comment]
> @samanthwal Do you have any further questions or can this issue be closed?
Hi @adityamandaleeka , sure we can close this.

Thanks @Tratcher  and @samsp-msft  for your suggestions on this.
