### ISSUE TITLE
 Proxy can front multiple sites and route based on SNI/Host 

### ISSUE THREAD

**Issue by anurse** [microsoft/reverse-proxy#14]
A proxy will often want to route based on the host. It's possible today but it's clunky.
https://github.com/dotnet/aspnetcore/issues/19354

**Comment by Tratcher** [comment]
Note dotnet/aspnetcore#19354 was backlogged. If this shows up in our performance analysis we'll need to revisit and likely contribute resources to addressing it.

**Comment by karelz** [comment]
ASP.NET work is done
