### ISSUE TITLE
Expose HttpClient.AllowAutoRedirect in cluster config?

### ISSUE THREAD

**Issue by riddlemd** [microsoft/reverse-proxy#1407]
Would be super handy to not have to write a custom code just to get access to this one property... a lot of our legacy code uses fully qualified URLs in the redirects so it's causing us to hop off the proxy frequently.

**Comment by Tratcher** [comment]
The client usually needs to be aware of redirects in order to store cookies, complete auth flows, cache, etc.

What kind of redirects are you seeing?

See these docs for recommendations to get apps to generate links and redirects with the correct host names:
https://microsoft.github.io/reverse-proxy/articles/header-guidelines.html#x-forwarded--forwarded

**Comment by riddlemd** [comment]
We've got some 307 (authorization redirect) and some 301 (content has moved) the issue is, again; they are fully qualified domains in the redirect so stuff on the other side of the proxy can't access where they're being redirected to.

**Comment by Tratcher** [comment]
I'd be surprised if AllowAutoRedirect worked for auth scenarios, it would break if there are any cookies involved.

If you don't want to modify the existing app to use forwarders then you could also use a response transform to rewrite the Location header.
https://microsoft.github.io/reverse-proxy/articles/transforms.html#addresponsetransform

**Comment by riddlemd** [comment]
> I'd be surprised if AllowAutoRedirect worked for auth scenarios, it would break if there are any cookies involved.

Would the cookies not be proxied out to the client? The client would then send them to the proxy and those would be passed to the server, don't see why that would be an issue.

**Comment by Tratcher** [comment]
Set-Cookie headers included on the 30X redirect response would not be proxied to the client if the proxy automatically redirects, the client never gets that 30X response. Set-Cookie is pretty common on 30X auth responses for scenarios like OAuth, OIDC, and forms auth.

**Comment by riddlemd** [comment]
Seems like that goes against the expected behavior of Set-Cookie, I would expect a proxy to queue up Set-Cookie for a domain and send those when you reach the end of a redirect chain... (sigh) looks like this will require custom code, since this seems to be a fundamental issue with httpclient's implementation.

**Comment by Tratcher** [comment]
> I would expect a proxy to queue up Set-Cookie for a domain and send those when you reach the end of a redirect chain

Nope, I'd be curious to see if any proxy supported that.

**Comment by adityamandaleeka** [comment]
Sounds like this has been answered, closing issue.
