### ISSUE TITLE
Behavior of HttpTransformer.Default should match the behavior of new HttpTransformer() or be moved/renamed

### ISSUE THREAD

**Issue by garrettm-msft** [microsoft/reverse-proxy#1409]
### Some details

**How many backends are in your application?**

- [ ] 1-2
- [ ] 3-5
- [ ] 6-10
- [X] 10+

**How do you host your application?**

- [ ] Kubernetes
- [ ] Azure App Service
- [ ] Azure VMs
- [ ] Other Cloud Provider (please include details below)
- [X] Other Hosting model (please include details below)
Azure Service Fabric

### What did you think of YARP?

We recently root caused a direct proxying regression on our upgrade to YARP 1.0.0 caused by #1246 , which changed the behavior of HttpTransformer.Default to match the default behavior of TransformBuilder.CreateTransformer rather than the behavior of new HttpTransformer(). While it seems fair for the default behavior of IHttpForwarder.SendAsync to match the default forwarding behavior of non-direct proxy methods, it is quite sneaky for the HttpTransformer.Default property to additionally include the behavior of StructuredTransformer and default transforms added by TransformBuilder.CreateTransformer.

We suggest:

- Moving/renaming HttpTransformer.Default to make it clearer what logic it includes
- Still providing a static value for new HttpTransformer() and/or making the parameterless HttpTransformer constructor public to make a default HttpTransformer less awkward to obtain

@davidni as FYI and in case he has more to add on this

**Comment by Tratcher** [comment]
> * Moving/renaming HttpTransformer.Default to make it clearer what logic it includes

That's a breaking change we're unlikely to make now that 1.0 has shipped.

> * Still providing a static value for new HttpTransformer() and/or making the parameterless HttpTransformer constructor public to make a default HttpTransformer less awkward to obtain

Maybe `HttpTransformer.Empty`?

**Comment by karelz** [comment]
Triage: @garrettm-msft can you please confirm if the above suggestion of adding `HttpTransformer.Empty` would address your key concerns?

**Comment by garrettm-msft** [comment]
Thanks both for the replies. While we believe the semantics are a bit unfortunate it's understandable that making such a breaking change is non-viable currently, and adding HttpTransformer.Empty should adequately address the concerns here.

**Comment by Tratcher** [comment]
Re-opening to add a test
