### ISSUE TITLE
Support for dapr sidecar on Azure Container Apps

### ISSUE THREAD

**Issue by thara0402** [microsoft/reverse-proxy#1411]
I deployed Reverse Proxy with YARP on Azure Container Apps.
Microservices Application leverage the YARP as an API gateway.
I want to YARP forwards the request to back-end service via dapr sidecar.

| YARP -> Dapr sidecar | -> | Dapr sidecar -> back-end service |

Do you have any plans to support it?

**Comment by Tratcher** [comment]
#967 is another dapr issue, but I don't know enough about dapr to say if they're related.

**Comment by mayoatte** [comment]
+1 for interest in this integration. This would be amazing.

**Comment by samsp-msft** [comment]
Duplicate of #967
