### ISSUE TITLE
oauth callback url

### ISSUE THREAD

**Issue by sajrashid** [microsoft/reverse-proxy#1420]
Hi,

Is there a doc for OAuth callback, using cookie authentication with GitHub (octokit)?

### Description
Using Blazor Wasm with WebApi as a SPA.  The callback returns to the `WebApi port (localhost:6000)` instead of the `proxy's (localhost:5000)`

The callback URL is set to `localhost:5000` and works if I remove the proxy.

I'm not sure how GitHub would know to return to `localhost:6000` ?

Something definitely amiss.

Am I forwarding the request incorrectly, I am using cookie authentication?

    "Urls": "https://localhost:5000;http://localhost:5001",
    "Logging": {
      "LogLevel": {
        "Default": "Information",
        // Uncomment to hide diagnostic messages from runtime and proxy
        // "Microsoft": "Warning",
        // "Yarp" : "Warning",
        "Microsoft.Hosting.Lifetime": "Information"
      }
    },
  
    "ReverseProxy": {
      // Routes tell the proxy which requests to forward
      "Routes": {
        "minimumroute": {
          // Matches anything and routes it to "wasm":
          "ClusterId": "minimumcluster",
          "Match": {
            "Path": "{**catch-all}"
          }
        },
        "route2": {
          // matches /something/* and routes to 1 external addresses
          "ClusterId": "WebApi",
          "Match": {
            "Path": "/api/{*any}"
          }
        },
        "route3": {
          // matches /something/* and routes to 1 external addresses
          "ClusterId": "WebApi",
          "Match": {
            "Path": "/swagger/{*any}"
          }
        },
        "route4": {
          // matches /something/* and routes to 1 external addresses
          "ClusterId": "WebApi",
          "Match": {
            "Path": "/login/{*any}"
          }
        },
        "route8": {
          // matches /something/* and routes to 1 external addresses
          "ClusterId": "WebApi",
          "Match": {
            "Path": "/signin/{*any}"
          }
        }
      },
      // Clusters tell the proxy where and how to forward requests
      "Clusters": {
        "minimumcluster": {
          "Destinations": {
            "wasm": {
              "Address": "https://localhost:7000/"
            }
          }
        },
        "WebApi": {
          "Destinations": {
            "first_destination": {
              "Address": "https://localhost:6000"
            }
            //"another_destination": {
            //  "Address": "https://bing.com"
            //}
          }
        }
      }
    }
  }

**Comment by Tratcher** [comment]
See https://microsoft.github.io/reverse-proxy/articles/header-guidelines.html#x-forwarded--forwarded and https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-6.0 for details on generating correct links and redirects behind a proxy.

**Comment by sajrashid** [comment]
@Tratcher you're deffo a 🦸 now,

🕺🏽, I have a token!

```
"Transforms": [
          { "RequestHeaderOriginalHost": "true" }
        ]
```

Thank you.
