### ISSUE TITLE
Transforming the query parameters based on mapping stored in the database

### ISSUE THREAD

**Issue by gajayreddy9** [microsoft/reverse-proxy#1428]
Hi,

I am looking at using YARP as revrese proxy for one of my applications. Here is what I am trying to do

The request comes in to proxy as **requestfoo.com/explore?id=guid&height=100**
I want to transform the request into **destinationfoo/explore?id=int&height=100** and proxy it to the destination.

I am thinking of  storing the mapping for id(guid) in the request to id(int) in the destination in a database. So When the request comes in I want to grab the guid in the request and check my cache first for the mapping to id(int) and then build the destination query parameters. If it does not exist in cache, I want to query the database and store it in the cache and then build the destination query parameters. Is it possible to achieve this using YARP? 

Can we do this using a custom transform? can we call database in a custom transform?

Or should it be done through routes?

**Comment by Tratcher** [comment]
You should be able to do this in a custom transform. Accessing a database is possible with caching for performance reasons.

You'd do something like this to add the custom transform:
https://github.com/microsoft/reverse-proxy/blob/ec6c5a2be3c5e4dee8b3e24c614dc08bf550f815/samples/ReverseProxy.Transforms.Sample/Startup.cs#L39-L49
Then you'd modify the query parameters on the transform context:
https://github.com/microsoft/reverse-proxy/blob/a5b36816f11e939f5037f521109153b5d67bae26/src/ReverseProxy/Transforms/RequestTransformContext.cs#L44
https://github.com/microsoft/reverse-proxy/blob/a5b36816f11e939f5037f521109153b5d67bae26/src/ReverseProxy/Transforms/QueryTransformContext.cs#L49

**Comment by gajayreddy9** [comment]
@Tratcher It worked. Thank you very much for the help.
