### ISSUE TITLE
Ship Preview1 nuget package

### ISSUE THREAD

**Issue by karelz** [microsoft/reverse-proxy#143]
Ship the nuget package
Create steps how-to - learn from @anurse

**Comment by anurse** [comment]
We also need to update the branding. Right now it's `0.1.0-alpha.1`.

That also means that if you want to do a dry-run @karelz, we already have perfect packages for it (since we already have build artifacts versioned `0.1.0-alpha.1`)

**Comment by WeihanLi** [comment]
Will it support for `netcoreapp3.1`?

**Comment by Tratcher** [comment]
> Will it support for `netcoreapp3.1`?

No, only the latest 5.0 preview.

**Comment by WeihanLi** [comment]
> > Will it support for `netcoreapp3.1`?
> 
> No, only the latest 5.0 preview.

Thanks for the info

**Comment by Tratcher** [comment]
@WeihanLi nevermind, we've decided to add 3.1 support. https://github.com/microsoft/reverse-proxy/issues/159

**Comment by WeihanLi** [comment]
> @WeihanLi nevermind, we've decided to add 3.1 support. #159

I'd known about that, thanks for your effort, that's really a good news

**Comment by karelz** [comment]
Shipped: https://www.nuget.org/packages/Microsoft.ReverseProxy/1.0.0-preview.1.20268.2
