### ISSUE TITLE
Custom Response Transform Issue

### ISSUE THREAD

**Issue by MartyBJones** [microsoft/reverse-proxy#1434]
### Describe the bug
When I add create a class that extends ResponseTransform the reverse proxy stops working.

Basically I am using the reverse proxy to pass requests that it can't handle down to an older legacy application.   When a 302 redirect is sent from the legacy application I want to update the "location" header so that it redirects back to the front facing application.

I modeled my custom response transformer from the "ResponseHeaderRemoveTransform.cs" class.

Basically what happens when I use the transformer is all requests are cancelled before the response is received.    I am getting the error

```
Yarp.ReverseProxy.Forwarder.HttpForwarder: Information: RequestCanceled: The request was canceled before receiving a response.

System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer)
```

**Here is my response transformer:**

```c#
public class CustomLocationTransformer : ResponseTransform
{
    public CustomLocationTransformer()
    {
    }

    // Assumes the response status code has been set on the HttpContext already.
    /// <inheritdoc/>
    public override ValueTask ApplyAsync(ResponseTransformContext context)
    {
        if (context is null)
        {
            throw new ArgumentNullException(nameof(context));
        }

        if (context.HttpContext.Response.StatusCode == 302)
        {
            string? location = context.HttpContext.Response.Headers.Location.FirstOrDefault();

            if (location != null && location.Contains("/legacy"))
            {
                context.HttpContext.Response.Headers.Remove("location");
                context.HttpContext.Response.Headers.Add("location", location.Replace("/legacy", ""));
            }
        }

        return default;
    }
}
```

**Comment by MihaZupan** [comment]
How are you adding the custom transform to the proxy?

Are you changing anything else as part of adding the transform? A response transform by definition only runs when a response is received, which doesn't happen in your case since the timeout is hit first.

**Comment by MihaZupan** [comment]
> I figured out the issue. I was initializing the response transformer as below. I was thinking the "AddPathPrefix" was to tell the context to only apply for that the transform to a given path but it was actually doing an request transform which is not what I wanted. I commented out that and it works as expected now.
proxyBuilder.AddTransforms(transformBuilderContext => { //transformBuilderContext.AddPathPrefix("/legacy"); transformBuilderContext.ResponseTransforms.Add(new CustomLocationTransformer()); });

https://github.com/microsoft/reverse-proxy/issues/990#issuecomment-990147618

@MartyBJones I assume you wanted to comment here 😄

**Comment by MartyBJones** [comment]
LOL.  Sorry about that.
