### ISSUE TITLE
Injecting retries and circuitbreaker  policies over YARP 

### ISSUE THREAD

**Issue by samanthwal** [microsoft/reverse-proxy#1442]
### What should we add or change to make your life better?
Assuming we can implement our own CustomForwarderHttpClientFactory  and then apply retries and circuitbreaker polices over HttpClient.
But looking something which can be made configurable at the cluster /destination level /method or status code level.
### Why is this important to you
Trying to replace SCG with YARP which has feature to add retries filters at endpoint level.
Something like below 
https://cloud.spring.io/spring-cloud-gateway/reference/html/#the-retry-gatewayfilter-factory

**Comment by Tratcher** [comment]
See https://github.com/microsoft/reverse-proxy/issues/56 for discussion of retries.

See https://microsoft.github.io/reverse-proxy/articles/dests-health-checks.html#passive-health-checks for circuit breakers.
