### ISSUE TITLE
Shortcircuit request-response

### ISSUE THREAD

**Issue by poostwoud** [microsoft/reverse-proxy#1445]
We have created a request transformer for identity server allowing reference tokens to be converted to self containing tokens. The introspection endpoint is called on request and after this point it is already known if the access token is still active or has expired. It would be great if we could somehow return a response based on this outcome without having to send the request to the backend services. This could save a lot of "useless" requests to the backend.

**Comment by MihaZupan** [comment]
You can serve the response before calling into the forwarder logic.
See a [`"Send an immediate response"`](https://microsoft.github.io/reverse-proxy/articles/middleware.html#send-an-immediate-response) example. You have full access to the request to decide whether you can skip going to the backend.

**Comment by poostwoud** [comment]
This is great! Thank you. Case closed.
