### ISSUE TITLE
How to HotSwap

### ISSUE THREAD

**Issue by OpenSpacesAndPlaces** [microsoft/reverse-proxy#1447]
If you're using YARP to manage .Net Core site and you're running off the exe. 

What's the correct strategy to load and warm a new version of the site and then swap the old and new?

**Comment by Tratcher** [comment]
This is for a new version of the app behind the proxy, right?

In general, YARP doesn't directly manage the destinations, you need an orchestrator for that. The general procedure is:
- Bring up a new instance of the site, send it some warmup requests
- Update YARP's config to include the new destination
- Make sure everything's running well
- Update YARP's config to remove the old destination

There's not currently a mechanism to gradually shift traffic from one to the other. With both destinations active at once you'd get traffic load balanced between them. There's some discussion here: https://github.com/microsoft/reverse-proxy/issues/126

**Comment by OpenSpacesAndPlaces** [comment]
```
Update YARP's config to include the new destination
Make sure everything's running well
Update YARP's config to remove the old destination
```

You're saying if I do like this:
```
 "ReverseProxy": {
    "Routes": {
      "route1": {
        "ClusterId": "cluster1",
        "Match": {
          "Path": "{**catch-all}"
        }
      }
    },
    "Clusters": {
      "cluster1": {
        "Destinations": {
          "destination1": {
            "Address": "https://www.mysitestaging.com"
          }
        }
      }
    }
  },
```

->

```
 "ReverseProxy": {
    "Routes": {
      "route1": {
        "ClusterId": "cluster1",
        "Match": {
          "Path": "{**catch-all}"
        }
      }
    },
    "Clusters": {
      "cluster1": {
        "Destinations": {
          "destination1": {
            "Address": "https://www.mysitelive.com"
          }
        }
      }
    }
  },
```

YARP will automatically read the config file changes and server over a new DNS?

So my pattern would be like?:

New Code -> Staging Url
Old Code -> Coldsite Url 
New Code -> Live Url + Cofirm Loadin
Old Code -> Spin Down App

**Comment by Tratcher** [comment]
Yes, YARP will react to config changes live.

Having a staging site is good too, but I was referring more to having both running side by side like this:
```
    "Clusters": {
      "cluster1": {
        "Destinations": {
          "destination1": {
            "Address": "https://live1" // old code
          }
        }
      }
    }
```
->
Add new instance
```
    "Clusters": {
      "cluster1": {
        "Destinations": {
          "destination1": {
            "Address": "https://live1" // old code
          },
          "destination2": {
            "Address": "https://live2" // new code
          }
        }
      }
    }
```
Chech health
->
Remove old instance
```
    "Clusters": {
      "cluster1": {
        "Destinations": {
          "destination2": {
            "Address": "https://live2" // new code
          }
        }
      }
    }
```
Spin down old instance

**Comment by OpenSpacesAndPlaces** [comment]
Thanks! We'll give this a shot!

**Comment by karelz** [comment]
Triage: Looks answered. #126 will handle the slow rollout.
