### ISSUE TITLE
How to prioritize local controller route over Host proxy configs

### ISSUE THREAD

**Issue by nabsul** [microsoft/reverse-proxy#1453]
Fantastic library by the way! I'm having some trouble getting my proxy app to work as I need, and I'm sure I'm just missing the magic incantation:

- I'm using YARP to reverse proxy requests to different services based on the host. 
- However, the reverse proxy app also has an endpoint for ACME cert renewal that the proxy should handle directly.
- When I visit `localhost/.well-known/acme-challenge/{value}` I correctly get the response from the proxy controller
- When I visit `domain1.com/.well-known/acme-challenge/{value}`, the request is reverse proxied to domain1.com
  - I don't want this behavior. I want all requests, regardless of domain, to go to the controller

I've tried changing `Order` in the controller as well as the proxy configurations, but it doesn't change the behavior. It seems that per-host filtering trumps all explicit priority specifications.

Perhaps there's a way to tell YARP to ignore anything going to `.well-known/acme-challenge/{value}`

Is there a way to solve this problem?

**Comment by Tratcher** [comment]
What route definitions are you using for ACME and YARP? The most specific match wins, starting with the path, method, host, and then headers.

Order helps break ties but note that the default matchers run with a large negative number order (-100 for hosts).

**Comment by nabsul** [comment]
Thanks for the quick reply:

> Order helps break ties but note that the default matchers run with a large negative number order (-100 for hosts).

I tried to give my controller Order int.MinValue and it still doesn't get prioritized :-)

I'm using a custom ConfigurationProvider for the proxy with each host configured as follows:

![image](https://user-images.githubusercontent.com/11143071/146045943-00440140-9924-4819-9c96-9fb3edf17d62.png)

And the ACME controller looks like this:

![image](https://user-images.githubusercontent.com/11143071/146045999-9cf3735a-5b4a-4a17-91a6-7b6080d9d4dc.png)

**Comment by nabsul** [comment]
I also tried creating a custom route matcher so that I can put `{**catchall:notAcme}`, but that just throws a 404 not found when it's the acme path :-)

**Comment by Tratcher** [comment]
Your setup works fine for me 😁 on .NET 6. Which ASP.NET version are you on? There was a wildcard routing bug in older versions.

**Comment by nabsul** [comment]
I'm on .net6 and Yarp 1.0.0. Just to be clear @Tratcher : Did you test with an http request that includes a hostname other localhost? It goes to the controller if your hostname is localhost and 127.0.0.1.

To repro this locally I have to add an entry to my hostfile so that somedomain.com goes to Yarp (and of course somedomain.com needs to be a domain configured in Yarp).

**Comment by nabsul** [comment]
Ok! This took a lot of digging. I don't think this is the fault of YARP, but an issue with how ASP.NET routing works. I was able to print out all my app's routes, and both YARP and the controller routes appear to be configured correctly, including the "Order" fields. But I guess asp.net prioritizes Host matching over the Order field.

I was finally able to achieve my desired behavior by branching the middleware: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-6.0#branch-the-middleware-pipeline

![image](https://user-images.githubusercontent.com/11143071/146393634-d60cf689-86ea-433c-be2b-f0272ae25b13.png)

**Comment by Tratcher** [comment]
> I'm on .net6 and Yarp 1.0.0. Just to be clear @Tratcher : Did you test with an http request that includes a hostname other localhost? It goes to the controller if your hostname is localhost and 127.0.0.1.
> 
> To repro this locally I have to add an entry to my hostfile so that somedomain.com goes to Yarp (and of course somedomain.com needs to be a domain configured in Yarp).

Yes, I tested with setting the host header to domain1.com matching your setup.

**Comment by nabsul** [comment]
Interesting! I wonder what was different with my setup? I need to wrap this up before my certs expire, but I'll try to repro this in an isolated project.
