### ISSUE TITLE
Service Fabric AuthorizationPolicy support for routes

### ISSUE THREAD

**Issue by francescocristallo** [microsoft/reverse-proxy#1465]
### What should we add or change to make your life better?

Would be great to have an AutorizationPolicy Label for Service Fabric services in ServiceManifest.xml, like:

`<Label Key="YARP.Routes.route2.AuthorizationPolicy">requireAuth</Label>`

### Why is this important to you?

Having this would remove the burden of Authorization from each single service for simple case scenarios

**Comment by Tratcher** [comment]
SF work has moved to https://github.com/microsoft/service-fabric-yarp
