### ISSUE TITLE
Forwarding POST request to downstream .NET service is failing when downstream service is Kerberos/Windows Auth protected

### ISSUE THREAD

**Issue by samanthwal** [microsoft/reverse-proxy#1476]
### Describe the bug

Forwarding POST request to downstream .NET service is failing when downstream service is Auth protected

### To Reproduce

What steps can we follow to reproduce the issue?

Components 

1) Downstream service  (service1) has windows AUTH enabled  which is written in .NET 4.X

3) YARP is enabled like as below with no auth on YARP (proxy)

    services.AddReverseProxy()
        .ConfigureHttpClient((context, handler) =>
        {
            handler.Credentials=CredentialCache.DefaultCredentials;
           handler.UseProxy=false;
        })

Testing Scenarios with sample .NET 5 console application

1) GET proxy/service1/endpoint1 **Works**

**Fiddler trace shows two requests**

 a) 401 without any authentication headers
 b) 200 with www-authenticate Negotiate

2) POST proxy/service1/endpoint1 **Fails**

Fiddler trace shows 1 request
a)  401 without any authentication header

5) When there is no AUTH in downstream services everything works fine.

Got Exceptions? Include both the message and the stack trace
-->
System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.InvalidOperationException: The stream was already consumed.
   at Yarp.ReverseProxy.Forwarder.StreamCopyHttpContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.CopyToAsyncCore(ValueTask copyTask)
   at System.Net.Http.HttpConnection.SendRequestContentAsync(HttpRequestMessage request, HttpContentWriteStream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
 at System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean isProxyAuth, HttpConnection connection, HttpConnectionPool connectionPool, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at  Yarp.ReverseProxy.Forwarder SendAsync
   
 
same is the issue even when downstream service is in .NET 5 Linux

### Further technical details

- Include the version of the packages you are using 
 Yarp.ReverseProxy : Version= 1.0.0

- The platform (Linux/macOS/Windows)
- Windows

**Comment by Tratcher** [comment]
Which user are you expecting to authenticate to the destination service as? `CredentialCache.DefaultCredentials` will give you the user that's running the proxy process, not the user from the client. YARP does not support end-to-end Negotiate/Windows/Kerberos auth, though it should be possible from the client to proxy or from proxy to destination.

Negotiate auth requires a multi-request handshake. This is a problem for POST requests because even when it receives the first 401 response, it has to send the request body. The proxy does not buffer the request body by default, so it's unable to replay the body later after the 200 response. To mitigate this you either need to enable `Expect: 100-continue` on the requests, or to buffer the requests (HttpRequestMessage.Content.LoadIntoBufferAsync() in a request transform).

**Comment by samanthwal** [comment]
Which user are you expecting to authenticate to the destination service as?  => Yes,  I am not trying delegation here but   Negotiate/Windows/Kerberos from proxy to destination.

I had already tried adding Expect: 100-continue in the request transform as 
 **{"RequestHeader": "Expect", "Set" : "100-continue"}**
but it does not work though after setting this I see 408 in fiddler where YARP is sending "Content-Length"=:some number" on 2nd request but body as empty


Not sure what do you mean by that  (HttpRequestMessage.Content.LoadIntoBufferAsync() in a request transform) because I can't find anything like that here or using config as well.

 .AddTransforms(builderContext =>
    {
        
            builderContext.AddRequestTransform(async transformContext =>
            {
               **//Here**
            });
    
    });

PS: I am not using any custom forwarder but default one from YARP.

**Comment by Tratcher** [comment]
> (HttpRequestMessage.Content.LoadIntoBufferAsync() in a request transform) => it worked , does it has side effect on the flow? or there is a better way doing it to avoid performance hit?

There's definitely a perf hit, especially for large bodies. You'll have to measure to see if it's acceptable.

I'm not aware of other workarounds you can try beyond switching the auth type.

**Comment by Mikbau** [comment]
> Thanks @Tratcher Which user are you expecting to authenticate to the destination service as? => Yes, I am not trying delegation here but Negotiate/Windows/Kerberos from proxy to destination.
> 
> I had already tried adding Expect: 100-continue in the request transform as **{"RequestHeader": "Expect", "Set" : "100-continue"}** but it does not work though after setting this I see 408 (Request Body Incomplete) in fiddler where YARP is sending "Content-Length"=some number" on 2nd request but body as empty
> 
> (HttpRequestMessage.Content.LoadIntoBufferAsync() in a request transform) => it worked , does it has side effect on the flow? or there is a better way doing it to avoid performance hit?

Samanthwal,
Would it be possible for you to share the YARP code in which you implement this? I trying to do the same as you, but currently without success (and I've spent days!).

Thank you so much in advance =)

**Comment by Mikbau** [comment]
Hi,
thank you so much! You made not only my day, but my entire week! \o/
I wish you a great day :-)
All the best,
Mike
