### ISSUE TITLE
Adding custom headers, but not seeing them in Fiddler

### ISSUE THREAD

**Issue by sarchibald-mdsol** [microsoft/reverse-proxy#1477]
### Describe the bug
I'm trying to add some headers to all my routes using the code below. But when I look at my requests in Fiddler, I don't see any of my headers added to the final request.

### To Reproduce

Here is the current code:
```c#
public void ConfigureServices(IServiceCollection services)
{
	// Add the reverse proxy to capability to the server
	services.AddReverseProxy()
		.LoadFromConfig(Configuration.GetSection("ReverseProxy"))
		.AddTransforms(builderContext =>
		{
			builderContext.AddPathPrefix(@"/");
			builderContext.AddRequestTransform(async transformContext =>
			{
				transformContext.ProxyRequest.Headers.Add("Authorization", "Basic <hidden-obfuscated>");
				transformContext.ProxyRequest.Headers.Add("Custom-Token", "doodah");
			});
		});

	//services.AddHttpForwarder();
	services.AddCors(options =>
		options.AddPolicy(
			"openPolicy",
			policy =>
				policy
					.AllowAnyOrigin()
					.AllowAnyMethod()
					.AllowAnyHeader()
		)
	);
}
```

Got Exceptions? Include both the message and the stack trace

### Further technical details
YARP 1.0.0
.NET5
React front end
Windows

Here's a snapshot of what's in Fiddler after executing a request:
![2021-12-22 07_44_47-Window](https://user-images.githubusercontent.com/28965834/147121086-8225322f-e22a-4661-b1ce-974b5ec892c6.png)

**Comment by MihaZupan** [comment]
> using the code below

Can you please share the code you are using?

**Comment by sarchibald-mdsol** [comment]
I've updated the original post. I forgot to remove the comment characters...

**Comment by sarchibald-mdsol** [comment]
I’ve updated the original post. I forgot to remove the comment characters around the code…

**Comment by Tratcher** [comment]
Fiddler only shows you the requests from the client to the proxy by default, it doesn't intercept requests from the proxy to the destination without additional config.

Can you share your appsettings.json file as well, it's hard to tell which parts of this flow belong to the proxy.

What are you expecting this to do? `builderContext.AddPathPrefix(@"/");` You wouldn't normally add just a slash to the request path.

**Comment by sarchibald-mdsol** [comment]
Sure.
Here’s the relevant part of the appsettings.
      "AllowedHosts": "*",
      "ReverseProxy": {
            "Routes": {
                  "reportServerRoute": {
                        "ClusterId": "reportServerCluster",
                        "CorsPolicy": "openPolicy",
                        "Match": {
                              "Path": "{**catch-all}"
                        },
                  }
            },
            "Clusters": {
                  "reportServerCluster": {
                        "Destinations": {
                              "reportServerDest": {
                                    "Address": http://modsreporting-dev.mdsol.com/
                              }
                        }
                  }
            }

I used pathprefix of “/” because the documentation for the config version implied a pathprefix was required, and I want all the routes that come into the proxy server to have these headers added. I initially tried without the pathprefix in the code version, but the results are always the same.

If you look at my screenshot, it certainly looks to me like fiddler is capturing the request from the proxy server to the final destination.

**Comment by Tratcher** [comment]
> I used pathprefix of “/” because the documentation for the config version implied a pathprefix was required, and I want all the routes that come into the proxy server to have these headers added. I initially tried without the pathprefix in the code version, but the results are always the same.

Match:Path is required in the route config, AddPathPrefix does something else and is not required, remove it.

It looks like you're being redirected (302) from localhost to `modsreporting-dev.mdsol.com`, so that second request is bypassing the proxy entirely. Some sites do this defensively if the host header doesn't match. You can check the info level logs from the proxy to confirm. https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-6.0#configure-logging

**Comment by sarchibald-mdsol** [comment]
I’m running my proxy server at localhost:44344. The proxy is supposed to forward to https://modsreporting-dev.mdsol.com.

I’m not quite sure what you mean by “host header doesn’t match”…

**Comment by sarchibald-mdsol** [comment]
Maybe I’m trying to set this up incorrectly.
I’m doing some development of a new React app that is a report viewing “portal” for a PowerBI Report server.
My actual report server is found at “https://modsreporting-dev.mdsol.com”.
My app is a react app that is running at “http://localhost:3000”  (Standard for a react app)
My YARP proxy server is running at “https://localhost:44344”.

I have another web api project running at “https://localhost:44300”, but I don’t need to proxy anything going to that address.

I want ALL traffic that is sent to “https://localhost:44344” to be forwarded to “https://modsreporting-dev.mdsol.com” along with the custom headers I’m trying to add.

Have I messed up something in my “ReverseProxy” section of the appsetttings.json?

**Comment by Tratcher** [comment]
Your appsettings.json looks fine then. Check the logs from YARP to see what it says about those requests.

**Comment by samsp-msft** [comment]
@sarchibald-mdsol - following up after the US holidays - did you resolve your issue?

**Comment by SEnglishSMP** [comment]
> Fiddler only shows you the requests from the client to the proxy by default, it doesn't intercept requests from the proxy to the destination without additional config.

@Tratcher Would you please point me to some documentation on what that additional config is?

**Comment by Tratcher** [comment]
Fiddler injects itself as an outbound client proxy. YARP disables outbound client proxy support on HttpClient by default for performance reasons, it expects to be able to directly access destinations. You'd have to turn that back on.

https://microsoft.github.io/reverse-proxy/articles/http-client-config.html#configuring-the-http-client
https://microsoft.github.io/reverse-proxy/articles/http-client-config.html#custom-iforwarderhttpclientfactory

**Comment by SEnglishSMP** [comment]
@Tratcher, thanks.  That got pointed in the right direction.

For anyone else looking to enable Fiddler debugging with YARP, I had to add the following when configuring services:
```cs
services
    .AddReverseProxy()
    .ConfigureHttpClient((context, handler) =>
    {
        handler.UseProxy = true;
        handler.Proxy = WebRequest.DefaultWebProxy;
    });
```
