### ISSUE TITLE
reverse-proxy docs - Routes is ordered or unordered

### ISSUE THREAD

**Issue by kkbruce** [microsoft/reverse-proxy#1483]
I was reading reverse-proxy docs.

In https://microsoft.github.io/reverse-proxy/articles/config-files.html#routes section

```
The routes section is an ordered list of route matches and their associated configuration.
```

In https://microsoft.github.io/reverse-proxy/articles/config-providers.html#routes section

```
The routes section is an unordered collection of named routes. 
```

If the docs are not wrong, can it be understood that it is ordered based on the appsettings.json file and unordered based on the programmatically?

**Comment by Tratcher** [comment]
The first doc is out of date. The routes _used to be_ an ordered list, but that changed quite a while ago.

Feel free to submit a PR correcting that doc.

**Comment by kkbruce** [comment]
@Tratcher 
Help PR review :-)

**Comment by MihaZupan** [comment]
@tratcher Aren't clusters and routes ordered, but destinations unordered in the current version?

**Comment by Tratcher** [comment]
Technically routes and clusters are both lists, but the order is not considered significant:
https://github.com/microsoft/reverse-proxy/blob/66935ec5bac4b231d8384605333503c2cf501011/src/ReverseProxy/Configuration/IProxyConfig.cs#L17-L22

The json config schema uses named objects which does not support ordering:
https://github.com/microsoft/reverse-proxy/blob/66935ec5bac4b231d8384605333503c2cf501011/samples/ReverseProxy.Config.Sample/appsettings.json#L21-L22
https://github.com/microsoft/reverse-proxy/blob/66935ec5bac4b231d8384605333503c2cf501011/samples/ReverseProxy.Config.Sample/appsettings.json#L68-L69
