### ISSUE TITLE
Add RequestTransformContext.Query.Collection Case Insensitivity

### ISSUE THREAD

**Issue by yilativ** [microsoft/reverse-proxy#1496]
### What should we add or change to make your life better?
Currently, the `context.Query.Collection` is case-sensitive. So utilizing things like Match-QueryParameters + Remove Query transform becomes inconsistent when matching a route based on query key with `IsCaseSensitive = false` (default) then wanting to remove that query value it only works if the match is case perfect.

### Why is this important to you?
Consistency of operation with Query Value match and transform functionality already existent. Ability to have the `context.Query` be case insensitive whether through configuration or by default (is there a need for case sensitive query keys?) will alleviate the need for me to do my custom transforms (`QueryParameterRemoveTransform`) because I need it to pick up query string keys regardless of case

Thank you for the work

**Comment by karelz** [comment]
Triage: It is inconsistent with ASP.NET, which defaults to case insensitive treatment. We should fix it.

**Comment by greenEkatherine** [comment]
Merged, kudos to @jerry-shao
