### ISSUE TITLE
YARP is filtering headers (with common names) because of distributed tracing 

### ISSUE THREAD

**Issue by samsp-msft** [microsoft/reverse-proxy#1497]
Long story short, change in net6/yarp filtering out a set of headers breaking our customers  consuming these headers in their business logic.  We did have a workaround deployed to unblock customers.   The ask is whether net6/yarp could expose an simpler option to opt out of such behavior (eg. one line fix).  This would allow us to write less codes especially avoiding manually propagate a pre-hardcoded set of headers.   It would sustain longer term and benefit other using net6/yarp as well.

[Article about headers removed](https://github.com/microsoft/reverse-proxy/blob/main/docs/docfx/articles/header-guidelines.md#traceparent-request-id-tracestate-baggage-correlation-context)
> TraceParent, Request-Id, TraceState, Baggage, Correlation-Context
> These headers relate to distributed tracing. They are automatically removed on .NET 6 or later so that the forwarding HttpClient can replace them with updated values.

**Comment by samsp-msft** [comment]
These headers are filtered because they are used for distributed tracing, and retaining them would cause a conflict. The problem is that distributed tracing is on by default in HttpClient, which is why they are stripped.

I would propose that we add a setting in YARP for both route-based and IHttpProxy usage that toggles distributed tracing and the filtering of these attributes. We can keep the default the same as the behavior today, but if DT is disabled, then the attributes would be allowed to pass, and tracing would be disabled by HttpClient.

**Comment by MihaZupan** [comment]
There are a few main ways a reverse proxy can operate in with regards to distributed tracing:
1. Actively participate in the trace (the default)
    - Requires the user to add an instrumentation library like OpenTelemetry/AppInsights to YARP, or risk breaking the trace for downstream services
    - YARP will parse incoming headers to populate ambient information (create an Activity). It will then remove the headers, allowing HttpClient to add them back with updated values. HttpClient will see there is some ambient state (Activity) and that the headers are not set, so it will add them.
    - If you don't use an instrumentation library, the trace will be broken (there will be an extra unknown node in it, or the headers will be removed altogether).
2.  Passthrough - leave the headers as-is
    - The YARP user has to be aware that some headers are being removed and explicitly re-add them back
    - It has two ways of doing so
      1. Add a transform/middleware that looks at the incoming request and adds the headers to the outgoing request AND set the `DistributedContextPropagator` to `null` / `NoOutputPropagator`[^1]. This will preserve the outgoing request headers as close as possible to the incoming ones.
      2. Set the `DistributedContextPropagator` to the `PassThroughPropagator`[^1]. This will instruct `HttpClient` to add the original headers back to the request. If the headers are not in the correct format for their name (e.g. custom protocol using the same header names), the values may be different.
3. Stop the trace - remove the headers and never add them back
    - This can be achieved by setting the `DistributedContextPropagator` to `null` / `NoOutputPropagator`[^1].

The first option is the default mode of operation for YARP. The reasoning behind it is that users interested in tracing information will want to make YARP actively participate in the trace to gain the most useful information. As such, that scenario works out-of-the-box[^2] just by adding an instrumentation library. See [docs](https://microsoft.github.io/reverse-proxy/articles/distributed-tracing.html).

**The way I understand this, the main questions here are:**
1. Is this the right default for YARP?
    - We rely on `HttpClient` to add headers back, which in turn means we rely on the default `DistributedContextPropagator` as well. Since that default is to always look for ambient information and add the headers, a truly passthrough proxy will always have to change some configuration - YARP can't make it always work well out-of-the-box.
2. Should we make YARP easier to configure for different scenarios?
    - The first scenario works well by default, especially within a .NET ecosystem (see [^2]).
    - The second (passthrough) scenario is not as trivial
      - > The YARP user has to be aware that some headers are being removed and explicitly re-add them back
      - This is a major drawback today - non-obvious and non-configurable behavior.
      - We can add a switch to stop YARP from removing these headers, but users will still have to configure the propagator themselves.
      - I would suggest we clearly document how to achieve passthrough behavior with all the necessary code. That means within the [article about header guidelines](https://github.com/microsoft/reverse-proxy/blob/main/docs/docfx/articles/header-guidelines.md#traceparent-request-id-tracestate-baggage-correlation-context) and possibly also mentioned in a dedicated passthrough article.
3. Is the documentation around this sufficient?
    - Especially for the passthrough case, **no**.

[^1]: The propagator can be set globally via the `DistributedContextPropagator.Current` property or on a per-handler basis via the `SocketsHttpHandler.ActivityHeadersPropagator` property. E.g. 
    ```c#
    DistributedContextPropagator.Current = DistributedContextPropagator.CreatePassThroughPropagator();
    ```
[^2]: As long as you are using W3C/hierarchical traces - the built-in options for .NET. If you are using a different tracing format, you will have to remove headers manually and implement a custom `DistriubutedContextPropagator`, see #1480.

**Comment by MihaZupan** [comment]
Triage: We decided the best approach here is to encapsulate all distributed-tracing-related logic (header modifications) into a custom `DistriubutedContextPropagator`.

We will remove these headers from the remove list in https://github.com/microsoft/reverse-proxy/blob/d9f186a7175dcfb532fe8c57a19082966192ee84/src/ReverseProxy/Forwarder/RequestUtilities.cs#L86-L93 and instead have a custom propagator perform the removes.

The custom propagator will be made public to allow direct forwarding scenarios to consume it and match the current YARP behavior. The propagator will wrap an arbitrary instance of `DistriubutedContextPropagator`, simplifying cases like #1480 to only implementing the desired propagation behavior and letting YARP handle header removal.

These changes will make it so that the major scenarios will both work well & be easily configurable:
- For the case of active participation in the trace, the behavior will be unchanged - it will work out-of-the-box.
- For the passthrough case, the only required change will be setting `SocketsHttpHandler.ActivityHeadersPropagator = null`.
