### ISSUE TITLE
[Tracking] Endpoint routing with middleware

### ISSUE THREAD

**Issue by anurse** [microsoft/reverse-proxy#15]
This will likely be useful for adding middleware to specific routes.
https://github.com/dotnet/aspnetcore/issues/14514

The workaround today is creating your own app builder.
https://github.com/dotnet/proxy/commit/8be62673e25861e283c14aafcc60db2b0ed928b7#diff-a899554e36fdb9c1c365b48b296246cdR35-R37

**Comment by Tratcher** [comment]
Per design decisions elsewhere, we don't need this work item anymore. We decided not to do custom pipelines for routes, but rather to have middleware inspect the route data at runtime and enable/disable themselves (which also works for hosts). The main trouble is that the proxy routes can be reloaded during the lifetime of the app, but pipelines are too complicated to define in config or rebuild every time the proxy config changes.

**Comment by karelz** [comment]
Closing as we don't need it.
