### ISSUE TITLE
Status 502 with accentuated cookie values

### ISSUE THREAD

**Issue by maxsnts** [microsoft/reverse-proxy#1502]
### Describe the bug
If the page being proxied has a cookie with accentuated characters ie: "é" in "José", yarp will not proxy the request and instead give out a 502 status code 

Now, i understand that the cookie value should be encoded, but its not always that we have control over the proxied project.

While the proxied app should be corrected, i think Yearp should at least not give a 502 since that completely prevents navigation.

Thank you

**Comment by MihaZupan** [comment]
The default encoding used for headers is ASCII, but you can change that via config/code. See [HttpClient configuration](https://microsoft.github.io/reverse-proxy/articles/http-client-config.html#httpclient).

```json
"HttpClient": {
    "RequestHeaderEncoding": "utf-8"
}
```

**Comment by Tratcher** [comment]
What error was reported in the logs? A 502 often means an exception was thrown and the request/response couldn't be proxied.

**Comment by MihaZupan** [comment]
`SocketsHttpHandler` will throw if you try sending non-Ascii header values without setting an encoding selector.

**Comment by Tratcher** [comment]
Right, so will Kestrel for the response. I just want to clarify if it's the request or response failing.

**Comment by maxsnts** [comment]
Some times is hard from us outside to connect a problem to a solution.

Maybe a stupid question but, how do i get logging to work so that i would have found this?
It really is not obvious. 
Maybe this info should be part of https://microsoft.github.io/reverse-proxy/articles/getting-started.html.

Anyhow, i will try changing the RequestHeaderEncoding and see if that solves my case.

Thank you

**Comment by Tratcher** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-6.0#configure-logging

**Comment by maxsnts** [comment]
Thank you for all your help.

The problem is indeed the encoding, and changing to utf-8 solves it.

As for logging, i was thinking that is was something more than the standard, something specific to yarp, since i can not seen on the logs any indication of the cause has suggested by MihaZupan.
 
Anyhow, thank you and Best regards

**Comment by maxsnts** [comment]
Should i be the one closing the issue or is preferable that you do it?
