### ISSUE TITLE
LOH in StreamCopier

### ISSUE THREAD

**Issue by Kahbazi** [microsoft/reverse-proxy#151]
Why is the buffer size is _81920_ in `StreamCopier`?

https://github.com/microsoft/reverse-proxy/blob/ca46305dc23519598d831c0fca64e0136476c89b/src/ReverseProxy.Core/Service/Proxy/StreamCopier.cs#L19

Is it to avoid having Large Heap Object? If so I think it still creates a LOH since `ArrayPool<byte>.Shared` is creating arrays with the length of power of 2, and `Rent`ing with length of _81920_ would get a array with size of _131072_.
Or is it ok to have pooled LOH with ArrayPool?

**Comment by ManickaP** [comment]
The same size is in runtime: https://github.com/dotnet/runtime/blob/f7d251fa684dc0c432525eb455be6e06f9629911/src/libraries/System.Private.CoreLib/src/System/IO/Stream.cs#L30-L33 with the argument of fitting under the LOH threshold.

**Comment by ManickaP** [comment]
From the https://github.com/dotnet/runtime/issues/43179#issuecomment-705728338:
> After that I experimented with changing it, but decreasing the buffer size makes a measurable impact on throughout in some cases, and the buffer ends up getting pooled a lot of the time, so it wasn't clear that decreasing it was actually the right call.

So I'm not sure if we'd want to change it. And if we do, we should start with benchmarks and measure the impact before we change anything.

@Kahbazi: Has this caused you any issues, or is it more of that you just noticed it in the code?

**Comment by Kahbazi** [comment]
@ManickaP I have no issue, I was just curios!

**Comment by ManickaP** [comment]
I'll close this for now. If we discover any performance issues due to this we can revisit and adjust the value.
