### ISSUE TITLE
Enable modification of request before Route selection

### ISSUE THREAD

**Issue by tom-puckett** [microsoft/reverse-proxy#1521]
### What should we add or change to make your life better?

I would like to be able to implement a RequestTransform that could analyze the incoming request, modify the request, and either:
- choose an appropriate Route myself (from the configuration provider) to reevaluate the request
- resubmit the modified request to YARP so Route matching can be performed again

### Why is this important to you?
My application allows users to request access to a variety of web applications hosted in containers that are spun up on demand.  When the initial request hits my portal, a Route and Cluster are added to YARP configuration using a custom ProxyConfigProvider.  The browser is then redirected to a URL that will match the new Route using a unique base path identifying the container.  A RequestTransform for that Route then removes the extra part of the path as the container expects.  This is all working.  

However, pages served from the containers have references to resources (e.g. css, script...) that don't include the Path pattern that the existing Route relies on for matching.  For example:
```
<link rel="stylesheet" href="/stylesheets/style.css">
```
Since I'm supporting multiple users, each of whom might be running one or more container sessions, I need a way to resolve such requests for referred resources so they can be forwarded to the correct destination host (configured Cluster).  If there is already a way to handle this I'm happy to change matching strategy, but I don't want to be rewriting references in the html body to make this work, and a cookie seems like no solution because these will be sent to all content for a user (same domain).  I haven't found anything so far but really it seems like this should be a solved problem.  At the end of the story, the result needs to be the use of the correct configured Cluster for the requested resource.  

For now my thinking is to use a high `Order` number (low priority) route with wildcard Path matching, leading to a request transform that would look at the request's `referer` header and make a decision about which other Route (or Cluster) would be appropriate (e.g. which one handled the original page request).  Not sure about any security issues with that idea, but I'd welcome any comments/advice.

**Comment by Tratcher** [comment]
> The browser is then redirected to a URL that will match the new Route using a unique base path identifying the container.

> However, pages served from the containers have references to resources (e.g. css, script...) that don't include the Path pattern that the existing Route relies on for matching. 

PathBase doesn't work well as a proxy routing discriminator for exactly this reason. I haven't seen anyone succeed with that approach. Using different domains or subdomains works a lot better since those are rarely included in resource links.

**Comment by tom-puckett** [comment]
> Using different domains or subdomains works a lot better since those are rarely included in resource links.

Thanks, I understand why that would be the suggested approach for most situations.  The challenge I have is that containers behind my application are ephemeral.  If each of them mapped from a separate domain/subdomain on the public side, we would be needing instantaneous and short lived DNS for large numbers of destinations, which doesn't seem workable (or cost effective).  

The custom IConfigurationProvider has enabled active management of Route/Cluster pairs to accomplish this inside the proxy application, and as mentioned, it seems to be working with the described workaround.  At this point I guess I'm only concerned about the performance implications of sending a request/response through the proxy a second time after revising the initial request.  

I don't know if mine is the only use case, but could this be an argument for a new kind of Transform that is invoked before route selection?  Is there a particular risk (e.g. security) that would make this a bad idea?

**Comment by Tratcher** [comment]
There's an ordering issue there. YARP is route based, so it only knows which requests to act on after routing has run.

You can certainly plug in custom middleware before routing to re-write requests, that should avoid the overhead of proxying them twice.

**Comment by tom-puckett** [comment]
> custom middleware

Middleware makes sense, I'll do that, thanks.  

It would be really useful if my middleware could determine whether YARP has a configured route that will match the modified request (without having to evaluate that myself).  Is there a way I can invoke YARP's route selection logic before routing actually happens?  Bonus for access to the matching Route and Cluster objects.

**Comment by Tratcher** [comment]
YARP doesn't have its own routing, it uses the main route table too.

**Comment by samsp-msft** [comment]
Stepping back a bit. You are likely to always have an issue if sites can use absolute paths.

There is a feature for [wildcard dns](https://en.wikipedia.org/wiki/Wildcard_DNS_record) entries that may work for your scenario. For example you could have a wildcard A record for *.containers.myapp.com, and a separate entry for the initial portal. The wildcard entry would point at the proxy. Requests would come into the portal - then when a container is spun up, you'd get a 302 redirect to <guid>.containers.myapp.com/ - which you would have added to the route table. Using the guid is a bit of security by obscurity but it means that if the user tries to bookmark or come back later when that container has been retired/recycled then they are unlikely to fall into a different instance that is not what they expect.

**Comment by karelz** [comment]
Triage: Looks like a pattern that would struggle in any proxy. YARP can't help here much. See workarounds above. Closing.

**Comment by tom-puckett** [comment]
Thanks all for the consideration.  I'll be switching my Transform to middleware as suggested, with a revisit to an internal conversation with our IT about the wildcard domain approach, which of course is the real answer.  They have balked before but I will try again with more emphasis.
