### ISSUE TITLE
Custom dispatcher and exclude endpoints

### ISSUE THREAD

**Issue by MDzyga** [microsoft/reverse-proxy#1522]
Hi,
### What should we add or change to make your life better?
I want to migrate ProxyKit to YARP and we implemented:
- custom response dispatcher - we have to cache user and client based on incoming token,
- service to exclude endpoints which can't be forwarded to master instance.

### Why is this important to you?
Probably you know how to exclude some endponts, but custom response dispatcher is mandatory because without it we can't cache user and client based on incoming token from master instance.

I added middleware to exclude endpoints but it doesn't work:
```c#
endpoints.MapReverseProxy(proxyBuilder =>
{
    proxyBuilder.Use(async (context, next) =>
    {
      var endpoint = context.GetEndpoint();

      var excludedEndpointsProvider = app.ApplicationServices.GetRequiredService<IExcludedEndpointsProvider>();
      if (excludedEndpointsProvider.IsExcluded(endpoint?.DisplayName, false))
      {
        context.Response.StatusCode = StatusCodes.Status203NonAuthoritative;
        await context.Response.WriteAsync("Endpoint excluded.");
        return;
      }

      await next();
    });

    proxyBuilder.UseLoadBalancing();
});
```

**Comment by Tratcher** [comment]
Your exclusion example looks ok, why do you say it didn't work? Any request that matched that `if` wouldn't be proxied.

> custom response dispatcher - we have to cache user and client based on incoming token,

I'm not sure what you're asking for here, can you give some examples?

**Comment by MDzyga** [comment]
I put breakpoint inside `Use` method and debugger doesn't stop there.

This is my implementation when I use ProxyKit.
```
appBuilder.RunProxy(async proxyContext =>
{
   proxyContext.Request.EnableBuffering();

   var memoryCache = app.ApplicationServices.GetService<IMemoryCache>();
   var masterUrl = memoryCache.Get<string>(Constants.MASTER_URL_CACHE_KEY);

   var forwardContext = proxyContext.ForwardTo(masterUrl).AddXForwardedHeaders();

   var response = await forwardContext.Send();

   using var scope = app.ApplicationServices.CreateScope();
   var handler = scope.ServiceProvider.GetService<IForwardedResponseDispatcher>();
   if (handler != null)
   {
     var isProcessed = await handler.ProcessResponse(response);
     if (!isProcessed && !response.Headers.Contains(RESPONSE_HEADER_NAME))
     {
       response.Headers.Add(RESPONSE_HEADER_NAME, masterUrl);
     }
  }

  return response;
});
```
So, when I get response from master instance, I have to process it differently in one case.

**Comment by Tratcher** [comment]
> I put breakpoint inside `Use` method and debugger doesn't stop there.

But the request still gets proxied? I agree that doesn't make sense, all proxied requests would go through MapReverseProxy and your middleware.

If you're not using the routing system anyways, try the direct proxying API instead, it's much closer to what you were using in proxykit. https://microsoft.github.io/reverse-proxy/articles/direct-forwarding.html

**Comment by MDzyga** [comment]
No, request is not proxied.

**Comment by Tratcher** [comment]
If it's not proxied then it's being handled by a different route. If you enable ASP.NET's Debug logging you should see which route was selected instead.
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-6.0#configure-logging

**Comment by MDzyga** [comment]
We use .Net 5 but I think it will be the same setting

**Comment by MDzyga** [comment]
Hi @Tratcher,
I noticed my mistake.
```
app.UseEndpoints(endpoints =>
{
  endpoints.MapControllers();
  endpoints.UseRequestsProxy();
});
```
When I commented  `endpoints.MapControllers();` it works.
Could you tell me how to combine API with ReverseProxy?
If I have master instance (destination), request should be forwarded to it.
If I don't have master instance or request is excluded, request should be executed on current instance.

**Comment by Tratcher** [comment]
And you know you have a master instance if masterUrl is set? In that case you can make this work by only adding the RouteConfig it masterUrl is set. You'll need to adjust the Order property so it overrides the controllers, int.MinValue should work.

**Comment by MDzyga** [comment]
Hi @Tratcher,
It's working :)
I have one small problem. When I set master instance, all requests are forwarded to it. Some of them can't be forwarded.
```
proxyBuilder.Use(async (context, next) =>
{
  string endpoint = context.Request.Path.ToString().ToLowerInvariant();

  if (!UseProxy(proxyBuilder, endpoint))
  {
    return;
  }

  context.Request.EnableBuffering();

  using IServiceScope scope = proxyBuilder.ApplicationServices.CreateScope();
  var proxyConfigurator = scope.ServiceProvider.GetRequiredService<IProxyConfigProvider>() as CustomProxyConfigProvider;

  string masterUrl = proxyConfigurator?.GetMasterUrl();

  await next();

  if (context.Response.StatusCode == StatusCodes.Status200OK && endpoint.Contains(TOKEN_ENDPOINT))
  {
    var tokenResponseProcessor = scope.ServiceProvider.GetRequiredService<IForwardedTokenResponseProcessor>();
    await tokenResponseProcessor.Process(context.Response, context.Request);

   context.Response.Headers.Add(RESPONSE_HEADER_NAME, masterUrl);
 }
});
```
Do you know how I should confogure YARP to skip these endpoints?
My `return` returns status code 200 instead of executing endpoint locally.

**Comment by Tratcher** [comment]
Can you show the rest of startup for context?

The UseProxy check can't go in the proxy middleware, routing has already happened, nothing else will handle the request if you don't here.

To fully customize when a request should be proxied vs handled locally, you'd need a middleware in front of routing that did the UseProxy check. If the check returned true then you'd call the [proxy APIs](https://microsoft.github.io/reverse-proxy/articles/direct-forwarding.html) directly, and if falls you'd call next so routing could happen.

Also, it's dangerous to try setting response headers after calling next. If the response has a body that has already started (Response.HasStarted) then setting headers will throw, they've already been sent to the client. This kind of check would need to happen in a response transform.
https://microsoft.github.io/reverse-proxy/articles/transforms.html#addresponsetransform

**Comment by samsp-msft** [comment]
Closing as answered, please re-open if you are still facing issues.

**Comment by MDzyga** [comment]
I will chech it soon and let you know if it works

**Comment by MDzyga** [comment]
Hi @Tratcher ,
I rewrote my solution to use direct forwarding but it looks like it doesn't work with API controllers.
Configure
```
app.UseEndpoints(endpoints =>
{
    endpoints.ConfigureProxy(forwarder);
    endpoints.MapControllers();
    endpoints.MapHealthChecks(Constants.HEALTH_ENDPOINT, new HealthCheckOptions
    {
        Predicate = _ => true,
        ResponseWriter = UIResponseWriter.WriteHealthCheckUIResponse
    });
});
```
ConfigureProxy
```
endpoints.Map("{**catch-all}", async httpContext =>
{
    var useProxy = true;
    string requestUrl = httpContext.Request.Path.ToString().ToLowerInvariant();

    using IServiceScope scope = endpoints.ServiceProvider.CreateScope();
    var excludedEndpointsProvider = scope.ServiceProvider.GetRequiredService<IExcludedEndpointsProvider>();
    var memoryCache = scope.ServiceProvider.GetService<IMemoryCache>();
    int? timeoutInSeconds = scope.ServiceProvider.GetRequiredService<IOptions<HttpSettings>>().Value.TimeoutInSeconds;

    if (excludedEndpointsProvider.IsExcluded(requestUrl, false))
    {
        useProxy = false;
    }

    string masterUrl = memoryCache.Get<string>(Constants.MASTER_URL_CACHE_KEY) ?? string.Empty;
    if (string.IsNullOrWhiteSpace(masterUrl))
    {
        useProxy = false;
    }

    var requestConfig = new ForwarderRequestConfig
    {
        ActivityTimeout = timeoutInSeconds.HasValue ? TimeSpan.FromSeconds(timeoutInSeconds.Value) : null,
        AllowResponseBuffering = true,
    };

    var httpClient = new HttpMessageInvoker(new SocketsHttpHandler
    {
        UseProxy = useProxy,
        AllowAutoRedirect = false,
        AutomaticDecompression = DecompressionMethods.None,
        UseCookies = false,
    });

    ForwarderError error = await forwarder.SendAsync(
        httpContext,
        masterUrl,
        httpClient,
        requestConfig,
        new CustomTransformer());

    if (error == ForwarderError.None && useProxy && requestUrl.Contains(TOKEN_ENDPOINT))
    {
        var tokenResponseProcessor = scope.ServiceProvider.GetRequiredService<IForwardedTokenResponseProcessor>();
        await tokenResponseProcessor.Process(httpContext.Response, httpContext.Request);
    }
});
```
I tried to register direct forwarding before and after registering controllers and health check but I got the same result. Requests weren't forwarded.
I verified it using debugger and on master instance I didn't received any requests.

**Comment by MDzyga** [comment]
@samsp-msft how I can open this issue?

**Comment by MDzyga** [comment]
I have 3 different routings patterns:
- api/v{version}/*
- connect/*
- health

In my scenario I have to forward all requests except 6 endpoints:
- */settings/*
- */local
- */certificate/*
- .well-known/openid-configuration

**Comment by MDzyga** [comment]
Hi @Tratcher,
Do you know where I made a mistake in my configuration or how I should configure YARP?

**Comment by MDzyga** [comment]
I prepared a repository to reproduce my scenario.
https://github.com/MDzyga/YARP

**Comment by MDzyga** [comment]
Hi @Tratcher,
do you have some idea how to solve it?
