### ISSUE TITLE
How to get status of destination

### ISSUE THREAD

**Issue by MDzyga** [microsoft/reverse-proxy#1524]
Hi,
### What should we add or change to make your life better?
I configured Active health check and I see it works but I don't know how to get this information.

### Why is this important to you?
We have to display information about master instance (destination) in our application.

**Comment by mgnoonan** [comment]
The HTTP status result is logged, are you looking for something more, like a response payload?

![image](https://user-images.githubusercontent.com/3255096/150369015-cd026eee-5323-4377-8062-3037cb13830a.png)

**Comment by MihaZupan** [comment]
We don't currently have a nice API you could use to query the state of destinations.

See https://github.com/microsoft/reverse-proxy/discussions/1124#discussioncomment-944694 for how you can observe the `DestinationState.Health` from a custom `IClusterChangeListener`.

**Comment by MDzyga** [comment]
Thanks.
Do you think about preparing some solution?

**Comment by adityamandaleeka** [comment]
@Mdzyga this work is covered by https://github.com/microsoft/reverse-proxy/issues/125 which is on our backlog. Closing this issue since it's being tracked there.
