### ISSUE TITLE
Many load balancers need to get ip through proxy protocol , can support proxy protol ?

### ISSUE THREAD

**Issue by markku636** [microsoft/reverse-proxy#1525]
### What should we add or change to make your life better?
Many load balancers need to get ip through proxy protocol , can support proxy protol ?
### Why is this important to you?
get Real ip (user ip )

**Comment by Tratcher** [comment]
Inbound or outbound?
https://github.com/microsoft/reverse-proxy/issues/11
https://github.com/microsoft/reverse-proxy/issues/12

Closing as a duplicate.

**Comment by markku636** [comment]
We need to get the user's ip through the proxy protocol
my network topology

![image](https://user-images.githubusercontent.com/8486599/150454970-59439d6a-1937-4071-bedc-65b0d3427352.png)
