### ISSUE TITLE
GetReverseProxyFeature without Exception

### ISSUE THREAD

**Issue by victortrusov** [microsoft/reverse-proxy#1527]
### What should we add or change to make your life better?
In my opinion, in terms of future usability it would be better to remove Exception throwing from `HttpContextFeaturesExtensions.GetReverseProxyFeature()`:
https://github.com/microsoft/reverse-proxy/blob/a323abe22131818853ae523420d5aa72bf9d9d93/src/ReverseProxy/Model/HttpContextFeaturesExtensions.cs#L33

### Why is this important to you?
It becomes harder to use this extension method you start adding endpoints that don't use reverse-proxy functionality. E.g. if you use `GetReverseProxyFeature()` somewhere in the middleware, you need either to wrap this code in try-catch block (not-optimal) or to define whether the current context use reverse-proxy or not beforehand.
Unfortunately, I couldn't find a better solution for the second option than just to use `context.Features.Get<IReverseProxyFeature>()`. What makes me think that it may actually be better to just return `null` in `GetReverseProxyFeature()` if the reverse-proxy feature is not used in the current `HttpContext`. And for users it may be as a way to define whether the current context uses reverse proxy or not and as a way to retrieve information about proxy at the same time.

**Comment by Tratcher** [comment]
We expected GetReverseProxyFeature to only be used in proxy middleware. Can you show how you'd use it in general middleware to light up functionality? The feature is only added at the start of the proxy pipeline, so other middleware would only be able to see it after the `next` middleware ran.

**Comment by victortrusov** [comment]
In my case it's a logging middleware where I log information about the request and the response (like URL, status code, etc.). I need `IReverseProxyFeature` to log whether this request was proxied or not if yes then where.

```
GET /test proxied to api(http://localhost:3000) responded 404 in 0.56 ms
GET /metrics responded 200 in 0.61 ms
```

**Comment by Tratcher** [comment]
Interesting. Is there a reason you're not enabling the proxy's own logs for that?

`context.Features.Get<IReverseProxyFeature>()` seems like an adequate mitigation for now. Most places I've seen GetReverseProxyFeature used do require the feature to be present, and I wouldn't want to weaken that guarantee. That's the main reason we introduced GetReverseProxyFeature instead of using `Features.Get` directly.

**Comment by victortrusov** [comment]
Mainly because to get all this information I need 2 proxy's default logs instead of 1. And for logging in the production it would be too much.
```
Request starting HTTP/1.1 GET http://localhost:5000/api/test - -
Proxying to http://localhost:3000/test HTTP/2 RequestVersionOrLower no-streaming
Request finished HTTP/1.1 GET http://localhost:5000/api/test - - - 200 - text/html;+charset=utf-8 1.6746ms
```
Also, as I have non-proxy endpoints, logging everything in one place seems like the right thing to do.

But in general, it's not a big thing. Maybe it's worth mentioning `context.Features.Get<IReverseProxyFeature>()` in docs as a way to deal with such situations. Also
> The feature is only added at the start of the proxy pipeline, so other middleware would only be able to see it after the next middleware ran.

is a super helpful information, thanks!

**Comment by pinkfloydx33** [comment]
I had a similar issue with UseExceptionHandler and Status Code pages just yesterday. We wanted to display slightly different information/data if the request was one that was (supposed to be) proxied, vs some other auxiliary routes living in our app. Also if the exception occurred before hitting the proxying functionality, trying to get the feature in the exception handler threw as well. I had to use the same work around as above. Not a big deal, but it was a surprise.

**Comment by karelz** [comment]
Triage: Looks like reasonable workaround exists.
We think the main scenario benefits from throwing exceptions (instead of getting 'random' `NullReferenceException`). Therefore we don't plan to change the default behavior.
