### ISSUE TITLE
Branch for preview 1

### ISSUE THREAD

**Issue by anurse** [microsoft/reverse-proxy#153]
It’s probably time to branch for preview 1. We need to:

* [x] Create preview 1 branch `release/1.0.0-preview1` 
* [x] Update `master` branding to `1.0.0-preview.2`
* [x] Update `master` subscriptions to get .NET from `.NET 5 Preview 5` channel (which is about to snap)

**Comment by Tratcher** [comment]
Would like to merge https://github.com/microsoft/reverse-proxy/issues/128 first since it's quite breaking.
