### ISSUE TITLE
Route order not respected for "*" host

### ISSUE THREAD

**Issue by luk355** [microsoft/reverse-proxy#1530]
### Describe the bug

Route order is not respected for routes with "*" wildcard in the hosts - see "To Reproduce" section.

### To Reproduce

Setup proxy with following configuration:

```csharp
public class EsProxyConfig : IProxyConfig
{
    private readonly CancellationTokenSource _cts = new CancellationTokenSource();

    public EsProxyConfig()
    {
        ChangeToken = new CancellationChangeToken(_cts.Token);
    }

    public IReadOnlyList<RouteConfig> Routes => new List<RouteConfig>()
    {
        new RouteConfig()
        {
             ClusterId = "httpbin",
             RouteId = "httpbin",
             Match = new RouteMatch() {
                 Path = "{**catch-all}",
                 Hosts = new[] { "*" }
             },
             Order= 1
        },
        new RouteConfig()
        {
             ClusterId = "github",
             RouteId = "github",
             Match = new RouteMatch() {
                 Path = "{**catch-all}",
                 Hosts = new[] { "foo-localhost" }
             },
             Order= 10
        }
    };

    public IReadOnlyList<ClusterConfig> Clusters => new List<ClusterConfig>() {
        new ClusterConfig()
        {
               ClusterId = "httpbin",
               Destinations = new Dictionary<string, DestinationConfig>(StringComparer.OrdinalIgnoreCase)
                {
                    { "destination", new DestinationConfig() { Address = "https://httpbin.org" } },
               }
        },
        new ClusterConfig()
        {
               ClusterId = "github",
               Destinations = new Dictionary<string, DestinationConfig>(StringComparer.OrdinalIgnoreCase)
                {
                    { "destination", new DestinationConfig() { Address = "https://github.com" } },
               },
        }
        
    };

    public IChangeToken ChangeToken { get; }
}
```

The httpbin route has "*" wildcard provided in the hosts and has lower order - therefore all requests to the proxy should be routed to httpbin. Given the proxy running on localhost, see the requests toghether with expected/and the actual route (wrong routing highlighted as bold):

| Request                                                           | Expected route | The actual route |
| ------------------------------------------------- | ---------------- | ------------------ |
| curl http://localhost                                         | httpbin             | httpbin               |
|  curl -H "Host:foo-localhost" http://localhost | httpbin             | **github**          |

To get the routing work as expected, hosts configuration from httpbin route can be ommited as shown below.

```csharp
new RouteConfig()
{
     ClusterId = "httpbin",
     RouteId = "httpbin",
     Match = new RouteMatch() {
         Path = "{**catch-all}",
// REMOVE HOSTS CONFIGURATION
//         Hosts = new[] { "*" }
     },
     Order= 1
},
```

### Further technical details

- .NET 6
- YARP.ReverseProxy v1.0.0
- Platform: Windows

**Comment by Tratcher** [comment]
We'll have to do some research to better understand the behavior.

While this does deserve an explanation, I don't expect there's anything YARP could/would do to change it since Host routing is a built-in ASP.NET Core component.

**Comment by karelz** [comment]
This issue was moved to dotnet/aspnetcore#39920
