### ISSUE TITLE
H2-H2 benchmark runs are randomly failing

### ISSUE THREAD

**Issue by MihaZupan** [microsoft/reverse-proxy#1531]
Some H2-H2 tests on the daily benchmark runs are randomly failing, leaving big time gaps on the dashboard.
There are also other oddities e.g. H2H2 POST scenarios for 10/100 kB are 20 times faster than 1 kB (because they're all errors).
[Example from today's run](https://dev.azure.com/dnceng/internal/_build/results?buildId=1570420&view=logs&j=e7951ff2-c247-5999-e0c4-5df736aae045&t=81b9a94d-92d6-5fe6-e83f-2e5e2a4bf8b8).

**Comment by adityamandaleeka** [comment]
cc @sebastienros

**Comment by MihaZupan** [comment]
Most of this should be resolved now. I'm monitoring the dashboards
