### ISSUE TITLE
Test header encoding end-to-end

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#154]
The HTTP spec has never been clear about proper header encoding and some clients send UTF-8 or Latin1 data. The proxy needs to be as transparent as possible to such issues, or at least give the developer adequate control over the behavior.

Test scenarios:
- Request - Main issue, the developer rarely controls the client behavior
  - UTF-8 for known headers (Host, Referrer) and custom headers
  - Latin1 for known headers (Host, Referrer) and custom headers
- Response - Less of a problem since the developer has more control over these
  - UTF-8 for known headers (Location) and custom headers
  - Latin1 for known headers (Location) and custom headers
- Servers
  - Kestrel
    - Request: [UTF-8](https://github.com/aspnet/KestrelHttpServer/issues/1144). Requires an opt-in setting to get Latin1 (https://github.com/dotnet/aspnetcore/issues/17400)
    - Response: ASCII only.
  - HttpSys - Uses [UTF-8](https://github.com/dotnet/aspnetcore/blob/a278ef6304b265926b2ea958330ab0b2bf34431f/src/Shared/HttpSys/RequestProcessing/HeaderEncoding.cs#L14)
  - IIS In-Proc - Same as HttpSys
  - IIS Out-of-Proc - Known to corrupt non-ascii headers when forwarding requests using WinHttp
- HttpClient
  - Request: Known to [disallow](https://github.com/dotnet/runtime/blob/30119554b2be144ceff06a41326345975dd178f9/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs#L1142-L1145) sending non-ascii request headers
  - Response: 
    - Custom Location [decoding](https://github.com/dotnet/runtime/blob/30119554b2be144ceff06a41326345975dd178f9/src/libraries/System.Net.Http/src/System/Net/Http/Headers/HeaderDescriptor.cs#L149-L156)
    - Otherwise [iso-8859-1](https://github.com/dotnet/runtime/blob/30119554b2be144ceff06a41326345975dd178f9/src/libraries/System.Net.Http/src/System/Net/Http/HttpRuleParser.cs#L21-L22), aka Latin1

**Comment by halter73** [comment]
[Kestrel accepts UTF-8 encoded request headers](https://github.com/aspnet/KestrelHttpServer/issues/1144), but only produces ASCII encoded response headers. I've updated the issue to reflect this.

I'm not sure about HttpSys/IIS. Are both request and response headers always UTF-8 decoded/encoded (ignoring out-of-proc)?

**Comment by karelz** [comment]
Triage: Seems to be covered by #760 -- we should be good for now. Pending user feedback.
