### ISSUE TITLE
IHttpForwarder and cancellation

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#1542]
IHttpForwarder.SendAsync does not directly accept a CancellationToken to abort it. It supports canceling if the ForwarderRequestConfig.ActivityTimeout expires, or if HttpContext.RequestAborted triggers (client disconnect).
https://github.com/microsoft/reverse-proxy/blob/79c88ce07f9b88a283e10fc4cc45287b2efa6750/src/ReverseProxy/Forwarder/IHttpForwarder.cs#L25-L26

A customer that wanted to add their own cancellation condition did so by replacing HttpContext.RequestAborted. However, this caused an issue where they were leaking resources because they were no longer responding to the original RequestAborted token. The fix was to chain the two tokens.

Feedback: Having a CancellationToken parameter on IHttpForwarder.SendAsync would make this less error prone.

**Comment by MihaZupan** [comment]
> Having a CancellationToken parameter on IHttpForwarder.SendAsync would make this less error prone

I agree with this from the perspective of runtime APIs, but this doesn't seem to be the pattern AspNet follows to my knowledge:
- Middleware don't give you `CancellationToken`s explicitly - you are expected to use `HttpContext.RequestAborted`
- Same thing for MVC controllers
- You can't inject a CT into minimal APIs
```c#
app.MapGet("/delay1", async (CancellationToken ct) => // blows up at runtime
{
    while (true)
    {
        Console.WriteLine(ct.IsCancellationRequested);
        await Task.Delay(1000);
    }
});

app.MapGet("/delay2", async (HttpContext context) =>
{
    while (true)
    {
        Console.WriteLine(context.RequestAborted.IsCancellationRequested);
        await Task.Delay(1000);
    }
});
```

With YARP being in the middle between runtime and AspNet, do we believe YARP users are more error-prone to this than those of other web apps?

**Comment by davidfowl** [comment]
@MihaZupan 

> You can't inject a CT into minimal APIs

You can and also into MVC controller actions.

**Comment by MihaZupan** [comment]
> You can and also into MVC controller actions.

Oh was that added in 7?
