### ISSUE TITLE
Loosing RemoteIpAddress when acting as reverse proxy

### ISSUE THREAD

**Issue by alphajoza** [microsoft/reverse-proxy#1543]
I have an asp.net core web application that can access to the request IP via `HttpContext.Connection.RemoteIpAddress` the application itself is listening to `http://127.0.0.1:5090` but when putting it behind the reverse proxy as the following configuration shows, my web app detects `HttpContext.Connection.RemoteIpAddress` equal to "127.0.0.1".

```
{
    "Logging": {
        "LogLevel": {
            "Default": "Information"
        }
    },
    "AllowedHosts": "*",
    "Kestrel": {
        "Endpoints": {
            "Http": {
                "Url": "http://my-public-ip-here:80"
            }
        }
    },
    "ReverseProxy": {
        "Routes": {
            "route1": {
                "ClusterId": "cluster1",
                "Match": {
                    "Hosts": [ "my-domain-name-here.com" ]
                },
                "Transforms": [
                	{ "RequestHeadersCopy": "true" },
          		{ "RequestHeaderOriginalHost": "true" }
                ]
            }
        },
        "Clusters": {
            "cluster1": {
                "Destinations": {
                    "destination1": {
                        "Address": "http://127.0.0.1:5090/"
                    }
                }
            }
        }
    }
}
```

**Comment by Tratcher** [comment]
That's common with any proxy. The following docs should help:
https://microsoft.github.io/reverse-proxy/articles/header-guidelines.html#x-forwarded--forwarded
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-6.0
https://microsoft.github.io/reverse-proxy/articles/transforms.html#defaults

**Comment by samsp-msft** [comment]
Triage: Closing as answered, please re-open if there are more issues.
