### ISSUE TITLE
Test end-to-end multi-value header support

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#155]
In theory the HTTP spec allows any multi-value headers to be represented as a single comma separated list or as multiple `key: value` headers. In practice there are at least two headers that break clients if merged to a single line, Set-Cookie and WWW-Authenticate.

Test the end-to-end experience for multi-value request and response headers, especially Set-Cookie and WWW-Authenticate. A header's format should be maintained as much as possible in either direction. E.g. don't split up a comma separated list into multiple headers, and don't combine multiple headers into a comma separated list.

There are known issues with Http.Sys and IIS data structures combining multi-value request headers.

**Comment by Tratcher** [comment]
https://github.com/microsoft/reverse-proxy/issues/437 is a good example of how this can break.

**Comment by Tratcher** [comment]
Another example:
https://github.com/microsoft/reverse-proxy/issues/467#issuecomment-734093762

**Comment by samsp-msft** [comment]
Tagging as its the kind of thing that will cause problems for one of our services.
