### ISSUE TITLE
Consider enforcing is null instead of == null

### ISSUE THREAD

**Issue by Kahbazi** [microsoft/reverse-proxy#1552]
In order to follow the style of ASP.NET Core repo, `is null` should be used instead of `== null`.

I'll send a PR, if this design is approved.

**Comment by samsp-msft** [comment]
Not high priority, but seems like a good thing to do. It should probably also include turning on an analyzer so we get build time feedback if it gets broken in future.

**Comment by MihaZupan** [comment]
We should wait at least until #1560 is merged to avoid conflicts
