### ISSUE TITLE
Direct Forwarding to a load balanced site - load not routinely redistributed

### ISSUE THREAD

**Issue by john--** [microsoft/reverse-proxy#1555]
Preface: Not really a bug with YARP, simply encountering behavior I'm having trouble explaining.

### Describe the bug

I'm using YARP with "Direct Forwarding".
One of my destinations is a layer-4 load balanced API, which contain 2 instances under it (API1, API2).

What I've noticed is that the requests to the underlying API instances don't get evenly distributed over time. Sometimes the traffic is a 75/25 split. Sometimes 100/0. Basically, whatever split it starts with, it sticks with, until the app pool recycles or the site restarts.

### To Reproduce
Setup YARP with Direct Forwarding to a layer-4 load balanced site, with two servers under it called API1 and API2.

Try turning the API1 instances offline to force a all traffic through API2.
Start up the YARP instance, create a large amount of traffic against the load balanced API. Maintain this traffic.
Turn API1 back on. Validate that it's under the load balancer.

Notice that even though both API1 and API2 are healthy, all traffic is still routed to API2.

### Further technical details

Recently migrated from ProxyKit, which didn't seem to have this issue.
YARP 1.0.
Windows server using a self-contained executable on .NET 6.

### Commentary.

My thought here is that there could be connection pooling holding all the connections open which is preventing us from routinely hitting the load balancer again for a new connection. Because it's layer-4 load balancing, there is no termination at the load balancer, and the connection simply gets passed through. So the "start state" of the YARP application is maintained even though the health and load of API1 and API2 are constantly changing throughout the day.

Does YARP use thePooledConnectionLifetime? Would simply changing that to a non-infinite value potentially solve my problem?

https://docs.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler.pooledconnectionlifetime?view=net-6.0

I really hate to bother the YARP developers, but this issue is particularly hard to test in my dev environment, so I figured asking questions never hurts. Any feedback would be much appreciated.

**Comment by samsp-msft** [comment]
Yes, YARP will use connection pooling from the proxy to the the destination. Depending on the HTTP version being used, that can result in few connections. AFAICR HTTP/2 will default to allowing 100 concurrent requests per connection. HTTP/1.1 will re-use the connection.
You can configure lifetime for the HttpClient used by YARP to control the lifetime properties, by configuring the SocketsHttpHandler used by it.

See https://microsoft.github.io/reverse-proxy/articles/direct-forwarding.html
https://docs.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler?view=net-6.0

The problem is that your L4 load distributor probably isn't designed for use when you have a reverse proxy - it works when load comes from a large number of clients, but in this case, the load is coming from one machine, and its designed to be as efficient as possible with connection re-use so that it can get the best performance,

Can you talk to the destinations directly rather than going through the L4? That may be more efficient in this case.

**Comment by john--** [comment]
Thank you @samsp-msft for the thorough response.

> Can you talk to the destinations directly rather than going through the L4? That may be more efficient in this case.

This might be a little more of a pain from an environment configuration perspective, but definitely possible and something to consider.

Just to confirm, if I do go the HttpClient/SocketsHttpHandler configuration route, PooledConnectionLifetime is the correct property to look at?

**Comment by samsp-msft** [comment]
Yes `PooledConnectionLifetime` is the overall time a connection will be kept for, and `PooledConnectionIdleTimeout` is how long it can remain idle before its dropped.

**Comment by MihaZupan** [comment]
> Does YARP use thePooledConnectionLifetime? Would simply changing that to a non-infinite value potentially solve my problem?

Likely not in the way you may expect - the traffic would start oscillating between the destinations.
At first, most traffic would go to one connection, then `PooledConnectionLifetime` kicks in and all the traffic starts going to the second one.
If you looked at the load across the apps over a longer time period, they may show a similar number, but if you looked at a shorter time period, most traffic would still be going to a single one.

`SocketsHttpHandler` won't create a new `HTTP/1.1` connection if an existing one can be reused. Seeing unbalanced traffic after your L4 balancer means that most requests were served by a single connection (never giving the balancer the opportunity to *balance*).
That means that the proxy never (or rarely) received multiple requests in parallel, as that would have forced it to open multiple connections to your L4 balancer.

That is, you would likely already get an even split between the apps given more load (more requests).
To get an even split even at lesser loads (when all requests can be handled by a single connection), a better approach may be to define both apps as separate destinations in YARP and drop the L4 balancer.

Alternatively, you could trick YARP into "load-balancing" the requests to the same destination by adding two destinations with different addresses that both resolve to the L4 balancer.
For example:
```json
"Destinations": {
  "L4_a": { "Address": "https://L4-a/" },
  "L4_b": { "Address": "https://L4-b/" }
}
```
and then have `L4-a` and `L4-b` resolve to the same IP (using the hosts file, or by manually creating connections via `SocketsHttpHandler`'s `ConnectCallback` ...)

**Comment by john--** [comment]
Thank you both for all of the detail. This is great information. I'll mark this as closed.
