### ISSUE TITLE
Updates to Destination Address not reflected everywhere

### ISSUE THREAD

**Issue by pinkfloydx33** [microsoft/reverse-proxy#1566]
### Describe the bug
Changes to the address of a destination made after the app is running don't appear to propagate entirely. Using the reverse proxy feature the address seems to differ depending on how it's retrieved/viewed.

### To Reproduce

Start with the basic YARP application and replace `MapReverseProxy` with the the following:
```csharp
endpoints.MapReverseProxy(proxy =>
{
    proxy.Use(async (HttpContext context, RequestDelegate _) =>
    {
        var rp = context.GetReverseProxyFeature();
        var output = @$"{rp.Cluster.Config.Destinations!["test"].Address}
{rp.Route.Cluster!.Model.Config.Destinations!["test"].Address}
{rp.Route.Cluster!.DestinationsState.AllDestinations[0].Model.Config.Address}
{rp.Route.Cluster.Destinations["test"].Model.Config.Address}";

        await context.Response.WriteAsync(output);
    });

    proxy.UseSessionAffinity();
    proxy.UseLoadBalancing();
    proxy.UsePassiveHealthChecks();
});

```

**Start** with the following configuration:

```json
{
    "ReverseProxy": {
        "Routes": {
            "test": {
                "ClusterId": "test",
                "Match": {
                    "Path": "/{**catch-all}"
                }
            }
        },
        "Clusters": {
            "test": {
                "Destinations": {
                    "test": {
                        "Address": "https://www.microsoft.com/"
                    }
                }
            }
        }
    }
}
```

Start the application and navigate to it, i.e. `https://localhost:5000/`. The following should be printed:

> https://microsoft.com/
> https://microsoft.com/
> https://microsoft.com/
> https://microsoft.com/

With the application running, modify the address of the `test/test` destination to `https://www.google.com/`. Now reload/re-navigate. The following will be printed:

> https://microsoft.com/
> https://microsoft.com/
> https://google.com/
> https://google.com/

### Further technical details
Running YARP 1.0.0 on NET6.0

I am not sure if this is actually a problem/something that would matter in practice. I stumbled upon this by accident during a local debug session when I forgot to revert a change to the destination address, which I then made on the spot. I happened to be inspecting the Reverse Proxy feature for something completely unrelated and noticed that the old value was still there and didn't seem to update no matter how long I left the application running.

This doesn't impact me as I'm not using it for anything. I just happened to notice the mismatch and figured I'd report it just in case.

**Comment by pinkfloydx33** [comment]
Additional notes: 
It looks like this isn't limited to address. For instance, start with a config that looks like the above, but then add a second destination while the app is running. The new destinations don't get reflected in all the same places:

```csharp
var c1 = rp.Cluster.Config.Destinations.Count;  // 1
var c2 = rp.Route.Cluster.Model.Config.Destinations.Count; // 1
var c3 = rp.Route.Cluster.DestinationsState.AllDestinations.Count; // 2
var c4 = rp.Route.Cluster.Destinations.Count; // 2
var c5 = rp.AllDestinations.Count; // 2
```

Could this be related to the fact that Health checks aren't enabled and so nothing(?) is actively monitoring the `ClusterState`?

**Comment by MihaZupan** [comment]
This is an artifact of the fact that we treat destination updates differently from other cluster config changes. If only the destinations are updated (common case), we avoid recreating the endpoint. The way we currently achieve that is by not updating the `ClusterModel` on destination changes.

Obviously, the observable behavior you discovered is very odd and confusing. I would consider it a bug.
We should change our logic to properly update these structures.
