### ISSUE TITLE
CORS preflight requests trigger and fail route configured AuthorizationPolicy

### ISSUE THREAD

**Issue by SharpKing** [microsoft/reverse-proxy#1567]
CORS preflight check sends an OPTIONS request that is triggering a route's configured AuthorizationPolicy. The policy then fails because the request is missing required authorization information to validate against the policy's set requirements. 

I believe that preflight requests should bypass any configured AuthorizationPolicy. To accomplish a workaround, I am currently implementing a custom AuthorizationHandler that automatically passes any OPTIONS method requests.

### To Reproduce:
In Startup.cs: 
*for example simplicity I used .RequireClaim() but any Requirements that rely on auth information (from the jwt in this case) will fail because auth headers are not sent with cors preflight requests.
```
services.AddAuthentication(options =>
{
	JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();
})
.AddJwtBearer(JwtBearerDefaults.AuthenticationScheme, options => {
	options.Authority = Configuration.GetValue<string>("AppSettings:AuthorityIssuer");
	options.TokenValidationParameters.ValidateAudience = false;
});
services.AddAuthorization(options =>
{
	options.AddPolicy("API_Policy", policy =>
	{
		policy.AddAuthenticationSchemes(JwtBearerDefaults.AuthenticationScheme)
		.RequireClaim("scope", "ApiScope");
	});
});
services.AddCors(options =>
{
	options.AddPolicy("corsPolicy", builder =>
	{
		builder.SetIsOriginAllowed(s => true).AllowAnyMethod().AllowAnyHeader().AllowCredentials();
	});
});
```

In appsettings.json:
```
"ReverseProxy": {
    "Routes": {
      "route1": {
        "ClusterId": "cluster1",
        "CorsPolicy": "corsPolicy",
        "AuthorizationPolicy": "API_Policy",
        "Match": {
          "Path": "/v1/{**remainder}"
        },
        "Transforms": [
          { "PathPattern": "/{**remainder}" }
        ]
      }
    },
    "Clusters": {
      "cluster1": {
        "Destinations": {
          "Default": {
            "Address": "https://example.com"
          }
        },
        "HttpRequest": {
          "ActivityTimeout": "00:00:10"
        }
      }
    }
  }
```

### Request Result
>AuthenticationScheme: Bearer was not authenticated.
>Authorization failed. These requirements were not met: ClaimsAuthorizationRequirement:Claim.Type=scope and Claim.Value is one of the following values: (ApiScope)

### Further technical details

- Include the version of the packages you are using : Yarp.ReverseProxy Version="1.0.0"
- The platform (Linux/macOS/Windows): Windows 10

**Comment by Tratcher** [comment]
CORS should work so long as you handle it before auth. Can you share your middleware pipeline?

**Comment by SharpKing** [comment]
Per your comment, I moved my app.UseCors() call to before app.UseAuthentication() and it worked....middleware order strikes again....time to bookmark [https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-6.0#middleware-order](url).

It would be nice if the framework/compiler could notice and call out mistakes like this, perhaps as a warning.

Thanks!

before: (broken)
```
public void Configure(IApplicationBuilder app)
        {
            app.UseRouting();
            app.UseAuthentication();
            app.UseAuthorization();
            app.UseCors();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapHealthChecks("/health");
                endpoints.MapReverseProxy();
            });
        }
```

after: (works)
```
public void Configure(IApplicationBuilder app)
        {
            app.UseRouting();
            app.UseCors();
            app.UseAuthentication();
            app.UseAuthorization();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapHealthChecks("/health");
                endpoints.MapReverseProxy();
            });
        }
```
