### ISSUE TITLE
The pathpattern does not take effect

### ISSUE THREAD

**Issue by jinzaz** [microsoft/reverse-proxy#1577]
### Some details

**How many backends are in your application?**

- [x] 1-2
- [ ] 3-5
- [ ] 6-10
- [ ] 10+

**How do you host your application?**

- [ ] Kubernetes
- [ ] Azure App Service
- [ ] Azure VMs
- [ ] Other Cloud Provider (please include details below)
- [x] Other Hosting model (please include details below)

### What did you think of YARP?

**Comment by jinzaz** [comment]
My Appsettings are configured like this

**Comment by jinzaz** [comment]
"Match": {
          "Path": "/api/Identity/{template1}/{template2}",
          "Methods": [ "POST" ],
          "CorsPolicy": "disable",
          "Transforms": [ // List of transforms. See ReverseProxy.Transforms.Sample for more details
            { "PathPattern": "/{template1}/{template2}" },
            { "RequestHeadersCopy": "true" },
            { "RequestHeaderOriginalHost": "true" }
          ]

But when I use this path "https://localhost:port/api/Identity/WeatherForecast/va" to request ,
The path received by the server is ”/api/Identity/WeatherForecast/va“.
Obviously, it hasn't changed.


            services.AddReverseProxy()
                .LoadFromConfig(Configuration.GetSection("ReverseProxy"))
                .AddConfigFilter<ReverseProxyConfigFilter>()
                .AddTransforms<MyTransformProvider>()
                .AddTransformFactory<MyTransformFactory>()
                .AddTransforms(transformBuilderContext => {

                    //transformBuilderContext.AddPathPrefix("/prefix");
                    if (string.Equals("token", transformBuilderContext.Route.AuthorizationPolicy))
                    {
                        transformBuilderContext.AddRequestTransform(async transformContext => {
                            var ticket = await transformContext.HttpContext.AuthenticateAsync("token");
                            var tokenService = transformContext.HttpContext.RequestServices.GetRequiredService<TokenService>();
                            var token = await tokenService.GetAuthTokenAsync(ticket.Principal);
                            transformContext.ProxyRequest.Headers.Authorization = new AuthenticationHeaderValue("Bearer",token);
                        });
                    
                    }

                });

**Comment by MihaZupan** [comment]
You are specifying `CorsPolicy` and `Transforms` under the `Match`. These are not options for a match, but for the route.

Try something like the following instead:
```json
"Match": {
  "Path": "/api/Identity/{template1}/{template2}",
  "Methods": [ "POST" ]
},
"Transforms": [
  { "PathPattern": "/{template1}/{template2}" },
  { "RequestHeaderOriginalHost": "true" }
]
```

**Comment by jinzaz** [comment]
Thank you. I was careless
