### ISSUE TITLE
Add support to Http.sys delegation to handle receiver restarts

### ISSUE THREAD

**Issue by NGloreous** [microsoft/reverse-proxy#1587]
This expands on #1503. 

When using http.sys delegation, there are two processes involved, the delegator (the process creating the DelegationRule to delegate requests it receives) and the receiver (the process the delegator transfers requests to). It's possible that the receiver may restart independently from the delegator and ideally, delegation continues to work once the receiver has finished restarting. 

The problem is the delegator has a handle open to the receiver's queue which prevents it from getting removed when the receiver shuts down. There are two possible issues due to this:

1. The receiver may fail to properly start because trying to create the queue will fail. Instead, the receiver needs to be smart enough to attach instead and properly re-configure the queue. The current ASP.NET core http.sys server does not support this (https://github.com/dotnet/aspnetcore/issues/40359), and I wouldn't expect most others to either since this is a newer concept. 
2. If the receiver does attach and re-configure the queue, delegation will fail due to this bug: https://github.com/dotnet/aspnetcore/issues/40358.

To work around \# 2, we can check if the error received while delegating is `ERROR_INVALID_PARAMETER`, and if so dispose and re-create the DelegationRule.

Solving for \# 1 is less straightforward. There is no way to get notified when the receiver detaches from the queue. We could poll but that doesn't seem ideal. Another option would be to monitor for when the receiver process exits and when it does to dispose the rule so it can properly start back up. 

I suggest we add support for consumers to "reset" a rule. This allows consumers to setup any type of monitoring they would like and then gives them the ability to force the DelegationRule to be rest.

I suggest adding the below public interface to allow for this:

```C#
public interface IHttpSysDelegator
{
    void ResetDestination(DestinationState destination);
}
```

**Comment by Tratcher** [comment]
Why pass in a DestinationState? If it's an out of process resource being monitored, I'd expect the inputs to that method to match those from the original config: the queue name and url prefix.

**Comment by NGloreous** [comment]
queue name and url prefix also make sense. I was debating which one to use or I guess we could support both?

**Comment by NGloreous** [comment]
I forgot to mention one other mitigation for #1 we could do within YARP. If we get a `ERROR_FILE_NOT_FOUND` error during delegation, we could reset the rule. This mitigation should probably be opt-in based on destination since it depends on receiver behavior. This mitigation may be "good enough" for some.

I was thinking of something like below. @Tratcher thoughts? 

```json
"Destinations": {
  "SampleHttpSysServer": {
    "Address": "http://localhost:5600/",
    "Metadata": {
      "HttpSysDelegationQueue": "SampleHttpSysServerQueue",
      "ResetDelegationQueueOnErrorNotFound": "true"
    }
  }
}
```

**Comment by Tratcher** [comment]
`ERROR_FILE_NOT_FOUND` is the error returned if you try to delegate while the destination is down? If you reset the rule immediately, won't that still prevent the destination from coming back up? And wouldn't you end up trying to reset the rule on every request until it worked?

**Comment by NGloreous** [comment]
Yes, that is the error you get if the receiver is not attached to the queue. The reset would dipose first and then try to re-create the rule. Re-creation will probably fail with the same error but we already re-try initialization for every request so once the receiver comes back, requests will start being delegated again.
