### ISSUE TITLE
Cross target .NET 5.0 and 3.1

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#159]
Multiple partners have said that they will be able to adopt YARP sooner if we provide a netcoreapp3.1 target. We can cross target the package and light up new functionality. We'll want to have a doc tracking things that won't work on 3.1.

**Comment by kasini3000** [comment]
mypoint:
Q: Will YARP provide compatibility with .net core 3.1?
A:
will not. You can use the .net core3.1 client to access YARP through the command line, after ssh, there is a powershell command line interface. This command line interface is compatible with any external calls such as win, linux, python, etc.

user app want add back end to YARP--->commandline--->ssh client---> ssh server--->
powershell YARP module (powershell 7.1 preview base .net core 5)
--->  the static method of .net core 5 of YARP

**Comment by Tratcher** [comment]
> If there is a lot of work for compatibility with .net core 3.1, I suggest not supporting it first.

So far almost every works, the main 5.0 improvements have been in performance. We'll see if we run into any roadblocks later on.

**Comment by kasini3000** [comment]
ok,3q
