### ISSUE TITLE
Match by Remote Ip range

### ISSUE THREAD

**Issue by lvitti** [microsoft/reverse-proxy#1607]
I wanted to know if there is some configuration to use a cluster that depends on the remote IP range?
To split the traffic that comes from the VPN, internet, or local network

Thanks

**Comment by Tratcher** [comment]
Nothing built in, but you can use the new 1.1 API `ReassignProxyRequest` for this. See https://github.com/microsoft/reverse-proxy/pull/1538

You could also use the Direct Forwarder approach:
https://microsoft.github.io/reverse-proxy/articles/direct-forwarding.html

**Comment by lvitti** [comment]
Awesome, that's was exactly what I need it!

Thanks

**Comment by karelz** [comment]
Triage: Answered, closing.
