### ISSUE TITLE
TlsHandshakeType value 24 should be labeled KeyUpdate

### ISSUE THREAD

**Issue by ritchiecarroll** [microsoft/reverse-proxy#1613]
https://github.com/microsoft/reverse-proxy/blob/8970c8ded8b47089ef37aab780b0e35648c99adf/src/ReverseProxy/Utilities/TlsFrameHelper.cs#L39

See similar issue and PR in dotnet/runtime:
https://github.com/dotnet/runtime/issues/66781
https://github.com/dotnet/runtime/pull/66786

**Comment by karelz** [comment]
Triage: Technically it is a breaking change, so we should fix it in 2.0.
