### ISSUE TITLE
[Question/feature request] How to know if programmatically loaded configuration has been applied or not?

### ISSUE THREAD

**Issue by nulltoken** [microsoft/reverse-proxy#1619]
### What should we add or change to make your life better?

When dynamically applying loaded configuration (cf. https://microsoft.github.io/reverse-proxy/articles/config-providers.html) after the initial startup, any validation failure will be logged, then silenced.

We would need a way to get notified of both successful configuration changes and invalid configuration rejection.

### Why is this important to you?

- We'd need to be able to reliably expose, through an endpoint, the version of the configuration. Currently when `InMemoryConfigProvider.Update()` is invoked, there is no way to tell if the configuration has been properly updated or ignored. As such, we don't know how to bump the currently deployed version to the latest valid one. (or keep it as is because nothing changed)
- When an invalid configuration is rejected, an exception is logged. We'd like to able to extend this and be able to trigger additional measures.

Disclaimer: This capability may already exist in YARP. I might just haven't found it.

**Comment by karelz** [comment]
Triage: Looks like reasonable request.
We should add event / callback telling the result, likely identifying the original configuration via the `IProxyConfig` object that has been passed to us (it is read only).
