### ISSUE TITLE
Add Maestro subscription from dotnet/aspnetcore to YARP

### ISSUE THREAD

**Issue by anurse** [microsoft/reverse-proxy#162]
YARP needs a Maestro subscription from dotnet/aspnetcore so we collect updated bits from that repo. We don't *need* it until we have a dependency on new APIs though so this doesn't have to block preview 1. It should probably be done before preview 2 though.

Some docs are here: https://github.com/dotnet/arcade/blob/master/Documentation/DependencyFlowOnboarding.md#consuming . @wtgodbe has some experience here and can probably help us out.

One potential complication: We currently take dotnet/runtime builds, and dotnet/aspnetcore depends on dotnet/runtime. I believe there's a way to express this properly (CoherentParentDependency I think?) but we may need to figure that out.

**Comment by anurse** [comment]
ping @Tratcher

**Comment by wtgodbe** [comment]
Yep, I can help out here, and `CoherentParentDependency` is the right way to express a runtime -> aspnetcore -> yarp dependency chain. Loop me in whenever we need to start this work

**Comment by Tratcher** [comment]
@wtgodbe thanks Will.

Does adding a [3.1 cross target](https://github.com/microsoft/reverse-proxy/issues/159) complicate this?

**Comment by anurse** [comment]
I don't think so. We cross targeting like this in dotnet/extensions and other places.

**Comment by Tratcher** [comment]
Closing this. We didn't end up needing this in the .NET 5 development cycle, and now we're sticking to released builds of .NET 5.
