### ISSUE TITLE
Multi-instance Azure app service proxying issue?

### ISSUE THREAD

**Issue by satyakadiyam** [microsoft/reverse-proxy#1620]
### My app configuration
1. .Net 6 ASP.Net Core + Yarp 1.0
2. Hosted in Azure app service (plan - S1:2)
3. I've custom IProxyConfigProvider to update proxy config at runtime (using distributed Redis cache as store config)

### Problem: 
When I update the proxy config, only one instance of my app is updated and other still has old config

### Scenario
**Step 1**: deploy the app with proxy config like "route1" goto "destination1"
**Step 2**: goto app.com/route1 --> routed to "destination1" (keep refresh and always goto "destination1" as expected)
--- all good till here--
**Step 3**: update config using a API (IProxyConfigProvider) with a new config like "route1" goto destination2"
**Step 4**: goto app.com/route1 --> routed to "destination1" and some times taking to "destination2" (keep refreshing, this behavior is consistent)

This app has 2 instances (app service plan S1:2), when I try to update config at runtime, only one instance is getting updated and the other is still holding old config

Any thoughts how to resolve this?

**Comment by satyakadiyam** [comment]
this should be implementation in application to propagate to all the instances . like a pub/sub to update config in each instance.

**Comment by Tratcher** [comment]
This could have worked, the issue was likely in how change notifications were being signaled from redis.
