### ISSUE TITLE
Remove the restriction that every route specify a Host

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#163]
https://github.com/microsoft/reverse-proxy/blob/20d50978e3aea16b0e5e56f9fd1bdb4f57a28c03/src/ReverseProxy/Service/Config/RuleParsing/RouteValidator.cs#L67-L72

The host is not needed when you want to proxy all requests, all remaining requests, or all requests based on path.

**Comment by samsp-msft** [comment]
I am assuming null = any host?

**Comment by Tratcher** [comment]
Right. At that point you'd be routing based on path.
