### ISSUE TITLE
How to identify subdomains?

### ISSUE THREAD

**Issue by leandrofagundes** [microsoft/reverse-proxy#1632]
Hi, I have a domain that is already address.example.com.
I need something like api1.address.example.com and api2.address.example.com on the same configuration file.

There is a way to achieve my needs with reverse-proxy?
Here is my config file.

```
{
  "Urls": "http://example.com/",
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "AllowedHosts": "*",
  "ReverseProxy": {
    "Routes": {
      "admin-webapp-route": {
        "ClusterId": "admin-webapp-cluster",
        "Match": {
          "Path": "{**catch-all}",
          "Hosts": [ "api1.address.example.com" ]
        }
      }
    },
    "Clusters": {
      "admin-webapp-cluster": {
        "Destinations": {
          "endpoint": {
            "Address": "http://admin-webblazor/"
          }
        }
      }
    }
  }
}
```

**Comment by Tratcher** [comment]
Do you want to forward all three domains to the same destination or separate ones? If you want to forward them to the same destination then list them all on the same route (wildcards can help with that). If you want to forward them to different destinations/clusters, then add separate routes and clusters for each.
