### ISSUE TITLE
[Question] Use YARP in kubernetes as a service plus ingress

### ISSUE THREAD

**Issue by pilouk** [microsoft/reverse-proxy#1636]
Following this [article](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/implement-api-gateways-with-ocelot).

I'm wondering if it's okay or makes sense to add a BFF/gateway(YARP) as a service in K8S with an Ingress in front? I have some custom code in my YARP such as JWT validation and REDIS token invalidation services which seem difficult to achieve with APIM or APIGateway from Azure.

Will, this setup works, and does anyone tried it?
Thanks!

**Comment by pilouk** [comment]
> Triage:
> 
> * @pilouk are you trying to add YARP as a regular service into your existing k8s config? ... This one should just work like any other service, right?
> * Or are you trying to use YARP as k8s Ingress -- i.e. part of k8s infrastructure? ... This one is in progress - see [Kubernetes Ingress Controller](https://github.com/microsoft/reverse-proxy/issues?q=is%3Aopen+is%3Aissue+label%3A%22Kubernetes+Ingress+Controller%22) issues

Thanks for your time @karelz!
I will add it as a regular service which will be the only one accessible externally.
I will test it with "azure container apps" tomorrow and come back or close this issue if everything is fine!

**Comment by pilouk** [comment]
works like a charm!

**Comment by NitinM3** [comment]
> works like a charm!
@pilouk 
Even I have to do similar stuff where reverse proxy will run like service hosted before traefik. It would be great if you provide some inputs on how you have achieved.

**Comment by pilouk** [comment]
> > works like a charm!
> > @pilouk
> > Even I have to do similar stuff where reverse proxy will run like service hosted before traefik. It would be great if you provide some inputs on how you have achieved.

Nothing really complicated if you have some knowledge of .NET and cloud platforms. You can use any hosted platform however, be sure your YARP service is exposed to the internet "public" if you want it to act as a gateway. Follow this [tutorial ](https://microsoft.github.io/reverse-proxy/articles/getting-started.html) I use .NET 6 C# project. Most of the important things will come down to the configuration file in your YARP project where you will add your downstream service URL which may be "private" if you don't want those expose.
