### ISSUE TITLE
How to support multiple protocols

### ISSUE THREAD

**Issue by Danieladu** [microsoft/reverse-proxy#1641]
### Some details

**How many backends are in your application?**

- [ ] 1-2
- [ ] 3-5
- [x] 6-10
- [ ] 10+

**How do you host your application?**

- [ ] Kubernetes
- [x] Azure App Service
- [ ] Azure VMs
- [ ] Other Cloud Provider (please include details below)
- [ ] Other Hosting model (please include details below)

### Question
Here is the scenario:
Route certain hosts into certain targets, which should support websockets and https both.

For example:
Route  "https://hostA"  => "https://targetA",
and route "wss://hostA" =>"wss://targetA",

At the same time, there are several such services,
Route  "https://hostB"  => "https://targetB",
and route "wss://hostB" =>"wss://targetB"

And several others...

Here are my try experiences:
1. Use the normal case sample (Config file and code config)
  It seems that the Address of the destination should be hard code, and there is no "Protocol" match property of class "RouteMatch",
  So there is no way to distinguish the protocol
```
        public IReadOnlyList<string>? Methods
        public IReadOnlyList<string>? Hosts
        public string? Path
        public IReadOnlyList<RouteQueryParameter>? QueryParameters
        public IReadOnlyList<RouteHeader>? Headers
```

2. Use direct forwarding
```
        endpoints.Map("/{**catch-all}", async httpContext =>
        {
            var error = await forwarder.SendAsync(httpContext, "https://localhost:10000/",
                httpClient, requestConfig, transformer);
            // Check if the operation was successful
            if (error != ForwarderError.None)
            {
                var errorFeature = httpContext.GetForwarderErrorFeature();
                var exception = errorFeature.Exception;
            }
        });
```
  But it seem that we can not filter different host into different targets?

3. Use HttpTransformer
I use below code try to enable the url redirect, 
```
                .AddTransforms(builderContext =>
                {
                    builderContext.AddRequestTransform(transformContext =>
                    {
                        if (transformContext.HttpContext.WebSockets.IsWebSocketRequest)
                        {
                            var destinationPrefix = transformContext.DestinationPrefix.Replace("https://", "wss://").Replace("http://", "ws://");
                            transformContext.ProxyRequest.RequestUri = RequestUtilities.MakeDestinationAddress(
                destinationPrefix, transformContext.Path, transformContext.Query.QueryString);
                        }

                        return default;
                    });
                });
```
But it does not work, and the connection could not be established

4. Use middleware to modify the destination url
```
                endpoints.MapReverseProxy(proxyPipeline => {
                    proxyPipeline.Use((request, next) => {
                        if(request.WebSockets.IsWebSocketRequest)
                        {
                            var feature = request.GetReverseProxyFeature();
                            feature.ProxiedDestination.Model.Config.Address = "xxx";
                        }
                        return next();
                    });
                });
```
But the compiler show that Init-only property or indexer 'DestinationConfig.Address' can only be assigned in an object initializer.

So is there a solution that could meet my requirements? Thanks!

**Comment by Tratcher** [comment]
https://github.com/microsoft/reverse-proxy/blob/main/docs/docfx/articles/websockets.md

Since WebSockets is based on HTTP/S You don't need to do anything special to enable WebSocket support in YARP. Proxy everything as HTTP/S and it should just work. The ws and wss url schemes are only used on clients, not on proxies or servers.

**Comment by Danieladu** [comment]
> https://github.com/microsoft/reverse-proxy/blob/main/docs/docfx/articles/websockets.md
> 
> Since WebSockets is based on HTTP/S You don't need to do anything special to enable WebSocket support in YARP. Proxy everything as HTTP/S and it should just work. The ws and wss url schemes are only used on clients, not on proxies or servers.

thanks for the quick reply..maybe there is somerhing wrong with my own service

**Comment by samsp-msft** [comment]
Did you get this working - you should only need routes for `http://` and `https://` within the proxy. The `ws://` urls will be mapped to http requests on the wire, which is what is seen by the proxy.

**Comment by Danieladu** [comment]
> Did you get this working - you should only need routes for `http://` and `https://` within the proxy. The `ws://` urls will be mapped to http requests on the wire, which is what is seen by the proxy.

Yes. It works. Thanks.
