### ISSUE TITLE
False positive with load  balancing configuration message

### ISSUE THREAD

**Issue by steveoh** [microsoft/reverse-proxy#1649]
### Describe the bug

I have a cluster defined with two destinations. When a request times out to a route, I get a warning that the load balancing might be configured incorrectly. 

### To Reproduce

```json
"Clusters": {
  "mapping": {
    "LoadBalancingPolicy": "PowerOfTwoChoices",
    "Destinations": {
      "mapping/destination1": {
        "Address": "https://something"
      },
      "mapping/destination2": {
        "Address": "https://somethingelse"
      }
    }
  }
}
```

```
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 15 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
[12:05:34 WRN] More than one destination available for cluster 'mapping', load balancing may not be configured correctly. Choosing randomly.
```

Isn't the whole point of load balancing to have more than one destination?

### Further technical details

- Include the version of the packages you are using
  - 1.1.0-rc.1.22152.1
- The platform (Linux/macOS/Windows)
  - mac os

**Comment by MihaZupan** [comment]
> Isn't the whole point of load balancing to have more than one destination?

The job of load balancing is to reduce the list of available destinations to 1.
The warning is saying that there were multiple destinations listed even after load balancing.

> System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 15 seconds elapsing.
[12:05:34 WRN] More than one destination available for cluster 'mapping'

You should see this warning *before* forwarding happens, not after.

Are you making any modifications to the request pipeline (e.g. custom middlewares, retry logic)?

**Comment by steveoh** [comment]
The config seems to add successfully on load

```
[12:03:20 INF] Starting web host...
[12:03:20 INF] Loading proxy data from config.
[12:03:21 DBG] Destination 'mapping/destination1' has been added.
[12:03:21 DBG] Destination 'mapping/destination2' has been added.
[12:03:21 DBG] New client created for cluster 'mapping'.
[12:03:21 DBG] Cluster 'mapping' has been added.
[12:03:21 INF] Now listening on: http://localhost:3000
```

I have this polly logic

```cs
var retryPolicy = HttpPolicyExtensions
              .HandleTransientHttpError()
              .Or<TimeoutRejectedException>() // thrown by Polly's TimeoutPolicy if the inner call times out
              .WaitAndRetryAsync(3, retryAttempt =>
                      TimeSpan.FromSeconds(Math.Pow(2, retryAttempt)));

            var timeoutPolicy = Policy.TimeoutAsync<HttpResponseMessage>(8); // Timeout for an individual try

            services.AddHttpClient("default", client => client.Timeout = new TimeSpan(0, 0, 15))
              .ConfigurePrimaryHttpMessageHandler(() => {
                  var handler = new HttpClientHandler();
                  if (handler.SupportsAutomaticDecompression) {
                      handler.AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate;
                  }

                  return handler;
              })
              .AddPolicyHandler(retryPolicy)
              .AddPolicyHandler(timeoutPolicy);
```

**Comment by MihaZupan** [comment]
But are you using the client created by Polly to proxy requests?

Can you show how you configure the proxy in the pipeline?

**Comment by steveoh** [comment]
I think this is pretty normal

```cs
                endpoints.MapReverseProxy(proxyPipeline => {
                    proxyPipeline.Use(async (context, next) => {
                        var request = context.Request;
                        if (request.Path.StartsWithSegments(new PathString("/map")) && tokenService is not null) {
                            request.QueryString = request.QueryString.Add("token", await tokenService.GetTokenAsync());
                        }

                        await next();
                    });
                })
```

**Comment by samsp-msft** [comment]
Do you just add your own middleware and not call the existing middleware, such as the example at  https://microsoft.github.io/reverse-proxy/articles/middleware.html#adding-middleware?

>  Middleware for session affinity, load balancing, and passive health checks are not included by default so that you can exclude, replace, or control their ordering with any additional middleware.

If you don't include them, then that explains the problem - no load balancing is being used, so all the destinations are being passed on.

**Comment by steveoh** [comment]
I updated my code snippet above. I use the add reverse proxy and load from config the config I pasted in the original message.

**Comment by MihaZupan** [comment]
What Sam is saying is that calling 
```c#
endpoints.MapReverseProxy();
```
has different behavior than
```c#
endpoints.MapReverseProxy(proxyPipeline =>
{
    // ...
});
```

In the second case, the extra middleware (session affinity, load balancing, and passive health) aren't included automatically. You have to include them manually.

```diff
endpoints.MapReverseProxy(proxyPipeline => {
    proxyPipeline.Use(async (context, next) => {
        // Your logic
        await next();
    });

+   proxyPipeline.UseSessionAffinity();
+   proxyPipeline.UseLoadBalancing();
+   proxyPipeline.UsePassiveHealthChecks();
})
```

**Comment by steveoh** [comment]
Thanks for explaining this to me. It didn't jump and and kick me in the face when I was scanning the docs.
