### ISSUE TITLE
 support other framework integration？

### ISSUE THREAD

**Issue by fanliang11** [microsoft/reverse-proxy#165]
Hello,reverse-proxy team member.
I am very happy that Microsoft has open sourced this project for the community, and I envy that Microsoft has started. It has a higher starting point than other individuals and communities. No matter whether it is mediocre or not, there are fans who support it.
### What should we add or change to make your life better?
is this project is a high-performance HTTP and reverse proxy, or a high degree of integration with Kubernetes, it would be very good if this is the case, but I would like to make a comment, not only highly integrated with asp.net core, only extended based on asp.net Core ProxyInvokerMiddleware also needs to consider the high integration of other frameworks or engines. I hope you can open the interface of the HttpMessageListener and HttpServerMessageSender function types, so as to extend the integrated encapsulated RPC call, and then write through Response in HttpServerMessageSender Required features
### Why is this important to you?
For Microsoft's open source products, I hope not only to consider the integration of Microsoft's product framework, but also to consider the community, so that the community ecology will be perfect. I am the original author of  [surging](https://github.com/fanliang11/surging), and I hope you can achieve flexible configuration integration, if possible, follow-up I will integrate

**Comment by Tratcher** [comment]
> is this project is a high-performance HTTP and reverse proxy,

Yes, that's one of our primary goals.

> or a high degree of integration with Kubernetes,

Integrating directly with Kubernetes is not currently a goal for us, but we hope the framework we provide is flexible enough to make it possible.

> I hope you can open the interface of the HttpMessageListener and HttpServerMessageSender function types,

I don't quite understand. You want us to provide implementations for those abstractions? I'm not sure how that's related to the reverse proxy scenario. If we were proxying HTTP based RPC calls it would be transparent to the proxy. That's how we support gRPC today.

**Comment by samsp-msft** [comment]
Triage: Could you describe what you think this integration would look like - maybe include a whiteboard diagram of how the proxy fits into the bigger picture.

**Comment by samsp-msft** [comment]
@fanliang11 - any update?

**Comment by fanliang11** [comment]
Sorry, busy work, no reply, I have a lot of dissatisfaction with the Microsoft framework, I need more flexibility, need to provide internal processing interface, to meet more scalability, such as rest Request message Whether the processing between the response message and the response message can be more an interface extension method public, so that I can make remote calls based on the internal RPC service, maybe my understanding is wrong, you can also point out my problem

**Comment by samsp-msft** [comment]
Triage: This is out of scope for the current plans for our team. Extensibility is a goal for YARP so if you run into places where you can't do this due to a limitation in the APIs please file further issues for those APIs.
