### ISSUE TITLE
Problem with proxy from http server to server with force https 

### ISSUE THREAD

**Issue by vaital3000** [microsoft/reverse-proxy#1651]
### Describe the bug
My server app was running without https. I need to proxy requests to an https server where there is redirect to https, but I get 301 response, because request has value "http" in scheme property.

I created RequestTransfortm and force set `context.HttpContext.Request.Scheme = "https";` after that proxy works fine.

I'm not sure if this is a bug, but I spent a lot of time solving this.

### To Reproduce
Example test to HttpForwarderTests

```c#
[Fact]
    public async Task ProxyToHttpsFromHttpRequest_WorksFine()
    {
        var events = TestEventListener.Collect();
        var httpContext = new DefaultHttpContext();
        httpContext.Request.Method = "POST";
        httpContext.Request.Scheme = "http";
        httpContext.Request.Host = new HostString("example.com:3456");
        httpContext.Request.Path = "/path/base/dropped";
        httpContext.Request.Path = "/api/test";
        httpContext.Request.QueryString = new QueryString("?a=b&c=d");
        httpContext.Request.Headers.Add(":authority", "example.com:3456");
        httpContext.Request.Headers.Add("x-ms-request-test", "request");
        httpContext.Request.Headers.Add("Content-Language", "requestLanguage");

        var requestBody = "request content";
        httpContext.Request.Headers.Add("Content-Length", requestBody.Length.ToString());
        httpContext.Request.Body = StringToStream(requestBody);
        httpContext.Connection.RemoteIpAddress = IPAddress.Loopback;

        var proxyResponseStream = new MemoryStream();
        httpContext.Response.Body = proxyResponseStream;

        var destinationPrefix = "https://localhost:123/a/b/";
        var targetUri = "https://localhost:123/a/b/api/test?a=b&c=d";
        var sut = CreateProxy();
        var client = MockHttpHandler.CreateClient(
            async (HttpRequestMessage request, CancellationToken cancellationToken) =>
            {
                await Task.Yield();
                var capturedRequestContent = new MemoryStream();

                // Use CopyToAsync as this is what HttpClient and friends use internally
                await request.Content.CopyToWithCancellationAsync(capturedRequestContent);
                capturedRequestContent.Position = 0;

                var response = new HttpResponseMessage((HttpStatusCode)234);
                response.ReasonPhrase = "Test Reason Phrase";
                response.Headers.TryAddWithoutValidation("x-ms-response-test", "response");
                response.Content = new StreamContent(StringToStream("response content"));
                response.Content.Headers.TryAddWithoutValidation("Content-Language", "responseLanguage");
                return response;
            });

        await sut.SendAsync(httpContext, destinationPrefix, client);
        Assert.Equal("https", httpContext.Request.Scheme);
    }
```

### Further technical details
- Yarp.ReverseProxy 1.0.0
- Reproduced on all platforms

**Comment by MihaZupan** [comment]
The only time YARP will look at `HttpContext.Request.Scheme` is when adding the `X-Forwarded-Proto` header.
It's possible your destination looks at this header and issues a redirect to attempt to get the client to use `https`.

`X-Forwarded-Proto` is added by default. See the [X-Forwarded- header transform docs](https://microsoft.github.io/reverse-proxy/articles/transforms.html#x-forwarded) for ways to configure this behavior.

**Comment by samsp-msft** [comment]
In the proxy configuration how have you specified the destination server? Have you used `http://something` or `https://something`?

**Comment by vaital3000** [comment]
I use `https://mysite`
I don't use WithTransformXForwarded and I don't see X-Forwarded-* headers on client.

**Comment by MihaZupan** [comment]
These transforms are added by default - even if you don't call `WithTransformXForwarded`. You have to explicitly opt-out if you don't want them.

The headers will be added inside the proxy when making a request to the destination.
They will be seen by the destination server, not by the client.

**Comment by vaital3000** [comment]
I called destination server as Client... sorry. 
But I see X-Forwarded-* headers only when I use WithTransformXForwarded.
I can try to create light sample for reproduce tomorrow.

**Comment by samsp-msft** [comment]
It may be that you have middleware on the destination server that is mapping the x-forward headers into the request context, and that is why it thinks the connection is over http, when in fact the connection from the proxy is via https.

**Comment by karelz** [comment]
Triage: No response, we assume that the last reply was spot on.
If not, please feel free to reopen with additional info. Thanks!
