### ISSUE TITLE
Ways to handle java security 

### ISSUE THREAD

**Issue by steveoh** [microsoft/reverse-proxy#1655]
I am looking for a little help proxying to a java application that I believe is using some sort of standard java authentication scheme (JAAS).

Currently, I proxy a request and add an `Apikey yada yada` Authorization header. It then does what seems to be a bit of an OAuth flow where it returns a 302 response setting a cookie and providing a url location to make another get request to. With my naive understanding of yarp and JAAS I created another match route that matches the 302 locations url and set the `Authorization` header again to get a successful response.

This leaks information into the browser which i think is bad. I am assuming it would be best if this entire transaction was handled within the yarp middleware. 

Is this something YARP can do? Are there any examples of this or do you have any suggestions on how to improve this scenario?

**Comment by samsp-msft** [comment]
Are you expecting the proxy to do the authorization with the java service, or do you want it passed back to the client browser?
If the goal is that the proxy does the authentication, is it going to be translating the authorization from a principle at the proxy and mapping that to something in the java world, or is it going to authenticate once, and then use that for every request that comes in to the proxy?
If you can take a screenshot/photo of a diagram of some form showing the desired flow, we can ensure that we are all on the same page with respect to the desired flow.

**Comment by steveoh** [comment]
> Are you expecting the proxy to do the authorization with the java service, or do you want it passed back to the client browser?

I would like the authorization with the java service to all happen within the proxy. I do not want the client to know it happened. They have already authenticated with the dotnet app that is proxying to the java service.

> If the goal is that the proxy does the authentication, is it going to be translating the authorization from a principle at the proxy and mapping that to something in the java world, or is it going to authenticate once, and then use that for every request that comes in to the proxy?

The owner of the service gave me an api key to use to authenticate but the service still wants to redirect with a cookie that is then required to complete the request. I would think that it could authenticate once and then use that for all subsequent requests until the cookie is no longer valid.

When I put this request into something like insomnia or postman that entire transaction happens "behind the scenes". Are these diagrams helpful?

### currently (naive implementation)

```mermaid
sequenceDiagram
	participant front as react app
    participant back as dotnet api
    participant service as java service

    front->>back: client makes request for image on a yarp match path
    back->>service: yarp sets a request header with the api key
    service->>front: service responds with a 302 redirect with a cookie and location
    front->>back: browser follows the 302 and a request comes back in on the location url
    back->>service: yarp matches this path and sets the request header again
    service->>front: returns the image
```

### desired implementation

```mermaid
sequenceDiagram
	participant front as react app
    participant back as dotnet api
    participant service as java service

    front->>back: client makes request for image on a yarp match path
    back->>service: yarp sets a request header with the api key and uses cookies if available
    service->>back: service responds with a 302 redirect with a cookie and location
    back->>back: store cookie
    back->>service: follow the url with the new cookies and set the request header again
    service->>front: returns the image
```

If on the first request the cookies could be stored and reused to remove the authorization flow on subsequent requests until the cookie expires and the auth flow is required again would be ideal.

**Comment by Tratcher** [comment]
Do you have examples of the urls for these requests? Where does the 302 send you from and to? Is that unique per resource?

If the issue is just that the app requires you to exchange the API key for a cookie, you can do that on an independent request rather than on one of the proxy requests. Then you add the necessary headers to all proxy requests and they don't have to do this dance.

**Comment by samsp-msft** [comment]
+1 to @Tratcher's suggestion. 

Make an independent call to the service to get a token at proxy startup, and retrieve the cookie and then add that to user requests to that destination. You can use https://docs.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler.allowautoredirect?view=net-6.0 to enable the 302 redirect to be handled as part of that request. You'll probably need to figure out what the timeout is on the auth token and have a timer to refresh it if its out of date.

You could possibly make this call on demand if you don't have a valid cookie, but you'll want to make sure that you don't make multiple token requests at once, and refresh if the cookie has expired.

**Comment by karelz** [comment]
Triage: Recommendations above should be sufficient. Not actionable for YARP. Closing.
Feel free to reopen if there is more info available or we missed something.

**Comment by steveoh** [comment]
@Tratcher how would I hook into the proxy startup event? I assume that isn't a middleware on the pipeline. I'm struggling to figure out the startup hook that will allow me to get the http client that yarp will use to hydrate the cookie container.

**Comment by steveoh** [comment]
So be cautious then? 

> Middleware should be cautious about modifying request fields such as headers in order to affect the outgoing proxied request. Such modifications may interfere with features like retries and may be better handled by [transforms](https://microsoft.github.io/reverse-proxy/articles/transforms.html).

**Comment by Tratcher** [comment]
I'd recommend setting it up as a transform on the outgoing request as mentioned in that quote. That avoid modifying the original incoming request.
https://microsoft.github.io/reverse-proxy/articles/transforms.html#addrequesttransform

Something like:
```
var authCookie = GetAuthCookie();
...
.AddTransforms(context =>
{
    context.AddRequestTransform(async requestContext =>
    {
        requestContext.ProxyRequest.Content.Headers.TryAddWithoutValidation(HeaderNames.Cookie, authCookie);
    });
});
```

**Comment by sibijohn72** [comment]
@Tratcher I have a similar problem but additionally my cookie expires. so it needs a different value every 6 hours. How do i handle this? AFAIK the transform is evaluated once on startup so the cookie value is fixed to whatever it was then.
