### ISSUE TITLE
Rules conflict resolution policy.

### ISSUE THREAD

**Issue by mahpate** [microsoft/reverse-proxy#1658]
If we have multiple rules which causes conflict in routes resolution in "DefaultEndpointSelector" and requests are failing. We should create policy based on MatcherPolicy, to resolve the route. One approach is to have based on EndPoint DisplayName compare based resolution, so it's deterministically resolved the conflict. Another Approach is to have resolve first endpoint in case conflict, this will be undeterministic, or come up with conflict resolution endpoint as a separate configuration in YARP policy (create new policy and set the conflict resolution endpoint)

**Comment by karelz** [comment]
Triage: @javiercn this looks deep in ASP.NET routing. What is the recommended way to tie break conflicts?

**Comment by javiercn** [comment]
> If we have multiple rules which causes conflict in routes resolution in "DefaultEndpointSelector" and requests are failing.

Are these YARP rules that the developer configures? I would first try to change the rules to avoid the ambiguity. If that's not possible, I would give each route an explicit order value and flow that to the resolved endpoint(s) for that rule.

If you are trying to come up with an additional criteria to disambiguate, I would not use the display name. Maybe you could use something like the order in which the route was defined in the file to disambiguate, which would feel more natural to existing ASP.NET Core users and would be easier to explain (put your most specific routes first on the file).

@karelz the scenario is a bit unclear for me, so take my advice with a grain of salt. If you provide more context I'm happy to give more detailed guidance.

**Comment by Tratcher** [comment]
The routes are dynamically loaded from one or more external sources, the proxy operator doesn't define/control them. At best the operator could set some policy of how to resolve potential conflicts.

**Comment by javiercn** [comment]
> The routes are dynamically loaded from one or more external sources

Could that information contain a number indicating the relative order of that route with respect to other routes (with default 0)? Or maybe use a precedence based on the order in which the different sources are imported? 

In all those cases you can leverage the built in Order criteria and it is easy to explain.

Using other criteria would require you implementing a MatcherPolicy that also implements IEndpointOrderer (I think that's how it's called) and the criteria would be hard to explain (for example if you were to use something like the displayname, which I would super strongly discourage against doing, as it is only for debug purposes).

**Comment by Tratcher** [comment]
Thanks @javiercn. Yes, Order is something that can be set as part of the route definition. It's also something the proxy operator could augment using a config-filter. @mahpate, can you give that a try?
https://microsoft.github.io/reverse-proxy/articles/config-files.html#routes
https://github.com/microsoft/reverse-proxy/blob/main/docs/docfx/articles/config-filters.md

**Comment by mahpate** [comment]
Thanks guys for the workaround. We have written MatcherPolicy with business logic of conflict detection and resolving it to the ordinal based on DisplayName.
