### ISSUE TITLE
HttpForwarder throw exception when trying to forward a POST request.

### ISSUE THREAD

**Issue by DeepWaterWhale** [microsoft/reverse-proxy#1665]
### Describe the bug
HttpForwarder throw exception when trying to forward a POST request.

### To Reproduce
Forward any POST request with body can repro.

Got Exceptions? Include both the message and the stack trace
Error Message: (Parameter 'size') Actual value was 0.

CallStack:
   at Microsoft.AspNetCore.Server.HttpSys.RequestStream.ValidateReadBuffer(Byte[] buffer, Int32 offset, Int32 size)
   at Microsoft.AspNetCore.Server.HttpSys.RequestStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 size, CancellationToken cancellationToken)
   at System.IO.Stream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at Yarp.ReverseProxy.Forwarder.StreamCopier.<CopyAsync>d__3.MoveNext() in D:\__GItRepo__\reverse-proxy\src\ReverseProxy\Forwarder\StreamCopier.cs:line 53

-->

### Further technical details

- Include the version of the packages you are using
Use the latest source code to build the package and testing.
commit id is: b8a58a6a7aec30d7d1bdda8e41f02bd1034d20ea

- The platform (Linux/macOS/Windows): Windows

I took a look at the code, in my understanding, yarp create a StreamCopyHttpContent in the proxy request to copy the original request's body.

And in StreamCopyHttpContent, it uses StreamCopier to do the real copy work, code is like below. But it throws exception when use an empty buffer directly, then return RequestBodyClient error back.

```C#
                // Issue a zero-byte read to the input stream to defer buffer allocation until data is available.
                // Note that if the underlying stream does not supporting blocking on zero byte reads, then this will
                // complete immediately and won't save any memory, but will still function correctly.
                var zeroByteReadTask = input.ReadAsync(Memory<byte>.Empty, cancellation);
                if (zeroByteReadTask.IsCompletedSuccessfully)
                {
                    // Consume the ValueTask's result in case it is backed by an IValueTaskSource
                    _ = zeroByteReadTask.Result;
                }
                else
                {
                    // Take care not to return the same buffer to the pool twice in case zeroByteReadTask throws
                    var bufferToReturn = buffer;
                    buffer = null;
                    ArrayPool<byte>.Shared.Return(bufferToReturn);

                    await zeroByteReadTask;

                    buffer = ArrayPool<byte>.Shared.Rent(DefaultBufferSize);
                }
```

**Comment by karelz** [comment]
Triage:
- We need ASP.NET issue
- Proposal for YARP - disable 0-byte reads on .NET 3.1 and 5.0

**Comment by Tratcher** [comment]
Thanks @DeepWaterWhale. I've filed https://github.com/dotnet/aspnetcore/issues/41305 to fix this in asp.net 6 and 7. We'll disable zero-byte reads in YARP for earlier runtime versions. Which version of asp.net are you using?

**Comment by Tratcher** [comment]
Related: https://github.com/microsoft/reverse-proxy/issues/1657

**Comment by DeepWaterWhale** [comment]
@Tratcher I am using asp.net 6.0

**Comment by karelz** [comment]
Fixed by https://github.com/microsoft/reverse-proxy/pull/1666

**Comment by ztoliver** [comment]
Is there a work-around for .net 6.0? I'm having this exact issue while attempting basic direct forwarding and it's blocking any POST request I'm trying to forward. Using YARP 1.1.0.

**Comment by samsp-msft** [comment]
Rollback to 1.0 until ASP.NET gets fixed?

**Comment by MihaZupan** [comment]
Or if you are not bound to HttpSys, Kestrel is not affected by this issue.

**Comment by ztoliver** [comment]
Rolling back to 1.0.0 just causes the forwarder to timeout. At least with 1.1.0 it returns an error (ForwarderError.RequestBodyClient) with the following exceptions.

- _Sent 0 request content bytes, but Content-Length promised 1220._
- _Error while copying content to a stream._

**Comment by MihaZupan** [comment]
If you are seeing such problems with YARP 1.0, it's not the same issue.
Please open a new issue and share your config & code. Most likely case is that you are modifying/reading the request body before forwarding.

**Comment by ztoliver** [comment]
Yep we are reading the request which is injected into a controller method and is required by Swagger to recognize the request model. When removing that parameter I can successfully forward the request, but then we lose Swagger support. Thanks for the help.
