### ISSUE TITLE
Immutable Metadata for Routing

### ISSUE THREAD

**Issue by Kahbazi** [microsoft/reverse-proxy#1669]
In https://github.com/microsoft/reverse-proxy/pull/1639 `Matchers` property has been changed from IReadonlyList to Array.
https://github.com/microsoft/reverse-proxy/blob/e684ba52dded6598260fa17cec8c1769088597dd/src/ReverseProxy/Routing/IHeaderMetadata.cs#L16
https://github.com/microsoft/reverse-proxy/blob/e684ba52dded6598260fa17cec8c1769088597dd/src/ReverseProxy/Routing/IQueryParameterMetadata.cs#L16

I'm just curious about the reason of this change. Isn't it better for routing metadata to be immutable?

If it's going to remain array, the read-only part should be removed from these API docs.
https://github.com/microsoft/reverse-proxy/blob/e684ba52dded6598260fa17cec8c1769088597dd/src/ReverseProxy/Routing/HeaderMatcher.cs#L53-L56
https://github.com/microsoft/reverse-proxy/blob/e684ba52dded6598260fa17cec8c1769088597dd/src/ReverseProxy/Routing/QueryParameterMatcher.cs#L51-L54

**Comment by Tratcher** [comment]
All of these types are internal so it would only be modifiable by code within this library. Do we actually modify it anywhere?

I assume we're using an array for efficiency?

**Comment by MihaZupan** [comment]
> I assume we're using an array for efficiency?

Yes. With an array, you avoid bounds checks and virtual calls for every element when enumerating.

And no, we don't modify these anywhere.

**Comment by Kahbazi** [comment]
Oh my bad, I missed the `internal` part! I was thinking about eventually these might move to ASP.NET Core repo, and there all the new metadata is immutable as far as I see. The issue could be closed.
