### ISSUE TITLE
Mandatory Request header validation

### ISSUE THREAD

**Issue by askids** [microsoft/reverse-proxy#1670]
hi,

Is there any existing feature available within YARP that allows me to enforce checking for presence of mandatory request headers on incoming requests?

Thanks!

**Comment by Tratcher** [comment]
Not directly. You can do this with middleware: https://microsoft.github.io/reverse-proxy/articles/middleware.html

**Comment by MihaZupan** [comment]
For simple validation on a per-route basis, you can use [header routing](https://microsoft.github.io/reverse-proxy/articles/header-routing.html).
The conditions are limited to basic operations such as "header foo exists", "header bar contains myValue".
If you must do more validation on the value, a custom middleware is the way to go as Chris suggested.

**Comment by askids** [comment]
I dont need to do header based routing. I just need to check if the header exists or not., when I receive a call for a route. if the header is not present, I want to throw a 400 bad request error. Looks like I will need to use custom middleware then.
