### ISSUE TITLE
Add NotExists to HeaderMatchMode enum

### ISSUE THREAD

**Issue by mak0t0san** [microsoft/reverse-proxy#1697]
### What should we add or change to make your life better?
Would like the ability to match only when a particular header is not present. This could be done by adding a `NotExists` value to `HeaderMatchMode` and implement code to handle it.

### Why is this important to you?
In my particular scenario we have an API application that runs in multiple types of environments, such as containerized environments as well as a dedicate virtual machine.  There are a couple of endpoints that don't work in the containerized environment so we use YARP to reverse-proxy those requests to the VM environment.  We've also had to add some extra deployment steps so that we can set different configuration values for the containerized version and the VM version. I would like to avoid having to setup extra deployment steps by having YARP add a header so that servers downstream can know that it's being forwarded the request.  Simply checking for the presence of a `X-Forwarded*` header is not sufficient as the servers upstream are behind load balancers that already get this header.

Here's what I want to do:

- Load-Balancer gets request, forwards to containerized environment
- Containerized environment receives request.  YARP configuration will reverse proxy some endpoints if a custom header does NOT exist and will transform and add a custom header
- VM environment receives request from YARP with new custom header added. This has the same exact files, including YARP configuration as the upstream servers.  However, the YARP rule will only match if the new header does NOT exist but the upstream server added the header so the YARP rule won't match and the code in the app will handle the request.

**Comment by karelz** [comment]
Triage: Not high demand so far (please upvote top post if you want it) - moving to Backlog for now.
It should be fairly straightforward and we would take a contribution.

**Comment by kevbry** [comment]
@karelz I needed this as well - PR submitted.

**Comment by MihaZupan** [comment]
Added in #1806

**Comment by MihaZupan** [comment]
Reopening to track adding docs
