### ISSUE TITLE
[New Feature]:  support grpc transcoding

### ISSUE THREAD

**Issue by pengweiqhca** [microsoft/reverse-proxy#1700]
https://cloud.google.com/endpoints/docs/grpc/transcoding

.proto files can be obtained through grpc reflection service.

**Comment by davidfowl** [comment]
This doesn't need to be built into YARP, it's shipping as part of ASP.NET Core's grpc implementation in .NET 7 cc @JamesNK

**Comment by JamesNK** [comment]
Yes. See https://docs.microsoft.com/en-us/aspnet/core/grpc/httpapi?view=aspnetcore-6.0

Note that the way it's implemented means it needs to run in the same app as the gRPC service. Some code could be reused to replicate the reverse proxy approach used by Envoy and grpc-gateway, but it would be more work and we'd need customer demand and compelling reason to consider it.

**Comment by pengweiqhca** [comment]
> > This doesn't need to be built into YARP,
> 
> Yes. See https://docs.microsoft.com/en-us/aspnet/core/grpc/httpapi?view=aspnetcore-6.0
> 
> Note that the way this feature is implemented for ASP.NET Core means it needs to run in the same app as the gRPC service. Some code could be reused to replicate the reverse proxy approach used by Envoy and grpc-gateway, but it would be more work and we'd need customer demand and compelling reason to consider it.

The backend is not only asp.net core, but also other grpc servers such as grpc.core (can't migrate to asp.net core for some reason).

**Comment by davidfowl** [comment]
@pengweiqhca What's your scenario? You have a .NET Framework application that you can't upgrade to .NET Core and you are routing to it using YARP?

**Comment by pengweiqhca** [comment]
> @pengweiqhca What's your scenario? You have a .NET Framework application that you can't upgrade to .NET Core and you are routing to it using YARP?

Yes

**Comment by JamesNK** [comment]
Grpc.Core is being deprecated. I think the end-of-life date has been moved back by a year, but you should make plans to stop using it.

**Comment by pengweiqhca** [comment]
> Grpc.Core is being deprecated. I think the end-of-life date has been moved back by a year, but you should make plans to stop using it.

If the ideas is easy to implement, there will be less troubles. 😒😒😒

> Some code could be reused to replicate the reverse proxy approach used by Envoy and grpc-gateway, but it would be more work.
This feature asp.net core may be not implemented, but as a reverse proxy, YARP need to consider whether to implement similar feature to Envoy and grpc-gateway.

**Comment by pengweiqhca** [comment]
@davidfowl Are there any plans to support `grpc-gateway` on YARP?

**Comment by davidfowl** [comment]
Not currently, no.

**Comment by samsp-msft** [comment]
There seem to be two approaches to this problem:
a) On-the-fly transcoding which is what https://cloud.google.com/endpoints/docs/grpc/transcoding does
b) Use code generation from the protobuf definition to create a service that will transcode, which is what https://github.com/grpc-ecosystem/grpc-gateway#usage does.

Neither of these directly fit well with the design ethos of YARP. One of the main decisions we have made for YARP is to be transparent about the bodies of requests - we just stream them through the proxy as fast as possible. Modifying grpc streams in-flight would not be congruous with that design decision.

But this seems like something that could be done with the ASP.NET core infra at the heart of YARP. Having middleware that is either doing dynamic transcoding on the fly or a code generator that will take the proto definitions and spit out a transcoding middleware both seem feasible.

I would suggest that this request gets moved to either ASP.NET repo, or the gRPC repos. @JamesNK where would be the most applicable?

**Comment by JamesNK** [comment]
ASP.NET Core and grpc-dotnet has support for this using the in-app gRPC JSON transcoding library. Realistically we aren't going to duplicate doing this in YARP middleware unless there is a compelling reason and a lot of customer demand.

**Comment by karelz** [comment]
Triage: Out of scope of YARP per discussion above. Closing.
