### ISSUE TITLE
Simple Transform

### ISSUE THREAD

**Issue by rnstevens** [microsoft/reverse-proxy#1703]
Appsettings.json - basic route (Transform from documentation)

Adding a Transform section, expecting to see that the QueryString parameter is added.
It's not being added, I understand for documentation it can be added via code or config.
Is there something missing from setup? 

Incoming: http://IncomingHost:5000/mysite

Expecting Yarp: http://IncomingHost:6000/mysite&Testmin=TestminValue
Getting Yarp: http://IncomingHost:6000/mysite

```json
  "ReverseProxy": {
    "Routes": {
      "minimumroute": {
        "ClusterId": "minimumcluster",
        "Match": {
          "Path": "/{**catch-all}"
        },
        "Transforms": [
          {
            "QueryStringParameter": "Testmin",
            "Append": "TestminValue"
          }
        ]
      }
```

**Comment by davidfowl** [comment]
Where's the cluster config?

**Comment by rnstevens** [comment]
Full appsettings.json.... I just included what I thought was relative to the situation.
Just want to know if the Transform section will be added to the mysite request-querystring.

{
  "Urls": "http://localhost:5060;https://localhost:5061",
  "Logging": {
    "LogLevel": {
      "Default": "Debug",
      "Microsoft.Hosting.Lifetime": "Information",
      "Microsoft.AspNetCore": "Debug"
    }
  },
  "iisSettings": {
    "windowsAuthentication": true,
    "anonymousAuthentication": false
  },
  "AllowedHosts": "*",
  "ReverseProxy": {
    "Routes": {
      "minimumroute": {
        "ClusterId": "minimumcluster",
        "Match": {
          "Path": "/{**catch-all}"
        },
        "Transforms": [
          {
            "QueryStringParameter": "Testmin",
            "Append": "TestminValue"
          }
        ]
      }
    },
    "Clusters": {
      "minimumcluster": {
        "Destinations": {
          "realsite": {
            "Address": "http://mysite-hidden"
          }
        }
      }
    }
  }
}

**Comment by MihaZupan** [comment]
Do you see any errors when starting the app?

Using your config, you should immediately see the following error on startup:
```
Unhandled exception. System.InvalidOperationException: Unable to load or apply the proxy configuration.
 ---> System.AggregateException: The proxy config is invalid. (Unknown transform: Append;QueryStringParameter)
 ---> System.ArgumentException: Unknown transform: Append;QueryStringParameter
```

`QueryStringParameter` doesn't exist. The transform is called `QueryValueParameter`.

Looks like one of the [samples in our docs](https://github.com/microsoft/reverse-proxy/blob/9d4b11a481dda92a2ea211fe0b32e6bdf3508a23/docs/docfx/articles/transforms.md?plain=1#L85) is using the wrong value, apologies for that.
