### ISSUE TITLE
Ship InMemoryConfigProvider

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#1713]
https://github.com/microsoft/reverse-proxy/blob/main/testassets/ReverseProxy.Code/InMemoryConfigProvider.cs

InMemoryConfigProvider is convenient for providing config from custom sources. It's copied several times in tests and samples, and even in customer projects.
https://github.com/DuendeSoftware/BFF/blob/main/src/Duende.Bff.Yarp/InMemoryConfigProvider.cs

The main reason I haven't done this yet is because I haven't implemented an update pattern.

**Comment by leastprivilege** [comment]
Yes it is useful. Please include it.

**Comment by samsp-msft** [comment]
> The main reason I haven't done this yet is because I haven't implemented an update pattern.

I think this really is the main value add that would be needed. The current implementation is kind of based on providing new collections each time. Should the routes and clusters be configurable, with startBatch, endBatch semantics so that the collection is editable?

**Comment by leastprivilege** [comment]
This would be a nice to have - but not essential IMO. There are other config stores available if you need that functionality. I see this more as a simple config as code approach.
