### ISSUE TITLE
Does not Route to Subdomain (Second Level Domain)

### ISSUE THREAD

**Issue by ErnestMushinge** [microsoft/reverse-proxy#1719]
### Describe the bug
When you listen on a subdomain the proxy return 302 redirects. It should route to the specified cluster.
However, if you define your hosts as 
"Hosts": [ "www.mydomain.com", "mydomain.com","api.mydomain.com" ]
- The above works, it routes the api.mydomain to the same cluster as mydomain.
- What fails is when you specify api.mydomain.com to be routed to another cluster.

### To Reproduce

Redirected 302 with no exception.
### Further technical details

- Include the version of the packages you are using
V 1.1
- The platform (Linux/macOS/Windows)
   Linux Docker Container

**Comment by karelz** [comment]
Triage: Please provide a complete config for us to look at (ideally minimized repro). Thanks.

**Comment by karelz** [comment]
Triage: Not actionable without more details. Closing for now.
Feel free to reopen if/when there is more info. Thanks!
