### ISSUE TITLE
Update TFM list in YARP 2.0

### ISSUE THREAD

**Issue by samsp-msft** [microsoft/reverse-proxy#1727]
* .NET 5 is out of support. 
* Core 3.1 will be out of support close to when .NET 7 ships. 

So we should reconsider the TFM map, and any issues that may be easier if we don't need to support 3.1.

**Comment by Tratcher** [comment]
Recommended TFM list: 6.0, 7.0

**Comment by MihaZupan** [comment]
#1728 dropped 3.1 and 5.0 support.

We can now also use file scoped namespaces in samples (#1351).
