### ISSUE TITLE
Azure App Service - Forward itself

### ISSUE THREAD

**Issue by andreatosato** [microsoft/reverse-proxy#1745]
Hi, 
I have this configuration:
```JSON
"ReverseProxy": {
    "Routes": {
      "MediaServiceRoute": {
        "ClusterId": "MediaService",
        "AuthorizationPolicy": "Default",
        "Match": {
          "Path": "/media-service/{*any}"
        },
        "Transforms": [
          {
            "RequestHeadersCopy": "true"
          },
          {
            "RequestHeaderOriginalHost": "true"
          },
          {
            "PathRemovePrefix": "/media-service"
          }
        ]
      }
    },
    "Clusters": {
      "MediaService": {
        "Destinations": {
          "MediaServiceInstance": {
            "Address": "https://dev-ms.azurewebsites.net/"
          }
        }
      }
    }
  }
  ```

My WebApp is on: https://dev-ga.azurewebsites.net
My API is on: https://dev-ms.azurewebsites.net/

When I call my YARP application, YARP send request to itself. Why?
In log I see that application what to proxy request correctly, but, it send request to itself.

This is my log:
2022-06-01 17:20:42.110 +00:00 [Information] Yarp.ReverseProxy.Forwarder.HttpForwarder: Proxying to https://dev-ms.azurewebsites.net/media-player-events HTTP/2 RequestVersionOrLower no-streaming
2022-06-01 17:20:42.132 +00:00 [Information] Microsoft.AspNetCore.Hosting.Diagnostics: Request starting HTTP/1.1 POST https://dev-ga.azurewebsites.net/media-player-events application/json;+charset=utf-8 -

Can anyone help me?

//cc @sciocoder

**Comment by Tratcher** [comment]
Because you're setting `"RequestHeaderOriginalHost": "true"`. The DNS for the two sites probably resolves to the same address, and then the host header is used to route requests within app service. Turn off RequestHeaderOriginalHost and see what happens.

**Comment by andreatosato** [comment]
Thanks a lot @Tratcher, works fine!
