### ISSUE TITLE
Add an overload of ReassignProxyRequest that accepts both route and cluster

### ISSUE THREAD

**Issue by asgeirn** [microsoft/reverse-proxy#1752]
### Discussed in https://github.com/microsoft/reverse-proxy/discussions/1749

<div type='discussions-op-text'>

<sup>Originally posted by **asgeirn** June  2, 2022</sup>
Hi!

I'm attempting using Unleash feature toggles to reassign proxy requests as described in https://microsoft.github.io/reverse-proxy/articles/ab-testing.html

However, the proxy route contains a PathSet tranform, and even if i reassign the proxy request to another cluster, this transform is still applied.

Is there a way to disable this transform for the request when I reassign the request to another cluster?</div>

Assigning both route and cluster when reassigning proxy request worked for me, this is the actual code I used instead of `ReassignProxyRequest`, with both route and cluster retrieved from `IProxyStateLookup`:

```cs
    var oldFeature = context.GetReverseProxyFeature();
    var destinations = cluster.DestinationsState;
    var newFeature = new ReverseProxyFeature()
    {
        Route = route,
        Cluster = cluster.Model,
        AllDestinations = destinations.AllDestinations,
        AvailableDestinations = destinations.AvailableDestinations,
        ProxiedDestination = oldFeature.ProxiedDestination,
    };
    context.Features.Set<IReverseProxyFeature>(newFeature);
```

**Comment by karelz** [comment]
Triage: We should be able to add an overload.
Should be simple - anyone interested in a contribution?

**Comment by ethankrein** [comment]
> anyone interested in a contribution?

Just an overload for ReassignProxyRequest that accepts route in addition to cluster? If so, I'd like to take this one.
