### ISSUE TITLE
How to enable cache between YARP and Clusters destinations

### ISSUE THREAD

**Issue by Nelo-cool** [microsoft/reverse-proxy#1754]
Hello guys!
### What should we add or change to make your life better?
How to enable (or implement) inmemory cache (or distributed -> redis or other)? Is this possible within Yarp?
### Why is this important to you?
My customer doesn't have cache on your services because source code is outdated, platform is outdated, but it needs to be able to handle the high load (for some time).

**Comment by Tratcher** [comment]
You can use the AspNetCore ResponseCaching middleware in YARP:
https://docs.microsoft.com/en-us/aspnet/core/performance/caching/middleware?view=aspnetcore-6.0

**Comment by Nelo-cool** [comment]
Yes, i can, I thought of this yesterday, used middleware !before! YARP. My example (worked sample):
![screen](https://user-images.githubusercontent.com/902820/172352218-d3fa4075-dfee-469b-b7e1-9a253e4d9963.JPG)

**Comment by Nelo-cool** [comment]
Thanks guys :)

**Comment by Tratcher** [comment]
Can you explain your comment about setting `CachControl: max-stale` for suppression?

**Comment by Nelo-cool** [comment]
I can explain my comment about **max-stale**: 

**Short answer: this is a workaround for our code. Simple and fast. But without enough testing. In the end, we may go the other way. ** 

Long:
Without this flag almost all browsers (header value) send CacheControl:no-cache or other values witch force a non-cached page request which causes the ResponseCachingMiddleware implementation to ignore this request (ignore the cache) and pass it on to the server to retrieve the data.

![1](https://user-images.githubusercontent.com/902820/172795973-cb5b4d75-29f5-4fd8-98be-e202ab51653d.JPG)

next:
![2](https://user-images.githubusercontent.com/902820/172796060-98107874-e7a6-4a1f-bfd1-d3e00bba9811.JPG)

next:
![3](https://user-images.githubusercontent.com/902820/172796073-6de43135-b9b5-446b-891e-4fa193dfd282.JPG)

**Comment by adityamandaleeka** [comment]
Triage: Sounds like this has been answered, so I'll close the issue.
