### ISSUE TITLE
Intermittent issue with HTTP2_PROTOCOL_ERROR (YARP and Asp .NET core)

### ISSUE THREAD

**Issue by arunravir** [microsoft/reverse-proxy#1767]
We are using YARP as a reverse proxy between our web servers hosted with in intranet. We are facing the Http2_Protocol_Error with the Signin-OIDC callback middleware in ASPNet Core. 

All the http requests are routed to the different endpoints from the application(hosting YARP). The Identity Server is used for the Single signon. The login page is rewritten to the identity server using the YARP and once the user entered the user name and password, the details are validated in Identity server and then redirected to the CallbackPath configured in the OIDC client configuration.

When the user logs in and redirected to the middleware (registered in CallbackPath) and it fails with Http2_protocol_error. The request is not sent to the server. 

Note: This issue is happening intermittently in production systems . I didn't see any error reported in the Website log file even in debug / trace levels.

The HttpError.log file shows the following errors

```
2022-06-14 20:05:59 17X.XX.XX.XXX 52715 17X.XX.XX.XXX 443 HTTP/2 POST /signin-oidc 829 - 400 - RequestLength - TCP

2022-06-15 19:22:23 17X.XX.XX.XXX 59605 17X.XX.XX.XXX 443 - - - 9 - - - LimitExceeded - TCP
```

**System Details:**
Windows 10 Enterprise
Version : 21H2
OS build : 19044.1766 

IIS 10.0.19041.1
.Net Core Runtime - 3.1.22
.Net Windows Hosting Bundle - 3.1.22

**Error :**
![image](https://user-images.githubusercontent.com/1920791/174922784-4bacbec1-fd15-48d2-9771-1b063f85326e.png)

**Comment by Tratcher** [comment]
```
2022-06-14 20:05:59 17X.XX.XX.XXX 52715 17X.XX.XX.XXX 443 HTTP/2 POST /signin-oidc 829 - 400 - RequestLength - TCP
2022-06-15 19:22:23 17X.XX.XX.XXX 59605 17X.XX.XX.XXX 443 - - - 9 - - - LimitExceeded - TCP
```
That implies your request was rejected because something was too large. My guess would be the cookies. Can you enable the HttpSubStatus field to narrow down which part?
https://docs.microsoft.com/en-us/troubleshoot/developer/webapps/iis/www-administration-management/http-status-code#4xx---client-error

Can you also share the fields header so we know which values are which?

**Comment by arunravir** [comment]
I am not seeing any errors logged in the http error log files with the Logging enabled with the Http Sub Status.

**Comment by Tratcher** [comment]
I'm going to close this as external and we can track further investigation with https://github.com/dotnet/aspnetcore/issues/42303.
