### ISSUE TITLE
Server Send Events (SSE) issues

### ISSUE THREAD

**Issue by semsitivity** [microsoft/reverse-proxy#1768]
Hi,
I didn't manage to make SSE working with a direct forwarder.
I can't figure out what are the expected headers or body content returned by the server.
Of course text/event-stream has to be set, but does a chunked Transfer-Encoding has to be set or something else ?
Today, my client stays connected but does not receive any data (while traces show when flushing on server side).
Is there a sample of server working well with reverse proxy somewhere?

**Comment by karelz** [comment]
Triage: We tested SignalR with YARP earlier. It worked well.
Do you have a small HelloWorld-style repro demonstrating the problems?

**Comment by semsitivity** [comment]
Hi,
I'm really sorry. YARP works absolutly well with SSE. The issues was coming from a nginx reverse proxy which was buffering the requests. Sorry for my message.
Investigating the issue makes me debug and read a lot of the code, and I learnt a lot! Thank you for your answer.
