### ISSUE TITLE
LoadFromMemory

### ISSUE THREAD

**Issue by YukaAn** [microsoft/reverse-proxy#1783]
I am trying to use the reverse-proxy 1.1.0 in my .net 6 project. I couldn't find the reference for .LoadFromMemory that I saw example from github. How can I make it working?

**Comment by zhiweiv** [comment]
It should be here: https://microsoft.github.io/reverse-proxy/articles/config-providers.html#example.

**Comment by YukaAn** [comment]
Yes, but when I include the reference of 1.1.0 from nuget.org in my project, it doesn't recognize that method (LoadFromMemory)

**Comment by YukaAn** [comment]
> Yes, but when I include the reference of 1.1.0 from nuget.org in my project, it doesn't recognize that method (LoadFromMemory)

**Comment by YukaAn** [comment]
> It should be here: https://microsoft.github.io/reverse-proxy/articles/config-providers.html#example.

Yes, but when I include the reference of 1.1.0 from nuget.org in my project, it doesn't recognize that method (LoadFromMemory)

**Comment by zhiweiv** [comment]
LoadFromMemory is the custom extension by your own code, not part of YARP, for the example below, it adds LoadFromMemory method to IReverseProxyBuilder, then you can call builder.Services.AddReverseProxy().LoadFromMemory();
```
namespace Microsoft.Extensions.DependencyInjection
{
    public static class InMemoryConfigProviderExtensions
    {
        public static IReverseProxyBuilder LoadFromMemory(this IReverseProxyBuilder builder, IReadOnlyList<RouteConfig> routes, IReadOnlyList<ClusterConfig> clusters)
        {
            builder.Services.AddSingleton<IProxyConfigProvider>(new InMemoryConfigProvider(routes, clusters));
            return builder;
        }
    }
}
```

**Comment by YukaAn** [comment]
So you mean I need to add this extension and the InMemoryConfigProvider code to my project? Actually I see the code is included in the latest src code in Github, under src->ReverseProxy->Configuration, will it be included in the next release?
________________________________

**Comment by zhiweiv** [comment]
The code is not in release 1.1 branch, so you have to write your own. I guess the next release should have the built-in InMemoryConfigProvider.

Thanks for the information too.
