### ISSUE TITLE
Use freezable pattern for contract types instead of deep cloning

### ISSUE THREAD

**Issue by alnikola** [microsoft/reverse-proxy#179]
### What should we add or change to make your life better?
Currently, we are making deep clones of all `Abstractions.*.Contract` types' instances (e.g. `LoadBalancingOptions` or `QuotaOptions`) before adding them to repositories. On top of that, some of them even have duplicates in `RuntimeModel` namespace with exactly the same contract, but different names (e.g. `LoadBalancingOptions` and `BackendConfig.BackendLoadBalancingOptions`). This is done to ensure safety and consistency of concurrent configuration reads in requests handling as well as to avoid accidental modifications.

However, it leads to code duplication and extra allocations in runtime. Thus, it's proposed to get rid of deep cloning and make all `Abstractions.*.Contract` types freezable which means they will be mutable during configuration initialization or refresh, but will prohibit any state changes after a `Freeze()` method is called. Each top-most configuration type (e.g. `Backend` and `Route`) will freeze it's state on a `Freeze()` call and ensure that all nested instances do the same (i.e. `Backend.Freeze()` must also call` LoadBalancingOptions.Freeze()`). Further, `ProxyConfigLoader` will call `Freeze()` on all top-most instances before adding them into repositories.

### Why is this important to you?
It will eliminate code duplication, the reduce number of allocations and memory footprint.

**Comment by Tratcher** [comment]
Prior art: AsReadOnly(), IsReadOnly, CopyAsReadOnly()
https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1.asreadonly?view=netcore-3.1
https://github.com/dotnet/aspnetcore/blob/0b90802e712a0dad12eebf2c7ad7abea9869ae54/src/Http/Headers/src/MediaTypeHeaderValue.cs#L421

**Comment by Tratcher** [comment]
Another proposal is to use C# 9 record types so the config objects are always immutable after creation.
https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-9#record-types

Known issues:
- Redesign IProxyConfigFilter (not used by anyone yet?).
- Some of the properties use mutable types like Cluster.Metadata is an IDictionary. These would need to become readonly collections. Would this complicate their creation?

**Comment by Tratcher** [comment]
Note today we make some costly deep clones of many objects to avoid anyone mutating them while we're using them.

https://github.com/microsoft/reverse-proxy/pull/328/files#diff-62ef4e5f2fda56af2de14f76479908daa52ef2bb11732b1f08d39c5782085b39R63

https://github.com/microsoft/reverse-proxy/blob/e4426b93621a4f0e4c55c626236a21404efd264e/src/ReverseProxy/Abstractions/ClusterDiscovery/Contract/Cluster.cs#L59-L72
