### ISSUE TITLE
Unit testing IProxyStateLookup is complicated by inaccessible members of ClusterState

### ISSUE THREAD

**Issue by jmezach** [microsoft/reverse-proxy#1792]
### What should we add or change to make your life better?
I'm currently trying to implement a middleware based on the ideas describes in [this document](https://microsoft.github.io/reverse-proxy/articles/ab-testing.html) which suggests using the `IProxyStateLookup` service in order to the configured clusters, etc. While writing some unit tests for this middleware I figured I could mock out the `IProxyStateLookup` interface and be off to the races. Unfortunately the `GetClusters()` method on that interface returns an `IEnumerable<ClusterState>`. While `ClusterState` does have a constructor that takes a string, it doesn't seem to be possible to set values for `ClusterModel` for example, which my middleware needs as it inspects some metadata on the cluster in order to its thing. There is a setter on that property, but it is internal so I can't access it (except through reflection of course ;)).

### Why is this important to you?
Ideally I would like to have some unit tests in place for my middleware in order to catch bugs as early as possible, but not being able to provide the appropriate data through the `IProxyStateLookup` interface blocks me from doing that.

**Comment by samsp-msft** [comment]
@Tratcher - what pattern do we use to allow creation of objects like this for unit tests?
