### ISSUE TITLE
WebSocket middleware

### ISSUE THREAD

**Issue by crfrolik** [microsoft/reverse-proxy#1797]
### What should we add or change to make your life better?

Is it possible to have middleware for WebSocket messages? To be specific, I'd like my proxy to allow some websocket messages to go through and some to be blocked. Not sure if this is currently possible or not.

### Why is this important to you?

Proxying a web server that doesn't support HTTPS or authentication. Would like to prevent messages that the logged in user does not have authorization to send.

**Comment by Tratcher** [comment]
YARP does not include support for filtering or modifying Request or Response bodies, or WebSockets. However, this us functionality you can add.

Here's an example of a middleware that counts WebSocket messages. You should be able to copy and modify it to more deeply inspect messages. Beware of the performance overhead of deep inspections like this.
https://github.com/microsoft/reverse-proxy/blob/main/src/ReverseProxy/WebSocketsTelemetry/WebSocketsTelemetryMiddleware.cs
