### ISSUE TITLE
Use in a standalone .NET 6 console application

### ISSUE THREAD

**Issue by crfrolik** [microsoft/reverse-proxy#1798]
### What should we add or change to make your life better?

Is it possible to use YARP in a console app? I tried to do this but quickly ran into problems, e.g. not having a `IApplicationBuilder` object to use.

All of the samples seem to be using `Sdk="Microsoft.NET.Sdk.Web"`, and I can't get them to work with a plain console app.

### Why is this important to you?

Running a console app instead of an ASP.NET web app.

**Comment by samsp-msft** [comment]
YARP is dependent on ASP.NET Core to provide the incoming http handling - it is in fact written as ASP.NET Core middleware. 

The better question is how is ASP.NET Core different from a console app - and the answer for most is none at all - when using the kestrel web server built into ASP.NET - it is effectively a console app - it doesn't depend on IIS or other platform infrastructure for handling http.

What are you looking for from it being a console app?

**Comment by crfrolik** [comment]
> What are you looking for from it being a console app?

Perhaps I'm just inexperienced when it comes to ASP.NET. My understanding is that e.g. `dotnet run Foo.dll` is only recommended for development scenarios, and that I'm expected to actually expected to use something like IIS for production. I was hoping for something lighter weight.

**Comment by samsp-msft** [comment]
There is no need to use IIS, you can create an exe for an ASP.NET Core app using the [`dotnet publish`](https://docs.microsoft.com/dotnet/core/tools/dotnet-publish) command. When using the publish command, you get to specify whether the package should include the .NET runtime (or it needs to be separately installed) and which OS / CPU architecture you want to build for.
See https://docs.microsoft.com/dotnet/core/deploying/ for more info.

**Comment by crfrolik** [comment]
Thanks for the response.

It sounds like my original request isn't feasible, so I'm closing this. In the meantime I'll look into your suggestion.

**Comment by samsp-msft** [comment]
I think you'll find that with the kestrel server ( which is what is used by the samples/ docs) that you effectively are running a console app. You can put in a main function and read from the args, write to the console etc. Kestrel is a high performance, reliable server (its not a toy for debugging). Its made this way so that .NET Core can be used from a linux container etc with minimal dependencies.
