### ISSUE TITLE
X-Forwarded-For Gets overwritten on google cloud run

### ISSUE THREAD

**Issue by stefandevo** [microsoft/reverse-proxy#1804]
I am hosting the docker container on google cloud run. The clients IP address is automatically placed into the X-Forwarded-For header. 

However when I use yarp to call another cloud run container the original client ip is overwritten. 

I found a way to do a transformation by reading the header value and place it inside a new header x-clientip but I would like to pass the value inside the regular headers  X-Forwarded-For headers. 

Any suggestions?

**Comment by Tratcher** [comment]
The x-forwarded transforms default to replacing the header to prevent spoofing. For a nested setup like yours you can change them to Append instead. See https://microsoft.github.io/reverse-proxy/articles/transforms.html#x-forwarded

**Comment by stefandevo** [comment]
Thx for your guidance, but that did not work.
I added following transform:

```
          {
            "X-Forwarded": "Set",
            "For": "Append",
            "Proto": "Off",
            "Prefix": "Off",
            "HeaderPrefix": "X-Forwarded-"
          }
```

Original IP was removed.

**Comment by stefandevo** [comment]
Ok. I added:

```
          { 
            "X-Forwarded": "Append",
            "For": "Append"
          }
```

The original host IP address is now the first in the list (together with the proxy address).
