### ISSUE TITLE
More pattern in match

### ISSUE THREAD

**Issue by WeihanLi** [microsoft/reverse-proxy#1809]
### What should we add or change to make your life better?

``` json
"Routes": {
      "images" : {
        "ClusterId": "images",
        "Match": {
          "Path": "*.(jpg|png|gif|jpeg|svg)"
        }
      }
}
```

It seemed it's not working now

### Why is this important to you?

It would help reduce the complexity of the configuration

**Comment by adityamandaleeka** [comment]
@WeihanLi Take a look at this doc for how to use regex in these constraints: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-6.0#regular-expressions-in-constraints

**Comment by WeihanLi** [comment]
@adityamandaleeka great thanks

**Comment by WeihanLi** [comment]
Hi @adityamandaleeka , I'm trying to match all images with `{any:regex(.+\\.(jpg|png|gif|jpeg))}` path pattern, while it seemed it 
does not work, is there something wrong with my config?

Request path: `/abc/test/test.jpg`

**Comment by WeihanLi** [comment]
> Hi @adityamandaleeka , I'm trying to match all images with `{any:regex(.+\\.(jpg|png|gif|jpeg))}` path pattern, while it seemed it does not work, is there something wrong with my config, could you please help on this
> 
> Request path: `/abc/test/test.jpg`

Fixed with `{**any:regex(.+\\.(jpg|png|gif|jpeg))}`
