### ISSUE TITLE
static readonly string fields

### ISSUE THREAD

**Issue by WeihanLi** [microsoft/reverse-proxy#1810]
Just noticed that there're some static read-only fields like follows:

![image](https://user-images.githubusercontent.com/7604648/180628432-65a05485-ab66-4333-bf06-5991c85deb15.png)

![image](https://user-images.githubusercontent.com/7604648/180628439-c7aa06cf-f973-4034-ab47-6434d0f7e265.png)

Should we consider using `const` instead of `static readonly` when possible, especially for internal types

**Comment by adityamandaleeka** [comment]
We could change this, but only for the internal ones (so that we don't make any breaking changes).

**Comment by adityamandaleeka** [comment]
Triage: this seems pretty low in value.
