### ISSUE TITLE
Support redis

### ISSUE THREAD

**Issue by wzxinchen** [microsoft/reverse-proxy#1821]
I want to build a redis server, which will be called by the end user. The scale of users may be very large, at the level of millions.

I can set up a redis server for each user, but the cost is obviously unpredictable.

The perfect solution I have in mind is to set up only one or a limited number of redis servers, and set up several folders (or categories) in the server. The folder name is consistent with the user name, so as to achieve my goal.

However, the problem is that the data of different users should be isolated from each other to prevent the data of different users from affecting each other. This involves the permission function of redis itself, but it seems that its permission function is not so strong.

Therefore, a compromise but feasible solution is to establish only one or a limited number of redis servers, and then use yarp to conduct a reverse proxy. The core purpose of the reverse proxy is to automatically add user name restrictions to the redis requests sent by users and limit some inappropriate operations.

However, it seems that yarp does not support reverse proxy for redis. Is there any relevant information to expand this function?

**Comment by samsp-msft** [comment]
Yarp is an http proxy. AFAIK Redis uses its own protocol RESP to communicate between clients and servers. You will need to find a proxy that supports it or create your own.
