### ISSUE TITLE
Doc server configurations

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#183]
Doc that YARP is supported on all AspNetCore servers. Link to the setup docs for each server. All of these servers provide SSL termination.

Highlight advanced scenario we plan to support though kestrel like early connection interception.

https://twitter.com/demisbellot/status/1263606633239904257?s=19

**Comment by karelz** [comment]
Triage: While we work on all server scenarios, we primarily test with Kestrel. We do not think we need extensive documentation for each server.
