### ISSUE TITLE
Add a check for duplicate route IDs in provider(s)

### ISSUE THREAD

**Issue by jura1514** [microsoft/reverse-proxy#1830]
Hi all,

If you are loading from multiple configuration sources and have a duplicate route ID in one of your configs, YARP is going to take the last one which is loaded and overwrite the first route ID.

I would like to add a validation check to inform the user that he has a duplicate route ID.

I checked YARP documentation and closest I found is **IProxyConfigFilter**, which partially does the job. However, it becomes tricky when configurations are reloaded. 

Also, looked at IProxyStateLookup and IProxyConfigProvider which has IProxyConfig and IChangeToken, but so far could not find an elegant solution.

I wonder, what would be the best way to achieve what I am trying to do? 

Many thanks in advance

Update:

have been looking more at a code, and I think it's might be a bug there, since looks like it suppose to check for duplicate routes but **seenRouteIds** collection is never updated

![image](https://user-images.githubusercontent.com/11175230/185145572-d096cdbe-7259-4087-9abd-fa518fc05d21.png)

**Comment by MihaZupan** [comment]
This is indeed a bug - our intention was to fail loading the config and warn the user if there are duplicate route definitions present.
