### ISSUE TITLE
FunctionalTests not running on command line build or CI

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#1840]
The functional test project https://github.com/microsoft/reverse-proxy/blob/main/test/ReverseProxy.FunctionalTests/Yarp.ReverseProxy.FunctionalTests.csproj isn't running when testing from the command line or CI. It's built but not executed.

I noticed because Yarp.ReverseProxy.HttpProxyCookieTests_Http2.ProxyAsync_RequestWithCookieHeaders started failing in VS after a recent SDK update. We need to react to a aspnetcore bugfix.

**Comment by adityamandaleeka** [comment]
> The functional test project https://github.com/microsoft/reverse-proxy/blob/main/test/ReverseProxy.FunctionalTests/Yarp.ReverseProxy.FunctionalTests.csproj isn't running when testing from the command line or CI. It's built but not executed.

`dotnet test` in `test/ReverseProxy.FunctionalTests` seems to run them just fine for me. Are you using a different workflow?

**Comment by adityamandaleeka** [comment]
Oh, I see. `build.[cmd|sh] -test` doesn't discover them.

**Comment by adityamandaleeka** [comment]
lol
 https://github.com/dotnet/arcade/blob/e7ede87875f41a9b3df898ae08da5ebc96e24f56/src/Microsoft.DotNet.Arcade.Sdk/tools/Tests.props#L17
