### ISSUE TITLE
IdentityServer4

### ISSUE THREAD

**Issue by vpaulino** [microsoft/reverse-proxy#185]
### What should we add or change to make your life better?
Yarp should have the capacity to execute OIDC with identityServer4
### Why is this important to you?
Having a reverse proxy in front of my applications with this cross curting concern will enable reusability and identity integration between diferent applications of the same system.

**Comment by Tratcher** [comment]
YARP plugs into the AspNetCore pipeline so you should also be able to plug in IdentityServer4 along side it. What support do you anticipate needing that's proxy specific? Can you try this with preview 1 and let us know how far you get?

RE: Authorization per proxy route https://github.com/microsoft/reverse-proxy/issues/122

**Comment by karelz** [comment]
Triage: No response for 1+ year, closing.
