### ISSUE TITLE
API documentation unavailable

### ISSUE THREAD

**Issue by GREsau** [microsoft/reverse-proxy#1859]
The YARP API documentation used to be available at https://microsoft.github.io/reverse-proxy/api/index.html, but it was deleted (presumably unintentionally) by this commit from GH actions: https://github.com/microsoft/reverse-proxy/commit/a18c5ee937a51467264e290ed83f9ee9ac926495

**Comment by MihaZupan** [comment]
Thank you for letting us know, this was indeed unintentional.
The API docs should be available as soon as #1860 is merged.
