### ISSUE TITLE
Non thread safe Random is used in ProxyInvokerMiddleware

### ISSUE THREAD

**Issue by AlexanderButs** [microsoft/reverse-proxy#186]
### Describe the bug
Non thread safe Random is used in ProxyInvokerMiddleware. Is it some kind of intentional? Should IRandomFactory be used instead of direct Random class instantiation?

### To Reproduce
Look inside code base :)

### Further technical details
None

**Comment by Tratcher** [comment]
True, but that is only used as a failsafe. The associated log message says:
"More than one destination available for backend `{backendId}`, load balancing may not be configured correctly. Choosing randomly."

We can fix it, but the app should really enable load balancing so they can control how the load is distributed.

**Comment by samsp-msft** [comment]
Good catch, probably should be updated - if only so we have a common design pattern for how random should be used.
