### ISSUE TITLE
Cluster "Action" for given routes

### ISSUE THREAD

**Issue by tswalker** [microsoft/reverse-proxy#1868]
### What should we add or change to make your life better?
It would be nice to leverage the HttpClient for an inbound route for generating immediate responses using the appsettings.json file with a new cluster parameter called "Action" (or similar).  As "Destinations" defines how the forwarder handles the request, "Action" would permit (with appropriate properties) an immediate response without the need to handle that path within Program.cs and additional middleware.

### Why is this important to you?
Currently, I need to check the path of the request for a route (say "myspecialroute") in middleware to generate a response and terminate the chain.  Using something simple like:

```c#
app.Use((context, next) =>
{
	var path = context.Request.Path;
	if (path.HasValue && path.Value.Contains("myspecialroute"))
	{
		context.Response.StatusCode = StatusCodes.Status400BadRequest;
		return context.Response.WriteAsync("This integration is not supported.");
	}
	return next();
});
```

Having this 'actionable' configured in appsettings would be nice as if the route changed, a simple config file update would do the trick versus having to re-program the middleware.

**Comment by Tratcher** [comment]
You could also define these special routes in AspNet MVC/Razor/minimal. YARP shares the route table with the rest of the app.

What capabilities would you expect an 'Action' to have, and how would those be described? Can you give some example JSON definitions?

**Comment by karelz** [comment]
Triage: 12 days no response, closing as not actionable. If/when there is more info, feel free to reopen. Thanks!
