### ISSUE TITLE
Docs: Mention 6.0 before 3.1

### ISSUE THREAD

**Issue by karelz** [microsoft/reverse-proxy#1873]
In Getting Started Page: https://microsoft.github.io/reverse-proxy/articles/getting-started.html

Note that 5.0 is Out-of-support -- remove it: https://github.com/dotnet/core/blob/main/releases.md

**Comment by Tratcher** [comment]
This would be in the 1.1 and latest branches. 3.1 and 5.0 have already been removed from main.

**Comment by karelz** [comment]
By end of next week we should ship 2.0 RC1, which will override docs. No point in changing 1.1 docs. Closing.
