### ISSUE TITLE
Stream is disposed after proxy response and some other middleware wants to interact with req-res body stream

### ISSUE THREAD

**Issue by jkone27** [microsoft/reverse-proxy#1876]
### Describe the bug
If you chaing middleware to interact with request/response body, after yarp has sent the request, finds the stream closed

```
Cannot access a disposed object.
Object name: 'The stream with Id 8e058f7e-32e4-47ee-aba4-023bdb4ace4e and Tag  is disposed.'.
    error.message   Connection id "0HML1APKQUPKA", Request id "0HML1APKQUPKA:00000002": An unhandled exception was thrown by the application.
    error.rootexceptionmessage  [System.ObjectDisposedException]: Cannot access a disposed object.
Object name: 'The stream with Id 8e058f7e-32e4-47ee-aba4-023bdb4ace4e and Tag  is disposed.'.
    error.source    Travix.Common.Logging.AspNetLoggerProvider
    error.stacktrace       at Microsoft.IO.RecyclableMemoryStream.ThrowDisposedException() in /_/src/RecyclableMemoryStream.cs:line 1437
   at Microsoft.IO.RecyclableMemoryStream.Seek(Int64 offset, SeekOrigin loc) in /_/src/RecyclableMemoryStream.cs:line 1245
   at ACME.Common.WebService.Middleware.Logging.ServerRequestResponseLoggingMiddleware.Invoke(HttpContext httpContext, ILoggerContext loggerContext, ICorrelationContextAccessor correlationContextAccessor)
   ```
This causes other middleware to fail and apps to return 500 where in fact they should just proceed fine?

### To Reproduce

add a middleware which accesses the body stream object reads is in a memory stream, 
and replays the original body stream afterwards (after temp reading it or using its content..)

**Comment by Tratcher** [comment]
Can you show the middleware? Intercepting the response body is delicate work. It looks like this is for logging? You should try the new logging middleware in .NET 7, or at least use it as an example:
https://github.com/dotnet/aspnetcore/blob/01177230911caab93dff106e4f0d973a06f51bf3/src/Middleware/HttpLogging/src/HttpLoggingMiddleware.cs#L159-L169

**Comment by karelz** [comment]
Triage: 12 days no response, closing as not actionable. If/when there is more info, feel free to reopen. Thanks!
