### ISSUE TITLE
YAML to define request and response contract for body transformation

### ISSUE THREAD

**Issue by juniormayhe** [microsoft/reverse-proxy#188]
### What should we add or change to make your life better?
Could we please have a way to load a YAML (OpenAPI 3) file to declaratively say, for a route, what are the expected datatypes and structure for _request_ and _response_ contracts?

Then, after loading this YAML, we could have (a) middleware classes for the proper YAML validation (comparing payload format with predefined YAML structure) and (b) middleware class for _request_ and _response_ body transformation. Regarding request and response body transformations, they could be done automatically (based on YAML definitions) or manually by adding the needed classes in middleware for transforming the content.

I have seen an issue opened here but it seems more related to [URL transformations](https://github.com/microsoft/reverse-proxy/issues/21). 

### Why is this important to you?
Have a unique package that gathers all necessary classes for adding the YAML contracts for request and response per route, configure classes for validation, and transformation of request and response body.

**Comment by Tratcher** [comment]
YAML aside, can you give specific examples about the kinds of body transformations you had in mind?

We don't currently have plans for any request or response body transformations. Such transformations are extremely expensive and scenario specific. 

That said, this is the kind of thing that can be plugged into the pipeline as middleware today, I don't think it would require any architectural changes to support.

**Comment by samsp-msft** [comment]
Triage: Processing & transforming the request/response bodies is not something we are going to build into YARP. That is a feature that is better handled by [Ocelot](https://github.com/ThreeMammals/Ocelot).
