### ISSUE TITLE
Refused to apply style from <URL> because its MIME type ('text/html') is not a supported stylesheet MIME type

### ISSUE THREAD

**Issue by mihaimyh** [microsoft/reverse-proxy#1880]
Hello,

We have an intranet Blazor server app on top of which we've added YARP to redirect users to another server when they click a button on the Blazor UI.
The problem is that some static files hosted on the target server are not loading, probably due to the content security policy (CSP) applied on the Blazor app.

![image](https://user-images.githubusercontent.com/549272/193750839-f3adff7c-8549-4541-ba73-4ce727149fa3.png)
![image](https://user-images.githubusercontent.com/549272/193751023-28cfa04b-81b9-4baa-af65-43a83d715a7c.png)

**Comment by Tratcher** [comment]
That sounds more like you're accidentally being sent an HTML file instead of a CSS file.
https://stackoverflow.com/questions/49406057/refused-to-apply-style-from-because-its-mime-type-text-html-is-not-a-supp

I suggest enabling debug level logs on the proxy and destination to figure out if this is a routing issue.

**Comment by mihaimyh** [comment]
Yes, it seems the index.html of the Blazor app is being served at the proxied route

**Comment by karelz** [comment]
Triage: Looks like it is understood and resolved as problem with routing configuration. Closing. Feel free to reopen if you need more help.

**Comment by mihaimyh** [comment]
I am still struggling with this, I am unable to fix the CSS issues I am facing when I am redirected to the backend destination from the Blazor app:

![image](https://user-images.githubusercontent.com/549272/197069829-97348756-b1e5-4a6b-9202-de1a36e25642.png)

**Comment by mihaimyh** [comment]
Seems that removing the `"AuthorizationPolicy": "ReverseProxy.AlertManager"` from the ReverseProxy configuration in appsettings.json fixed the issue.

**Comment by mihaimyh** [comment]
I actually found that my custom implementation of `ITicketStore` was causing the issues due to some `DbUpdateConcurrencyException`
