### ISSUE TITLE
Change framework to net5.0

### ISSUE THREAD

**Issue by TeddyAlbina** [microsoft/reverse-proxy#189]
### Follow dotnet 5 framework identifier evolution

I have Visual Studio 2019 16.6 the installed dotnet framework 5.0.100-preview.4.20258.7 wich have the framework identifier .net5 instead of netcoreapp5.0 .

So it cannot loads the projects within the solution,

**Comment by Tratcher** [comment]
Note we have some scripts in the repo to address this like restore.cmd that downloads a specific version of the SDK to a local .dotnet directory and startvs.cmd that starts VS using that local SDK. With these local versions I'm able to open the repo solution in VS 16.7.0-p1.

But yes, we do still need to move everything to net5.0.
