### ISSUE TITLE
How to create scoped middleware

### ISSUE THREAD

**Issue by thomas-illiet** [microsoft/reverse-proxy#1898]
Hello guys,

Following documentation help me to create custom middleware: https://microsoft.github.io/reverse-proxy/articles/middleware.html

I would like to use the scoped service in the middleware,
Do you have any example to do this?

Regards
Thomas

**Comment by Tratcher** [comment]
https://learn.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-6.0#request-services

`HttpContext.RequestServices.GetRequiredService<MyScopedService>()`
