### ISSUE TITLE
The daily build  not work now

### ISSUE THREAD

**Issue by witskeeper** [microsoft/reverse-proxy#1900]
### Some details

**How many backends are in your application?**

- [ ] 1-2
- [ ] 3-5
- [ ] 6-10
- [x] 10+

**How do you host your application?**

- [x] Kubernetes
- [ ] Azure App Service
- [ ] Azure VMs
- [ ] Other Cloud Provider (please include details below)
- [ ] Other Hosting model (please include details below)

### What did you think of YARP?

The daily build  not work now.  
I saw the latest version is 2.0.0-preview.1.22457.2 , and build date is  2022-09-08.
From docs: [daily build](https://github.com/microsoft/reverse-proxy/blob/main/docs/DailyBuilds.md).

**Comment by Tratcher** [comment]
Hmm, the internal code mirror seems to be down...

**Comment by MihaZupan** [comment]
This has been resolved with #1901
A new build is now available on the dotnet-libraries feed.
