### ISSUE TITLE
InMemoryConfigProvider not included with release of 1.1.1

### ISSUE THREAD

**Issue by hatzhang** [microsoft/reverse-proxy#1905]
I am trying to follow the ReverseProxy.Code.Sample, and use InMemoryConfigProvider to configure the proxy. 
InMemoryConfigProvider is not included in the version of 1.1.1, so i just copied it from main branch, but somehow i can't get it work, the reverse proxy pipeline not configured correctly, and ProxyPipelineInitializerMiddleware or ForwarderMiddleware won't be invoked. 

I wonder if there are any preview version newer than 1.1.1, and it's has InMemoryConfigProvider  included.

Thanks.

**Comment by Tratcher** [comment]
It's part of 2.0. https://github.com/microsoft/reverse-proxy/pull/1732

You can get preview builds from https://github.com/microsoft/reverse-proxy/blob/main/docs/DailyBuilds.md

**Comment by hatzhang** [comment]
Thanks. I made a mistake when combining the destination url ```${my-path}{**catchall}```, which should be ```${my-path}{{**catchall}}```. 
Anyway, it now works with the code copied or directly using the preview builds.
