### ISSUE TITLE
Kubernetes Controller does not update YARP config ongoing with new/modified/deleted resources

### ISSUE THREAD

**Issue by archonandrewhunt** [microsoft/reverse-proxy#1912]
### Describe the bug
Kubernetes Controller watches do not work to update YARP config after initial deployment. 

### To Reproduce
1. Deployment a service with ingress to k8s cluster
2. Deploy YARP K8s Controller
3. Update initial deployment, recreate the pod for example to produce a different endpoint
4. Controller will not update the config, and the routing from your YARP ingress will stop working.

### Further technical details
- 1.1.1
- Linux
- AKS, K8s cluster version 1.23.12

I debugged this locally and it seems like the watches in ResourceInformer are just not working at all. I never observe any events being generated. In WatcherExt `MakeStreamReaderCreator`, the code never proceeds past the await on the responseTask

**Comment by MihaZupan** [comment]
What was the last commit of this repo when you tested this?

**Comment by archonandrewhunt** [comment]
I was on the release/1.1 branch, with commit [a911a04](https://github.com/microsoft/reverse-proxy/commit/a911a041300ef259663aa46474b629b90fc82e05)

**Comment by MihaZupan** [comment]
Can you please try it using the `main` branch? The k8s logic in this repo is still experimental and doesn't ship with any specific release. Any bugs that may have been fixed will likewise not be ported to `release/1.1`.

**Comment by archonandrewhunt** [comment]
Thanks @MihaZupan, I will give it a try off of `main` and report back. For reference, we have been running the k8s controller in prod without issues, I was merely trying to update to 1.1.1 when I encountered these issues.

**Comment by archonandrewhunt** [comment]
Sorry for the slow turnaround here @MihaZupan - I was able to test this on the latest code from `main` and it does work there vs `release/1.1`. Appreciate your help!
