### ISSUE TITLE
Load balancing based on hash of request features

### ISSUE THREAD

**Issue by alnikola** [microsoft/reverse-proxy#193]
### What should we add or change to make your life better?
Consistent hashing is an algorithm distributing requests processing among a number of worker nodes based of a hash of some key present in the request without preliminary knowledge of the exact key values. There is not an explicit key-to-node mapping defined for each key, instead the range of all possible key hash values is known and each worker node is assigned to process one or more sub-ranges of these values. The same sub-range is usually assigned to more than one node for load balancing.

As an example, let's assume the key is a tenant ID (exact type is not important) with hash value range [0 - 100], then if we have 4 worker nodes A, B, C, D the load generated by tenants can be distributed among nodes as follows:
| Node | Assigned tenant ID hash ranges |
| :-------: | :-------: |
| A | [0 - 25], [75 - 100] |
| B | [25 - 50], [75 - 100] |
| C | [0 - 25], [50-75] |
| D | [25-50], [50-75] |

The proposal for the reverse proxy is to support request to destination routing defined via consistent hashing of key set somewhere on request (cookie, header, path, query parameter, etc.). The exact location should be configurable.
### Why is this important to you?
It's required for request routing in distributed systems employing consistent hashing-based load balancing.

**Comment by samsp-msft** [comment]
Needs more design to account for what happens when a server is down, or the backend list changes.

**Comment by davidfowl** [comment]
I would suggest in these types of issues we look around at our fellow reverse proxies to see what sorts of behaviors exists in the wild.

**Comment by Tratcher** [comment]
Does it matter if we implement this as a load balancing algorithm or as an affinity algorithm?

I see nginx has it listed under load balancing. That makes some sense as every request is always afinitized. We don't need the dynamic affinity middleware to establish an affinity relationship.
https://docs.nginx.com/nginx/admin-guide/load-balancer/http-load-balancer/#choosing-a-load-balancing-method

**Comment by alnikola** [comment]
HAProxy also considers it as [a load balancing method](https://www.haproxy.com/blog/haproxys-load-balancing-algorithm-for-static-content-delivery-with-varnish/), so let's treat it the same way and rename the issue.
@samsp-msft Do you agree?

**Comment by Tratcher** [comment]
This would be a good opportunity to work on the load balancer extensibility (https://github.com/microsoft/reverse-proxy/issues/106). Especially now that we have the pattern that was developed for session affinity.

**Comment by samsp-msft** [comment]
I'm not going to get hung up on what we call this issue - or whether we consider it affinity or load balancing - we should have the capability :-)

**Comment by alnikola** [comment]
Going back to the above question on how to react on a destination becoming unhealthy.

This feature looks as a mix of a pure load balancing where we aim to equalize the load across destinations and "balanced routing" where a request first gets routed based on some hash to a sub-set of destinations and then we try to evenly distribute load among them. So, I see at least two consistent-hash-based load balancing modes:

## Equal
Every time a destination gets unhealthy, the mapping from hash ranges to destinations gets completely rebuilt taking into account only healthy destinations. This will ensure an equal load among all available backend's destinations.

### Example.
The following consistent hash mapping is defined
| Destinations | Tenant ID | Load % | Cached Items |
| :-------: | :-------: | :-------: | :-------: |
| A | [1,3,5] | 25% | I-1, I-2, I-3 |
| B | [2,4,6] | 25% | I-2, I-4, I-6 |
| C | [1,3,4] | 25% | I-1, I-3, I-4 |
| D | [2,5,6] | 25% | I-2, I-5, I-6 |

If destination B gets unhealthy, the mapping gets rebuilt to equally redistribute the load among available nodes. Nodes have to fetch missing items from external storage and put them into cache.
| Destinations | Tenant ID | Load % | Cached Items |
| :-------: | :-------: | :-------: | :-------: |
| A | [6,1] | **33.33%** | I-1, I-2, I-3, I-6 |
| ~~B~~ | --- | -% | --- |
| C | [2,3] | **33.33%** | I-1, **I-2**, I-3, I-4 |
| D | [4,5] | **33.33%** | I-2, **I-4**, I-5, I-6 |

## Stable
Even if a destination gets unhealthy, the mapping doesn't change and requests matching the corresponding hash range will be handled by the remaining healthy destinations serving that range. As explained in the beginning, consistent hashing implies a redundancy in mapping hash range to nodes, thus if one node goes down others will continue serving requests in range. This scenario is useful if it's preferred to avoid moving request-related data already cached on some destinations to other nodes.

### Example.
The following consistent hash mapping is defined
| Destinations | Tenant ID | Load % | Cached Items |
| :-------: | :-------: | :-------: | :-------: |
| A | [1,3,5] | 25% | I-1, I-2, I-3 |
| B | [2,4,6] | 25% | I-2, I-4, I-6 |
| C | [1,3,4] | 25% | I-1, I-3, I-4 |
| D | [2,5,6] | 25% | I-2, I-5, I-6 |

If destination B gets unhealthy, the mapping doesn't get rebuilt completely, so all requests from tenant 4 go to C and from tenants 2,6 goes to D. The load becomes unequal, but data locality is preserved
| Destinations | Tenant ID | Load % | Cached Items |
| :-------: | :-------: | :-------: | :-------: |
| A | [1,3,5] | 25% | I-1, I-3, I-5 |
| ~~B~~ | --- | -% | --- |
| C | [1,3,4] | **41.67%** | I-1, I-3, I-4 |
| D | [2,5,6] | **58.34%** | I-2, I-5, I-6 |

**Comment by rwkarg** [comment]
Other load balancers will also have stick tables that are shared across instances (when there is more than one instance of the load balancer running) so that routing is consistent across all instances.

We should be explicit about what consistency is provided or available:
* Is it only local to each instance and another instance may end up routing a request to a different endpoint?
* Is it best effort to distribute state to other load balancer instances (how do they even know about eachother?)?
* Is it consistent across all instances at the expense of latency on establishing concensus or at the expense of availability?

**Comment by karelz** [comment]
Triage: We should wait for more feedback what exactly is needed by customers before we jump into implementing it.
Customers can today write it on their own to get unblocked.

**Comment by samsp-msft** [comment]
SOGOTP

**Comment by karelz** [comment]
Triage: Old issue, only 1 upvote so far. Closing. We can reconsider if there is more demand in future.
