### ISSUE TITLE
Add an available callback on each Websocket message 

### ISSUE THREAD

**Issue by tom-puckett** [microsoft/reverse-proxy#1931]
### What should we add or change to make your life better?

I'd appreciate an available callback so I can be aware of websocket messages sent through YARP.  I would need enough context with the callback to know whether the message is a websocket ping/pong or real application message, maybe the message opcode would be a good detail to include so the handler can better decide what it wants to do.  The message direction would be important too. It's not in my use case to receive the message payload, maybe others would value that? 

### Why is this important to you?

My proxy application connects users on demand to back end applications that live in containers.  The proxy application creates and deletes containers based on several factors, one of which is user activity.  The proxy application maintains a collection of time stamps that track the latest user activity for each container, but with back end applications that use a websocket for all activity after initialization (e.g. R-Shiny) I cannot track user activity because I have no way to know when websocket messages happen.

**Comment by Tratcher** [comment]
Related discussion: https://github.com/microsoft/reverse-proxy/issues/1929

**Comment by tom-puckett** [comment]
This would surely become apparent during implementation, but it would be necessary for the callback to identify which websocket (how to identify?) triggered it.  

That also leads me to wonder whether it would be possible to register for this callback separately on each websocket, maybe in another callback event when the websocket upgrade is completed (persistent connection begins). That could give me a way to provide a meaningful identifier of the websocket, to be passed into message callbacks, and lessen the overall performance impact if message callbacks are not requested for some connections.

**Comment by MihaZupan** [comment]
Thank you for the detailed description of the scenario.

> it would be necessary for the callback to identify which websocket (how to identify?) triggered it

Regarding identifying what websocket/user/stream/request a given event is related to, please see https://learn.microsoft.com/dotnet/fundamentals/networking/networking-telemetry, specifically the [in-process correlation](https://learn.microsoft.com/dotnet/fundamentals/networking/networking-telemetry#in-process-correlation) section.

Essentially it boils down to identifying the relevant context information before the WebSocket connection even starts and referencing it from the event callbacks (via `AsyncLocal`).

---

We do have existing telemetry for the forwarder (that WebSocket streams go through as well) that continuously gives you stats about ongoing data transfers:
https://github.com/microsoft/reverse-proxy/blob/d2e47e21798c16d9c105a4fc00cf4d93a4df0f23/src/TelemetryConsumption/Forwarder/IForwarderTelemetryConsumer.cs#L42-L51

From this, you can identify whether data is actively being transmitted. E.g. did the server send more than 100 bytes in the last minute? Then there's likely more than just ping/pongs being sent through.

Would that work for you?

---

On the other hand, we also have WebSocket-specific telemetry, but that is currently limited to a single "summary" event once the connection is closed:
https://github.com/microsoft/reverse-proxy/blob/d2e47e21798c16d9c105a4fc00cf4d93a4df0f23/src/TelemetryConsumption/WebSockets/IWebSocketsTelemetryConsumer.cs#L21

Note that the message count doesn't include control frames like ping/pong in this case.

We could consider doing something similar to what I mentioned above with the forwarder - have a periodic event that fires for each direction that also contains the current message count.

> It's not in my use case to receive the message payload, maybe others would value that?

Logging message contents is very expensive with the existing logging mechanism in place. The WebSocket telemetry component also doesn't buffer messages as they come in, so we don't even always have the whole message in memory at the same time. I would prefer not to consider that unless there's a real demonstrated need for it.

**Comment by tom-puckett** [comment]
> void IForwarderTelemetryConsumer.OnContentTransferring(DateTime timestamp, bool isRequest, long contentLength, long iops, TimeSpan readTime, TimeSpan writeTime) { }

I'll prototype this and reply again. It's possible that I could infer what I want to know from this one, though on first read it doesn't seem like the most natural fit.  I'll also need to see how it works to identity each active websocket since this is critical. How often is this callback fired, or what condition/activity triggers it, and is the answer likely to remain true in the future? 

I think new callback(s) on IWebSocketsTelemetryConsumer would be the most natural solution, especially since that might best convey clear context about each message and the corresponding websocket.

**Comment by MihaZupan** [comment]
> How often is this callback fired, or what condition/activity triggers it, and is the answer likely to remain true in the future?

Up to once every second, as long as any data is flowing through. For example if you didn't see it fire for 10 seconds, then no data was sent/received in that period.
This is unlikely to change and we would mention it as a breaking-change in release notes if we were to change it in the future.

> especially since that might best convey clear context about each message and the corresponding websocket.

Note that they wouldn't give you any more context about which websocket they are for than the `IForwarderTelemetryConsumer`. You're still expected to tie events to whatever data is relevant to you yourself via `AsyncLocal`.
