### ISSUE TITLE
Package description is missing

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#194]
https://devblogs.microsoft.com/dotnet/introducing-yarp-preview-1/#comment-6191

https://www.nuget.org/packages/Microsoft.ReverseProxy/1.0.0-preview.1.20268.2
"Package Description"

Example:
https://github.com/dotnet/aspnetcore/blob/3132e5c6cee173bc025f36b2cfa3c53161370ca1/src/Http/Http.Features/src/Microsoft.AspNetCore.Http.Features.csproj#L4

**Comment by samsp-msft** [comment]
Fix in preview 2
