### ISSUE TITLE
404 When using YARP with Blazor Server and a legacy .Net Framework application

### ISSUE THREAD

**Issue by Conbag93** [microsoft/reverse-proxy#1952]
I am attempting to use YARP to assist me in migrating my legacy .Net Framework MVC/WebForms application over to a Blazor Server application.

I am following the guide here:
https://learn.microsoft.com/en-us/aspnet/core/migration/inc/start?view=aspnetcore-7.0

Although I am using this experimental extension to assist with the migration - this just adds some references to YARP and some basic configuration between the two apps, so I believe the issue I am running into falls under the YARP umbrella.

### Describe the bug
When I launch the application, I correctly land on my Blazor Server application - I can navigate within the application and everything works as expected.
However, if I navigate to a specific page (e.g. /counter)  and refresh the browser - instead of the request being resolved by my Blazor application, it is being redirected to my legacy application and subsequently throwing a 404.

### To Reproduce

Create a new project using the default .Net Framework Web Application Template.
Create a new Blazor Server project using the default template
Follow the steps here https://learn.microsoft.com/en-us/aspnet/core/migration/inc/start?view=aspnetcore-7.0 to install the new migration assitant extension.
On the "Migrate Project" dialog, select "Existing Project" and select the Blazor Server project.

### Expected Result
Any requests that cannot be resolved by the Asp.Net Core application should be forwarded to the Asp.Net Framework application. This is how it works when the Asp.Net Core app uses core MVC.

### Actual Result
Requests to the 'root' site are correctly resolved to the Blazor Server app.
However, requesting a page directly in the address bar, e.g. /counter - will be forwarded by YARP to the .Net Framework application - likely resulting in a 404.

Perhaps this is not a bug and is a known limitation or a misconfiguration.
However, I am a new to YARP and I'm struggling to find definitive information on how I can investigate this further - or if there's anything specific to Blazor Server routing that is relevant during configuration. Searching "Blazor" in this repo doesn't return anything particularly helpful.

Any advice would be much appreciated.

**Comment by Tratcher** [comment]
The most likely case here is that Blazor and YARP are both configured with wildcard path matches and there's some ambiguity which should apply. To make YARP loose ties like this, the route Order property can be set to a larger value like 1000. 

https://github.com/microsoft/reverse-proxy/blob/7cef5f2bb4aec197c50f892aac6707496b52d52e/samples/ReverseProxy.Config.Sample/appsettings.json#L32

**Comment by Conbag93** [comment]
Thanks @Tratcher for the response.
I did notice some references to this property, but changing it didn't seem to affect anything in my case.

My appsettings.json is as follows:
```
{
  "Logging": {
    "LogLevel": {
      "Default": "Debug",
      "Microsoft.AspNetCore": "Debug"
    }
  },
  "AllowedHosts": "*",
  "ReverseProxy": {
    "Routes": {
      "fallbackRoute": {
        "ClusterId": "fallbackCluster",
        "Order": "1000",
        "Match": {
          "Path": "{**catch-all}"
        }
      }
    },
      "fallbackCluster": {
        "Destinations": {
          "fallbackApp": {
            "Address": "https://localhost:44390"
          }
        }
      }
    }
  }
}
```

And my legacy application is listening on :44390.

I have tried to make the wild-card more restrictive by adding prefixes - but this would introduce other problems with all hyperlinks, css and javascript etc. This is too big of a task to update correct manually.

When I hit the root of my application, I correctly land on Blazor, and the following is output to the debug logs:

```
Microsoft.AspNetCore.Routing.Matching.DfaMatcher: Debug: 2 candidate(s) found for the request path '/'
Microsoft.AspNetCore.Routing.Matching.DfaMatcher: Debug: Endpoint '/_Host' with route pattern '' is valid for the request path '/'
Microsoft.AspNetCore.Routing.Matching.DfaMatcher: Debug: Endpoint 'fallbackRoute' with route pattern '{**catch-all}' is valid for the request path '/'
```

When I try to directly enter the /counter page, the following is output to the debug log:
```
Microsoft.AspNetCore.Routing.Matching.DfaMatcher: Debug: 1 candidate(s) found for the request path '/counter'
Microsoft.AspNetCore.Routing.Matching.DfaMatcher: Debug: Endpoint 'fallbackRoute' with route pattern '{**catch-all}' is valid for the request path '/counter'
Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware: Debug: Request matched endpoint 'fallbackRoute'
```

So it seems to me like - outside of the 'root' of the site (which is a .cshtml file) - Asp.Net core has no awareness of my .razor files and their @page directives. 
Do I need to somehow manually register all of my individual razor components?

**Comment by Conbag93** [comment]
Thank you, I will post it there.

At the same time, I would like to gently point out that this isn't a niché use-case and it would be in everyone's interest to know the position on hosting YARP within a Blazor Server app.

**Comment by Conbag93** [comment]
In the end, I went with a different approach.

The migration extension sets things up so that the 'new' .Net Core project will act as the reverse-proxy as well as being a 'standard' new web application.

Instead of taking this approach - I made a new web-project whose sole-purpose is to run YARP.
Additionally, I added the following line to my Blazor Server project.
```
app.UsePathBase("/core");
```

This allows me to easily identify which requests I should proxy to Blazor.
All others will go to my legacy app:

```
{
  "Logging": {
    "LogLevel": {
      "Default": "Debug",
      "Microsoft.AspNetCore": "Debug"
    }
  },
  "AllowedHosts": "*",
  "ReverseProxy": {
    "Routes": {
      "BlazorRoute": {
        "ClusterId": "BlazorCluster",
        "Match": {
          "Path": "/web/{**catch-all}"
        }
      },
      "LegacyRoute": {
        "ClusterId": "LegacyCluster",
        "Match": {
          "Path": "{**catch-all}",
          "Order":  1000
        }
      }
    },
    "Clusters": {
      "LegacyCluster": {
        "Destinations": {
          "Web": {
            "Address": "https://localhost:44331"
          }
        }
      },
      "BlazorCluster": {
        "Destinations": {
          "Web": {
            "Address": "https://localhost:7027"
          }
        }
      }
    }
  }
}
```

I actually think keeping the projects separate in this way is actually way better.
