### ISSUE TITLE
Configure static External IP for Kubernetes Ingress Controller

### ISSUE THREAD

**Issue by unknownstring** [microsoft/reverse-proxy#1958]
Hi, 

I am looking into using Yarp as ingress controller and need to be able to configure the LoadBalancer IP as static. In Nginx configuration, this is done by setting 'loadBalancerIP' to the requested static IP in the Service manifest. However, this setting is ignored.

Is there a way to apply this using Yarp.Kubernetes.Controller?

Sample manifest for Nginx
```
kind: Service
apiVersion: v1
metadata:
...
...
...
spec:
  ports:
    - name: http
      protocol: TCP
...
...
...
  loadBalancerIP: 12.345.0.678
...
...
...
```

**Comment by MihaZupan** [comment]
As far as I understand, the ingress controller isn't doing anything with the `loadBalancerIP`. That is, this setting isn't specific to Nginx or YARP, instead, it's your cloud provider that looks for this field and provisions the LB. Are you using the same provider when testing this?

**Comment by unknownstring** [comment]
@MahaZupan, you're absolutely correct, thanks a lot for clearing up the responsibility part! Working as expected with new Static IP provisioned by Azure Cloud
