### ISSUE TITLE
[Question] How to manage duplicate response headers

### ISSUE THREAD

**Issue by adrian-patt** [microsoft/reverse-proxy#1971]
### Describe the bug
We have an ASP.Net Core service which uses YARP to forward requests to multiple other services. We noticed recently that our responses have duplicate response headers, where the response headers from the proxy-forwarded destination are combined with the response headers of the service hosting YARP. 

Below is an example of duplicated response-headers:

![image](https://user-images.githubusercontent.com/121127878/208751077-24923db2-b439-40b1-96fc-933a15bae0dd.png)

### To Reproduce
Have a service setup which uses YARP to forward requests to other services. Service which is hosting YARP calls `endpoints.MapReverseProxy()` in startup and has a standard route config in appsettings with routes and match paths. The reverse proxy is added in the startup with
  ```cs
   services.AddReverseProxy()
              .Load(builder.Configuration.GetSection("ReverseProxy"));
  ```

### Further technical details
I've been looking to see if anyone else has had a similar issue but can't seem to find anything. What I want to ask is what the best approach is to deal with this duplication. Is the best practice to tell the service hosting YARP to not include any response headers for reverse proxy routes? Is there some sort of response transform that allows me to merge the proxy response headers with the response headers of my service acting as the entry point? Or maybe there is something I'm missing.

Any sort of help/resources will be greatly appreciated!

**Comment by Tratcher** [comment]
How are you adding these headers in your service hosting YARP? Some middleware that automatically adds them to every response before invoking next?

There are two ways to approach this:
A) Prevent them from being added for routes that will be proxied. This would involve inspecting the matched endpoint to see if it's assigned to YARP.
B) Use a transform to filter out duplicates from the back end.
https://microsoft.github.io/reverse-proxy/articles/transforms.html#addresponsetransform

**Comment by adrian-patt** [comment]
Exactly, the headers are being added by middleware. The headers are necessary in non-yarp calls (some endpoints are not proxied but are handled by the service directly).

I tried option B, but the transform removed the headers coming from the destination service, which may have information we need (like content-type for the payload). In other words I'd like to remove the headers added by the service hosting YARP and keep only the destination response headers, but I don't know if that's possible using transforms. It seems like transforms are only for transforming responses from proxy destinations.

I think we might have to go with option A, though not so desirable. It would mean adding custom logic for proxied routes to prevent the addition of headers. It may be the best option though.

**Comment by Tratcher** [comment]
Transforms can do almost anything to the response. With the defaults, the proxy response headers are copied and appended to the AspNetCore response headers. You could scan the AspNetCore response headers in the transform and remove duplicates.

**Comment by Tratcher** [comment]
Oh, or you just have a request transform that calls Clear on the response headers before proxying. That would get rid of any default app headers.

**Comment by adrian-patt** [comment]
I will try the second option you mentioned, it seems the cleanest. How would clearing the response headers in a request transform ensure no default app headers are returned? I don't quite understand but I'll give it a go.

Thanks so much for your time and the speedy responses.

**Comment by Tratcher** [comment]
That depends on how the middleware are adding them? I assume they're being added on the way in. It's more difficult to add them later.

**Comment by adrian-patt** [comment]
Alright I will try to remove them in the request transform. I'll close the issue for now since it's more of a question/behavior, I'll add my solution later on once I've figured it out (in case anyone else finds the same behavior in the future). 

Thanks again!

**Comment by adrian-patt** [comment]
> Oh, or you just have a request transform that calls Clear on the response headers before proxying. That would get rid of any default app headers.

This solved my issue. I did the following transform:
```cs
services.AddReverseProxy()
    .AddTransforms((context) =>
    {
        context.AddRequestTransform(async requestContext =>
        {
            requestContext.HttpContext.Response.Headers.Clear();
            await Task.FromResult(requestContext);
        });
    });
```
And my issue was solved, only the destination response headers were included.

**Comment by Tratcher** [comment]
```
        context.AddRequestTransform(requestContext =>
        {
            requestContext.HttpContext.Response.Headers.Clear();
            return default;
        });
```

**Comment by msamwill** [comment]
Have the same issue but I'm using a HttpForwarder.  It does not appear to have the AddRequestTransform option.  Is there another way to clear the response headers?

**Comment by MihaZupan** [comment]
If you are already using the forwarder directly, you also have access to the `HttpContext`, so you can use that directly `httpContext.Response.Headers.Clear();`.
You also have control over the `HttpTransformer` used, and you can add extra logic there (see `CustomTransformer` in [direct forwarding docs](https://microsoft.github.io/reverse-proxy/articles/direct-forwarding.html)).

If you are running into more problems, please open a new issue.

**Comment by msamwill** [comment]
That works.  Thank you!
________________________________
From: Miha Zupan ***@***.***>
Sent: Friday, September 1, 2023 9:44 AM
To: microsoft/reverse-proxy ***@***.***>
Cc: Williams, Anna ***@***.***>; Comment ***@***.***>
Subject: [EXTERNAL]: Re: [microsoft/reverse-proxy] [Question] How to manage duplicate response headers (Issue #1971)


If you are already using the forwarder directly, you also have access to the HttpContext, so you can use that directly httpContext.Response.Headers.Clear();.
You also have control over the HttpTransformer used, and you can add extra logic there (see CustomTransformer in direct forwarding docs<https://urldefense.proofpoint.com/v2/url?u=https-3A__microsoft.github.io_reverse-2Dproxy_articles_direct-2Dforwarding.html&d=DwMCaQ&c=j9YNQVTYIohH8cYE_3mLmw&r=PaO4_Cax22BUWnXzINx4sDIBHr4tHn5X2SQTEimO2dw&m=WDihOBuIpcmF1lWgRqNoy34jg0XxrcQnkH8amJqq6pfPGPMSce5PE5YYa9_ScOZp&s=Pkgi3JC1p0Vu8CHLsAoVGy-ZERLwtzeYuYQ5OqmTCg0&e=>).

If you are running into more problems, please open a new issue.

**Comment by msamwill** [comment]
Removing headers with httpContext.Response.Headers works as shown below.  However, after clearing my browser cache I'm getting net::ERR_HTTP2_PROTOCOL_ERROR 200 on all resources using the proxy.  

app.UseEndpoints(endpoints =>
{
    endpoints.Map("/proxy.ashx/{**catch-all}", async (HttpContext httpContext, IHttpForwarder forwarder) =>
    {
        var error = await forwarder.SendAsync(httpContext, "targetUrl", httpClient, requestOptions,
        static (context, proxyRequest) =>
        {
            var targetUrl = context.Request.QueryString.HasValue ? context.Request.QueryString.Value.Substring(1) : context.Request.GetEncodedUrl();
            proxyRequest.RequestUri = new System.Uri(targetUrl);
            proxyRequest.Headers.Host = null;
            return default;
        });

        // Check if the proxy operation was successful
        if (error != ForwarderError.None)
        {
            var errorFeature = httpContext.Features.Get<IForwarderErrorFeature>();
            var exception = errorFeature.Exception;
        }

        //Remove headers added by Proxy
        //httpContext.Response.Headers.Remove(HeaderNames.CacheControl);
        //httpContext.Response.Headers.Remove(HeaderNames.XPoweredBy);
        //httpContext.Response.Headers.Remove(HeaderNames.XXSSProtection);
        //httpContext.Response.Headers.Remove(HeaderNames.XContentTypeOptions);
        //httpContext.Response.Headers.Remove(HeaderNames.StrictTransportSecurity);
        //httpContext.Response.Headers.Remove("X-AspNet-Version");
    });
});
