### ISSUE TITLE
ISessionAffinityPolicy should be async

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#1974]
### What should we add or change to make your life better?

FindAffinitizedDestinations and AffinitizeResponse could use async overloads to allow for external data store affinity lookups, or other operations like checking the body. These could be added in a non-breaking way as Default Interface Methods that call the sync APIs.

### Why is this important to you?

Example: David had to read the response body to get an identifier. He was also unable to use IDistributedCache.
https://github.com/davidfowl/SmartLoadBalancer/blob/1d43229daf09f836aabf7a78ce31658a207cf53b/Yarp.Ingress/SignalRSessionAffinity.cs

**Comment by karelz** [comment]
Triage: Reasonable thing to do, given it can be done in non-breaking way.

**Comment by davidfowl** [comment]
So I was finally able to try this out and hit a problem. It seems like I need to use the SuppressBody on the ResponseTransformContext, but that isn't accessible in AffinitizeResponseAsync (I'm trying to write a response to affinitize the signalr connection).
