### ISSUE TITLE
Unhealthy destination log should be set at least a Warn level.

### ISSUE THREAD

**Issue by NZE** [microsoft/reverse-proxy#1976]
Log level when Unhealthy destination detected is Information at the moment which can be easily ignored in our seq logs. 
Can we change it to a Warn level or enable us to set the log level as we wish? 

```c#
private static readonly Action<ILogger, string, TimeSpan, Exception?> _unhealthyDestinationIsScheduledForReactivation = LoggerMessage.Define<string, TimeSpan>(
            LogLevel.Information,
            EventIds.UnhealthyDestinationIsScheduledForReactivation,
            "Destination `{destinationId}` marked as 'Unhealthy` by the passive
            health check is scheduled for a reactivation in `{reactivationPeriod}`.");

```

Thanks

**Comment by Tratcher** [comment]
This was an intentional choice at the time, but we can re-visit it.

The theory is that a destination's health state change is routine and doesn't directly reflect on the proxy's function. We only want errors logged when the proxy's own components fail. Warn could be a compromise, that's a level we don't use much.

**Comment by karelz** [comment]
Triage: It is not Error state - it is not sign of YARP misconfiguration, or something bad happening.
We are ok with something in between Information and Error. Warn is the only option there.

**Comment by MihaZupan** [comment]
What's more, the `ActiveDestinationHealthStateIsSetToUnhealthy` event which is the active counterpart to `UnhealthyDestinationIsScheduledForReactivation` is already set to warning. Makes sense to match both.
