### ISSUE TITLE
Affinity is broken with multiple YARP instances 

### ISSUE THREAD

**Issue by eyalg-msft** [microsoft/reverse-proxy#1980]
### Describe the bug
Affinity is not working in YARP. When you have more than one YARP instance each YARP produces different hash values for the same destination machines. When the affinity is being resolved on a different YARP instance it fails. Hence Affinity is broken in YARP.

### To Reproduce
- Use 2 or more YARP instances, with 2 or more destinations in a cluster. 
- Define cookie affinity. 
- try to get to a single destination machine using the YARP produced cookie
- the affinity resolution is failing when reaching the YARP instance who did not create the affinity cookie.

### Further technical details
- The issue root source is that YARP is using data protection. 
- When data protection not configured. The default behavior will be to create a different key per YARP instance.
- The workaround is to define data protection with either no hashing, or with a distributed key across YARP instances
- This adds unnecessary dependency on the key storage place to allow affinity to work.

### Suggested fix
- Provide a default SHA256 one-way hashing for YARP
- Affinity will work out of the box across YARP instances
- Destinations names are protected
- No dependency on distributed cache and no need to define data protection manually.
- Still allows YARP users to use DI to replace the data protection algorithm if needed.

**Comment by Tratcher** [comment]
Context from other discussions:

Session affinity relies on DataProtection to encrypt the cookie. When running more than one instance, you must share the DataProtection keys across instances.
https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/web-farm?view=aspnetcore-7.0#required-configuration

https://github.com/microsoft/reverse-proxy/issues/1981 Covers adding this to the docs.

FYI this is the standard design for protected cookies in AspNetCore (Auth cookies, session cookies, anti-forgery, etc.)

**Comment by eyalg-msft** [comment]
As discussed on the question thread, this is a design decision which sounds right level pf protection for authentication, but not for affinity IMO. ARR solution for example is not dependent on an external shared caching or storage. However, it still hides the destination perfectly. It does not make sense to claim that YARP supports affinity, but only for one instance, and if you want more without adding dependencies then you have to pretty much ignore YARP affinity and write it yourself using a one -way hash, which is what we did.

I do believe we can do better. we can provide this affinity functionality out of the box without compromising security, and at least be on par with older solutions like ARR. Currently the affinity is broken out of the box for more than one instance, and the workaround is painful design wise. In our product it was not acceptable.

**Comment by MihaZupan** [comment]
Note that a "one-way hash" does not provide the same security characteristics though.
These hashes can be brute-forced, and you also leak information about the topology (e.g. were different requests served by the same destination, how many different destinations are there).

You may not care about that (perfectly valid), but it's something that shouldn't be overlooked.

**Comment by eyalg-msft** [comment]
You leak the same information with a shared key as well, the only question is for how long, since you have an expiration date on the key. by default, which is the current behavior its 3 months. I would argue that that's the same level of security, at least within 3 months. There are solutions to make it more secure without a shared key, but as I mentioned I don't think that it's a requirement for affinity. At least we know it's not a requirement for IIS ARR. And in internal design meeting it's not for our product as well.

**Comment by MihaZupan** [comment]
> You leak the same information with a shared key as well

The key here is shared only between instances of YARP that you control, it's not visible to the client.
To the client, the cookie value is opaque garbage data that you can't obtain any information from.

**Comment by eyalg-msft** [comment]
Oh ok, I see. I thought that for the same destination the resulted hash would be the same using the same key. If this is the case, then it's the same as one-way hash. if it's not then I misunderstood. sorry. 

Anyway, it's not something I think we should decide. we should allow by default a working affinity without dependencies, and we can allow a stricter approach for whoever needs it. I suspect most will not alter the default behavior if it will work out of the box with SHA256 one-way hash.

**Comment by Tratcher** [comment]
Note that the current design doesn't use a one-way hash, it decrypts the value on return and uses that to find the destination by name. Using one-way hashes would require computing/storing the hash for every possible destination.

**Comment by eyalg-msft** [comment]
The fact is that currently it is broken out if the box by design. IIS and ARR is working well out of the box. Inside Microsoft many migrate  from iis and ARR. The use of data protection for cookies is somewhere between over engineering to wrong since it breaks the affinity and force yarp users to align with this design decision and create new dependency on some shared cache. I still think that the leakage is the same, but anyway even if its not, it's a degree of security which does not exists in current ARR solution. For our purposes it's an overkill. I would.highky encourage us as Microsoft to at least provide a solution that will work out of the box same as the ARR does. Anyway let's document the choices and allow data protection for those who might want it, I doubt how many will use it for cookie affinity. Regarding memory consumption it should be very small, and you can always argue for cpu usage and increased latancy with encryption decryption. Still both of them probably are neglectible. Yet I would prefer to use memory and gain every millisecond of latency that impact users directly.

Thanks,
Eyal.
________________________________
מאת: Chris Ross ***@***.***>
‏‏נשלח: Thursday, December 29, 2022 7:07:18 PM
‏‏אל: microsoft/reverse-proxy ***@***.***>
עותק: Eyal Gaber ***@***.***>; Author ***@***.***>
‏‏נושא: Re: [microsoft/reverse-proxy] Affinity is broken with multiple YARP instances (Issue #1980)


Note that the current design doesn't use a one-way hash, it decrypts the value on return and uses that to find the destination by name. Using one-way hashes would require computing/storing the hash for every possible destination.

**Comment by davidfowl** [comment]
This seems like a reasonable default for YARP. Some notes from a discussion:

- We can default to a one-way hash, SHA256 seems like a reasonable default. The cookie would store `Hex(Sha256(destination.Id))`.
- The cookie session affinity policy will support the existing dataprotection based format, but will write cookies in this new format. This should alleviate updates where older and newer versions of YARP are deployed at the same time.

Sample implementation:

```C#
public sealed class HashbasedCookieSessionAffinityPolicy :  ISessionAffinityPolicy
{
    private readonly ConditionalWeakTable<DestinationState, string> _hashes = new();
    private static readonly object AffinityKeyId = new();

    public string Name => SessionAffinityConstants.Policies.Cookie;

    public void AffinitizeResponse(HttpContext context, ClusterState cluster, SessionAffinityConfig config, DestinationState destination)
    {
        if (!config.Enabled.GetValueOrDefault())
        {
            throw new InvalidOperationException($"Session affinity is disabled for cluster.");
        }

        // Affinity key is set on the response only if it's a new affinity.
        if (!context.Items.ContainsKey(AffinityKeyId))
        {
            var affinityKey = GetDestinationHash(destination);

            // Nothing is written to the response
            var affinityCookieOptions = new CookieOptions
            {
                Path = config.Cookie?.Path ?? "/",
                SameSite = config.Cookie?.SameSite ?? SameSiteMode.Unspecified,
                HttpOnly = config.Cookie?.HttpOnly ?? true,
                MaxAge = config.Cookie?.MaxAge,
                Domain = config.Cookie?.Domain,
                IsEssential = config.Cookie?.IsEssential ?? false,
                Secure = config.Cookie?.SecurePolicy == CookieSecurePolicy.Always || (config.Cookie?.SecurePolicy == CookieSecurePolicy.SameAsRequest && context.Request.IsHttps),
                Expires = config.Cookie?.Expiration is not null ? DateTimeOffset.UtcNow.Add(config.Cookie.Expiration.Value) : default(DateTimeOffset?),
            };

            context.Response.Cookies.Append(config.AffinityKeyName, affinityKey, affinityCookieOptions);
        }
    }


    public AffinityResult FindAffinitizedDestinations(HttpContext context, ClusterState cluster, SessionAffinityConfig config, IReadOnlyList<DestinationState> destinations)
    {
        string? affinityHash = context.Request.Cookies[config.AffinityKeyName];
        if (affinityHash is not null)
        {
            foreach (var d in destinations)
            {
                var hashValue = GetDestinationHash(d);

                if (affinityHash == hashValue)
                {
                    context.Items[AffinityKeyId] = affinityHash;
                    return new(d, AffinityStatus.OK);
                }
            }

            return new(null, AffinityStatus.DestinationNotFound);
        }

        return new(null, AffinityStatus.AffinityKeyNotSet);
    }

    private string GetDestinationHash(DestinationState d)
    {
        return _hashes.GetValue(d, static d =>
        {
            var destinationIdBytes = Encoding.UTF8.GetBytes(d.DestinationId.ToUpperInvariant());
            var hashBytes = SHA256.HashData(destinationIdBytes);
            return Convert.ToHexString(hashBytes);
        });
    }
}
```

**Comment by eyalg-msft** [comment]
thanks @davidfowl, this is great. I have validated it locally and it's working as expected.

**Comment by blowdart** [comment]
With a limited set of sha is not a protection, especially a sha without a salt which would be needed here. 

It does meet your requirement of "Destinations names are protected"

**Comment by Tratcher** [comment]
Update:
- This customer does not consider the destination id as secret data, they even return it in plain text in other headers sometimes.
- ARR uses the host name in the affinity cookie, using the same hash as described above.
- We're ok making this breaking change to hash by default. Document the breaking change and the guarantees (or lack there of) for hashes.
- Keep the data protection implementation as a named alternative
