### ISSUE TITLE
Is there any posibility to exclude specific endpoint?

### ISSUE THREAD

**Issue by ahmedtolba1984** [microsoft/reverse-proxy#1983]
Dears,
I have a local endpoint that I need to skip and won't Yarp to totally ignore it.
Is there any possibility to achieve that?

**Comment by Tratcher** [comment]
How have you configured YARP? And how have you configured the local endpoint? The local endpoint should win by default so long as it is a more specific match.

**Comment by ahmedtolba1984** [comment]
@Tratcher 
I just need to skip these local endpoints and by the way, I solved it using app.Map("local endpoints") so, Yarp isn't totally aware of these endpoints
I just wanted to ask if there is a setting or something similar

**Comment by karelz** [comment]
Seems to be solved. Closing.
