### ISSUE TITLE
How to monitor for errors?

### ISSUE THREAD

**Issue by rosrosros** [microsoft/reverse-proxy#1996]
### Some details

**How many backends are in your application?**

- [x] 1-2
- [ ] 3-5
- [ ] 6-10
- [ ] 10+

**How do you host your application?**

- [ ] Kubernetes
- [ ] Azure App Service
- [ ] Azure VMs
- [ ] Other Cloud Provider (please include details below)
- [x] Other Hosting model (please include details below)
Hosted on windows box

### What did you think of YARP?

I have a reverse proxy setup where YARP fronts an IIS web site.
YARP is setup to log to Windows Event Log:

```
Config file:

{
  "Logging": {
    "EventLog": {
      "LogLevel": {
        "Default": "Information" // information is required to log all the relevant errors
      }
    }
  },
```

```
Program.cs:

builder.Services.Configure<EventLogSettings>(config =>
{
    config.LogName = "Yarp";
    config.SourceName = "Yarp";
});
```

All is well apart from the GB's of log data YARP generates because of the log level "information"
All I really wanna know is when YARP throws exceptions like this one:
```

System.InvalidOperationException: Invalid non-ASCII or control character in header: 0x0009
    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ThrowInvalidHeaderCharacter(Char ch)
```

For now I can only find then in Event Viewer by filtering on EventID = 48

?? How do I monitor for exceptions without logging so much data??

**Comment by Tratcher** [comment]
Try this: https://microsoft.github.io/reverse-proxy/articles/middleware.html#error-handling

**Comment by adityamandaleeka** [comment]
Looks like this has been answered. Closing the issue.

**Comment by rosrosros** [comment]
Yes - it was a great suggestion that solved my issue
