### ISSUE TITLE
Blazor Site Links are not rewritten to new PathBase

### ISSUE THREAD

**Issue by Mr-Pearce** [microsoft/reverse-proxy#2010]
I have a Blazor Server app(client) and a Yarp server app(proxy) the proxy dynamical sets up the routings for multiple services via rest api calls.

My yarp code is using 
```
var clusterId = $"{request.RouteFor}_cluster";
var route = new RouteConfig()
{
    RouteId = $"{request.RouteFor}_route",
    ClusterId = clusterId,
    Match = new RouteMatch
    {
        Path = request.Route + "/{**catch-all}"
    }
}
.WithTransformPathRemovePrefix(new PathString(request.Route))
.WithTransformRequestHeader("X-Forwarded-PathBase", request.Route, true);


var cluster = new ClusterConfig()
{
    ClusterId = clusterId,
    Destinations = new Dictionary<string, DestinationConfig>(StringComparer.OrdinalIgnoreCase)
        {
            { $"{request.RouteFor}_destination", new DestinationConfig() { Address = request.Destination } }
        }
};
```
which should should config wise look like example this:
```
{
  "ReverseProxy": {
    "Routes": {
      "Route1": {
        "ClusterId": "Cluster_01",
        "Match": {
           "Path": "/api1/{**catch-all}"
        },
        "Transforms": [
          { "PathRemovePrefix": "/api1" },
          {
            "RequestHeader": "X-Forwarded-PathBase",
            "Set": "/api1"
          }
        ]
      }
    },
    "Clusters": {
      "Cluster_01": {
        "Destinations": {
          "newDestination": {
            "Address": "http://x.x.x.x:6001/"
          }
        }
      }
    }
  }
}
```

my Blazor Side client uses.
```
app.Use(async (context, next) =>
{
    if (context.Request.Headers.TryGetValue("X-Forwarded-PathBase", out var pathBase))
    {
        context.Request.PathBase = pathBase.Last();
        if (context.Request.Path.StartsWithSegments(context.Request.PathBase, out var path))
        {
            context.Request.Path = path;
        }
    }
    await next();
});
```

I can reach the client site via the proxy address `https://localhost:5001/api1`, the PathBase is set correctly and css, javascript and so on is loaded properly.
Even the SignalR connection is working.

The Problem is that all Links on the blazor site are leading to 
`https://localhost:5001/link1` instead of
`https://localhost:5001/api1/link1`

Is there a way to fix this with headers or do i need to rewrite the result body?

**Comment by adityamandaleeka** [comment]
Can you show us what your link generation code looks like?

**Comment by Tratcher** [comment]
Unrelated, but you're double trimming the request path.
`{ "PathRemovePrefix": "/api1" },`
and
```
        if (context.Request.Path.StartsWithSegments(context.Request.PathBase, out var path))
        {
            context.Request.Path = path;
        }
```
You only need one or the other.

If you sent a request like `/api1/api1/foo` you'd get `/foo`.

**Comment by Mr-Pearce** [comment]
> Can you show us what your link generation code looks like?

There is no special code.
Just a Navbar with some  hrefs like
```
<a href="/">Home</a>
<a href="/api1">Api 1</a>
```

**Comment by Tratcher** [comment]
But what's generating `https://localhost:5001/link1`? That doesn't seem to be a YARP issue, that's the link generator not including PathBase.

**Comment by Mr-Pearce** [comment]
I found the error.
using this 
```
<a href="">Home</a>
<a href="api1">Api 1</a>
```
instead of
```
<a href="/">Home</a>
<a href="/api1">Api 1</a>
```
was the solution.
