### ISSUE TITLE
Response header not removed?

### ISSUE THREAD

**Issue by jbonnett92** [microsoft/reverse-proxy#2028]
I have this config:
```json
{
    "routeId": "identity-http-api-service-routes",
    "match": {
        "methods": null,
        "hosts": null,
        "path": "/api/identity/{**catchall}",
        "queryParameters": null,
        "headers": null
    },
    "order": null,
    "clusterId": "identity-http-api-service",
    "authorizationPolicy": null,
    "corsPolicy": null,
    "metadata": null,
    "transforms": [
        {
            "ResponseHeaderRemove": "Server",
            "When": "Always"
        }
    ]
},
```

Notice that I have added the transform for removing the server header, yet I still get the header returned in the browser:
<img width="1440" alt="Screenshot 2023-02-09 at 16 17 05" src="https://user-images.githubusercontent.com/3740700/217871514-01281b3b-8034-4e23-a0f0-17d9d3033fbf.png">

Any ideas why this is?

**Comment by MihaZupan** [comment]
Kestrel will always set the Server header on the response.
If you want to disable that, you can toggle the `AddServerHeader` option in `UseKestrel`.
```c#
builder.WebHost.UseKestrel(options =>
{
    options.AddServerHeader = false;
});
```

**Comment by jbonnett92** [comment]
Hi @MihaZupan, 
I'm not explicitily using Kestral, the server is set using the environment that is it hosted in.

**Comment by jbonnett92** [comment]
Turns out I was adding it in the wrong project :(
