### ISSUE TITLE
Hope this is a General Reverse Proxy

### ISSUE THREAD

**Issue by reader-man** [microsoft/reverse-proxy#203]
Hi,
 Nice to see .net core has its own reverse proxy, but i hope that this will be a general one, that can run by its own on .net core, and can be used to proxy any other engines as if its an nginx alternative, but hope it will be much faster as asp.net core is faster that other tech.

Regards.

**Comment by tbonham** [comment]
I’m hoping for the same.

**Comment by Tratcher** [comment]
Yes, that's the plan.

**Comment by samsp-msft** [comment]
YARP will not care about what platform the destination sites/services use. While a major scenario is enabling extensibility using .NET, we are also having internal discussions about what features a pre-built YARP proxy would include.
