### ISSUE TITLE
Passive Health Check Path Configuration

### ISSUE THREAD

**Issue by say25** [microsoft/reverse-proxy#2032]
### Why is this important to you?

I would love to be able to configure the route for passive health checks. In our use case, the passive health check to our destination is more of a destination status and less of a should our application respond to requests or not.

Maybe my understanding of the way Yarp Health checks work is flawed but we want to configure an application load balancer health check at /health and expose the passive health check at something like /destination-status

**Comment by Tratcher** [comment]
I think there's some confusion about what YARP's passive health checks are for. They do not initiate their own requests like active health checks. Instead they monitor normal traffic for unexpected results (e.g. connection failures, 5xx's, etc.) to decide if a destination is healthy or not.

It sounds like what you want is more of a status aggregator for reporting purposes?

**Comment by karelz** [comment]
Triage: Seems to be answered. Closing. Let us know if we missed anything.

**Comment by say25** [comment]
Yea that’s pretty much correct. We worked around this by moving our health route to /live
