### ISSUE TITLE
How to make YARP understand DevExpress DataSourceLoadOptions class?

### ISSUE THREAD

**Issue by duyan11110** [microsoft/reverse-proxy#2047]
I use YARP as an API gateway and DevExpress for ASP.net Core for UI in my microservice solution.

UI code (port 7004)
```C#
gItems.AddSimpleFor(c => c.CustomerID).ColSpan(2)
                .Label(l => l.Text(@L["utim_form_CustomerAbbr"]).ShowColon(false))
                .Editor(e => e.SelectBox()
                    .DataSource(d => d.RemoteController()
                        .LoadUrl("/api/customer-service/customer/basic-list")
                        .Key("customerID")
                    )
                    .DataSourceOptions(c => c.Paginate(true).PageSize(10))                    
                    .ID("sb_customer")
                    .SearchEnabled(true)
                    .OnValueChanged("onChangedCustomerAbbr")
                    .ElementAttr("customerName", "customerName")
                    .DisplayExpr("customerAbbr")
                    .ValueExpr("customerID")
                    .ShowClearButton(true)
                );
```

Back-end code (port 7006)
```C#
public async Task<LoadResult> GetBasicListAsync(DataSourceLoadOptions loadOptions)
        {
            int companyId = 1;
            var customers = await _customerRepository.GetQueryableAsync();
            var query = (from c in customers
                         where c.CompanyID == companyId
                        select new
                        {
                            c.CustomerID,
                            c.CustomerAbbr,
                            c.CustomerName,
                            c.Address
                        });

            return await DataSourceLoader.LoadAsync(query, loadOptions);
        }
```

DataSourceLoadOptions properties:
```JSON
{
  "requireTotalCount": true,
  "requireGroupCount": true,
  "isCountQuery": true,
  "isSummaryQuery": true,
  "skip": 0,
  "take": 0,
  "sort": [
    {
      "selector": "string",
      "desc": true
    }
  ],
  "group": [
    {
      "selector": "string",
      "desc": true,
      "groupInterval": "string",
      "isExpanded": true
    }
  ],
  "filter": [
    "string"
  ],
  "totalSummary": [
    {
      "selector": "string",
      "summaryType": "string"
    }
  ],
  "groupSummary": [
    {
      "selector": "string",
      "summaryType": "string"
    }
  ],
  "select": [
    "string"
  ],
  "preSelect": [
    "string"
  ],
  "remoteSelect": true,
  "remoteGrouping": true,
  "expandLinqSumType": true,
  "primaryKey": [
    "string"
  ],
  "defaultSort": "string",
  "stringToLower": true,
  "paginateViaPrimaryKey": true,
  "sortByPrimaryKey": true,
  "allowAsyncOverSync": true
}
```

YARP config (port 7500)
```JSON
{
  "ReverseProxy": {
    "Routes": {
      "Customer Service": {
        "ClusterId": "customerCluster",
        "Match": {
          "Path": "/api/customer-service/{**everything}"
        }
      }
    },
    "Clusters": {
      "customerCluster": {
        "Destinations": {
          "destination1": {
            "Address": "https://localhost:7006"
          }
        }
      }
    }
  }
}
```

When running my solution, in Chrome Developer tool, I see client sent correct request like this: `https://localhost:7004/api/customer-service/customer/basic-list?skip=0&take=10` but on the gateway, it only received this url:

```
2023-02-17 16:36:07.006 +07:00 [INF] Request starting HTTP/1.1 GET https://localhost:7500/api/customer-service/customer/basic-list?api-version=1.0 - -
2023-02-17 16:36:07.007 +07:00 [INF] Executing endpoint 'Customer Service'
2023-02-17 16:36:07.007 +07:00 [INF] Proxying to https://localhost:7006/api/customer-service/customer/basic-list?api-version=1.0 HTTP/2 RequestVersionOrLower no-streaming
2023-02-17 16:36:07.043 +07:00 [INF] Received HTTP/2.0 response 200.
```

As you can see, the part of `skip=0&take=10` was removed. How can I keep those parameters?
Thank you.

**Comment by Tratcher** [comment]
> Request starting HTTP/1.1 GET https://localhost:7500/api/customer-service/customer/basic-list?api-version=1.0

That's what the proxy received, there's no modification in our control before that. I suspect there were multiple requests and you're comparing the wrong ones, or there was an issue on the client.

**Comment by duyan11110** [comment]
Hi @Tratcher,
Thanks for your comment, but I'm sure, I didn't compare wrongly. I asked DevExpress the same question here: https://supportcenter.devexpress.com/ticket/details/t1148907/yarp-api-gateway-not-recognized-datasourceloadoptions-class and they answered this issue may relate to model binder. I've tried some other methods like this:
```
public async Task<LoadResult> GetSomethingAsync(string value, DataSourceLoadOptions loadOptions)
```
The proxy can pass `value` parameter, but not for all properties of DataSourceLoadOptions class. When I try to change my code like this:
```
public async Task<LoadResult> GetBasicListAsync(int skip, int take)
```
it works fine (pls note: `skip` and `take` are two of DataSourceLoadOptions properties.

So, pls help to check again.

**Comment by Tratcher** [comment]
I don't follow, YARP isn't involved in any model binding. Can you share a more complete example app so we can see how things tie together?

**Comment by duyan11110** [comment]
To reproduce, pls see here: https://github.com/duyan11110/MicroserviceSample
Steps:
1. Open Sample.sln, add DevExpress nuget packages and make sure to build successfully
2. Change connection string in all appsettings.json files
3. In shared folder, run Sample.DbMigrator **twice**
4. Pull RabbitMq and Redis and run following commands:
docker run -it --rm --name localhost -p 5672:5672 -p 15672:15672 rabbitmq:latest
docker run -it --rm --name redislocal -p 6379:6379 redis:latest
5. Open terminal in root folder and run: tye run --watch
6. View tye dashboard at: http://localhost:8000
7. Open UI at: http://localhost:7004
8. Login with this account: admin/1q2w3E*
9. Open Develop Tool on Chrome/Firefox/...
10. Click on Menu:Test1 -> UTI -> UTI Maintenance by Ct Party menu, in Network tab, you will see this API: `http://localhost:7004/api/test1-service/u-tIMaintenance-by-ct-party?skip=0&take=100&requireTotalCount=true&value=%7B%22InputDateFrom%22%3A%222023-02-28%22%2C%22InputDateTo%22%3A%222023-02-28%22%7D&_=1677576922079`, but check on the gateway:
```
[gateway_2e90f858-3]: [16:35:25 INF] Request starting HTTP/1.1 GET http://localhost:7500/api/test1-service/u-tIMaintenance-by-ct-party?value=%7B%22InputDateFrom%22%3A%222023-02-28%22%2C%22InputDateTo%22%3A%222023-02-28%22%7D&api-version=1.0 - -
[gateway_2e90f858-3]: [16:35:25 INF] Executing endpoint 'Test1 Service'
[gateway_2e90f858-3]: [16:35:25 INF] Proxying to http://localhost:7005/api/test1-service/u-tIMaintenance-by-ct-party?value=%7B%22InputDateFrom%22%3A%222023-02-28%22%2C%22InputDateTo%22%3A%222023-02-28%22%7D&api-version=1.0 HTTP/2 RequestVersionOrLower no-streaming
[gateway_2e90f858-3]: [16:35:27 INF] Received HTTP/1.1 response 200.
[gateway_2e90f858-3]: [16:35:27 INF] Executed endpoint 'Test1 Service'
[gateway_2e90f858-3]: [16:35:27 INF] Request finished HTTP/1.1 GET http://localhost:7500/api/test1-service/u-tIMaintenance-by-ct-party?value=%7B%22InputDateFrom%22%3A%222023-02-28%22%2C%22InputDateTo%22%3A%222023-02-28%22%7D&api-version=1.0 - - - 200 - application/json;+charset=utf-8 2422.9062ms
```
11. Click on the arrow of Customer Abbr dropdown box, you will see this API in Network tab: `http://localhost:7004/api/customer-service/customer/basic-list?skip=0&take=10&_=1677576922080`, and check the gateway again:
```
[gateway_2e90f858-3]: [16:42:00 INF] Request starting HTTP/1.1 GET http://localhost:7500/api/customer-service/customer/basic-list?api-version=1.0 - -
[gateway_2e90f858-3]: [16:42:00 INF] Executing endpoint 'Customer Service'
[gateway_2e90f858-3]: [16:42:00 INF] Proxying to http://localhost:7006/api/customer-service/customer/basic-list?api-version=1.0 HTTP/2 RequestVersionOrLower no-streaming
[gateway_2e90f858-3]: [16:42:00 INF] Received HTTP/1.1 response 200.
[gateway_2e90f858-3]: [16:42:00 INF] Executed endpoint 'Customer Service'
[gateway_2e90f858-3]: [16:42:00 INF] Request finished HTTP/1.1 GET http://localhost:7500/api/customer-service/customer/basic-list?api-version=1.0 - - - 200 - application/json;+charset=utf-8 27.0743ms
```
Highly appreciated for your investigation.

**Comment by MihaZupan** [comment]
> in Network tab, you will see this API: `http://localhost:7004/api/test1-service/u-tIMaintenance-by-ct-party?skip=0&take=100&requireTotalCount=true&value=%7B%22InputDateFrom%22%3A%222023-02-28%22%2C%22InputDateTo%22%3A%222023-02-28%22%7D&_=1677576922079`

> but check on the gateway `[gateway_2e90f858-3]: [16:35:25 INF] Request starting HTTP/1.1 GET http://localhost:7500/api/test1-service/u-tIMaintenance-by-ct-party?value=%7B%22InputDateFrom%22%3A%222023-02-28%22%2C%22InputDateTo%22%3A%222023-02-28%22%7D&api-version=1.0 - -`

Looks like there's a thing running on `localhost:7004` that forwards that request to YARP on `localhost:7500`, but modifies it?

**Comment by karelz** [comment]
@duyan11110 your repro is rather involved. I don't think we will have time and energy to set it up.
Can you try to debug it on your side, or try to minimize the repro to something more manageable?

**Comment by MihaZupan** [comment]
@duyan11110 were you able to narrow down and simplify the repro here?

**Comment by karelz** [comment]
Triage: Not actionable repro. Closing. Feel free to reopen when you have something more actionable for us. Thanks!
