### ISSUE TITLE
How to determine the target request address according to the dynamic request

### ISSUE THREAD

**Issue by xgbzsc** [microsoft/reverse-proxy#2050]
How to determine the target request address according to the dynamic request. For example, proxy in nginx_ pass $scheme://$http_ host$request_ uri;

**Comment by MihaZupan** [comment]
Are you asking how to see the host header that the client sent to the proxy?
That information is available via `HttpContext.Request.Host` in any middleware/transform.

What are you trying to achieve? You may not have to work with these values manually.

**Comment by xgbzsc** [comment]
> Are you asking how to see the host header that the client sent to the proxy? That information is available via `HttpContext.Request.Host` in any middleware/transform.
> 
> What are you trying to achieve? You may not have to work with these values manually.

How to configure like nginx  nginx_ pass $scheme://$http_ host$request_ uri;

**Comment by Tratcher** [comment]
Something like this?
```c#
app.Map("{**catch-all}", (IHttpForwarder forwarder, HttpContext context) =>
{
  return forwarder.SendAsync(context, context.Request.GetEncodedUrl(), client);
});
```

See the direct forwarding doc for a more detailed example.
https://microsoft.github.io/reverse-proxy/articles/direct-forwarding.html#update-startup

**Comment by MihaZupan** [comment]
Triage: Closing as answered. Feel free to reopen this issue if we missed anything.
