### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by jbonnett92** [microsoft/reverse-proxy#2051]
There is a link that is broken in the documention: [https://microsoft.github.io/reverse-proxy/articles/distributed-tracing.html](https://microsoft.github.io/reverse-proxy/articles/distributed-tracing.html)

The link to the OpenTelemetry implementation: [https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/docs/trace/getting-started/README.md](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/docs/trace/getting-started/README.md)

**Comment by MihaZupan** [comment]
Should be updated to https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/trace/getting-started-aspnetcore
