### ISSUE TITLE
Passive Health-Check include client-initiated request cancellations as error condition.

### ISSUE THREAD

**Issue by Hylaean** [microsoft/reverse-proxy#2062]
### Describe the bug
Passive HealthCheck default behavior include client-initiated request abortions as error condition.
This exposes Yarp routes to switch to an unhealthy status because of flood of aborted requests, for both erroneous or malicious causes.
While requests abortions can signal an error, including them can be problematic. We've currently turned off the feature while trying to establish a way to mitigate the undesired behavior through RateLimiting.

### To Reproduce
                HealthCheck = new HealthCheckConfig
                {
                    Active = // 
                    Passive = new PassiveHealthCheckConfig
                    {
                        Enabled = true,
                        Policy = HealthCheckConstants.PassivePolicy.TransportFailureRate,
                        ReactivationPeriod = TimeSpan.FromSeconds(30),
                    },
                    AvailableDestinationsPolicy = HealthCheckConstants.AvailableDestinations.HealthyOrPanic,
                },
                Metadata = new Dictionary<string, string> 
                { 
                    { ConsecutiveFailuresHealthPolicyOptions.ThresholdMetadataName, "3" },
                    { TransportFailureRateHealthPolicyOptions.FailureRateLimitMetadataName, "0.33" },
                },

Any Client with fast request abort. In our case it was an angular app that mistakenly initiated two requests, aborting the first one.

### Further technical details

- Include the version of the packages you are using
Yarp.ReverseProxy 2.0.0
- The platform
Behavior was tested on linux (WSL2) and Windows Datacenter 2022

**Comment by MihaZupan** [comment]
I'm unable to reproduce this behavior.
Can you please share the steps you used via miha.zupan@microsoft.com?

**Comment by Hylaean** [comment]
Ok, I may have misinterpreted the issue. I'll try to provide you that.
