### ISSUE TITLE
Exception Forwarder error in /{**catch-all}: Request: Dll was not found

### ISSUE THREAD

**Issue by mikewindlake** [microsoft/reverse-proxy#2064]
### Describe the bug
This error is seen in the logs 

`Exception Forwarder error in /{**catch-all}: Request: Dll was not found.`

It seems to be related to when bad gateway errors are occurring on the connection between the application and the incoming messages from Azure gateway. The the ASP.net application continues to run but this is concerning because it's throwing in the library code and messages seem to be getting dropped.

We are looking at what the root cause of what these log messages might mean

### Further technical details

This is running the reverse-proxy 1.1 in a ASP.Net 7.0 application. running in Azure windows container, running in K8S

We are using the code approach to mapping routes

```c#
public void Configure(IApplicationBuilder app, IHttpForwarder forwarder)
{
    // Configure our own HttpMessageInvoker for outbound calls for proxy operations
    var httpClientHandler = new HttpClientHandler();
    var httpClient = new HttpMessageInvoker(httpClientHandler);

    // Setup our own request transform class
    /// ...

    app.UseRouting();
    app.UseWebSockets();
    app.UseEndpoints(endpoints =>
    {
        endpoints.Map("/{**catch-all}", async httpContext =>
        {
           ...

```

**Comment by MihaZupan** [comment]
Can you share the full exception/stack trace?
```c#
var error = forwarder.SendAsync(...);

if (error != ForwarderError.None)
{
    var errorFeature = httpContext.Features.Get<IForwarderErrorFeature>();
    var exception = errorFeature.Exception.ToString();
}
```

**Comment by mikewindlake** [comment]
It doesn't get caught there, we have a custom message there which we aren't seeing. This seems to be outside of the endpoint methods.

**Comment by mikewindlake** [comment]
Unfortunately, I didn't get the exception trace. Adding more logging

**Comment by MihaZupan** [comment]
Any luck tracking down more information here?

**Comment by mikewindlake** [comment]
I haven't, we haven't hit the same network conditions as the cloud team fixed the out of range IP addresses.  However I did determine that the exception was being thrown out of the forwarder.SendAsync and wasn't returned as an error.

**Comment by samsp-msft** [comment]
Awaiting more details

**Comment by mikewindlake** [comment]
If I can't get it reproduced soon, I'll close this.

**Comment by karelz** [comment]
Triage: Not enough info to make it actionable for us. Closing.
Feel free to reopen once you have more info available. Thanks!
