### ISSUE TITLE
Cannot build on a machine with powershell 7

### ISSUE THREAD

**Issue by DinoChiesa** [microsoft/reverse-proxy#2078]
### Describe the bug
The build command presumes that a back-version of powershell is installed. If only powershell 7 is available, the build will fail. 

### To Reproduce
On a machine that has only powershell 7 installed, run `.\eng\common\build.ps1 -restore -build`. 

```
PS C:\Users\xyz\dev\dotnet\yarp-reverse-proxy> $PSVersionTable.PSVersion

Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      3      3

PS C:\Users\xyz\dev\dotnet\yarp-reverse-proxy> .\eng\common\build.ps1 -restore -build
  Determining projects to restore...
  All projects are up-to-date for restore.
'powershell' is not recognized as an internal or external command,
operable program or batch file.
C:\Users\xyz\.nuget\packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.22426.8\tools\InstallDotNetCore.targets(15,5): error : dotnet-install failed [C:\Users\dpchi\.nuget\packages\microsoft.dotnet.ar
cade.sdk\7.0.0-beta.22426.8\tools\Tools.proj]
'powershell' is not recognized as an internal or external command,
operable program or batch file.
```
### Further technical details

- powershell 7
- Windows 10
- current main of reverse-proxy 
- SDK 7.0.104

**Comment by MihaZupan** [comment]
Is `powershell` available on your PATH? If not, can you try adding it (likely `%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\`)?

**Comment by samsp-msft** [comment]
Closing due to no-response. Please follow @MihaZupan 's instructions and reactivate if its still an problem.
