### ISSUE TITLE
ConsecutiveFailuresHealthPolicy would wrongly mark a new faulty destination as healthy, causing proxy failure.

### ISSUE THREAD

**Issue by nlyu** [microsoft/reverse-proxy#2079]
### Describe the bug

We noticed that there is a bug in `ConsecutiveFailuresHealthPolicy`: [link](https://github.com/microsoft/reverse-proxy/blob/ac99291bc8aba7b4a8aa49918be5ff2cae84d404/src/ReverseProxy/Health/ConsecutiveFailuresHealthPolicy.cs#L71)

`ConsecutiveFailuresHealthPolicy` doesn't factor in whether the current active `DestinationHealth` is Unknown before applying its regular failure count logic. This means that when a new faulty destinations are added but immediately return failures from active health probes, the policy would have a period where it mark destination as `DestinationHealth.Healthy` before it transition to` DestinationHealth.Unhealthy` based on the configured consecutive failure count.

Example if consecutive failures threshold is 2. 
When a new unreachable destination comes up:

| time | health state | Should be |
| ----------- | ----------- | ----------|
| t0 |  unknown | unknown |
| t1 |  healthy | unhealthy |
| t2 |  healthy | unhealthy |
| t3 |  unhealthy |  unhealthy |

The reason we encounter this problem is because we host service on Service Fabric Cluster. And we would do weekly deployment. Every time we have weekly deployment, we see proxy failure. Because, when new destination showing up, the service on this new destination are not reachable during the start up. But destination are marked as healthy in our gateway, due to the ConsecutiveFailuresHealthPolicy.

### Suggestion

Can we add a condition in ` EvaluateHealthState`?

If previous health state is unknown, and new health state is unhealthy, immediately return DestinationHealthState = unhealthy.

**Comment by davidni** [comment]
Slightly modified table from the issue description that might make the issue more obvious:

Assume a destination is actually unhealthy -- i.e. all probe attempts WILL deterministically fail.

time | Active probe result | Expected destination health in YARP | Actual destination health in YARP
-- | -- | -- | --
t0 (init, before any probes) | -- | unknown | unknown ✅ 
t1 | fail | unhealthy | healthy ⚠️ 
t2 | fail | unhealthy | healthy ⚠️ 
t3 | fail | unhealthy | unhealthy ✅

**Comment by MihaZupan** [comment]
Thanks for filing the issue, the current behavior does look wrong.
We might want to tweak the expected state to "`unknown`, `unknown`, `unknown`, `unhealthy`" (unknown instead of immediately unhealthy), but it should definitely not switch to healthy.

**Comment by garrettm-msft** [comment]
Extending the `unknown` period seems reasonable given the semantics of the policy and works for our destination selection purposes.

**Comment by davidni** [comment]
Once we introduce the notion of Degraded state, that may be more appropriate than `Unknown` for those initial moments -- in that case we have at least some data to indicate the destination is not healthy -- if other destinations are perceived as Healthy, we would prefer to route to those instead. Related: #2071

**Comment by karelz** [comment]
Triage: Looks like a bug we should fix.

**Comment by doboczyakos** [comment]
Any news on this bug?

**Comment by doboczyakos** [comment]
@karelz I propose the following solution until you can implement "remaining unknown":
Change
            var count = _failureCounters.GetOrCreateValue(destination);
to
            var count = _failureCounters.GetValue(destination, _ =>
            {
                var ac = new AtomicCounter();
                Enumerable.Range(0, threshold - 1).ToList().ForEach(_ => ac.Increment());
                return ac;
            });
in ReverseProxy/Health/ConsecutiveFailuresHealthPolicy.cs line 44

I think it's better to return unhealthy instead of healthy in this case. It seems unacceptable to say "it's healthy" while healthcheck says the opposite.

**Comment by doboczyakos** [comment]
It is considered as a bug since 8 months.
We must set ConsecutiveFailures to 1 (and cannot use a higher value) as a workaround.
Any news on the fix?
