### ISSUE TITLE
Consider using new TimeProvider instead of ITimer and ITimerFactory

### ISSUE THREAD

**Issue by joperezr** [microsoft/reverse-proxy#2084]
Now that TimeProvider APIs have been added to .NET 8.0, we should consider if we want to replace some internal types that are used by Yarp. For instance, we should be able to replace

https://github.com/microsoft/reverse-proxy/blob/b6f00851fc1032706c275b414244a95ef70d3a26/src/ReverseProxy/Utilities/ITimerFactory.cs#L8-L11

with The new `TimeProvider.CreateTimer` that was introduced:

https://github.com/dotnet/runtime/blob/ce4857970dff1e987a3991238c8b32e8eae3cab7/src/libraries/Common/src/System/TimeProvider.cs#L137

cc: @tarekgh @Tratcher

**Comment by MihaZupan** [comment]
Seems reasonable to replace YARP's current `IClock`/`ITimer`/`ITimerFactory` once `TimeProvider` is finalized and down-level packages ship.
Given we don't want to drag `IClock` (public API) along forever, it'd make sense to make the transition and drop `IClock` in a major version.

**Comment by Tratcher** [comment]
We'll need to come up with a transition plan for these things. Ideally there's one version where both are available, and one may be marked obsolete.
