### ISSUE TITLE
YARP removes Connection: Upgrade header from WebSocket "Switching Protocols" response

### ISSUE THREAD

**Issue by bstromquist** [microsoft/reverse-proxy#2088]
### Describe the bug
I have a Blazor App that communicates just fine with a SignalR Hub. When I use my YARP app (based on the Reverse.Proxy.Direct sample) to reverse proxy my SignalR hub the Blazor App complains that the WebSocket upgrade is missing the Connection: Upgrade header. This then causes my YARP app to error here:
```
var error = await forwarder.SendAsync(httpContext, endpoint, httpClient, requestOptions);
```
with ForwarderError.UpgradeResponseClient. I'll try to produce a minimal example while I await your response.

### To Reproduce
Reverse proxy a SignalR connection through a YARP app based on the Reverse.Proxy.Direct sample.

### Further technical details
- .NET6
- YARP 2.0.0
- Windows

**Comment by bstromquist** [comment]
Never mind - I can't reproduce it now.

**Comment by bstromquist** [comment]
As a final note, this all came about because my YARP app was attached to an IIS installation that did not have the WebSocket feature installed. It was IIS, not YARP that was stripping the response.

**Comment by rossvegas** [comment]
Hi @bstromquist did you ever make that minimal example using signalr with direct forwarding it sure would come in handy for me right now, I'm stuck with Yarp sucessfully negotiating the connection to the hub but then timing out when trying to connect with the connection Id and upgrading the connection to a websocket.

**Comment by bstromquist** [comment]
Ross,

I never did because, as I mentioned in the issue, I found that it was IIS that was causing the problem. Are you using IIS? if so, I can dig into what I did there.  I haven't been working with signalr since that issue was written but I am willing to figure go back and figure out the IIS configuration if that helps.


  *   Brian

________________________________
