### ISSUE TITLE
Will YARP support Windows Authentication for Domain Users Already Authenticated?

### ISSUE THREAD

**Issue by Octania** [microsoft/reverse-proxy#2089]
I have been attempting to implement Windows Authentication with YARP but just discovering that Windows, Negotiate, NTLM, Kerberos are not supported.

**Comment by Tratcher** [comment]
There are no plans for additional feature work to support windows auth.

You saw the possible alternatives here?
https://microsoft.github.io/reverse-proxy/articles/authn-authz.html#windows-negotiate-ntlm-kerbereos

**Comment by Octania** [comment]
Yes but what if the Authentication was implemented in Kestrel or IIS instead of the YARP routes, wont that suffice?

**Comment by Tratcher** [comment]
To be specific, you can use windows auth to identify the user in the YARP app (via IIS or Kestrel). You cannot however forward that identity to the destination using windows auth, nor can you directly use windows up to authenticate to the destination through YARP. You can forward that identity using some other custom means such as creating a JWT and adding it to the request.

**Comment by Octania** [comment]
Thanks @Tratcher
