### ISSUE TITLE
Ordinal comparer is used for configuration settings

### ISSUE THREAD

**Issue by alnikola** [microsoft/reverse-proxy#209]
### Describe the bug
StringComparer.Ordinal is used to compare configuration settings keys in different places (e.g. in [Backend.DeepClone](https://github.com/microsoft/reverse-proxy/blob/6ef667ab055efeebfe6a6ffab421b93289f881ff/src/ReverseProxy/Abstractions/BackendDiscovery/Contract/Backend.cs#L68))

It's proposed to universally change it to StringComparer.OrdinalIgnoreCase.

**Comment by Tratcher** [comment]
Reason: These keys are being pulled from the Extensions Configuration system which treats keys as OrdinalIgnoreCase. We don't have a specific need for keys to be case sensitive so they should be handled consistent with config.
