### ISSUE TITLE
X-Forwarded-Prefix header is not set

### ISSUE THREAD

**Issue by ctyar** [microsoft/reverse-proxy#2095]
### Describe the bug
These docs state that the `X-Forwarded-Prefix` header will set automatically by default, this doesn't seem to be the case.
https://github.com/microsoft/reverse-proxy/blob/ef0a8bb3620478016bcfcb0dd5dc977623615d4d/docs/docfx/articles/transforms.md#defaults
https://github.com/microsoft/reverse-proxy/blob/f26d0f1d324dd5b0bf436de7c66b016137b15049/docs/docfx/articles/header-guidelines.md#x-forwarded--forwarded

### To Reproduce
Yarp `Program.cs`
```csharp
public static void Main(string[] args)
{
    var builder = WebApplication.CreateBuilder(args);

    builder.Services.AddReverseProxy()
        .LoadFromConfig(builder.Configuration.GetSection("ReverseProxy"));

    var app = builder.Build();

    app.MapReverseProxy();

    app.Run();
}
```
Yarp config:
```json
{
  "ReverseProxy": {
    "Routes": {
      "route1": {
        "ClusterId": "cluster1",
        "Match": {
          "Path": "/api1/{**catch-all}"
        },
        "Transforms": [
          {
            "PathRemovePrefix": "/api1"
          }
        ]
      }
    },
    "Clusters": {
      "cluster1": {
        "Destinations": {
          "destination1": {
            "Address": "http://localhost:5147"
          }
        }
      }
    }
  }
}
```
And a simple ASP.NET Core app for `Api1`.

Headers in a direct call to `Api1`:
![Direct headers](https://user-images.githubusercontent.com/1432648/230715579-1fa1ed19-0877-4ffd-ab9a-46902155f7a7.png)

Headers in a call through Yarp:
![Yarp headers](https://user-images.githubusercontent.com/1432648/230715593-1715960d-a613-4790-a939-fc310feb4bde.png)

### Further technical details

- Yarp.ReverseProxy Version=2.0.0
- Windows and .NET 7

I even tried adding a `RequestHeader` transform like this but still not seeing the header in the `Api1`
```json
"Transforms": [
  {
    "PathRemovePrefix": "/api1"
  },
  {
    "RequestHeader": "X-Forwarded-Prefix",
    "Set": "/api1"
  }
]
```

**Comment by benjaminpetit** [comment]
`X-Forwarded-Prefix` only applies to `HttpRequest.PathBase`.

To make your transformer work, you need to disable the `X-Forwarded-Prefix` transformer:

``` json
{
    "X-Forwarded": "Set",
    "Prefix": "Off"
}
```

**Comment by ctyar** [comment]
@benjaminpetit I'm sorry, but I'm not sure what you mean, I tried both of these and neither worked.
```json
"Transforms": [
  {
    "PathRemovePrefix": "/api1"
  },
  {
    "X-Forwarded": "Set",
    "Prefix": "Off"
  }
]
```
```json
"Transforms": [
  {
    "X-Forwarded": "Set",
    "Prefix": "Off"
  }
]
```

**Comment by benjaminpetit** [comment]
This worked for me:
```json
        "Transforms": [
          {
            "PathRemovePrefix": "/api1"
          },
          {
            "X-Forwarded": "Set",
            "Prefix": "Off"
          },
          {
            "RequestHeader": "X-Forwarded-Prefix",
            "Set": "/api1"
          }
        ]

**Comment by ctyar** [comment]
Yes! Thank you
