### ISSUE TITLE
Windows Authentication Inconsistent Results with 401 Unauthorized.

### ISSUE THREAD

**Issue by Octania** [microsoft/reverse-proxy#2096]
I understand that YARP will not propagate Windows Authentication to the calling app and this is not what I am attempting, I am not looking to pass token around.

I am simply trying to protect a route as stated in the YARP docs.

Steps:

1. Add an Authentication policy to the specified route(s) as stated below:
https://microsoft.github.io/reverse-proxy/articles/authn-authz.html#configuration

2. For Windows Auth and IIS, I implement the following, and also, I set anonymous Auth to **Disabled** and Windows Auth to **Enabled**. Note: I am hosting in IIS.
```c#
builder.Services.AddAuthentication(NegotiateDefaults.AuthenticationScheme)
   .AddNegotiate();
   
    services.AddAuthorization(options =>
    {
        options.AddPolicy("customPolicy", policy =>
            policy.RequireAuthenticatedUser());
    });   
```
And that's it.

**Result:**
On the server running IIS, I installed PostMan  and when I make a request to YARP, the first two attempts fails but the third one passes. However, when I make a request to the proxy from another computer, it passes the first time and then fail the next. For example: If I make 3 requests it passes the first time and then fail the next two times and then passes the 5 try.

Also, it does not work in any browser. No authentication prompts nothing just persistent 401.

**Comment by Tratcher** [comment]
If you've enabled windows and disabled anonymous at the iis level then you don't need any auth code in your app, all requests to your app would have to be authenticated. Remove the auth code and try again.

**Comment by Octania** [comment]
> To be clear, you have windows auth enabled on the proxy app using YARP, and anonymous auth enabled on the app being proxied to?

Here is my the work flow:
I have a calling/intermediary app. This app has _Windows Authentication_ set to _disabled_ and _Anonymous Authentication_ set to _Enabled_ .

This app calls the proxy endpoints/routes.
The Proxy has _Windows Authentication_ set to _Enabled_ and _Anonymous Authentication_ set to _Disabled.
If I turned on Windows auth on the Proxy and enable Anonymous auth, everything works.

Note: The proxy passes calls to a backend API with uses JWT. So the app being proxied to uses JWT Auth Scheme.

But regardless of the backend Auth Scheme, this should work.

Frontend App (No Auth/Anonymous Auth)
Proxy/YARP (Windows Auth)
Backend API/Proxied App (JWT Auth Scheme)

**Comment by Octania** [comment]
> Ok, that's the setup I'd expect. One more thing to clarify: 401.2 is an IIS error, but which instance is it coming from? Is it the proxy instance, or the backend instance? You should be able to check in the IIS logs, and the YARP logs.

There seem to be a disconnect between the Proxy and IIS.
These calls are not reaching the Proxy and based on the IIS Failed Request Tracing I have the following entry:

`<failedRequest url="SomeURL"
               siteId="3"
               appPoolId="SomePool"
               processId="SomeId"
               verb="POST"
               authenticationType="NOT_AVAILABLE"          
               failureReason="STATUS_CODE"
               statusCode="401.1"
               triggerStatusCode="401.2"
               timeTaken="0"
               xmlns:freb="http://schemas.microsoft.com/win/2006/06/iis/freb"
               >`

**Comment by Tratcher** [comment]
If calls aren't even reaching the proxy then let's remove it from the repro. Make a hello-world AspNetCore app with your windows auth setup and see if you can get that working.

**Comment by UltraDever** [comment]
> @Octania did you get a chance to look at your IIS setup if it is working properly? Per above, it does not seem to be YARP problem.

You are correct and I wanted to come back and respond in-case someone else has this issue.
In this case, the issue appears to be a domain problem. When I have both YARP and the Calling app on the same environment, everything works fine. However, when I have YARP and the calling app on different environments then the Auth Token is never passed by the browser. I can see the auth headers in the browser, but they are never passed to IIS.
I have concluded that this is not a YARP issue.

Just to be clear, when I say the calling app, I am not referring to the app or API being proxied to, I am referring to the app making calls to YARP.

Thank you for the assistance.
