### ISSUE TITLE
How to get IHttpForwarder without Startup class

### ISSUE THREAD

**Issue by mah0o7co** [microsoft/reverse-proxy#2097]
I am using .net 7.
I want to get IHttpForwarder without using startup class. 
How to get forwarder inside program.cs

**Comment by MihaZupan** [comment]
Sorry about the confusion, if you're using the new minimal APIs with ASP.NET such that you just have a `Program.cs` file, you can inject services into the handler delegate like so:

```c#
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddHttpForwarder();

var app = builder.Build();

app.Map("/{**catch-all}", async (HttpContext context, IHttpForwarder forwarder) =>
{
    await forwarder.SendAsync(context, "https://httpbin.org", client);
});
```

See https://learn.microsoft.com/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-7.0#parameter-binding
