### ISSUE TITLE
Since i put more routes in the reverse proxy the cookie value become bigger

### ISSUE THREAD

**Issue by abratvisma** [microsoft/reverse-proxy#2106]
### Describe the bug
At this moment we got issue with ChunkingCookieManager described here https://github.com/dotnet/aspnetcore/issues/4639 which sadly not fixed yet.
What is not clear to me is that the new 3 additional routes that I added does not use cookie as its authorization, so how can adding new routes to the configuration somehow make the cookie become bigger and it become chunked.

### To Reproduce
- Follow the guideline to do incremental migration
- Add lot of rules like 6 routes
- Use open id connect

Ofcourse we can fix ChunkingCookieManager (will be nice if we can have official fix)
we can also try to fix why the cookie value so big in the first place
what is not quite clear yet for me is that this happen after I added those new routes

**Comment by Tratcher** [comment]
The number of routes should not have any relation to the cookie size.

Are you using these migration components? If so, please move this issue over there. (I can't transfer it across orgs).
https://github.com/dotnet/systemweb-adapters/tree/main/src

Can you please share your fix for the ChunkingCookieManager on the original issue?

**Comment by abratvisma** [comment]
that's what I thought also, it does not make any sense that adding more routes makes the cookie bigger
but I swear it happens after I add more routes

yes i do use migration component, ill close this one as you suggest and move it over there

i have no fix for ChunkingCookieManager, the workaround for me simply increasing the max header size in nginx
but my point is that bug still exists
