### ISSUE TITLE
How to log all of YARP activities to a file on disk

### ISSUE THREAD

**Issue by UltraDever** [microsoft/reverse-proxy#2107]
Perhaps I missed something, but looking at the documentation for logging, how do we log YARP events to file?
There are no conventional controllers to inject providers and so on.
Has anyone done this?

**Comment by Tratcher** [comment]
YARP has built in logs for all activities using ILogger. Do those include the information you want?

There isn't a file logger in the box but there are a bunch of libraries that do that.

> ASP.NET Core doesn't include a logging provider for writing logs to files. To write logs to files from an ASP.NET Core app, consider using a [third-party logging provider](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-7.0#third-party-logging-providers).

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-7.0#built-in-logging-providers

**Comment by UltraDever** [comment]
> YARP has built in logs for all activities using ILogger. Do those include the information you want?
> 
> There isn't a file logger in the box but there are a bunch of libraries that do that.
> 
> > ASP.NET Core doesn't include a logging provider for writing logs to files. To write logs to files from an ASP.NET Core app, consider using a [third-party logging provider](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-7.0#third-party-logging-providers).
> 
> https://learn.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-7.0#built-in-logging-providers

Perhaps I should have been clearer. Every 3rd party logger that I see is injecting an instance into a Controller/Constructor.
Given YARP is a Middleware and does not use conventional controllers, how do we get this information?

**Comment by Tratcher** [comment]
Serilog for example hooks into the AspNetCore logging infrastructure and can export the built in framework logs wherever you tell it to. YARP uses the same logging system and will be included in those logs exported.
https://github.com/serilog/serilog-aspnetcore

So, are you trying to get the logs from YARP, or add your own?

**Comment by UltraDever** [comment]
> Serilog for example hooks into the AspNetCore logging infrastructure and can export the built in framework logs wherever you tell it to. YARP uses the same logging system and will be included in those logs exported. https://github.com/serilog/serilog-aspnetcore
> 
> So, are you trying to get the logs from YARP, or add your own?

Thank you!
Not adding my own trying to get the logs from YARP, well, also the requests and response as an option.

**Comment by MihaZupan** [comment]
If you want to log the request/response (either just headers or also the body), you should check out https://learn.microsoft.com/aspnet/core/fundamentals/http-logging that's already built-in to ASP.NET Core.

**Comment by karelz** [comment]
Triage: Seems to be answered, closing.
