### ISSUE TITLE
LoadBalancing Green/Blue deployments

### ISSUE THREAD

**Issue by grahamehorner** [microsoft/reverse-proxy#212]
I would I feel be a good feature for the reverse-proxy to allow the load balancer to have support for green/blue deployments of services; that routes request according to some rule eg. based of % of traffic.

**Comment by Tratcher** [comment]
https://github.com/microsoft/reverse-proxy/issues/126 this is covered under the name A/B testing.

**Comment by karelz** [comment]
Duplicate of #126
