### ISSUE TITLE
Requests with HttpForwarder are slower

### ISSUE THREAD

**Issue by xmasctf** [microsoft/reverse-proxy#2126]
I'm making API calls using Postman to some endpoint (e.g. https://example.com/api) and it takes between 150-200ms to get a response.

I'm trying to use IHttpForwarder from [YARP 2.0.](https://microsoft.github.io/reverse-proxy/articles/direct-forwarding.html) and suddenly my requests start to take 400-700ms to get a response. I added some events logging based on [diagnosing YARP-based proxies](https://microsoft.github.io/reverse-proxy/articles/diagnosing-yarp-issues.html#using-telemetry-events) and those are the results:

> Forwarder Telemetry [13:30:40.534] => OnForwarderStage :: Stage: SendAsyncStart
> Forwarder Telemetry [13:30:40.758] => OnForwarderStage :: Stage: SendAsyncStop
> Forwarder Telemetry [13:30:40.966] => OnContentTransferred :: Content length: 510127, IOps: 24, Read time: 0.204, Write time: 0.003

Any idea how to fast those things up? Here is my code, which is more or less the same as in their documentation:

```csharp
[ApiController]
[Route("/test")]
public class TestController : ControllerBase
{
    private readonly IHttpForwarder _forwarder;

    private readonly CustomTransformer _transformer;
    private readonly HttpMessageInvoker _httpClient;
    private readonly ForwarderRequestConfig _requestOptions;

    public TestController(IHttpForwarder forwarder)
    {
        _forwarder = forwarder;

        // Setup our own request transform class
        _transformer = new CustomTransformer();

        // Configure our own HttpMessageInvoker for outbound calls for proxy operations
        _httpClient = new HttpMessageInvoker(new SocketsHttpHandler()
        {
            UseProxy = false,
            AllowAutoRedirect = false,
            AutomaticDecompression = DecompressionMethods.None,
            UseCookies = false,
            ActivityHeadersPropagator = new ReverseProxyPropagator(DistributedContextPropagator.Current)
        });

        // Initialize the ForwarderRequestConfig
        _requestOptions = new ForwarderRequestConfig { ActivityTimeout = TimeSpan.FromSeconds(100) };
    }

    [HttpGet]
    [Route("{**catch-all}")]
    public async Task IndexAsync()
    {
        var error = await _forwarder.SendAsync(HttpContext, "https://example.com/api/", _httpClient, _requestOptions, _transformer);
    }
}
```

I have tried disabling TLS/SSL certificate check, and adding some PooledConnectionLifetime to SocketsHttpHandler but without success. Is there anything else I can take look at to resolve the issue?

Thanks for help!

**Comment by MihaZupan** [comment]
A new `TestController` will be allocated on each request, meaning that you are allocating a new `SocketsHttpHandler` instance on each request.
As a result, every request will have to establish a new connection to the destination server, leading to increased latency.

Do you see meaningfully better results if you create the `SocketsHttpHandler` as a singleton instead?

**Comment by xmasctf** [comment]
Hi @MihaZupan, thanks for your response.

So what I did is, I have added this piece of code to `Startup`

```csharp
services.AddSingleton(_ => new SocketsHttpHandler()
{
    UseProxy = false,
    AllowAutoRedirect = false,
    AutomaticDecompression = DecompressionMethods.None,
    UseCookies = false,
    ActivityHeadersPropagator = new ReverseProxyPropagator(DistributedContextPropagator.Current)
});
```

And then I'm using it in `TestController` constructor as
```csharp
public TestController(IHttpForwarder forwarder,
    SocketsHttpHandler socketsHttpHandler)
{
     _forwarder = forwarder;
     _transformer = new CustomTransformer();
     _httpClient = new HttpMessageInvoker(socketsHttpHandler);
     _requestOptions = new ForwarderRequestConfig { ActivityTimeout = TimeSpan.FromSeconds(100) };
}
```

Measured times are now somewhere between 250 - 450ms, which is much better:

> Forwarder Telemetry [13:02:49.277] => OnForwarderStage :: Stage: SendAsyncStart
> Forwarder Telemetry [13:02:49.359] => OnForwarderStage :: Stage: SendAsyncStop
> Forwarder Telemetry [13:02:49.507] => OnContentTransferred :: Content length: 703046, IOps: 24, Read time: 0.137, Write time: 0.008

Is this what you meant, or should I do it any different?

Thanks for your help!

**Comment by MihaZupan** [comment]
Yes, that's one way to do that.

Are the number you are seeing now about as expected / comparable to talking to the destination directly?

**Comment by xmasctf** [comment]
Well, there is still some difference, since it takes 150-200ms when making calss directly to API, and 250-450ms when using YARP. 

Is this expected, or should there be less difference?

**Comment by samsp-msft** [comment]
There should be a small latency increase by adding YARP in the middle, as it is an extra hop, that needs to unpack the original request, and resend it, receive the results and repack them again, but an extra 100-250ms sounds high, depending on what type of environment the proxy is running in (network, hardware, hosting situation)
Is this time measuring for a single request, or averaged for a number of repeated requests? 
Is the YARP process warm - does request #2 or 10 have the same performance, assuming that the process hasn't restarted, and it's within connection re-use times?
Is this over TLS or plain http?
What is the size of the payload for the request and response?
Where is the proxy located network wise with respect to the caller and the destination - is the network causing some of the delay?

**Comment by xmasctf** [comment]
Lets say that the end destination is some kind of black box, I'm not aware of infrastructure that is being used there, since it's not controlled by me.
The measuring time is an average of 50 repeated requests, but I don't include the results of first requests because of the warm up process, as you mentioned. Since measurements were performed only locally and with requests made with Postman, maybe there will be different results when deploying to production slot.
