### ISSUE TITLE
Daily build broken Yarp.Kubernetes.Controller

### ISSUE THREAD

**Issue by KLuuKer** [microsoft/reverse-proxy#2134]
### Some details

**How many backends are in your application?**

- [ ] 1-2
- [ ] 3-5
- [X] 6-10
- [ ] 10+

**How do you host your application?**

- [X] Kubernetes (AKS)
- [ ] Azure App Service
- [ ] Azure VMs
- [ ] Other Cloud Provider (please include details below)
- [ ] Other Hosting model (please include details below)

### What did you think of YARP?

Daily build for **only** the kubernetes controller is broken
it's stuck on
- 2.0.0-rc.2.23068.2
- Wednesday, January 18, 2023 (1/18/2023)

while the main yarp nuget is on
- 2.1.0-preview.1.23259.1
- Tuesday, May 9, 2023 (5/9/2023)

**Comment by MihaZupan** [comment]
We're not currently shipping NuGet packages for the k8s controller (#1254) such that you have to build the project yourself.

For some time in 2022 we've been publishing the package to the daily feed (between #1642 and #2005). We could revisit that and continue pushing to the daily feed even if we don't yet publish to NuGet.

**Comment by KLuuKer** [comment]
I would prefer just grabbing from the daily feed, instead of building it myself everytime (which i was trying todo)

**Comment by karelz** [comment]
Triage: We agree that it should be back in daily feed. But we should make sure to NOT ship it by accident.

**Comment by KLuuKer** [comment]
Can I get a status update?
cause i'm grabbing the git repo (again) to update all of the code to the latest build....

**Comment by specialforest** [comment]
I'm interesting too, so I don't have to maintain a clone. Is this just a matter of reverting #2005?

**Comment by karelz** [comment]
Triage: We should do it ASAP, sorry that it is taking so long.
@benjaminpetit can you please help here?

**Comment by specialforest** [comment]
It could be that a daily build hasn't run yet. I see only the old build from Jan 18 in the nuget feed:
```
nuget list Yarp.Kubernetes -PreRelease -Source "https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-libraries/nuget/v3/index.json"
Yarp.Kubernetes.Controller 2.0.0-rc.2.23068.2
```

**Comment by Tratcher** [comment]
@benjaminpetit Something isn't right, I see `Yarp.ReverseProxy.2.1.0-preview.1.23558.1.nupkg` on the feed, but not `Yarp.Kubernetes.Controller.2.1.0-preview.1.23558.1.nupkg`.

**Comment by benjaminpetit** [comment]
I updated the publishing script to not publish Yarp.Kubernetes.Controller on nuget.org.

**Comment by benjaminpetit** [comment]
@KLuuKer, @specialforest : the package is now avaiable on the .NET Libraries Transport Daily feed, you need to add to your `NuGet.config` file the following line:

``` xml
<add key=".NET Libraries Transport Daily" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-libraries-transport/nuget/v3/index.json" />
```
