### ISSUE TITLE
Can´t Forward to two grpc service using Yarp

### ISSUE THREAD

**Issue by jose8789** [microsoft/reverse-proxy#2143]
### Describe the bug
I created two grpc services in two different projects in asp.net core and one project as my gateaway using yarp.proxy, in addition the two projects contain each 1 grpc service name greeter... Now cannot forward request to each one because I cannot figure out how to configure yarp configuration for this case
```
// The request message containing the user's name.
message HelloRequest {
  string name = 1;
}

// The response message containing the greetings.
message HelloReply {
  string message = 1;
}


Grpc service 2
syntax = "proto3";

option csharp_namespace = "GrpcService2";

package greet;

// The greeting service definition.
service Greeter {
  // Sends a greeting
  rpc SayHello (HelloRequest) returns (HelloReply);
}

// The request message containing the user's name.
message HelloRequest {
  string name = 1;
}

// The response message containing the greetings.
message HelloReply {
  string message = 1;
}
he´s how i´m calling the services

var channel1 = GrpcChannel.ForAddress("https://localhost:8000/greeter1/");
var client1 = new GrpcService1.Greeter.GreeterClient(channel1);
var request1 = new GrpcService1.HelloRequest { Name = "Jose Felix from service 1" };
var response1 = client1.SayHello(request1);

Console.WriteLine(response1.Message);

var channel2 = GrpcChannel.ForAddress("https://localhost:8000/service2");
var client2 = new GrpcService2.Greeter.GreeterClient(channel2);
var request2 = new GrpcService2.HelloRequest { Name = "Jose Felix from service 2" };
var response2 = client2.SayHello(request2);
Console.WriteLine(response2.Message);
```

### Further technical details

- Yarp.proxy version 2.0.0
-Windows

**Comment by jose8789** [comment]
`{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "AllowedHosts": "*",
  "ReverseProxy": {
    "Routes": {
      "grpcservice1": {
        "ClusterId": "grpcservice1",
        "Match": {
          "Path": "/greeter/{**catch-all}"
        },
        "Transforms": [
          { "PathPattern": "/Greeter/{**catch-all}" }
        ]
      },
      "grpcservice2": {
        "ClusterId": "grpcservice2",
        "Match": {
          "Path": "service2/{**catch-all}"
        },
        "Transforms": [
          { "PathPattern": "{**catch-all}" }
        ]
      }
    },
    "Clusters": {
      "grpcservice1": {
        "HttpRequest": {
          "Version": "2",
          "VersionPolicy": "RequestVersionExact"
        },
        "Destinations": {
          "destination1": {
            "Address": "https://localhost:8001"
          }
        }
      },
      "grpcservice2": {
        "HttpRequest": {
          "Version": "2",
          "VersionPolicy": "RequestVersionExact"
        },
        "Destinations": {
          "destination1": {
            "Address": "https://localhost:8002"
          }
        }
      }
    }
  }
}`

**Comment by jose8789** [comment]
this the configuration i have tried so far but without success

`{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "AllowedHosts": "*",
  "ReverseProxy": {
    "Routes": {
      "grpcservice1": {
        "ClusterId": "grpcservice1",
        "Match": {
          "Path": "/greeter/{**catch-all}"
        },
        "Transforms": [
          { "PathPattern": "/Greeter/{**catch-all}" }
        ]
      },
      "grpcservice2": {
        "ClusterId": "grpcservice2",
        "Match": {
          "Path": "service2/{**catch-all}"
        },
        "Transforms": [
          { "PathPattern": "{**catch-all}" }
        ]
      }
    },
    "Clusters": {
      "grpcservice1": {
        "HttpRequest": {
          "Version": "2",
          "VersionPolicy": "RequestVersionExact"
        },
        "Destinations": {
          "destination1": {
            "Address": "https://localhost:8001"
          }
        }
      },
      "grpcservice2": {
        "HttpRequest": {
          "Version": "2",
          "VersionPolicy": "RequestVersionExact"
        },
        "Destinations": {
          "destination1": {
            "Address": "https://localhost:8002"
          }
        }
      }
    }
  }
}`

**Comment by jose8789** [comment]
The main problem is that the service has the same name

**Comment by Tratcher** [comment]
Try this, I made some minor tweaks to your `Match/Path` fields to match your requests above.
```
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "AllowedHosts": "*",
  "ReverseProxy": {
    "Routes": {
      "grpcservice1": {
        "ClusterId": "grpcservice1",
        "Match": {
          "Path": "/greeter1/{**catch-all}"
        },
        "Transforms": [
          { "PathPattern": "/Greeter/{**catch-all}" }
        ]
      },
      "grpcservice2": {
        "ClusterId": "grpcservice2",
        "Match": {
          "Path": "/service2"
        },
        "Transforms": [
          { "PathPattern": "/" }
        ]
      }
    },
    "Clusters": {
      "grpcservice1": {
        "HttpRequest": {
          "Version": "2",
          "VersionPolicy": "RequestVersionExact"
        },
        "Destinations": {
          "destination1": {
            "Address": "https://localhost:8001"
          }
        }
      },
      "grpcservice2": {
        "HttpRequest": {
          "Version": "2",
          "VersionPolicy": "RequestVersionExact"
        },
        "Destinations": {
          "destination1": {
            "Address": "https://localhost:8002"
          }
        }
      }
    }
  }
}
```

**Comment by jose8789** [comment]
I thanks for replying. I tried your suggestion but it didn't work. it is giving an error

`Grpc.Core.RpcException
  HResult=0x80131500
  Message=Status(StatusCode="Unimplemented", Detail="Bad gRPC response. HTTP status code: 404")
  Source=Grpc.Net.Client
  StackTrace:
   at Grpc.Net.Client.Internal.HttpClientCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at GrpcService1.Greeter.GreeterClient.SayHello(HelloRequest request, CallOptions options) in D:\GitHub\School\src\Services\Presentation\Wpf\YarpGrpcApp\GrpcClient\obj\Debug\net8.0\Service1\GreetGrpc.cs:line 119
   at GrpcService1.Greeter.GreeterClient.SayHello(HelloRequest request, Metadata headers, Nullable`1 deadline, CancellationToken cancellationToken) in D:\GitHub\School\src\Services\Presentation\Wpf\YarpGrpcApp\GrpcClient\obj\Debug\net8.0\Service1\GreetGrpc.cs:line 108
   at Program.<Main>$(String[] args) in D:\GitHub\School\src\Services\Presentation\Wpf\YarpGrpcApp\GrpcClient\Program.cs:line 8
`

**Comment by Tratcher** [comment]
What was the request path for that one?

**Comment by jose8789** [comment]
I made up a github repo and added my initial project so can have a better idea... help me... 
https://github.com/jose8789/YarpGrpcTest.git

**Comment by Tratcher** [comment]
Your repo is empty.

**Comment by jose8789** [comment]
Hi, I just saw that it is really empty. Sorry, but now try  this one 
https://github.com/jose8789/testapp.git
