### ISSUE TITLE
Flow the status code from BadHttpRequestException 

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#2163]
The AspNetCore servers (especially Kestrel) will throw BadHttpRequestException from the request body when something goes wrong and include a HTTP status code that can be forwarded to the client. E.g. 413 when the request body exceeds size limits.

Today YARP captures the request body exceptions and returns a generic 400. It could instead check for this exception and flow a more specific status code back to the client.

**Comment by Hartaxfr** [comment]
Up !
