### ISSUE TITLE
CORS error in downstream services while using custom CORS policy

### ISSUE THREAD

**Issue by boyzrule** [microsoft/reverse-proxy#2188]
I am using YARP at Gateway level which is built using .NET seven for microservices and have a custom CORS policy in gateway for allowing specific origins to go through and connect to downstream services. When a call comes from client(browser) to a down stream microservice thorough gateway (YARP is configured in gateway) then it's giving me a CORS error as below:

error in browser: 

"Access to XMLHttpRequest at 'https://localhost:4000/downstream Service/API/v1/get List' 
from origin 'https://localhost:7000' has been blocked by CORS policy: 
Cannot parse Access-Control-Allow-Methods response header field in preflight response."

call comes from 7000 to 4000
7000 is web client here and 4000 is upstream gateway - as we can see downstream service path has been added with an upstream call port (4000) number to the call but the call is not going through because of browser.

how can I resolve this, any insight or help would be much appreciated.

**Comment by adityamandaleeka** [comment]
It may be useful to see a diagram of your configuration. In short, it seems like something has a reference to a host it shouldn't, but it's hard to tell what that is just based on the error you're seeing.

**Comment by boyzrule** [comment]
Hi aditya, 

Thanks for the response. Find the settings below for gateway config and downstream service config. 

This is my gateway CORS settings
![image](https://github.com/microsoft/reverse-proxy/assets/9811005/22b8e261-eaf5-40f5-b4ec-35ffc14c40f0)

This is my downstream service 1 configuration in service 1 configuration:
![image](https://github.com/microsoft/reverse-proxy/assets/9811005/17b90951-0670-485a-a967-b1fcd2afcc13)

Also, I wanted to mention here that when I change the gateway CORS config to below then it's working fine without any CORS error in browser.
![image](https://github.com/microsoft/reverse-proxy/assets/9811005/5f121f89-9662-4876-96d0-988fa3466486)

Any custom values in headers and Methods will raise CORS error.
Also, GET verb in Allow methods works fine (as shown below) but will give CORS error if we add other HTTP verbs.
![image](https://github.com/microsoft/reverse-proxy/assets/9811005/5616f27e-3cbe-464e-b269-aff4aa831a36)

Find the CORS policy I am using as below .
![image](https://github.com/microsoft/reverse-proxy/assets/9811005/1c8df3d6-be3c-4784-9f57-6ee229e4d034)
I am using any header and method to avoid CORS error but its not the ideal way and wanted to really use custom headers.

I saw the YARP documentation shows us that we can manage these headers for proxy calls to copy request headers and response headers either through configuration or through middle ware and I tried both but could not get it working. so any insight would be much appreciated.

Thanks!

**Comment by boyzrule** [comment]
Hi Aditya,

This is very high-level diagram of the CORS and YARP configuration apart from the configurations I have previously added.
![image](https://github.com/microsoft/reverse-proxy/assets/9811005/519e9fa3-1c98-4250-9a7c-d0db1551d52a)

**Comment by adityamandaleeka** [comment]
How are you using the config in your code? There should be something that's consuming the json config in your code. Perhaps there's a parsing issue or something there? You mentioned that having just one verb works and adding more doesn't; maybe the separators you're using (`,`) aren't being handled correctly? Just a guess...
