### ISSUE TITLE
Load Balancer mode - user dependency injection

### ISSUE THREAD

**Issue by grahamehorner** [microsoft/reverse-proxy#219]
### What should we add or change to make your life better?
At present the Load Balancer implementation has a fixed number of modes, and the implementation of these are rigid. however the number of load balancing algorithms/possibilities are infinite some can be complex and data-driven from external eg. service-discovery 

IMHO using dependency injection to allow a developer to register implementation of the logic for selection/routing to a endpoint; and thus remove the fixed nature of the LoadBalancer mode of operation.

### Why is this important to you?
As a developer I would like to extend/add/replace the mode of operation of the reverse proxy LoadBalancer with my own implementations in a way that has minimal code complexity and is easy to deploy and test in isolation.

ie. LoadBalancer - Green/Blue deployment routing with traffic slip 60% - 40%

**Comment by Tratcher** [comment]
Making load balancing more extensible is covered by https://github.com/microsoft/reverse-proxy/issues/106

FYI: we anticipate Green/Blue rolling deployments to be implemented as a distinct feature from load balancing, see https://github.com/microsoft/reverse-proxy/issues/126

**Comment by grahamehorner** [comment]
@Tratcher Thanks; I was using Green/Blue as an example of where the loadbalancer splits traffic or selects and endpoint based on some computation which is not currently implemented, possibly a confusing example given the name.

**Comment by karelz** [comment]
Duplicate of #106
