### ISSUE TITLE
no-streaming flag in logs

### ISSUE THREAD

**Issue by marekott** [microsoft/reverse-proxy#2194]
Hi, recently I was investigating logs generated by Yarp because we have noticed that entries informing about proxying of the request always ends with `no-streaming`. Our first thought was that it indicates that request was buffered in memory before proxying it to destination service. However after further investigation, I can see that this flag is only informing if current request was made with gRpc (https://github.com/microsoft/reverse-proxy/blob/main/src/ReverseProxy/Forwarder/HttpForwarder.cs#L135). Why is this info so important that it is added to each of those logs especially that it will change its value only when gRpc call is made? It can be a little misleading since streaming can be performed also in other scenarios than gRpc (WebSockets for example).

**Comment by Tratcher** [comment]
Also filed as a discussion: https://github.com/microsoft/reverse-proxy/discussions/2193

**Comment by karelz** [comment]
It currently covers only gRPC, but might cover more in future.
We could just drop the negative "no-streaming" parameter from logging and keep only the positive one "streaming".
We should also update gRPC docs to clarify it.

**Comment by marekott** [comment]
Hi @karelz sounds like a better solution than the current one. Of course perfect situation would be if it would cover more than only gRPC scenario. I can see that you have added `help wanted` label, I could help with that but please confirm that we indeed are removing `no-streaming` log and keep only `streaming` for gRPC.

**Comment by karelz** [comment]
Yes, that is correct.

**Comment by marekott** [comment]
Made PR with that change: https://github.com/microsoft/reverse-proxy/pull/2200. Hope it will be useful.
