### ISSUE TITLE
Control the handling of TaskCanceledException and other exceptions

### ISSUE THREAD

**Issue by anders-dev1** [microsoft/reverse-proxy#2195]
#### Our setup
We use YARP as a gateway from our frontend client to the backend services, with communication via gRPC-web.

#### The suggestion
We encounter an issue when the client leaves a page while streaming data from a backend service through the YARP proxy. YARP throws a `TaskCanceledException` in this scenario. No error is thrown or logged by the backend service. We expect this exception to be thrown, as it usually is when a task is canceled. However, it is currently not possible to catch and handle the exception with YARP. This is problematic for us because YARP logs the exception, which then gets caught by our analytics.

We have attempted to add middleware to address this issue, but we have been unable to stop the logging of the exception.

Changing the log level to not log errors is not a viable solution as we may miss other important errors.

We suggest one of the following solutions:
1. Add a configuration flag to toggle the logging of `TaskCanceledException` since it is an expected exception.
2. Make it possible for the consumer of YARP to decide how to handle exceptions. This may be achievable if we can catch it in middleware.

### Why is this important to you?
This is important to us as we don't want to log expected exceptions, which then gets reported by our analytics.

**Comment by Tratcher** [comment]
Please share the full log and stack trace you're concerned about.

> Add a configuration flag to toggle the logging of TaskCanceledException since it is an expected exception.

We have a policy against customizing log levels, it doesn't scale.

> Make it possible for the consumer of YARP to decide how to handle exceptions. This may be achievable if we can catch it in middleware.

This is more plausible.

**Comment by anders-dev1** [comment]
Sure, here is the stacktrace:
```
"System.Threading.Tasks.TaskCanceledException: The operation was canceled.\r\n ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..\r\n ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.\r\n --- End of inner exception stack trace ---\r\n at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)\r\n at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)\r\n at System.Net.Http.HttpConnection.ReadAsync(Memory`1 destination)\r\n at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadAsyncCore(Memory`1 buffer, CancellationToken cancellationToken)\r\n --- End of inner exception stack trace ---\r\n at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadAsyncCore(Memory`1 buffer, CancellationToken cancellationToken)\r\n at Yarp.ReverseProxy.Forwarder.StreamCopier.CopyAsync(Stream input, Stream output, Int64 promisedContentLength, StreamCopierTelemetry telemetry, ActivityCancellationTokenSource activityToken, Boolean autoFlush, CancellationToken cancellation)"
```

And the whole log entry (changed RequestPath as i can't show deails of what we are working on):
```
{"@t":"2023-07-18T07:14:28.1538081Z","@mt":"{error}: {message}","@x":"System.Threading.Tasks.TaskCanceledException: The operation was canceled.\r\n ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..\r\n ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.\r\n --- End of inner exception stack trace ---\r\n at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)\r\n at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)\r\n at System.Net.Http.HttpConnection.ReadAsync(Memory`1 destination)\r\n at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadAsyncCore(Memory`1 buffer, CancellationToken cancellationToken)\r\n --- End of inner exception stack trace ---\r\n at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadAsyncCore(Memory`1 buffer, CancellationToken cancellationToken)\r\n at Yarp.ReverseProxy.Forwarder.StreamCopier.CopyAsync(Stream input, Stream output, Int64 promisedContentLength, StreamCopierTelemetry telemetry, ActivityCancellationTokenSource activityToken, Boolean autoFlush, CancellationToken cancellation)","error":"ResponseBodyCanceled","message":"Copying the response body was canceled.","EventId":{"Id":48,"Name":"ForwardingError"},"SourceContext":"Yarp.ReverseProxy.Forwarder.HttpForwarder","RequestId":"0HMS7BQ8709RD:000000DF","RequestPath":"/servicename/streamendpoint","ConnectionId":"0HMS7BQ8709RD"}
```

Thanks for your help 😃

**Comment by MihaZupan** [comment]
Triage:
- We agree that most errors that occur as a result of the client disconnecting are not directly actionable by the proxy, and therefore less useful and potentially drowning out logs about real issues.
- We do not believe adding options to control how each exception is logged is a scalable solution.
- We are open to removing exceptions that result due to the client disconnecting from logs, or to moving them to a separate event with a higher verbosity level.

**Comment by jakebanks** [comment]
+1 for this, we are also seeing these as noise in our telemetry unfortunately

cc @ChintanRaval

**Comment by MihaZupan** [comment]
Now that we moved these logs from `Information` to `Warning`, this has become a lot more annoying - #2340.
Moving this one out of backlog.

**Comment by hesperanca** [comment]
+1 Same here. I get a notification on my mobile when there are exceptions raised by the servers. We have a multitenant SAAS tool and I'm getting pinged when our SPA client app cancels a request (e.g. when a customer paginates quickly through lists on our client app).

**Comment by MihaZupan** [comment]
#2503 is moving `RequestCanceled`, `RequestBodyCanceled`, and `UpgradeRequestCanceled` to a new debug-level log.
