### ISSUE TITLE
External logins and Handling routes that don't exist.

### ISSUE THREAD

**Issue by AdamBlade** [microsoft/reverse-proxy#2197]
### Describe the bug
A little preface, I'm trying to use YARP for local dev only, for handling a SPA and API.

I'm having issues when trying to use External logins it seems to be bypassing YARP and I'm not sure why.
Another issue is the fact that If I try to access a route that doesn't exist I get an infinite loop of requests.
For example It will flood the console with this.

info: Yarp.ReverseProxy.Forwarder.HttpForwarder[9]
      Proxying to https://localhost:7181/api/auth/google-login2 HTTP/2 RequestVersionOrLower no-streaming
info: Yarp.ReverseProxy.Forwarder.HttpForwarder[9]
      Proxying to https://localhost:7181/api/auth/google-login2 HTTP/2 RequestVersionOrLower no-streaming
info: Yarp.ReverseProxy.Forwarder.HttpForwarder[9]
      Proxying to https://localhost:7181/api/auth/google-login2 HTTP/2 RequestVersionOrLower no-streaming
info: Yarp.ReverseProxy.Forwarder.HttpForwarder[9]
      Proxying to https://localhost:7181/api/auth/google-login2 HTTP/2 RequestVersionOrLower no-streaming
info: Yarp.ReverseProxy.Forwarder.HttpForwarder[9]
      Proxying to https://localhost:7181/api/auth/google-login2 HTTP/2 RequestVersionOrLower no-streaming
info: Yarp.ReverseProxy.Forwarder.HttpForwarder[9]
      Proxying to https://localhost:7181/api/auth/google-login2 HTTP/2 RequestVersionOrLower no-streaming
info: Yarp.ReverseProxy.Forwarder.HttpForwarder[9] 

I was expecting to get 404, because that route doesn't exist on my API.

Here is how my app settings looks like.

```json
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
  },
  "ReverseProxy": {
    "Clusters": {
      "Client": {
        "Destinations": {
          "Client1": {
            "Address": "https://localhost:5173"
          }
        }
      },
      "Server": {
        "Destinations": {
          "Server1": {
            "Address": "https://localhost:7181/api"
          }
        }
      }
    },
    "Routes": {
      "ServerRoute": {
        "ClusterId": "Server",
        "Match": {
          "Path": "/api/{**catch-all}"
        },
        "Transforms": [
          {
            "PathRemovePrefix": "/api"
          }
        ]
      },
      "ClientRoute": {
        "ClusterId": "Client",
        "Match": {
          "Path": "{**catch-all}"
        }
      }
    }
  }
}

```

I've tried two scenarios:

- Yarp lives on my API (on this scenarios the login is not bypassed but i'm getting infinite request loops)
- Yarp lives in it's own separate project (on this scenario it's bypassing yarp when trying to do external login and getting infinite loops on paths that don't exist.)

Am I missing something obvious here? Any hint would be greatly appreciated.

### Further technical details
SPA - Vite
Windows 10/11
Net 7.

**Comment by MihaZupan** [comment]
> I'm having issues when trying to use External logins it seems to be bypassing YARP

External OAuth providers will generally have you specify a redirect Url in their configuration.
Are you specifying the YARP address there?

> I get an infinite loop of requests

Who is making these requests, the SPA from the browser?
What does the response look like, are they redirects?

**Comment by AdamBlade** [comment]
The loops happen when I try accessing a route that doesn't exist (via browser), like for example:
https://localhost:7181/api/auth/google-login2 
It doesn't seem to be redirecting, in my browser I only have one request but in YARP I see a wall of requests like the ones I've exemplified above.

When I specify the YARP address for the login redirect it fails, either from CORS or that the redirect_uri is mismatched.

**Comment by MihaZupan** [comment]
> Proxying to https://localhost:7181/api/auth/google-login2 HTTP/2 RequestVersionOrLower no-streaming

> "Destinations": {
> "Server1": {
> "Address": "https://localhost:7181/api"

Is your YARP running at `localhost:7181`?
If you ask YARP to proxy a request back to itself, then you will run into such a request loop.

> When I specify the YARP address for the login redirect it fails, either from CORS or that the redirect_uri is mismatched.

If you are hitting CORS issues, is the page referencing resources of the destination server instead of the proxy?
E.g. the url on a script is referencing `https://localhost:5173/script.js` instead of `/script.js` or `https://proxy-address/script.js`?

**Comment by AdamBlade** [comment]
Hi, 
I'm running YARP from my API which is on 7181.
So you're suggesting I use a 3rd project just for the Yarp setup to avoid running into request loop?
But why does this loop occur only if the route doesn't exist?

**Comment by MihaZupan** [comment]
> But why does this loop occur only if the route doesn't exist?

It does exist. Specifying the following in your config created a route that matches requests starting with `/api/`.

```c#
"ServerRoute": {
  "ClusterId": "Server",
  "Match": {
    "Path": "/api/{**catch-all}"
  },
```

If you don't want YARP to match those requests and try to forward them, you shouldn't define that route.

Do you have an API controller in the same app as your proxy that you want to handle requests to `/api/`?
In that case, you'd only want to define a `catch-all` in YARP, and make sure it has a lower priority (higher order value) than the API controller route.

**Comment by karelz** [comment]
Triage: Seems to be answered - configuration error. Closing.
