### ISSUE TITLE
Set timeout for Yarp.ReverseProxy.Forwarder.HttpForwarder

### ISSUE THREAD

**Issue by tellass567** [microsoft/reverse-proxy#2207]
### Describe the bug
Is it possible to configure the Yarp.ReverseProxy.Forwarder.HttpForwarder, so that I can set a timeout for the HttpForwarder? This is a code snippet from Program.cs. The configurations are in appsettings.json. The HTTP forwarder is not explicitly configured.

var builder = WebApplication.CreateBuilder(args);
builder.Services
.AddReverseProxy()
.LoadFromConfig(builder.Configuration.GetSection("section from appsettings"))
...
var app = builder.Build();
...
app.UseStaticFiles();
app.UseRouting();
app.UseAuthentication();
app.UseAuthorization();
app.Run();

The problem is this python script:

import requests
import urllib3
...
print(requests.get('https://yarp.xyz/interestingsite', headers=headers, verify=False))
time.sleep(0.0)
print(requests.get('https://yarp.xyz/abc.css', headers=headers, verify=False))
...

When I increase the sleeping time from 0.0 to 0.5 The scripts works and I get the css file. Otherwise I get an exception from the forwarder. Kestrel returns 502 http status code. The exception message is below.

Have also checked https://github.com/microsoft/reverse-proxy/discussions/2183. Do I have to explictly define a the forwarder and configure it in the code instead of the appsettings.json?

### Exception
info: Yarp.ReverseProxy.Forwarder.HttpForwarder[48]
      Request: An error was encountered before receiving a response.
      System.Net.Http.HttpRequestException: An error occurred while sending the request.
       ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
       ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
         --- End of inner exception stack trace ---
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
         at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext c

### Further technical details

- Include the version of the packages you are using
8.0.100-preview.3.23178.7

- The platform (Linux/macOS/Windows)
Windows

**Comment by Tratcher** [comment]
There's not an absolute timeout option, but there is an ActivityTimeout. https://microsoft.github.io/reverse-proxy/articles/http-client-config.html#httprequest

I don't quite understand your repro, how is that related to a timeout?

**Comment by karelz** [comment]
Triage: No further information in 3 weeks. Closing as there is nothing actionable for us now. Feel free to reopen if there is more info available.

**Comment by albrookesplowman** [comment]
Hi,  Please can you help... I have a API call which is taking long that the default 100 seconds to return.  I am using the direct forwarder mechanism but when I change of the ActivityTimeout to a larger number e.g. 10 minutes or even 1 hour, I still get a cancellation exception after 100 seconds.  it is an activityCancellationTokenSource.  I have tried calling the SendAsync with my own cancellation token set with a long timespan and this isn't getting triggered so I am not sure where the timeout of 100seconds is coming from.  Is there anywhere else that I can configure this timeout?

**Comment by MihaZupan** [comment]
Please open a new issue @albrookesplowman, we don't track comments on closed issues.

In general, the three places YARP will monitor for cancellation are:
- The activity timeout set in `ForwarderRequestConfig`
- The (optional) `CancellationToken` passed as the last parameter to `SendAsync`
- The `HttpContext.RequestAborted` `CancellationToken`

`RequestAborted` will fire if the client that made the request to the proxy disconnected/canceled its request. Could that be happening?

P.S. you should be creating the http client outside of the callback, otherwise you're never sharing connections to the backend service.

**Comment by albrookesplowman** [comment]
@MihaZupan - https://github.com/microsoft/reverse-proxy/issues/2298
