### ISSUE TITLE
Capture memory profile and eliminate unnecessary allocations

### ISSUE THREAD

**Issue by halter73** [microsoft/reverse-proxy#221]
We should look at our primary scenarios, perhaps those defined for our TE-style benchmarks https://github.com/microsoft/reverse-proxy/issues/40, and capture a memory profile so we can eliminate unnecessary allocations and improve performance.

**Comment by halter73** [comment]
I've started collecting memory profiles. So far, most of the allocations are more-or-less what we expected. A lot of string and dictionary entry allocations related to copying headers back and forth. Initially, there's also a lot of byte[] allocations as the memory pool grows to facilitate response body stream copying.

The most surprising allocation that I've noticed at this point is Kestrel allocating byte arrays via System.Text.Encoding.GetBytes() to generate HTTP status reason phrases. Normally, Kestrel would not call GetBytes() for reason phrases and instead use a cached default value corresponding with the response's status code. YARP, explicitly sets the reason phrase however, which bypasses this optimization.

It probably makes sense for YARP to set the reason phrase if it's not the default for the returned status code, but it could skip the allocation otherwise by just not specifying the reason phrase when it the default for the returned status code which should be the vast majority of cases.

I'll look at submitting a PR to address this.

<details>
  <summary>Memory profile screenshots</summary>

  ![string-allocs](https://user-images.githubusercontent.com/54385/84421329-435df600-abd0-11ea-9bb0-4cb4eb562c4b.PNG)

  ![dictonary-allocs](https://user-images.githubusercontent.com/54385/84421409-61c3f180-abd0-11ea-8c2a-0299a88c86bf.PNG)

  ![headerstoreiteminfo-allocs](https://user-images.githubusercontent.com/54385/84421362-4fe24e80-abd0-11ea-8e5b-fdd20789a405.PNG)

  ![byte-allocs](https://user-images.githubusercontent.com/54385/84421420-67b9d280-abd0-11ea-946d-493c4ce9b82c.PNG)
</details>

**Comment by Tratcher** [comment]
> It probably makes sense for YARP to set the reason phrase if it's not the default for the returned status code, but it could skip the allocation otherwise by just not specifying the reason phrase when it the default for the returned status code which should be the vast majority of cases.

That sounds like an optimization for Kestrel, not YARP. YARP is doing a blind copy of the response structure, it can't tell if the destination server actually specified a reason phrase or if it's returning a default value. That would require it to know which values were considered defaults for both HttpResponseMessage and Kestrel (they might not even align).

Kestrel should check for values that it has pre-encoded replacements for before invoking the encoder.

**Comment by samsp-msft** [comment]
How should we be thinking about the impact of the allocations?
33 allocations for the bodies are half the memory - but the 33 count is low, so it seems to not be churning them.
For things like string where there are hundreds of thousands of allocations - presumably we want to see the count and if something can be done to reduce those?

**Comment by halter73** [comment]
Both YARP or Kestrel *could* do the same lookup to see and elide the allocation if the custom-set reason phrase is the default value for status code, but I feel it would be wasteful for Kestrel to do in non-proxy scenarios. I cannot think of any reason to manually set the *default* reason phrase in addition to just setting the response status code outside of proxying. That being said, setting a reason phrase at all is a niche scenario, so it's not like the extra lookup in Kestrel would affect our plaintext and json benchmarks.

> How should we be thinking about the impact of the allocations?

I would mostly ignore the byte[] allocations that are renting from a memory pool like the 33 allocations for response body copying.

Normally, I would start collecting traces after a warmup to ignore these allocations, but VS forces you to start collecting at process start. I think I still messed up though, because I could have selected the post-warmup section of the benchmark timeline before digging into the allocations.

**Comment by samsp-msft** [comment]
Maybe the better question is what are the allocation counts on a per request basis. How many requests does your tracing cover? Is there a way of breaking it down further to what are the costs per header for example?

**Comment by halter73** [comment]
I should have recorded the output from bombardier which would tell you the number of request.

Still, you can infer the number of requests from the memory profile. In the first screenshot, you see a lot of objects were allocated exactly 19,866 times. Those are objects that were allocated once per request. So there were ~20,000 requests measured.

**Comment by halter73** [comment]
> Is there a way of breaking it down further to what are the costs per header for example?

If we want to do that, I would probably compare memory profiles from a scenario with 4 request headers and 8 request headers of similar sizes. We could do the same thing for response headers.

**Comment by davidfowl** [comment]
@halter73 did you use the number of requests feature of bombardier? 😄

**Comment by halter73** [comment]
No. I just did the following which defaults to sending requests as fast as possible (without pipelining) for 10 seconds:

```
> bombardier-windows-amd64.exe -c 256 http://localhost:5000/api/dump
```


<details>
  <summary>bombardier-windows-amd64.exe --help</summary>

```
> bombardier-windows-amd64.exe --help
usage: F:\Downloads\bombardier-windows-amd64.exe [<flags>] <url>

Fast cross-platform HTTP benchmarking tool

Flags:
      --help                  Show context-sensitive help (also try --help-long
                              and --help-man).
      --version               Show application version.
  -c, --connections=125       Maximum number of concurrent connections
  -t, --timeout=2s            Socket/request timeout
  -l, --latencies             Print latency statistics
  -m, --method=GET            Request method
  -b, --body=""               Request body
  -f, --body-file=""          File to use as request body
  -s, --stream                Specify whether to stream body using chunked
                              transfer encoding or to serve it from memory
      --cert=""               Path to the client's TLS Certificate
      --key=""                Path to the client's TLS Certificate Private Key
  -k, --insecure              Controls whether a client verifies the server's
                              certificate chain and host name
  -H, --header="K: V" ...     HTTP headers to use(can be repeated)
  -n, --requests=[pos. int.]  Number of requests
  -d, --duration=10s          Duration of test
  -r, --rate=[pos. int.]      Rate limit in requests per second
      --fasthttp              Use fasthttp client
      --http1                 Use net/http client with forced HTTP/1.x
      --http2                 Use net/http client with enabled HTTP/2.0
  -p, --print=<spec>          Specifies what to output. Comma-separated list of
                              values 'intro' (short: 'i'), 'progress' (short:
                              'p'), 'result' (short: 'r'). Examples:

                                * i,p,r (prints everything)
                                * intro,result (intro & result)
                                * r (result only)
                                * result (same as above)
  -q, --no-print              Don't output anything
  -o, --format=<spec>         Which format to use to output the result. <spec>
                              is either a name (or its shorthand) of some format
                              understood by bombardier or a path to the
                              user-defined template, which uses Go's
                              text/template syntax, prefixed with 'path:' string
                              (without single quotes), i.e.
                              "path:/some/path/to/your.template" or
                              "path:C:\some\path\to\your.template" in case of
                              Windows. Formats understood by bombardier are:

                                * plain-text (short: pt)
                                * json (short: j)

Args:
  <url>  Target's URL
```
</details>

**Comment by davidfowl** [comment]
NP, this profile is great (@halter73 shared it with me). There's SO much low hanging fruit which is good news. The bad news is a bunch of it might be because of API design 😄 . Regardless, now we have a baseline

**Comment by Tratcher** [comment]
> The bad news is a bunch of it might be because of API design

@davidfowl care to share a some of the highlights?

**Comment by Tratcher** [comment]
@sebastienros is this a task you can take over from Stephen? I think we're ready to do a first pass on the main request pipeline.

**Comment by sebastienros** [comment]
Sure. Do you want me to do it or is there someone in the team that wants to try it and just needs me to show how to 
- get a trace
- do changes and see progress
- repeat

**Comment by Tratcher** [comment]
Can you take a first pass at some of the middleware components?
https://github.com/microsoft/reverse-proxy/tree/master/src/ReverseProxy/Middleware

**Comment by Tratcher** [comment]
@alnikola @MihaZupan this issue tracks some of your current perf tasks.

**Comment by karelz** [comment]
@MihaZupan is there anything left here?
