### ISSUE TITLE
YARP 2.0.1 reverse proxy 302

### ISSUE THREAD

**Issue by fushiontest** [microsoft/reverse-proxy#2211]
I used **YARP 2.0.1**, when destination address response 302, my browser will change url,
I try to add X-forward-xx as following:
       targetRouteConfig = targetRouteConfig.WithTransformXForwarded(
                  xFor: ForwardedTransformActions.Append,
                  xHost: ForwardedTransformActions.Append,
                  xProto: ForwardedTransformActions.Append,
                  xPrefix: ForwardedTransformActions.Append);
but this issue still ocurred, have you any idea?
Note: I try use nignx poxy my destination webapp, It's Ok!

**Comment by karelz** [comment]
Triage: No response in 2 weeks. Not actionable for us, closing. Feel free to reopen if there is more info available. Thanks!
