### ISSUE TITLE
Behind proxy request and response from different services?

### ISSUE THREAD

**Issue by jbonnett92** [microsoft/reverse-proxy#2212]
Hi,
Is it possible that any request to YARP can get split in some way, e.g. YARP sends a request to a service, that service processes and moves onto another service where that service then responds? All this without going back to the previous service.

Thanks,
Jamie

**Comment by MihaZupan** [comment]
> YARP sends a request to a service, that service processes and moves onto another service where that service then responds

I'm not sure I understand what you're trying to do.

Do you mean that YARP would send every request to multiple destinations, but only proxy back the response for one of them? There's a bit more discussion around traffic mirroring like this in #105.

Or do you mean that the destination service A would do something with the request, and then forward it to another service B? If so, you could use YARP in service A to proxy the request again.

**Comment by karelz** [comment]
Triage: No response in 2 weeks. Not actionable for us, closing. Feel free to reopen if there is more info available. Thanks!
