### ISSUE TITLE
Duplicate message field in HttpForwarder ForwardingError log

### ISSUE THREAD

**Issue by JCFruit** [microsoft/reverse-proxy#2215]
Hello!

While investigating log messages rejected by out log collecting system, we found out that [HttpForwarder](https://github.com/microsoft/reverse-proxy/blob/main/src/ReverseProxy/Forwarder/HttpForwarder.cs#L951) uses `message` as parameter name in ForwardingError log message template.

Since we use json-encoded logging, resulting json has duplicated `message` property - one for log message itself and one for forwarding error. Such logs are rejected by our log collecting system as invalid.

Probably, parameter can be renamed to `errorMessage` or something like that

**Comment by MihaZupan** [comment]
What log collection system are you using? Who is doing the json encoding (and how)?

This sounds like a bug in that logic, not a YARP issue.

**Comment by JCFruit** [comment]
So basically it looks like this
1. Application (YARP) writes logs via Serilog.Sinks.Console with JsonEncoding to stdout.
2. Filebeat collects logs from stdout and ships them to log collection system based on ELK stack

Serilog sink produces json with property for each parameter in log message template, which results in two `message` properties in resulting json.

```json
// Example log message
{
    "@timestamp": "2023-08-10T07:11:17.9571614Z",
    "level": "INFO",
    // full message produced by ILogger
    "message": "RequestCanceled: \"The request was canceled before receiving a response.\"",
    "error": "RequestCanceled",
    // value of message parameter from message template
    "message": "The request was canceled before receiving a response.",
    "SourceContext": "Yarp.ReverseProxy.Forwarder.HttpForwarder"
    // other properties are omitted
}
```

**Comment by MihaZupan** [comment]
FWIW, `message` seems like such a generic parameter name that there are bound to be many other places where it'd end up being used with `ILogger`. Renaming it in YARP would just hide one symptom.

**Comment by JCFruit** [comment]
Yes, im talking Serilog (and probably some other logging frameworks) producing messages with this property under root.

But to be completely honest, i double-checked, and it looks like we using custom formatter for serilog, wich dumps all properties under json root. So, maybe, it only ours problem.

**Comment by JCFruit** [comment]
So, should I just close the issue?
