### ISSUE TITLE
How to use multiple custom transform providers?

### ISSUE THREAD

**Issue by askids** [microsoft/reverse-proxy#2219]
Hi

Currently I am using Yarp with custom implementation of ITransformProvider to apply request transformation. Now I have a requirement where I need to use 3 different transform provider based on a) route b) 2 variants based on presence of request header. I prefer to have separate classes for each of the transform providers. So in such a case, how do I conditional use different transform providers?

Thanks!

**Comment by Tratcher** [comment]
You can register as many different ITransformProvider's as needed, all will be used.

**Comment by askids** [comment]
> You can register as many different ITransformProvider's as needed, all will be used.

If we register multiple providers, in which order will they be applied?

**Comment by MihaZupan** [comment]
In the order they are registered with DI.

**Comment by karelz** [comment]
Triage: Answered, closing.
