### ISSUE TITLE
Add more benchmark scenarios

### ISSUE THREAD

**Issue by halter73** [microsoft/reverse-proxy#222]
This is a follow up to https://github.com/microsoft/reverse-proxy/issues/40.

There are countless proxy scenarios and variations that can be benchmarked, but currently our proxy benchmarks only capture the following scenario:

- Using unencrypted connections and making HTTP/1.1 GET requests to both the proxy and backend

This scenario varies by response body size: 10B, 100B, 1KB, 10KB, 100KB plaintext responses are currently tested. Limiting response body sizes to just 32KB and 255KB should reduce the total number of scenarios allowing us to add more interesting scenarios without creating information overload.

The next proxy benchmark scenarios we plan to add are:

- Using TLS connections and making HTTP/2 GET requests to both the proxy and backend
- Using TLS connections and making HTTP/1.1 GET requests to both the proxy and backend
- Using unencrypted connections and making HTTP/1.1 POST requests to both the proxy and backend

After those scenarios are completed. Here are even more scenarios we can consider.

- Logging completely disabled
- Requests with bodies
- Variations on headers
  - Large request headers
  - Large response headers
  - Request/Response header transformation
- gRPC through the rpoxy
  - gRPC streaming

**Comment by davidni** [comment]
Sugg adding larger payloads as well e.g. **10MB**.

For context, see e.g. [an issue I had with HttpSysServer on ASP .NET Core 2](https://github.com/aspnet/HttpSysServer/pull/418). A trivial HttpSys flag passed incorrectly resulted in massive impact (more than 20x slower throughput in that case). I expect most customers will encounter large payloads at one point or another, and making sure we're not adding perf cliffs along the way would be nice.

**Comment by karelz** [comment]
Triage:

We added most of all these benchmarks: https://aka.ms/aspnet/benchmarks
Couple of them are in progress of being added.

Closing, current status is enough for 1.0 for now.
