### ISSUE TITLE
Add microbenchmarks

### ISSUE THREAD

**Issue by halter73** [microsoft/reverse-proxy#223]
We should add microbenchmarks for key methods like ProxyInvokerMiddleware.Invoke(), LoadBalancingMiddleware.Invoke(), LoadBalancer.PickDestination(), etc. using https://github.com/dotnet/BenchmarkDotNet.

This provides a benefit over end-to-end benchmarks since microbenchmarks can more reliably measure smaller performance gains or losses in the components they measure which can add up over time.

**Comment by karelz** [comment]
Triage: We should have it for a few things when they show up on the profile. Not needed now.
