### ISSUE TITLE
[Question] How to remove duplicate response headers

### ISSUE THREAD

**Issue by msamwill** [microsoft/reverse-proxy#2236]
### Describe the bug
We have an ASP.Net Core razor pages application which uses YARP to forward requests to an internal server. We noticed recently that our responses have duplicate response headers, and the Cache-Control header has been changed from no-cache to include must-revalidate.

Below is an example of duplicated response-headers and modified Cache-Control header:
![image](https://github.com/microsoft/reverse-proxy/assets/7591429/dc71eb11-141a-43f6-835e-5e2e67643f7b)

### To Reproduce
Have a asp.net core razor pages application which uses YARP to forward requests to an internal server.  Service which is hosting YARP uses HttpForwarder and uses app.UseEndPoints in program.cs to transform and forward request.  

**The reverse proxy is added in the startup with:**
```c#
builder.Services.AddHttpForwarder();
```

**The message invoker is defined as follows:**
```c#
var httpClient = new HttpMessageInvoker(new SocketsHttpHandler()
{
    UseProxy = false,
    AllowAutoRedirect = false,
    AutomaticDecompression = DecompressionMethods.None,
    UseCookies = false,
    EnableMultipleHttp2Connections = true, 
    ActivityHeadersPropagator = new ReverseProxyPropagator(DistributedContextPropagator.Current)
});
```

**The app.UseEndpoints:**
```c#
app.UseEndpoints(endpoints =>
{
    endpoints.Map("/insertactualpathhere/{**catch-all}", async (HttpContext httpContext, IHttpForwarder forwarder) =>
    {
        var error = await forwarder.SendAsync(httpContext, "targetUrl", httpClient, requestOptions,
        static (context, proxyRequest) =>
        {
            var targetUrl = context.Request.QueryString.HasValue ? context.Request.QueryString.Value.Substring(1) : context.Request.GetEncodedUrl();
            proxyRequest.RequestUri = new System.Uri(targetUrl);

            proxyRequest.Headers.Host = null;
            return default;
        });

        // Check if the proxy operation was successful
        if (error != ForwarderError.None)
        {
            var errorFeature = httpContext.Features.Get<IForwarderErrorFeature>();
            var exception = errorFeature.Exception;
        }

        //Remove headers added by Proxy
        httpContext.Response.Headers.Remove(HeaderNames.CacheControl);
        httpContext.Response.Headers.Remove(HeaderNames.XPoweredBy);
        httpContext.Response.Headers.Remove(HeaderNames.XXSSProtection);
        httpContext.Response.Headers.Remove(HeaderNames.XContentTypeOptions);
        httpContext.Response.Headers.Remove(HeaderNames.StrictTransportSecurity);
        httpContext.Response.Headers.Remove("X-AspNet-Version");
        
    });
});
```

Got Exceptions? Include both the message and the stack trace
```
-->
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
﻿      An unhandled exception has occurred while executing the request.
﻿      System.InvalidOperationException: The response headers cannot be modified because the response has already started.
﻿         at Microsoft.AspNetCore.HttpSys.Internal.HeaderCollection.ThrowIfReadOnly()
﻿         at Microsoft.AspNetCore.HttpSys.Internal.HeaderCollection.Remove(String key)
﻿         at Program.<>c__DisplayClass0_0.<<<Main>$>b__2>d.MoveNext() in C:\Source\polkmap_new\Program.cs:line 112
﻿      --- End of stack trace from previous location ---
﻿         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
﻿         at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
﻿         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

### Further technical details
I found this post https://github.com/microsoft/reverse-proxy/issues/1971 which is very similar.  This case was resolved using the add request transform function, this does not appear to be an option with the HttpForwarder.  Could possibly add https://stackoverflow.com/questions/37395227/add-response-headers-to-asp-net-core-middleware instead.  I'm guessing there is a better option and I'm missing something simple.

- Include the version of the packages you are using
NuGet package version 2.01
- The platform (Linux/macOS/Windows)
Windows 11 (on development computer only right now)

**Comment by msamwill** [comment]
Added OnStarting method prior to forwarder and removed headers there instead.  This seems to be working.  If there is a better option, please let me know.

endpoints.Map("/inseractualpathhere/{**catch-all}", async (HttpContext httpContext, IHttpForwarder forwarder) =>
{
    httpContext.Response.OnStarting(() =>
    {
        //Remove headers
        httpContext.Response.Headers.Remove(HeaderNames.CacheControl);
        httpContext.Response.Headers.Remove(HeaderNames.XPoweredBy);
        httpContext.Response.Headers.Remove(HeaderNames.XXSSProtection);
        httpContext.Response.Headers.Remove(HeaderNames.XContentTypeOptions);
        httpContext.Response.Headers.Remove(HeaderNames.StrictTransportSecurity);
        httpContext.Response.Headers.Remove("X-AspNet-Version");
        return Task.CompletedTask;
    });

 var error = await forwarder.SendAsync(httpContext, "targetUrl", httpClient, requestOptions,
 static (context, proxyRequest) =>...

**Comment by MihaZupan** [comment]
It's not clear to me from your description whether you want to keep the headers added by your app, keep the ones added by the backend, or remove them completely.

The `forwarder.SendAsync` accepts an `HttpTransformer` where you can inject logic to modify the request/response.

E.g. if you want to avoid copying some headers from the backend, you can remove them in a response transform
```c#
private sealed class CustomTransformer : HttpTransformer
{
    public override ValueTask<bool> TransformResponseAsync(HttpContext httpContext, HttpResponseMessage proxyResponse, CancellationToken cancellationToken)
    {
        proxyResponse.Content.Headers.Remove(HeaderNames.CacheControl);

        // This will copy any remaining headers from 'proxyResponse' to 'httpContext'
        return base.TransformResponseAsync(httpContext, proxyResponse, cancellationToken);
    }
}
```

If you want to always remove these headers (even if added by your app prior to proxying), you could instead always remove them from the `HttpContext.Response`
```c#
public override async ValueTask<bool> TransformResponseAsync(HttpContext httpContext, HttpResponseMessage proxyResponse, CancellationToken cancellationToken)
{
    var proxyResponse = await base.TransformResponseAsync(httpContext, proxyResponse, cancellationToken);

    httpContext.Response.Headers.Remove(HeaderNames.CacheControl);

    return proxyResponse;
}
```

Or if you always want to keep only the headers returned by the proxy, you can clear them beforehand
```c#
httpContext.Response.Headers.Clear();

var error = await forwarder.SendAsync(httpContext, ...);
```

You can also take inspiration from other built-in transform implementations, like the [`ResponseHeadersAllowedTransform`](https://github.com/microsoft/reverse-proxy/blob/main/src/ReverseProxy/Transforms/ResponseHeadersAllowedTransform.cs).

**Comment by adityamandaleeka** [comment]
Looks like this has been answered.
