### ISSUE TITLE
setting cookie for multiple DNS

### ISSUE THREAD

**Issue by chuser1** [microsoft/reverse-proxy#2238]
Hi, I was proxying an application which has multiple DNS I want to pass cookie from one DNS response to another DNS request.
For example: application is using Microsoft authentication if we hit base URL http://xyz.com it is getting redirected to https://login.live.com, now when we hit base URL in response header we have x cookie, same cookie x I want to pass to https://login.live.com.  Is there any way to create pool of cookie for one base URL and other pool for other base URL.

**Comment by Tratcher** [comment]
I don't think cookies allow for sharing a cookie across domains?

Why are you proxying requests to login.live.com? The client should be accessing that directly.

**Comment by adityamandaleeka** [comment]
Triage: no response in 2 weeks. Closing, feel free to reopen.
