### ISSUE TITLE
Hostname token that can be used in transforms

### ISSUE THREAD

**Issue by radderz** [microsoft/reverse-proxy#2242]
### What should we add or change to make your life better?

It would be good for multi tenant systems to be able to have some kind of transform where the hostname becomes a part of the route as a prefix.

I.e. https://hostname/somepath -> https://cluster/hostname/somepath

### Why is this important to you?

This is useful when storing files in publicly accessible file storage like Azure Blobs for files like "/.wellknown/assetlinks.json" for andoird deep linking where depending on the hostname this needs to be on a different path. Having something like this would let us add a folder in azure blob storage that holds the tenant hostname for storing and files we want to serve up.

This can be done in code but would be good to be able to do it through configuration.

I would see a rule similar to this:

```json
"Routes" : {
	"deep-linking-assetlinks": {
		"ClusterId": "deep-linking-cluster",
		"Match": {
			"Path": "/.well-known/assetlinks.json"
		},
		"Transforms": [
			{
				"PathSet": "/{**host}/assetlinks.json"
			}
		]
	}
}
```

> The above would resolve https://hostname/.well-known/assetlinks.json -> https://cluster/hostname/assetlinks.json

**Comment by karelz** [comment]
Triage: In general, we don't want to create a massive new language in the config. Code-first would be our preference here. However, if there is strong demand, we will be happy to reassess our position.
Keeping it open to collect more upvotes.

**Comment by radderz** [comment]
Is there a way to write out own types of transforms?

I.e. a PrependHostName transform that does the same thing?

**Comment by Tratcher** [comment]
Yes: https://microsoft.github.io/reverse-proxy/articles/transforms.html#itransformfactory

**Comment by radderz** [comment]
Oh cool, I didn't notice that was possible in the docs.

For me this would be a reasonably simple implementation so from my perspective this could be closed unless you want to keep this open for others to consider. I imagine not everyone uses their YARP proxy at the code level.

**Comment by karelz** [comment]
> I imagine not everyone uses their YARP proxy at the code level

Flexibility (via code) is the key added value of YARP compared to other reverse proxies.
While no-code scenario is on our radar, it won't provide that much flexibility and is not on immediate roadmap for us.

**Comment by samsp-msft** [comment]
YARP was started because internal Microsoft Teams wanted more customizability than other proxies offered, so we have always been a library that you build a custom proxy from. Having the ability for users to write code means we can focus on providing suitable extensibility points rather than having to try and bake in functionality that will satisfy everyone's individual needs.

We want to strike the right balance of being able to extend the functionality in code, which is then available for use from configuration. Does this implementation meet that goal for you?
