### ISSUE TITLE
Configuration API

### ISSUE THREAD

**Issue by cmenzi** [microsoft/reverse-proxy#2245]
### What should we add or change to make your life better?
I would be great having a Configuration API endpoint to update configuration at runtime. 

### Why is this important to you?
If you would like to create API Gateway with Yarp. Microservices CI/CD jobs can update the configuration of newly created endpoints and routes.

Similar to
- https://www.envoyproxy.io/docs/envoy/latest/api/api
- https://caddyserver.com/docs/api-tutorial

The even have test config, transition config, ...

That would make my life better :-)

**Comment by karelz** [comment]
Triage: We think you should be able to easily plug in config endpoint into [IConfigProvider](https://microsoft.github.io/reverse-proxy/api/Yarp.ReverseProxy.Configuration.IProxyConfigProvider.html). Is that what you are looking for?

**Comment by cmenzi** [comment]
Yes, I know. We already built something, based on IConfigProvider and Azure App Configuration Service. But I mean first class support like `UseYarpConfigurationApi()`. 😄

**Comment by Tratcher** [comment]
This is an area where the community can try out a few approaches and let us know what works well. E.g. what granularity of updates are supported? Is there versioning and rollback support?

One requirement is that these endpoints would have to be authenticated.

**Comment by cmenzi** [comment]
Are these questions to me or in general?

I think the current model already supports everything. We would just need to create stable & versioned Model classes

I think we could also add those thing as Contribs projects.

Not sure how Yarp is up to this.

Yes, sure Authentication is a must, but I would just go with the AspNet Core capabilities. With this, basically everything is possible. ApiKey, JwtBearer, ...

**Comment by cmenzi** [comment]
Are these questions to me or in general?

I think the current model already supports everything. We would just need to create stable & versioned Model classes

I think we could also add those thing as Contribs projects.

Not sure how Yarp is up to this.

Yes, sure Authentication is a must, but I would just go with the AspNet Core capabilities. With this, basically everything is possible. ApiKey, JwtBearer, ...

**Comment by John0King** [comment]
@Tratcher @karelz  the `IConfigProvider` and `IProxyConfig`   returns an `IReadOnlyList<RouteConfig>`  and  an `IReadOnlyList<ClusterConfig>`  which is a "limited in memory" mode   , and   route configurations can not over `Int.MaxValue`,
I'm wonder that on  a  platform like azure/github , the user keep adding routes  and the platfom must process all the "routes" , 
Will this "in memeory" mode too  limited in this scenario?

**Comment by Tratcher** [comment]
@John0King At that scale a flat list of routes doesn't work well anyways. Azure is already using YARP in several large services, but they tend to need a lot of customization, so they do their own routing and then use IHttpForwarder directly. Another way services scale is to have multiple layers of proxies & routing.

**Comment by adityamandaleeka** [comment]
Triage: it doesn't seem like there's anything immediately actionable here for us to do here, but we're interested in feedback on what YARP could provide in the box to make this easier. If you try this out yourself and have any input for us, please let us know in a new issue.
