### ISSUE TITLE
ActivityTimeout for gRPC keep alive pings

### ISSUE THREAD

**Issue by oakio** [microsoft/reverse-proxy#2247]
What is the reason to ignore HTTP/2 protocol pings for reset [ActivityTimeout](https://microsoft.github.io/reverse-proxy/api/Yarp.ReverseProxy.Forwarder.ForwarderRequestConfig.html#Yarp_ReverseProxy_Forwarder_ForwarderRequestConfig_ActivityTimeout)?

In my case proxing gRPC stream with [Keep Alive Pings](https://learn.microsoft.com/en-us/aspnet/core/grpc/performance?view=aspnetcore-7.0#keep-alive-pings) not working as expected.

**Comment by karelz** [comment]
HTTP/2 and TCP pings are not propagated to user code, therefore `ActivityTimeout` does not know about them.
You set the `ActivityTimeout` to higher value, or you can try to enforce more gRPC traffic (e.g. gRPC pings if there is such a thing).

**Comment by oakio** [comment]
Thanks for reply!
