### ISSUE TITLE
Specify path-based route namespaces

### ISSUE THREAD

**Issue by greatbob6** [microsoft/reverse-proxy#226]
### What should we add or change to make your life better?

I would love to have the ability to create a route in a way which would make a request to the destination using only a portion of the path which the proxy receives.  This way I could namespace routes using the path.

Assume the following setup:

Route is defined to match based on Path: /api1/{**catchall}
Destination address is defined: https://destination/
Incoming request path: /api1/dothething

Desired result:
Outgoing request is made to https://destination/dothething

Current result:
Outgoing request is made to https://destination/api1/dothething

### Why is this important to you?

Currently, I don't see a good way to setup routes to different destinations based on path, it would have to use some form of host differentiation but my original requests will be pointing at the proxy directly rather than being more transparently intercepted and so it seems that the host information will not be useful.

**Comment by greatbob6** [comment]
It looks like the catchall route value is already acquiring the data which would be needed to do this, it would just need a way of configuring the destination path using that data.

**Comment by Tratcher** [comment]
This work is already in progress, check out https://github.com/microsoft/reverse-proxy/pull/225

**Comment by greatbob6** [comment]
Awesome, thanks for sharing!

**Comment by karelz** [comment]
Duplicate of #225
