### ISSUE TITLE
Question: API for fetching health information

### ISSUE THREAD

**Issue by palashsinha** [microsoft/reverse-proxy#2273]
### Question:
Is it possible to create an API endpoint which will return the consolidated health check information from each instances of downstream services? Each downstream microservices can have multiple dependencies(DB, Message broker etc.) and it can return health information for each dependencies. This way a the client can have more details on each microservices and it's dependencies.
### ### 
We wanted to create a custom health monitor dashboard to fetch all the health checks for each instances. As YARP already contains all the destinations and it checks for liveliness of the instance, we wanted to extend this to fetch more health information.

**Comment by karelz** [comment]
Triage: Today, you can get list of destinations via `IProxyStateLookup` - where you can get basic health data - Healthy/NotHealthy.
That will not give you details of each backend - you need to go to healthcheck point of the backend to get that. The details are not interesting to YARP, we would be just aggregating.
If you are interested in that, you might be able to add Metadata to each destination with "DestinationHealthceckDetailsURL" and then aggregate it across all destinations.

You might even leverage Kestrel built-in health details - see https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-7.0
