### ISSUE TITLE
Catch-all path does not match empty string

### ISSUE THREAD

**Issue by ptupitsyn** [microsoft/reverse-proxy#2275]
The following config does not match empty path:
* `instance-name.example.com/foobar` works
* `instance-name.example.com/1` works
* `instance-name.example.com/` **does not work**

```csharp
            routes.Add(new RouteConfig
            {
                RouteId = instance.Name,
                ClusterId = clusterId,
                Match = new RouteMatch
                {
                    Hosts = new[]
                    {
                        "instance-name.example.com"
                    },
                    Path = "{**catchall}"
                }
            });
```

Browser sends host header correctly (`instance-name.example.com`). Am I doing something wrong?

**Comment by ptupitsyn** [comment]
With help of debug logging (https://microsoft.github.io/reverse-proxy/articles/diagnosing-yarp-issues.html), figured out that another route was taking precedence (default from Blazor).

The fix is to set `RouteConfig.Order` to `int.MinValue`.

**Comment by ChintanRaval** [comment]
also, you may need a forward slash to start the catchall i.e. `/{**catchall}`
