### ISSUE TITLE
Accessing current request route info (basically RouteModel) from policy handler (HandleRequirementAsync)

### ISSUE THREAD

**Issue by c0deExplorer** [microsoft/reverse-proxy#2276]
Because, authorization middleware is configured before endpoints.MapReverseProxy(), {http context}.GetReverseProxyFeature() is null inside the authorization policy handler. But the handler is getting properly routed based on "AuthorizationPolicy" in the config. Would like to know how I could access the current route info (ex. routeId, match path etc )from within policy handler.
Thank you!

**Comment by Tratcher** [comment]
You can get RouteModel from the Endpoint Metadata:
https://github.com/microsoft/reverse-proxy/blob/0229054f36a30396c4d58e6ecdc8188b5c7d9fb4/src/ReverseProxy/Model/ProxyPipelineInitializerMiddleware.cs#L30-L33

GetReverseProxyFeature only works within the proxy middleware pipeline.

**Comment by c0deExplorer** [comment]
Perfect! That's exactly what I was looking for. Thanks much @Tratcher!

**Comment by karelz** [comment]
Triage: Answered above, closing.
