### ISSUE TITLE
Proxy should have active health checks to confirm the state of destinations

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#228]
We have the IHealthProbeWorker and associated infrastructure, but it's all internal and nobody ever starts it.

This was forked from the original partner team code before health checks were completely implemented. Some missing pieces:
- An IHostedService that resolves the IHealthProbeWorker and starts and stops it when needed. 
- DI extensions for registering the health services.

@davidni

**Comment by davidni** [comment]
We've made substantial changes in this area since the hard fork:
* Debouncing of failures
* Wired up with signals to react to config changes immediately
* Logging and metrics reporting
* Fixed exception handling

When are you planning to tackle this? I don't have the bandwidth to prepare a PR until at least late next week.

**Comment by Tratcher** [comment]
We haven't scheduled it yet, I only filed it for tracking once we realized it was incomplete.

**Comment by davidni** [comment]
FYI, I've started to cleanup and refactor our internal implementation in prep for submitting a PR here. Earliest ETA remains late next week.

**Comment by Tratcher** [comment]
When looking at the design also consider https://github.com/microsoft/reverse-proxy/issues/304 for pulling health state from another service.

**Comment by alnikola** [comment]
Draft design proposal:
- IDestinationHealthEvaluationStrategy - evaluates a destination health based on probing results and requests successes/failures reported by active and passive health check services. **It's configured per cluster**.
Strategy examples: "take last status", "mark as unhealthy after first failure, mark as healthy after all success in X time period", "ignore some unsuccessful response codes", etc.
- IActiveHealthProber - proactively pings destinations once in a given period and calls the evaluation strategy with the probing results to determine a destination health status. If the newly calculated status is different from the current one, it updates `Health` property on the `DestinationInfo.DynamicStateSignal`.
- IPassiveHealthWatcher - reacts to requests proxying results reported by the `ProxyInvokerMiddleware` and passes them to an evaluation strategy to determine a destination health status. This passive watcher gets called for both of successfully and unsuccessfully proxied requests. If the newly calculated health status is different from the current one, it updates `Health` property on the `DestinationInfo.DynamicStateSignal`.
- IExternalDestinationHealthDataListener - opens an HTTP endpoint on YARP itself which can be called by 3rd party health data providers to explicitly set destination health status. If the newly received destination health status is different from the current one, it updates `Health` property on the `DestinationInfo.DynamicStateSignal`. It gets registered with an extension method which would also register the corresponding endpoint on Kestrel.

**Comment by alnikola** [comment]
`IDestinationManager` - adds/removes destination from/on available destination list when destination's health change.

**Comment by Tratcher** [comment]
> * Support an external destination health data source which can either completely substitute the built-in health checks or be combined with them (see #304)

Is there also a requirement for the reverse scenario, pushing health data to an external service? Or at least publicly exposing it so such an operation could be performed? It seems like #306 would also require access to health data.

> IPassiveHealthWatcher - reacts to requests proxying results reported by the ProxyInvokerMiddleware

There's no technical reason it needs to be part of ProxyInvokerMiddleware right? I think the only unique knowledge ProxyInvokerMiddleware has right now is which DestinationInfo was finally selected, and that's data we should find a way to preserve regardless.  IPassiveHealthWatcher should be inserted into the pipeline with its own middleware to maximize customization flexibility even up to being able to remove/replace the whole middleware.

> IDestinationHealthEvaluationStrategy

In the diagram, both IActiveHealthMonitor and IPassiveHealthWatcher should be pointing at the same IDestinationHealthEvaluationStrategy, right?

> it updates Health property on the DestinationInfo.DynamicStateSignal

We'll need to discuss the public usage of signals here. We've avoided their use in public APIs so far.

**Comment by Tratcher** [comment]
IPassiveHealthWatcher seems like it should be able to examine responses in more detail to decide what it considers a failure. Should it be passed the HttpContext? E.g. the destination could respond with a 503 or a 400 and that wouldn't generate a IProxyErrorFeature today, IProxyErrorFeature primarily captures exceptions.

**Comment by Tratcher** [comment]
Do the active health probes use the same per-cluster HttpClient as the proxied requests?
- Pro:
  - Re-uses existing connections, configuration (e.g. client certificates)
  - More accurately reflects the proxied request experience
  - Reacts to cluster config changes, central point of config
- Con: 
  - The health checks may be queued behind other requests, take longer to run.

Where do we configure the active health check endpoint?
- At the cluster level supply a path like `/health-checks`.
- At the destination level allow an alternate prefix (scheme, host, port, path) so you can specify that health checks are done on a different scheme/port.
- Active health checks are sent to the the destination (or alternate) prefix + cluster health path.

**Comment by samsp-msft** [comment]
> * Con:
>   
>   * The health checks may be queued behind other requests, take longer to run.
> 
Is there a timeout for the health checks. In which case the above may actually be a good thing - the host is obviously overloaded if it can't answer - or would that lead to more trouble?

**Comment by Tratcher** [comment]
For the config schema, I'm expecting health checks to have their own per-cluster section:
```
        "cluster1": {
            "LoadBalancing": {
                "Mode": "Random"
            },
            "HealthChecks": {
                "Enabled": "true",
                "Interval", "00:05:00"
                "Timeout", "00:00:30"
                "Strategy": "TakeLatest",
                "Path": "/Heath",
            }
            "Destinations": {
                "cluster1/destination1": {
                    "Address": "https://localhost:10001/",
                    "Health": "http://localhost:4040/",
                }
            }
        }
```
See some of the existing settings we have in the system:
https://github.com/microsoft/reverse-proxy/blob/master/src/ReverseProxy/Configuration/Contract/HealthCheckData.cs

**Comment by samsp-msft** [comment]
If a path is set on the healthchecks and a host on the destination do they get appeneded, or should a path on the destination be considered an override.

**Comment by Tratcher** [comment]
I'd recommend they append for consistency. That's how the cluster path would apply to the normal destination prefix.

**Comment by davidni** [comment]
Thinking about previous discussions about "gradual warm-up" of destinations as well as soft Vs. hard failure modes, would it perhaps make sense to make the health signal a double instead of a boolean? The `AND` could be implemented as a multiply, and the final health value for a destination could be multiplied with its weight to affect final routing decisions.

This would enable interesting scenarios (e.g. reduce weight to a destination if its latency is increasing, but don't remove it from rotation entirely, to mitigate cascading failure / snowball effect. To be clear, this is more future looking, and we don't need it right away.

**Comment by alnikola** [comment]
That's an interesting idea. Though, I was thinking about a different approach to gradual warm-up where we kept destination weight and health status separately. That way, a new IWarmUpManager would be a yet another recipient of destination's health change event which would react to the "Unhealthy -> Healthy" transition by starting gradually increasing the destination's weight and thus increasing the load.

**Comment by Tratcher** [comment]
@davidni, that's a good point, health isn't necessarily binary. I've seen a number of systems that use at least three states (healthy, degraded, offline). If we didn't want to go with a full double we may still consider using several buckets, including one for slow start. This may have interesting effects in the stack, like maybe load balancing prefers heathy endpoints, but session affinity allows any state but offline.

**Comment by alnikola** [comment]
Health state buckets seem as a good compromise between binary and double values.

**Comment by Tratcher** [comment]
IActiveHealthMonitor depends on IClusterManager and Signals for config change notifications, neither of which are currently public. We'll need a public solution here for IActiveHealthMonitor to be a viable extensibility point.

**Comment by Tratcher** [comment]
I'm trying to understand the separation of responsibilities between IPassiveHealthWatcher vs IPassiveHealthCheckPolicy and IActiveHealthMonitor vs IActiveHealthCheckPolicy.

IPassiveHealthWatcher is passed the entire request/response, makes some determination about that being a success or failure, looks up the policy for the current cluster, and then calls IPassiveHealthCheckPolicy with the same parameters. Determining success or failure seems like it should be a concern for IPassiveHealthCheckPolicy, not IPassiveHealthWatcher? Would it make more sense if IPassiveHealthWatcher's sole responsibility was to look up the policy for a cluster and call it, then have the policy determine success or failure? That would also help with our non-binary ideas around health states.

IActiveHealthMonitor has a similar concern. IActiveHealthMonitor's responsibility is scheduling and sending the health probes, not determining if they succeeded or failed. Here again I think it'd make more sense to pass the whole response to the cluster specific IActiveHealthCheckPolicy and let it determine success/failure/health. The response may also contain hints like "retry-after" that could influence the health state algorithm beyond the scope of a single probe.

**Comment by alnikola** [comment]
> IActiveHealthMonitor depends on IClusterManager and Signals for config change notifications, neither of which are currently public. We'll need a public solution here for IActiveHealthMonitor to be a viable extensibility point.

Valid point. To avoid exposing `IClusterManager` and signals, I propose propagate Cluster changes via push instead of pulling cluster collection from `IClusterManager`.
Specifically:
1. Add a new interface `IConfigChangeListener` with `OnClustersChanged(Cluster cluster)` method. It can be implemented by several services, so all implementations will be registered via `TryAddEnumerable`.
2. Add `IConfigChangeListener` as a base interface of `IActiveHealthMonitor`.
3. Add a virtual method `OnItemChanged(T item)` to `ItemManagerBase<T>` that will be called right after `UpdateSignal` call in `ItemManagerBase<T>.GetOrCreateItem`.
4. Implement `UpdateSignal` method in `ClusterManager` with code calling `OnClusterChanged` on all registered `IConfigChangeListener` implementations.

In code
```C#
public interface IConfigChangeListener
{
    void OnClustersChanged(Cluster cluster);
}

public interface IActiveHealthMonitor : IConfigChangeListener, IDisposable
{
    Task ForceCheckAll(IEnumerable<ClusterInfo> allClusters);
}

internal abstract ItemManagerBase<T>
{
    // ...
    public T GetOrCreateItem(string itemId, Action<T> setupAction)
    {
        // ...
        if (!existed)
        {
           _items.Add(itemId, item);
            UpdateSignal();
            OnItemChanged(item); // New code
        }

        protected virtual void OnItemChanged(T item)
        {
            // Do nothing by default.
        }
        // ...
    }
}

internal sealed class ClusterManager
{
    private readonly IConfigChangeListener[] _listeners;
    // ...
    protected override void OnItemChanged(Cluster item)
    {
        foreach (var listener in _listeners)
        {
            listener.OnClusterChanged(item);
        }
    }
}
```

**Comment by alnikola** [comment]
> I'm trying to understand the separation of responsibilities between IPassiveHealthWatcher vs IPassiveHealthCheckPolicy and IActiveHealthMonitor vs IActiveHealthCheckPolicy.
> 
> IPassiveHealthWatcher is passed the entire request/response, makes some determination about that being a success or failure, looks up the policy for the current cluster, and then calls IPassiveHealthCheckPolicy with the same parameters. Determining success or failure seems like it should be a concern for IPassiveHealthCheckPolicy, not IPassiveHealthWatcher? Would it make more sense if IPassiveHealthWatcher's sole responsibility was to look up the policy for a cluster and call it, then have the policy determine success or failure? That would also help with our non-binary ideas around health states.
> 
> IActiveHealthMonitor has a similar concern. IActiveHealthMonitor's responsibility is scheduling and sending the health probes, not determining if they succeeded or failed. Here again I think it'd make more sense to pass the whole response to the cluster specific IActiveHealthCheckPolicy and let it determine success/failure/health. The response may also contain hints like "retry-after" that could influence the health state algorithm beyond the scope of a single probe.

My idea was a concern separation between policies on one side and `Watcher`/`Monitor` on the other. Meaning, `PassiveHealthWatcher` and `ActiveHealthMonitor` incapsulate logic of running a check operation and registering its result (though, for `Watcher` is seems as a simple pass-through), but they don't know how that result affects destinations health. Whereas, policies incapsulate calculation of a new destination health status based on the current status and the check result, but are they not aware of how the check operation itself is executed.

Having that said, I see your point that passing the entire request/response message or a probing result to policies can make it more flexible, but not sure if it justifies an increased coupling between the check logic and the health status evaluation.
