### ISSUE TITLE
Question: Does Yarp support to set destination per in-coming request?

### ISSUE THREAD

**Issue by Zoe-ms** [microsoft/reverse-proxy#2280]
We want to leverage YARP as http2 proxy. We have a per region proxy server, and we have a scenario that the proxy server need check each incoming request, have some storage lookup according to values to the request, then forward the request to any other region proxy server based on the storage value. So in this case, the forward target is determined by parsing the request, and it would be different per request.
Per my understanding, today in YARP, the routing rules are defined in Kestrel ConfigureServices, loading from config or memory. Setting routing destination at request level seems cannot be supported. Not sure if I miss anything. Could you please help confirm?
Thanks.

**Comment by MihaZupan** [comment]
As mentioned offline, this is something that direct forwarding can help with - https://microsoft.github.io/reverse-proxy/articles/direct-forwarding.html.
You can inspect the incoming request, decide on the destination, and call the forwarder.

**Comment by karelz** [comment]
Triage: Answered, closing.
