### ISSUE TITLE
Unable to set RateLimiterPolicy to 'default' or 'disable'

### ISSUE THREAD

**Issue by jakebanks** [microsoft/reverse-proxy#2284]
### Describe the bug
Following the [README](https://github.com/microsoft/reverse-proxy/blob/main/docs/docfx/articles/rate-limiting.md) for rate limiting I am able to successfully add a rate limiter policy `customPolicy`, however, when I try to disable it for a route I am getting the error `RateLimiter policy 'disable' not found for route 'route1'.`

I think this might be caused by the code for validating routes being unable to detect these built in policies, since the collection appears empty.

Am I doing something incorrectly here?

### To Reproduce

Using config example from [rate-limiting.md](https://github.com/microsoft/reverse-proxy/blob/main/docs/docfx/articles/rate-limiting.md)

```json
"ReverseProxy": {
    "Routes": {
      "route1" : {
        "ClusterId": "cluster1",
        "Match": {
          "Hosts": ["example.pageuppeople.com"]
        },
        "RateLimiterPolicy": "disable"
      }
    },
    "Clusters": {
      "cluster1": {
        "Destinations": {
          "destination1": {
            "Address": "http://example.com/"
          }
        }
      }
```
or with in-application config:

```c#
 new RouteConfig
        {
            RouteId = routeId,
            ClusterId = clusterId,
            Match = new RouteMatch
            {
                Hosts = commaSeparatedHosts.Split(","),
            },
            RateLimiterPolicy = "Disable"
        };
```

See my draft PR [here](https://github.com/microsoft/reverse-proxy/pull/2283), I am happy to provide a minimal example if that is required

### Further technical details

- YARP 2.0.1
- Windows

**Comment by MihaZupan** [comment]
Thank you for the report, the current behavior does look wrong.

**Comment by jakebanks** [comment]
Solved by https://github.com/microsoft/reverse-proxy/pull/2283
