### ISSUE TITLE
Set request/connection time out by host

### ISSUE THREAD

**Issue by varma1035** [microsoft/reverse-proxy#2285]
Is it possible to provide connection/request timeout option at host level in cluster.
Some host may have high traffic and may be slow, It would nice if user can set timeout at host level.

**Comment by MihaZupan** [comment]
If you're using the configuration file, you can specify a different activity timeout for each cluster:
```json
"myCluster": {
  "Destinations": {
    // ...
  },
  "HttpRequest": {
    "Timeout": "00:02:00" // 2 minutes
  }
}
```

If you mean the timeout to establish new connections, you can tweak the `ConnectTimeout` property like so
```c#
services.AddReverseProxy()
    .ConfigureHttpClient((context, handler) =>
    {
        if (context.ClusterId == "slowHost")
        {
            handler.ConnectTimeout = TimeSpan.FromSeconds(42);
        }
    });
```

Does that help?

**Comment by varma1035** [comment]
@MihaZupan  Thank you for your reply.
This is very helpful.

Thanks

**Comment by karelz** [comment]
Triage: Answered, closing.
