### ISSUE TITLE
Component-specific data storage

### ISSUE THREAD

**Issue by alnikola** [microsoft/reverse-proxy#229]
There is a need for the storage where different proxy components can store data specific to their internal logic.

At the very least this storage must provide the following capabilities:
1.	Storing mutable and immutable data
2.	Fast and thread safe retrieval of an entity by key efficiently operating in a highly concurrent environment
3.	Thread safe operations to add, update and delete data entities

Optionally it should also provide:
1.	Persistent storage preserving data between proxy process restarts
2.	Data changes notifications

Examples of the storage use cases:
1.	Destination affinity key lookup table for session affinity feature
2.	Load balancing counters

See also #87

**Comment by Tratcher** [comment]
Design review: ClusterInfo.DynamicState is the current location for this, but it needs to be extensible.

This property can be replaced with a ConcurrentDictionary to store arbitrary state. If change notification is needed, an implementer may choose to store a Signal in the dictionary.

**Comment by Tratcher** [comment]
We ended up using ConditionalWeakTable for this in TransportFailureRateHealthPolicy. It seems like a good compromise for adding state to entities you don't own.

**Comment by alnikola** [comment]
@Tratcher Should we close it then if there is no actual work left?

**Comment by Tratcher** [comment]
We should check what other state should be moved to this pattern first:
- ClusterLoadBalancingOptions.RoundRobinState 
https://github.com/microsoft/reverse-proxy/blob/3344ec85f5f105e4dd323d07cc78a1bc3c3ec305/src/ReverseProxy/Service/RuntimeModel/ClusterLoadBalancingOptions.cs#L20

**Comment by samsp-msft** [comment]
We need to be able to associate the custom metadata with:
* Routes
* Clusters
* Individual destinations

For another example, see #587 where the need is to be able to associate metadata on the routes.
