### ISSUE TITLE
Feature: lifecycle management for zero downtime distributed hosting

### ISSUE THREAD

**Issue by davidni** [microsoft/reverse-proxy#23]
When running at scale, gateway instances must report their health state indicating whether an instance is willing or not to receive new traffic. See e.g. [Azure Load Balancer health probes](https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-custom-probe-overview), which would call the Gateway periodically.

It makes sense for the Reverse Proxy core to support this since this requires careful coordination of startup / teardown activities, and it also influences runtime gateway behavior. E.g during graceful shutdown, Gateway must remain serving new requests, while reporting its upcoming teardown. It must also advise clients to close existing connections by sending a `Connection: close` response header when applicable during graceful shutdown, while delaying teardown until (a) all requests are drained; **and* (b) Load Balancer has detected the instance is not eligible for new traffic.

We have implemented this in Island Gateway and I can share more details if desired.

**Comment by samsp-msft** [comment]
It seems like this has 3 parts to it:
a) Supporting graceful shutdown where clients are advised to connect to something else
b) Draining connections before actually shutting down - probably with a timeout
c) Eventing & signal model so that activating shutdown can tell the router to stop traffic, and when shutdown is complete, and the API to activate shutdown when told to by the router - assuming that app code will be listening to signals from the router.

**Comment by anurse** [comment]
The "Hosted" .NET app model (i.e. using Microsoft.Extensions.Hosting) on which ASP.NET Core is based has a graceful shutdown model and Kestrel participates in it already I believe. When shutdown is requested, Kestrel stops accepting new connections and drains existing ones (I'm not sure if it puts `Connection: close` in but that could be added). If a (configurable) timeout elapses, the server terminates more forcefully (yields back to Program.Main which will likely exit and terminate the process).

So I think we have (b) already and adding (a) is relatively straightforward.

For (c), we have the necessary event hooks ([`IApplicationLifetime.ApplicationStopping`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.hosting.iapplicationlifetime.applicationstopping?view=aspnetcore-3.1#Microsoft_AspNetCore_Hosting_IApplicationLifetime_ApplicationStopping)). I'm not sure there's a clear enough "pattern" that we could just implement in YARP though. I think custom code would be the primary way users would interact with that.

**Comment by anurse** [comment]
Triage: We do also have (a) it turns out.

Sounds like we need at least a sample (and maybe even a feature) for signalling health state based on `IApplicationLifetime`.

**Comment by samsp-msft** [comment]
See the following as a follow on from c)
#125 - Having an API for querying and understanding proxy status
#124 - REST / gRPC endpoint to expose the data from the proxy
#123 - Dashboard showing that data

**Comment by rwkarg** [comment]
We achieve the first part (not ready state when starting/stopping/stopped) of c) in our services with a health check on `IHostApplicationLifetime` that tracks the status (starting/started/stopping/stopped) and use that in the readiness check.

The second part, removing from the upstream Load Balancer (LB) before rejecting new connections, is a bit more tricky. It either needs an active call from the service (and response from the LB) to remove the instance from rotation on the LB OR some knowledge about the configuration of health checks on the LB (ex. 3 failed checks with 10 sec. check interval) to know how long we need to report as unhealthy to the LB so it will have us removed before we proceed with Stopping and rejecting new connections.

**Comment by samsp-msft** [comment]
Seems to be working for Island Gateway with a 3min shutdown for Kestrel (long duration due to gRPC streaming). 
Should look at how to gracefully shutdown inner protocols such as grpc streaming. Eg https://github.com/grpc/grpc-go/issues/2888

**Comment by karelz** [comment]
Triage: We should be able to just see it working on Island Gateway prototype.
Sample may be useful for everyone

**Comment by karelz** [comment]
Triage: Scenario which didn't need any work, unclear what to do in sample. Closing.
