### ISSUE TITLE
Understanding Routes and Backends Settings

### ISSUE THREAD

**Issue by LanceMcCarthy** [microsoft/reverse-proxy#231]
Hi Team,

Before I go into my question, I wanted to share that I did take the time to review the [Getting Started](https://microsoft.github.io/reverse-proxy/articles/getting_started.html) docs and the [reverse proxy example](https://github.com/microsoft/reverse-proxy/tree/master/samples/ReverseProxy.Sample) on GitHub. I also went through the API reference for [Backend](https://microsoft.github.io/reverse-proxy/api/Microsoft.ReverseProxy.Abstractions.Backend.html)
[ProxyRoute](https://microsoft.github.io/reverse-proxy/api/Microsoft.ReverseProxy.Abstractions.ProxyRoute.html), [ProxyMatch ](https://microsoft.github.io/reverse-proxy/api/Microsoft.ReverseProxy.Abstractions.ProxyMatch.html) (and others). 

However, I still don't know what-goes-where (partially because the demos all use 'localhost'). I think more examples are needed, this is one of those cases where API reference is not good enough. 

I have a very simple reverse proxy need. no load balancing or advanced config, just simple https traffic redirection. External traffic comes from the router and goes directly to the reverse proxy (Caddy in this case). Also, the proxy server has the SSL certs on it.

Here's that simple example that represents all of my routes, it shows two scenarios:

1. External traffic comes in for  `hassio.mydomain.com` it gets routed to `internal.hassio.mydomain.com:1234` (_DNS will resolve the internal.x IP address_)
2. External traffic comes in for `vpn.mydomain.com` it gets routed to an IP address `192.168.1.2:1234` where the vpn server is

```yaml
hassio.mydomain.com {
    reverse_proxy {
        to https://internal.hassio.mydomain.com:4567
        transport http {
            read_buffer 4096
        }
        header_up Host {http.request.host}
        header_up X-Real-IP {http.request.remote.host}
        header_up X-Forwarded-For {http.request.remote.host}
        header_up X-Forwarded-Port {http.request.port}
        header_up X-Forwarded-Proto {http.request.scheme}
        header_down Strict-Transport-Security "max-age=31536000;"
        header_down X-XSS-Protection "1; mode=block"
        header_down X-Content-Type-Options "SAMEORIGIN"
        header_down X-Frame-Options "sameorigin"
        header_down Referrer-Policy "strict-origin-when-cross-origin"
    }
}

vpn.mydomain.com {
    reverse_proxy {
        to https://192.168.1.2:1234
        transport http {
            read_buffer 4096
            tls_insecure_skip_verify
        }
        header_up Host {http.request.host}
        header_up X-Real-IP {http.request.remote.host}
        header_up X-Forwarded-For {http.request.remote.host}
        header_up X-Forwarded-Port {http.request.port}
        header_up X-Forwarded-Proto {http.request.scheme}
        header_down Strict-Transport-Security "max-age=31536000;"
        header_down X-XSS-Protection "1; mode=block"
        header_down X-Content-Type-Options "SAMEORIGIN"
        header_down X-Frame-Options "sameorigin"
        header_down Referrer-Policy "strict-origin-when-cross-origin"
    }
}
```

Here is the Yarp appsettings that I tried to use (IP and port values mocked):

```json
{
...
  "ReverseProxy": {
    "Routes": [
      {
        "RouteId": "hassio_route",
        "BackendId": "hassio_backend",
        "Match": {
          "Host": "hassio.mydomain.com"
        }
      },
      {
        "RouteId": "vpn_route",
        "BackendId": "vpn_backend",
        "Match": {
          "Host": "unifi.mydomain.com"
        }
      }
    ],
    "Backends": {
      "hassio_backend": {
        "Destinations": {
          "destination1": {
            "Address": "https://internal.hassio.mydomain.com:1234"
          }
        }
      },
      "vpn_backend": {
        "Destinations": {
          "destination1": {
            "Address": "https://192.168.1.55:1234"
          }
        }
      }
    }
  }
}
```

Do I have it backwards?

## Header Settings

I'm also having trouble with setting the header_up and header_down setting, I couldn't find any information on how I can use those in the appsettings ReverseProxy definition.

**Comment by Tratcher** [comment]
Yes, we do need more docs and samples. We'll be adding more with each milestone.

Yes, your routes and backends look correct. Was it not working for you?

As for header customizations, I'm working on that now over at https://github.com/microsoft/reverse-proxy/pull/225/files#diff-5eaf949dff24b9e8ca79381a8eb61de3. Let me know on that PR if those examples make sense to you. I think I've implemented the equivalent of everything your using above, except maybe X-Forwarded-Port which would be included with the Host.

For preview1 we hard coded it to add X-Forwarded-For, X-Forwarded-Proto, and X-Forwarded-Host for every request.
