### ISSUE TITLE
Adding query parameter with unique value per request

### ISSUE THREAD

**Issue by danielbecroft** [microsoft/reverse-proxy#2315]
I'm trying to append a request-specific query parameter to every request that is proxied. Our specific scenario here is a stop-gap to appen the `X-AppGW-Trace-Id` header as a query string to allow it to appear in plain-text logs downstream (like IIS and Tomcat logs, etc). 

I've tried the following:
```
builderContext.AddQueryValue("foo", "bar");

builderContext.AddRequestTransform(async transformContext => 
{
	var uri = transformContext.ProxyRequest.RequestUri;
	var uriBuilder = uri == null ? new UriBuilder() : new UriBuilder(uri);

	var query = QueryHelpers.ParseQuery(uriBuilder.Query);
	query.Add("fizz", "buzz");

	uriBuilder.Query = QueryString.Create(query).Value;

	transformContext.ProxyRequest.RequestUri = uriBuilder.Uri;

	transformContext.ProxyRequest.Headers.Add("X-Custom-Header", "ProxyReader.Headers.Add");
});
```

- The `foo=bar` query string is appended correctly.
- The `X-Custom-Heaer` is also added correctly on the request

But, the `fizz=buzz` query parameter does not get added.

- The `transformContext.ProxyRequest.RequestUri` value is null when it executes (not sure if it should be), so I don't have access to teh original request. I could build it up from the `transformContext.HttpContext.Request.Host` values, etc, but then it won't get proxied correctly (I'm assuming here). There are other path transforms that are occurring on the same route.

I've also tried calling `builderContext.AddQueryValue()` inside the `AddRequestTransform`, but that did nothing.

Is this possible at all (adding a query parameter value that is unique per proxied request), and if so, what tricks am I missing?

**Comment by Tratcher** [comment]
Your transforms are writing to different objects and then overwriting each other later. `transformContext.ProxyRequest.RequestUri` isn't set until after transforms run. 

Try this: `transformContext.Query.Collection["fizz"] = "buzz";`

**Comment by danielbecroft** [comment]
Thanks @Tratcher , that's resolved the issue.
