### ISSUE TITLE
Cancellation exception escapes when session affinity is enabled

### ISSUE THREAD

**Issue by minkom-ms** [microsoft/reverse-proxy#2317]
### Describe the bug
When session affinity is enabled and a request cancellation occurs, a cancellation exception escapes the forwarder.

### To Reproduce
1. Setup a cluster with session affinity enabled.
2. Make a request and drop it quickly from the client.

Expected: forwarder middleware completes gracefully
Actual: forwarder middleware throws OperationCanceledException

### Further technical details
When a client quickly disconnects after making a request, [SendAsync](https://github.com/microsoft/reverse-proxy/blob/3a5a68fac3bccbcf19e785a82497abf4b1c30053/src/ReverseProxy/Forwarder/HttpForwarder.cs#L161C20-L161C124) fails with cancellation. The code logic goes through [HandleRequestFailureAsync](https://github.com/microsoft/reverse-proxy/blob/3a5a68fac3bccbcf19e785a82497abf4b1c30053/src/ReverseProxy/Forwarder/HttpForwarder.cs#L630C1-L631C133), [ReportErrorAsync ](https://github.com/microsoft/reverse-proxy/blob/3a5a68fac3bccbcf19e785a82497abf4b1c30053/src/ReverseProxy/Forwarder/HttpForwarder.cs#L658C1-L658C95) and finally [TransformResponseAsync](https://github.com/microsoft/reverse-proxy/blob/3a5a68fac3bccbcf19e785a82497abf4b1c30053/src/ReverseProxy/Forwarder/HttpForwarder.cs#L669) with a cancellation token which is already canceled. With session affinity enabled, [AffinitizeResponse ](https://github.com/microsoft/reverse-proxy/blob/3a5a68fac3bccbcf19e785a82497abf4b1c30053/src/ReverseProxy/SessionAffinity/ISessionAffinityPolicy.cs#L68C1-L68C58) is called which throws right away because the cancellation token is already signaled.
- YARP version: 2.0.1
- .Net Core 7, Windows

**Comment by MihaZupan** [comment]
There's no point in YARP surfacing these exceptions that are happening as part of error handling already. We've already decided on the error to report which may be more specific than "cancellation".
This shouldn't be specific to session affinity, but affect any transform that reacts to cancellation by throwing, which we should expect.

We should be swallowing `OperationCancelledException`s from `TransformResponseAsync` when done as part of error handling IMO.
