### ISSUE TITLE
EnableMultipleHttp2Connections not covered in samples/docs

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#2323]
SocketsHttpHandler.EnableMultipleHttp2Connections is enabled by default by YARP for better performance in server-to-server communication. However, that's not shown in our docs/samples where a SocketsHttpHandler is manually configured. This can cause perf issues for users like https://github.com/microsoft/reverse-proxy/discussions/2282.
https://microsoft.github.io/reverse-proxy/articles/http-client-config.html
https://microsoft.github.io/reverse-proxy/articles/direct-forwarding.html
https://github.com/microsoft/reverse-proxy/blob/1d18b77fc87bd20c08ef84be1cec1294303fd32d/testassets/ReverseProxy.Direct/Startup.cs#L37
https://github.com/microsoft/reverse-proxy/blob/1d18b77fc87bd20c08ef84be1cec1294303fd32d/samples/ReverseProxy.Direct.Sample/Startup.cs#L38

**Comment by jakebanks** [comment]
Please also update it here, thanks https://microsoft.github.io/reverse-proxy/articles/http-client-config.html#custom-iforwarderhttpclientfactory
