### ISSUE TITLE
Kubernetes Ingress Controller Update Kubernetes Client to 10.x

### ISSUE THREAD

**Issue by HappyCodeSloth** [microsoft/reverse-proxy#2336]
### What should we add or change to make your life better?

Update the [Kubernetes.Controller](https://github.com/microsoft/reverse-proxy/tree/main/src/Kubernetes.Controller) to use version >= 10.0.16 && < 11.0.0 of the Kubernetes.Client.

### Why is this important to you?

I would like to use the YARP Kubernetes.Controller in conjunction with the [Microsoft.ApplicationInsights.Kubernetes](https://www.nuget.org/packages/Microsoft.ApplicationInsights.Kubernetes) package which requires version >= 10.0.16 && < 11.0.0 of the Kubernetes.Client.

**Comment by karelz** [comment]
Triage: Makes sense, we will take the PR - thanks for it! (let's continue code review on the PR)
