### ISSUE TITLE
Getting Started docs - Minimal YARP Sample 404

### ISSUE THREAD

**Issue by Eonasdan** [microsoft/reverse-proxy#2345]
The getting [started page](https://microsoft.github.io/reverse-proxy/articles/getting-started.html#create-a-new-project) links to "Minimal YARP Sample" which results in a 404 on GitHub.

**Comment by Tratcher** [comment]
Woops. I just updated all of the samples to use the minimal style so I'd deleted that sample as redundant. Need to fix the link.

**Comment by MihaZupan** [comment]
Fixed by #2367, #2379
