### ISSUE TITLE
RequestHeaderXForwardedForTransform wrongly appends existing headers with a ","

### ISSUE THREAD

**Issue by eddietisma** [microsoft/reverse-proxy#2347]
The `RequestHeaderXForwardedForTransform` wrongly appends existing headers with a `;` instead of `,`.

```
// Expected
X-Forwarded-For: existing
X-Forwarded-For: existing, proxy

// Actual
X-Forwarded-For: existing 
X-Forwarded-For: existing; proxy
```
Correct format: `X-Forwarded-For: <client>, <proxy1>, <proxy2>`
https://en.wikipedia.org/wiki/X-Forwarded-For

### To Reproduce
Add the following test cases to [RequestHeaderXForwardedForTransformTests](https://github.com/microsoft/reverse-proxy/blob/4397d054801ed7205d3dacc59f5b95b5e0be3caa/test/ReverseProxy.Tests/Transforms/RequestHeaderXForwardedForTransformTests.cs).

```
[InlineData("existing", "127.0.0.1", ForwardedTransformActions.Set, "127.0.0.1")]
[InlineData("existing", "127.0.0.1", ForwardedTransformActions.Append, "existing, 127.0.0.1")]
[InlineData("existing", "127.0.0.1", ForwardedTransformActions.Remove, "")]
```

Also these are wrong:
```
[InlineData("existing,Header", "127.0.0.1", ForwardedTransformActions.Append, "existing,Header;127.0.0.1")]
[InlineData("existing;Header", "127.0.0.1", ForwardedTransformActions.Append, "existing;Header;127.0.0.1")]
```
### Further technical details

- Version: 2.1.0
- Platform: Windows

**Comment by Tratcher** [comment]
See my comments on the PR, I think this is a misunderstanding.

**Comment by eddietisma** [comment]
Sorry, it is working as expected. My bad!
