### ISSUE TITLE
303 redirect  

### ISSUE THREAD

**Issue by SalimiHabib** [microsoft/reverse-proxy#2357]
We try to use YARP for server masking , it work fine but not for redirected resource .
we want to  be able to  show requested URL instead of forwarded URL  in address bar , also links in page must change to requested host.
for example 
we request https://aaa.com from YARP  if upstream is https://bbb.com and return 200 then no problem and we get https://aaa.com in address bar , but problem start when upstream (like word-Press) start using 303 to relocate resources .
by getting 303  YARP start for new call with URI that send to it in  location header and return new result to client by new host and new links , but it is against server masking .

how to solve this ?
do i have correct setup for server masking ?

**Comment by Tratcher** [comment]
Rewriting response content is difficult and not directly supported by YARP. See https://microsoft.github.io/reverse-proxy/articles/transforms.html#response-body-transforms

Do you control the backend app at all? It can be much easier to get them to insert the correct links by forwarding the original host as X-Forwarded-Host. See https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-8.0#forwarded-headers

**Comment by SalimiHabib** [comment]
As you said it is hard to Rewrite response .
i will go with change in upstream 
thanks for your time
