### ISSUE TITLE
Asymmetric affinity provider settings representation

### ISSUE THREAD

**Issue by alnikola** [microsoft/reverse-proxy#236]
There are currently 2 approaches to store session affinity provider settings. `CookieSessionAffinityProvider` uses the global instance `CookieSessionAffinityProviderOptions` as a source for affinity cookie parameters whereas `CustomHeaderSessionAffinityProvider` allows to define different custom affinity header names per backend in the configuration file.

It's suggested to make affinity cookie configurable per backend as well, move it to the configuration file, and get rid of the global `CookieSessionAffinityProviderOptions`.

**Comment by karelz** [comment]
Triage: We should discuss it in API design

**Comment by Tratcher** [comment]
Related: SessionAffinityOptions has its own Settings string collection that should be consolidated with the cluster metadata collection.

**Comment by samsp-msft** [comment]
Key aspect from #976 is if there are multiple independent clusters with affinity, then their cookies can stomp on each other.

**Comment by Tratcher** [comment]
Proposal: Move the global CookieSessionAffinityProviderOptions to per cluster SessionAffinityCookieConfig. While session affinity is extensible, cookies are the primary and default use case and are worth exposing on the main object model. 

Since CustomHeaderSessionAffinityProvider only has one option in the untyped Settings collection, the header name, we can try to use a shared field to store that or the cookie name.

```C#
public record SessionAffinityOptions (-> SessionAffinityConfig soon)
{
  // Identifies the name of the field where the affinity value is stored.
  // For the cookie affinity provider this will be the cookie name.
  // For the header affinity provider this will be the header name.
  // The provider will give its own default if no value is set.
  // This value should be unique across clusters to avoid affinity conflicts.
  // https://github.com/microsoft/reverse-proxy/issues/976
  public string? AffinityKeyName { get; init; }

  // Configuration used the the cookie affinity provider, if enabled.
  public SessionAffinityCookieConfig CookieConfig { get; init; }
}
// Mirrors CookieBuilder and CookieOptions
// https://github.com/dotnet/aspnetcore/blob/main/src/Http/Http.Abstractions/src/CookieBuilder.cs
public record SessionAffinityCookieConfig 
{
  public string? Path { get; init; }
  public string? Domain { get; init; }
  public bool? HttpOnly { get; init; } // Defaults to true
  public CookieSecurePolicy SecurePolicy { get; init; }
  public SameSiteMode SameSite { get; init; }
  public TimeSpan? Expiration { get; init; } // Do not set for 'browser session' behavior.
  public TimeSpan? MaxAge { get; init; } 
  public bool? IsEssential { get; init; }
}
