### ISSUE TITLE
How we can control the HttpTimeout(ForwardRequest) using config file

### ISSUE THREAD

**Issue by jayendranarumugam** [microsoft/reverse-proxy#2373]
### What should we add or change to make your life better?

I can find the property in ConfigClass (using code) that we can use [`ActivityTimeout`](https://microsoft.github.io/reverse-proxy/api/Yarp.ReverseProxy.Forwarder.ForwarderRequestConfig.html#Yarp_ReverseProxy_Forwarder_ForwarderRequestConfig_ActivityTimeout)` . But can we configure this in the config file ? 

### Why is this important to you?

Currently I have more clusters (20) and routes (40) apprx which is easy for me to handle in config files. But I want to see how can I provide or override this timeout in config file itself

**Comment by Tratcher** [comment]
See https://microsoft.github.io/reverse-proxy/articles/config-files.html
```
        "HttpRequest" : { // Options for sending request to destination
          "ActivityTimeout" : "00:02:00",
          "Version" : "2",
          "VersionPolicy" : "RequestVersionOrLower",
          "AllowResponseBuffering" : "false"
        },
```

**Comment by jayendranarumugam** [comment]
Thanks @Tratcher !
