### ISSUE TITLE
Support K8s Cert-manager

### ISSUE THREAD

**Issue by JohnGalt1717** [microsoft/reverse-proxy#2376]
### What should we add or change to make your life better?
A large portion of companies will be using cert-manager (https://cert-manager.io/) in k8s to manage certificates. These will typically get mapped to a folder in the pods.  

I'd like to see yarp explicitly be able to handle this scenario and integrate directly with cert-manager so that certificates are loaded, and reloaded when updated automatically and transparently.

### Why is this important to you?

Managing certificates is hard, and lots of environments automate this without using lets encrypt. Having an example and workflow for this will increase adoption of yarp and make it easier for companies such as ourselves to integrate with cert-manager which works well under k8s.

**Comment by benjaminpetit** [comment]
Do you want to be able to tell cert-manager to issue certificates, or do you want to only consume them via kubernetes secrets?

**Comment by davidfowl** [comment]
This should be achievable as long as Kestrel is configured with the right configuration that points to the files on disk.

**Comment by JohnGalt1717** [comment]
> This should be achievable as long as Kestrel is configured with the right configuration that points to the files on disk.

Do you have any suggestions? Haivng an example and documentation would be highly useful and I suspect would result in increased adoption given that certificates are a huge portion of what YARP is doing and under K8s this is VERY not straight forward if you aren't an expert even at the best of times, let alone having to cycle a deployment when the certs are updated.

**Comment by benjaminpetit** [comment]
Indeed, sorry I was thinking about YARP as an ingress. @davidfowl sugegstion is the easiest one to use: when you create your YARP services, mount the secret to a known location, and reference it in the config of your reverse proxy?

**Comment by karelz** [comment]
Triage: Seems to be answered. Closing.

We should create new issue to track YARP ability to swap cert on the fly from k8s secrets.
