### ISSUE TITLE
Add annotation for Methods match

### ISSUE THREAD

**Issue by witskeeper** [microsoft/reverse-proxy#2378]
### What should we add or change to make your life better?

Ingress Controller support Host, Path, Header but Methods match.

see: <https://github.com/microsoft/reverse-proxy/blob/main/src/Kubernetes.Controller/Converters/YarpParser.cs#L133>

### Why is this important to you?

add Methods match will make the functionality more comprehensive.

**Comment by MihaZupan** [comment]
Looks like a duplicate of #1828?

**Comment by adityamandaleeka** [comment]
Yup, closing this as a duplicate.
