### ISSUE TITLE
Session affinity quickly finds destination in a lookup table

### ISSUE THREAD

**Issue by alnikola** [microsoft/reverse-proxy#238]
Currently, session affinity providers do a linear search through healthy endpoint collection until they find the first destination matching the request's affinity key. This algorithm has O(n) complexity and can be improved.

It's proposed to create a dictionary mapping DestinationId to Destination, so the latter can be retrieved in O(1) time. The dictionary will be stored on a new property BackendDynamicState.HealthyDestinationsById which will be recreated right after the healthy destination list recreated in BackendInfo.CreateDynamicStateQuery() method.

P.S. It's an ad hoc implementation of a more generic storage mechanism discussed in #229

**Comment by Tratcher** [comment]
We can use this as a scenario to design #229. We shouldn't need the intermediate HealthyDestinationsById property.

**Comment by karelz** [comment]
Triage: We don't have customer signal hinting this will be needed. Closing for now. We can reopen once we have customers hitting limits and when it will show up for them on profiles.
