### ISSUE TITLE
Reverse Proxy : does not forward when the request is coming from Azure APIM

### ISSUE THREAD

**Issue by psrinivasan9128** [microsoft/reverse-proxy#2380]
### Describe the bug

I have developed a Reverse proxy using Yarp. It does some validations and then forwards. It is hosted as Docker image in k8. 

Test case

a. Tested with postman -  worked correct,  validates the headers. forwards the request.
b. Testing from APIM -  I created a API gateway in Azure which has a backend URL to this proxy host.  The Azure Apim redirection works well. I verified the logs. However the redirection fails with an error. 

### To Reproduce

**success from postman**
[40m[32minfo[39m[22m[49m: ReverseProxyManager.Api.Startup[0]
      [!dt trace_id=ca2f0c493c8860eff31ffc016b21b487,span_id=7693b69250f9dc6c,trace_sampled=true,dt.entity.host=HOST-89F7D55F49BBCDBD,dt.entity.host_group=HOST_GROUP-18F127AA6023AC8C,dt.entity.process_group_instance=PROCESS_GROUP_INSTANCE-5DF85BBE3781175F,dt.host_group.id=] Route Destination: ##<values from config> ##
[2024-01-18 19:32:12.594  INF] Proxying to ##<endpoint>##

**exception from apim**
trace_id=f3b2c4ee228014cb43649c4314b88f57,span_id=fa5e708602735e9a,trace_sampled=true,dt.entity.host=HOST-89F7D55F49BBCDBD,dt.entity.host_group=HOST_GROUP-18F127AA6023AC8C,dt.entity.process_group_instance=PROCESS_GROUP_INSTANCE-5DF85BBE3781175F,dt.host_group.id=] ##ByPassTokenAuthentication : 1 CONFIG VALUES ##
[2024-01-18 19:27:51.235  INF] RequestCreation: **An error was encountered while creating the request message.**

errors above without running the Transforms logic and forwarding my request.

### Further technical details

- Include the version of the packages you are using  - 2.1
- The platform (Linux/macOS/Windows)  - Docker - Linux

**Comment by adityamandaleeka** [comment]
Can you collect the YARP logs and see if that reveals more info? Instructions here: https://microsoft.github.io/reverse-proxy/articles/diagnosing-yarp-issues.html

**Comment by psrinivasan9128** [comment]
Thanks. Apologies , please close this.

IT is not YARP . Basically the request from APIM encodes the URL which was not done when the request was sent from postman. handling this in my .net core middleware resolved this.

**Comment by psrinivasan9128** [comment]
not an issue
