### ISSUE TITLE
How can Yet ReverseProxy implement HTTP proxy functionality like Fiddler (in https)?

### ISSUE THREAD

**Issue by sqlnew** [microsoft/reverse-proxy#2382]
Can the team help me? Thank you very much!
I want to use YetReverseProxy for HTTP forward proxy for traffic capturing or modifying traffic in systems or browsers, just like Fiddler and Titanium Web Proxy. But the example I can find is that YetReverseProxy can only use the reverse proxy function. I want to specify an HTTP proxy to access any website's URL through a browser.

Can YetReverseProxy implement this forward proxy function?

Also, I found a question from a friend who had the same problem as me:

https://github.com/microsoft/reverse-proxy/discussions/1637 .

I specify it as a proxy server in the browser, such as setting the proxy server IP port to 127.0.0.1:5000 (which can be accessed using Chrome's command-line parameter -- proxy server=127.0.0.1:5000), and then use it to access all other websites. When the browser accesses the HTTP protocol, forwarding is not a problem, but when accessing the HTTPS protocol, the target address cannot be accessed. An error message appears:

Yarp ReverseProxy Forwarder HttpForwarder [48]
RequestCreation: An error was accounted for while creating the request message
System NotSupportedException: Unsupported request method 'CONNECT'

YARP endpoint mapping all the time httpContext.Request.IsHttps comes as false.

```
            var httpClient = new HttpMessageInvoker(new SocketsHttpHandler()
            {
                UseProxy = false,
                AllowAutoRedirect = false,
                AutomaticDecompression = DecompressionMethods.None,
                UseCookies = false,
                ActivityHeadersPropagator = new ReverseProxyPropagator(DistributedContextPropagator.Current),
                ConnectTimeout = TimeSpan.FromSeconds(35),
            });

            app.Map("/{**catch-all}", async (HttpContext httpContext, IHttpForwarder forwarder) =>
            {

                //httpContext.Request.IsHttps aways is false
                var prefix = httpContext.Request.IsHttps ? "https://" : "http://";
                var destinationAddress = prefix + httpContext.Request.Host;
                var error = await forwarder.SendAsync(httpContext, destinationAddress, httpClient, requestConfig);

                if (error != ForwarderError.None)
                {
                    var errorFeature = httpContext.GetForwarderErrorFeature();
                    var exception = errorFeature.Exception;
                    //TODO: Log exception
                }
            });
```

**Comment by Tratcher** [comment]
That's not supported, forward proxies are very different technologies from reverse proxies.

**Comment by sqlnew** [comment]
@Tratcher 
First of all, thank you for your answer. This is really a pity. I always thought YetReverseProxy could have the function of forward proxies. I really hope that Microsoft and the community can develop a forward proxy server. Currently, there are too few forward proxy servers based on C # language, and there are almost no components to choose from. Thank you very much for your efforts.
