### ISSUE TITLE
Handle TCP errors and half-close on upgraded connections

### ISSUE THREAD

**Issue by davidni** [microsoft/reverse-proxy#239]
## Context
YARP is not handling all connecton teardown situations correctly, particularly when proxying an upgraded HTTP/1.1 connection. This issue is to discuss specifically the HTTP/1.1 protocol upgrade proxying path.

The diagram below illustrates the parts involved.

```
   ______                 ___________                 ______
         | --------> (A) |           | (B) --------> |      
    down |               |  Gateway  |               | up   
   ______| <-------- (D) |___________| (C) <-------- |______

```

And the table below illustrates what could possibly go wrong as well as how each condition would ideally be handled.

| # | Scenario        | Description                              | Desired TCP behavior  | socket pseudo-code        |
|:--|:----------------|:-----------------------------------------|:----------------------|:--------------------------|
| 1 | `recv(A) == -1` | Error receiving downstream request body  | Send `RST` both       | `close(up), close(down)`  |
| 2 | `send(B) == -1` | Error sending upstream request body      | Send `RST` both       | `close(down), close(up)`  |
| 3 | `recv(C) == -1` | Error receiving upstream response body   | Send `RST` both       | `close(down), close(up)`  |
| 4 | `send(D) == -1` | Error sending downstream response body   | Send `RST` both       | `close(up), close(down)`  |
| 5 | `recv(A) == 0`  | Got EOF from downstream                  | Send `FIN` up         | `shutdown(up, SHUT_WR)`   |
| 6 | `recv(C) == 0`  | Got EOF from upstream                    | Send `FIN` down       | `shutdown(down, SHUT_WR)` |

## Comments and observations
* Items 1 - 4 can be tackled easily. Detecting errors is trivial in `StreamCopier` (just catch and handle `IOException`). And we could react to that by calling `HttpContext.Abort()` on the downstream channel; and by calling `RawConnectionStream.Dispose()` on the upstream channel (`RawConnectionStream` is what we get back from HttpMessageInvoker when a connection is upgraded)
* I don't see how we can implement items 5 - 6. Half-closing either of the streams seems impossible with the current API surface exposed by .NET Core and ASP .NET Core.

## Issue
Conditions 5 and 6 are the problematic ones. Detecting them is trivial (`StreamCopier` runs to completion). But how can we react to it and half-close either stream? Not handling this could lead to deadlocks if the upgraded protocol does not handle close semantics at the application layer. E.g. WebSockets are immune to this issue because WebSockets have their own way to signal intent to close without relying on TCP `FIN`. But other upgraded protocols could conceivably require transparent proxying of `FIN` packets for correctness.

This is somewhat worrisome because of the potential for connections to remain open indefinitely without a way to make forward progress (deadlock).

Thoughts?

**Comment by halter73** [comment]
> I don't see how we can implement items 5 - 6. Half-closing either of the streams seems impossible with the current API surface exposed by .NET Core and ASP .NET Core.

Kestrel doesn't support half-closed connections. As soon as a Kestrel transport receives a TCP FIN, the transport completely closes the connection completely without any interaction from middleware. See https://github.com/dotnet/aspnetcore/issues/13188.

Until that Kestrel issue addressed (and there are no current plans to do so atm), items 5-6 are moot as far as YARP is concerned.

>  Not handling this could lead to deadlocks if the upgraded protocol does not handle close semantics at the application layer. E.g. WebSockets are immune to this issue because WebSockets have their own way to signal intent to close without relying on TCP FIN. But other upgraded protocols could conceivably require transparent proxying of FIN packets for correctness.

Do you have an example of such a protocol? If there's a common protocol that relies on half-closed upgraded connections, that could affect prioritization. So far in my experience working on ASP.NET, I haven't heard of any HTTP or WebSocket client needing support for half-closed TCP connections. This seems like it would be a more important requirement for a layer 4 proxy.

> This is somewhat worrisome because of the potential for connections to remain open indefinitely without a way to make forward progress (deadlock).

Because Kestrel transports immediately close connections entirely upon receiving a FIN, no connections should remain in a half-closed state indefinitely.

**Comment by Tratcher** [comment]
Most of the error handling should have been addressed by https://github.com/microsoft/reverse-proxy/pull/406. We'll still need to verify if the half-close scenarios are required.

**Comment by karelz** [comment]
Triage: We do not think half-close scenarios are supported in .NET stacks. Closing.
If there are concrete repros, we can reopen.
