### ISSUE TITLE
Distributed Tracing docs should also include vanilla OTel instructions/sample

### ISSUE THREAD

**Issue by andrejpk** [microsoft/reverse-proxy#2394]
### Describe the bug
[The Yarp Distributed tracing doc](https://microsoft.github.io/reverse-proxy/articles/distributed-tracing.html) assumes you are using App Insights and this hides a few necessary pieces you may not know if you are using a more vanilla OTel config. For example, you need to add HttpClientInstrumentation.

I suggest this doc augments these instructions with a more vanilla config like I have in [my example sandbox repo](https://github.com/andrejpk/yarpSimple/blob/main/YarpProxy/Program.cs)

### To Reproduce
If you follow these instructions and don't know to add the HttpClient instrumentation and configure it, you don't get client spans.

**Comment by karelz** [comment]
Triage: Sounds good, thanks for the PR!

**Comment by andrejpk** [comment]
Fixed by #2395
