### ISSUE TITLE
AddPathRemovePrefix does not work

### ISSUE THREAD

**Issue by 239573049** [microsoft/reverse-proxy#2429]
### Describe the bug
When using the default
```csharp
app.MapForwarder("/sample/anything/{id}", "https://httpbin.org", b => b.AddPathRemovePrefix("/sample"));
```
Is valid, but currently in use

```csharp
app.MapForwarder("/sample/{**catch-all}", "https://httpbin.org", b => b.AddPathRemovePrefix("/sample"));
```
I need to block all routes forwarded to the service under '/sample/' and forward them without '/sample'

### Further technical details

- Include the version of the packages you are using
- The platform (Windows)

**Comment by 239573049** [comment]
I need to remove the prefix /sample/anything when using the proxy, but the prefix cannot be removed when using /sample/{**catch-all}.

**Comment by MihaZupan** [comment]
It can, `AddPathRemovePrefix` doesn't care about the route template you specified.

Are you sure your requests are matching the correct route?
I would suggest bumping the log levels to see what is happening.
```json
"LogLevel": {
  "Default": "Debug",
  "Microsoft": "Debug",
  "Microsoft.Hosting.Lifetime": "Information"
}
```

Otherwise can you provide a full repro project that we can look at?

**Comment by 239573049** [comment]
I tried the demo and it seemed to work
