### ISSUE TITLE
Create method PickDestinationAsync in ILoadBalancingPolicy

### ISSUE THREAD

**Issue by jvsancho80** [microsoft/reverse-proxy#2447]
Create method PickDestinationAsync in ILoadBalancingPolicy. I use method ReadFromJsonAsync because I need content body to resolve destination url. In this case call method Result and this is a bad idea.

Best regards.

**Comment by Tratcher** [comment]
Reading the body to pick a destination is a routing decision, not a load balancing one. Load balancing should only be choosing between equivalent destinations and should not take the request into consideration.

Consider using direct forwarding instead:
https://microsoft.github.io/reverse-proxy/articles/direct-forwarding.html

**Comment by MihaZupan** [comment]
See also https://github.com/microsoft/reverse-proxy/issues/1345#issuecomment-957895036

**Comment by karelz** [comment]
Triage: Seems to be answered, closing. Let us know if we missed anything.
