### ISSUE TITLE
How to map forwarder with `Host`?

### ISSUE THREAD

**Issue by yukozh** [microsoft/reverse-proxy#2449]

**Comment by MihaZupan** [comment]
Can you please be a bit more specific about what you're trying to achieve?

**Comment by yukozh** [comment]
Header `Host`

**Comment by MihaZupan** [comment]
If your proxy accepts multiple host headers and you want to just copy the same host header when proxying to a single destination, you could use something like
```c#
app.MapForwarder("/{**catch-all}", "https://backend", b => b.AddOriginalHost());
```
By default, YARP will remove the original Host header, `AddOriginalHost` preserves it instead.

---

If you want to select different backend destinations based on the incoming host header, you can:
- Specify the hosts a given route will match [like so](https://microsoft.github.io/reverse-proxy/articles/config-files.html#:~:text=catch%2Dall%7D%22%2C-,%22Hosts%22%20%3A%20%5B%20%22www.aaaaa.com%22%2C%20%22www.bbbbb.com%22%5D%2C,-%7D%2C%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%22Clusters%22) when using the configuration file
- Manually select the destination when using direct forwarding
  ```c#
  app.Map("/{**catch-all}", async (HttpContext httpContext, IHttpForwarder forwarder) =>
  {
      var destination = httpContext.Request.Host.Value switch
      {
          "foo.com" => "backend.a",
          "bar.com" => "backend.b",
          _ => "backend.c",
      };
  
      var error = await forwarder.SendAsync(httpContext, $"https://{destination}", httpClient, requestOptions);
  });
  ```

**Comment by yukozh** [comment]
ty
