### ISSUE TITLE
Through the yarp proxy svn, the file name will appear 502 at noon, and no detailed errors can be seen

### ISSUE THREAD

**Issue by 239573049** [microsoft/reverse-proxy#2478]
### Describe the bug
Through the yarp proxy svn, the file name will appear 502 at noon, and no detailed errors can be seen，
![image](https://github.com/microsoft/reverse-proxy/assets/61819790/4b08becb-09da-4a2e-95c2-44183f30e142)

If I print this error, only the svn Chinese file name will trigger it, and I will still report an error when I create a yarp project without any dependencies.

### Further technical details

- Include the version of the packages you are using
- The platform (Linux/macOS/Windows)

**Comment by MihaZupan** [comment]
![image](https://github.com/microsoft/reverse-proxy/assets/25307628/c83c402e-65d4-42b8-b8c9-31b3a722e2ad)

As the error indicates, the backend server returned a header with a non-ASCII character.
That's not allowed by default, but you can opt-in to using a different encoding (e.g. UTF8) - see the [relevant documentation section here](https://microsoft.github.io/reverse-proxy/articles/http-client-config.html#:~:text=RequestHeaderEncoding%20%2D%20enables%20other%20than,ResponseHeaderEncodingSelector%20%3D%20_%20%3D%3E%20Encoding.Latin1%3B).
