### ISSUE TITLE
I would like to be able to request from yarp a list of services

### ISSUE THREAD

**Issue by thompson-tomo** [microsoft/reverse-proxy#2482]
### What should we add or change to make your life better?
With Aspire developing along nicely including making it easier for to utilise service discovery, it would be great if my YARP was providng an opt-in middleware to publish an endpoint of services registered in the proxy so that internal applications can reliable source destination information.

### Why is this important to you?
Will make it easier for client applications to obtain services registered in the proxy by name,

**Comment by MihaZupan** [comment]
Have you seen #123, #124, #1710?
Is there something missing in those proposals that you would like to see?
