### ISSUE TITLE
The custom header does not work properly when it contains Chinese characters

### ISSUE THREAD

**Issue by a34546** [microsoft/reverse-proxy#2488]
Success :
<img width="311" alt="image" src="https://github.com/microsoft/reverse-proxy/assets/26135551/c486a9e3-9bdf-4bb0-879a-1adc7996d496">

Unresponsive:
<img width="413" alt="image" src="https://github.com/microsoft/reverse-proxy/assets/26135551/446a092d-ac31-4338-bc27-071a32966cd0">

**Comment by MihaZupan** [comment]
You can check debug Kestrel logs from the proxy, but it's very likely that you are running into the fact that non-ASCII header values are not allowed by default, but you can opt-in to using a different encoding (e.g. UTF8) - see the [relevant documentation section here](https://microsoft.github.io/reverse-proxy/articles/http-client-config.html#:~:text=RequestHeaderEncoding%20%2D%20enables%20other%20than,ResponseHeaderEncodingSelector%20%3D%20_%20%3D%3E%20Encoding.Latin1%3B).

**Comment by a34546** [comment]
The configuration of using UTF8 encoding for the request header still yields the same result.
The console also has no error logs.
Please help me check if the configuration is correct.

`
{
  "Logging": {
    "LogLevel": {
      "Default": "Debug"
    }
  },
  "AllowedHosts": "*",
  "ReverseProxy": {
    "Routes": {
      "route1": {
        "ClusterId": "UserApiCluster",
        "Match": {
          "Path": "UserApi/{**catch-all}"
        }
      }
    },
    "Clusters": {
      "UserApiCluster": {
        "HttpClient": {
          "RequestHeaderEncoding": "utf-8",
          "ResponseHeaderEncoding": "utf-8"
        },
        "Destinations": {
          "Node1": {
            "Address": "http://127.0.0.1:5030"
          }
        }
      }
    }
  }
}
`

**Comment by MihaZupan** [comment]
Have you configured Kestrel to accept the headers as well (`ConfigureKestrel` sample the docs)?

**Comment by a34546** [comment]
This is my code.

![image](https://github.com/microsoft/reverse-proxy/assets/26135551/c0e6dbc9-2108-4a31-9136-ffc987405c1a)

I'm not sure if there are any missing .
Please help me check. 
Thank you

**Comment by 239573049** [comment]
![image](https://github.com/microsoft/reverse-proxy/assets/61819790/c0e4f75c-a07e-415a-8dd4-e9fffe83ba21)
You should have set it up

**Comment by MihaZupan** [comment]
Can you provide a minimal runnable repro project for this issue and/or a network capture?
Without that, we're just guessing at what the problem might be.

It is odd that the client is seeing the server as unresponsive instead of getting back an error about an invalid request.

**Comment by MihaZupan** [comment]
Closing as it's not actionable for us without more info.
Feel free to reopen if you're able to gather it
