### ISSUE TITLE
transforming hostname

### ISSUE THREAD

**Issue by bigpod98** [microsoft/reverse-proxy#249]
Hello, first of all thanks for doing this i love that you guys are doing reverse proxy in dotnet. I right bow am thinking of moving some of my personal reverse proxy needs(in my computer lab) to yarp but i have a slight problem.
The hostname keeps transforming to the destination hostname.

Basicly i want it to still say what i typed in to get to the proxy not the destination that proxy points you.
Main reason for that is i most of the time have multiple of them running from same system so they share the hostname and ip and well they each just have different ports

**Comment by Tratcher** [comment]
This is now configurable in preview 2. See https://microsoft.github.io/reverse-proxy/articles/transforms.html#requestheaderoriginalhost
You can build the library locally or wait for preview 2 to release (soon).

**Comment by bigpod98** [comment]
Thanks for quick anwser i might just try and build it localy

**Comment by bigpod98** [comment]
Thanks for quick anwser i might just try and build it localy

**Comment by bigpod98** [comment]
just leaving a bit of issue feedback. When i build the library i added the thing that is said in the article above. `"Transforms": [
          { "RequestHeaderOriginalHost": "true" }
        ]`

all i get when i enter the url is a blank white webpage and a favicon is the standard asp.net core favicon which could be from my yarp project or from the internal application im trying to proxy to since i tryed to do it to one of my web apps that i made and am running on the server

**Comment by Tratcher** [comment]
Sounds like you're hitting an error code response, what shows up in the logs and the browser f12 tools?

**Comment by bigpod98** [comment]
Console that opens up doesnt show any error and f12 tools of edge dont show much of anything realy but i could not be looking in the right place

**Comment by Tratcher** [comment]
The browser F12 networking tab should show you the request and response headers and the status code. I assume it's a 4xx or 5xx in this case, so we'd still have to go see the server logs to understand why. 
See https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1#configure-logging for turning the log levels up to Debug.

**Comment by bigpod98** [comment]
`dbug:` Microsoft.Extensions.Hosting.Internal.Host[1]
      Hosting starting
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[63]
      User profile is available. Using 'C:\Users\pajdisek\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
dbug: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[37]
      Reading data from file 'C:\Users\pajdisek\AppData\Local\ASP.NET\DataProtection-Keys\key-45f4c4a6-1818-43c9-8169-2116d9fda66a.xml'.
dbug: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[37]
      Reading data from file 'C:\Users\pajdisek\AppData\Local\ASP.NET\DataProtection-Keys\key-ca3c4105-02ed-42f8-8bb9-07b8276c84bc.xml'.
dbug: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[37]
      Reading data from file 'C:\Users\pajdisek\AppData\Local\ASP.NET\DataProtection-Keys\key-e5ad6276-5196-406e-acd1-56e892daa727.xml'.
dbug: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[18]
      Found key {45f4c4a6-1818-43c9-8169-2116d9fda66a}.
dbug: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[18]
      Found key {ca3c4105-02ed-42f8-8bb9-07b8276c84bc}.
dbug: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[18]
      Found key {e5ad6276-5196-406e-acd1-56e892daa727}.
dbug: Microsoft.AspNetCore.DataProtection.KeyManagement.DefaultKeyResolver[13]
      Considering key {45f4c4a6-1818-43c9-8169-2116d9fda66a} with expiration date 2020-07-04 16:58:08Z as default key.
dbug: Microsoft.AspNetCore.DataProtection.TypeForwardingActivator[0]
      Forwarded activator type request from Microsoft.AspNetCore.DataProtection.XmlEncryption.DpapiXmlDecryptor, Microsoft.AspNetCore.DataProtection, Version=3.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 to Microsoft.AspNetCore.DataProtection.XmlEncryption.DpapiXmlDecryptor, Microsoft.AspNetCore.DataProtection, Culture=neutral, PublicKeyToken=adb9793829ddae60
dbug: Microsoft.AspNetCore.DataProtection.XmlEncryption.DpapiXmlDecryptor[51]
      Decrypting secret element using Windows DPAPI.
dbug: Microsoft.AspNetCore.DataProtection.TypeForwardingActivator[0]
      Forwarded activator type request from Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorDescriptorDeserializer, Microsoft.AspNetCore.DataProtection, Version=3.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 to Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorDescriptorDeserializer, Microsoft.AspNetCore.DataProtection, Culture=neutral, PublicKeyToken=adb9793829ddae60
dbug: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.CngCbcAuthenticatedEncryptorFactory[4]
      Opening CNG algorithm 'AES' from provider '(null)' with chaining mode CBC.
dbug: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.CngCbcAuthenticatedEncryptorFactory[3]
      Opening CNG algorithm 'SHA256' from provider '(null)' with HMAC.
dbug: Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider[2]
      Using key {45f4c4a6-1818-43c9-8169-2116d9fda66a} as the default key.
dbug: Microsoft.AspNetCore.DataProtection.Internal.DataProtectionHostedService[65]
      Key ring with default key {45f4c4a6-1818-43c9-8169-2116d9fda66a} was loaded during application startup.
info: Microsoft.ReverseProxy.Configuration.ProxyConfigLoader[1]
      Applying proxy configs
dbug: Microsoft.ReverseProxy.Service.Management.ReverseProxyConfigManager[24]
      Destination `backend1_destination2` has been added.
dbug: Microsoft.ReverseProxy.Service.Management.ReverseProxyConfigManager[21]
      Backend `backend1` has been added.
dbug: Microsoft.ReverseProxy.Service.Management.ReverseProxyConfigManager[24]
      Destination `backend2_destination1` has been added.
dbug: Microsoft.ReverseProxy.Service.Management.ReverseProxyConfigManager[21]
      Backend `backend2` has been added.
dbug: Microsoft.ReverseProxy.Service.Management.ReverseProxyConfigManager[27]
      Route `app1` has been added.
dbug: Microsoft.ReverseProxy.Service.Management.ReverseProxyConfigManager[27]
      Route `route2` has been added.
dbug: Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer[2]
      Failed to locate the development https certificate at '(null)'.
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://[::]:80
dbug: Microsoft.AspNetCore.Hosting.Diagnostics[0]
      Loaded hosting startup assembly yarptest
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: D:\Source\CSharp\Repo\PajdisekRandomProjectCSharp\yarptest
dbug: Microsoft.Extensions.Hosting.Internal.Host[2]
      Hosting started
dbug: Microsoft.AspNetCore.Server.Kestrel[39]
      Connection id "0HM0JQNV3GPVE" accepted.
dbug: Microsoft.AspNetCore.Server.Kestrel[1]
      Connection id "0HM0JQNV3GPVE" started.
dbug: Microsoft.AspNetCore.Server.Kestrel[39]
      Connection id "0HM0JQNV3GPVF" accepted.
dbug: Microsoft.AspNetCore.Server.Kestrel[1]
      Connection id "0HM0JQNV3GPVF" started.
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://testingyarpx/ - -
dbug: Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware[0]
      Wildcard detected, all requests with hosts will be allowed.
dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1001]
      2 candidate(s) found for the request path '/'
dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1005]
      Endpoint '/ HTTP: GET' with route pattern '/' is valid for the request path '/'
dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1005]
      Endpoint 'app1' with route pattern '/{**catchall}' is valid for the request path '/'
dbug: Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware[1]
      Request matched endpoint '/ HTTP: GET'
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint '/ HTTP: GET'
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint '/ HTTP: GET'
dbug: Microsoft.AspNetCore.Server.Kestrel[9]
      Connection id "0HM0JQNV3GPVE" completed keep alive response.
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://testingyarpx/ - - - 200 0 - 76.1595ms`

![Zajeta slika](https://user-images.githubusercontent.com/6921913/85077903-9d0f8300-b1c3-11ea-836c-1f119e9a7563.PNG)

**Comment by Tratcher** [comment]
```
dbug: Microsoft.ReverseProxy.Service.Management.ReverseProxyConfigManager[24]
      Destination `backend1_destination1` has been added.
dbug: Microsoft.ReverseProxy.Service.Management.ReverseProxyConfigManager[21]
      Backend `backend1` has been added.
dbug: Microsoft.ReverseProxy.Service.Management.ReverseProxyConfigManager[27]
      Route `app1` has been added.
...
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://testingyarpx/ - -
...
dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1005]
      Endpoint '/ HTTP: GET' with route pattern '/' is valid for the request path '/'
dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1005]
      Endpoint 'app1' with route pattern '/{**catchall}' is valid for the request path '/'
dbug: Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware[1]
      Request matched endpoint '/ HTTP: GET'
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint '/ HTTP: GET'
```

Oh, you have a conflicting route defined in your app for `GET /`. Is that an MVC controller action?

**Comment by bigpod98** [comment]
as soon is i read conflicting route for `/` i knew what it was i forgot to remove the mapget in startup guess i didnt select all of it but just content

**Comment by bigpod98** [comment]
i removed that mapget and it started working fine i guess next time i should look what im doing not just go shiny new thing lets get this quicly ready so i can test it.

Thanks for help with this user error
