### ISSUE TITLE
ArgumentException: Invalid destination prefix. (Parameter 'destinationPrefix')

### ISSUE THREAD

**Issue by rubenc57** [microsoft/reverse-proxy#2492]
Hello

I get this error after upgrading my webforms project, using .NET Upgrade Assistant 

ArgumentException: Invalid destination prefix. (Parameter 'destinationPrefix')

WebApp .net framework 4.8
to
WebAppCore  .net 8.0

Yarp.ReverseProxy 2.1.0

Can someone knows why?

Greetings
Ruben

**Comment by MihaZupan** [comment]
The error indicates that the YARP configuration is incorrect - the destination wasn't configured with a proper address (e.g. it was an empty string).

Can you check that `ProxyTo` is configured correctly in your `launchSettings.json` / `appsettings.json`?
You can also print `app.Configuration["ProxyTo"]` to see what the value was set to at runtime.
