### ISSUE TITLE
Whitelisting of custom Upgrade Headers

### ISSUE THREAD

**Issue by jesterret** [microsoft/reverse-proxy#2495]
### What should we add or change to make your life better?
It would be great to get an option to configure YARP to allow whitelisting the Upgrade Header values.
Right now, the upgrade header gets [stripped](https://github.com/microsoft/reverse-proxy/blob/release/latest/docs/docfx/articles/header-guidelines.md/#upgrade), but that breaks the applications that use custom values there, for example tailscale/[headscale](https://headscale.net/reverse-proxy/#envoy). 

### Why is this important to you?
I enjoy the extensibility and flexibility of YARP, but I couldn't figure out a way to bypass this behaviour, as it's handled by forwarder directly.

**Comment by MihaZupan** [comment]
Have you tried re-adding the values in a request transform?

E.g. if the value is a known constant https://microsoft.github.io/reverse-proxy/articles/transforms.html#requestheader.

Or if it's something more dynamic, writing a custom transform along the lines of
```c#
builder.Services.AddReverseProxy()
    .AddTransforms(builder =>
    {
        builder.AddRequestTransform(context =>
        {
            // If this request is what you expect (e.g. not a regular HTTP/1.1 WebSocket request)
            if (context.HttpContext.Request.Headers.ContainsKey("Foo"))
            {
                context.ProxyRequest.Headers.Add("Upgrade", "bar");
            }

            return default;
        });
    })
```

**Comment by jesterret** [comment]
Oh, great, that seems to work!  
I did try to experiment with using transforms for that, but via config file and seems I must've done something wrong then.
Thank You! :heart:
