### ISSUE TITLE
Review host matching validation

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#25]
The RouteValidator uses a strict regex to check the host matching pattern.  I have my doubts that this level of validation is even needed. The source is developer input, not external input, and it's only used in the route matcher (HostAttribute). We should be careful about second guessing what the HostMatcherPolicy can handle. For example the regex doesn't allow IDNs (Unicode hosts). 

Preferably we'd use a validation helper provided directly by the framework so they'd be in sync.

**Comment by mifopen** [comment]
Is there any workaround for IDN support? I need to route requests based on IDN host

**Comment by Tratcher** [comment]
@mifopen IDN support should be possible, we just haven't tried it yet. Are you willing to do a little experimentation?

First we need to figure out which format the HostMatcherPolicy requires, unicode or punycode. I think it's unicode from looking at the code:
https://github.com/dotnet/aspnetcore/blob/27610b0901535ce4b71832d7f3adf708f0c689c7/src/Http/Routing/src/Matching/HostMatcherPolicy.cs#L333
https://github.com/dotnet/aspnetcore/blob/27610b0901535ce4b71832d7f3adf708f0c689c7/src/Http/Http/src/Internal/DefaultHttpRequest.cs#L122
https://github.com/dotnet/aspnetcore/blob/27610b0901535ce4b71832d7f3adf708f0c689c7/src/Http/Http.Abstractions/src/HostString.cs#L158-L162

Second, I think this regex validation needs to be removed to allow for unicode characters:
https://github.com/microsoft/reverse-proxy/blob/5291514a487f8ccb3866d94b541674c964367db8/src/ReverseProxy/Service/Config/ConfigValidator.cs#L139

**Comment by Tratcher** [comment]
#817 removed the offending regex because it was preventing hosts with ports. We still need to add some tests for IDNs, host:port, etc..

**Comment by karelz** [comment]
Triage: We need the IDN part which is still missing.
