### ISSUE TITLE
Bearer token implementation from cookie

### ISSUE THREAD

**Issue by agirgol** [microsoft/reverse-proxy#2513]
Hi, I am trying to develop a website with microservice architecture. I have a service that generates tokens and holds authorizations, and I write the tokens I produce into cookies. I am trying to take this token in Reverse Proxy and send it in the Authorization header, but I was not successful and I still get the 401 error. Where might the problem be? 
```c#
using Core.Security.Encryption;
using Core.Security.JWT;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.IdentityModel.Tokens;
using System.Net.Http.Headers;
using Yarp.ReverseProxy.Transforms;

var builder = WebApplication.CreateBuilder(args);

var tokenOptions = builder.Configuration.GetSection("TokenOptions").Get<TokenOptions>()
    ?? throw new InvalidOperationException("TokenOptions section cannot be found in configuration.");

builder.Services.AddReverseProxy()
    .LoadFromConfig(builder.Configuration.GetSection("ReverseProxy"))
    .AddTransforms(transformBuilderContext =>
    {

        if (string.Equals("default", transformBuilderContext.Route.AuthorizationPolicy))

            transformBuilderContext.AddRequestTransform(async transformContext =>
            {
                var accessToken = transformContext.HttpContext.Request.Cookies["accessToken"];
                if (!string.IsNullOrEmpty(accessToken))
                {
                    transformContext.ProxyRequest.Headers.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
                }
            });
    });

builder.Services.AddAuthentication(opt =>
{
    opt.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
})
    .AddJwtBearer(options =>
    {
        options.TokenValidationParameters = new TokenValidationParameters
        {
            ValidateIssuer = true,
            ValidateAudience = true,
            ValidateLifetime = true,
            ValidIssuer = tokenOptions.Issuer,
            ValidAudience = tokenOptions.Audience,
            ValidateIssuerSigningKey = true,
            IssuerSigningKey = SecurityKeyHelper.CreateSecurityKey(tokenOptions.SecurityKey)
        };
    });

var app = builder.Build();

app.UseAuthentication();
app.UseAuthorization();

app.MapReverseProxy();

app.Run();

**Comment by adityamandaleeka** [comment]
@agirgol Are you still hitting this issue? Looking at auth-related logs from the server might give you some hints about why you're getting the 401s.

This might be useful: https://microsoft.github.io/reverse-proxy/articles/diagnosing-yarp-issues.html

**Comment by agirgol** [comment]
Thank you for the advice, I provided the solution by adding an event to JwtBearer, I tried with addtransform but I was not successful.                                                                                                                                                                                    `using Core.Security.Encryption;
using Core.Security.JWT;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.IdentityModel.Tokens;

var builder = WebApplication.CreateBuilder(args);

var tokenOptions = builder.Configuration.GetSection("TokenOptions").Get<TokenOptions>()
    ?? throw new InvalidOperationException("TokenOptions section cannot be found in configuration.");

builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowSpecificOrigin",
        builder => builder.WithOrigins("http://localhost:3000")
                          .AllowAnyHeader()
                          .AllowAnyMethod());
});

builder.Services.AddReverseProxy()
    .LoadFromConfig(builder.Configuration.GetSection("ReverseProxy"));

builder.Services.AddAuthentication(opt =>
{
    opt.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
})
    .AddJwtBearer(options =>
    {
        options.TokenValidationParameters = new TokenValidationParameters
        {
            ValidateIssuer = true,
            ValidateAudience = true,
            ValidateLifetime = true,
            ValidIssuer = tokenOptions.Issuer,
            ValidAudience = tokenOptions.Audience,
            ValidateIssuerSigningKey = true,
            IssuerSigningKey = SecurityKeyHelper.CreateSecurityKey(tokenOptions.SecurityKey),
            ClockSkew = TimeSpan.Zero
        };
        options.Events = new JwtBearerEvents
        {
            OnMessageReceived = context =>
            {
                context.Token = context.Request.Cookies["accessToken"];
                return Task.CompletedTask;
            }
        };
    });

var app = builder.Build();

app.UseCors("AllowSpecificOrigin");

app.MapReverseProxy();

app.UseAuthentication();
app.UseAuthorization();

app.Run();
`

**Comment by pinkfloydx33** [comment]
You weren't successful with the transform, because authorization policies are applied at the start of routing, before the proxy endpoints. The inbound requests must  be authenticated _first_. Your jwt events works because that's what it's facilitating
