### ISSUE TITLE
How I can handle custom exception from RequestTransform?

### ISSUE THREAD

**Issue by devopsalexandr** [microsoft/reverse-proxy#2526]
### Describe the bug
throw new Exception() from inheritor of RequestTransform and try to catch. It is always 502 error

### Further technical details

- Iatest
- all platforms

**Comment by bretbas** [comment]
Yes, i want to know too.

**Comment by devopsalexandr** [comment]
how I can to catch this exception and handle it?

**Comment by MihaZupan** [comment]
If your logic is throwing from a `RequestTransform`, YARP will catch the exception for you and report a `ForwarderError.RequestCreation` with a 502 status code.

You can either catch the exception in your own transform logic to avoid having `TransformRequestAsync` throw in the first place, or you can react to it after the fact (see [error handling](https://microsoft.github.io/reverse-proxy/articles/middleware.html#error-handling)).

**Comment by karelz** [comment]
Triage: Seems to be answered, closing. Feel free to reopen if there is something we missed.
