### ISSUE TITLE
MaxRequestBodySize on RouteConfig class has no effect

### ISSUE THREAD

**Issue by nazirj-absa** [microsoft/reverse-proxy#2533]
### Describe the bug
The value is set in code. The RateLimiterPolicy works brilliantly.
However, we would like to limit the body request on certain endpoints.
MaxRequestBodySize - is different per route.
However, it has no effect.
Setting the value to a modest 53 bytes on a limit of 50 bytes has no effect.

```c#
RouteConfig routeItem = new RouteConfig()
{
    RouteId = $"route-{endpoint.Name}-{Random.Shared.Next()}",
    ClusterId = endpoint.ClusterId,
    Match = new RouteMatch
    {
        Path = $"/{pathPrefix}{endpoint.MatchPath}"
    },
    RateLimiterPolicy = endpoint.RateLimiterPolicy,
    MaxRequestBodySize = endpoint.MaxRequestBodySize,
    Transforms = new List<Dictionary<string, string>>() { new Dictionary<string, string> { { "PathSet", endpoint.TransformPath } } },
    AuthorizationPolicy = endpoint.AuthorizationPolicy
};
```

### To Reproduce
Use postman to perform a post or put with the json payload of:
{"val":"test","val1":"test","val2":"test11111111111111111111111111111111111111111111111111111111111"}
i.e. 101 bytes.

If the route has MaxRequestBodySize of 50 bytes - the request still returns with a 200 status.

```
        [HttpPut("UpdateItem")]
        public ActionResult UpdateItem([FromBody] JsonElement body)
        {
            return Ok($"updated - {body.ToString()}");
        }

        [HttpPost("CreateItem")]
        public ActionResult CreateItem([FromBody] JsonElement body)
        {
            return Ok($"created - {body.ToString()}");
        }
```

### Further technical details

- Include the version of the packages you are using
- The platform is Windows.
- Yarp version 2.1.0

**Comment by MihaZupan** [comment]
Setting `MaxRequestBodySize` from code does work for me.

Can you provide a minimal runnable example?

**Comment by nazirj-absa** [comment]
I confirmed this works locally in DEBUG & RELEASE.

However, when running in a container on AWS ECS, this does NOT work. I am not sure what the difference would be.

It completely ignores the max request body size limit.

The Rate Limiter works.

**Comment by nazirj-absa** [comment]
I wonder if running as an exe compared to dll has an effect?

-o /app/publish /p:UseAppHost=false

```
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
ARG BUILD_CONFIGURATION=Release

WORKDIR /src
COPY ["xxx.csproj", "xxx.Container/"]
RUN dotnet restore "./xxx.Container.csproj"

COPY . .
WORKDIR "/src/xxx.Container"

RUN dotnet build "./xx.csproj" -c $BUILD_CONFIGURATION -o /app/build
RUN dotnet publish "./xxx.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM artifacts.bcp.absa.co.za/mcr.microsoft.com/dotnet/aspnet:8.0

WORKDIR /src
ADD /xxx/root-ca.tar.gz /usr/local/share/ca-certificates
RUN apt-get update && apt-get install ca-certificates && update-ca-certificates

WORKDIR /app
COPY --from=build-env /app/publish .
EXPOSE 8080 443
ENTRYPOINT ["dotnet", "xxx.dll"]
```

**Comment by nazirj-absa** [comment]
I wonder if this has something to do with running on a kestrel server on windows vs running in ubuntu.

**Comment by MihaZupan** [comment]
Running in container/not, via dll/not, in windows/ubuntu shouldn't affect whether this option is respected or not.

I would double-check that you are using the expected code & config in your container.

**Comment by nazirj-absa** [comment]
I even hard coded the value at 300 bytes and passed in 1600 bytes, but it does not work on the container. It does work locally both debugger and via exe. 

I know my deploy and container is correct as I am passing the version back in the response header. I increment the version on every container build. I will keep digging. The request is going via ALB to Container. However, I don't think that will have an effect on the operation.

**Comment by nazirj-absa** [comment]
So, I think I found my issue.

If I log the request, I noticed the request body size check is terminated, sort off.

```
        app.MapReverseProxy(proxyPipeline =>
        {
            proxyPipeline.Use(async (context, next) =>
            {
                //await Handler(context,next); 
                await loggingService.Handler(context, next);

            });
        });
```

```
    public class HttpLoggingService
    {

        public HttpLoggingService()
        {
            
        }

        private async Task FormatRequest(HttpRequest request)
        {
            request.EnableBuffering();

            var buffer = new byte[Convert.ToInt32(request.ContentLength)];

            await request.Body.ReadAsync(buffer, 0, buffer.Length).ConfigureAwait(false);

            var body = Encoding.UTF8.GetString(buffer);

            request.Body.Seek(0, SeekOrigin.Begin);

            Console.WriteLine($"request => {body.ToString()}");
        }

        public async Task Handler(HttpContext context, Func<Task> next)
        {

            await FormatRequest(context.Request);
            await next();
        }
    }
```

**Comment by nazirj-absa** [comment]
@MihaZupan so I was able to locate the issue. See above comment as well.

If you leave the request open and execute the read after the delegate, then the max request body size IS done.
https://microsoft.github.io/reverse-proxy/articles/middleware.html#logs-and-metrics

If you the log request first, then delegate and then log response, the max request body size check is NOT executed.

I am not sure if the section "https://microsoft.github.io/reverse-proxy/articles/middleware.html#what-not-to-do-with-middleware" mean we should not attempt to read a body even thou request buffering is enabled.


https://github.com/dotnet/aspnetcore/issues/40635

https://medium.com/@luisalexandre.rodrigues/logging-http-request-and-response-in-net-web-api-268135dcb27b

**Comment by MihaZupan** [comment]
The `MaxRequestBodySize` set via YARP configuration applies to the request as it's being processed by YARP. It does not apply in any previous middleware you set during `MapReverseProxy`.
In your case, if you already read the whole body before a limit has been set, it won't be enforced later on since you're not reading from the request anymore (just from the already-buffered copy).

Logging like in your example has several problems:
1. Not all requests will have a `Content-Length` header
1. Unconditionally allocating a buffer large enough to fit the whole `Content-Length` is an easy way to DOS your server
1. A `request.Body.ReadAsync` call may return before filling the whole buffer (hence why it returns the number of bytes read)
1. Trying to read the request body right away breaks functionality like `100 Continue`s and any bidirectional protocol (e.g. WebSockets, gRPC)

I would strongly recommend you use the built-in logging instead which handles all such things for you. See https://learn.microsoft.com/aspnet/core/fundamentals/http-logging

**Comment by karelz** [comment]
Triage:
- We are improving the docs in PR https://github.com/microsoft/reverse-proxy/pull/2584
- Nothing else remains, closing.
