### ISSUE TITLE
Slow content download on requests proxied with YARP behind load balancer

### ISSUE THREAD

**Issue by jbendson** [microsoft/reverse-proxy#2541]
### Describe the bug
Slow content download on requests proxied with YARP behind load balancer. Likely this is config related but looking for some insight what may be happening here.

Here's how the issue looks in devtools:
With Load Balancer:

![with-lb](https://github.com/microsoft/reverse-proxy/assets/5824730/7c12ba8c-c5cf-45fe-8b4f-8fba9fd318c7)

Without Load Balancer:

![without-lb](https://github.com/microsoft/reverse-proxy/assets/5824730/afd08509-a5d1-4e24-9c84-15820f087123)

Details  when the issue does/does not occur:
- As shown above issue only happens when accessing through load balancer
- Response size does not have major affect. Latency is typically very close to 100ms
- Issue only happens on requests proxied by YARP. Other requests to this application that are not handled by YARP such as health endpoints do not experience the slow content download time
- Issue only happens on requests from chromium based browsers (Edge, Chrome). Firefox, Postman, etc. don't show the issue.

### To Reproduce
- Access API thru YARP setup behind load balancer using Chrome/Edge
- See slow content download in Network tab - Timing

### Further technical details

- Include the version of the packages you are using
- Platform Details: 

- YARP 2.1.0
- .NET 8
- Hosted by IIS
- Windows Server 2019 Standard
- Load Balancer: NetScaler 13.1

**Comment by adityamandaleeka** [comment]
> Issue only happens on requests from chromium based browsers (Edge, Chrome). Firefox, Postman, etc. don't show the issue.

This clue is quite interesting. It might be useful to look at whether the traffic is different somehow (e.g. HTTP/2 vs HTTP/1.1). You might find the browser dev tools to be useful for this, or perhaps something like Wireshark.

**Comment by karelz** [comment]
Triage: Not enough info to make it actionable. Closing. Feel free to reopen once there is more details.

**Comment by a35506322** [comment]
I'm having the same problem. Doesn't anyone else have a problem? ...
