### ISSUE TITLE
POST not working in IIS/Express due to IsUpgradableRequest

### ISSUE THREAD

**Issue by maeneak** [microsoft/reverse-proxy#255]
-- Admin Edit: Unrelated issue content hidden --

<details>

I'm currently unable to get Request Transforms to work on NETCore 3.1 in VS19 16.6.5.
```
    {
        "RouteId": "oh/rest",
        "BackendId": "oh",
        "Match": {
          "Host": "localhost",
          "Path": "/rest/{*remainder}"
        },
        "Transforms": [
          { "X-Forwarded": "" },
          { "RequestHeaderOriginalHost": "true" }
        ]
      }
```
From wireshark:
```
POST /rest/items/Flush2Relay_Switch1 HTTP/1.1\r\n
    Host: otherhost:8080\r\n
    Accept: application/json, text/plain, */*\r\n
    Accept-Encoding: gzip, deflate, br\r\n
    Accept-Language: en-US, en; q=0.9\r\n
    Cache-Control: no-cache\r\n
    Connection: close\r\n
     [truncated]Cookie: HIDDDEN
    Pragma: no-cache\r\n
    Referer: https://localhost:44354/paperui/index.html\r\n
    User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36 Edg/83.0.478.54\r\n
    Origin: https://localhost:44354\r\n
    sec-fetch-site: same-origin\r\n
    sec-fetch-mode: cors\r\n
    sec-fetch-dest: empty\r\n
    X-Forwarded-Proto: https\r\n
    X-Forwarded-Host: localhost:44354\r\n
    X-Forwarded-For: ::1\r\n
    Content-Length: 0\r\n
    \r\n
    [Full request URI: http://otherhost:8080/rest/items/Flush2Relay_Switch1]
    [HTTP request 1/1]
    [Response in frame: 52458]
```

The proxy is proxying correctly but the incoming request is not being modified. Is this feature still in development?

</details>

**Comment by Tratcher** [comment]
Transforms were introduced in preview2 which has not been released yet. You can either build the repo locally or wait for preview2 to release (soon).

**Comment by maeneak** [comment]
Awesome thanks mate. Also POST data is not getting proxied, is this in the pipeline as well?

**Comment by Tratcher** [comment]
POST data should already work. The request above has Content-length 0?

**Comment by maeneak** [comment]
Above is the POST packet intercepted at the destination. This is the request from the client browser.
```
 localhost:44354
:method: POST
:path: /rest/items/Flush2Relay_Switch1
:scheme: https
accept: application/json, text/plain, */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
cache-control: no-cache
content-length: 2
content-type: text/plain
cookie:HIDDEN
origin: https://localhost:44354
pragma: no-cache
referer: https://localhost:44354/paperui/index.html
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-origin
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36 Edg/83.0.478.54
ON
```

**Comment by Tratcher** [comment]
Odd, I see POSTs working fine over HTTP/1.1 and HTTP/2. Can you put together a more complete repro?

**Comment by maeneak** [comment]
Just tested with preview2 and getting the same result. I'll do some more research and report back.

**Comment by maeneak** [comment]
Even with a barebones app using postman i get no POST information through to the destination if i pass it through the proxy. I'm catching the frames with WireShark as soon as they arrive at the destination.
Direct:
```
POST /testing HTTP/1.1
Content-Type: text/plain
User-Agent: PostmanRuntime/7.24.1
Accept: */*
Postman-Token: ddee86f9-2fd7-4039-b219-bd663335bd06
Host: destination:8080
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 4
Test
```
Proxied:
```
POST /testing HTTP/1.1
Host: destination:8080
Accept: */*
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
User-Agent: PostmanRuntime/7.24.1
Postman-Token: d76ccb8f-a3aa-4caa-863c-b8bf20ec611d
Content-Length: 0

```

**Comment by Tratcher** [comment]
That config still works for me, even using postman. FYI I'm using this sample:
https://github.com/microsoft/reverse-proxy/tree/master/samples/ReverseProxy.Sample
To route to this server:
https://github.com/microsoft/reverse-proxy/tree/master/samples/SampleServer

What do the debug logs say in the proxy? I'm suspicious that some other component is consuming the request body before proxying.
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1#configure-logging

**Comment by maeneak** [comment]
Yep seems to be a problem with IISExpress. Tested with Kestrel and works as expected. Your a legend @Tratcher, keep up the good work 👍

Here's a snippet of the debug logs from IISExpress for reference.
```
Microsoft.ReverseProxy.Middleware.LoadBalancingMiddleware: Information: Operation started: ReverseProxy.PickDestination
Microsoft.ReverseProxy.Middleware.LoadBalancingMiddleware: Information: Operation ended: ReverseProxy.PickDestination, 4.1147ms, success
Microsoft.ReverseProxy.Middleware.ProxyInvokerMiddleware: Information: Operation started: ReverseProxy.Proxy
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.5\Microsoft.AspNetCore.Http.Extensions.dll'. 
Microsoft.ReverseProxy.Service.Proxy.HttpProxy: Information: Proxying to http://destination:8080/testing
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.5\System.Net.Sockets.dll'. 
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.5\System.Net.Security.dll'. 
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.5\System.Net.NameResolution.dll'. 
Microsoft.ReverseProxy.Middleware.ProxyInvokerMiddleware: Information: Operation ended: ReverseProxy.Proxy, 122.6035ms, success
```

**Comment by Tratcher** [comment]
Yup, it repros in IIS Express. I quick debug shows IsUpgradableRequest is returning true in IIS Express for mysterious reasons.
https://github.com/microsoft/reverse-proxy/blob/92bbf67c5dfca6539a7d23f7f920519f6145a166/src/ReverseProxy/Service/Proxy/HttpProxy.cs#L94

That puts it on the websocket code path which drops the request body.

Thanks for the report @maeneak, we'll get to the bottom of this.

**Comment by samsp-msft** [comment]
Is this just a problem with IIS Express, or does it affect all IIS use cases?

**Comment by Tratcher** [comment]
Both IIS and IIS Express.

I've requested a patch for AspNetCore 3.1 and a fix in 5.0. Both of those will take a little while, so I think we should mitigate this by checking the Connection: Upgrade header ourselves.

**Comment by samsp-msft** [comment]
Triage: Need a temp fix to make this work for preview 3.

**Comment by Tratcher** [comment]
Workaround: check for the `Upgrade: websocket` header. That's the most common kind of upgrade.

**Comment by Tratcher** [comment]
Here's a workaround you can do without modifying YARP. Add this in Startup anywhere before UseEndpoints, or even in the MapReverseProxy pipeline. Note this completely disables WebSocket proxying.
```
            app.Use((context, next) =>
            {
                context.Features.Set<IHttpUpgradeFeature>(null);
                return next();
            });
```
You could choose to be more selective by checking the upgrade header first.
```
            app.Use((context, next) =>
            {
                if (!string.Equals("WebSocket", context.Request.Headers[HeaderNames.Upgrade], StringComparison.OrdinalIgnoreCase))
                {
                    context.Features.Set<IHttpUpgradeFeature>(null);
                }
                return next();
            });
```

I'm going to add the same check for preview3 as a temporary mitigation.

**Comment by Tratcher** [comment]
A mitigation is in place and the underlying issue isn't going to be fixed in 5.0. Moving this to the backlog.

**Comment by Tratcher** [comment]
The HttpProxy code has been refactored a few times now and the original issue of the request body getting dropped no longer applies. The only thing IsUpgradableRequest is used for now is to force outbound requests to use HTTP/1.1 instead of the default HTTP/2.

https://github.com/microsoft/reverse-proxy/blob/6ff471c5417daa1c65ba886bd53e05f7370a2d2d/src/ReverseProxy/Service/Proxy/HttpProxy.cs#L258-L274

The WebSocket (and now SPDY) mitigation remains in place to ensure those scenarios always use 1.1 and work by default. I'm not sure if there's demand for proxying other upgrade scenarios like HTTP/2 (http h2c), they're pretty uncommon. However, since this is now only a matter of changing the request version, it's possible to customize the behavior using request transforms.

I'm closing this as addressed. We can revisit if there's additional feedback.

**Comment by rogerfar** [comment]
Sorry to revive and old thread, but was this fixed? I just tested this with a .NET 7 YARP app in IIS, routing to another .NET 7 app also hosted in IIS10. 

Still getting the same problem:
```
2023-05-04 07:56:55.803 -06:00 [INF] Request starting HTTP/2 POST https://site1/Api/Authentication/Login application/json;charset=UTF-8 80
2023-05-04 07:56:55.803 -06:00 [DBG] 2 candidate(s) found for the request path '/Api/Authentication/Login'
2023-05-04 07:56:55.803 -06:00 [DBG] Endpoint 'route-dev3-5-19-test' with route pattern '/{**catchall}' is valid for the request path '/Api/Authentication/Login'
2023-05-04 07:56:55.803 -06:00 [DBG] Endpoint 'route-catchall' with route pattern '{**catch-all}' is valid for the request path '/Api/Authentication/Login'
2023-05-04 07:56:55.803 -06:00 [DBG] Request matched endpoint 'route-dev3-5-19-test'
2023-05-04 07:56:55.803 -06:00 [INF] Executing endpoint 'route-dev3-5-19-test'
2023-05-04 07:56:55.803 -06:00 [DBG] The MaxRequestBodySize has been set to '-1'.
2023-05-04 07:56:55.803 -06:00 [INF] Proxying to http://site2/Api/Authentication/Login HTTP/2 RequestVersionOrLower no-streaming
2023-05-04 07:56:55.810 -06:00 [INF] Received HTTP/1.1 response 415.
2023-05-04 07:56:55.810 -06:00 [INF] Executed endpoint 'route-dev3-5-19-test'
2023-05-04 07:56:55.810 -06:00 [INF] Request finished HTTP/2 POST https://site1/Api/Authentication/Login application/json;charset=UTF-8 80 - **415** - - 7.0910ms
```

**Comment by Tratcher** [comment]
Comments on closed issues are not tracked, please open a new issue with the details for your scenario.
