### ISSUE TITLE
Reject Unhandled Routes  

### ISSUE THREAD

**Issue by hamidrezashahnazari** [microsoft/reverse-proxy#2564]
### What should we add or change to make your life better?
Hi there , in my Yarp project I have  a list of  Exact routes  per cluster , if there was an unhandled route which is not match I need to produce 403 Forbbiden status code instead of 404 ? what is the  best solution for this case? 
### Why is this important to you?

**Comment by benjaminpetit** [comment]
Could you add a catch all default route that would return 403?

**Comment by MihaZupan** [comment]
Closing as answered, let us know if you need more help
