### ISSUE TITLE
No Cancellation in TransformProvider

### ISSUE THREAD

**Issue by aateeque** [microsoft/reverse-proxy#2567]
Hi
This is perhaps more a question than an issue; but I am implementing an `ITransformProvider`. 

My provider makes database calls and I would like to wire up cancellation via a request `CancellationToken` - thinking being that for an aborted request, for example, we can gracefully cancel our async tasks. 

I don't see any `CancellationToken` on `TransformBuilderContext` so wondered how I would go about this? Perhaps, `TransformBuilderContext` should have a `CancellationToken` wired to the `HttpContext.RequestAborted`?

**Comment by Tratcher** [comment]
ITransformProvider isn't called per request, it's called during configuration. You shouldn't need to cancel it.
