### ISSUE TITLE
I want to reverse proxy a website and add interception for a certain API interface，Can it be achieved?

### ISSUE THREAD

**Issue by bbhxwl** [microsoft/reverse-proxy#2596]
For example, I am a reverse agent http://127.0.0.1:3000/

in the light of http://127.0.0.1:3000/testApi Interface interception, wanting to add an authorization myself. If successful, continue. If unsuccessful, return an error,.

**Comment by MihaZupan** [comment]
Have you seen https://github.com/microsoft/reverse-proxy/tree/release/latest/samples/ReverseProxy.Auth.Sample?

**Comment by karelz** [comment]
Triage: Closing as answered.
