### ISSUE TITLE
Standard header (like X-Forwarded-For) in lowercase when pointing to https site

### ISSUE THREAD

**Issue by alkampfergit** [microsoft/reverse-proxy#2611]
### Describe the bug
When I configured a destination that point to the same application but https address, the headers like X-Forwarded-For are sent lowercase like x-forwarded-for

### To Reproduce
I have a configuration perfectly working where I changed the destinations to switch from http to https. The application is residing on the same machine, bounded in ip 127.0.0.2. That application opens a port in http (8888) and an https channel in 127.0.0.2, the address xxx.codewrecks.com points to ip 127.0.0.2. When I use http://localhost:8888 everything goes just fine, when I use "https://jarvisdev.codewrecks.com/" I have problem with blazor

```json
            "jarvis-automation": {
                "Destinations": {
                    "jarvis-automation/destination1": {
                        //"Address": "http://localhost:8888/" 
						"Address": "https://jarvisdev.codewrecks.com/" 
                    }
                }
            },
```

Now I map this site in a subfolder of main site with YARP

```json
      "automation": {
        "ClusterId": "jarvis-automation",
        "AuthorizationPolicy": "JarvisProxy",
        "Match": {
          "Path": "/automation/{**catchall}"
        },
        "Transforms": [
          {
            "PathPattern": "/{**catchall}"
          }
        ]
      },
```

Everything seems to work, except that blazor part of the application is dead. We found that the culprit is that blazor does not correctly read the X-Forwarded-For header (it probably use case sensitive search ... )

When we use the http address Blazor correclty serve all the scripts in the correct http[x]://jarvisdevproxy.codewrecks.com/automation/_blazor (the automation part is present)

![image](https://github.com/user-attachments/assets/3ac38420-85d2-4118-b870-655ce37725f9)

When I use the https site I got this log, that clearly shows that the blazor application incorrectly thinks that it is served in the root path (the normalized url is wrong because it misses automation part), and this generates all sort of problems (in the root we have another app with another blazor application).

![image](https://github.com/user-attachments/assets/9370953a-693e-4a44-979b-ef807ff348a0)

To fix the problem I've added a simple middleware in asp.net core that inspect the header of the request for X-Forwarded header (see code below), and if it find them to be lowercase it will rewrite with correct casing. It transforms x-forwarded-for in X-Forwarded-For (as for http specification). Now blazor application works again, indeed the fact that yarp sent the header lowercase is the problem. I know that application should not check for headers in case sensitive way, but it seems that blazor component does it in this way.

This an image of the proxied application that received lowercase header.

![image](https://github.com/user-attachments/assets/3f3368e1-c0a5-433a-9b8e-906b2667c421)

This is the code of the middleware that fixes the problem.

```csharp
![image](https://github.com/user-attachments/assets/7c8e7beb-473d-49df-a192-dff3d16ca977)

With that middleware everything works as expected

public class FixYarpHeaderMiddleware
{
    private readonly RequestDelegate _next;

    public FixYarpHeaderMiddleware(RequestDelegate next)
    {
        _next = next;
    }

    public async Task InvokeAsync(HttpContext context)
    {
        var headersToCheck = new Dictionary<string, string>
        {
            { "x-forwarded-for", "X-Forwarded-For" },
            { "x-forwarded-host", "X-Forwarded-Host" },
            { "x-forwarded-proto", "X-Forwarded-Proto" }
        };

        foreach (var header in headersToCheck)
        {
            if (context.Request.Headers.TryGetValue(header.Key, out var value))
            {
                context.Request.Headers.Remove(header.Key);
                context.Request.Headers[header.Value] = value;
            }
        }

        await _next(context);
    }
}
```

**Comment by Tratcher** [comment]
Header names are not case sensitive in HTTP, and in HTTP/2 they're explicitly supposed to be sent as lower case. If they are case sensitive in Blazor then that's a blazor bug.

When you switch from http to https you're also probably getting switched from HTTP/1.1 to HTTP/2, causing everything to become lower case.

**Comment by alkampfergit** [comment]
The explanation make sense, absolutely I think that blazor has a bug, but actually I did not thought about HTTP/1.1 and HTTP/2 as the reason why yarp behave differently. 

Think we can close this.
