### ISSUE TITLE
Warnings after updating to 2.2.0

### ISSUE THREAD

**Issue by marekott** [microsoft/reverse-proxy#2613]
### Describe the bug
After updating `Yarp.ReverseProxy` to 2.2.0  we have suddenly started observing a lot of warnings logged, for example:

`UpgradeResponseCanceled: Copying the upgraded response body was canceled.`
`UpgradeResponseDestination: The destination reported an error when copying the upgraded response body.`
`RequestTimedOut: The request timed out before receiving a response.`
`Request: An error was encountered before receiving a response.`
`ResponseBodyCanceled: Copying the response body was canceled.`

Such logs were never observed in 2.0.1 and downgrading to it, immediately stops them. I've already created similar issue when updating to 2.1.0: https://github.com/microsoft/reverse-proxy/issues/2340. From mentioned there issues I've concluded that level of those warning was lowered to debug in 2.2.0. However they are logged as warnings.

I have two questions regarding above situation:
1. Is it expected behavior that such logs are logged as warnings?
2. Should I be concerned about those entries since their log level was raised in newer version of the package?

**Comment by MihaZupan** [comment]
As discussed in #2340, these aren't new warnings, but their log level has changed between versions.
That is, you would see these if you enabled `Info`-level logs even on 2.0.1.

The change in 2.2.0 moved several logs from `Warning` to `Debug`. From [2.2.0 preview 1 release notes](https://github.com/microsoft/reverse-proxy/releases/tag/v2.2.0-preview1):
> - Errors triggered by the client disconnecting are now logged under a `Debug` severity (#2503 by @MihaZupan).
>   - `ForwarderError.RequestCanceled`, `RequestBodyCanceled`, and `UpgradeRequestCanceled` are now logged under a new `ILogger` event with a `Debug` severity. Other errors continue to be logged under the existing event with a `Warning` severity.
>  - How errors are mapped to different `ForwarderError`s remains the same.

The errors you listed weren't moved as they're not generally triggerable by the client, but potentially indicative of issues with the backend server.

**Comment by marekott** [comment]
Ok, thanks for clarification. I will investigate those logs.
