### ISSUE TITLE
YARP keep terminating the WebSocket after around 2 minutes 

### ISSUE THREAD

**Issue by AbdallahR99** [microsoft/reverse-proxy#2615]
When I connect to the web socket through the original site, there is no problem in connecting and it lasts for a long time

But when I connect through YARP reverse proxy , this error appears after around 2 minutes: 

> UpgradeActivityTimeout: The WebSocket connection was closed after being idle longer than the Activity Timeout.
> 
> ﻿System.OperationCanceledException: The operation was canceled.
> 
> ﻿   at System.Threading.CancellationToken.ThrowOperationCanceledException()
> 
> ﻿   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
> 
> ﻿   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.ReadAsync(Memory`1 memory, CancellationToken cancellationToken)
> 
> ﻿   at Microsoft.AspNetCore.Server.IIS.Core.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
> 
> ﻿   at Yarp.ReverseProxy.Forwarder.StreamCopier.CopyAsync(Stream input, Stream output, Int64 promisedContentLength, StreamCopierTelemetry telemetry, ActivityCancellationTokenSource activityToken, Boolean autoFlush, CancellationToken cancellation)

I also noticed that yarp receive the ws calls as http 

![Screenshot 2024-09-24 091748](https://github.com/user-attachments/assets/d40df577-5fc3-4148-afbc-c578493f930a)

![image](https://github.com/user-attachments/assets/9e20201f-8adb-4176-8fc5-0985145e09bd)

**Comment by MihaZupan** [comment]
YARP uses an `ActivityTimeout` with a 100-second default on all requests.
See https://microsoft.github.io/reverse-proxy/articles/http-client-config.html#httprequest

The way to avoid it triggering for long-lived requests like WebSockets is to enable keep-alive/ping mechanisms.

**Comment by AbdallahR99** [comment]
@MihaZupan modified the `ActivityTimeout` and still facing the same issue
tried also to override the `keep-alive` in the headers and nothing changed

**Comment by MihaZupan** [comment]
You're seeing messages about `The WebSocket connection was closed after being idle longer than the Activity Timeout.` after two minutes even after increasing the timeout?

Are you able to create a small runnable repro?

Keep-Alive headers won't affect this. What I was referring to are actual periodic pings sent by the WebSocket client and/or server. E.g. if the client is using `ClientWebSocket`, you can change the [`KeepAliveInterval`](https://learn.microsoft.com/dotnet/api/system.net.websockets.clientwebsocketoptions.keepaliveinterval).

**Comment by AbdallahR99** [comment]
> You're seeing messages about The WebSocket connection was closed after being idle longer than the Activity Timeout. after two minutes even after increasing the timeout?

Yes exactly the same message 

> Are you able to create a small runnable repro?

can't it requires to set up qliksense enterprise 

> Keep-Alive headers won't affect this. What I was referring to are actual periodic pings sent by the WebSocket client and/or server. E.g. if the client is using ClientWebSocket, you can change the [KeepAliveInterval](https://learn.microsoft.com/dotnet/api/system.net.websockets.clientwebsocketoptions.keepaliveinterval).

doesn't work

**Comment by MihaZupan** [comment]
If you're seeing that message after 2 minutes after having increased the `ActivityTimeout`, my guess is that the setting change wasn't applied correctly.

Can you share how you're configuring YARP? Without any info, this isn't actionable from our side.

> doesn't work

You've enabled WebSocket pings and you're still seeing the timeout? Can you share a network capture?

**Comment by AbdallahR99** [comment]
I just ran the project now and found it working fine 

I guess it was a cache issue 

 I just tested it and commented the `"ActivityTimeout": "00:30:00",` line and tried the guest browser to avoid the cache then I faced the issue again and worked fine when I uncommented it
