### ISSUE TITLE
Path not working even if I use {**catch-all}

### ISSUE THREAD

**Issue by marenfis** [microsoft/reverse-proxy#2618]
### Describe the bug
I started exploring YARP using the documentation https://microsoft.github.io/reverse-proxy/articles/getting-started.html.
If I try the url https://localhost/test, /prod or /hugo, everything works as expected while other paths like /igor or /tryout are not working 

### To Reproduce
- Create a new .NET API project
- Install Nuget package
- Remove the code for API from program.cs (.AddControllers(), .AddEndpointsApiExplorer(), .AddSwaggerGen(), .UseSagger(), .UseSwaggerUI();
- Add Code to program.cs and add the configs to appsettings.json like described here: https://microsoft.github.io/reverse-proxy/articles/getting-started.html
- run the project and try /test --> works
- try /igor --> returns 404

### Further technical details

- .NET Core 8
- Yarp.ReverseProxy 2.2.0

**Comment by MihaZupan** [comment]
Can you share the YARP configuration you're using?
What do you see from the logs - are the requests being rejected by the proxy or by the backend service?

**Comment by marenfis** [comment]
``Here is the config I'm using (appsettings.json):
```
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
  },
  "AllowedHosts": "*",
  "ReverseProxy": {
    "Routes": {
      "route1": {
        "ClusterId": "cluster1",
        "Match": {
          "Path": "{**catch-all}"
        }
      }

    },
    "Clusters": {
      "cluster1": {
        "Destinations": {
          "destination1": {
            "Address": "https://example.com/"
          }
        }
      }
    }
  }
}
```

And the log I got:
```
info: Yarp.ReverseProxy.Forwarder.HttpForwarder[9]
      Proxying to https://example.com/igor HTTP/2 RequestVersionOrLower
info: Yarp.ReverseProxy.Forwarder.HttpForwarder[56]
      Received HTTP/1.1 response 500.

```

**Comment by MihaZupan** [comment]
What behavior were you expecting?
It seems like you've asked YARP to proxy requests as-is, and the proxy returned whatever response `example.com` returned for that path.
