### ISSUE TITLE
reverse-proxy returns status code 502

### ISSUE THREAD

**Issue by zhenlei520** [microsoft/reverse-proxy#2647]
Scenario:
Service A --> reverse-proxy --> Service C

Problem:
By capturing the packet, we found that the response information of reverse-proxy --> Service C is normal, showing 200, but reverse-proxy returns 502 to service A. We added a logging middleware to reverse-proxy.

var app = builder.Services.AddServices(builder);

app.MapReverseProxy();

app.UseMiddleware<LoggingMiddleware>();

In LoggingMiddleware, we received context.Response.StatusCode The result is 502. I don’t know what happened in the middle. How should we deal with this problem?

**Comment by zhenlei520** [comment]
Service C responds very quickly, usually within 10ms, and sometimes within 3ms. I don't know if this is related to the response speed.

**Comment by zhenlei520** [comment]
Abnormal information is found after adjusting the log level
```
ck to the client.
System.InvalidOperationException: Invalid non-ASCII or control character in header: 0x00E6
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ThrowInvalidHeaderCharacter(Char ch)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseHeaders.SetValueFast(String key, StringValues value)
   at Yarp.ReverseProxy.Forwarder.HttpTransformer.CopyResponseHeaders(HttpHeaders source, IHeaderDictionary destination)
   at Yarp.ReverseProxy.Forwarder.HttpTransformer.TransformResponseAsync(HttpContext httpContext, HttpResponseMessage proxyResponse)
   at Yarp.ReverseProxy.Transforms.Builder.StructuredTransformer.TransformResponseAsync(HttpContext httpContext, HttpResponseMessage proxyResponse, CancellationToken cancellationToken)
   at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer, CancellationToken cancellationToken)
```

**Comment by zhenlei520** [comment]
I found out that the problem was caused by the header returned by the upstream service containing unicode encoding. I asked the upstream business system to modify it, but is there any plan to support unicode in the future? Currently only ascii encoding is supported

**Comment by MihaZupan** [comment]
Non-ASCII header values are supported, but they're not allowed by default.
See https://microsoft.github.io/reverse-proxy/articles/http-client-config.html#httpclient for the relevant HttpClient and Kestrel configuration.

**Comment by zhenlei520** [comment]
> Non-ASCII header values are supported, but they're not allowed by default. See https://microsoft.github.io/reverse-proxy/articles/http-client-config.html#httpclient for the relevant HttpClient and Kestrel configuration.

Thank you very much

**Comment by zhenlei520** [comment]
@MihaZupan 

There is another question that needs to be confirmed. We have a service cluster C, which is an MVC project of the Framework. Its response time is very short. After connecting to reverse-proxy, it is found that the response time of service cluster C has become longer. Before connecting to reverse-proxy, the average response time recorded in the IIS log of service C was 3ms. After connecting to reverse-proxy, it became 8ms. I can't figure out what caused this.

**Comment by MihaZupan** [comment]
I'd check whether the requests coming from the proxy are the same as without it (same HTTP version, same headers, ...).
If they're exactly the same you could try adding telemetry on your side to track where time is being spent.

**Comment by MihaZupan** [comment]
Closing this one as it's not actionable from us at the moment. Feel free to reopen if you're able to gather more data.
