### ISSUE TITLE
Add parameters to IDestinationResolver ResolveDestinationsAsync method

### ISSUE THREAD

**Issue by ayrloong** [microsoft/reverse-proxy#2663]
I think adding a ServiceName parameter to IDestinationResolver ResolveDestinationsAsync can facilitate third-party service discovery queries

Here https://github.com/dotnet/aspire/blob/main/src/Microsoft.Extensions.ServiceDiscovery.Yarp/ServiceDiscoveryDestinationResolver.cs#L60 If we have a ServiceName parameter, we can use the Microsoft.Extensions.ServiceDiscovery package to implement a service discovery very well.

Also, I think IReadOnlyDictionary<string, DestinationConfig> destinations may not be necessary because we can find DestinationConfig in Microsoft.Extensions.ServiceDiscovery ServiceEndpointResolver

**Comment by ayrloong** [comment]
After careful consideration, we add a method to implement it. I may have a misunderstanding of the ResolveDestinationsAsync method.

**Comment by MihaZupan** [comment]
YARP doesn't know about the service name, that's a higher level concept that your configuration may be using.
In the Aspire example, it's parsed from the destination address (`var serviceName = originalUri.GetLeftPart(UriPartial.Authority);`).

You also have access to the metadata from the original `DestinationConfig` where you can store any extra information that may be relevant to your configuration.

**Comment by ayrloong** [comment]
Thanks for your reply. I have another question. Why does YARP use DestinationConfig to find the endpoint? I think it is common to add additional information to ClusterConfig to find the endpoint.

In YARP, cluster --> destination corresponds to service --> endpoint in Kubernetes.  so I think it is more appropriate to add additional information in ClusterConfig

**Comment by MihaZupan** [comment]
I suppose we could also pass the cluster info into the callback.

> In YARP, cluster --> destination corresponds to service --> endpoint in Kubernetes

If you're using it in such context, it's also more likely that you'll only have 1 destination, so you can often store the metadata there instead.

**Comment by ayrloong** [comment]
Thanks I wiil close the issue.
