### ISSUE TITLE
API for reporting health from external sources

### ISSUE THREAD

**Issue by mpetrinidev** [microsoft/reverse-proxy#267]
### What should we add or change to make your life better?

Configure a maintenance mode for cluster destinations between two dates. 

```json
  "Destinations": {
    "cluster1/destination1": {
      "Address": "https://localhost:10000/"
    },
    "cluster1/destination2": {
      "Address": "http://localhost:10010/",
      "Maintenance": {
        "From": "yyyy-MM-dd HH:mm:ss",
        "To": "yyyy-MM-dd HH:mm(+2mm):ss"
      }
    }
  }
```

In the above example, the idea is to disable forward request to `destination2` in the lapse of 2 minutes

### Why is this important to you?

We experiment with some troubles in our production environment when the applications pool being recycled using IIS. Despite swap, we lose some requests and the solution was disabled the application during some seconds until the application pool recycles.

**Comment by Tratcher** [comment]
Why not remove the destination temporarily?

Health checks may also cover this scenario, automatically disabling a destination until it responds to health probes.

**Comment by mpetrinidev** [comment]
> Why not remove the destination temporarily?

Yes, but I have to do this every day. We schedule the application pool to recycle once a day at night and not every 29 hours by default.

Maybe it makes more sense to configure a Cron expression to do this and I have to formulate the idea. 🤔

> Health checks may also cover this scenario, automatically disabling a destination until it responds to health probes.

Exactly, I saw the health options for the destinations. Maybe I'll try to seek some workaround on this using the health checks and move the responsibility of this to the destination.

**Comment by samsp-msft** [comment]
If your scenario is a forced recycling, then health checks or plugging into the health system would be ideal.

What is recycling the app pool? It would be good if that could:
* First inform a health module to drain a destination
* Have a notification/timeout when the drain is complete
* Restart
* Do a request to force a warm-up (if necessary)
* Tell the health module that the destination is now good again

Some of this can be done by just taking down the server and relying on health checks or failed requests to timeout, but having the coordination should make it seamless for end users that anything has occurred.

**Comment by samsp-msft** [comment]
Triage: Putting on the backlog as there are uglier workarounds that can be used in 1.0 (eg add/remove)

**Comment by adityamandaleeka** [comment]
Closing since this appears to be covered by #1723
