### ISSUE TITLE
Query string behaviour with PathPattern transform

### ISSUE THREAD

**Issue by jmezach** [microsoft/reverse-proxy#268]
I've been trying out the new preview and have been diving into what's possible with the new transforms feature. Essentially I'm trying to reproduce what I currently have using Ocelot but with YARP. I'm seeing some interesting behaviour with the PathPattern transform, that I couldn't find in the documentation. I'm not sure if it's a bug, or just me not understanding the feature, but here goes.

In my development environment I have setup an ASP.NET Core app targeting net5.0 that includes YARP. I also have an ASP.NET Core 3.1 app that serves as my backend service for testing. It has one API at `/api/values` which echoes the incoming headers back in the response, as well as the value of the `path` query string parameter.

For my configuration I have the following:

```json
"ReverseProxy": {
    "Routes": [
      {
        "RouteId": "realization",
        "ClusterId": "EchoService",
        "Match": {
          "Methods": [ "GET", "POST" ],
          "Path": "/realization/{**catchall}"
        },
        "Transforms": [
            { "PathSet": "/api/values" }
        ]
      },
      {
          "RouteId": "scheduling",
          "ClusterId": "EchoService",
          "Match": {
            "Methods": [ "GET", "POST" ],
            "Path": "/scheduling/{*path}"
          },
          "Transforms": [
              { "PathPattern": "/api/values" }
          ]
      }
    ],
    "Clusters": {
      "EchoService": {
        "LoadBalancing": {
          "Mode": "Random"
        },
        "Destinations": {
          "backend_destination1": {
            "Address": "https://localhost:5003/"
          }
        }
      }
    }
  },
```

If I do a request to `/realization` everything is fine and I get back the headers and no path because there is no path after /realization. But if I do a request to `/scheduling/shops/4/2019/52/versions/Actual` I see a request to `https://localhost:5003/api/values?path=shops/4/2019/52/versions/Actual` coming into the EchoService. First of all I wasn't necessarily expecting this since I couldn't find anything in the docs that it actually appends the rest as a query string parameter, although that is a nice feature to have.

However, I don't think it is passing the path correctly, because I believe it should be URL encoded at least. My EchoService currently replies with a 404 because of this I think.

### Some details

**How many backends are in your application?**

- [x] 1-2
- [ ] 3-5
- [ ] 6-10
- [ ] 10+

**How do you host your application?**

- [ ] Kubernetes
- [ ] Azure App Service
- [ ] Azure VMs
- [ ] Other Cloud Provider (please include details below)
- [x] Other Hosting model (please include details below)

### What did you think of YARP?
Great project that I'm following with some great interest.

**Comment by Tratcher** [comment]
We're re-using MVC's url template binder, I wasn't expecting unused parameters to be added to the query either. The backing field here is only supposed to represent the path so the `?` gets encoded as `%3F`, which explains why your routing broke.

> although that is a nice feature to have.

You want it do that (assuming I fix the encoding)? I'd have expected unused parameters to be dropped.

If we keep them, there's also the question of how these extra query parameters should interact with the existing query string on the request. Should they be appended? Replaced?

**Comment by samsp-msft** [comment]
Drop the extra parameters. I'd prefer to keep the capabilities here to be simple, and defer to a callback for more complex scenarios.

**Comment by jmezach** [comment]
It would be nice to have the capability of putting things into query parameters yes, but I'd rather do it explicitly rather than having this implicit behaviour. For example, I would expect this to work:

```json
      {
          "RouteId": "scheduling",
          "ClusterId": "EchoService",
          "Match": {
            "Methods": [ "GET", "POST" ],
            "Path": "/scheduling/{*remainder}"
          },
          "Transforms": [
              { "PathPattern": "/api/values?path={remainder}" }
          ]
      }
```

Interestingly this doesn't work currently. If I do this, the path query parameter is passed to the downstream service, but it doesn't get a value.

**Comment by Tratcher** [comment]
Ok, but we'd probably make a query transform a separate rule.

**Comment by jmezach** [comment]
That makes total sense. I might be able to write something up if you're willing to take a PR for this?

**Comment by Tratcher** [comment]
@jmezach I have created #269 to fix the initial issue with the path.

I don't think the same template APIs we're using will support query strings. You're welcome to experiment and let us know if you come up with a viable approach.

**Comment by Tratcher** [comment]
Closing as fixed. If you work out a way to do something similar for query's let us know.
