### ISSUE TITLE
Support for websockets - Add tests

### ISSUE THREAD

**Issue by TropicalThunder** [microsoft/reverse-proxy#273]
### What should we add or change to make your life better?

Support for proxying websocket requests to the backend and/or proxy websockets to another backend other than where the http requests go.

### Why is this important to you?

It would broaden the scope of use cases for the application.

**Comment by Tratcher** [comment]
WebSockets are already supported by default, have you tried it?

If you want them to go to a separate destination then you would assign them their own route.

**Comment by samsp-msft** [comment]
Triage: Closing as its already supported. Please re-open if you find issues.

**Comment by JensMagnus** [comment]
I'm getting

`core.b11c5824.js:1 WebSocket connection to 'wss://example.com/api/websocket' failed: Error during WebSocket handshake: 'Connection' header is missing`

Is it a YARP related issue?

**Comment by Tratcher** [comment]
That's not enough information. A decrypted network trace or Trace level server logs with Kestrel's Connection logging enabled would help debug that.
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-3.1#connection-logging

**Comment by samsp-msft** [comment]
Triage: Need to add a functional test for web sockets
