### ISSUE TITLE
Non-HTTP proxying

### ISSUE THREAD

**Issue by dasMulli** [microsoft/reverse-proxy#276]
More of a question / suggestion:

Is there any plan for making yarp work with non-http traffic? e.g. using the reverse proxy for TLS termination and then forwarding encapsulated TCP connections.

Example: Exposing AMQP endpoints in a cluster via TLS.

**Comment by samsp-msft** [comment]
No, there are not currently plans to support non-http traffic.

**Comment by Tratcher** [comment]
Alternative: Take a look at Kestrel's connection middleware. You can intercept incoming connections and add your own custom handling.
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-3.1

**Comment by dasMulli** [comment]
Thanks, was just checking.
If at some point there was a configuration abstraction for yarp it would benefit for this.. similar like Traefik 2 moved from Backends to Router, adding support for TCP routing config.
So basically one more layer of abstraction for configuration purposes.
