### ISSUE TITLE
Configuration via Code

### ISSUE THREAD

**Issue by Tornhoof** [microsoft/reverse-proxy#284]
### What should we add or change to make your life better?
At the moment the main configuration extension method looks like:
https://github.com/microsoft/reverse-proxy/blob/a3b5e1b9b03fcec8bc764b033b5c066838a8ffe9/src/ReverseProxy/Configuration/DependencyInjection/ReverseProxyServiceCollectionExtensions.cs#L45-L60
and as ``ProxyConfigOptions`` is internal
https://github.com/microsoft/reverse-proxy/blob/a3b5e1b9b03fcec8bc764b033b5c066838a8ffe9/src/ReverseProxy/Configuration/ProxyConfigOptions.cs#L10-L15
makes it sufficiently complicated to configure the proxy via code and not via configuration json settings.

May I suggest making:
- ``ProxyConfigOptions`` public
- Adding extension method  ``public static IReverseProxyBuilder Configure(this IReverseProxyBuilder builder, Action<ProxyConfigOptions> configureAction)`` to allow code based configuration, I guess that one does not need the ``ProxyConfigLoader`` config loader by default

### Why is this important to you?
- I need to change the configuration based on other settings in my appsetting, using MemoryConfigurationProvider  and keys is sufficiently error prone due to the complexity of the configuration object.

**Comment by Tratcher** [comment]
> I need to change the configuration based on other settings in my appsetting

We've designed config filters for that.
https://github.com/microsoft/reverse-proxy/blob/a3b5e1b9b03fcec8bc764b033b5c066838a8ffe9/samples/ReverseProxy.Sample/Startup.cs#L34

Can you let us know how those work for you?

We are also planning a code driven flow, see https://github.com/microsoft/reverse-proxy/issues/8.

**Comment by Tornhoof** [comment]
> We've designed config filters for that.

Ah thanks, yeah as those registered in the DI I can inject my own options there and start modifying it.

And yeah this is basically a duplicate of #8 in any case.
