### ISSUE TITLE
Configure CORS for proxy routes

### ISSUE THREAD

**Issue by Kahbazi** [microsoft/reverse-proxy#285]
### What should we add or change to make your life better?
Support adding CORS metadata for individual routes and group routes (https://github.com/microsoft/reverse-proxy/issues/164).

[CorsMiddleware](https://github.com/dotnet/aspnetcore/blob/master/src/Middleware/CORS/src/Infrastructure/CorsMiddleware.cs#L144-L173) supports three types: `IDisableCorsAttribute`, `ICorsPolicyMetadata` and `IEnableCorsAttribute`.
I suggest YARP should only supports `IDisableCorsAttribute` and  `IEnableCorsAttribute`. It would be the same as authorization that we can only set Policy name and not authentication schemes or roles.

### Why is this important to you?
I want to use YARP as a backend for a SPA and I want to check CORS before sending the request to the API Server.

**Comment by Tratcher** [comment]
Forked from https://github.com/microsoft/reverse-proxy/issues/87#issuecomment-652933954
