### ISSUE TITLE
Custom routing endpoint metadata

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#286]
Forked from https://github.com/microsoft/reverse-proxy/issues/87#issuecomment-620896307

Endpoint.Metadata is a custom collection with generic search functionality (via downcasting).
https://github.com/dotnet/aspnetcore/blob/600d5ff4978c84b42aa15a11a0fdb0dbd1cc8692/src/Http/Http.Abstractions/src/Routing/EndpointMetadataCollection.cs#L75

We need some way to add custom endpoint metadata. ProxyRoute is too low level for that, it's a raw config representation, you're not going to be able to represent complex objects like IAuthorizeData there. We likely need an event in RuntimeRouteBuilder that lets you customize the routes as we build them. You'd take some config metadata and translate it to complex objects like IAuthorizeData.
https://github.com/microsoft/reverse-proxy/blob/ea7164c689ea06343b99a30aa7feecef4eda215d/src/ReverseProxy.Core/Service/DynamicEndpoints/RuntimeRouteBuilder.cs#L51-L66

Note we've added first class auth support in #122, and CORS is proposed in #281 

What other per-endpoint route metadata is there?

**Comment by samsp-msft** [comment]
Triage: more flexible, but harder to use than just directly implementing Auth & CORS, but may be better in the long run.

**Comment by Kahbazi** [comment]
I think `MapReverseProxy` should also return `IEndpointConventionBuilder`, so the client could add metadata for all routes.

**Comment by Tratcher** [comment]
> I think `MapReverseProxy` should also return `IEndpointConventionBuilder`, so the client could add metadata for all routes.

What kind of metadata would you want to add for all routes? Hard coding authz or cors centrally?

**Comment by Kahbazi** [comment]
> Hard coding authz or cors centrally?

Yes and also any other third-party middleware that might want to use endpoint metadata.
Almost every `Map` method on `IEndpointRouteBuilder` returns `IEndpointConventionBuilder`, and I think YARP should too.
