### ISSUE TITLE
Enable TLS options to be controlled by hostname via a callback

### ISSUE THREAD

**Issue by samsp-msft** [microsoft/reverse-proxy#288]
https://github.com/dotnet/runtime/issues/31097

**Comment by karelz** [comment]
Addresed

**Comment by Tratcher** [comment]
Re-opening as this still needs to be reacted to in Kestrel.
https://github.com/dotnet/aspnetcore/issues/20981

**Comment by Tratcher** [comment]
This has now been addressed in Kestrel.
