### ISSUE TITLE
Make cancelation configurable

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#293]
Offline feedback from the StackOverflow team.

Two cancellation tokens are used when proxying requests, a short one and a long one.
https://github.com/microsoft/reverse-proxy/blob/a3b5e1b9b03fcec8bc764b033b5c066838a8ffe9/src/ReverseProxy/Middleware/ProxyInvokerMiddleware.cs#L76-L87

**The short token defaults to a 30 second timeout and is not currently configurable.** This tracks the amount of time the destination has to respond with headers (not body). It's also linked to the long token.
- This timeout should be configurable globally
- Should there be a way to override it per route or cluster?

The long token is actually the HttpContext.RequestAborted token. It's used to track the response body. This tells the destination to abort if the client disconnects.
- Does this need to be configurable in any way?
- Should there also be a timeout applied to this part of the request? Configurable at what level?
- Timeouts on the body don't work well for varying sized responses, or for streaming scenarios.
- Middleware could add its own timeouts per request by augmenting RequestAborted.

**Comment by samsp-msft** [comment]
@scalablecory, @alnikola  - why does the 30s timeout seem familiar for something baked into the networking stack?
