### ISSUE TITLE
Missing Host header

### ISSUE THREAD

**Issue by amweiss** [microsoft/reverse-proxy#295]
### Describe the bug
Using the default configuration ( `{ "RequestHeaderOriginalHost": "false" }` )for transforms, it seems like the `Host` header is missing from the outgoing requests.

This is causing issues with some of the upstream services throwing errors for invalid hosts.

If I add the transform of`{ "RequestHeaderOriginalHost": "true" }` it does correctly set it to the proxy request.

### To Reproduce

Run one of the samples or tests that have `{ "RequestHeaderOriginalHost": "false" }`.

After step 6 in `HttpProxy` inspect the `upstreamResponse.RequestMessage.Headers` and notice `Host` is missing.

### Further technical details

- Include the version of the packages you are using
1.0.0-preview.3.20330.3
- The platform (Linux/macOS/Windows)
macOS

**Comment by Tratcher** [comment]
HttpClient doesn't populated the Host header in HttpRequestMessage.Headers.Host by default, it's written directly from the Url to the network. The host used in this case would come from the destination server address in your config.
https://github.com/dotnet/runtime/blob/9715a9c2b43a9111e91c7997fc2cb838e5250969/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs#L401-L406

You'd need to capture a Wireshark/Fiddler trace to see the actual request sent to the destination.

**Comment by amweiss** [comment]
Hm, well this will take some digging then as getting TLS decryption in wireshark on mac has been problematic for me and proxyman and fiddler don't capture the request for some reason.

If I add `{"Forwarded": ""}` it no longer complains that `localhost` is an invalid host for the service but I will have to see what that does when this is also running deployed.

**Comment by amweiss** [comment]
I suspect this is related to https://github.com/kubernetes/ingress-nginx/issues/2463 and bad configuration on the upstream service. Thanks for the clarification.
