### ISSUE TITLE
Can't resolve ERR_HTTP2_INADEQUATE_TRANSPORT_SECURITY error in browser

### ISSUE THREAD

**Issue by brian2github** [microsoft/reverse-proxy#296]
I am trying to run the ReverseProxySample.  Using Chrome or Edge I am getting the ERR_HTTP2_INADEQUATE_TRANSPORT_SECURITY error in the browser.  I have not tried another browser.  I used IISCrypto tool and used its 'best practices' setting, as some internet posts say this error message is related to security ciphers, and rebooted.  Then in PowerShell I created a self-signed cert, and adjusted the appsettings.json, thinking it could be a cert issue.  I have not been able to resolve this, so I'm reaching out if anyone knows what causes this - or how to resolve it.

I am including my appsettings.json below, in case there is something dumb that I did to cause this.

This is a test of just trying to get the reverse proxy to work, so I am using google.ca as an example.

```
{
  "https_port": 443,
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "AllowedHosts": "*",
  "Kestrel": {
    "Endpoints": {
      "https": {
        "StoreLocation": "LocalMachine",
        "StoreName": "My",
        "url": "https://localhost:5001"
      }
    }
  },
  "ReverseProxy": {
    "Clusters": {
      "cluster1": {
        "LoadBalancing": {
          "Mode": "Random"
        },
        "SessionAffinity": {
          "Enabled": "true",
          "Mode": "Cookie"
        },
        "Metadata": {
          "CustomHealth": "false"
        },
        "Destinations": {
          "cluster1/destination1": {
            "Address": "https://www.google.ca/"
          }
        }
      },
      "cluster2": {
        "Endpoints": {
          "cluster2/destination1": {
            "Address": "https://www.google.ca/"
          }
        }
      }
    },
    "Routes": [
      {
        "RouteId": "route1",
        "ClusterId": "cluster1",
        "Match": {
          "Methods": [ "GET", "POST" ],
          "Host": "localhost",
          "Path": "/api/{plugin}/stuff/{*remainder}"
        },
        "Transforms": [
          { "PathPattern": "/foo/{plugin}/bar/{remainder}" }
        ]
      },
      {
        "RouteId": "route2",
        "ClusterId": "cluster1",
        "Match": {
          "Host": "localhost"
        },
        "Transforms": [
          {
            "X-Forwarded": "proto,host,for,pathbase",
            "Append": "true",
            "Prefix": "X-Forwarded-"
          },
          {
            "Forwarded": "by,host,for,proto",
            "ByFormat": "Random",
            "ForFormat": "IpAndPort"
          },
          { "ClientCert": "X-Client-Cert" },

          { "PathSet": "/apis" },
          { "PathPrefix": "/apis" },
          { "PathRemovePrefix": "/apis" },

          { "RequestHeadersCopy": "true" },
          { "RequestHeaderOriginalHost": "true" },
          {
            "RequestHeader": "foo0",
            "Append": "bar"
          },
          {
            "RequestHeader": "foo1",
            "Set": "bar, baz"
          },
          {
            "RequestHeader": "clearMe",
            "Set": ""
          },
          {
            "ResponseHeader": "foo",
            "Append": "bar",
            "When": "Always"
          },
          {
            "ResponseTrailer": "foo",
            "Append": "trailer",
            "When": "Always"
          }
        ]
      }
    ]
  }
}

```

**Comment by Tratcher** [comment]
Is this running on Win8 or 2012R2? https://github.com/dotnet/aspnetcore/issues/16811

**Comment by brian2github** [comment]
Thanks for the quick response.  Yes it is Windows 8.1.  I am trying the registry entry now to disable http2.

**Comment by Tratcher** [comment]
For Kestrel there's a config setting to turn it off.
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-3.1
```
{
  "Kestrel": {
    "Endpoints": {
      "HttpsDefaultCert": {
        "Url": "https://localhost:5001",
        "Protocols": "Http1"
      }
    }
  }
}
```

**Comment by brian2github** [comment]
The registry entry I made didn't seem to have an effect.

```
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\HTTP\Parameters]
"EnableHttp2Tls"=dword:00000000

```

  I followed the link you provided and I found one mention about disabling http2 in the appsettings.json.  I tried adding the Protocols Http1:

```
"Kestrel": {
    "Endpoints": {
      "https": {
        "StoreLocation": "LocalMachine",
        "StoreName": "My",
        "url": "https://localhost:5001",
        "Protocols": "Http1"
      }
    }
  },
  
```

and it seemed like it switched back to an earlier error I was getting about cert validation.  I can't tell if I'm making progress or not.

```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HM0USEH33CME", Request id "0HM0USEH33CME:00000001": An unhandled exception was thrown by the application.
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.

```

**Comment by Tratcher** [comment]
That's coming from your destination server. I assume you're not actually proxying to `https://www.google.ca/` as shown above, but rather to a local server using a self-signed certificate?

The APIs to override destination TLS errors aren't public yet. https://github.com/microsoft/reverse-proxy/issues/137

**Comment by brian2github** [comment]
I am using google.ca as an example, but I do want to proxy to an external service - not a local server.  Does this mean the proxy has to have the same certificate as the destination server?  Acting as a reverse proxy, I'm not using the same host name.

**Comment by Tratcher** [comment]
No, the destination just needs to have a valid certificate trusted by the local machine. google.ca should have worked.

Note your using a bunch of transforms in the sample above like `{ "RequestHeaderOriginalHost": "true" },` so you may have caused a mismatch where you connected to google.cs but tried to send the `localhost` host header.

**Comment by brian2github** [comment]
I will try to clean up the appsettings.json file, because it has a bunch of stuff from the sample that I don't need, at least at the moment.  Also I noticed the comment on the other thread about where the ignore cert validation (RemoteCertificateValidationCallback) could be injected if necessary - but as you said, google.ca _should be ok_.  Is there a way to trace the communication between the proxy and the destination?

**Comment by brian2github** [comment]
After I removed the transforms, voila!  It worked.  Thanks so much for your help, @Tratcher
