### ISSUE TITLE
Q: Can reverse-proxy act as a general proxy server?

### ISSUE THREAD

**Issue by brian2github** [microsoft/reverse-proxy#298]
I wanted to check my understanding, and confirm if this scenario is legitimate.

My understanding is the difference between a proxy and a reverse-proxy is just semantic - basically where the proxy is located related to the client and the server.

I want to point the browser (or application) to the Reverse-Proxy service via proxy configuration.  Basically like a 'Fiddler' scenario.

The browser's proxy server would point to the reverse-proxy (say, port 5001 for secure), and all the requests would go through the reverse-proxy service.  The user would type in the same URL as normal, but be sent through the Reverse-Proxy service instead.

Would this generally be expected to work?  I know that the client would need to trust the Reverse-Proxy server certificate, similar to having to trust the Fiddler 'root cert'.

Can I use the 'reverse-proxy' sample, or would there be a better sample to use for this scenario?

**Comment by Tratcher** [comment]
No, a forward proxy implements a specific protocol with features such as TLS tunneling (CONNECT). Connect and TLS tunneling is not supported by any ASP.NET Core server, so you wouldn't be able to build a full forward proxy.
