### ISSUE TITLE
Remove FluentAssertions

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#30]
This testing style and library are inconsistent with our other projects.

**Comment by Kahbazi** [comment]
Do you accept PR for this issue?

**Comment by Tratcher** [comment]
Start with one test class? Some if this will be mechanical, but another part will be about establishing the desired style for the tests. I'd also like to address the over use of Mock.

**Comment by Kahbazi** [comment]
Well I have already removed the `FluentAssertion` from all projects. I sent a PR.
