### ISSUE TITLE
LifeCycle Management: state flag when YARP is truly ready to handle requests

### ISSUE THREAD

**Issue by samsp-msft** [microsoft/reverse-proxy#306]
This is a corollary to #23, but for startup rather than shutdown.

Have an event for when YARP is up and running, and is ready for requests. This needs to be when the config is loaded, and the backends have been pinged for the destinations in the initial config.

YARP will be pinged by health checks for higher up systems, and needs to be able to respond affirmatively if its really ready to respond to requests.

**Comment by karelz** [comment]
Depends on Health checks #228

**Comment by ManickaP** [comment]
Summary from a chat with @davidni:
- Non-blocking, cheap, bool returning method that can be regularly polled.
- Only for the initial state of config. If there are new endpoints coming through config updates, they shouldn't be taken into account.
- All initially configured endpoints must be up and ready.

**Comment by Tratcher** [comment]
> * All initially configured endpoints must be up and ready.

Clarification: all initially configured endpoints must have had their state checked and reported. They don't have to be up, we just need to know if they're up.
