### ISSUE TITLE
Design review: Remove interfaces for internal types

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#309]
There's a lot of unneeded abstraction in the internal object model. E.g. IDynamicConfigBuilder is internal, implemented by only one type (DynamicConfigBuilder), and mainly used for test mocks.

The concrete types can still live in DI if needed, or else they can be new'd up directly by their consumer. E.g. the DynamicConfigBuilder is only used in the ReverseProxyConfigManager and can be new'd up there directly. The methods can be made virtual for mocking if needed.

**Comment by samsp-msft** [comment]
Triage: Needs further design to assess each interface.

**Comment by Tratcher** [comment]
These mainly exist for testing:
```
internal interface ICertificateConfigLoader
internal interface ITimer
internal interface ITimerFactory
```

`internal interface IHeaderMetadata` is used with routing. Do we need the interface? In theory we want to contribute this code to aspnetcore and this would become public.

https://github.com/microsoft/reverse-proxy/pull/886 removes the IItemManager interfaces.

Service Fabric has several internal interfaces. We'll review those later.

**Comment by Tratcher** [comment]
Moving to backlog as the major offenders have been addressed.

**Comment by Tratcher** [comment]
Closing as the SF work is moving elsewhere.
