### ISSUE TITLE
Middleware should cache ClusterInfo.Config

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#310]
ClusterInfo.Config is a Signal that retrieves a the current snapshot of configuration for a cluster.
https://github.com/microsoft/reverse-proxy/blob/3e84b854e73bce20f469b688000a526e08644073/src/ReverseProxy/Service/RuntimeModel/ClusterInfo.cs#L49

This snapshot should be read once and then cached for the remainder of the request.

Bug: Each middleware is re-reading the Signal and may end up with a different instance of the snapshot, and thus different settings.

https://github.com/microsoft/reverse-proxy/blob/3e84b854e73bce20f469b688000a526e08644073/src/ReverseProxy/Middleware/DestinationInitializerMiddleware.cs#L58
https://github.com/microsoft/reverse-proxy/blob/02c8fda74ae8787edefa545b0b8e242f8e33cf98/src/ReverseProxy/Middleware/HttpContextFeaturesExtensions.cs#L12-L14
https://github.com/microsoft/reverse-proxy/blob/3e84b854e73bce20f469b688000a526e08644073/src/ReverseProxy/Middleware/LoadBalancingMiddleware.cs#L38-L42

Fix:
- Cache both the ClusterInfo and the ClusterConfig as separate entries in the Feature collection.
- Subsequent middleware should read the cached config state, not the signal.

**Comment by davidfowl** [comment]
I would prefer if we had less features rather than more. A single feature modification at the beginning of the request.

**Comment by Tratcher** [comment]
@davidfowl https://github.com/microsoft/reverse-proxy/pull/312
https://github.com/microsoft/reverse-proxy/blob/5181ab2881a2a21fd5021b0f509b9d3594d1ce5b/src/ReverseProxy/Middleware/DestinationInitializerMiddleware.cs#L58-L60

That would mean combining the cluster config and the available destinations list. Note this is effectively public API, 3rd party middleware will be inspecting it.

It's technically possible to skip storing the ClusterInfo in the features, it's retrievable from the Endpoint.
