### ISSUE TITLE
ItemManagerBase has some inefficiencies

### ISSUE THREAD

**Issue by davidfowl** [microsoft/reverse-proxy#315]
### Describe the problem
The ItemManagerBase updates the signal when ever an item changes and that results in a recreation of the collection:

https://github.com/microsoft/reverse-proxy/blob/6fb3d3b6bbd5525755231a2e2f48cc4c77c84526/src/ReverseProxy/Service/Management/ItemManagerBase.cs#L94

This happens in response to any changes to routes, destinations and clusters. What's worse is that the entire list changes any item any item in that list changes. That will trigger a signal update per item added/removed.

**Comment by Tratcher** [comment]
Design notes: We should allow batched updates by adding APIs to the ItemManager like StartBatch and CompleteBatch. StartBatch would make an internal copy to operate on and then CompleteBatch would swap it with the live collection and fire the signal.

**Comment by davidni** [comment]
Sugg: consider making it a single method that takes a lambda and takes care of potential concurrency issues. Either by taking a lock, or with a CompareExchange loop in the end that only replaces the original if it hasn't changed since the beginning of the call. E.g.

```cs
public async Task BatchUpdate(Func<IEnumerable<T>, Task<IEnumerable<T>> func);
```

**Comment by davidfowl** [comment]
The current design is based on immutable snapshots. Maybe we should be using ImmutableArray or something similar to handle these incremental updates and returning a snapshot of that instead of creating a new list everytime.

**Comment by davidfowl** [comment]
I spent a little bit of time looking at this and it looks like we do a couple of things:
- I like the single method to detect batch changes. It pushes most of the responsibility back into the collection and it can do the triggering of the signal when needed.
- Internally, we need to store and immutable list or an immutable array or we need to something other than a `IROList<T>` (since we need to track identity in an efficient manner)

**Comment by Tratcher** [comment]
Related: #513. Since Signals were removed we might not need most of this snapshot logic. Using a ConcurrentDictionary might be sufficient.
