### ISSUE TITLE
Add Helper Methods for adding Transform at Runtime

### ISSUE THREAD

**Issue by Kahbazi** [microsoft/reverse-proxy#317]
### What should we add or change to make your life better?

Add helper methods for each `Transform`.
```csharp
public static class TransformHelper
{
    public static void AddPathPrefixTransform(this ProxyRoute proxyRoute, PathString prefix)
    {
        proxyRoute.Transforms.Add(new Dictionary<string, string>
        {
            ["PathPrefix"] = prefix,
        });
    }

    public static void AddPathRemovePrefixTransform(this ProxyRoute proxyRoute, PathString prefix)
    {
        proxyRoute.Transforms.Add(new Dictionary<string, string>
        {
            ["PathRemovePrefix"] = prefix,
        });
    }
}
```

### Why is this important to you?
This methods can be used in `IProxyConfigFilter`.

**Comment by Tratcher** [comment]
This is right in line with https://github.com/microsoft/reverse-proxy/issues/60, though a big part of that one is to let you define new custom transforms.

**Comment by samsp-msft** [comment]
If you want to contribute this - lets schedule an ad-hoc design meeting before working on the PR. Ping me to get that setup.

**Comment by Kahbazi** [comment]
@samsp-msft yeah, I would like to contribute this.

**Comment by Kahbazi** [comment]
For adding Transforms with parameters, we could either have two separate methods for each or use an Enum in input.
**1. Multiple methods** 
```csharp
public static void AddSetRequestHeaderTransform(this ProxyRoute proxyRoute, string headerName, string value)
{
    proxyRoute.Transforms.Add(new Dictionary<string, string>
    {
        ["RequestHeader"] = headerName,
        ["Set"] = value
    });
}

public static void AddAppendRequestHeaderTransform(this ProxyRoute proxyRoute, string headerName, string value)
{
    proxyRoute.Transforms.Add(new Dictionary<string, string>
    {
        ["RequestHeader"] = headerName,
        ["Append"] = value
    });
}
```

**2. Multiple parameters** 
```csharp
public static void AddSetRequestHeaderTransform(this ProxyRoute proxyRoute, string headerName, string value, TransformHeaderType transformHeaderType)
{
    var type = transformHeaderType switch
    {
        TransformHeaderType.Set => "Set",
        TransformHeaderType.Append => "Append",
        _ => throw new System.ArgumentException(nameof(transformHeaderType));
    };

    proxyRoute.Transforms.Add(new Dictionary<string, string>
    {
        ["RequestHeader"] = headerName,
        [type] = value
    });
}
```

Which one do you prefer?

**Comment by Tratcher** [comment]
I'd prefer multiple overloads (option 1), that avoids introducing more enum types that aren't widely used. Alternatively it could be a bool parameter, that's what we use for the internal implementation.
https://github.com/microsoft/reverse-proxy/blob/24c0c5a969bb025dd7a355f0b62ee4cbac96c99f/src/ReverseProxy/Service/RuntimeModel/Transforms/RequestHeaderValueTransform.cs#L18
