### ISSUE TITLE
Make cancelation configurable

### ISSUE THREAD

**Issue by samsp-msft** [microsoft/reverse-proxy#319]
[Re-filing as I screwed up and converted to a discussion when I did it in the wrong tab. Originally #293]

Offline feedback from the StackOverflow team.

Two cancellation tokens are used when proxying requests, a short one and a long one.
https://github.com/microsoft/reverse-proxy/blob/a3b5e1b9b03fcec8bc764b033b5c066838a8ffe9/src/ReverseProxy/Middleware/ProxyInvokerMiddleware.cs#L76-L87

**The short token defaults to a 30 second timeout and is not currently configurable.** This tracks the amount of time the destination has to respond with headers (not body). It's also linked to the long token.
- This timeout should be configurable globally
- Should there be a way to override it per route or cluster?

The long token is actually the HttpContext.RequestAborted token. It's used to track the response body. This tells the destination to abort if the client disconnects.
- Does this need to be configurable in any way?
- Should there also be a timeout applied to this part of the request? Configurable at what level?
- Timeouts on the body don't work well for varying sized responses, or for streaming scenarios.
- Middleware could add its own timeouts per request by augmenting RequestAborted.

**Comment by samsp-msft** [comment]
@scalablecory, @alnikola - why does the 30s timeout seem familiar for something baked into the networking stack?

**Comment by davidni** [comment]
> Should there be a way to override it per route or cluster?

Yes! :). We recently implemented configurability at the Cluster level by adding a top level property `ProxyTimeout` on `ClusterConfig`. Being able to set it per route would also be useful. Order of precedence IMHO should be RouteConfig --> ClusterConfig --> Global value.

**Comment by davidni** [comment]
Related: When retries are implemented, it will be important to further distinguish timeout per attempt, and global timeout for all attempts.

Additional reading: [Timeouts in Envoy](https://www.envoyproxy.io/docs/envoy/latest/faq/configuration/timeouts), [per_try_timeout](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-retrypolicy-per-try-timeout)

**Comment by scalablecory** [comment]
> @scalablecory, @alnikola - why does the 30s timeout seem familiar for something baked into the networking stack?

Doesn't ring any bells to me. Could you be thinking of the ~60 second Socket.Connect() timeout in Windows?

**Comment by amweiss** [comment]
Per-route would be ideal for our use cases, but per-cluster would be sufficient.

**Comment by NickCraver** [comment]
Could we start with the global timeout and potentially do the others later on? The static 30 is causing constant issues for us, especially on first request when the app behind the proxy is spinning up.

**Comment by Tratcher** [comment]
@NickCraver How about I start by bumping it to 100s to match HttpClient's traditional default?

**Comment by NickCraver** [comment]
@Tratcher that would definitely help - practically speaking we wouldn't need to adjust it for the 95% case after that. Until we can configure it, that'd be a very welcomed change! /cc @deanward81

**Comment by Tratcher** [comment]
@NickCraver ok, I'll tweak it in https://github.com/microsoft/reverse-proxy/pull/406 for preview5 since I'm about to mess with timeouts anyways.

**Comment by ManickaP** [comment]
Fixed in https://github.com/microsoft/reverse-proxy/pull/512
