### ISSUE TITLE
Header transform to rename a header

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#327]
### What should we add or change to make your life better?
@Kahbazi asked about having a request transform that could rename a header. @Kahbazi can you give an example?

Implementation wise, because header transforms are indexed by name this would need to be implemented as two transforms, a copy and a remove. There's already a remove rule that could be re-used (RequestHeaderValueTransform set to empty). A copy rule would be easy enough. In config these two rules could be set up by a single RenameHeader definition.

**Comment by Kahbazi** [comment]
In the scenario that I have in mind, both destination and proxy need to have separate authentication, and both need token in Authorization header.
Now the client sends these two tokens in different headers.
```
Authorization : proxy_token
Signature : destination_token
```
So now proxy can handle authentication with `Authorization` header and rename `Signature` to `Authorization` for the request to destination.

**Comment by Tratcher** [comment]
Interesting. If you get a 401 in that situation, how can the client tell if it was from the proxy or the destination?

Have you considered using the Proxy-Authorization header instead? Components like the JwtBearer handler can be reconfigured to use alternate headers.

**Comment by samsp-msft** [comment]
Back to the original question - **transforms for headers**. I *really* want us to have an extensibility point where you can register your own code to do transforms - otherwise we are just inventing a DSL when we have a great alternative that is performant and everybody already knows - C# (or other .net languages).
Once you start having to use multiple rules to achieve a behavior, its probably better to drop to code.

**Comment by Tratcher** [comment]
Yes #60 covers extensibility.

I expect the main criteria for config support to be how many people need a certain kind of transform.

**Comment by Kahbazi** [comment]
> Interesting. If you get a 401 in that situation, how can the client tell if it was from the proxy or the destination?

The proxy adds a header in response when it proxy a request. The absence of the header means something is wrong in the proxy level.

> Have you considered using the Proxy-Authorization header instead?

Well the proxy (Api Manager) and the destination existed separately and one day the business lead us to put the destination behind the proxy. Changing it now would be a breaking change, but it might be possible for the new services.

**Comment by Kahbazi** [comment]
Now that `RequestTransform` has access to all headers and rename header transform can be done in one transform, can we have this transform as well?

**Comment by Tratcher** [comment]
We're going to hold off on adding new transforms for a while and focus on the infrastructure to let people add their own (#60). That's number two on my list right now.

**Comment by Tratcher** [comment]
Ok, now that #60 is complete here's what the above example looks like:
```C#
                        transformBuilderContext.AddRequestTransform(async transformContext =>
                        {
                            var proxyHeaders = transformContext.ProxyRequest.Headers;
                            proxyHeaders.Remove("Authorization");
                            if (proxyHeaders.TryGetValues("Signature", out var values))
                            {
                                proxyHeaders.Remove("Signature");
                                proxyHeaders.TryAddWithoutValidation("Authorization", values);
                            }
                            return Task.CompletedTask;
                        });
```

What do you think?

**Comment by Kahbazi** [comment]
This is good. It would solve the issue.

**Comment by karelz** [comment]
Triage: Seems to be straightforward, no need to do anything special, or document it explicitly until we get more customers asking for it.
