### ISSUE TITLE
Host header transform with invalid value results in duplicate host headers

### ISSUE THREAD

**Issue by stekou** [microsoft/reverse-proxy#334]
### Bug Description
When using route transforms, if the `RequestHeader` is set to `Host` and the `set` option is set to an invalid value, such as `baz,bar`, the resulting request forwarded to the backend can have multiple `Host` headers.  However, if a valid value is specified, the behavior is correct (i.e. only one `Host` header is forwarded, with the value specified in the transform).

### Reproducing
Create a config file with a transform specifying an invalid value for the `Host` header.  My transform looks like:

```
"Transforms": [
  {
    "RequestHeader": "Host",
    "Set": "site,baz"
  },
]
```
The forwarded request will look like:

![image](https://user-images.githubusercontent.com/14203705/87769744-e6f38500-c7d2-11ea-85c0-e0197208d227.png)

**Comment by Kahbazi** [comment]
It seems like this is how Http request works on dotnet.

When you set a valid value to `Host` the `HttpRequest.Headers.Host` property is being set with that value, but when you set an invalid value, the `HttpRequest.Headers.Host` property is null, but in both scenarios host is added to headers. 

https://github.com/dotnet/runtime/blob/ba403484f48d18f0888fc3abcd0ce56a17134c07/src/libraries/System.Net.Http/src/Syste
```chsarp
m/Net/Http/SocketsHttpHandler/HttpConnection.cs#L402
if (!request.HasHeaders || request.Headers.Host == null)
{
    await WriteHostHeaderAsync(request.RequestUri, async).ConfigureAwait(false);
}
```

Here's the part when `HttpConnection` adds the url as host when ``HttpRequest.Headers.Host` is null and later adds all the other headers which include an invalid host!

**Comment by stekou** [comment]
@Kahbazi FYI iit looks like your link got line-broken in the middle.

**Comment by Tratcher** [comment]
@scalablecory

**Comment by samsp-msft** [comment]
Triage: Looks like a bug in HttpClient. Moving over to dotnet/runtime.
