### ISSUE TITLE
Create versioned docs

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#344]
### What should we add or change to make your life better?
Have different versions of the docs for different releases.

### Why is this important to you?
We're making breaking changes between releases. As part of that we try to update the docs in the same PR, but that means the docs are out of sync with the released version until the next release.

Proposal: Have two branches for the docs, one based on the current release and one based on master. https://microsoft.github.io/reverse-proxy/ should point at the current release.
Or does docfx have built in versioning?

**Comment by samsp-msft** [comment]
Lets see if we can do this in preview 4, if its a large change, we should reconsder.
