### ISSUE TITLE
Support for TLS Client Authentication on the Downstream Servers

### ISSUE THREAD

**Issue by carlos-sarmiento** [microsoft/reverse-proxy#354]
### What should we add or change to make your life better?
I would like to be able to get reverse-proxy to include a specific client certificate as part of the SSL handshake with the server it is proxying the request to. From the documentation it seems that TLS Client Auth is supported when the RP is terminating the SSL session and as a header forwarded to a server downstream (which is not using Client auth itself)

### Why is this important to you?
I have a server that is secured in part by TLS Mutual Auth. I'd like to use reverse-proxy to setup a localhost server which is capable of proxying the request of a local app that doesn't have support for TLS Mutual Auth to this protected server

**Comment by Tratcher** [comment]
This will tie into #137, see the design proposal at the bottom (https://github.com/microsoft/reverse-proxy/issues/137#issuecomment-662054047). The current theory is you'd be able to specify a client certificate per cluster. Is that enough our do you need it per destination instance?

**Comment by carlos-sarmiento** [comment]
Makes total sense for my use case, per cluster is perfect
