### ISSUE TITLE
{**catchall} catches all except for the route in controller

### ISSUE THREAD

**Issue by coderookie1994** [microsoft/reverse-proxy#370]
I'm not sure whether this scenario is my misunderstanding or expected behaviour of {**catchall}, but here is the scenario.

I have a route in my source app's controller as follows :-

    [HttpGet]
    [Route("/api/test")]
    public async Task<IActionResult> Get()
    {
        var result = await _client.GetAsync("https://localhost:5002/api/test");
        return Ok(await result.Content.ReadAsStringAsync());
    }

This is my reverse proxy setting

    "ReverseProxy": {
    "Routes": [
      {
        "RouteId": "test1",
        "ClusterId": "cluster1",
        "Match": {
          "Methods": [ "GET", "POST" ],
          "Host": "localhost",
          "Path": "/{**catchall}"
        },
        "Transforms": [
          { "PathPattern": "/api/test" }
        ]
      }
    ],
    "Clusters": {
      "cluster1": {
        "Destinations": {
          "cluster1/destination": {
            "Address": "https://localhost:5004/"
          }
        }
      }
    }

I expect all the requests to get forwarded to https://localhost:5004/api/test including request to /api/test from https://localhost:5001/api/test.

Currently /api/test returns the response from my route defined in my controller instead of the route defined in my proxy api.

**Comment by Tratcher** [comment]
`/api/test` exists in both the proxy app and the destination app? In that case this is expected. In the proxy app Startup you called something like MapControllers() which added `/api/test` to the route table. Then MapReverseProxy() added `/{**catchall}` to the route table. Routing uses the more specific match `/api/test`, all other things being equal.

See https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-3.1#route-template-precedence-and-endpoint-selection-order

I think you could override this by setting the order property (https://github.com/microsoft/reverse-proxy/pull/360) so that the proxy catch-all route is given priority.

**Comment by coderookie1994** [comment]
Hi @Tratcher, apologies for the delay, I updated my nuget package after #360 got merged. Here is my proxy configuration 
```json
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "ReverseProxy": {
    "Routes": [
      {
        "RouteId": "test1",
        "ClusterId": "cluster1",
        "Order": -1,
        "Match": {
          "Methods": [ "GET", "POST" ],
          "Host": "localhost",
          "Path": "/{**catchall}"
        },
        "Transforms": [
          { "PathPattern": "/api/test2" }
        ]
      }
    ],
    "Clusters": {
      "cluster1": {
        "Destinations": {
          "cluster1/destination": {
            "Address": "https://localhost:5004/"
          }
        }
      }
    }
  }
}
```
Here is my controller code
`

    [HttpGet]
    [Route("/test")]
    public async Task<IActionResult> Get()
    {
        var result = await _client.GetAsync("https://localhost:5002/api/test");
        return Ok(await result.Content.ReadAsStringAsync());
    }
`
As you can see in the proxy config I have set my "Order" property to -1, for it to take priority over the route in the controller i.e "/test". Even after setting the property to -1, it still hits my controller route and does not forward the request to the destination configured in the proxy config. What am I doing wrong over here ?

**Comment by Tratcher** [comment]
Are you on 3.1 or 5.0? There was a bug in catch-all routes that you might be hitting.  See https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-3.1#route-template-reference

**Comment by coderookie1994** [comment]
It's net5.0
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup> 
    <PackageReference Include="Microsoft.ReverseProxy" Version="1.0.0-preview.4.*" /> 
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>
</Project>

```

**Comment by coderookie1994** [comment]
Hi @Tratcher looks like toggling that switch to true helped. Thanks for the reference.
Closing now.

**Comment by AntonC9018** [comment]
> `/api/test` exists in both the proxy app and the destination app and the one in the proxy app is being called? In that case this is expected. In the proxy app Startup you called something like MapControllers() which added `/api/test` to the route table. Then MapReverseProxy() added `/{**catchall}` to the route table. Routing uses the more specific match `/api/test`, all other things being equal.
> 
> See https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-3.1#route-template-precedence-and-endpoint-selection-order
> 
> I think you could override this by setting the order property (#360) so that the proxy catch-all route is given priority.

I'm currently experiencing the opposite, see https://github.com/microsoft/reverse-proxy/discussions/792#discussioncomment-4119355
