### ISSUE TITLE
Session affinity scenario is broken in the sample app

### ISSUE THREAD

**Issue by alnikola** [microsoft/reverse-proxy#385]
Session affinity doesn't work in ReverseProxy.Config.Sample. It might have got broken when transformation pieces were added.

**Comment by Tratcher** [comment]
How does it fail?

**Comment by Tratcher** [comment]
Clearing the milestone so this shows up in triage.

**Comment by karelz** [comment]
Triage: Create PR to fix it and we can review what is left / removed.
