### ISSUE TITLE
[Question] Read run-time config in preview4

### ISSUE THREAD

**Issue by amweiss** [microsoft/reverse-proxy#387]
Previously you could have `IClustersRepo` injected into code to do a run-time inspection of the clusters. With preview4, that's no longer available. I can't find a good way to recreate this now.

`context.Features.Get<IReverseProxyFeature>()` seems like it could provide a single instance matching the request, but not the overall config.

The goal was to do a manual inspection at runtime of the cluster info via an endpoint that returned the config loaded from a file. Is there a way to do this I'm missing or is that no longer supported?

**Comment by Tratcher** [comment]
You could resolve the IProxyConfigProvider from DI and read the config that way.

**Comment by amweiss** [comment]
Yep, that does it, thanks!
