### ISSUE TITLE
Unhandled error happens shows when source server connection refuses

### ISSUE THREAD

**Issue by ahadrt** [microsoft/reverse-proxy#392]
### It is better to design a mechanism to handle source connection refuse
I am trying to use this **nice library** to handle both python and node server behind the asp.net core which we needed. Problem is that when behind server is not running asp.net web server which uses proxy shows unhandled error. In this case we need to wait for a while ( adjustable timeout) and try some times and handle a particular error instead of this error.
### the settings is

``` c#
  public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers();
            services.AddReverseProxy()
       .LoadFromConfig(Configuration.GetSection("ReverseProxy"));
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseHttpsRedirection();

            app.UseRouting();

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapGet("oops", cnt =>
                {
                    return cnt.Response.WriteAsync("secret");
                });
              
                endpoints.MapControllers();
                endpoints.MapReverseProxy();
            });
        }
    }

```

And appsettings.json is just like this:

``` JSON

{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "AllowedHosts": "*",
  "ReverseProxy": {
    "Routes": [
      {
        "RouteId": "route1",
        "ClusterId": "cluster1",
        "Match": {
          "Path": "{**catch-all}"
        }
      }
    ],
    "Clusters": {
      "cluster1": {
        "Destinations": {
          "cluster1/destination1": {
            "Address": "http://localhost:5000"
          }
        }
      }
    }
  }
}

```

## The Error page says

<img width="1201" alt="Screen Shot 2020-09-02 at 04 46 58" src="https://user-images.githubusercontent.com/2572195/91918233-9d55ef80-ecd7-11ea-81fb-a297fe1d36d3.png">

### Further technical details
- proxy web server is kestrel (launch in visual studio for mac in develop mode)
- Tested .net core is v 3.1
- The platform used is MacOS Catalina 10.15.6
- Behind server is Python v3.8 and flesk web server

## Is there any feature for handle and control the state of reversing? or this is short come and is on the road map?

**Comment by Tratcher** [comment]
I'm working on error handling right now with https://github.com/microsoft/reverse-proxy/issues/138. These will be converted to 502s.

Retry will come later.

**Comment by ahadrt** [comment]
Thank you very much for your rapid answer. We will wait the update. when will be updated do you estimate?

**Comment by Tratcher** [comment]
I should make progress on #138 by the end of next week. Subscribe to that issue for updates.

**Comment by ahadrt** [comment]
shure thing
