### ISSUE TITLE
Remove '*Options' suffixes from 'Abstractions.Cluster' properties

### ISSUE THREAD

**Issue by alnikola** [microsoft/reverse-proxy#396]
There are inconsistently used '*Options' suffixes on [Cluster properties](https://github.com/microsoft/reverse-proxy/blob/master/src/ReverseProxy/Abstractions/ClusterDiscovery/Contract/Cluster.cs#L26). It's suggested to remove them.

**Comment by karelz** [comment]
Triage: Yes, we should do it.
