### ISSUE TITLE
My 3 questions

### ISSUE THREAD

**Issue by kasini3000** [microsoft/reverse-proxy#398]
Is msrp software only for asp.net users?
I think it can only be started from the asp.net project now.

can start msrp from the command line?

Will it provide the command line to load the listener, cluster, and endpoint parameters?
Even more complex commands?

### Some details

**How many backends are in your application?**

- [ ] 10+

**How do you host your application?**

- [ ] Other Hosting model (please include details below)

### What did you think of YARP?
good

**Comment by Tratcher** [comment]
> Is msrp software only for asp.net users?
> I think it can only be started from the asp.net project now.

YARP is first and foremost a library for use with ASP.NET Core. However...

> can start msrp from the command line?
>
> Will it provide the command line to load the listener, cluster, and endpoint parameters?
> Even more complex commands?

Yes. Today if you follow the [Getting Started](https://microsoft.github.io/reverse-proxy/articles/getting_started.html) guide the end result will be an exe that you can run from the command line and configure via a the appsettings.json file. See [this sample](https://github.com/microsoft/reverse-proxy/blob/32b6174b3bcc299a5272ae8d11630049d3c74d2b/samples/ReverseProxy.Config.Sample/appsettings.json#L10-L20) as well.

In the future we do plan to ship a pre-built version of that exe with additional built in features. See https://github.com/microsoft/reverse-proxy/issues/261.

**Comment by kasini3000** [comment]
the end result will be an exe that you can run from the command line and configure via a the appsettings.json file.-----This helped me a lot, thank you！

**Comment by karelz** [comment]
Duplicate of #261
