### ISSUE TITLE
Simple proxying

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#408]
Many users have very basic needs from a proxy. They don't need load balancing, affinity, or even routing, or they address those concerns in their own way. What these users really need is the code from [HttpProxy](https://github.com/microsoft/reverse-proxy/blob/c1d65e944d2205c2d442d45785e7875bd87c0fde/src/ReverseProxy/Service/Proxy/HttpProxy.cs) that manages the transition between HttpContext and HttpRequestMessage. They want to call this from their own controller or middleware to forward specific requests to specific destinations.

Consider directly exposing HttpProxy (or a more targeted API) for these use cases.

**Comment by DanielDestino** [comment]
I had the same need and made a simple clent implementation of YARP here:

https://github.com/DestinoAS/Destinet.HttpProxyClient
