### ISSUE TITLE
Documentation for swapping authentication types

### ISSUE THREAD

**Issue by crismsx** [microsoft/reverse-proxy#416]
A common scenario I'm running into is to proxy a request for the sole reason of swapping the authentication token. 

In particular, the use case involves the swapping of 2 OAuth2 tokens. The client has access to one IdentityServer and the resource server to a different IdentityServer. The proxy in between is the only component that has access to both IdentityServers and is able to swap the access tokens. The swap should work only for specific (configured) routes.

Consider adding documentation that covers this authentication scenario.

**Comment by Tratcher** [comment]
See this discussion: https://github.com/microsoft/reverse-proxy/discussions/375

As this is a flow that's likely require a lot of customization I don't know that we'll be able to provide more than general guidance and docs. We'll have to wait and see what the most common patterns are.

**Comment by karelz** [comment]
Triage: We can make it an example of adding a header based on the incoming user - likely related to #60

**Comment by macsux** [comment]
We've been using HTTP Headers to do Auth/Authz at the proxy and propagate identity downstream as HTTP headers. This implies there is implicit transport security between proxy and final destination provided by the infrastructure, but this is now increasingly common with SDN, K8S, and use of reverse proxies in sidecar scenarios. I believe this is also a model that is applied by Azure AppService (they auto inject HTTP module to reconstruct .NET Principal from authentication headers). Consider offering this out of the box as it greatly simplifies downstream services processing identity without having to deal with any security blocks. We've been using this to offload Kerberos validation to the sidecar. The identity is extracted and 2 headers are sent downstream:

X-Identity: someuser\domain
X-Roles: User,SomeGroup
Alternatively repackaging identity into JWT can provide greater flexibility as it allows for the much richer expression of principal than plaintext headers above. For this option, it would be useful to have the ability to send both signed and unsigned tokens. Unsigned JWT tokens would lessen the burden of dealing with managing JWK that proxy would need to expose and downstream having to configure.

Signed JWT should also be supported by exposing a JWK url at the proxy. This is to facilitate scenarios where security between proxy and destination cannot be enforced at the transport infrastructure level. Also, some JWT libraries don't support unsigned JWT tokens.

There's also the concept of identity delegation. Consider downstream service wanting to make further downstream calls on behalf of user. OAuth2 supports this via token-exchange where the original incoming token is exchanged to acquire extract claims that the downstream service is implicitly authorized for without requiring user consent. Kerberos also supports this by either delegating TGT of the user (unconstrained delegation) or via similarly constrained delegation which is very similar to oauth2. In all of these cases, there is a desire to propagate the original token/ticket downstream for further use.

**Comment by mgnoonan** [comment]
I have a similar situation to @crismsx, we need to swap client authentication using NTLM to a certificate based authentication from Azure AD. We have a large number of clients that authenticate to the proxy using NTLM, so it was not feasible in a short timeline to switch them all to using Azure AD. We use our current proxy library to convert the incoming NTLM request to an outgoing AAD request to a service running in Azure.

But since the library we are currently using has been deprecated now that YARP is approaching GA, so it would be nice to get some documentation on how to swap authentication like this so we can convert. Thanks.

**Comment by Tratcher** [comment]
The custom transforms work has been merged and should be adequate to for auth swapping. Check out #703 and try out the daily builds. 

The next questions at this point are:
A) Is there any kind of auth swapping you can't do with the given transform infrastructure?
B) Are there a few auth swapping patterns that are common enough that they should be added directly to YARP?

**Comment by Kahbazi** [comment]
For the sake of [RFC - 407 Proxy Authentication Required](https://tools.ietf.org/html/rfc7235#section-3.2), do you think there should be a built in way (without Events) in the current ASP.NET Core authentication handlers to set 407 status code? 
https://github.com/dotnet/aspnetcore/blob/c925f99cddac0df90ed0bc4a07ecda6b054a0b02/src/Security/Authentication/Core/src/AuthenticationHandler.cs#L279-L283

**Comment by Tratcher** [comment]
@Kahbazi I've mainly seen the 407 approach used with forward proxies, not reverse proxies. Do you have any examples where reverse proxies use 407?

407 uses a different header because it's expected that you'd need to simultaneously authenticate to both the proxy and the destination. A reverse proxy is usually less visible to the caller and owns the authentication step to the destination.

**Comment by Kahbazi** [comment]
@Tratcher Ah, my mistake! I thought it was for reverse proxy. I have scenarios where there's authentication for both reverse proxy and the destination and I thought I discovered a standard way to state which authentication has been failed.

**Comment by Tratcher** [comment]
Un-assigning and moving to the v1 milestone awaiting further feedback.

**Comment by karelz** [comment]
Triage: This was part of the PR #703 -- documented in https://microsoft.github.io/reverse-proxy/articles/authn-authz.html#swapping-authentication-types

**Comment by likemike91** [comment]
The article states that there may be some samples regarding swapping authentication types.

Is there already a sample out there where a BFF exchanges the token (token_exchange grant) of the user for audience=api1 to a new token on behalf of the user for audience=api2 or is that an entirely different use case?
