### ISSUE TITLE
Host documentation on github.com instead of microsoft.github.io

### ISSUE THREAD

**Issue by sgutkin** [microsoft/reverse-proxy#420]
### What should we add or change to make your life better?
Please consider moving the documentation from   microsoft.github.io to github.com.  
For example this URL:  https://microsoft.github.io/reverse-proxy/articles/getting_started.html

### Why is this important to you?
I am working with a bank.  It is extremely difficult to create a business case to justify opening up the proxy to allow access to a public Git repo.  It took years to get access to github.com   I am sure corporate America  is rife with such situations.   

I know something similar was done with the AutoRest project. 

Thanks!

**Comment by Tratcher** [comment]
> I know something similar was done with the AutoRest project.

Do you have a reference for this?

The good news is that the docs are generated from the same repo, so if you have access to github.com you can still get them. See https://github.com/microsoft/reverse-proxy/tree/master/docs/docfx.
https://github.com/microsoft/reverse-proxy/blob/master/docs/docfx/articles/getting_started.md

**Comment by karelz** [comment]
Triage: Final released product will have official docs. For now, the source code should be sufficient work around.
Let us know if it is too inconvenient for you.
