### ISSUE TITLE
X-Forwarded-For behaviour doesn't seem to match documentation

### ISSUE THREAD

**Issue by jmezach** [microsoft/reverse-proxy#424]
### Describe the bug
I've been doing some more testing and we're noticing some weird behaviour with respect to the X-Forwarded-For header. We have the following setup currently:

Client -> Load Balancer (F5) -> .NET Framework Web API service hosted in IIS

The downstream service currently has a middleware that verifies if the client's IP address matches the IP address that was used when the user first logged in (which is stored in the users claims). This is a security feature we've implemented to mitigate the theft of the users credentials.

To avoid having to duplicate this code in every service we're hosting we've been looking at YARP so that it can perform this IP address validation and the downstream service doesn't have to worry about it. This will however be a (possibly slow) migration scenario so we need the services to function as normal with or without YARP put in front. So with YARP the picture becomes this:

Client -> Load Balancer (F5) -> YARP hosted in IIS -> .NET Framework Web API service hosted in IIS

Without configuring anything with respect to the X-Forwarded headers we receive the following in the downstream service:

```
X-Forwarded-For: <client-ip>, <load-balancer-ip>
```

This makes sense since the default behaviour of the [RequestHeaderXForwardedForTransform](https://github.com/microsoft/reverse-proxy/blob/v1.0.0-preview4/src/ReverseProxy/Service/RuntimeModel/Transforms/RequestHeaderXForwardedForTransform.cs) is to `Append` the RemoteIpAddress of the incoming connection to the `X-Forwarded-For` header and the load balancer is configured to already sent the `X-Forwarded-For` header with the original client's IP address.

Unfortunately the middleware isn't capable of handling multiple IP addresses currently so I had a look at what we can configure in YARP. According to the [documentation](https://microsoft.github.io/reverse-proxy/articles/transforms.html#x-forwarded) we should be able to switch `Append` to `False` but states that:

> If append is false and the associated value is not available on the request (e.g. RemoteIpAddress is null), any existing header is still removed to prevent spoofing.

So I wasn't expecting that to work at all, because I would expect to either not receive a `X-Forwarded-For` header at all or I would receive an `X-Forwarded-For` header with the IP address that YARP sees. However, what we're actually seeing is:

```
X-Forwarded-For: <client-ip>
```

That makes our middleware work, but it doesn't match the documentation nor does it match what I would expect to happen when I looked at the code.

### To Reproduce
I'm using the following configuration:

```json
"ReverseProxy": {
    "Routes": [
      {
        "RouteId": "no-gateway-auth",
        "ClusterId": "echoService",
        "Match": {
          "Path": "/realization/{**catch-all}"
        },
        "Transforms": [
         { "PathSet": "/api/values" },
         { "X-Forwarded": "", "Prefix": "X-Forwarded-", "Append": false }
        ]
      }
    ],
   "Clusters": {
      "echoService": {
        "Destinations": {
          "echoService/destination1": {
            "Address": "https://localhost:5003/"
          }
        }
      }
    }
}
```

### Further technical details
- Version: 1.0.0-preview.4
- Platform: Windows Server 2016

**Comment by Tratcher** [comment]
You set `"X-Forwarded": ""` which turned off the x-forwarded-for header processing. The rest of the options are ignored in that case. The documented removal case would be like this:
`{ "X-Forwarded": "for", "Append": false }`

**Comment by jmezach** [comment]
Ah, you're right. I totally missed that in the docs. Indeed setting `{ "X-Forwarded": "for", "Append": false }` as a transform on the route does result in the downstream service receiving the IP address of our load balancer as we expected. So I guess for our transition period we can just disable processing of those headers using `{ "X-Forwarded": "" }` so that it will continue to work for the downstream service until we have everything in place in the YARP proxy.

Sorry to bother you with this ;).
