### ISSUE TITLE
Github action doc build no longer works

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#428]
https://github.com/microsoft/reverse-proxy/runs/1135982884?check_suite_focus=true

We updated to the Preview8 SDK which requires VS 16.8.0-preview2, but the github agents only have 16.7.
https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md#visual-studio-enterprise-2019

For preview 5 we should probably run the steps manually, after we get all the preview5 edits made.
https://github.com/microsoft/reverse-proxy/actions/runs/261817348/workflow

@MihaZupan

**Comment by Tratcher** [comment]
A workaround might be to revert the SDK only in that release/docs branch, but that might complicate our branching even more.

**Comment by Tratcher** [comment]
This was worked around by building the docs locally and checking them in. The Github Action was modified to sync the checked in docs rather than build them.

Revert after 16.8 RTMs in November and gets deployed to the github agents (when?).

**Comment by karelz** [comment]
Triage: Wait for November - it will go away, we can manually workaround until then.

**Comment by Tratcher** [comment]
ETA: Nov 16-20
https://github.com/actions/virtual-environments/issues/1891
