### ISSUE TITLE
Do not flow the Connection header?

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#439]
https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.10

The Connection header is per hop and shouldn't be forwarded through a proxy. Note most of the spec concerns here apply to traditional forward proxies, but they might still be useful for a reverse proxy. E.g. Forwarding a `Connection: close` header would allow the client to terminate the proxy's connection to the destination and negatively impact performance.

Note for WebSockets we do need to forward the `Connection: Upgrade` header, so we can't ban Connection outright.

**Comment by karelz** [comment]
Triage: Motivation protect performance - we should filter out `Connection: close` (we don't have more at the moment).

**Comment by Tratcher** [comment]
Keep-Alive should also be removed from requests. We already remove it from HTTP/2 responses.
