### ISSUE TITLE
Implement method transforms

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#445]
https://github.com/microsoft/reverse-proxy/discussions/444
Some servers only accept basic HTTP methods like GET and POST, not PUT or DELETE. Implement request method transforms like PUT -> POST.
- It would look a lot like the [PathSet](https://microsoft.github.io/reverse-proxy/articles/transforms.html#pathset) transform.
- Derive from [RequestParamtersTransform](https://github.com/microsoft/reverse-proxy/blob/b48d6950a69e3fccb3b17e09bd64dcb0cfdcb926/src/ReverseProxy/Service/RuntimeModel/Transforms/RequestParametersTransform.cs).
- Modify [RequestParametersTransformContext.Method](https://github.com/microsoft/reverse-proxy/blob/b48d6950a69e3fccb3b17e09bd64dcb0cfdcb926/src/ReverseProxy/Service/RuntimeModel/Transforms/RequestParametersTransformContext.cs#L27)

Related: Consider support for the X-Http-Method-Override header to preserve the original method. This would have to be a separate transform since headers are processed seperately.

**Comment by samsp-msft** [comment]
I’d like to see this one done as an extension - it would be a good way to prove if we have the right extensibility points?

**Comment by Tratcher** [comment]
It would be interesting as an exercise when we actually build those extensibility points (https://github.com/microsoft/reverse-proxy/issues/60) to test...

**Comment by karelz** [comment]
Triage: Apparently happens to a few customers (sad), should be simple to do.
