### ISSUE TITLE
Sample/Doc for pipeline module(s)

### ISSUE THREAD

**Issue by samsp-msft** [microsoft/reverse-proxy#452]
Most of the questions we get for "how do I?" with the proxy can be solved with a custom middleware component. Although we have a samples folder - that is more of a scratch pad for the teams internal experiments - it is not documentation for what you can do and how you should do it as a middleware component. For example, can you create new destinations on the fly, can you lookup the destinations for a backend cluster and swap those in.

This should cover:

* What properties existing pipeline stages operate on, and write out -> so that you know where to insert your module
* Reading from config
* Modifying destinations for a request
* Reading and modifying headers before the request is sent to destination
* Reading and modifying headers before the response is sent to the client

**Comment by karelz** [comment]
Duplicate of #114
