### ISSUE TITLE
Comparison typo?

### ISSUE THREAD

**Issue by NoahStahl** [microsoft/reverse-proxy#457]
I was looking through the code and noticed this line:

https://github.com/microsoft/reverse-proxy/blob/7a6f66ccf886dfb331d607c8aa498a0c80e58856/src/ReverseProxy/Abstractions/RouteDiscovery/Contract/RouteHeader.cs#L64

Shouldn't it be comparing `header1.Name` to `header2.Name` instead of itself? Apologies if I'm misreading the logic.

**Comment by Tratcher** [comment]
You're right 😁. Want to fix it? If not I'll get to it soon.

**Comment by NoahStahl** [comment]
I gave it a shot in submitted PR. :)
