### ISSUE TITLE
HttpClient vs HttpMessageInvoker buffering issue

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#458]
We decided to use HttpMessageInvoker with IHttpProxy and IProxyHttpClientFactory to cut out some unnecessary layers for a modest perf benefit. However, because HttpClient derives from HttpMessageInvoker customers can still return it from the factory and/or pass it to IHttpProxy. They might do this if they were for example using the IHttpClientFactory API to produce their client, or just out of habit.

Problem:
When HttpClient overrides HttpMessageInvoker.SendAsync it changes the response behavior to fully buffered (HttpCompletionOption.ResponseContentRead) and there's no way to override that from the HttpMessageInvoker API. Fully buffering responses would have significant impacts on the proxy performance and functionality including:
- High memory usage
- Increased latency
- Timeouts would apply to the full response body, not just the headers
- Broken streaming scenarios like gRPC and WebSockets

Possible Mitigations:
A) Doc guidance. We already document several other things a developer could mess up when creating their own client like these:
```c#
            new SocketsHttpHandler()
            {
                UseProxy = false,
                AllowAutoRedirect = false,
                AutomaticDecompression = DecompressionMethods.None,
                UseCookies = false
            }
```
Fully buffering is worse than any of those, but calling it out in the docs might be a good start.
B) Downcast check for HttpClient and hard fail.
C) Downcast check for HttpClient and call the non-buffering overload of SendAsync. That makes the scenario work, but incurs some (small?) performance overhead even if you aren't using HttpClient.

Recommendation: A (docs guidance) should be done regardless. We could do B initially and wait to see if we get feedback that people require C instead.

**Comment by karelz** [comment]
Triage: A + B even on every request (should be ok), until feedback that C would be valuable

**Comment by Tratcher** [comment]
Re-opening for the doc work.

**Comment by Kahbazi** [comment]
Does it also need to be checked here?
https://github.com/microsoft/reverse-proxy/blob/bb6978db0517b21d3125e65bcf8ebb6d87351fd6/src/ReverseProxy/Service/Management/ProxyConfigManager.cs#L283

**Comment by Tratcher** [comment]
@Kahbazi I'd considered it, but this check covers both scenarios. What would you gain with the second check?

**Comment by Kahbazi** [comment]
Oh , you're right. At the end the it goes to `HttpProxy`.

I think there's no need to check it in `ActiveHealthCheckMonitor` either? Since it's internal, right?

https://github.com/microsoft/reverse-proxy/blob/0a5ae94e347a773ed1f183a776d150682d21b211/src/ReverseProxy/Service/HealthChecks/ActiveHealthCheckMonitor.cs#L126

**Comment by Tratcher** [comment]
Health checks aren't impacted in the same way, they don't stream responses. And they're all using the same HttpClient anyways so it doesn't really matter who reports the error so long as it is reported.
