### ISSUE TITLE
Routes can be fully dynamic and discovered on a per request basis for hyper scale hosting

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#46]
The current proxy routing design assumes all route data is available up front and can be loaded atomically into the route table. The EndpointDataSource routing model assumes this as well.

For more dynamically-configured services, we probably don't want to fetch the entire route table from the db, but instead have a pull and cache for each hostname model.

How can we lazy-load route, backend, and endpoint data on a per request basis?

Assume we're working with a discrete key like Host, not a complicated best-match scenario like Path, and little or no wildcard support (maybe wildcard subdomains but only for specific depths?).

@davidni is this a scenario you'd evaluated?

@rynowak can such a system work within routing, co-exist side by side routing, or would it completely replace routing?

**Comment by samsp-msft** [comment]
My mental concept is that routing should be one of the steps in the pipeline. But I don't think we have talked enough about what that pipeline looks like. This kind of matches with the conversation today about:
a) The process being matching the host/path to a set of endpoints -> load balancing then picks the right one from that list, accounting for stickiness -> the connection is chosen from a pool, or a new one is created.
b) Passing of client cert information from the front end to workers as part of headers.

For Antares, I would expect to not use a config based route, and instead have a custom routing component. It would manage the connection to the DB and local cache, and return a set of candidate hosts to subsequent steps including the load balancer.

**Comment by Tratcher** [comment]
Here's the current flow:
- Routes and their backends are loaded at startup and added to the central route table.
- A request arrives, matched against the route table, and the proxy logic begins.
- Routes are reloaded if the config changes.

Here's the flow I think we'd need:
- No routes are loaded at startup
- Per request a custom middleware checks the local route cache.
  - If there's no match then it checks the central database. Should it also do negative caching?
    - If there's a match it loads all of the Backend and Endpoint information.
  - If there's now a match in the cache the proxy logic begins.
- There needs to be change notifications from the database to update items in the cache
- There needs to be idle timeout eviction of routes and backends.

Components that likely need to be redesigned/replaced:
- ReverseProxyConfigManager
- IRouteManager
- IProxyDynamicEndpointDataSource
- DynamicConfigBuilder
- IBackendsRepo
- IRoutesRepo

Need updates:
- IBackendManager - Needs idle timeout cleanup

**Comment by rynowak** [comment]
Routing's implementation requires all of the **path matching** logic to be available synchronously. For anything that isn't path based you have full control including the ability to run async code.

You can ultimately just do special casing in routing with a catch-all route, and then you have full control.

**Comment by Tratcher** [comment]
> You can ultimately just do special casing in routing with a catch-all route, and then you have full control.

At that point, why use routing at all?

**Comment by davidfowl** [comment]
Say we don’t use routing, what features would we end up re-implementing and is that worth it

**Comment by Tratcher** [comment]
Depends on how strong your db lookup key is. Of it's keyed by host and always unique then great. If you need to resolve a set and then find the closest match base on something like path then you'd need to reuse some routing mechanics.

Definitely need customer requirement to constrain this scenario or else it will quickly get out of hand.

**Comment by rynowak** [comment]
> can such a system work within routing, co-exist side by side routing, or would it completely replace routing?

The other thing that I'd mention here is that you don't have to use the routing middleware to use routing's concepts. The contract of the routing middleware is that it assigns an endpoint to the request, so it could be a different implementation and no one would care.

**Comment by rynowak** [comment]
> For more dynamically-configured services, we probably don't want to fetch the entire route table from the db, but instead have a pull and cache for each hostname model.

I guess what I want to know what's the hierarchy of data. Is `hostname` the first criteria to match, and then only after that we start processing other request-related properties.

Basically if you want to do lazy-loading you have to opinionated about what the boundaries are that are lazy. So whether or not the existing implementation does what you want depends a lot on those boundaries.

**Comment by Tratcher** [comment]
> The contract of the routing middleware is that it assigns an endpoint to the request, so it could be a different implementation and no one would care.

Exactly, I expect a lazy load middleware to do it's own routing and assign an endpoint, but the rest of the pipeline remains the same.

**Comment by halter73** [comment]
Do we really need to redesign routing to lazily load routes on a per-hostname basis?

Or would we consider this an advanced enough scenario to require some custom code at the beginning of the middleware pipeline that checks the host name, and sees if non-expired routes are already cached for the hostname.  If not, it could delay the rest of the pipeline until the routes are configured.

**Comment by samsp-msft** [comment]
I go with @Tratcher - in this case its a complete replacement of the routing module. It does its own thing and returns the endpoints for loadbalancing etc to work on.
It would be nice (low pri) if it needs to do sub-routes based on path to be able to have sub-instances of route tables - but that wouldn't be something config needs to be able to express.

**Comment by Tratcher** [comment]
> Or would we consider this an advanced enough scenario to require some custom code at the beginning of the middleware pipeline that checks the host name, and sees if non-expired routes are already cached for the hostname? If there are no valid routes, it could delay the rest of the pipeline until the routes are loaded.

That's pretty much the component I'm talking about. By the time it's done the work to load the route or to check that the route is already loaded, actually running routing is redundant, it can already assign the resulting endpoint.

**Comment by Tratcher** [comment]
This customer had an interesting example for dynamic routes: https://github.com/microsoft/reverse-proxy/issues/45#issuecomment-628753157

Summary: They routing is based on tenant, but the tenant id is determined through some combination of values in the request path, headers, query, etc.. They'd need to write code to compute this, but then the rest of the pipeline should be fairly standard to load balance and proxy the request.

**Comment by softwareguy74** [comment]
> This customer had an interesting example for dynamic routes: [#45 (comment)](https://github.com/microsoft/reverse-proxy/issues/45#issuecomment-628753157)
> 
> Summary: They routing is based on tenant, but the tenant id is determined through some combination of values in the request path, headers, query, etc.. They'd need to write code to compute this, but then the rest of the pipeline should be fairly standard to load balance and proxy the request.

Our exact use case.

**Comment by softwareguy74** [comment]
This is a must have feature and really the only reason to use this vs some existing proxy server.  I want to run arbitrary .NET code for at runtime for lookups.

**Comment by ryandle** [comment]
> This customer had an interesting example for dynamic routes: [#45 (comment)](https://github.com/microsoft/reverse-proxy/issues/45#issuecomment-628753157)
> 
> Summary: They routing is based on tenant, but the tenant id is determined through some combination of values in the request path, headers, query, etc.. They'd need to write code to compute this, but then the rest of the pipeline should be fairly standard to load balance and proxy the request.

The second bit of our scenario is that, once we dynamically determine the route key ( tenant id) we then also have to dynamically determine the destination. Our tenants are eligible to go to 1 of N endpoints at any given time, and we need to write custom code to select one on each request.

**Comment by Tratcher** [comment]
> * Use custom code to select the back-end destination endpoint based on that routing key

What kind of criteria are used for this selection? Load, health, affinity?

**Comment by ryandle** [comment]
Custom state that we store. Tenant's are bound to a specific backend-endpoint at any given point in time. That binding may change in the event of a failover.

**Comment by Tratcher** [comment]
Some industrious folks have come up with an alternate design that defines one catch-all route, one cluster, and a custom proxy middleware that dynamically selects the destination(s) based on their own criteria (similar to how session affinity or load balancing work).

Pros:
- Works with todays object model
- Relatively simple to implement
- It can compose with other middleware like load balancing

Cons:
- Limited routing composition, it may conflict with other endpoints in your app
- You're limited to one route and cluster, and therefor one set of options.
- It still assumes all the destinations list is fully loaded. We were able to work around this by creating destinations on the fly with a few tweaks to the object model.
  - Fully dynamic destinations don't work well with health checks or circuit breakers.
- Round robin load balancing doesn't work well here, that state is per cluster and assumes a somewhat stable list of destinations.

**Comment by samsp-msft** [comment]
> * It still assumes all the destinations list is fully loaded. We were able to work around this by creating destinations on the fly with a few tweaks to the object model.
>   
>   * Fully dynamic destinations don't work well with health checks or circuit breakers.
> * Round robin load balancing doesn't work well here, that state is per cluster and assumes a somewhat stable list of destinations.
Where is the round-robin data stored - I wonder if for this case, you could take the list of destinations, sort and then create a hash that would be constant for that list, and key the round robin seed off that?

**Comment by Tratcher** [comment]
Note for triage: We've addressed most of the partner asks here via https://microsoft.github.io/reverse-proxy/articles/direct-proxying.html.

**Comment by karelz** [comment]
Triage: `IHttpProxy` solved it. Closing.
