### ISSUE TITLE
Organize files

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#462]
The current folder hierarchy is a side-effect of merging multiple assemblies and some organic growth. It's confusing to find things and could use some restructuring. One example is that some interfaces are adjacent to their implementations and some aren't. A shallower structure might also be easier to work with.

I don't anticipate this would affect product code, but we might choose to align namespaces with the new structure. Wait until after we complete some of the big features in flight this milestone.

**Comment by alnikola** [comment]
Summary:

0. DON'T DO IT while there are major PRs open (like health check).
1. Flatten project structure.
2. Keep interfaces and implementation together, so we group things by domains not types.
3. Verify and fix namespaces after the project structure compaction
4. Top level folders ideas
   4.1 Discovery
      4.1.1 Abstractions (code config)
      4.1.2 Serializable (Configuration/Contract currently, *Data types)
   4.2 Model (currently RuntimeModel)
   4.3 Routing
   4.4 Load balancing
   4.5 Health
   4.6 Proxy
   4.7 Session affinity
   4.8 Transforms
   4.9 Management (all config-related services go here)
   4.10 Utilities (Signals, timers and other current utilities)

**Comment by ManickaP** [comment]
### My questions
Mostly about things you didn't even talk about

#### Documentation
- Article file names: underscores (https://github.com/microsoft/reverse-proxy/blob/master/docs/docfx/articles/getting_started.md) vs. dashes (https://github.com/microsoft/reverse-proxy/blob/master/docs/docfx/articles/direct-proxying.md) vs. nothing (https://github.com/microsoft/reverse-proxy/blob/master/docs/docfx/articles/proxyhttpclientconfig.md)
- Markdown docs file names camel-case (https://github.com/microsoft/reverse-proxy/blob/master/docs/DailyBuilds.md) seems like all are camel-case :+1: 
- Readme files uppercase (https://github.com/microsoft/reverse-proxy/blob/master/docs/designs/README.md) vs. lowercase (https://github.com/microsoft/reverse-proxy/blob/master/docs/docfx/readme.md) vs. camel-case (https://github.com/microsoft/reverse-proxy/blob/master/src/ReverseProxy/Signals/Readme.md)
- Random readme files in sources (https://github.com/microsoft/reverse-proxy/blob/master/src/ReverseProxy/Signals/Readme.md), should this rather be in articles?
  - Can we document the new structure/namespaces with readme files? Can this be than picked up by docfx and used in API reference docs?

#### Tests
- Functional tests are separate project why? Do we plan to add much more of them?
  - Now that `dotnet test` from the repo root doesn't work, it's super annoying to run all the tests (switching directories and running `dotnet test` twice).


#### Add 2. Keep interfaces and implementation together, so we group things by domains not types.
I have a counter argument. It's just food for thought and I don't expect you to act on it.
This organization makes the most sense for people which are well oriented in the project. For instance in `4.1.1 Discovery/Abstractions` you had to put a comment saying what goes there. How could/should anyone new know where the "code config" files are? This is something that needs to be learned and makes harder to do small contributions by external contributors. And what if a new domain is being introduced? People tend to make it fit existing hierarchy and it leads to too generalized directories (e.g. `4.9 Management` sounds too general). In my personal experience, unless the domains are very well defined, the end result is usually confusing to navigate. On the other hand, if you split the files by type, it's pretty straightforward what goes where.

**Comment by karelz** [comment]
Triage: Minor preference for v1.0 as we want to update namespaces in a similar fashion.

**Comment by Tratcher** [comment]
Other recommendations from API review:
Yarp.ReverseProxy.ServiceFabric (package and namespace) -> Yarp.ServiceFabric
Yarp.ReverseProxy.Kubernetese.* (package and namespace) -> Yarp.Kubernetese.*

**Comment by MihaZupan** [comment]
Also `Yarp.ReverseProxy.` -> `Yarp.` overall in all namespaces?

**Comment by Tratcher** [comment]
> Also `Yarp.ReverseProxy.` -> `Yarp.` overall in all namespaces?

I thought the conclusion there was that the main assembly, package, and namespace would remain Yarp.ReverseProxy? We didn't want to flatten all the way down to just Yarp since that's the overall project name. `Yarp.ReverseProxy.Proxy.IHttpProxy` was still an open discussion.

**Comment by karelz** [comment]
Also Telemetry Consumption package: `Yarp.ReverseProxy.Telemetry.Consumption` -> `Yarp.Telemetry.Consumption`
