### ISSUE TITLE
YARP with single page web applications - Angular

### ISSUE THREAD

**Issue by prabh-62** [microsoft/reverse-proxy#469]
### Describe the bug
YARP doesn't proxy HTTP requests to web applications

### To Reproduce

- `Node.js` should be installed on system (Pre-requisite)

On powershell/Terminal:
- `npx @angular/cli@next new admin-console --strict --routing --style css`
- `cd admin-console`
- `npm start` (This exposes the angular app on port 4200 by default)
<img width="991" alt="angular_4200" src="https://user-images.githubusercontent.com/13006107/96075790-cf7f7300-0e79-11eb-8853-f3f3bcf3b477.png">

Now, create an ASP.NET application and route all traffic to this UI application
```csharp
public void ConfigureServices(IServiceCollection services)
{
	var webRoutes = new ProxyRoute[] {
                new ProxyRoute {
                    RouteId = "adminConsoleUIRoute", ClusterId = "adminConsole", Match = {Path = "/{{**catch-all}}",},
                }
            };
	var webClusters = new Cluster[] {
                new Cluster {
                    Id = "adminConsole",
                    Destinations = {{"destination1", new Destination {Address = "http://localhost:4200"}}}
                }
            };

	services.AddReverseProxy().LoadFromMemory(webRoutes.ToList(), webClusters.ToList());
}
```

- Once we run the ASP.NET app, if we navigate to `http://localhost:5000`, YARP returns HTTP 404 and doesn't show the UI app running on `http://localhost:4200`
<img width="988" alt="yarp_5000" src="https://user-images.githubusercontent.com/13006107/96075807-d9a17180-0e79-11eb-9b75-c097cff80a14.png">

### Further technical details

- Include the version of the packages you are using - Latest master code (Added project reference instead of nuget)
- The platform (Linux/macOS/Windows) - MacOS

**Comment by Tratcher** [comment]
Shouldn't `Match = {Path = "/{{**catch-all}}",}` be `Match = {Path = "/{**catch-all}",}`?

If that doesn't help, can you share the debug server logs?

**Comment by prabh-62** [comment]
My bad, Chris. Looks good now

<img width="1028" alt="angular_app_yarp" src="https://user-images.githubusercontent.com/13006107/96122016-df6d7600-0ebe-11eb-9dac-e247e0b423c9.png">

**Comment by sabrioezer** [comment]
Hi @prabh-62 , I am trying something similar, but the http-request returns only the html of the page and doesnt include source .js data. Which then results with multiple 404-Not Found errors.

Here is my configuration:
`var routes = new[]
            {
                new ProxyRoute()
                {
                    RouteId = "route1",
                    ClusterId = "cluster1",
                    Match =
                    {
                        Path = "/{**catch-all}"
                    }
                }
            };

            var clusters = new[]
            {
                new Cluster()
                {
                    Id = "cluster1",
                    Destinations =
                    {
                        { "destination1", new Destination() { Address = "http://localhost:4200/#/about" } }
                    }
                }
            };


            services.AddReverseProxy()
                .LoadFromMemory(routes.ToList(), clusters.ToList());`

and the errors:
![image](https://user-images.githubusercontent.com/45690424/105460721-831fac80-5c8c-11eb-8857-002d630ac691.png)

On server runs Angular NgRx Material Starter.

**Comment by prabh-62** [comment]
```csharp
new Destination() { Address = "http://localhost:4200/#/about" } }
```

Should the Address be just `http://localhost:4200` ?

**Comment by sabrioezer** [comment]
It is the same with `http://localhost:4200`

**Comment by Tratcher** [comment]
What URI does the html include for the source .js? It may be dynamically generating a URI using the internal destination address rather than the public one.

**Comment by sabrioezer** [comment]
`<script src="runtime.js" type="module"></script><script src="polyfills.js" type="module"></script><script src="styles.js" type="module"></script><script src="vendor.js" type="module"></script><script src="main.js" type="module"></script>
`
There are no URIs, and therefore request has been made to client (Request URL: https://localhost:44322/runtime.js) and not to the proxy. Proxy recieves these scripts; but they won't be forwarded to the client. Is this the normal behaviour?

**Comment by abhishekisforyou** [comment]
Basically turn high into it

**Comment by prabh-62** [comment]
<img width="485" alt="angular_json_basehref" src="https://user-images.githubusercontent.com/13006107/105860360-7a481700-5fbb-11eb-8cb1-e29256c17cbb.png">

Are you providing any `baseHref` or `deployUrl` values either via `@angular/cli` or by editing `angular.json`?

**Comment by sabrioezer** [comment]
No, there is no baseHref value
in index.html
`<base href="/">
  <title>AngularNgrxMaterialStarter</title>`
and also in angular.json
