### ISSUE TITLE
Deal with SniHelper_TruncatedData_Fails test warnings

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#473]
Every official build produces 6 copies of the following warning:
```
##[warning]No of subresults in test case: Microsoft.ReverseProxy.Utilities.Tls.TlsFrameHelperTests.SniHelper_TruncatedData_Fails are more than supported limit 1000, truncating remaning ones.
```

The test uses programmatically generated member data to exhaustively cover the scenario (3980 variations!).
https://github.com/microsoft/reverse-proxy/blob/a3b5e1b9b03fcec8bc764b033b5c066838a8ffe9/test/ReverseProxy.Tests/Utilities/TlsFrameHelperTests.cs#L99-L122

The test should either be broken up or be made less exhaustive so it can properly report results.

**Comment by greenEkatherine** [comment]
I discussed it with @wfurt, he suggested to put these cases into one test. There is the same test in runtime that also should be fixed by this https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Security/tests/FunctionalTests/TlsFrameHelperTests.cs
