### ISSUE TITLE
301 Redirection

### ISSUE THREAD

**Issue by robertok77** [microsoft/reverse-proxy#478]
hi,
I use following configuration as example:
```


  "ReverseProxy": {
    "Routes": [
      {
        "RouteId": "route1",
        "ClusterId": "cluster1",
        "Match": {
          "Path": "{**catch-all}"          
        },
        "Transforms": [
          {
            "ResponseHeader": "Location"
            "Set": "https://example.com/{location path}",
            "When": "???"
          }
        ]
      }
    ],
    "Clusters": {
      "cluster1": {
        "Destinations": {
          "cluster1/destination1": {
            "Address": "https://example.com/"
          }
        }
      }
    }
  }
```

I need change the location 301 response header  based on old value path:
like 
location: https://hostname.com/api/test
to
location:  https://example.com/api/test

Maybe this should be done in code ?

thanx

**Comment by Tratcher** [comment]
See https://github.com/microsoft/reverse-proxy/discussions/466

**Comment by robertok77** [comment]
Neither "A" nor "B" of #466 match requirements. 
As I see "B" allows to add value at design time.
I rather need to access runtime values ( `Location ` header)

What about some kind of handler class `TransformResponseHandler` with override method 
`public abstract StringValues OnTransformedResponseHeader(HttpContext context, HttpResponseMessage response, StringValues oldValues, StringValues newValues)`

so this handler could be called after `ResponseHeaderTransform.Apply`

having access to `oldValues `and `newValues ` should do the job

**Comment by Tratcher** [comment]
That's still within the scope of "B" for a custom transform. [ResponseHeaderTransform](https://github.com/microsoft/reverse-proxy/blob/e9f7bb8d3eb5b68475137bcbdca40ab10353babe/src/ReverseProxy/Service/RuntimeModel/Transforms/ResponseHeaderTransform.cs#L22) is given the `value` of the header it's registered for (Location in this case), and returns the modified value. It has full access to the HttpContext and HttpResponseMessage for any data it needs to create a dynamic value.

**Comment by robertok77** [comment]
current code allows to add value at design time, I made a slip,
however, when do you plan to allow custom transform ...?

**Comment by Tratcher** [comment]
#60 is planned for the 1.0 release, but we haven't decided when yet.

**Comment by robertok77** [comment]
I ask to report info to client 
see you

**Comment by Tratcher** [comment]
#60 has been completed by #703, please try out the daily builds and let us know how it works for you.

**Comment by Biboba** [comment]
Hello @Tratcher,

Thanks for your reply on that issue.
I had the same use case and I was able to update the location header using an "AddResponseTransform" to the transformBuilderContext but don't you think it should be done automatically ?
I think it would be nice improvement to automatically update the FQDN of the location header to the reverse proxy one if the current one matches the adress of one cluser/destination.

Thanks for listening !

**Comment by Tratcher** [comment]
> but don't you think it should be done automatically

We recommend using tools like x-forwarded-host to correctly generate links and redirects in the destination rather than trying to re-write them in the proxy. Proxy rewrites are a lot more expensive and error prone than generating the right value to begin with.
