### ISSUE TITLE
Prioritization in Http2 requests

### ISSUE THREAD

**Issue by samsp-msft** [microsoft/reverse-proxy#48]
Http2 has the concept of prioritization of requests within a stream. How do we want to think of these with respect to the proxy front end if it has an HTTP/2 or HTTP/3 connection. As we terminate the end user request, and create new requests, potentially distributed across multiple servers, any prioritization signals will be lost. As we queue requests for processing, or pack responses into the response stream, do we need to be prioritizing which responses get streamed first?

https://blog.cloudflare.com/adopting-a-new-approach-to-http-prioritization/

**Comment by Tratcher** [comment]
Prioritization is not exposed or honored in any of our http client or server stacks. It's not a thing the proxy needs to consider unless our customers come asking for it.

**Comment by anurse** [comment]
I tend to agree here. I'd suggest this be an Idea (since we do basically understand the actionable work, we just don't know the exact design or value) and be backlogged.

**Comment by Tratcher** [comment]
Recommend we close this due to low interest.
