### ISSUE TITLE
Remove null checks in constructors

### ISSUE THREAD

**Issue by alnikola** [microsoft/reverse-proxy#486]
Currently, we check for null all constructor parameters which might be not necessary since DI infra won't pass in `null`s. Let's discuss whether or not they have some real value, and if not - remove them.

**Comment by Marusyk** [comment]
I would try to help with it

**Comment by Tratcher** [comment]
@Marusyk thanks, but please wait until we decided if this is a good idea or not.

**Comment by karelz** [comment]
Triage: Public APIs can be used also outside of DI - they should keep the checks.
Overall not worth it, let's keep the checks. Closing.
Thanks @Marusyk for the offer, maybe you can find another issue in the repo to help (e.g. [here](https://github.com/microsoft/reverse-proxy/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22)). Let us know if you need help to find more / different issues. Thanks!
