### ISSUE TITLE
append the user bearer token to api from Proxy 

### ISSUE THREAD

**Issue by som-nitjsr** [microsoft/reverse-proxy#492]
### Describe the bug
I am using https://github.com/ProxyKit/ProxyKit  in my UI i am using cookie based authentication and my api need bearer token(access token). 
this is my current code in startup.cs running.
Now I wanted to move this library but could not find a way to achieve the same.

```c#
app.Map("/xyz", api =>
            {
                api.RunProxy(async context =>
                {
                    var forwardContext = context.ForwardTo(Configuration["xyzapi"]);

                    try
                    {
                        var token = await context.GetUserAccessTokenAsync();
                        forwardContext.UpstreamRequest.SetBearerToken(token);

                        return await forwardContext.Send();
                    }
                    catch (Exception ex)
                    {
                        throw;
                    }

                });
            });
```

**Comment by Tratcher** [comment]
Yeah, we haven't built that flow yet, we're still collecting input on what format people want to flow the user details in. https://github.com/microsoft/reverse-proxy/issues/416 https://github.com/microsoft/reverse-proxy/discussions/375

**Comment by som-nitjsr** [comment]
by when this feature will be available?

**Comment by Tratcher** [comment]
Unknown. We're tracking the scenario but are still gathering requirements. There are a few variations of the scenario and we haven't heard strong feedback about which ones people need most.

Your case is most like #375, have you tried the proposal at https://github.com/microsoft/reverse-proxy/discussions/375#discussioncomment-54056 ?

**Comment by som-nitjsr** [comment]
Thanks it is working

**Comment by Tratcher** [comment]
See https://github.com/microsoft/reverse-proxy/issues/561#issuecomment-752273544 for preview8 updates here.
