### ISSUE TITLE
Write migration docs

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#495]
Some customers interested in moving to YARP have asked us for docs comparing YARP to their prior solutions like ARR, Nginx, etc.. This includes:
A) Feature comparisons for what is and isn't available
B) Performance comparisons, what can they expect
C) Side-by-side configuration examples showing how to move their existing configuration to YARP.

**Comment by karelz** [comment]
Triage: We believe our current docs are simple and straightforward enough to make this not needed.
