### ISSUE TITLE
Remove the Arrange/Act/Assert test comments

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#527]
Arrange/Act/Assert is a fine pattern for writing tests, but we don't need the actual comments in the code, they're just noise.
https://github.com/microsoft/reverse-proxy/blob/6defd11081d37c0d59b34b67cdabff240c9b8e84/test/ReverseProxy.Tests/Abstractions/ClusterDiscovery/Contract/ClusterTests.cs#L61-L68

Triage: Remove those comments from the tests so that we have a consistent style across the tests.

**Comment by Marusyk** [comment]
:) I'll cleanup it
