### ISSUE TITLE
Service Fabric integration for route discovery should support transforms

### ISSUE THREAD

**Issue by akanieski** [microsoft/reverse-proxy#528]
### What should we add or change to make your life better?
The Service Fabric route discovery PR #257  is great. It would be awesome if it could add the ability to configure transforms using the same `Labels` concept developed in #257. This would again be similar to the way that Traefik exposes it's transformations through container labels seen [here](https://doc.traefik.io/traefik/middlewares/headers/). 

### Why is this important to you?
Adding transformations is sort of a key functionality that YARP already supports. I think its the next logical progression to bring this functionality to the Service Fabric integration.

### Transform Serialization
One concern is how to serialize transforms. My initial thought would be to use strongly typed XML to serialize the transform as this is what a developer familiar with SF would be comfortable with, but that doesn't quite jive with the idea of `Labels` being an `IDictionary<string, string>`. On the contrary it might be best to just use re-use `Labels`, the idea being that `Labels` and `Transforms` area really just `Dictionary<string, string`. For example, a `Label` for [AddTransformResponseHeader](https://microsoft.github.io/reverse-proxy/articles/transforms.html#responseheader), might look like this:

```
            <Label Key='YARP.Routes.route1.Transforms.[0].ResponseHeader'>x-custom-header</Label>
            <Label Key='YARP.Routes.route1.Transforms.[0].Append'>Hello from proxied application</Label>
            <Label Key='YARP.Routes.route1.Transforms.[0].When'>Success</Label>
```

This is similar to the way Traefik handles it's middleware labels for docker containers.

#### Complete Service Manifest Example:
```
<ServiceManifest Name="Service1Pkg" Version="1.0.0" xmlns="http://schemas.microsoft.com/2011/01/fabric">
  <ServiceTypes>
    <StatelessServiceType ServiceTypeName="Service1Type" >
      <Extensions>
        <Extension Name="YARP-preview">
          <Labels xmlns="http://schemas.microsoft.com/2015/03/fabact-no-schema">
            <Label Key="YARP.Enable">true</Label>
            <Label Key="YARP.Routes.route1.Hosts">example.com</Label>

            <!-- Optional: ResponseHeader Transform -->
            <Label Key='YARP.Routes.route1.Transforms.[0].ResponseHeader'>x-custom-header</Label>
            <Label Key='YARP.Routes.route1.Transforms.[0].Append'>Hello from proxied application</Label>
            <Label Key='YARP.Routes.route1.Transforms.[0].When'>Success</Label>

            <!-- Optional: enable health probes -->
            <Label Key='YARP.Backend.Healthcheck.Enabled'>true</Label>
            <Label Key='YARP.Backend.Healthcheck.Path'>api/health</Label>
            <Label Key='YARP.Backend.Healthcheck.Timeout'>30</Label>
            <Label Key='YARP.Backend.Healthcheck.Interval'>10</Label>
          </Labels>
        </Extension>
      </Extensions>
    </StatelessServiceType>
  </ServiceTypes>

  <!-- ... -->
</ServiceManifest>
```

### Work
Perhaps I can work on implementing this once #257 is merged in.
- [X] Adjust `Microsoft.ReverseProxy.ServiceFabric.LabelsParser.BuildRoutes` to handle `YARP.Routes.<RouteId>.Transforms.<Transform Index>.<Property Name>` labels and convert them to Transforms on each respective route.
- [ ] Update docs page to include explanation of Service Fabric transforms syntax

**Comment by Tratcher** [comment]
> `<Label Key='YARP.Routes.route1.Transforms.CustomTransform1.ResponseHeader'>x-custom-header</Label>`

We can borrow the way a list is flattened in IConfiguration which is by giving the entries indexes like this:

`<Label Key='YARP.Routes.route1.Transforms.[0].ResponseHeader'>x-custom-header</Label>`
