### ISSUE TITLE
[Tracking] Early filtering SSL 

### ISSUE THREAD

**Issue by samsp-msft** [microsoft/reverse-proxy#53]
Be able to filter connections at SSL connection time to prevent DoS attacks

**Comment by anurse** [comment]
Specifically, this involves being able to filter connections based on information contained in the ClientHello TLS frame. Examples include:

* Cipher Suite selection
* Protocol Version
* Server Name Indication (SNI)
* Application-Level Protocol Negotiation (ALPN; used for HTTP/2 and HTTP/3)

**Comment by karelz** [comment]
Duplicate of #16
