### ISSUE TITLE
Inconsistent use of nullable fields in config

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#531]
The config classes like Cluster are inconsistent about the use of nullable fields.
https://github.com/microsoft/reverse-proxy/blob/6defd11081d37c0d59b34b67cdabff240c9b8e84/src/ReverseProxy/Abstractions/ClusterDiscovery/Contract/ProxyHttpClientOptions.cs#L14-L18

This makes it hard for the various parts of the implementation to tell if they're being given a default value or if the user actually specified that value. Since many parts of the implementations are supposed to be replaceable components, it would help if they could distinguish so they could provide their own defaults while still respecting explicit user config.

Proposal: Make most/all config fields nullable and only specify the default in the implementations.

**Comment by karelz** [comment]
Triage: Affects base object model, therefore v1

**Comment by karelz** [comment]
Should be fairly straightforward to do ... we would welcome help here.
