### ISSUE TITLE
Is it normal to make half of performance ?

### ISSUE THREAD

**Issue by okproject** [microsoft/reverse-proxy#537]
### Some details

**How many backends are in your application?**

- [x ] 1-2
- [ ] 3-5
- [ ] 6-10
- [ ] 10+

**How do you host your application?**

- [ ] Kubernetes
- [ ] Azure App Service
- [ ] Azure VMs
- [ ] Other Cloud Provider (please include details below)
- [x] Other Hosting model (please include details below)
        - Local environment: macbook 2015 mid 16gb mem i7 cpu 256gb ssd

### What did you think of YARP?
Hi.

Thank you very much to invest that kind of tool; thank you all team members, contrirbutors.

### Problem
- As a summary my test results performance degradation. I want to know if is there any mistake by me or nature of the product currently.

#### Given
-  APP A - YARP)I have e .net core 3.1 project that contains YARP and configuration.It listens port 80
- I changed etc/host file to listen website1.com   points to 127.0.0.1
- APP B - WEBSITE1) I have website*1*   asp.net core 3.1 MVC app (default new website template)
- I hosted 2 different instance of APP B on my local machie on port 5010 and 5020
- I configured YARP instance to point APPB with load balancing config.
- I used  loadtest (npm package), tcpkali, bombardier packages for loadtest

#### When1
- When i directly test APP-B single instance instance with localhost:5010
#### Then1  
- It handles 30.000 request per second

#### When2
- When i test my APPAPP-A YARP instance instance with website2.com (i updated etc host file to point it)
- My YARP configuration points to instance of same app running on different process
- I used both RoundRobin and Random options to distribute load
- I specify loadBalancingSettin in startup cs as specified in documentation
#### Then2
- It handles 13000 - 15000  request per second

**Question1**: Is it normal to have that much degradation when i use YARP ?

**Question2**: Can you please share with me how to modify my computer setting as both load testing client and local server for load testing scenario. I found too many documents; nothing exact.

So if you some advice  about setting macos Catalina 10.15.6   for loadtest using YARP, i would be great.

Thank you very much for the YARP again.

**PS** : I disabled all loggers to see performance of the apps (console logger makes performance worst, so i cleared all log providers for loadtest)

**Comment by Tratcher** [comment]
Yes, adding any proxy to your flow adds significant overhead, especially when the requests are simple and only bound by the constraints of the HTTP stack. If your requests were bound by constraints in your app business logic you wouldn't nearly as much impact.

We aim to improve YARPs throughput from ~50% to ~75%.

@sebastienros

**Comment by sebastienros** [comment]
I confirm what @Tratcher said.
And we measure this cost on any proxy, it's not specific to yarp.

But based on the client load, this can actually improve perf in some cases, so this is very specific to what kind of benchmark is run. In your case this is totally expected.

**Comment by okproject** [comment]
@Tratcher  @sebastienros   thank you very much for the answers.

And I want to say than you very much again.

I have one more question.

1. Pod
For example, when we use kubernetes

- We create a pod that contains 2 container. One of them is web app and other one is nginx sidecar container

- When we switch from nginx to YARP, is the scenario same ? I mean do we need to place web app and YARP containers in a pod ? Or is it wrong use for that kind of scenario ?

2. Load Balancing

- In kubernetes scenario we have service object that manage load balancing by yml definition.
- Is YARP planned for replace the kubernetes service to handle load balancing or it is not in case ?

Thank you

**Comment by Tratcher** [comment]
We haven't started looking at kubernetes in detail yet, but yes, you should be able to use YARP anywhere that you use NGinx as a proxy. We're tracking this here: https://github.com/microsoft/reverse-proxy/issues/200

**Comment by karelz** [comment]
Triage: Seems to be answered, closing. Kubernetes support is tracked in #200.
