### ISSUE TITLE
Use globally installed dotnet SDK if version matches

### ISSUE THREAD

**Issue by kiapanahi** [microsoft/reverse-proxy#547]
At the time of this writing the latest released dotnet SDK is 5.0.100 and the `restore.cmd` command tries to download the exact same version in the _.dotnet_ directory to further use in the _$PATH_.

It would be nice if the restore script checked for the installed SDKs on the system and if a suitable version was found, omit the SDK download section altogether and instead use the installed copy.

This would theoretically save bandwidth and reduces build time especially for folks with slower internet connections.

**Comment by Tratcher** [comment]
That's a fair ask. We were consuming preview SDKs until last week. We'll probably go back to consuming preview SDKs at some point in the future, but not for a few months at least. Consuming the installed one if present would improve performance. The same idea would apply to the runtimes as well.

The main question I have is if we can pull things piecemeal or of it has to all come from one location or the other. I suspect the latter which would make this more difficult. This is also all managed by our central Arcade tooling infrastructure so we may have to ask them to implement it for us. I'll ask around.

**Comment by karelz** [comment]
Triage: The fact we use RTW version is point in time only. We will "soon" migrate to .NET 6 previews to allow us target .NET 6.
Given that this is infrastructure issue (Arcade is separate repo used by all/most .NET repos) and this is the only repo needing it, we do not think it makes sense to push for this.
Closing
