### ISSUE TITLE
Load balancer config extension

### ISSUE THREAD

**Issue by samsp-msft** [microsoft/reverse-proxy#55]
Enable custom metadata in backend endpoint definition so a custom load balancer could do A/B switching etc.

Note: This task is about ensuring the plumbing is available to support this scenario, but does not involve creating a custom load balancer

**Comment by Tratcher** [comment]
Possibly a duplicate of https://github.com/microsoft/reverse-proxy/issues/126.

**Comment by Tratcher** [comment]
Partially addressed by #793, making destination metadata accessible at runtime.

As for associating extra state with destinations at runtime, we've found that ConditionalWeakTable works really well for that.
