### ISSUE TITLE
[SF] Review error handling logic and harden it where necessary

### ISSUE THREAD

**Issue by alnikola** [microsoft/reverse-proxy#552]
The SF integration's error handling is currently quite relaxed in exception handling and allows to proceed further regardless of anything. We should review it and harden were necessary.

**Comment by alnikola** [comment]
Pre-triage: We need to collect more information about the real-world scenarios of the SF integration usage. Moving to backlog for now.

**Comment by Tratcher** [comment]
SF work has moved to https://github.com/microsoft/service-fabric-yarp
