### ISSUE TITLE
[SF] Label names casing handling

### ISSUE THREAD

**Issue by alnikola** [microsoft/reverse-proxy#553]
Label names are currently being compared as `Ordinal`. Let's review it to confirm that's it's the right way or change it to `OrdinalIgnoreCase`.

**Comment by Tratcher** [comment]
Our config file sources use OrdinalIgnoreCase so I'd recommend that for SF too.

**Comment by alnikola** [comment]
It's not that simple unfortunately here. In example, Traefik uses [case sensitive labels](https://doc.traefik.io/traefik/v1.7/configuration/backends/servicefabric/#labels).

**Comment by Tratcher** [comment]
Hmm, they don't give a reason for that. Why would we preserve that behavior? You're unlikely to have entries that differ only by case.

**Comment by karelz** [comment]
Triage: After a lengthy debate, we are ok with current status until proven otherwise :)
