### ISSUE TITLE
[SF] LoadFromServiceFabric should take options

### ISSUE THREAD

**Issue by alnikola** [microsoft/reverse-proxy#555]
LoadFromServiceFabric should take options.

@Tratcher Could you please add details here?

**Comment by Tratcher** [comment]
SF is enabled by the call `services.AddReverseProxy().LoadFromServiceFabric();`, but then configured by the call `services.Configure<ServiceFabricDiscoveryOptions>(_configuration.GetSection("ServiceFabricDiscovery"));`.

It's standard in AspNetCore to combine these calls to something like:
 `services.AddReverseProxy().LoadFromServiceFabric(_configuration.GetSection("ServiceFabricDiscovery"));`, or
 `services.AddReverseProxy().LoadFromServiceFabric(options => { });`,

We have something similar for config based routes:
`.LoadFromConfig(_configuration.GetSection("ReverseProxy"))`

**Comment by karelz** [comment]
Triage: We need to follow up the ASP.NET pattern. Should be simple.
