### ISSUE TITLE
[SF] Convert static classes to interfaces + implementations

### ISSUE THREAD

**Issue by alnikola** [microsoft/reverse-proxy#558]
Service Fabric integration incapsulates parts of logic in several static types which are not unit test friendly (e.g. `LabelsParser`). Let's convert those types into instance ones and extract their interfaces where it seems beneficial.

**Comment by alnikola** [comment]
Pre-triage: Moved to backlog due to a low priority.

**Comment by Tratcher** [comment]
SF work has moved to https://github.com/microsoft/service-fabric-yarp
