### ISSUE TITLE
[SF] Choose the right extension name

### ISSUE THREAD

**Issue by alnikola** [microsoft/reverse-proxy#560]
Service Fabric's YARP extension is currently named "YARP-preview" which is temporal and needs to be confirmed. Let's finalize the extension name's discussion.

**Comment by Tratcher** [comment]
Branding: `YARP` is the project name but was not used anywhere in the actual product before the SF package. @davidni warned that the name `ReverseProxy` was probably too generic since SF already has one of those.

**Comment by samsp-msft** [comment]
Where does this name show up? Is it in SF or YARP?

**Comment by Tratcher** [comment]
SF apps that want to opt-into being exposed through YARP add this config:
```XML
<Extensions>
  <Extension Name="YARP-preview">
    <Labels xmlns="http://schemas.microsoft.com/2015/03/fabact-no-schema">
      <Label Key="YARP.Enable">true</Label>
      <Label Key="YARP.Routes.route1.Hosts">example.com</Label>
    </Labels>
  </Extension>
</Extensions>
```
The YARP SF discovery scans apps in the current SF cluster looking for that config.

**Comment by karelz** [comment]
Triage: Branding decision.

**Comment by Tratcher** [comment]
SF work has moved to https://github.com/microsoft/service-fabric-yarp
