### ISSUE TITLE
[IHttpProxy] Configuration of Upstream Request before Proxying

### ISSUE THREAD

**Issue by JulianHBuecher** [microsoft/reverse-proxy#561]
Hello everyone,
during the last two weeks I was digging into YARP a little bit.
I have an existing application (Backend For Frontend), which works with ProxyKit to handle Requests to Upstream.
For my sake the support for ProxyKit is over now and I want my application to be ready for the future ;)

**Now I have a little problem:**
With ProxyKit I could configure the forwarded UpstreamRequest before I sent it to the Backend. Now I tried something similar with YARP and the "Direct Proxying"-functionality.

Here is my endpoint configuration:
```
app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers()
                    .RequireAuthorization();

                endpoints.Map("/api/{**catch-all}", async context =>
                {
                    var endpointLookUp = context.RequestServices.GetRequiredService<ProxiedApiRouteEndpointLookup>();

                    if (endpointLookUp.TryGet(context.Request.Path, "/api", out var endpoint))
                    {
                        if (!context.Request.Headers.ContainsKey("X-XSRF-TOKEN"))
                        {
                            var unauthorized = new HttpResponseMessage(HttpStatusCode.Unauthorized);
                        }

                        await antiforgery.ValidateRequestAsync(context);

                        var token = await context.GetUserAccessTokenAsync();

                        var forwardContext = context.ForwardTo(endpoint).CopyXForwardedHeaders();
                        forwardContext.UpstreamRequest.SetBearerToken(token);


                        await httpProxy.ProxyAsync(**forwardContext**, endpoint, httpClient, proxyOptions);
                    }
                });
            });
```
After getting the token and embedding it into the UpstreamRequest I stuck... 🤔
The httpProxy.ProxyAsnyc()-method could not handle an UpstreamRequest... Is there something I didn't read in the docs? Or is this functionality not available yet (and is planned for the future)?
The proxyOptions and the httpClient is similar to the configuration in the "Direct Proxying"-example.

Hoping you could give me some advice here 😊

Best regards,
Julian

**Comment by Tratcher** [comment]
See https://github.com/microsoft/reverse-proxy/issues/492.

**Comment by JulianHBuecher** [comment]
Thanks a lot @Tratcher 👍 

```
...
var token = await context.GetUserAccessTokenAsync();

context.Request.Headers.Add("Authorization", $"Bearer {token}");

await httpProxy.ProxyAsync(context, endpoint, httpClient, proxyOptions);
...
``` 

That's the magic. Hopefully we could use a build in function to set tokens for our UpstreamRequests in the future.

See you 😊

**Comment by Tratcher** [comment]
Re-opening so we can add a feature like that.

**Comment by macsux** [comment]
+1 on this.

I find the current architecture of Transformers too limiting for certain advanced scenarios. Ideally, I'm looking for ways to register middleware actions before proxying with the ability to freestyle configure `HttpRequestMessage` from the current `HttpContext`. After the proxying, I would want the ability to register middleware components to freestyle configure response pipeline by tweaking `HttpContext.Response`. 

Current Transformers class seems to make very specific assumptions on the kind of transformers that can be applied (headers/path). IMO the existing transforms can still be kept but wrapped into the "Before/After" proxying categories as mentioned above.

**Comment by davidfowl** [comment]
Mutating the request in order to transform the outbound isn't ideal. Maybe we need a lower level proxy API  (that doesn't require allocation) and gives a Func<HttpContext, HttpRequestMessage, Task> transform

**Comment by Tratcher** [comment]
@macsux Yes the transforms are very structured, but I'm curious to see examples of transforms you can't do? The main one that's not supported is request and response body transforms because you'd need full middleware for many of those scenarios. 

You can also plug in HttpMessageHandler's into the HttpClient pipeline for more freestyle transformations.

**Comment by litan1106** [comment]
I ran into this problem as well. Bump for the best solution.

**Comment by Tratcher** [comment]
For folks using IHttpProxy directly I've done some significant refactoring of the transforms for that layer for preview8 (https://github.com/microsoft/reverse-proxy/pull/612, https://github.com/microsoft/reverse-proxy/pull/643). The result is more direct access to customize the outgoing request.

The above auth scenario now looks like this:

```C#
        private class CustomTransformer : HttpTransformer
        {
            public override async Task TransformRequestAsync(HttpContext httpContext, HttpRequestMessage proxyRequest, string destinationPrefix)
            {
                await base.TransformRequestAsync(httpContext, proxyRequest, destinationPrefix);

                var token = await httpContext.GetUserAccessTokenAsync();
                proxyRequest.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token);
            }
        }
```

**Comment by Tratcher** [comment]
FYI #703 makes the higher level transform infrastructure more extensible. Please give it a try.

**Comment by JulianHBuecher** [comment]
@Tratcher thanks a lot for your help. I'm looking forward to use YARP as proxy and load balancer. 
Is a feature for request throttling by custom control parameter planned in the near future? Would be nice ;) 
Have a nice day. Best regards, Julian

**Comment by Tratcher** [comment]
@JulianHBuecher We're not planning anything specific in YARP at the moment. ASP.NET Core already has a Concurrency Limiter, and here's a PR that makes it customizable per endpoint: https://github.com/dotnet/aspnetcore/pull/20835/

**Comment by JulianHBuecher** [comment]
Okay, that's what I'm searching for. Perfect, thank you. 👍

**Comment by rollandjb** [comment]
@Tratcher
> You can also plug in HttpMessageHandler's into the HttpClient pipeline for more freestyle transformations.

Is there an example of how to do this. I have looked but couldn't find anything. 

Thank you.

**Comment by Tratcher** [comment]
Only this doc that shows how to customize the HttpClient. You'd add a DelegatingHandler with your customizations around the SocketsHttpHandler.
https://microsoft.github.io/reverse-proxy/articles/http-client-config.html#custom-iforwarderhttpclientfactory
