### ISSUE TITLE
Register local IP address as the host in routes config

### ISSUE THREAD

**Issue by mifopen** [microsoft/reverse-proxy#562]
I need to be able to make a request to the host with yarp running with its local ip address.
Like `http://<ip address of the host>/`
How can I match it from the config?
I've tried something like this:
```json
  "ReverseProxy": {
    "Routes": [
      {
        "RouteId": "route1",
        "ClusterId": "cluster1",
        "Match": {
          "Hosts": [
            "localhost",
            "127.0.0.1",
            "0.0.0.0"
          ]
  }
```
But it doesn't work

**Comment by Tratcher** [comment]
To clarify, what is the public url you want and what is the destination address? Something like this?
Client -> http://localhost -> YARP -> http://{destinationIP} -> destination

Inbound ports are configured through kestrel and then you use routes to decide what to forward.
```
{
  "Kestrel": {
    "Endpoints": {
      "Http": {
        "Url": "http://localhost:5000"
      },
  },
  "ReverseProxy": {
    "Routes": [
      {
        "RouteId": "route1",
        "ClusterId": "cluster1",
        "Match": {
          "Hosts": [
            "localhost"
          ]
      }
     "Clusters" ....
  }
}
```

**Comment by samsp-msft** [comment]
This needs to be made clear in the YARP documentation.

**Comment by mifopen** [comment]
@Tratcher Not exactly
Like this: Client -> http://{yarpIP} -> YARP -> http://{destinationIP} -> destination

**Comment by mifopen** [comment]
And the problem is how to specify that `yarpIP` in the Hosts array.

**Comment by mifopen** [comment]
The scenario: YARP here is just a node in a bigger cluster with another load balancer and that load balancer healthchecks its nodes by IPs.

**Comment by Tratcher** [comment]
The Hosts array is optional, if you just want to forward all requests you can do it like this:
```
    "Routes": [
      {
        "RouteId": "route1",
        "ClusterId": "cluster1",
        "Match": {
          "Path": "/{**catch-all}"
         }
      }
```

**Comment by mifopen** [comment]
Never thought of that! Thanks!

**Comment by karelz** [comment]
Triage: Answered above.
