### ISSUE TITLE
Request Aggregates

### ISSUE THREAD

**Issue by draxtor** [microsoft/reverse-proxy#564]
### What should we add or change to make your life better?
Does this proxy supports request aggregates? Or do you plan such feature?
Something like Ocelot does:
https://ocelot.readthedocs.io/en/latest/features/requestaggregation.html
### Why is this important to you?
It's  nice to have such feature to orchestrate several services together.
Benefits:
- client does one http call
- decoupling of services on frontend and backend, only proxy knows where the data coming from

**Comment by Tratcher** [comment]
Request aggregation is a non-goal for YARP as it requires detailed understanding of the application model, rendering, etc. 

Last I heard Ocelot was planning to re-platform itself on top of YARP so continuing to use Ocelot for these features might be your best option.

**Comment by karelz** [comment]
Triage: This is not goal of YARP. It can be achieved in MVC Controller or WebAPI.

**Comment by GFoley83** [comment]
@Tratcher three years on, it look like YARP has some support for Request Aggregates via [response body transforms](https://microsoft.github.io/reverse-proxy/articles/transforms.html#response-body-transforms). 

Will this be the extent of YARP's support for response body transforms? And what are you thought on using YARP in this fashion?

Given Ocelot is more or less dead, it looks like there's a gap the the .NET landscape for some features that are more aligned with an API Gateway than a reverse proxy.

**Comment by Tratcher** [comment]
response body transforms only cover manipulating a single response, and it's a completely manual process. There's no support for coordination or aggregation of responses. This remains a non-goal for YARP.

Some of the YARP components may be useful for someone to build such a tool, but the logic for splitting requests and merging responses requires a framework that operates at a much higher level than YARP.
