### ISSUE TITLE
[SF] Enable Service Fabric naming discovery by inspecting protocol in destinations  "fabric:/" on cluster

### ISSUE THREAD

**Issue by jaanclaeys** [microsoft/reverse-proxy#569]
### What should we add or change to make your life better?
I looked into the service fabric implementation with the automatic discovery, and I was wondering if there was not a possibility to make this simpler so that we can put the config wherever we want.

I would rather have a change on the way the ReverseProxy library parses the destination on a cluster, and allow people to configure "fabric:/app/service" style of configuration. It would look at the protocol and then either take the default naming service, or add some additional configuration to the cluster to set the destination of that naming resolvement for the protocol.

### Why is this important to you?
If a team is only responsible for the reverseproxy (like a middleware team) in service fabric, it does not make sense to configure the actual reverseproxy configuration on the service itselves. It does make sense to have a seperate service (ReverseProxyService) on the cluster that can proxy other targetservices that are not exposed to the outside world. Configuration should then not be held at the services.

It would also make things simpler and leave the weird Traefik style of configuration for something that you can inject yourselves. An extension on the proxied service could still exist, but I rather see that with an injected IServiceFabricConfigProvider and more loose coupling between the actual discovering of the names and the parsing of the configuration.

**Comment by samsp-msft** [comment]
I think what you are asking for is the ability to define routes in YARP that pull the destination information from service fabric (or other sources). How about something like the following:
```
{
    "ReverseProxy": {
        "Routes": [
            {
                "RouteId": "FromSF",
                "ClusterId": "sf1",
                "Match": {
                    "Path": "/example/{*any}"
                }
            }
        ],
        "Clusters": {
            "sf1": {
                "provider": {
                    "ServiceFabric": "fabric://app/service"
                }
            }
        }
    }
}
```
I am thinking that it shouldn't just be a special destination URL, using a richer object model enables more properties that may need to be passed around.
In this case a ServiceFabric provider object would be instantiated, and it would then know how to interpret the SF specific configuration, and also to keep the destinations up to date.

**Comment by jaanclaeys** [comment]
Indeed something like this would be flexible, you could argue though that the destination indicates the protocol and could be supported out of the box. And naming resolution in general is also something general. Of course service fabric probably is not an IETF asserted protocol

You could have this (defaults of course apply for the namingresolution according to protocol)

```json
{
  "ReverseProxy": {
    "Routes": [{
      "RouteId": "FromSF",
      "ClusterId": "sf1",
      "Match": {
        "Path": "/example/{*any}"
      }
    }],
    "Clusters": {
      "sf1": {
        "destination": "fabric:/app/service",
        "namingresolution": {
          "protocol": "serviceFabric",
          "port": 19081,
          "host": "yourhost.com"
        }
      }
    }
  }
}
```      

And this would also count for regular http:
```json
{
  "ReverseProxy": {
    "Routes": [{
      "RouteId": "FromHttp",
      "ClusterId": "http",
      "Match": {
        "Path": "/example/{*any}"
      }
    }],
    "Clusters": {
      "http": {
        "destination": "http://application.com",
        "namingresolution": {
          "protocol": "dns",
          "port": 53,
          "host": "yourhost.com"
        }
      }
    }
  }
}
```

**Comment by samsp-msft** [comment]
Agreed, this is beyond the scope of the 1.0 integration.

**Comment by Tratcher** [comment]
Offline discussion:
- The proposal is a fundamentally different design from the current approach. Something that different might be best developed as an alternative package rather than trying to work it into the current one.
- Using `fabric:/app/service` addresses at the cluster level makes sense as a means of discovering destination instances.
- I don't recommend trying to re-use the same config provider format, the service config looks quite different and trying to share the structure seems confusing.

**Comment by davidni** [comment]
Let's also consider https://github.com/microsoft/reverse-proxy/issues/46 when coming up with a design for this one. 

For example, we should eventually provide a reasonable alternative to Service Fabric's own convention-based Reverse Proxy, which applies the hardcoded template `http://localhost:19081/{applicationName}/{serviceName}/{**catchall}` and proxies to destination cluster `fabric:/{applicationName}/{serviceName}`, dynamically discovering specific destination addresses on the fly.

The discussion on this thread so far has focused on simplifying how `destinations` are specified within a `cluster` and adding capabilities of ad-hoc dynamic discovery of destinations within a cluster denoted only by its Service fabric service uri (`fabric:/appName/svcName`). The point above hints at a similar possibility of simplification at the `cluster` / `route` level, making them parameterizable by route params.

**Comment by Tratcher** [comment]
> Let's also consider #46 when coming up with a design for this one.

I think we're planning to close #46 as adequately addressed by https://microsoft.github.io/reverse-proxy/articles/direct-proxying.html. We have a few different partners testing that approach now.

**Comment by Tratcher** [comment]
SF work has moved to https://github.com/microsoft/service-fabric-yarp
