### ISSUE TITLE
Simple circuit breaking (passive health-check)

### ISSUE THREAD

**Issue by samsp-msft** [microsoft/reverse-proxy#57]
Mark a back end node unhealthy when a request fails.

There will typically be a bunch of policy about how many failures are required to trip the circuit and when to retry the back end to see if it has recovered. This item is to ensure we have the plumbing to be able do circuit breaking, but not necessarily to create an all encompassing circuit breaking module.

**Comment by Tratcher** [comment]
Completed by https://github.com/microsoft/reverse-proxy/pull/459
