### ISSUE TITLE
Load balancing algorithms

### ISSUE THREAD

**Issue by samsp-msft** [microsoft/reverse-proxy#58]
Complete the set of common load balancing schemes
* Round Robin
* Random
* ~~First healthy endpoint~~ (already implemented)

**Comment by Tratcher** [comment]
Current implementation:
https://github.com/microsoft/reverse-proxy/blob/be96d64cb0fb732e5a31aebb91e0b9350798d62a/src/ReverseProxy.Core/Service/Proxy/LoadBalancer.cs#L21-L36

Note that load balancing is configurable per backend set. Do we need that level of granularity, or could this be specified server wide?

**Comment by anurse** [comment]
Oh it should definitely be per backend. It's very common for different services to have different load profiles and benefit from different kinds of load balancing. It's also something [Envoy configures per-cluster](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/cluster.proto#envoy-api-enum-cluster-lbpolicy) which serves as some prior art.

**Comment by Tratcher** [comment]
Another one: Least busy
We have the metadata we need for this, it just requires one pass through the list.

**Comment by Kahbazi** [comment]
Is it possible to add a feature for blue green deployment to load balancer? or is it out of the scope of load balancer?

**Comment by Tratcher** [comment]
> Is it possible to add a feature for blue green deployment to load balancer? or is it out of the scope of load balancer?

I think that's a different feature from load balancing that would be handled earlier at the routing phase. Load balancing assumes all nodes are equivalent, plus or minus health/load.

**Comment by anurse** [comment]
I'm going to break this up into smaller issues for individual algorithms. @Tratcher and I were talking about some of them being fairly easy and high-value for preview 1 (while others are more complicated).

**Comment by anurse** [comment]
Created #72 #73 #74 #75

Closing this out now.
