### ISSUE TITLE
[SF] Label parsing is inefficient

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#586]
The service fabric label parsing code is really inefficient.
https://github.com/microsoft/reverse-proxy/blob/23a572bc0b54c4975869786d5e003159efdc2cb9/src/ReverseProxy.ServiceFabric/ServiceDiscovery/Util/LabelsParser.cs#L80

The pattern `$"{thisRoutePrefix}.Foo."` is used repeatedly and it creates a lot of the same garbage strings over and over again. The new Transforms support extends the problem (https://github.com/microsoft/reverse-proxy/pull/532).

SF polls for changes, so this code could be run quite frequently and evaluate many services. Review this whole code path for ways to reduce allocations.

**Comment by alnikola** [comment]
Pre-triage: It seems rather expensive so moving to backlog for now, since we are wrapping up the current iteration of SF integration.

**Comment by alnikola** [comment]
On the second thought, I might cause a substantial perf downgrade in some scenarios. Moving back to 'untriaged' to discuss it further.
