### ISSUE TITLE
Expose route metadata so that we can read it from a custom middleware

### ISSUE THREAD

**Issue by goenning** [microsoft/reverse-proxy#587]
### What should we add or change to make your life better?

Expose route metadata so that we can read it from a middleware to build custom logic based on it

### Why is this important to you?

I'm looking to perform body transformation which will vary per route, so the idea is to store a hint on the metadata and use that on a middleware. Example:

```json
{
    "RouteId": "route1",
    "ClusterId": "cluster1",
    "Match": {
        "Hosts": [
            "example.com"
        ]
    },
    "Metadata": {
        "RequestBodyTransform": "Tranformation1",
    }
}
```

Startup.cs
```csharp
endpoints.MapReverseProxy(proxyPipeline =>
{
    proxyPipeline.UseMiddleware<MyMiddleware>();
});
```

MyMiddleware.cs
```csharp
public async Task Invoke(HttpContext context)
{
    var route = context.GetProxyRoute();
    if (route.Metadata["RequestBodyTransform"] == "Tranformation1")
    {
        ...
    }

    await _next(context);
}
```

Ref: https://github.com/microsoft/reverse-proxy/discussions/576

**Comment by samsp-msft** [comment]
Triage: needs some design.
