### ISSUE TITLE
[SF] Define time intervals as timespans not seconds

### ISSUE THREAD

**Issue by alnikola** [microsoft/reverse-proxy#589]
Time intervals in SF service manifest are currently defined as integer numbers of seconds (e.g. `75`) whereas in regular config files they are defined as timespans (e.g. `00:01:25`). We should make it consistent so that all time intervals are defined as timespans.

Before:
```
<Label Key='YARP.Backend.HealthCheck.Active.Timeout'>30</Label>
```

After:
```
<Label Key='YARP.Backend.HealthCheck.Active.Timeout'>00:00:30</Label>
```

**Comment by samsp-msft** [comment]
Triage: putting on backlog, but blocking SF release
