### ISSUE TITLE
Active Health Checks of destinations

### ISSUE THREAD

**Issue by samsp-msft** [microsoft/reverse-proxy#59]
Creating a simple out of band (not part of proxied requests) to confirm the health status of back ends.

a) Polling back ends to see if they are alive
b) Eliminating dead entries from load balancing

**Comment by anurse** [comment]
We believe this is already at least partially implemented in the original prototype code, so this is mostly about reviewing that code and ensuring it meets our needs.

**Comment by samsp-msft** [comment]
Duplicate of #228
