### ISSUE TITLE
[SF] Add docs on replica endpoint selection logic

### ISSUE THREAD

**Issue by alnikola** [microsoft/reverse-proxy#590]
SF replicas can expose multiple endpoints for requests and health probes. YARP currently supports only one endpoint of each type whose selection is controlled by `ServiceFabric.ListenerName` and `HealthCheck.Active.ServiceFabric.ListenerName` parameters respectively. Though, the detailed description of this logic is missing. We need to better document it.

**Comment by samsp-msft** [comment]
related to #541
