### ISSUE TITLE
[SF] Remove redundant `YARP.` prefix from SF label names

### ISSUE THREAD

**Issue by alnikola** [microsoft/reverse-proxy#591]
All of SF service manifest's extension labels names start with 'YARP.' prefix despite the fact they are residing inside the section named 'YARP-preview' Let's get rid of those redundant prefixes.

Before:
```
<Label Key="YARP.Enable">true</Label>
<Label Key="YARP.Routes.route1.Path">{**catch-all}</Label>
<Label Key="YARP.Backend.HealthCheck.Active.Enabled">true</Label>
```

After:
```
<Label Key="Enable">true</Label>
<Label Key="Routes.route1.Path">{**catch-all}</Label>
<Label Key="Backend.HealthCheck.Active.Enabled">true</Label>
```

**Comment by samsp-msft** [comment]
Triage: Putting on backlog - it would be a breaking change so needs to be done before we declare SF released.

**Comment by Tratcher** [comment]
Moved to https://github.com/microsoft/service-fabric-yarp/issues/8
