### ISSUE TITLE
Custom request/response modifications via code transforms

### ISSUE THREAD

**Issue by samsp-msft** [microsoft/reverse-proxy#60]
Ability to customize headers (beyond x-forward or affinity) from code extensibility for both request to back end, and response to the the client.

**Comment by Tratcher** [comment]
See feedback from https://github.com/microsoft/reverse-proxy/pull/225#discussion_r441143683 about config formats and how that may affect extensibility.

**Comment by AJAnderhub** [comment]
I would second the need for custom header modifications. Prepending to response headers would the use case for my scenario.

**Comment by robbieknuth** [comment]
+1, I have a need to modify headers in an ad-hoc fashion. Concrete scenario is ripping an auth token from a cookie and setting that as the Authorization header. This would eliminate my need for CORS entirely and simplify my api server to be jwt only, resulting in all client-ish things on the client server.

**Comment by Tratcher** [comment]
Requirements summary:
- Someone can write code to modify request and response parameters/headers.
- That code can be associated with specific routes via config, including parameters.
- Config validation can validate parameters for transforms.
- Transforms compose so you don't have to write one uber transform.
- Transformations need to allow async code.

Example scenarios:
- Swap auth format: https://github.com/microsoft/reverse-proxy/issues/416
