### ISSUE TITLE
X-Forwarded[Append] support Ignore if there is

### ISSUE THREAD

**Issue by u-less** [microsoft/reverse-proxy#606]
### What should we add or change to make your life better?

For multi-layer agents, it is enough to keep the value of the first head

### Why is this important to you?

'Swashbuckle.AspNetCore.SwaggerGen' multiple values for head are not supported

**Comment by Tratcher** [comment]
How do you end up with the x-forwarded headers on some requests and not others? That implies your layering or your agents are inconsistent. If they were consistent then you'd be able to turn x-forwarded off in YARP.
