### ISSUE TITLE
IClusterChangeListener singleton ?

### ISSUE THREAD

**Issue by 3GDXC** [microsoft/reverse-proxy#613]
I would like to register additional IClusterChangeListerners to the DI system; so I may hook into these events and update the Microsoft.Extensions.Diagnostics.HealthChecks and subsequently the health UI reports will display cluster status.

**Comment by Tratcher** [comment]
Multiple listeners are supported:
https://github.com/microsoft/reverse-proxy/blob/05a60d0ae5913d73e7a1f12d4cc50e9011081a30/src/ReverseProxy/Service/Management/ClusterManager.cs#L16

Singleton has to do with object lifetime (it lives for the lifetime of the app), not how many there are.

See https://github.com/microsoft/reverse-proxy/issues/125 for related discussions about proxy health.

> Ideally the internal sealed class ClusterManager should be made non-sealed public class so a developer could derive from it and implement addition logic/rules etc.
> 
> i.e. if a cluster is added/removed we'd like a message set to a remote alerting/monitoring systems

You should be able to do that with the IClusterChangeListeners.

**Comment by karelz** [comment]
Triage: We are pretty sure it works (we're using it for HealthChecks). Can you please provide (simplified) repro for us?

**Comment by karelz** [comment]
Triage: No repro, closing. Feel free to reopen if there is more evidence. Thanks!
