### ISSUE TITLE
Test 100-continue scenarios

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#617]
https://github.com/microsoft/reverse-proxy/blob/37ed6a93f3ea54cc412471ca85ac9b3e38aca749/src/ReverseProxy/Service/Proxy/HttpProxy.cs#L182-L186

That code makes an assumption that request bodies are always read, which is likely false in the case of 100-continues. That check is also one of the few places where it would be problematic if a transform replaced the HttpContent object, the Started property wouldn't be available.

This exception should probably be removed.

**Comment by karelz** [comment]
Triage: Common in Auth scenarios. Protocol completeness.

**Comment by davidni** [comment]
@Karelz shall I send a PR for this or is someone already on it? We have been running with this patched for a while in prod now, and we need this fixed to fully adopt YARP.

**Comment by karelz** [comment]
@davidni yes please!!! :)

**Comment by Tratcher** [comment]
Update: @davidni sent a PR to remove the broken condition. We still want to add more automated tests here.

**Comment by Tratcher** [comment]
Re-opening. #1038 only covered a very narrow scenario, we need functional tests to make sure the end-to-end works as expected. Mainly that the proxy does not cause a 100-continue to be sent prematurely, and that everything still works when a 4xx is received.

`Expect: 100-continue` scenarios:
A) HTTP/1.1 POST with a Content-Length is proxied over HTTP/1.1, destination responds with a 100 Continue, the proxy responds with a 100 Continue, the data is uploaded, there's a 200 response.
B) HTTP/1.1 POST with a Transfer-Encoding is proxied over HTTP/1.1, destination responds with a 100 Continue, the proxy responds with a 100 Continue, the data is uploaded, there's a 200 response.
C) A & B proxied over HTTP/2
D) HTTP/1.1 POST with a Content-Length is proxied over HTTP/1.1, destination responds with a 4xx, the data gets uploaded anyways.
E) D but with Transfer-Encoding.
F) HTTP/1.1 POST with a Content-Length is proxied over HTTP/2, destination responds with a 4xx and a RESET, the proxy app (kestrel) drains the request body.
G) HTTP/2 POST with a Content-Length is proxied over HTTP/2, destination responds with a 4xx and a RESET, the proxy app (kestrel) sends the 4xx and a RESET to cancel the body.

How do we actually confirm a 100-continue is sent/received in a functional test? That's all hidden by the http stacks.

**Comment by Tratcher** [comment]
https://github.com/dotnet/runtime/issues/53914 is an example of why we need test converge for this.
