### ISSUE TITLE
QueryParameterTransform should allow URL parameter with value that is empty string

### ISSUE THREAD

**Issue by weichch** [microsoft/reverse-proxy#619]
### Describe the bug
I'm proxying request from `http://source/path` to `http://destination/path?param1=&param2=value`, with two transforms:
```c#
new QueryParameterFromStaticTransform(QueryStringTransformMode.Set,"param1","")
new QueryParameterFromStaticTransform(QueryStringTransformMode.Set,"param2","value")
```
However, `param1` is dropped while being applied to `RequestParametersTransformContext` due to [this line of code](https://github.com/microsoft/reverse-proxy/blob/master/src/ReverseProxy/Service/RuntimeModel/Transforms/QueryParameterTransform.cs#L30).

Empty string is valid variable value as per [RFC 6570](https://tools.ietf.org/html/rfc6570) and in my case the destination server cannot work without `param1`.

### To Reproduce

```c#
var context = new RequestParametersTransformContext
{
    Query = new QueryTransformContext(HttpContext.Request)
};
new QueryParameterFromStaticTransform(QueryStringTransformMode.Set, "Empty", "").Apply(context);

// url should equal to ?Empty= but is empty string atm
var url = context.Query.QueryString.ToString();
```

### Further technical details

- Include the version of the packages you are using
**Package version:** 1.0.0-preview.7.20562.2
**ASP.NET version:** .NET Core 3.1 and .NET 5
- The platform (Linux/macOS/Windows)
Windows

**Comment by Tratcher** [comment]
That makes sense, but it's going to require some design changes. Most transforms use the return of an empty value to indicate the header, query param, etc, should be removed. You're right that an empty query param is valid, though I don't know how common it is to require its presence. We'll have to re-think how transforms indicate removal.

**Comment by karelz** [comment]
Triage: Distinguish between empty string and null?
Given that it affects design, we should do it in 1.0.

**Comment by weichch** [comment]
@Tratcher I agree it's not commonly seen but unfortunately our destination server uses the key of the parameter instead of the value. I was thinking a new property `AllowEmptyValue` which defaults to `false`, then I can explicitly set it to `true` when needed. Similar to [OpenAPI specs](https://swagger.io/docs/specification/describing-parameters/):

> **Empty-Valued and Nullable Parameters**
Query string parameters may only have a name and no value, like so:
GET /foo?metadata
Use allowEmptyValue to describe such parameters:
