### ISSUE TITLE
Support W3C Baggage header

### ISSUE THREAD

**Issue by Kahbazi** [microsoft/reverse-proxy#621]
### What should we add or change to make your life better?
Add an options in `ActivityPropagationHandler` to choose whether it will use `Correlation-Context` or `baggage` header, or maybe both! 

Related to https://github.com/dotnet/aspnetcore/pull/28328.

### Why is this important to you?
To follow the current standard.

**Comment by karelz** [comment]
Triage: We might need to send both values (old one and new one). We can do it earlier than Runtime (which has separate issue).

**Comment by karelz** [comment]
@Kahbazi do you want to take the work?

**Comment by Kahbazi** [comment]
> @Kahbazi do you want to take the work?

@karelz Yes, I do.
