### ISSUE TITLE
Support AllowAnonymous for ProxyRoute.AuthorizationPolicy

### ISSUE THREAD

**Issue by Kahbazi** [microsoft/reverse-proxy#622]
### What should we add or change to make your life better?
Now that we could add authorization metadata for multiple routes at a time, perhaps it makes sense to support `AllowAnonymous` for `ProxyRoute.AuthorizationPolicy`.
### Why is this important to you?
It's a good feature to have when we want to authorize all routes on a cluster but exclude some of them.

**Comment by karelz** [comment]
Triage: We expect auth customers to run into it eventually -> v1
