### ISSUE TITLE
DangerousAcceptAnyServerCertificate is true by default

### ISSUE THREAD

**Issue by Kahbazi** [microsoft/reverse-proxy#623]
### Describe the bug
The document states that the default value for `DangerousAcceptAnyServerCertificate` is `false`.

> DangerousAcceptAnyServerCertificate - indicates whether the server's SSL certificate validity is checked by the client. Setting it to true completely disables validation. Default value is false.

Now this seems it's handled in `ProxyHttpClientFactory`
https://github.com/microsoft/reverse-proxy/blob/71fc0df89c1e20dace44433429dd88a0feaaccf5/src/ReverseProxy/Service/Proxy/Infrastructure/ProxyHttpClientFactory.cs#L63

but it's actually set to `true` if it's not set in `ConfigurationConfigProvider`
https://github.com/microsoft/reverse-proxy/blob/e4426b93621a4f0e4c55c626236a21404efd264e/src/ReverseProxy/Configuration/ConfigurationConfigProvider.cs#L335

### To Reproduce
`cluster1` in this `appsettings.json`  would have `DangerousAcceptAnyServerCertificate` as true.
```
"Clusters": {
  "cluster1": {
    "HttpClient": {
      "MaxConnectionsPerServer": 2
    }
  }
}
```

**Comment by karelz** [comment]
Triage: Thanks for catching it @Kahbazi! That is not intentional. Do you want to submit PR? Or should we do it?
We should just remove the `true` default and leave it `null`.

**Comment by karelz** [comment]
That was super fast :O ... thanks a lot @Kahbazi!
