### ISSUE TITLE
gRPC support

### ISSUE THREAD

**Issue by mohsenShakiba** [microsoft/reverse-proxy#625]
### Describe the bug
The YARP library doesn't proxy gRPC requests. if I'm wrong please tell me if there are any extra steps for configuring YARP for supporting gRPC.

### To Reproduce
setting up a gRPC service and configuring YARP to proxy to that service will result in client receiving 502 status code.

**Comment by Tratcher** [comment]
gRPC is fully supported. There's likely a configuration issue so it can't communicate with the destination. Can you share the debug level logs and the proxy configuration?
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-5.0#configure-logging

**Comment by mohsenShakiba** [comment]
tank you for your response, I will further investigate the issue.
