### ISSUE TITLE
Raise an error when reserved keywords for auth and CORS is used

### ISSUE THREAD

**Issue by Kahbazi** [microsoft/reverse-proxy#634]
### What should we add or change to make your life better?
There are multiple keywords for authorization and CORS policy, which yarp has special behavior for them. There could be an exception or at least error log if those keywords are actually a valid policy in ASP.Net Core authorization or CORS. 

### Why is this important to you?
Having a log will save time in troubleshooting why specific policy is not running.

**Comment by Tratcher** [comment]
You mean here where we check for special values but otherwise pass it through to IAuthorizationPolicyProvider?
https://github.com/microsoft/reverse-proxy/blob/5758d7fa692af72c6ba07ba60044eb51df9d7af3/src/ReverseProxy/Service/Config/ConfigValidator.cs#L234-L250

You would want it to generate an error if "Default" or "Anonymous" was an actual registered auth policy?

I wonder how common a mistake that would be.

**Comment by Kahbazi** [comment]
> You would want it to generate an error if "Default" or "Anonymous" was an actual registered auth policy what we ended up ignoring?

Yes.

> I wonder how common a mistake that would be.

It could be rare the cases that someone might add a policy named "default" instead of setting the `DefaultPolicy`.

**Comment by stefannikolei** [comment]
Wouldn't it be good to have an Analyzer for that?

**Comment by Tratcher** [comment]
@stefannikolei this is an error in data that would normally be pulled from outside the app at runtime. Analyzer's only apply during development.

**Comment by karelz** [comment]
Triage: We should wait for demand. Does not seem to be too common ...

**Comment by Kahbazi** [comment]
> Triage: We should wait for demand. Does not seem to be too common ...

I don't think any customer would demand this feature because it's just an error for preventing customer to ignore the policies.
Since this is labeled Help Wanted, do you accept PR for it?

**Comment by Tratcher** [comment]
> Since this is labeled Help Wanted, do you accept PR for it?

Sure, though we'd prefer to focus on the Help Wanted items in YARP 1.0.0 first.
https://github.com/microsoft/reverse-proxy/labels/help%20wanted
