### ISSUE TITLE
Sending 200 OK throws exception in RequestParametersTransform

### ISSUE THREAD

**Issue by KSib** [microsoft/reverse-proxy#639]
For reference, I'm using Microsoft.ReverseProxy 1.0.0-preview.7.20562.2 in an empty ASP.NET Web Application using .NET 5.

I can't figure out how to get a similar IIS URL Rewrite action to happen the same way in YARP without it throwing an exception. The below is what I'm trying to imitate:

![image](https://user-images.githubusercontent.com/1589238/102815842-ac4dd400-4392-11eb-96d5-28cc5af1389b.png)

Basically, I'm using the `RequestParametersTransform`'s Apply method to catch a some header data and HTTP OPTIONS. If the data is what I'm expecting then return a 200 OK. The problem is when I do this, an exception is logged. It actually works as it is, but I'd prefer the exception to not be thrown. Here's a basic idea of what I'm doing, but I'm not sure how best to go about this.

What is the ideal way to intercept a request and then return a 200OK early? should I instead store something in the request and then process that a class that implements `ResponseHeaderTransform`?

```csharp

public override void Apply(RequestParametersTransformContext context)
        {
            context.HttpContext.Request.Headers.TryGetValue("origin", out StringValues originValues);
            var originString = originValues.FirstOrDefault();

            // Intercept the OPTIONS HTTP method for CORS Preflight
            if (context.HttpContext.Request.Method == HttpMethod.Options.Method)
            {
                if (OriginCheckService.IsHostAllowed(originString))
                {
                    context.HttpContext.Response.StatusCode = StatusCodes.Status200OK;

                    // If the origin is allowed, then change up the response headers
                    context.HttpContext.Response.Headers["Access-Control-Allow-Origin"] = originString;
                    context.HttpContext.Response.Headers["Access-Control-Allow-Headers"] = "kbn-version,content-type";
                    context.HttpContext.Response.Headers["Access-Control-Allow-Credentials"] = "true";

                    context.HttpContext.Response.WriteAsync(string.Empty).GetAwaiter().GetResult();

                    return;
                }

                throw new BadHttpRequestException($"2: Unable to process CORS pre-flight request. Origin '{originString}' not allowed.");
            }

            // We use this as the general proxy to the ELK server
            if (OriginCheckService.IsHostAllowed(context.HttpContext.Request.Host.Value))
            {
                context.HttpContext.Response.Headers["Access-Control-Allow-Origin"] = originString;
                context.HttpContext.Response.Headers["Access-Control-Allow-Credentials"] = "true";
                return;
            }
        }
```

The error that's thrown is the following:

An unhandled exception was thrown by the application.
System.InvalidOperationException: StatusCode cannot be set because the response has already started.
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.ThrowResponseAlreadyStartedException(String name)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.set_StatusCode(Int32 value)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.Microsoft.AspNetCore.Http.Features.IHttpResponseFeature.set_StatusCode(Int32 value)
   at Microsoft.AspNetCore.Http.DefaultHttpResponse.set_StatusCode(Int32 value)
   at Microsoft.ReverseProxy.Service.Proxy.HttpProxy.CopyResponseStatusAndHeaders(HttpResponseMessage source, HttpContext context, IReadOnlyDictionary`2 transforms)
   at Microsoft.ReverseProxy.Service.Proxy.HttpProxy.ProxyAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, RequestProxyOptions proxyOptions)
   at ReverseProxy.Startup.<>c__DisplayClass5_0.<<Configure>b__1>d.MoveNext() in C:\Users\[redacted]\Documents\Code Play\ReverseProxy\ReverseProxy\Startup.cs:line 88
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()

**Comment by Tratcher** [comment]
Let's back up a step first. Have you tried the built in CORS support? https://microsoft.github.io/reverse-proxy/articles/cors.html

Transforms do not support early termination. The exception is happening because you're writing a response, YARP proxies the request anyways, and it then tries to write the response again.

For early termination scenarios you'd need to write middleware. See here:
https://github.com/microsoft/reverse-proxy/blob/c51f60bc800b2ca798cfe66d6db2baccad3f5811/samples/ReverseProxy.Code.Sample/Startup.cs#L73-L88

**Comment by KSib** [comment]
I tried the CORS thing and I swear it didn't work for what I was wanting. I'll give it another go though. It seemed like it was placing CORS in front of my Kibana instance, but it was still failing Kibana's CORS check.

However, now that I think about it, I didn't use CORS and 

```csharp
  // We use this as the general proxy to the ELK server
            if (OriginCheckService.IsHostAllowed(context.HttpContext.Request.Host.Value))
            {
                context.HttpContext.Response.Headers["Access-Control-Allow-Origin"] = originString;
                context.HttpContext.Response.Headers["Access-Control-Allow-Credentials"] = "true";
                return;
            }
```

this code together. It seems like this is necessary as well

**Comment by KSib** [comment]
So here's what I'm doing and I would expect this to work, but it's not:

```csharp
 public void ConfigureServices(IServiceCollection services)
        {
            services.AddAuthorization();

            services.AddCors(options =>
            {
                options.AddPolicy("customPolicy", builder =>
                {
                    //builder.AllowCredentials();
                    builder.AllowAnyOrigin();

                    //var allowedOrigins = Configuration.GetValue<string[]>("CustomSettings:AllowedHosts");

                    //builder.WithOrigins(allowedOrigins);
                });
            });

            services.AddHttpProxy();

            services.Configure<CustomSettings>(options => Configuration.GetSection("CustomSettings").Bind(options));
            services.AddSingleton<IOriginCheckService, OriginCheckService>(x =>
            {
                var customSettings = x.GetRequiredService<IOptions<CustomSettings>>();
                return new OriginCheckService(customSettings);
            });
        }
```

```csharp
 public void Configure(IApplicationBuilder app, IWebHostEnvironment env, IHttpProxy httpProxy, 
                              IOriginCheckService originCheckService, IOptions<CustomSettings> customSettings)
        {
            var httpClient = new HttpMessageInvoker(new SocketsHttpHandler()
            {
                UseProxy = false,
                AllowAutoRedirect = false,
                AutomaticDecompression = DecompressionMethods.None,
                UseCookies = false
            });

            var proxyOptions = new RequestProxyOptions()
            {
                RequestTimeout = TimeSpan.FromSeconds(100),
                // Copy all request headers except Host
                Transforms = new Transforms(
                    copyRequestHeaders: true,

                    requestTransforms: new List<RequestParametersTransform>() { new RequestTransformations(originCheckService) },

                    requestHeaderTransforms: new Dictionary<string, RequestHeaderTransform>()
                    {
                        { HeaderNames.Host, new RequestHeaderValueTransform(string.Empty, append: false) }
                    },

                    responseHeaderTransforms: new Dictionary<string, ResponseHeaderTransform>()
                    {
                        { string.Empty, new ResponseTransformations() }
                    },

                    responseTrailerTransforms: new Dictionary<string, ResponseHeaderTransform>())
            };

            app.UseRouting();
            app.UseCors();
            app.UseAuthorization();
            app.UseEndpoints(endpoints =>
            {
                endpoints.Map("/{**catch-all}", async httpContext =>
                {
                    await httpProxy.ProxyAsync(httpContext, customSettings.Value.ProxyTarget, httpClient, proxyOptions);

                    var errorFeature = httpContext.Features.Get<IProxyErrorFeature>();
                    if (errorFeature != null)
                    {
                        var error = errorFeature.Error;
                        var exception = errorFeature.Exception;
                    }
                });
            });
        }
```

When I set it up this way, I get this in the console:

Access to XMLHttpRequest at 'https://dev-elkreporting.development.[redacted].com/internal/security/login' from origin 'https://localhost:44353' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

The way I understand it is that this is supposed to prevent that by basically doing something similar to what I had coded. Intercept the OPTIONS request and allow whatever origin was specified and also prevent any Allow-Origin header errors from happening. Am I misunderstanding this?

**Comment by Tratcher** [comment]
Nothing is invoking your customPolicy, it needs to be associated with your Map endpoint. Something like this:
https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-5.0#enable-cors-with-endpoint-routing
```
            endpoints.MapGet("/echo",
                context => context.Response.WriteAsync("echo"))
                .RequireCors(MyAllowSpecificOrigins);
```

**Comment by KSib** [comment]
Thanks. It looks like this is what I was needing. The documentation made it look like the "customPolicy" is magically used somehow from the code. 

In the help doc here: https://microsoft.github.io/reverse-proxy/articles/cors.html I would probably include a bit of code that references it since this below code apparently isn't tied to this above 

```csharp
options.AddPolicy("customPolicy", builder =>
        {
            builder.AllowAnyOrigin();
        });
```

```csharp
app.UseEndpoints(endpoints =>
    {
        endpoints.MapReverseProxy();
    });
```

**Comment by Tratcher** [comment]
YARP CORS support is wired up using MapReverseProxy and config:
```
{
  "ReverseProxy": {
    "Routes": [
      {
        "RouteId": "route1",
        "ClusterId": "cluster1",
        "CorsPolicy": "customPolicy",
```

When you're doing manual routing with MapGet to IHttpProxy you're using basic ASP.NET Core components, and need to use their CORS support.
