### ISSUE TITLE
Request body too large

### ISSUE THREAD

**Issue by dbinkert** [microsoft/reverse-proxy#640]
For reference, we are using Microsoft.ReverseProxy 1.0.0-preview.7.20562.2 in an empty ASP.NET Web Application using .NET 5, running with Kestrel

On larger requests we receive the following error:

RequestBodyClient: "The client reported an error when copying the request body." (1474d177)
System.AggregateException: One or more errors occurred. (Request body too large.) (Error while copying content to a stream.)

Is it possible to increase the size and how can we do this?

**Comment by Tratcher** [comment]
That can be set at the server level (for all requests) as shown here:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-5.0#maximum-request-body-size

We should make this configurable per route.

**Comment by aDisplayName** [comment]
Any update on this?

**Comment by Tratcher** [comment]
@aDisplayName This is a default limit on request sizes in aspnetcore. You can change it at the server level or per request, it's just not exposed in the YARP config model. What level do you need to change it at? For all routes? For one route? For specific requests?

**Comment by MihaZupan** [comment]
It is currently milestoned for YARP 2.0.

In the meantime, you can still modify the limits programmatically on a per-request granularity.

**Comment by Tratcher** [comment]
Or via custom transforms.

**Comment by Tratcher** [comment]
Related: https://github.com/dotnet/aspnetcore/issues/40452
We can add metadata to routes, but we'll also need something to read it and update the per request feature.

**Comment by Tratcher** [comment]
FYI https://github.com/microsoft/reverse-proxy/pull/1947
