### ISSUE TITLE
Track & handle error when user replaced Content in HttpProxy

### ISSUE THREAD

**Issue by Kahbazi** [microsoft/reverse-proxy#644]
> https://github.com/microsoft/reverse-proxy/blob/6ff471c5417daa1c65ba886bd53e05f7370a2d2d/src/ReverseProxy/Service/Proxy/HttpProxy.cs#L290

We could check if to see if the `destinationRequest.Content` is anything but `StreamCopyHttpContent` before sending the request.
https://github.com/microsoft/reverse-proxy/blob/6ff471c5417daa1c65ba886bd53e05f7370a2d2d/src/ReverseProxy/Service/Proxy/HttpProxy.cs#L130

and if it changed replace it with another `HttpContent` wrapper like `StreamCopyHttpContent` but it would wrap the `HttpContent` that user has set.

**Comment by Tratcher** [comment]
We'll probably wait to make a decision here until we see someone try to replace the content and can figure out their scenario for doing so.

**Comment by karelz** [comment]
Triage: We think this is very theoretical at this point. Not worth checking.
2 scenarios:
- Wrapping our stream -- likely OK
- Replacing our stream entirely -> Bad thing s will happen as we lose tracking (telemetry, state checks - error handling)

Closing now, let's wait for understanding when someone really runs into it and why.
