### ISSUE TITLE
DNS services

### ISSUE THREAD

**Issue by grahamehorner** [microsoft/reverse-proxy#647]
The reverse-proxy IMHO seem a logic place to hold DNS records (cache) and/or filter/forward DNS queries for the services behind the proxy; this could of course be a service in its own right, however having a DNS resolver that is used by only the service behind the proxy could/would also offer benefits like service discovery and dynamic resolution of services and/or addition cluster nodes when scaling up.

Please consider adding the ability to host a DNS service with in the reverse-proxy and/or some event hooks with regards DNS caching/record expiry.

**Comment by Tratcher** [comment]
There are two dimensions to this: incoming and outgoing requests.

Incoming: YARP is an HTTP proxy, it does not participate in the DNS resolution process for clients. You can however set up your deployment using a service-mesh architecture where all requests are sent to a local proxy and then it does handle forwarding, DNS, etc. as an outgoing concern.

Outgoing: Today YARP is build on HttpClient which uses the OS DNS libraries, it has little control over the DNS process. However, there are new features being considered for HttpClient that would give more control here, such as the new [ConnectCallback](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler.connectcallback?view=net-5.0#System_Net_Http_SocketsHttpHandler_ConnectCallback) that can be used to customize the socket creation process, including handle the DNS resolution.

Do either of these match the scenarios you had in mind?

**Comment by karelz** [comment]
Triage: We think the DNS scenarios are/should be covered on different levels (HttpClient)
