### ISSUE TITLE
Improve TransformRequestAsync, TransformResponseAsync & TransformResponseTrailersAsync in non-async path

### ISSUE THREAD

**Issue by Kahbazi** [microsoft/reverse-proxy#663]
Currently all request and response transformers are sync. Since the transformers are in the hot path, can we improve `TransformRequestAsync`, `TransformResponseAsync` & `TransformResponseTrailersAsync` by removing the async-await in the main method and return a `Task` directly?

This is what I have in mind:

```csharp
public Task TransformResponse()
{
    if (ShouldCopyResponseHeaders.GetValueOrDefault(true))
    {
        var task = base.TransformResponseAsync(httpContext, proxyResponse);
        if (!task.IsCompletedSuccessfully)
        {
            return TransformResponseWithAwait(task);
        }
    }

    if (ResponseTransforms.Count == 0)
    {
        return Task.CompletedTask;
    }

    var transformContext = new ResponseTransformContext()
    {
        HttpContext = httpContext,
        ProxyResponse = proxyResponse,
        HeadersCopied = ShouldCopyResponseHeaders.GetValueOrDefault(true),
    };

    for (int i = 0; i < ResponseTransforms.Count; i++)
    {
        var task = ResponseTransforms[i].ApplyAsync(transformContext);

        if (!task.IsCompletedSuccessfully)
        {
            return TransformResponseWithAwait(task, i, ResponseTransforms);
        }
    }

    return Task.CompletedTask;
}
```

**Comment by Tratcher** [comment]
It adds some complexity, but it might be worth it.  I'd wait until after we've worked out a few more parts of the object model like #60.

**Comment by karelz** [comment]
Triage: Do experiment, profile before and after.

**Comment by Kahbazi** [comment]
I will take this task. What's the best way to profile the changes?

**Comment by MihaZupan** [comment]
If you point me to a buildable branch, I can run the change through our perf infra.

**Comment by Kahbazi** [comment]
@MihaZupan Here's the changes https://github.com/microsoft/reverse-proxy/pull/775.
