### ISSUE TITLE
Is there any timeline of when you'll release the Service Fabric NuGet packages/docs?

### ISSUE THREAD

**Issue by WhitWaldo** [microsoft/reverse-proxy#664]
### Some details

**How many backends are in your application?**

- [ ] 1-2
- [ ] 3-5
- [ ] 6-10
- [X ] 10+

**How do you host your application?**

- [ ] Kubernetes
- [ ] Azure App Service
- [ ] Azure VMs
- [ ] Other Cloud Provider (please include details below)
- [ X] Other Hosting model (please include details below)
Azure Service Fabric

### What did you think of YARP?
I think it's a terrific idea and a long time coming. I've been following the various [Service Fabric pull requests](https://github.com/microsoft/reverse-proxy/pulls?q=is:pr+service+fabric) in anticipation of trying this out in my own solution, but each time I circle back, neither the docs are live nor is the Nuget package available. 

Is there any sort of anticipated timeline around when you might be releasing Service Fabric support or any sort of documentation detailing what outstanding items stand in the way of this?

Thank you!

**Comment by karelz** [comment]
It will be part of upcoming Preview8 -- see docs: https://github.com/microsoft/reverse-proxy/blob/master/docs/docfx/articles/service-fabric-int.md
That should hopefully answer all your questions above.

**Comment by WhitWaldo** [comment]
Very exciting, thank you.
