### ISSUE TITLE
Use HttpCompletionOption.ResponseHeadersRead in HttpClient.SendAsync

### ISSUE THREAD

**Issue by Kahbazi** [microsoft/reverse-proxy#67]
Does setting `HttpCompletionOption.ResponseHeadersRead` in `HttpClient.SendAsync` improve performance?
https://github.com/microsoft/reverse-proxy/blob/bc9298322206f35e7d658183464cdf806280143f/src/ReverseProxy.Core/Service/Proxy/HttpProxy.cs#L158

**Comment by samsp-msft** [comment]
@scalablecory I think HttpCompletionOption.ResponseHeadersRead is the default?

**Comment by Kahbazi** [comment]
It seems `HttpCompletionOption.ResponseContentRead` is default for `SendAsync()`
https://github.com/dotnet/runtime/blob/c06810bf654e09f016fe34dd2b4ac31fb73370a1/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs#L22
https://github.com/dotnet/runtime/blob/c06810bf654e09f016fe34dd2b4ac31fb73370a1/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs#L450
