### ISSUE TITLE
Missing release notes

### ISSUE THREAD

**Issue by jmezach** [microsoft/reverse-proxy#671]
I noticed that preview 8 is up on NuGet and has also been tagged here on GitHub but no release notes are available. I was wondering what's new in this release and also if there are any breaking changes we should be aware of?

**Comment by MihaZupan** [comment]
Thank you for pointing this out, release notes have now been added for preview 8, along with the list of breaking changes:

https://github.com/microsoft/reverse-proxy/releases/tag/v1.0.0-preview8

**Comment by jmezach** [comment]
Thanks! Much appreciated.
