### ISSUE TITLE
Add support for HttpClientFactory named clients

### ISSUE THREAD

**Issue by mcm-ham** [microsoft/reverse-proxy#672]
### What should we add or change to make your life better?

I would like the ability to specify a [named client](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-5.0#named-clients) in the reverse proxy configuration to be used.

### Why is this important to you?

I'm already using named clients to make requests to downstream servers to retrieve data to process (e.g. combining data from multiple downstream api endpoints) before returning. However, for some requests I don't need to do any processing so would like to simply use reverse-proxy to forward the request to downstream service directly.

**Comment by Tratcher** [comment]
FYI there's one technical hurdle we'd have to overcome first which is described in https://github.com/microsoft/reverse-proxy/issues/458. We've blocked the usage of HttpClient instances in favor of HttpMessageInvoker due to that buffering issue and general efficiency.

If that were addressed, then you could do this with a `IProxyHttpClientFactory` as described here: https://microsoft.github.io/reverse-proxy/articles/proxyhttpclientconfig.html

**Comment by karelz** [comment]
@mcm-ham what kind of functionality do you miss from `HttpClientFactory` that can't be used with current design of YARP?

**Comment by karelz** [comment]
Triage: Unclear what the benefit is and if it is worth the additional cost. Feel free to reopen when there is more info.

**Comment by Akridian** [comment]
@karelz, in my case I seek for HttpClient usage to add access token management from [IdentityModel](https://identitymodel.readthedocs.io/en/latest/aspnetcore/web.html). Currently in our project we use [ProxyKit](https://github.com/ProxyKit/ProxyKit#24-configuring-proxykits-httpclient), but it is [closed](https://github.com/ProxyKit/ProxyKit/issues/230) after YARP announcement.

My goal is to create two endpoints: one should proxy requests to API with adding user access token and other with client access token, for open and private parts of the app respectively.

**Comment by Tratcher** [comment]
@Akridian you can do the same with transforms, middleware, or our own client factory. See:
https://microsoft.github.io/reverse-proxy/articles/transforms.html#from-code
https://github.com/microsoft/reverse-proxy/issues/561#issuecomment-731015961
https://microsoft.github.io/reverse-proxy/api/Yarp.ReverseProxy.Forwarder.ForwarderHttpClientFactory.html#Yarp_ReverseProxy_Forwarder_ForwarderHttpClientFactory_WrapHandler_Yarp_ReverseProxy_Forwarder_ForwarderHttpClientContext_HttpMessageHandler_

**Comment by Akridian** [comment]
@Tratcher Thank you a lot! With that I think we are ready to migrate. Wanna believe YARP will release with .NET 6.
