### ISSUE TITLE
Support EnableMultipleHttp2Connections 

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#675]
https://github.com/microsoft/reverse-proxy/blob/e4426b93621a4f0e4c55c626236a21404efd264e/src/ReverseProxy/Abstractions/ClusterDiscovery/Contract/ProxyHttpClientOptions.cs#L22-L23

This is unblocked for .NET 5.0.

**Comment by karelz** [comment]
Triage: We should have that as people will hit perf problems without it.
@Kahbazi any interest to pick this up?

**Comment by Kahbazi** [comment]
@karelz Yes, I will take this.
