### ISSUE TITLE
Add Enabled options to ProxyRoute, Cluster & Destination

### ISSUE THREAD

**Issue by Kahbazi** [microsoft/reverse-proxy#684]
### What should we add or change to make your life better?
Add a `bool Enabled` property to `ProxyRoute`, `Cluster` & `Destination` and only apply them if `Enabled` is `true`.
### Why is this important to you?
There are scenarios that we need to temporary stop serving requests for a specific route or cluster. It's easier to set `Enabled` to `false`, instead of removing a whole section for a route and bring it back later.

**Comment by Tratcher** [comment]
> There are scenarios that we need to temporary stop serving requests for a specific route or cluster.

Can you give examples for these scenarios?

**Comment by Kahbazi** [comment]
> Can you give examples for these scenarios?

The scenarios happens when YARP is being used as an API Manager. Sometimes there's a need to stop serving an API (route) or set of APIs (cluster) or sometimes we need to config an API but publish it later.

**Comment by abhishekisforyou** [comment]
``range(n): 0, 1, 2, ... n-1
range(x,y): x, x+1, x+2, ... y-1 code this over this

**Comment by Tratcher** [comment]
Would you expect the config validator to run for these disabled entities? We don't do that for things like Session Affinity since we assume the config may be incomplete. Note routes that fail validation can cause the entire config to be rejected.

https://github.com/microsoft/reverse-proxy/blob/240c5b7b79d5813c90f5f52e0d68fcd504dc0c81/src/ReverseProxy/Service/Config/ConfigValidator.cs#L307-L311

**Comment by abhishekisforyou** [comment]
Also add some factor for it like 2V And 5V That's Better

**Comment by Kahbazi** [comment]
> Would you expect the config validator to run for these disabled entities? We don't do that for things like Session Affinity since we assume the config may be incomplete. Note routes that fail validation can cause the entire config to be rejected.

Uhmm, I think the ideal solution would be to also validate disabled entities but if the validation failed only ignore that specific entity whether it's disabled or enabled and log them at critical level or report it in health check or expose the validation errors via an API, so eventually there's a dashboard that shows all valid and invalid entities.

**Comment by samsp-msft** [comment]
@Tratcher how is appsettings.json parsed? Does it support comments?
@Kahbazi if so would that be an adequate solution?

**Comment by Kahbazi** [comment]
> @Kahbazi if so would that be an adequate solution?

Commenting the entities will work, but it would be helpful to have a dashboard to see enabled and disabled entities.

**Comment by karelz** [comment]
Triage: We should leave this custom per config provider -- in json we should just leverage comments (our parser supports it we think).
ServiceFabric provider can do something on its own if it is important there.

Closing.
