### ISSUE TITLE
Use ValueTask for transforms

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#685]
Most request/response transforms run synchronously. The ability to make them async was only added recently in anticipation of handling auth scenarios. We should try moving these all to ValueTasks for efficiency reasons.
https://github.com/microsoft/reverse-proxy/blob/240c5b7b79d5813c90f5f52e0d68fcd504dc0c81/src/ReverseProxy/Service/RuntimeModel/Transforms/RequestTransform.cs#L19

Initially I didn't think this was viable for 3.1, but we've since gotten that working in another PR.

**Comment by Kahbazi** [comment]
@Tratcher I can work on this issue. Is it up for grab?

**Comment by Tratcher** [comment]
Hold off for now. I'm working on #60 which will probably conflict, and I might both together.

**Comment by Tratcher** [comment]
@Kahbazi Want to try this now?

**Comment by Kahbazi** [comment]
@Tratcher Yes, I'll take this.
