### ISSUE TITLE
Call another request and add the first result on the second request

### ISSUE THREAD

**Issue by luizfbicalho** [microsoft/reverse-proxy#686]
### What should we add or change to make your life better?
I'm not even sure if it's already possible to do this.

I'm trying to call a request, get the response and add it to another request.

In reality what I'm trying is this

I would add a client header to my proxy, with this header I would get a token form one request, and pass it on the header for my current request

Example

I have an api called /api/producs/list
and another api /api/token

and this is exposed as /productsapi/producs/list
and the token is not exposed

what i need is to pass some headers to the /productsapi/producs/list, then the proxy should call /api/token, add the token to the headers and call  /api/producs/list, returning the result to the client.

### Why is this important to you?

We have a lot of different apis exposed from many services, and we want to abstract the authentication on all of them to ma simpler for the app that will use it.

**Comment by Tratcher** [comment]
Here are a few places we're already discussing proxy request customization for auth:
https://github.com/microsoft/reverse-proxy/discussions/375
https://github.com/microsoft/reverse-proxy/issues/416
#60

**Comment by luizfbicalho** [comment]
Thanks @Tratcher

**Comment by abhishekisforyou** [comment]
You're welcome

**Comment by Tratcher** [comment]
Check out https://github.com/microsoft/reverse-proxy/issues/416#issuecomment-775318003 for an update here.
