### ISSUE TITLE
filtering based on IP

### ISSUE THREAD

**Issue by mohsenShakiba** [microsoft/reverse-proxy#706]
Is it possible to allow requests from only a list of while-listed IPs?
what is important to me is to be able to filter the requests based on IP and if the IP is in the previously declared white-listed IPs then the request can go through, otherwise it will return a UnAuthorized or something similar.

**Comment by Tratcher** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/security/ip-safelist?view=aspnetcore-5.0

**Comment by mohsenShakiba** [comment]
thank you for your answer

**Comment by mohsenShakiba** [comment]
It's my understanding that safe list implementation of ASP.NET Core(the provided link) will affect the entire system and it's not per route.
what I need is to provider safelist for a specific route.
thank you

**Comment by mohsenShakiba** [comment]
It's my understanding that safe list implementation of ASP.NET Core(the provided link) will affect the entire system and it's not per route.
what I need is to provider safelist for a specific route.
thank you

**Comment by Tratcher** [comment]
Ah. You can start with same example but make two changes:
1) Move the middleware into the proxy specific pipeline like this:
https://github.com/microsoft/reverse-proxy/blob/66f39b675e05c9b2490cf49f817c33060c9b02e8/samples/ReverseProxy.Code.Sample/Startup.cs#L80-L98
2) Look up the allowed IPs per route. You can either:
  A) Use a key like the route name to fetch the data from your own store. `HttpContext.GetEndpoint().DisplayName` or
  B) Include this data in the route metadata (not yet public https://github.com/microsoft/reverse-proxy/issues/587)

**Comment by Kahbazi** [comment]
There's also another way which uses custom route metadata. Add a custom metadata to the routes you want to filter, then have a middleware which decides whether to filter or not based on `HttpContext.GetEndpoint().GetMetadata<Your_Custom_Metadata>()` and the middleware between `UseRouting()` and `UseEndpoints()`.

```csharp
app.UseRouting();

app.UseIpFilteringMiddleware();

app.UseEndpoints(endpoints =>
{
    endpoints.MapReverseProxy()
        .ConfigureEndpoints((builder, route) =>
        {
            if (route == yourCondition )
            {
                builder.WithMetadata(your_custom_metadata);
            }
        }
}
```

**Comment by mohsenShakiba** [comment]
Thanks for your helpful responses, but what I ended up using was simply putting the IP in the header and adding a RouteHeader to any specific route that requires IP filtering. I know this is not the best way as it doesn't take into account the subnet mask but it will provide the level of granularity needed.
