### ISSUE TITLE
Add telemetry to application insights

### ISSUE THREAD

**Issue by luizfbicalho** [microsoft/reverse-proxy#708]
### What should we add or change to make your life better?
Would be interesting to make integtation with application insights easier, like adding all the telemetry to azure application inghts
### Why is this important to you?
Because we can use all of the appliction insights infrastructure to monitor the proxy.

**Comment by Tratcher** [comment]
YARP operates as an ASP.NET Core component. What do you need from YARP beyond Application Insights existing ASP.NET Core integration?

**Comment by luizfbicalho** [comment]
The application insights log doens't  show the proxy request

For example, my proxy calls an api to get a valid token for this request, if I open the application insights log, it show the token request, but it doesn't show the proxy request to the destination.

Maybe I did something wrong in the telemetry configuration


```
            services.AddReverseProxy()
                .LoadFromConfig(Configuration.GetSection("ReverseProxy"));
            services.AddTelemetryListeners();
           
            services.AddApplicationInsightsTelemetry(Configuration["APPINSIGHTS_CONNECTIONSTRING"]);
```

**Comment by Tratcher** [comment]
@MihaZupan do you think this is because of https://github.com/dotnet/runtime/issues/31261?

**Comment by karelz** [comment]
Triage: We will need some guidance/docs by @MihaZupan

**Comment by luizfbicalho** [comment]
I didn't understand @karelz  and @MihaZupan , is there something that I can do to log all of the information about the proxy information on the fowarded request?

**Comment by MihaZupan** [comment]
Not currently, we will need to add more instrumentation as described in https://github.com/microsoft/reverse-proxy/issues/776#issuecomment-786241459 to support AppInsights out of the box.

Out-of-the-box you will currently only see the incoming requests to the proxy, and we will forward the trace information in the request to the backend, so if you have other services participating in the distributed trace, those will light up as well.

**Comment by luizfbicalho** [comment]
Thanks, if it doesn't work out of the box, is there something that I can do? some extension would help? I could try to develop something if I had the direction

**Comment by brentnewbury-work** [comment]
Is there any update to this? I'd also like to know if there's anything we can do now to light up dependency tracking of proxied requests in AppInsights.

**Comment by MihaZupan** [comment]
It is actively being worked on in runtime. Relevant issue: https://github.com/dotnet/runtime/issues/50658

If you are blocked, see [outgoing dependencies tracking](
https://docs.microsoft.com/en-us/azure/azure-monitor/app/custom-operations-tracking#outgoing-dependencies-tracking) docs on how you could instrument your handler.
AppInsights-specific example [Handler.cs](https://gist.github.com/MihaZupan/92b55d7321def07958bafea98f8b517f) (untested)

**Comment by brentnewbury-work** [comment]
For me, I'm looking for dependency tracing. I want to be able to go into App Insights in the proxy, and see the proxied requests, see what database calls were made in the backend, etc. We can normally do that with our other App Services, but for some reason the proxy isn't doing this at all.

**Comment by MihaZupan** [comment]
I believe all distributed tracing needs can be addressed via the [`DistributedContextPropagator`](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.distributedcontextpropagator) APIs added in 6.0.

I recommend we remove the `ActivityContextPropagator` from YARP when moving to 6.0 (#1055) as `DistributedContextPropagator` exposes a superset of functionality and YARP's current default does not match Runtime behavior.

Do we care about enhancing `ActivityContextPropagator` for < 6.0? Workarounds exist and it would ultimately be deprecated.

Removing the milestone to bring this to attention in next triage.

**Comment by Tratcher** [comment]
> YARP's current default does not match Runtime behavior.

Is this fixable for 1.0?

**Comment by MihaZupan** [comment]
> Is this fixable for 1.0?

Yes, the default I had in mind specifically was `BaggageAndCorrelationContext` here
https://github.com/microsoft/reverse-proxy/blob/bbd9dbcd844dfa01a7a3d1a46c0c599d974199c3/src/ReverseProxy/Forwarder/ForwarderHttpClientFactory.cs#L131

Default runtime behavior (at least for now) is closer to `ActivityContextHeaders.CorrelationContext`.

**Comment by karelz** [comment]
Triage: Some docs may be still needed -- @MihaZupan to check it out, then close.

**Comment by MihaZupan** [comment]
Note:
From some manual testing, YARP will have to remove tracing headers from the request in order for the E2E to work well (HttpClient internals will no-op if already present).

**Comment by samsp-msft** [comment]
It may make sense to be a 1.1 feature to go with .NET 6?
