### ISSUE TITLE
Reload config

### ISSUE THREAD

**Issue by kesso1** [microsoft/reverse-proxy#714]
I was wondering if it's possible to reload a configuration while runtime maybe with different settings? And where this can be actually done, do you have to implement this in a controller class?

**Comment by Tratcher** [comment]
This is already enabled by default when you're using the IConfiguration approach.
https://github.com/microsoft/reverse-proxy/blob/66f39b675e05c9b2490cf49f817c33060c9b02e8/samples/ReverseProxy.Config.Sample/Startup.cs#L33-L34

Are you having trouble with it? Or are you using a different means of providing config?

**Comment by kesso1** [comment]
I want to implement the yarp-proxy with a front-end windows authentication of .net core. The backend server use a bearer authentication. I want to add this bearer token as authorization header with yarp transforms, but this bearer token has to be updated and user-specific. Therefore I'm looking for a session-specific configuration of the proxy.

**Comment by Tratcher** [comment]
Oh, per-user auth tokens aren't something you should be storing in config regardless, but rather fetching from a secured store or generating on-demand. 

I'm working to enable custom request transforms like this now with https://github.com/microsoft/reverse-proxy/pull/703.

**Comment by kesso1** [comment]
#703 is exactly what I'm looking for... Thanks a lot.
