### ISSUE TITLE
Ignore case for ServieFabric config

### ISSUE THREAD

**Issue by Kahbazi** [microsoft/reverse-proxy#723]
Do we need to ignore case when parsing enum when reading service fabric configuration?

https://github.com/microsoft/reverse-proxy/blob/853b6920059a0347fd165f69c5ed7283dea3d202/src/ReverseProxy.ServiceFabric/ServiceDiscovery/Util/LabelsParser.cs#L163
https://github.com/microsoft/reverse-proxy/blob/853b6920059a0347fd165f69c5ed7283dea3d202/src/ReverseProxy.ServiceFabric/ServiceDiscovery/Util/LabelsParser.cs#L282

**Comment by Tratcher** [comment]
This came up in the initial review. It seems the whole service fabric config (not just our package) is case sensitive, so this package was written as case sensitive as well. Key names, transforms, everything...

Long term I expect this to be a usability issue, but we'll see.

**Comment by Tratcher** [comment]
SF work has moved to https://github.com/microsoft/service-fabric-yarp/
