### ISSUE TITLE
AsyncLocal in HttpTransformer.TransformResponseAsync not working as expected

### ISSUE THREAD

**Issue by XHUN97terX** [microsoft/reverse-proxy#728]
### Describe the bug
The current way the HttpTransformer.TransformResponseAsync function is called from HttpProxy prevents the AsyncLocal type to work correctly. It's empty when it's expected not to be.
Any chance we could get the [method](https://github.com/microsoft/reverse-proxy/blob/119204632f12b30c5a00c2132a20066c87ac9858/src/ReverseProxy/Service/Proxy/HttpProxy.cs#L437) calling it to be async with await, so the statemachine can handle this properly? 
I don't think the extremely minor difference in performance is worth some assumptions being broken. :/

Thank you!

PS.: I know I can work around it by using the HttpContext to store the values I would store in AsyncLocals, and I know they aren't the clearest way to program, but I have a legitimate use for it. 
Also, if the idea is not rejected, I can make a PR myself of course.

### To Reproduce
Use AsyncLocal from an overriden TransformRequestAsync and TransformResponseAsync. Set value in TransformRequestAsync, and try to read the value from TransformResponseAsync. It's going to be empty.

### Further technical details

Windows 10
.NET Core 3.1
Microsoft.ReverseProxy 1.0.0-preview.8.21065.1

**Comment by Tratcher** [comment]
I don't think changing CopyResponseStatusAndHeadersAsync would help. TransformRequestAsync and TransformResponseAsync are sibling methods so any asynclocal state you modified in TransformRequestAsync would be reverted when returning to the parent method ProxyAsync between the two calls. Or am I missing something here?

**Comment by XHUN97terX** [comment]
No, you are not. My understanding of AsyncLocals was wrong. 
Thanks for correcting me. 👍
