### ISSUE TITLE
Stash LoadBalancingPolicy on ClusterConfig

### ISSUE THREAD

**Issue by Kahbazi** [microsoft/reverse-proxy#733]
Currently the `ILoadBalancePolicy` is get from a dictionary on each request in `LoadBalancingMiddleware`.
https://github.com/microsoft/reverse-proxy/blob/5cfbc328dec97048d751e2e3b396ec26993c7bd1/src/ReverseProxy/Middleware/LoadBalancingMiddleware.cs#L54

Can we stash a `ILoadBalancePolicy` on `ClusterConfig` when building a cluster to improve the performance?

**Comment by Tratcher** [comment]
That's an interesting idea. @MihaZupan @alnikola has the load balancing policy lookup shown up in the CPU profiles at all?

**Comment by Kahbazi** [comment]
The same thing also could be done for `IPassiveHealthCheckPolicy`.
https://github.com/microsoft/reverse-proxy/blob/5cfbc328dec97048d751e2e3b396ec26993c7bd1/src/ReverseProxy/Middleware/PassiveHealthCheckMiddleware.cs#L40-L42

**Comment by karelz** [comment]
Triage: We should first prove it shows up on profiles to justify the complexity.
Per @MihaZupan dictionary lookups are cheaper in .NET 5 as well and it didn't show up in @alnikola profiles so far ...

**Comment by MihaZupan** [comment]
A few Dictionary improvements I had in mind (looks like they all made it in 5.0):
https://github.com/dotnet/coreclr/pull/27195
https://github.com/dotnet/coreclr/pull/27299
https://github.com/dotnet/runtime/pull/36252

**Comment by karelz** [comment]
Triage: Closing - the work in #734 did not bring the expected gains. Not worth it.
