### ISSUE TITLE
Roadmap/release

### ISSUE THREAD

**Issue by JackPoint** [microsoft/reverse-proxy#735]
### What should we add or change to make your life better?
Thanks for building this package. I'm looking to migrate to this package. Is there a roadmap or release date known for this package?

### Why is this important to you?
I want to migate to this package but didn't want to use a preview package. If I have a date for release, I can plan on the migration

**Comment by Tratcher** [comment]
We should have an update on that timeline soon. The main thing we're waiting on is for early adopters to sign-off that the library is working well for them.

Are you able to test the current preview version and let us know if it has all of the features you need and works well for you?

**Comment by JackPoint** [comment]
Thanks for your reply. I have to schedule it for one of the teams, so I can't test it in the next 2-3 months. According to the docs most things work for me. Things I miss/extend my own:

- Need to proxy 1 request to multiple endpoints. Kind of fan out option for the load balancer. I'll extend the ILoadBalancingPolicy for that.
- My configuration changes often, so I'd like to make it easy to change clusters/destinations by GUI and API. I'm considering moving the configuration to a database and building a GUI and API on top of that.

**Comment by Tratcher** [comment]
> * Need to proxy 1 request to multiple endpoints. Kind of fan out option for the load balancer. I'll extend the ILoadBalancingPolicy for that.

Can you expand on this, what will you do with the responses? I don't anticipate this will work well with YARPs current design.

> * My configuration changes often, so I'd like to make it easy to change clusters/destinations by GUI and API. I'm considering moving the configuration to a database and building a GUI and API on top of that.

That should be fine. See the IProxyConfigProvider for pulling your changes. https://microsoft.github.io/reverse-proxy/articles/configproviders.html

**Comment by JackPoint** [comment]
We use a proxy to distribute external messages (webhook) through different parts of the system. I have multiple instances of a testing environment. 

I'd like to send those webhook messages to one specific environment to process or to multiple (if that's configured). That last one is a fan out kind of solution. The configuration should also say with of the environments is the main one so that response will be send back. The other environments response could be send on a background thread.

Hope this makes sense. Let me know if you think this will work or you know a better solution.

**Comment by Tratcher** [comment]
I see. We call that traffic mirroring and are tracking it here: https://github.com/microsoft/reverse-proxy/issues/105. That's feature is not currently on our 1.0 plan. Review the discussion on #105 and let's continue discussing it there.

**Comment by JackPoint** [comment]
Thanks for pointing out. That's an other way of calling it. I thing it will work for me.

The more I hope for a roadmap so I know what to expect!

**Comment by karelz** [comment]
Covered by #480
