### ISSUE TITLE
Dispose SchedulerEntry.Timer in case it's already been added

### ISSUE THREAD

**Issue by Kahbazi** [microsoft/reverse-proxy#742]
Should the `Timer` of `SchedulerEntry` get disposed in case the entry already exists in the dictionary?
https://github.com/microsoft/reverse-proxy/blob/9f568f1875eb4485cd9d6b58b85fccb9224b5658/src/ReverseProxy/Service/Management/EntityActionScheduler.cs#L62-L66

**Comment by karelz** [comment]
Triage: Looks like we should call it. Should be easy to do -- anyone interested?
