### ISSUE TITLE
Change cluster from a ITransformFactory before it goes to the cluster destination

### ISSUE THREAD

**Issue by we4sz** [microsoft/reverse-proxy#743]
### What should we add or change to make your life better?
I'm using Yarp to build a white label product for my client. I build a ITransformFactory that made Yarp responsible to verify that the request host is valid to any of the underlaying labels hosts. If the host is not matching any of the host saved to the labels I would like to make Yarp either to return a custom response or to forward to another clusterId so I can customize the response to the consumer.

**Example:**
Label A: Hosts["app.app", "app.dev"]

Request to host: **app.app**, should go down to underlaying cluster and set a header for Label A
Request: to host: **app.app** should go down to underlaying cluster and set a header for Label A
Request: to host: **app.notmatch** should give a custom response

### Why is this important to you?
I would like to have some kind of custom dynamic host verification and create a custom response if the verification fails.

**Comment by Tratcher** [comment]
Transforms run too late to divert or reject the request.

If you have a fixed list of hosts, you can put those into the route match host field.
https://microsoft.github.io/reverse-proxy/articles/configfiles.html
https://microsoft.github.io/reverse-proxy/api/Microsoft.ReverseProxy.Abstractions.ProxyMatch.html#Microsoft_ReverseProxy_Abstractions_ProxyMatch_Hosts

Anything that didn't match would get a 404 by default. You could add a catch-all route at the end to customize that response:
```C#
endpoints.Map("{**catch-all}", context =>
{
  return context.Response.WriteAsync("Not Found");
});
```

The other option is a middleware that inspects requests and rejects them (e.g. doesn't call next()).
https://github.com/microsoft/reverse-proxy/blob/cd117da030ca16d201de9d579e11155ae040d791/samples/ReverseProxy.Config.Sample/Startup.cs#L51-L63

**Comment by we4sz** [comment]
Thanks for fast response, a middleware it is :)
