### ISSUE TITLE
ReverseProxy.Direct.Sample sample coding issue

### ISSUE THREAD

**Issue by sammimk830** [microsoft/reverse-proxy#752]
For reference, we are using Microsoft.ReverseProxy 1.0.0-preview.8.21065.1 in an empty ASP.NET Web Application using .NET 5

I follow this instructions to input the code, but it had error as below.
![image](https://user-images.githubusercontent.com/34807325/108191833-91a79980-714e-11eb-9c7b-0f1f047f78ce.png)
![image](https://user-images.githubusercontent.com/34807325/108191998-b7cd3980-714e-11eb-92f1-4d3242aeb7f0.png)
![image](https://user-images.githubusercontent.com/34807325/108192148-dfbc9d00-714e-11eb-860b-22a105450456.png)

then I checked below commit history. I found the code is correct before commit. Why?
![image](https://user-images.githubusercontent.com/34807325/108193196-26f75d80-7150-11eb-894c-0e56afb526bc.png)
![image](https://user-images.githubusercontent.com/34807325/108193557-8ce3e500-7150-11eb-9615-601a4964a43f.png)
![image](https://user-images.githubusercontent.com/34807325/108193783-c9afdc00-7150-11eb-8332-a994d5e51de5.png)

**Comment by Tratcher** [comment]
Those docs were updated to reflect API changes in Preview 9 which just shipped. Sorry for any confusion. Please try Preview 9 and let us know how it works for you.
https://github.com/microsoft/reverse-proxy/releases/tag/v1.0.0-preview9
