### ISSUE TITLE
Obfucated ip should be based on the ip instead of random

### ISSUE THREAD

**Issue by Kahbazi** [microsoft/reverse-proxy#764]
Based on the [RFC 7239 ](https://tools.ietf.org/html/rfc7239#section-6.3)

> A generated identifier may be used where there is a wish to keep the
   internal IP addresses secret, while still allowing the "Forwarded"
   header field to be used for tracing and debugging.

**Comment by Tratcher** [comment]
> obfuscated identifiers SHOULD be randomly generated for each request

**Comment by Kahbazi** [comment]
Oh my bad. So how can it be used for tracing and debugging if it's per request? Should there be a specific log in `RequestHeaderForwardedTransform` which states what obfuscated node is being sent instead of ip?

**Comment by Tratcher** [comment]
The per-request header value would at least be stable for the duration of that request and all downstream requests. I'd be very careful about adding a log that associated the obfuscated value with the real one, that's choice better left to the developer.

**Comment by Kahbazi** [comment]
I see. Thanks for your explanation.
