### ISSUE TITLE
Proxy is supplied as a project template for dotnet new

### ISSUE THREAD

**Issue by anurse** [microsoft/reverse-proxy#77]
We believe one delivery mechanism for the proxy (perhaps the main one) is a `dotnet new` template. We should have what we need to create one, so let’s add it to this repo and start producing it in our builds.

**Comment by Tratcher** [comment]
Design question: What should be included in the template by default?
- Config file based setup like the sample app?

**Comment by karelz** [comment]
Triage: The getting started is fairly simple - 6 lines of code, or cloning sample. Not worth maintaining a template on top of that.
