### ISSUE TITLE
Support Open Telemetry for metrics

### ISSUE THREAD

**Issue by samsp-msft** [microsoft/reverse-proxy#776]
As part of being a good CNCF citizen, we need to make sure we interoperate well out of the box for Open Telemetry.

https://github.com/dotnet/runtime/issues/44445

**Comment by Tratcher** [comment]
Here's a demo we can borrow and insert ourselves into:
https://github.com/shirhatti/trivia

Note: the way we bypass HttpClient and go directly to SocketHttpHandler bypasses the DiagnosticsHandler and may break some of the open telemetry integration. See https://github.com/microsoft/reverse-proxy/issues/292

**Comment by samsp-msft** [comment]
Does @MihaZupan 's last comment on #292 imply that it should work?

**Comment by Tratcher** [comment]
I think we only ported a subset of the functionality, enough to add headers, but not enough to track the outbound request as a separate child activity.

**Comment by Kahbazi** [comment]
How the users are going to consume the open telemetry? Are we going to add the rest of `DiagnosticHandler` to the http request and let users use [OpenTelemetry.Instrumentation.AspNetCore](https://www.nuget.org/packages/OpenTelemetry.Instrumentation.AspNetCore) and [OpenTelemetry.Instrumentation.Http](https://www.nuget.org/packages/OpenTelemetry.Instrumentation.Http) or we are going to create a new Activity for YARP and create a `OpenTelemetry.Instrumentation.YARP` package?

**Comment by MihaZupan** [comment]
Distributed tracing works with YARP, but as Chris mentioned, we will appear as a single node (there is no separation for *incoming* and *outgoing* requests, it's seen as a single operation).

Do we know what is the use-case for YARP to have a separate activity for the outgoing request?

**Comment by Tratcher** [comment]
Having a separate activity would get you more granular timings, right? Or do you rely on the destination to start its own activity?

I'd also expect a separate activity to be useful in retry scenarios.

@Kahbazi I would expect to re-use the OpenTelemetry.Instrumentation.AspNetCore package. I don't know if we'll be able to re-use the http package or not.

**Comment by MihaZupan** [comment]
> Having a separate activity would get you more granular timings, right?

Yes, but only slightly - in YARP the outgoing request starts at about the same time as the incoming one (there are no network delays etc. in between). Retries would be a good scenario tho.

> do you rely on the destination to start its own activity

Yes, every part of the system contributes its information.

> I would expect to re-use the OpenTelemetry.Instrumentation.AspNetCore package. I don't know if we'll be able to re-use the http package or not.

The AspNetCore part can be reused.

For Http, it could be reused if we mirror the `DiagnosticListener` events currently used by `DiagnosticHandler` (same names, same arguments).

**Comment by Kahbazi** [comment]
> > Having a separate activity would get you more granular timings, right?
> 
> Yes, but only slightly - in YARP the outgoing request starts at about the same time as the incoming one (there are no network delays etc. in between). Retries would be a good scenario tho.

There might be scenarios where there's delay between the incoming request and outgoing requests, like when there is authentication involved, or when there's a `ConcurrencyMiddleware` for routes.

**Comment by samsp-msft** [comment]
If the outbound request is queued, in theory there could also be a delay there while it waits for an available connection (eg H2 concurrency limit).

**Comment by MihaZupan** [comment]
ToDo: Distributed tracing & logging
- Update the `ActivityPropagationHandler` to create its own child `Activity` (so that outgoing requests are separated from the incoming request) and log events matching those of Runtime's `DiagnosticsHandler`
- Test YARP behavior with OpenTelemetry & App insights on 5.0 and 3.1
- Test compatibility of above HTTP instrumentations with a DiagnosticListener/ActivitySource implementation of our handler
- Test ILogger integration behavior with the OpenTelemetry SDK
  - Do we need extra config to get ILogger to capture Span IDs
  - Are logs exported and correlated
- Create samples for wiring up telemetry egress. There shouldn't be any difference here to any other AspNetCore app so pointing to existing docs might be sufficient

Runtime work (dotnet/runtime#31261):
- Updating DiagnosticsHandler to use ActivitySource
- Exposing the type?


Future: Metrics
- Specs yet to finalize
- .NET 6.0 APIs yet to become available
- Do we need different instrumentation / flowing EventCounter data (dimensions?)

**Comment by Kahbazi** [comment]
> Update the ActivityPropagationHandler to create its own child Activity (so that outgoing requests are separated from the incoming request) and log events matching those of Runtime's DiagnosticsHandler

YARP could be used as part of an ASP.NET Core application, and although having matching events as `DiagnosticsHandler` is necessary, I think having the exact same events but with different name is useful in order to monitor only YARP requests.

**Comment by karelz** [comment]
Triage: Let's scope it to "just" Metrics (will be in .NET 6.0, hence Backlog here for YARP) -- @MihaZupan can you please file a new issue with leftovers for Logging and Telemetry we should address in YARP 1.0?

**Comment by rcdailey** [comment]
Hey folks, sorry to bump an old issue but I wanted to check up on this. Right now at my day job I'm trying to instrument our YARP microservice and it's unclear to me how I should go about it. For your "every day" ASP.NET WebApi project using .NET 7, I'd use these packages:

```xml
    <PackageVersion Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.4.0-rc.4" />
    <PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="1.4.0-rc.4" />
    <PackageVersion Include="OpenTelemetry.Extensions.Propagators" Version="1.4.0-rc.4" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.0.0-rc9.13" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Http" Version="1.0.0-rc9.13" />
```

And set it up with `services.AddOpenTelemetry()`. Based on the discussion here, this doesn't seem like the right way to go about it. As a quick test, I ran a request from the proxy to a separate microservice and I didn't see any `X-B3` headers with the trace/span IDs. So, either there's something wrong with the integration or requests sent directly from the YARP-backed microservice aren't creating & attaching a trace or span IDs. Below is the full setup code I've been testing with.

On a final note, I'll say that I've found [this page](https://microsoft.github.io/reverse-proxy/articles/diagnosing-yarp-issues.html#using-telemetry-events) but I'm not sure if I need to go down that rabbit trail. That seems like a whole lot of manual effort, when initially I'm expecting automatic instrumentation via OTel to be possible.

Thanks in advance for any updates and guidance...

```cs
private static void SetupOpenTelemetry(IServiceCollection services)
{
    const string serviceName = "MyYarpProxy";
    var resourceBuilder = ResourceBuilder.CreateDefault()
        .AddService(serviceName, GitVersionInformation.SemVer);

    services.AddOpenTelemetry()
        .WithTracing(builder => builder
            .AddSource(serviceName)
            .SetResourceBuilder(resourceBuilder)
            .AddHttpClientInstrumentation()
            .AddAspNetCoreInstrumentation()
            .AddOtlpExporter(options =>
            {
                options.Endpoint = new Uri("http://otel:4317");
            }));
}
```

**Comment by karelz** [comment]
Triage: We believe that work done in 8.0 Runtime and in Kestrel covers everything that might be needed for OpenTelemetry to work well.
If we add more, then we would be mirroring those in Runtime/Kestrel.

Closing

@davidfowl did you miss anything else which you would find valuable in YARP?
