### ISSUE TITLE
Requests are not forwarded, if a similar path exists in YARP

### ISSUE THREAD

**Issue by clausndk** [microsoft/reverse-proxy#785]
### Describe the bug
We have a list of services, with a common endpoint of /api/ping, in order for us to monitor the services.
I would like the same for the proxy itself (YARP), however this causes YARP to always respond from its own controller, and not those of the cluster.

I have a controller in my "backed service", at api/ping, that looks like this:
```
public class PingController : ControllerBase
    {
        [HttpGet("api/ping")]
        public string Ping()
        {
            return $"Atlas @ {DateTimeOffset.UtcNow:O}";
        }
    }
```

However, if I place the same kind of controller, with the same path in the YARP project, I only get responses from the YARP gateway.
```
namespace Microsoft.ReverseProxy.Sample.Controllers
{
    public class PingController : Controller
    {
        [HttpGet("api/ping")]
        public string Ping()
        {
            return $"YARP @ {DateTimeOffset.UtcNow:O}";
        }
    }
}
```

In general, I would expect a gateway/proxy to forward requests, when available and possible, and then fallback to it's own resources if they match as well.

I would then expect the order of the ASP.NET (Core) Middlewares, would be responsible for this. 

My startup looks like this:
```
public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddLettuceEncrypt().PersistCertificatesToAzureKeyVault();
            services.AddControllers();
            services.AddReverseProxy()
                .LoadFromServiceFabric(
                    options =>
                    {
                        options.DiscoveryPeriod = TimeSpan.FromSeconds(5);
                        options.DiscoverInsecureHttpDestinations = true;
                        options.AllowStartBeforeDiscovery = false;
                    });
        }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            //app.UseHttpsRedirection();
            app.UseRouting();
            app.UseAuthorization();
            app.UseEndpoints(
                endpoints =>
                {
                    endpoints.MapControllers();
                    endpoints.MapReverseProxy();
                });
        }
    }
```

Is this expected behavior? If so, why?
Can I change it?

### To Reproduce
As described above

### Further technical details

- Include the version of the packages you are using
   <PackageReference Include="Microsoft.ReverseProxy.ServiceFabric" Version="1.0.0-preview.9.21116.1" />
- The platform (Linux/macOS/Windows)
  Windows - Service Fabric setup

**Comment by Tratcher** [comment]
In routing the most most specific match wins. What paths do you have set up to proxy?

Example: If you set the proxy to forward `/{**catch-all}` and you have the ping controller above matching `api/ping` in the proxy, then a request to `/api/ping` matches the controller as more specific than the catch-all.

**Comment by clausndk** [comment]
> In routing the most most specific match wins. What paths do you have set up to proxy?
> 
> Example: If you set the proxy to forward `/{**catch-all}` and you have the ping controller above matching `api/ping` in the proxy, then a request to `/api/ping` matches the controller as more specific than the catch-all.

Hello Tratcher

I've only setup routing with hosts, so I would expect that to be "catch-all"?

```
<Extension Name="YARP-preview">
	<Labels xmlns="http://schemas.microsoft.com/2015/03/fabact-no-schema">
		<Label Key="YARP.Enable">true</Label>
		<Label Key="YARP.Routes.atlas.Hosts">atlas-local.domain.dk</Label>
		<Label Key="YARP.Backend.SessionAffinity.Enabled">false</Label>
	</Labels>
</Extension>
```

**Comment by Tratcher** [comment]
Yes, that's a catch-all path with a host constraint. You can manually control the priority by setting the Order property on one of the routes (lower values match first), but that only reverses the situation. Ultimately you can't serve `/api/ping` from both the proxy and one of the proxy destinations without a way to differentiate the requests such as the host constraint you've added on the proxy route.

**Comment by clausndk** [comment]
I'm not really sure of my options here then?

Are you telling me I can configure a priority? If yes, where? Would that cause destinations to win over local controllers?

I would expect YARP to forward the request, if a match in destination, route and any other parameter are met. I would expect it to forward requests for me, when I curl a request to http(s)://atlas-local.domain.dk/api/ping, but not if I do a request to http(s)://127.0.0.1/api/ping, because if would not be able to destermine a target destination for such a request.

Does that make sense?
Would you not expect YARP to follow such principle (bug or not)?

**Comment by Tratcher** [comment]
This is by design, proxy routes are not given special priority over local routes, the standard route matching algorithm is applied equally to both and the most specific one wins. To override that you set the `Order` property on your routes.
In this example something like `<Label Key="YARP.Routes.route1.Order">-10</Label>` should work (lower numbered routes are checked first).
The alternative is to add a host constraint of "127.0.0.1" to your local ping route so that it doesn't match requests for atlas-local.domain.dk.

**Comment by samsp-msft** [comment]
> The alternative is to add a host constraint of "127.0.0.1" to your local ping route so that it doesn't match requests for atlas-local.domain.dk.

From your description you need to be using host names in the routes to distinguish the routes for destinations or for YARP itself.
