### ISSUE TITLE
DestinationInfo points to a DestinationConfig which does not have all the data of the Abstractions.Destination Record

### ISSUE THREAD

**Issue by samsp-msft** [microsoft/reverse-proxy#788]
### Describe the bug
From RuntimeModel.DestinationInfo I want to access the metadata collection specified in config. The Config property is pointing to a DestinationConfig which is intended as snapshot of the config object, but it doesn't have all the properties of the Abstractions.Destination object used by config.

Now that config objects are records, the immutable clone is unnecessary, and the Config should just point directly at the Abstractions.Destination object. 

This same pattern can be applied to ClusterInfo/ClusterConfig and RouteInfo/RouteConfig.

This will get rid of 3 extra types, and cloning at runtime.

**Comment by Tratcher** [comment]
The RouteConfig and ClusterConfig have dynamically constructed state like transforms and the HttpClient. DestinationConfig is the only one without extra state.

**Comment by samsp-msft** [comment]
Why is ClusterConfig.Options called Options?

**Comment by Tratcher** [comment]
> Why is ClusterConfig.Options called Options?

@samsp-msft Calling it `Cluster` because it used a `Cluster` type seemed redundant.

**Comment by samsp-msft** [comment]
State, Snapshot, Config would all be better names :-)
