### ISSUE TITLE
My app did not work on Azure Web App Linux

### ISSUE THREAD

**Issue by bmatatuk** [microsoft/reverse-proxy#791]
### Describe the bug
My proxy app did not work on Azure Web App Linux. But worked straight away on a Windows instance on Azure.
I have published my app on to Azure directly from VS2019 and it seems to have updated the necessary settings and flags on Azure and restarted the web app too. I have tried several things, but it wouldn't forward my request to my intended URL. 

But, without any fuss, it worked on my first attempt on a windows instance on Azure.

I am very new to the Azure environment therefore could not go too deep to investigate.

Is there something that I've missed in the process? 

### Further technical details
-IDE : VS2019 Enterprise
-.NET CORE 5
-YARP Version: YARP 1.0.0-preview9
-Using appsetting.json 
-Azure App Service Linux (worked on windows Instance)

Thanks

**Comment by Tratcher** [comment]
What did happen? E.g. what were the responses from the proxy, and what was recorded in the server logs?

**Comment by bmatatuk** [comment]
Sorry.. As I have mentioned in my post, I have deleted the service and therefore do not have access to the logs. But, on a newly created instance the issue mentioned doesn't seem to be there. It must be a one off issue or a buggy azure app instance. I'll get back with logs should I encounter it again.

Thanks
