### ISSUE TITLE
Use StringBuilderPooledObjectPolicy instead of StringBuilder in RequestHeaderForwardedTransform

### ISSUE THREAD

**Issue by Kahbazi** [microsoft/reverse-proxy#799]

**Comment by davidfowl** [comment]
Don't use either? Maybe ValueStringBuilder?

**Comment by Kahbazi** [comment]
https://github.com/dotnet/runtime/blob/e51470d6142784f7989d946fd3f4a667d5e743a6/src/libraries/Common/src/System/Text/ValueStringBuilder.cs#L11
`ValueStringBuilder` is internal right now. Is it ok if the implementation is copied to yarp?

**Comment by Tratcher** [comment]
That seems bigger than we'd want to copy, though we might only need some of it. Can you check how much we'd need?
