### ISSUE TITLE
Make use of IWebProxy

### ISSUE THREAD

**Issue by t-mxcom** [microsoft/reverse-proxy#803]
### What should we add or change to make your life better?

Please consider implementing an easy way of specifying an `IWebProxy` implementing instance to be used by **reverse-proxy** when proxying requests to the target clusters.

### Why is this important to you?

While I wouldn't use it in production, my development PC is configured to perform all web-requests through a corporate web proxy secured by NTLM.

When using the [Direct Proxy](https://microsoft.github.io/reverse-proxy/articles/direct-proxying.html) approach, specifying the `IWebProxy` works:

```cs
var webProxy = new WebProxy("http://our.corporate.proxy.addr:8080", true)
{
    Credentials = CredentialCache.DefaultCredentials
};
var httpClient = new HttpMessageInvoker(new SocketsHttpHandler()
{
    UseProxy = true,
    Proxy = webProxy,
    AllowAutoRedirect = false,
    AutomaticDecompression = DecompressionMethods.None,
    UseCookies = false
});
```

But I couldn't find a way to use the reverse proxy (`AddReverseProxy`, `MapReverseProxy`) features through the corporate web proxy.
If there is a way, please add the solution to your docs!

THANKS VERY MUCH!

**Comment by Tratcher** [comment]
To enable a proxy today you'd need to customize the IProxyHttpClientFactory.
https://microsoft.github.io/reverse-proxy/articles/proxyhttpclientconfig.html#custom-iproxyhttpclientfactory

It's not clear how common a need that would be.

**Comment by t-mxcom** [comment]
Thanks for your answer! This works fine!

Currently, the implementation of `IProxyHttpClientFactory` in `Microsoft.ReverseProxy.Service.Proxy.Infrastructure.ProxyHttpClientFactory` is marked `internal`.
What do you think about making this `public` so it can be inherited to add custom logic and configuration?

**Comment by Tratcher** [comment]
That's tracked by https://github.com/microsoft/reverse-proxy/issues/805.

Closing this as answered.

**Comment by MattiasMartens** [comment]
> https://microsoft.github.io/reverse-proxy/articles/proxyhttpclientconfig.html#custom-iproxyhttpclientfactory

This is a dead link

**Comment by Tratcher** [comment]
https://microsoft.github.io/reverse-proxy/articles/http-client-config.html#custom-iforwarderhttpclientfactory
