### ISSUE TITLE
Make ProxyHttpClientFactory public and extensible

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#805]
Today when someone wants to customize their IProxyHttpClientFactory they have to copy a lot of code from the internal ProxyHttpClientFactory to avoid some common pitfalls.
https://microsoft.github.io/reverse-proxy/articles/proxyhttpclientconfig.html#custom-iproxyhttpclientfactory

Find a way to make the existing factory more extensible so they don't have to copy it.

One idea would be to have a built in extension something like this:
```c#
            services.AddReverseProxy()
                .CustomizeHttpClient((context, handler) => handler.MaxConnectionsPerServer = 25)
```

Note there have also been asks for using IProxyHttpClientFactory together with IHttpProxy.
https://github.com/microsoft/reverse-proxy/issues/801#issuecomment-788200333

**Comment by samsp-msft** [comment]
What about making ProxyHttpClientFactory overridable, or will that fail because of the interface?

**Comment by Tratcher** [comment]
Allowing you to derive from ProxyHttpClientFactory should work, but we'd have to think through the overloads. The current signature for `public HttpMessageInvoker CreateClient(ProxyHttpClientContext context)` doesn't enable any composition by overriding, we'd have to add at least one more virtual method with a more composable signature.

The other downsides of deriving from ProxyHttpClientFactory are that A) you then have to take care of registering that implementation in DI, and B) you've got yet another class for what is likely a small customization.

**Comment by Tratcher** [comment]
Also consider DelegatingHandlers as shown in #843.

**Comment by karelz** [comment]
Triage: Currently you need to copy ~100 lines of code from samples to change any setting -- ugly.
