### ISSUE TITLE
xref links from Articles to ref docs are not working.

### ISSUE THREAD

**Issue by samsp-msft** [microsoft/reverse-proxy#829]
### Describe the bug
x:ref links for example the ones to Cluster and Route in https://microsoft.github.io/reverse-proxy/articles/configfiles.html are not linking correctly.

**Comment by Tratcher** [comment]
I think it broke when we changed from classes to records. In fact, even the API docs for Cluster and ProxyRoute are missing.

I know a .NET Core version of docfx is in progress, we should try it and see if it's more up to date.

**Comment by karelz** [comment]
Triage: Blocked on new .NET Core-based tool that understands records.

**Comment by Tratcher** [comment]
https://github.com/dotnet/docfx/releases Try out the 3.0 betas.

**Comment by Tratcher** [comment]
Sounds like this is fixed in https://github.com/dotnet/docfx/releases/tag/v2.58. That should be an easy update.
