### ISSUE TITLE
Let the ServiceDiscovery abstraction

### ISSUE THREAD

**Issue by pengweiqhca** [microsoft/reverse-proxy#839]
Add ReverseProxy.ServiceDiscovery project, let the ServiceDiscovery abstraction.
ReverseProxy.ServiceDiscovery
 ---- ReverseProxy.ServiceDiscovery.ServiceFabric
 ---- ReverseProxy.ServiceDiscovery.Kubernetes
 ---- ReverseProxy.ServiceDiscovery.XXX

**Comment by Tratcher** [comment]
What do you propose to put into the ServiceDiscovery abstraction? What can be shared across these implementations?
