### ISSUE TITLE
Extending HttProxy

### ISSUE THREAD

**Issue by luis-alexandre** [microsoft/reverse-proxy#841]
### What should we add or change to make your life better?
Is it possible to change the modifier for HttProxy class to "public"? So it will be possible to add more feature and change some parameters in runtime mode.

`internal class HttpProxy : IHttpProxy`

### Why is this important to you?
In runtime, I would like to change the cluster address (destinationPrefix parameter) before ProxyAsync method makes a requests to it.

`public async Task ProxyAsync(
            HttpContext context,
            string destinationPrefix,
            HttpMessageInvoker httpClient,
            RequestProxyOptions requestOptions,
            HttpTransformer transformer)`

**Comment by Tratcher** [comment]
Are you using IHttpProxy [directly](https://microsoft.github.io/reverse-proxy/articles/direct-proxying.html) or through the [config system](https://microsoft.github.io/reverse-proxy/articles/getting_started.html)?

> In runtime, I would like to change the cluster address (destinationPrefix parameter) before ProxyAsync method makes a requests to it.

Can you give an example of the changes you want to make to the address and the scenario for why?

The recommended way to make per-request modifications is to use [Transforms](https://microsoft.github.io/reverse-proxy/articles/transforms.html) (or [HttpTransformer](https://microsoft.github.io/reverse-proxy/api/Microsoft.ReverseProxy.Service.Proxy.HttpTransformer.html#Microsoft_ReverseProxy_Service_Proxy_HttpTransformer_TransformRequestAsync_Microsoft_AspNetCore_Http_HttpContext_System_Net_Http_HttpRequestMessage_System_String_) if using IHttpProxy directly).

**Comment by luis-alexandre** [comment]
I am using through config system. What I want to do is to change the host from Cluster.Destination.Address path before YARP call it. For example in cluster configuration I can have this:

`"Clusters": {
      "produto-v1": {
        "Destinations": {
          "produto-v1-dst": {
            "Address": "[host]/products"
          }
        }
      }
}`

Then, in runtime mode, when I call the route, that will be redirect to this "template address". In this moment, I would like to pass the right host, for example:  "ecommerce.com/products". 

This way, I can have the same configuration in my repository, kind of "template", for different hosts.

I am taking a looking in the YARP code and I am thinking in to implement a new class that use IHttpProxy interface, like HttProxy class, but I don't want to lose or duplicate all exist logic.

**Comment by Tratcher** [comment]
You want to determine the destination when you run the app, but it doesn't change per request?

I'd suggest using [IProxyConfigFilter](https://github.com/microsoft/reverse-proxy/blob/d1dc9ab0374ea141f4a4dca934e7ef6cd9858c50/samples/ReverseProxy.Config.Sample/CustomConfigFilter.cs#L11) to fill the templated value when loading the config, or to create the config directly in code:
https://github.com/microsoft/reverse-proxy/blob/867359b02a606590c6e71fff8a4fadddc046021f/samples/ReverseProxy.Code.Sample/Startup.cs

**Comment by luis-alexandre** [comment]
yeah.. you're right. I want to determine the destination when my app is running. What I am thinking is the consumer could pass a header with specific domain value, for example ecommerce, and use that to determine the destination. 

It's something like this (sorry for the draft below):

Request Pipeline pass "ecommercetwo" in its header:
`proxy --> Clusters --> destination `

Then, after validating header value and applying some logic on it, my application will replace the tag "[host]" from Cluster settings for ecommercetwo.com.

This way, in my config, I don't need duplicate the same route to have different clusters and I can avoid to have large configurations settings in my repository to management them.

**Comment by Tratcher** [comment]
Oh, you do want to modify it per request. In that case rather than trying to work around the config system, you might be better off skipping the config system and calling IHttpProxy directly.
https://github.com/microsoft/reverse-proxy/blob/867359b02a606590c6e71fff8a4fadddc046021f/samples/ReverseProxy.Direct.Sample/Startup.cs#L51-L53

That will give you full control to inspect the request and decide where to send it.

For background, dynamic destinations don't work well with the config model because they invalidate the state needed for active and passive health checks, load balancing, session affinity, etc..

**Comment by luis-alexandre** [comment]
I tried the direct proxying approach before, but I coudn't load all information about routes from my repository. For example: transformations, metadata, authentication, etc.

Is it possible that direct proxying approach and config system working togehther? I am asking that because I want to use the other YARP features as well, like transformation, cors, authentication, etc.

**Comment by Tratcher** [comment]
Hmm, you could do a hybrid with middleware.
https://github.com/microsoft/reverse-proxy/blob/d1dc9ab0374ea141f4a4dca934e7ef6cd9858c50/samples/ReverseProxy.Code.Sample/Startup.cs#L46-L49
https://github.com/microsoft/reverse-proxy/blob/d1dc9ab0374ea141f4a4dca934e7ef6cd9858c50/samples/ReverseProxy.Code.Sample/Startup.cs#L101-L108

Your middleware would inspect the route, calculate the destination, and then call IHttpProxy yourself and then terminate the pipeline by not calling `next()`.

You will need preview 10 [daily](https://github.com/microsoft/reverse-proxy/blob/main/docs/DailyBuilds.md) builds to be able to get access to the route config from middleware (#814). Fair warning, there have been [branding](https://github.com/microsoft/reverse-proxy/pull/830) changes in preview 10, we should have new packages up on nuget soon.

**Comment by luis-alexandre** [comment]
@Tratcher .. your suggestion worked well... thanks!
I have a final question. If I use this hybrid approach, do you think that I will lose some YARP feature?

**Comment by Tratcher** [comment]
This approach won't work with active or passive health checks, load balancing, or session affinity. All of those rely on having a set list of destinations and maintaining state about them, but you're making up destinations as you go.

**Comment by luis-alexandre** [comment]
Ok @Tratcher .. thanks a lot for your help.
I will wait for the new package!
