### ISSUE TITLE
Microsoft.ReverseProxy is now Yarp.ReverseProxy

### ISSUE THREAD

**Issue by samsp-msft** [microsoft/reverse-proxy#852]
We have gone through a naming change for Preview 10, so the namespaces and package names have changed. 

# Microsoft.ReverseProxy -> Yarp.ReverseProxy

You will now find YARP under nuget as:
https://www.nuget.org/packages/Yarp.ReverseProxy/

[Preview 10](https://www.nuget.org/packages/Yarp.ReverseProxy/1.0.0-preview.10.21168.2) has just been released incorporating these changes. Please update your references and namespace imports as applicable. A simple search and replace should be sufficient as the APIs under the namespaces have not changed.

Thanks, 

The YARP Team

**Comment by alexwiese** [comment]
Yet Another Reverse Proxy Reverse Proxy?

**Comment by karelz** [comment]
Yes Yes :D

**Comment by MihaZupan** [comment]
@samsp-msft Given that this issue is not pinned anymore, should it be closed?
