### ISSUE TITLE
RequestHeaderOriginalHost=false conflicts with RequestHeader "Host" Set

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#859]
Regressed in preview 8
https://github.com/microsoft/reverse-proxy/discussions/858#discussioncomment-505443

The transform `"RequestHeaderOriginalHost": "false"` (where false is the default value) conflicts with someone trying to set a custom host via `{ "RequestHeader": "Host", "Set": "customHost" }`

If RequestHeaderOriginalHost is not set or is false, then a transform is added that removes the host header. The problem is that this is added and runs after your RequestHeader Set transform, so the Host gets set and then removed.

Workaround:
```
{ "RequestHeaderOriginalHost": "true" },
{
"RequestHeader": "Host",
"Set": "customHost"
}
```

Possible fix: Have RequestHeaderOriginalHost=false only remove the host from the proxy request if it matches the original one from the request.

**Comment by karelz** [comment]
Triage: Should be fairly simple, no workaround, we should fix it.
