### ISSUE TITLE
Extending configuration nodes with additional data

### ISSUE THREAD

**Issue by samsp-msft** [microsoft/reverse-proxy#87]
In looking at the round robin implementation and the features / scenarios @Kahbazi mentioned, we are going to need to be able to stuff extra information into these nodes.
There are a couple of scenarios:

- Data that internal components will want to store, and will always be needed - these should probably go as properties directly on the objects

- Data that some optional components will want to store, such as load balancing counters - For these I would suggest we go with something like the [Feature](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httpcontext.features?view=aspnetcore-3.1) collection from HttpContext. The key complication here is that it needs to be thread safe as it can be accessed from many workers simultaneously. This mechanism could also be used for custom components for storing state that does not need to be set by configuration. A further complication is whether this state is persisted across configuration changes - I would suggest it should be, with some form of notification so that the owning component can decide what to do.

- Data that needs/can be specified by the user as part of configuration. For example if a load balancing scheme is to direct a percentage of traffic to particular nodes, that needs to be specifiable. I think it may be better to implement a dictionary approach for specifying properties on these nodes so that we have flexibility to add what is needed.

I am trying to think of YARP as a framework for a proxy with extensibility as a core tenet - we aren't going to cover every scenario with built in components, so we need to be consider how extra components are going to hook in and store their state.

**Comment by anurse** [comment]
As this is a "Discussion" item that usually indicates we don't have specific action to take here yet. Should we plan to have a more concrete discussion on this and create some actionable work or are we not quite there yet?

**Comment by Tratcher** [comment]
> * Data that needs/can be specified by the user as part of configuration. For example if a load balancing scheme is to direct a percentage of traffic to particular nodes, that needs to be specifiable. I think it may be better to implement a dictionary approach for specifying properties on these nodes so that we have flexibility to add what is needed.

We actually already have something for this. Backend, BackendEndpoint, and ProxyRoute all have `IDictionary<string, string> Metadata` collections that bind from config.

Read-only external config input should be stored separately from mutable runtime state due to concurrency issues. i.e. we shouldn't try to re-use this collection for the other two data types.

**Comment by Kahbazi** [comment]
I would like to see `List<object> EndpointMetadata` property on [ProxyRoute](https://github.com/microsoft/reverse-proxy/blob/bc9298322206f35e7d658183464cdf806280143f/src/ReverseProxy.Core/Abstractions/RouteDiscovery/Contract/ProxyRoute.cs) which should be added to `endpointBuilder`
https://github.com/microsoft/reverse-proxy/blob/4520fb1d110f8687647e3b052a40d84d26b2ec7f/src/ReverseProxy.Core/Service/DynamicEndpoints/RuntimeRouteBuilder.cs#L51-L54

**Comment by Tratcher** [comment]
Filed https://github.com/microsoft/reverse-proxy/issues/121 to make Metadata more user friendly.

@Kahbazi `List<object>`? How would a component find the value it needs in the list?

**Comment by Kahbazi** [comment]
I would like to add `IAuthorizeData`, `IAllowAnonymous` or `ICorsMetadata` to Endpoint Metadata, so I could have different AuthN, AuthZ and CORS for different endpoints.

**Comment by Tratcher** [comment]
Hmm, I can see why you'd want those, but those aren't objects you'll be able to load directly from a config source. It would take some intermediate translation in the endpoint builder.

We should be adding first class support for authz (filed https://github.com/microsoft/reverse-proxy/issues/122). (And CORS?)

**Comment by Kahbazi** [comment]
I'm definitely in favor of adding first class support for authz (and CORS), but still I would like to see a 
`List<object>` on `ProxyRoute`. 
I believe each framework that maps endpoints to the `IEndpointRouteBuilder`, should also provide APIs for adding endpoint metadata to it. Who knows what middleware or components might comes in future that needs some metadata on an endpoints as a trigger, and since we can't know what they needs adding metadata from code is good enough for me.

> (And CORS?)

I'm thinking of using YARP as a backend for multiple SPAs and each needs different CORS settings.

**Comment by samsp-msft** [comment]
> @Kahbazi `List<object>`? How would a component find the value it needs in the list?
I think part of what @Tratcher was asking is how would you want to retrieve the objects. HttpContext has a feature collection, which is essentially an IDictionary<System.Type, object>, so items can be retrieved based on the key rather than having to search through a list each time.

**Comment by Kahbazi** [comment]
no I don't want to add these items to each request of `HttpContext`. I want them to be in endpoint metadata and I could get them with 
`httpContext.GetEndpoint().Metadata.GetMetadata<SomeMetadata>()`

**Comment by Tratcher** [comment]
Oh, I see. Endpoint.Metadata is a custom collection with generic search functionality (via downcasting).
https://github.com/dotnet/aspnetcore/blob/600d5ff4978c84b42aa15a11a0fdb0dbd1cc8692/src/Http/Http.Abstractions/src/Routing/EndpointMetadataCollection.cs#L75

Ok, let me back up. Yes we need some way to add custom endpoint metadata. ProxyRoute is too low level for that, it's a raw config representation, you're not going to be able to represent complex objects like IAuthorizeData there. We likely need an event in RuntimeRouteBuilder that lets you customize the routes as we build them. You'd take some config metadata and translate it to complex objects like IAuthorizeData.
https://github.com/microsoft/reverse-proxy/blob/ea7164c689ea06343b99a30aa7feecef4eda215d/src/ReverseProxy.Core/Service/DynamicEndpoints/RuntimeRouteBuilder.cs#L51-L66

**Comment by Tratcher** [comment]
Or maybe an event in DynamicConfigBuilder when we build the ParsedRoute object.
https://github.com/microsoft/reverse-proxy/blob/61055e1dd468ab90083ec4f5fddbce603e11ace5/src/ReverseProxy.Core/Service/Config/DynamicConfigBuilder.cs#L66

**Comment by Tratcher** [comment]
I'm adding some config events earlier in the pipeline but I think they're still too low level for this.
https://github.com/microsoft/reverse-proxy/pull/47.

**Comment by Kahbazi** [comment]
Can we have first class support for CORS the way we have for authz?

**Comment by Tratcher** [comment]
> Can we have first class support for CORS the way we have for authz?

Can you open a new issue for that and outline what CORS support you're looking for? I'm not as familiar with that part of the stack. What would you normally configure per route?

**Comment by Tratcher** [comment]
FYI I've split out the endpoint metadata event from https://github.com/microsoft/reverse-proxy/issues/87#issuecomment-620896307 to https://github.com/microsoft/reverse-proxy/issues/286, it's independent of the original issue here around various data stores.

**Comment by karelz** [comment]
Triage: 1.0 has metadata, while not pretty, it is adequate. We can keep iterating on it post 1.0.

**Comment by karelz** [comment]
Triage: Merge it into #1709

**Comment by samsp-msft** [comment]
Duplicate of #1709
