### ISSUE TITLE
Unit testing with GetRequiredCluster()

### ISSUE THREAD

**Issue by jmezach** [microsoft/reverse-proxy#878]
### What should we add or change to make your life better?
We have a middleware that reads some metadata from the cluster configuration. In previous versions of YARP we did this by getting the `IReverseProxyFeature` from the `HttpContext` directly. Preview 10 introduced a `GetRequiredCluster()` extension method on the `HttpContext` so I figured we might as well use that. The change was easy enough, but unfortunately my unit tests broke. That's because `GetRequiredCluster()` relies on the `Endpoint` being set on the `HttpContext` which we can set using `SetEndpoint()`. However, the endpoint also needs to have `RouteConfig` metadata which I'm unable to create in my unit tests since it requires a `ClusterInfo` instance and the constructor for that class is `internal`. 

### Why is this important to you?
Ideally I would like to be able to test my middleware without having to fetch the `IReverseProxyFeature` directly in my code. Or perhaps I'm just missing something that would allow me to do this?

**Comment by jmezach** [comment]
Yeah, we just went back to using `IReverseProxyFeature` directly and it works just fine. It's mainly a matter of now having to do some `null` checks to make sure things aren't going to blow up at runtime. That does beg the question whether the YARP library has nullable annotations?

**Comment by Tratcher** [comment]
Nullable annotations are something we're considering :grin: #654
