### ISSUE TITLE
Make default HttpProxy implementation public and extensible

### ISSUE THREAD

**Issue by vdjuric** [microsoft/reverse-proxy#884]
Please make Yarp.ReverseProxy.Service.Proxy.HttpProxy public and method ProxyAsync virtual so advanced user could derive from HttpProxy class and override ProxyAsync with custom behaviour.

This derived class would then be registered via DI, for example: `services.AddSingleton<IHttpProxy, HttpProxyDerived>()`

**Comment by samsp-msft** [comment]
Why would you rather this than putting your custom implementation as an explicit step at the end of the pipeline?

**Comment by Tratcher** [comment]
HttpProxy is not well factored for derivation, you'd have to re-implement the whole thing anayways. At that point you'd be better off using the interface.

What are you trying to customize?

**Comment by vdjuric** [comment]
Hi @samsp-msft @Tratcher

I implemented transformer which automatically calls OAauth authentication endpoint, receives OAuth token and adds it to request header. After this, actual authenticated request is called. This works great!

However, if for some reason authentication with header provided OAuth token fails (when doing actual call via HttpClient, when all transformers are done) and if I receive back from destination server HTTP status code 401 (Unauthorized, for example token could be expired or revoked), I would like to automatically retry entire chain (including all transformers, which would then generate new OAuth token and include new value in request header).

I think this could be only done in HttpProxy implementation.

**Comment by Tratcher** [comment]
We're discussing retries in https://github.com/microsoft/reverse-proxy/issues/56. The design proposal uses proxy middleware. If you want to help prototype that then let's continue the discussion over there.

It's odd that your OAuth token would be rejected immediately after you acquired it, or is there some caching in the system?

**Comment by vdjuric** [comment]
You are right, I forgot to explicitly mention that OAauth tokens are valid for some time (in my case for 15 minutes) and for more optimal flow, tokens are temporary cached in IMemoryCache. If I would always request fresh tokens, there would be no issues - but this would also require double call every time which increases latency.

I can also shift this retry logic to client, but it would be better if Yarp could handle this, so clients can be very simple.

I will check discussion in #56, thanks!

**Comment by vdjuric** [comment]
(continuing discussion in #56, closing)
