### ISSUE TITLE
[SF] Always get HTTP 503 from YARP service on SF cluster

### ISSUE THREAD

**Issue by linmeng08** [microsoft/reverse-proxy#889]
### Describe the bug

I am trying Yarp on Service Fabric cluster and can't get the basic sample to work, the service always returns 503:

```
PS C:\Users\vmadmin> Invoke-RestMethod -Method Get -Uri http://localhost:8601/
Invoke-RestMethod : The remote server returned an error: (503) Server Unavailable.
```

Calling the /api/dump URL on the Yarp proxy service responses correctly:

```
PS C:\Users\vmadmin> Invoke-RestMethod -Method Get -Uri http://localhost:8601/api/dump

protocol : HTTP/1.1
method   : GET
scheme   : http
host     : localhost:8601
path     : /api/dump
headers  : @{Host=System.Object[]; User-Agent=System.Object[]}
time     : 2021-04-05T12:26:53.1515397+00:00
```

My Startup.cs is identical to [Startup.cs from the sample folder](https://github.com/microsoft/reverse-proxy/blob/main/samples/ReverseProxy.ServiceFabric.Sample/Startup.cs). My appsettings.json contains ServiceFabricDiscovery section as following:

```
  "ServiceFabricDiscovery": {
    "DiscoveryPeriod": "00:00:15",
    "DiscoverInsecureHttpDestinations": true,
    "AlwaysSendImmediateHealthReports": true
  }
```

There is only one backend application (destination) runs in the cluster which has this in its ServiceManifest.xml:

```
    <StatefulServiceType ServiceTypeName="StoreServiceType" HasPersistedState="true">
      <Extensions>
        <Extension Name="YARP-preview">
          <Labels xmlns="http://schemas.microsoft.com/2015/03/fabact-no-schema">
            <Label Key="YARP.Enable">true</Label>
            <Label Key="YARP.Routes.route1.Path">{**catch-all}</Label>
          </Labels>
        </Extension>
      </Extensions>
    </StatefulServiceType>
...
  <Resources>
    <Endpoints>
      <Endpoint Name="ServiceEndpoint" Type="Input" Protocol="http" />
```

The service listens on this HTTP endpoint and is working, i.e. directly calling the HTTP endpoint returns 200:

```
PS C:\Users\vmadmin> Invoke-RestMethod -Method Get -Uri http://10.0.0.4:20006/100718a8-b91f-464b-8cef-be607e5b3008/132620989779040711

nodeName nodeIp   machineName counter
-------- ------   ----------- -------
SF_0     10.0.0.4 SF000000    921
```

I am not sure what it needs to do to make the Yarp proxy service forward the call to this backend service, do you know where I have missed or not done it right? Does Yarp has any logs that I can look into to see where might be the problem?

### Further technical details

Yarp.ReverseProxy 1.0.0-preview.10.21168.2
Yarp.ReverseProxy.ServiceFabric 1.0.0-preview.10.21168.2
Service Fabric cluster is on latest version (8.0.513.9590)

**Comment by linmeng08** [comment]
Also just to add, on the backend service I can see OK health report from Yarp, so the endpoint discovery should be working?

Health State | Source | Property | Report Message
-- | -- | -- | --
OK | YARP | DynamicConfig | Successfully built cluster 'fabric:/YarpBackendApp/StoreService' with 1 routes.

**Comment by Tratcher** [comment]
You'll need to check the server logs to get the reason for the 503.
https://github.com/microsoft/reverse-proxy/blob/28f748a0836f826b1f0ccd5404e0e23873fb744e/samples/BasicYarpSample/appsettings.json#L5-L9
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-5.0#configure-logging

**Comment by linmeng08** [comment]
Thank you @Tratcher , I am seeing this warning after enabling logging:

```
Category: Yarp.ReverseProxy.Middleware.LoadBalancingMiddleware
EventId: 7
ConnectionId: 0HM7OE76FOFO2
RequestId: 0HM7OE76FOFO2:00000002
RequestPath: /
SpanId: |56c06876-48ba210e954589db.
TraceId: 56c06876-48ba210e954589db

No available destinations after load balancing for cluster 'fabric:/YarpBackendApp/StoreService'.
```

I can still see the health report on the backend service (destination):

Health State | Source | Property | Source UTC | Message
-- | -- | -- | -- | --
OK | YARP | DynamicConfig | Mon, 05 Apr 2021 20:36:32 GMT | Successfully built cluster 'fabric:/YarpBackendApp/StoreService' with 1 routes.

Here is what the endpoint of the backend service looks like:

Name | Endpoint
-- | --
Default | http://10.0.0.8:20011/e63415b7-4e34-4a03-b747-67df4a36ee1f/132621005748205487

Do you know why I am getting **No available destinations** error message?

**Comment by linmeng08** [comment]
I further checked Yarp logs and found this exceptio

```
Category: Yarp.ReverseProxy.ServiceFabric.Discoverer
EventId: 13

Config error found when trying to build endpoint for replica '132621005748205487' of service 'fabric:/YarpBackendApp/StoreService', skipping.

Exception: 
Yarp.ReverseProxy.ServiceFabric.ConfigException: No acceptable endpoints found for replica '132621005748205487'. Search criteria: listenerName='', emptyStringMatchesAnyListener=true.
   at Yarp.ReverseProxy.ServiceFabric.Discoverer.BuildDestination(ReplicaWrapper replica, String listenerName, String healthListenerName)
   at Yarp.ReverseProxy.ServiceFabric.Discoverer.DiscoverDestinationsAsync(ServiceFabricDiscoveryOptions options, ServiceWrapper service, Dictionary`2 serviceExtensionLabels, CancellationToken cancellation)
```

This is what the endpoint section looks like in the ServiceManifest.xml for the backend service:

```
    <Endpoints>
      <Endpoint Name="ServiceEndpoint" Type="Input" Protocol="http" />
      <Endpoint Name="ReplicatorEndpoint" />
    </Endpoints>
```

The actual port assigned by SF runtime is as following and the endpoint is up and responding:

Name | Endpoint
-- | --
Default | http://10.0.0.8:20011/e63415b7-4e34-4a03-b747-67df4a36ee1f/132621005748205487

**Comment by Tratcher** [comment]
@alnikola can you look at this error tomorrow?

**Comment by alnikola** [comment]
@linmeng08 By default, we select **HTTPS endpoints only**, but it seems your endpoint is published as plaintext HTTP. If you want to use plaintext HTTP endpoints, you need to explicitly allow it by setting `true` to `ServiceFabricDiscoveryOptions.DiscoverInsecureHttpDestinations`.
```C#
services.Configure<ServiceFabricDiscoveryOptions>(o => o.DiscoverInsecureHttpDestinations = true);
```

**Comment by linmeng08** [comment]
Hi @alnikola - thank you for the response, I did have this in my appsettings.json:

```
  "ServiceFabricDiscovery": {
    "DiscoveryPeriod": "00:00:15",
    "DiscoverInsecureHttpDestinations": true,
    "AlwaysSendImmediateHealthReports": true
  },
```
and code in my Startup.cs:

```
            services.AddReverseProxy()
                .LoadFromServiceFabric(this.configuration.GetSection("ServiceFabricDiscovery"));
```

But it seems the configurations are not being used - i.e. from the Yarp logs I can also see the discovery runs every 30 seconds (the default value) and not 15 seconds as I specified in my configuration file. I have now changed my code to use the callback to specify the configuration values like you posted then it started to work correctly.

**Comment by alnikola** [comment]
@Tratcher Could you please clarify if defining an option object in appsettings.json like `ServiceFabricDiscovery` above should be picked up by ASP.NET Core configuration pipeline?

**Comment by faix** [comment]
@linmeng08 i got this running successfully by defining the options in code. My ConfigureServices function looks like so:

services.AddControllers();
services.AddReverseProxy()
                .LoadFromServiceFabric(options =>
                {
                    options.AllowStartBeforeDiscovery = false;
                    options.DiscoverInsecureHttpDestinations = true;
                    options.DiscoveryPeriod = TimeSpan.FromSeconds(15);
                    options.AlwaysSendImmediateHealthReports = true;
                    options.ReportReplicasHealth = false;
                });

**Comment by Tratcher** [comment]
The config logic looks fine. If you want more help figuring it out please share a complete repro app as a github repo.

**Comment by linmeng08** [comment]
Hi @faix yes it woks for me too with the options specified in the code, it's just not working when loading from configuration (appsettings.json). If the configuration works for others then it may be some issue on my side. I will try do more digging later this week and see if I can get that working.

Thank you all for the responses!

**Comment by karelz** [comment]
Triage: No repro, not actionable, closing for now. Feel free to reopen when there is repro. Thanks!
