### ISSUE TITLE
Changing the project title

### ISSUE THREAD

**Issue by cameronfletcher** [microsoft/reverse-proxy#90]
### What should we add or change to make your life better?
YARP (which stands for "YARP: A Reverse Proxy") is not formed from the [initial components of a longer phrase](https://en.wikipedia.org/wiki/Acronym) and as such does not do this project justice.
I suggest a rename to use DERP (which stands for "Dotnet Extensible Reverse Proxy") as a sensible alternative.

### Why is this important to you?
I take pride in the things I can influence for the better. You're welcome.

Linked issue: https://github.com/ProxyKit/ProxyKit/issues/10

**Comment by anurse** [comment]
We're not planning on changing the name 😛.
