### ISSUE TITLE
Document runtime version differences (APIs / Features) and workarounds

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#901]
https://github.com/microsoft/reverse-proxy/blob/main/docs/docfx/articles/runtimes.md documents relevant differences between 3.1 and 5.0. This should be updated to include new 5.0 APIs that YARP has exposed publicly. Some examples:
https://github.com/microsoft/reverse-proxy/blob/a1730a8817354ff59c1245a061b01da7a6496551/src/ReverseProxy/Abstractions/ClusterDiscovery/Contract/ProxyHttpClientOptions.cs#L52-L64

Also include that EnableMultipleHttp2Connections has been enabled by default.

**Comment by karelz** [comment]
Triage: E.g. Telemetry is useless (due to bug in Runtime).

**Comment by samsp-msft** [comment]
I'd suggest we also add info to this doc for how to build for 3.1, accounting for #1002 and #837.
