### ISSUE TITLE
Per request metrics

### ISSUE THREAD

**Issue by samsp-msft** [microsoft/reverse-proxy#908]
In looking at what Island gateway exposes, and the capabilities of prometheus & prometheus.net, I think we need a way to track per request telemetry.

Idea:
Have a feature that goes on the http context, either directly or as part of the ProxyFeature that will collect the telemetry. It would be an interface similar to IProxyMetrics that collects metric related data such as request/response time, bytes, timing for stages.

If its not present then it would be ignored. If it is present then the data would be set on it.
The consumption strategy would be for the consumer to add it via a middleware stage, and then collect the data at the end. By requiring them to set it, it enables them to decide which requests to add it to, to enable sampling etc.

@tratcher, @MihaZupan

**Comment by MihaZupan** [comment]
> By requiring them to set it, it enables them to decide which requests to add it to, to enable sampling etc.

If any of the exposed information would have to come from EventSource, you lose out on any benefits of sampling since you're paying the mayor part of the cost for every request, sampled or not.

**Comment by samsp-msft** [comment]
There is still a cost in firing the data to whatever collection routine.

Take a look at the samsp/prometheus branch - I have a working sample there that is collecting the metrics based on the events. As you say that can have perf implications, but I don't know how you'd get some of the http internals without going through events?

It would be good to do some perf runs and see how much impact it would have.

**Comment by samsp-msft** [comment]
Chris pointed out that the middleware is not called until after some of the events are fired :-(, but the Feature collection on the context does exist. The reason that I had middleware populating the feature with an object was to enable smarter collection, such as sampling or using a pool of objects ( I know how @davidfowl hates allocations). So I think that needs to change.

As you need to bring in the Telemetry consumption library, and register some of its listeners, maybe the per-request metrics collection should need to be registered as part of that, along with properties for whether to sample or collect all of them?

I initially wasn't sure that having to register the listeners to use this was a good idea - its another step you can miss - but it has the benefit of enabling you to select how granular you want to be with measurements, with increasing costs.

**Comment by MihaZupan** [comment]
We discussed adding a feature with timings in a meeting with the diagnostics team and decided to stay with the current approach (callbacks). The user can implement such functionality as a layer on top of callbacks, at most we can point that out in docs.

Closing against #676
