### ISSUE TITLE
Rename Cluster.Id to Cluster.ClusterId

### ISSUE THREAD

**Issue by Kahbazi** [microsoft/reverse-proxy#909]
Rename `Cluster.Id` property to `Cluster.ClusterId` to be consistence with `ProxyRoute` which has a `RouteId` property.

https://github.com/microsoft/reverse-proxy/blob/e9255a8e57518821f4eac2d5fab6c5be60fa7c96/src/ReverseProxy/Abstractions/ClusterDiscovery/Contract/Cluster.cs#L22

**Comment by MihaZupan** [comment]
Same with `DestinationInfo`

https://github.com/microsoft/reverse-proxy/blob/01af113e65f5553d8cad3410c0b224e21b0964d0/src/ReverseProxy/Service/RuntimeModel/DestinationInfo.cs#L34

Should we just make all of them `Id`?

**Comment by Kahbazi** [comment]
> Should we just make all of them Id?

I prefer `ClusterId` since I want to store them in a database and would like to have `Id` column as its auto increment primary key.

**Comment by karelz** [comment]
Triage: Part of API review.
