### ISSUE TITLE
Listening to 0.0.0.0 introduces random 1000ms delays in responses

### ISSUE THREAD

**Issue by vkapartzianis** [microsoft/reverse-proxy#911]
### Describe the bug
Setting `"Urls":  "http://0.0.0.0:8001"` instead of `"Urls":  "http://localhost:8001"` in appsettings.json seems to introduce random 1000ms delays in responses (to local connections).

### To Reproduce

I'm using a load-balancing configuration as below, with comments removed for simplicity. Requests come in parallel, 2 to 16 at a time and 4 services handle them, usually responding in 5-10ms. This is working fine until I change `localhost:8001` to `0.0.0.0:8001` in order to handle (very rare) requests from other IPs. After the change, the services still respond in 5-10ms but some times Yarp takes more than 1000ms (1020-1030) to respond in turn. That's with no requests from other IPs -- all requests are still local, the only thing that changes is listening to `0.0.0.0:8001` instead of `localhost:8001`.

I tried changing "LoadBalancingPolicy" but that had no effect.

``` json
{
  "AllowedHosts": "*",

  "Urls":  "http://localhost:8001",

  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },

  "ReverseProxy": {
    "Routes": [
      {
        "RouteId": "route",
        "ClusterId": "cluster",
        "Match": {
          "Path": "{**catch-all}"
        }
      }
    ],
    "Clusters": {
      "cluster": {
        "Destinations": {
          "Pricer_Service_1": {
            "Address": "http://127.0.0.1:18001"
          },
          "Pricer_service_2": {
            "Address": "http://127.0.0.1:18002"
          },
          "Pricer_service_3": {
            "Address": "http://127.0.0.1:18003"
          },
          "Pricer_service_4": {
            "Address": "http://127.0.0.1:18004"
          }
        },
        "LoadBalancingPolicy": "RoundRobin"
      }
    }
  }
}
```

### Further technical details

- Yarp.ReverseProxy v1.0.0-preview.10.21168.2
- Microsoft.NETCore.App 5.0.4
- Microsoft.AspNetCore.App 5.0.4
- Windows Server 2019

**Comment by Tratcher** [comment]
Use `http://*:8001` instead.

Localhost listens on ipv4 and 6 (127.0.0.1, ::1). 0.0.0.0 is any ipv4 address. * Will get you any address.

Dns resolves ipv6 addresses first so the client tried those first, times out, and then tries the next one.

**Comment by vkapartzianis** [comment]
That worked, thanks!
