### ISSUE TITLE
Please document the ProxyMatch "Path" pattern syntax

### ISSUE THREAD

**Issue by aschuhardt** [microsoft/reverse-proxy#914]
### What should we add or change to make your life better?

Provide documentation for how to write ProxyMatch path patterns.

### Why is this important to you?

The examples provided only illustrate that the string `/{**catch-all}` works, somehow, and doesn't go into any detail about the syntax used.  I have no idea how to use this.

Questions:

- Does the word "catch-all" have special meaning?
- What does `**` mean?  Is it different from a single `*`?
- How do I specify more complex patterns?
- Can we specify exclusions? i.e. `/{^error}` or something to exclude paths that start with the word "error"

**Comment by Tratcher** [comment]
The path pattern is passed through to the AspNetCore routing system which is documented here:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-5.0#route-template-reference

We should make sure our docs have the appropriate references back to the AspNetCore docs.

**Comment by aschuhardt** [comment]
> 
> 
> The path pattern is passed through to the AspNetCore routing system which is documented here:
> https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-5.0#route-template-reference
> 
> We should make sure our docs have the appropriate references back to the AspNetCore docs.

Thank you for that info.  Yes having that link someplace in the YARP docs would be very helpful.

**Comment by karelz** [comment]
Triage: We should provide link from our docs.
