### ISSUE TITLE
YARP Bench in internat

### ISSUE THREAD

**Issue by issingle** [microsoft/reverse-proxy#917]
### Describe the bug
**Bench in internat，performance not good.**

TestServer(Azure VM 2cpu 8G RAM):
ReverseProxy.Direct.Sample (net5)
www.test.com:80  is IIS
www.test.com:81  is Yarp ,backend is 127.0.0.1:80

TestClient（Local Workstation):
ab.exe -n1000 -c100
ping server  time=10ms

### Details
**AB.exe access IIS directly**
PS G:\> .\ab.exe -n1000 -c100 http://www.test.com/test/echo
This is ApacheBench, Version 2.3 <$Revision: 655654 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking www.test.com (be patient)
Completed 100 requests
Completed 200 requests
Completed 300 requests
Completed 400 requests
Completed 500 requests
Completed 600 requests
Completed 700 requests
Completed 800 requests
Completed 900 requests
Completed 1000 requests
Finished 1000 requests

Server Software:
Server Hostname:        www.test.com
Server Port:            80

Document Path:          /test/echo
Document Length:        330 bytes

Concurrency Level:      100
Time taken for tests:   12.130 seconds
Complete requests:      1000
Failed requests:        0
Write errors:           0
Total transferred:      659000 bytes
HTML transferred:       330000 bytes
Requests per second:    82.44 [#/sec] (mean)
Time per request:       1212.987 [ms] (mean)
Time per request:       12.130 [ms] (mean, across all concurrent requests)
Transfer rate:          53.06 [Kbytes/sec] received

Connection Times (ms)
                    min  mean[+/-sd] median   max
Connect:        3         12  63.1      7          1007
Processing:    13   1160 701.2    807        2865
Waiting:          9      624 622.5    465        2864
Total:              32   1172 704.9    816        2875

Percentage of the requests served within a certain time (ms)
  50%    816
  66%    857
  75%   1812
  80%   1837
  90%   1886
  95%   2844
  98%   2864
  99%   2869
 100%   2875 (longest request)

-----------------------------------------------------------------------------------------------------
**AB.exe access YARP**
PS G:\> .\ab.exe -n1000 -c100 http://www.test.com:81/test/echo
This is ApacheBench, Version 2.3 <$Revision: 655654 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking www.test.com:81(be patient)
Completed 100 requests
Completed 200 requests
Completed 300 requests
Completed 400 requests
Completed 500 requests
Completed 600 requests
Completed 700 requests  <----- At this time, Server Side Yarp cpu usage from 5%down to 0
Completed 800 requests
Completed 900 requests
Completed 1000 requests
Finished 1000 requests

Server Software:        Microsoft-IIS/7.5
Server Hostname:        www.test.com
Server Port:            81

Document Path:          /test/echo
Document Length:        318 bytes

Concurrency Level:      100
Time taken for tests:   92.903 seconds
Complete requests:      1000
Failed requests:        3
   (Connect: 3, Receive: 0, Length: 0, Exceptions: 0)
Write errors:           0
Total transferred:      589979 bytes
HTML transferred:       318000 bytes
Requests per second:    10.76 [#/sec] (mean)
Time per request:       9290.309 [ms] (mean)
Time per request:       92.903 [ms] (mean, across all concurrent requests)
Transfer rate:          6.20 [Kbytes/sec] received

Connection Times (ms)
                   min  mean[+/-sd]   median   max
Connect:        5         30 479.5          9     15011
Processing:    11   9149 23197.2   1943   80003
Waiting:         9     7614 22225.8    604    79987
Total:              21   9178 23198.5   1954   80013

Percentage of the requests served within a certain time (ms)
  50%   1954
  66%   1995
  75%   2005
  80%   2010
  90%  22994
  95%  78998
  98%  80002
  99%  80004
 100%  80013 (longest request)

**Comment by davidni** [comment]
Few comments that may help based on previous experience using `ab` in situations like this:
1. Looks like your test client (Apache ab) is not reusing connections. If it were, you'd see a line in the output showing `Keep-Alive requests:    1000`. Without connection reuse, a large portion of your time is likely spent for TCP handshakes (this would be even worse if this was using https). To achieve connection re-use with `ab`, make sure you pass the `-k` flag, and **make sure the server response is not chunked** -- `ab` uses HTTP/1.0, not HTTP/1.1, and therefore chunked responses also have a `Connection: close` response header

2. The delays you are seeing are suspiciously close to 21 seconds, the default TCP connection timeout after retries with exponential back-off (3 + 6 + 12 = 21 seconds). It is possible that your second test through YARP incurred SYN-throttling by Azure networks to protect your service from DoS attacks. Reusing connections would also help here, as you wouldn't be establishing this many connections and therefore would not be SYN-throttled.

3. Worst case, if you can't figure this out any other way, you can use a low-level packet sniffer like Wireshark to get to the bottom of this. The source of latencies should be fairly obvious from that.

**Comment by issingle** [comment]
Add -k flag,it seems better. 
For compare, I add a openresty test. 
First test YARP,then openresty
-------------------------------------------
**server:YAPP**
ab.exe -n1000 -c100 -k http://www.test.com:81/test/echo 
Server Software:        Microsoft-IIS/7.5
Server Hostname:        www.test.com
Server Port:            81

Document Path:          /test/echo
Document Length:        317 bytes

Concurrency Level:      100
Time taken for tests:   3.913 seconds
Complete requests:      1000
Failed requests:        0
Write errors:           0
Keep-Alive requests:    1000
Total transferred:      608256 bytes
HTML transferred:       324608 bytes
Requests per second:    255.58 [#/sec] (mean)
Time per request:       391.265 [ms] (mean)
Time per request:       3.913 [ms] (mean, across all concurrent requests)
Transfer rate:          151.82 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    1   2.9      0      17
Processing:    35  320 181.6    271    1167
Waiting:       35  320 181.6    271    1167
Total:         41  321 182.5    271    1167

Percentage of the requests served within a certain time (ms)
  50%    271
  66%    303
  75%    398
  80%    425
  90%    550
  95%    710
  98%    912
  99%   1077
 100%   1167 (longest request)
 
----------------------------------------------------
**server: openresty** 
_server{
	listen 82;
	location /{
		proxy_pass http://127.0.0.1:80;
	}
}_

ab.exe -n1000 -c100 -k http://www.test.com:82/test/echo 
Server Software:        openresty/1.19.3.1
Server Hostname:        www.test.com
Server Port:            82

Document Path:          /test/echo
Document Length:        317 bytes

Concurrency Level:      100
Time taken for tests:   1.305 seconds
Complete requests:      1000
Failed requests:        0
Write errors:           0
Keep-Alive requests:    1000
Total transferred:      595000 bytes
HTML transferred:       317000 bytes
Requests per second:    766.32 [#/sec] (mean)
Time per request:       130.494 [ms] (mean)
Time per request:       1.305 [ms] (mean, across all concurrent requests)
Transfer rate:          445.27 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    1   2.4      0      13
Processing:     5   91 145.3     36     750
Waiting:        4   91 145.3     36     750
Total:          5   92 146.8     36     757

Percentage of the requests served within a certain time (ms)
  50%     36
  66%     48
  75%     61
  80%     72
  90%    336
  95%    415
  98%    622
  99%    704
 100%    757 (longest request)

**Comment by karelz** [comment]
Triage: Looks like there is nothing substantial to follow up on. Feel free to reopen if we missed anything.
