### ISSUE TITLE
Configuration model changes called out in release notes

### ISSUE THREAD

**Issue by jmezach** [microsoft/reverse-proxy#930]
### Some details

**How many backends are in your application?**

- [ ] 1-2
- [ ] 3-5
- [x] 6-10
- [ ] 10+

**How do you host your application?**

- [ ] Kubernetes
- [ ] Azure App Service
- [ ] Azure VMs
- [ ] Other Cloud Provider (please include details below)
- [x] Other Hosting model (please include details below)

### What did you think of YARP?
We love YARP and have been running it in production for quite some time now. As new previews are being released we of course try to upgrade to the latest preview as fast as possible. In order to do that, release notes are obviously very important since they help us determine the impact of the upgrade. Of course we understand that at this stage breaking changes are necessary, but it is sometimes unclear whether the breaking change is purely in code or whether it (also) impacts the configuration model.

For example the [1.0.0-preview9](https://github.com/microsoft/reverse-proxy/releases/tag/v1.0.0-preview9) release notes calls out that there is a breaking change in that the config model has become read only. My team assumed that this also meant that the configuration itself had to change which made them hesitant to perform the upgrade. In the end it turned out the configuration didn't have to change at all, so the upgrade went very smoothly.

Honestly it isn't a really big deal, but it would have been helpful if each released would explicitly call out whether or not changes to the configuration would need to be made. @karelz suggested I'd post this here as an issue.

**Comment by Tratcher** [comment]
We have been using the `Breaking-Change` label to mark PRs that affect APIs, config, etc.. Should we add a new label for `Breaking-Config`? I'd suggest adding that in addition to the `Breaking-Change` label, and we could retroactively add it to old PRs.

**Comment by jmezach** [comment]
Yeah, I think that would work great for us.

**Comment by MihaZupan** [comment]
We're making sure to call out config-breaking changes in our release notes.

Given that breaking changes to the config are relatively uncommon (compared to code), we will try to call out if the config was untouched in release notes as well.
Generally speaking, the expectation should be that the config remains valid unless breaking changes are called out.
