### ISSUE TITLE
Test YARP against .NET 6 previews

### ISSUE THREAD

**Issue by samsp-msft** [microsoft/reverse-proxy#936]
Although there shouldn't be any changes in .NET 6 that break YARP, we should add .NET 6 as a target for build validation

**Comment by Tratcher** [comment]
We'll start with tests and samples. We don't want to add a .NET 6 target to the shipping packages until after 1.0.

**Comment by Tratcher** [comment]
We'll also need to review #if's in the tests and product code to make sure we're using the new NET5_0_OR_GREATER symbols so we don't have to add 6.0 specific symbols.
https://github.com/dotnet/designs/blob/be793b557255c9ed1276ecdd23119b64f45453bf/accepted/2020/or-greater-defines/or-greater-defines.md
