### ISSUE TITLE
Sample (& doc update) that uses simpler Asp.net template format

### ISSUE THREAD

**Issue by samsp-msft** [microsoft/reverse-proxy#937]
.NET 6 preview 4 is set to contain a new simpler template for web sites. We should have a sample (and docs) that show how to use YARP with the simpler template.

**Comment by Tratcher** [comment]
Waiting for the preview 4 sdk update here: https://github.com/microsoft/reverse-proxy/pull/972

**Comment by MihaZupan** [comment]
Should now be unblocked.

**Comment by MihaZupan** [comment]
@samsp-msft did you have another sample project in mind or updating an existing sample (e.g. BasicYarpSample)?

**Comment by Tratcher** [comment]
This should be its own sample since it will only work on 6.0. See:
https://github.com/dotnet/aspnetcore/blob/main/src/ProjectTemplates/Web.ProjectTemplates/content/EmptyWeb-CSharp/Program.cs

**Comment by MihaZupan** [comment]
Keeping this open as a tracking issue to update the Getting Started docs once 6.0 is released (behavior of `dotnet new web` changed to use the minimal sample)
