### ISSUE TITLE
Use MinHeap data structure to store a large number of EndpointInfos

### ISSUE THREAD

**Issue by alnikola** [microsoft/reverse-proxy#94]
When backend's LoadBalancingMode is set to `LeastRequests`, LoadBalancer needs to find an endpoint with [the lowest ConcurrencyCounter value](https://github.com/microsoft/reverse-proxy/blob/fee1ada299c072d2fa05c4693ec07ee6c9e0771a/src/ReverseProxy.Core/Service/Proxy/LoadBalancer.cs#L55). Currently, endpoints are stored in a list and search is done through a simple linear enumeration having O(n) complexity. This approach works well for a small collection (e.g. < 20), but gets ineffective for large once. Therefore, it's proposed to switch to  [Min Heap data structure](https://en.wikipedia.org/wiki/Binary_heap) instead of list when endpoint count get big enough.

We could introduce a new abstraction for endpoint collection (e.g. `IEndpointCollection : IReadOnlyList<EndpointInfo>`) exposing GetLeastLoadedEndpoint method with at least two implementations: ListEndpointCollection and MinHeapEndpointCollection. Further, [in the end of probing iteration](https://github.com/microsoft/reverse-proxy/blob/master/src/ReverseProxy.Core/Service/HealthProbe/BackendProber.cs#L119) if the current [BackendConfig](https://github.com/microsoft/reverse-proxy/blob/master/src/ReverseProxy.Core/Service/HealthProbe/BackendProber.cs#L73).Mode = LeastRequests and endpoint count is big enough, BackendProber will command [IEndpointManager](https://github.com/microsoft/reverse-proxy/blob/master/src/ReverseProxy.Core/Service/Management/IEndpointManager.cs) to change the underlying collection holding endpoints to new MinHeapEndpointCollection, or to ListEndpointCollection otherwise.

The worst case here is mode changing to LeastRequests from something else just after BackendProber updated the endpoint list, so ListEndpointCollection would have to use a linear search to find the target item. However, it will be the same as it is currently.

Further, to increase performance heap can be updated not on each ConcurrencyCounter change, but on events fired by a heuristic based on that counter [tracked in ProxyInvokerMiddleware](https://github.com/microsoft/reverse-proxy/blob/master/src/ReverseProxy.Core/Middleware/ProxyInvokerMiddleware.cs#L86). In example, it can happen when any of ConcurrencyCounters has got changed more than 10%.

**Comment by samsp-msft** [comment]
LeastRequests is generally not as useful or simple as it first appears:
* There is a cost to maintaining the list of what is least used, that has to account for all requests, or have an O(n) lookup cost.
* That doesn't account for load that may be coming from other instances of the proxy, or other sources.

Using algorithms like randomly pick 2 backends then choose the lowest load perform better and provide better balancing of load across the back ends.

**Comment by alnikola** [comment]
>There is a cost to maintaining the list of what is least used, that has to account for all requests, or have an O(n) lookup cost.

O(n) lookup cost is only for a simple list. I made this proposal because MinHeap **works faster**:

- Get the least used endpoint - O(1)
- Update endpoint's concurrent request counter - O(logn)

> That doesn't account for load that may be coming from other instances of the proxy, or other sources.

But as far as I see, to choose the **lowest loaded** endpoint  in this case, we must **also** know the total number of active requests. Thus, it would be the same accounting problem as with the LeastRequests, if there is another instance of proxy sending requests to the endpoint.
Or, am I missing something here?

**Comment by karelz** [comment]
Triage: Not required for 1.0. We can revisit if we have people hitting the limits ...
