### ISSUE TITLE
Transforms and direct proxying (re-visited)

### ISSUE THREAD

**Issue by leastprivilege** [microsoft/reverse-proxy#949]
continuation of #801

I had a look at the new `ITransformBuilder` changes - while this brings us a step closer, I think this might need a little bit more refactoring...

Since we only use `IHttpProxy` we call `services.AddHttpProxy` - we don't have `ITransformBuilder` registered.

Since all the plumbing is internal, we cannot register ourselves and the extension methods hangs of the builder for the full fledged reverse proxy which requires additional configuration plumbing...

Possible I am missing something of course.

**Comment by Tratcher** [comment]
Fair point, the following example code was added to testassets/ReverseProxy.Direct project, but it can't actually resolve the service from DI:
```C#
            var transformBuilder = app.ApplicationServices.GetRequiredService<ITransformBuilder>();
            var transformer = transformBuilder.Create(context =>
            {
                context.AddQueryRemoveKey("param1");
                context.AddQueryValue("area", "xx2", false);
                context.AddOriginalHost(false);
            });
```
```
System.InvalidOperationException: No service for type 'Yarp.ReverseProxy.Service.ITransformBuilder' has been registered.
```
I'll move the registration into `AddHttpProxy`.

**Comment by leastprivilege** [comment]
thanks!
