### ISSUE TITLE
Expose gRPC service in YARP

### ISSUE THREAD

**Issue by mohsenShakiba** [microsoft/reverse-proxy#952]
### Describe the bug
I've created a [sample solution](https://github.com/mohsenShakiba/GrpcyarpTest) that contains three projects:
- GrpcClient
- GrpcService
- YarpService

What I want is to expose the GrpcService Through the YarpService so that the client can send gRPC requests to YARP instead of GrpcService.
Now when I run the GrpcClient the request fails with a 502 response.
What am I doing wrong? am I missing a piece of configuration?
Is it even possible to expose gRPC endpoints in YARP?

### To Reproduce

- Clone the https://github.com/mohsenShakiba/GrpcyarpTest repo
- Run GrpcService with command: `dotnet run -p ./GrpcService/`
- Run YarpService with command: `dotnet run -p ./YarpService/`
- Run GrpcClient with command: `dotnet run -p ./GrpcClient/`

### Further technical details
GrpcService listens on:
```c#
options.ListenAnyIP(6000, listenOptions => { listenOptions.Protocols = HttpProtocols.Http2; });
options.ListenAnyIP(7000, listenOptions => { listenOptions.Protocols = HttpProtocols.Http1; });
```
And the YarpService also listens on:
```c#
options.ListenAnyIP(7500, listenOptions => { listenOptions.Protocols = HttpProtocols.Http1AndHttp2; });
options.ListenAnyIP(8000, listenOptions => { listenOptions.Protocols = HttpProtocols.Http2; });
```
Also I have a cluster that points to HTTP/2 grpc service
```json
"cluster1": {
  "Destinations": {
    "cluster2/destination1": {
      "Address": "http://localhost:6000/"
    }
  }
},
```

**Comment by Tratcher** [comment]
What error is reported in the yarp server logs?

You're not using https so there's an extra setting required to enable http/2:
```
"cluster1": {
  "HttpRequest": {
    "VersionPolicy": "RequestVersionExact"
  },
  "Destinations": {
    "cluster2/destination1": {
      "Address": "http://localhost:6000/"
    }
  }
},
```
https://microsoft.github.io/reverse-proxy/articles/proxyhttpclientconfig.html#httprequest

Also, the client no longer needs this setting on 5.0:
```       AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport", true);
```

**Comment by mohsenShakiba** [comment]
This is the exception shown in the yarp service
```
System.Net.Http.HttpRequestException: An error occurred while sending the request.
       ---> System.IO.IOException: The response ended prematurely.
         at System.Net.Http.HttpConnection.FillAsync(Boolean async)
         at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean async, Boolean foldedHeadersAllowed)
         at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at Yarp.ReverseProxy.Service.Proxy.HttpProxy.ProxyAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, RequestProxyOptions requestOptions, HttpTransformer transformer)
```
the link you have provided doesn't seem to work for me but regarding the https config for http/2, I just want to let you know that I can connect to grpc server directly without https, so I guess the problem resides somewhere else.

**Comment by Tratcher** [comment]
> the link you have provided doesn't seem to work for me but regarding the https config for http/2, I just want to let you know that I can connect to grpc server directly without https, so I guess the problem resides somewhere else.

The gRPC client already uses the new RequestVersionExact option internally so it can connect without https. YARP doesn't use that option by default since it doesn't know if the destination wants to use HTTP/1.1 or HTTP/2 by default. If you check the destination server logs you should see a protocol error where YARP tries to send HTTP/1.1 and the server requires HTTP/2.

**Comment by mohsenShakiba** [comment]
Thanks, what you explained pointed me to the exact issue,
What I had to do, based on the YARP document is to set the cluster HttpRequest.Version in configuration.
so I changed the cluster configuration to this and it worked:
```
"cluster1": {
  "HttpRequest": {
    "Version": "2",
    "VersionPolicy": "RequestVersionExact"
  },
  "Destinations": {
    "cluster1/destination1": {
      "Address": "http://localhost:6000/"
    }
  }
},
```

**Comment by Tratcher** [comment]
That's odd, 2 is the default version...

Re-opening since we should make sure we have a gRPC specific doc that mentions RequestVersionExact and http (gRPC is one of the few places I see HTTP/2 used without https).

**Comment by Tratcher** [comment]
https://github.com/microsoft/reverse-proxy/issues/118
