### ISSUE TITLE
API Review: IHttpProxy.ProxyAsync should return ProxyError result

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#962]
Today `IHttpProxy.ProxyAsync` avoids throwing for most common failures, reporting them through the IProxyErrorFeature instead.
https://github.com/microsoft/reverse-proxy/blob/0f42bff0e774bc5cbe5322c4f2b6c8e424789f05/samples/ReverseProxy.Direct.Sample/Startup.cs#L55-L63

This isn't discoverable. ProxyAsync should return `ValueTask<ProxyError>` so it's obvious what the result was. IProxyErrorFeature is only needed for direct callers if you want the details. 
```C#
var result = await httpProxy.ProxyAsync(httpContext, "https://example.com", httpClient, requestOptions, transformer);
if (result != ProxyError.None)
{
    var errorFeature = httpContext.Features.Get<IProxyErrorFeature>();
    var exception = errorFeature.Exception;
}
```

IProxyErrorFeature is still needed for middleware as they don't call IHttpProxy directly.

@Kahbazi interested?

**Comment by davidfowl** [comment]
I like the return value instead.
