### ISSUE TITLE
integrate with Dapr as Dapr's gateway

### ISSUE THREAD

**Issue by geffzhang** [microsoft/reverse-proxy#966]
### Some details

**How many backends are in your application?**

- [ ] 1-2
- [ ] 3-5
- [*] 6-10
- [ ] 10+

**How do you host your application?**

- [*] Kubernetes
- [ ] Azure App Service
- [*] Azure VMs
- [ ] Other Cloud Provider (please include details below)
- [ ] Other Hosting model (please include details below)

### What did you think of YARP?

**Comment by Tratcher** [comment]
Combining with #967
