### ISSUE TITLE
[HTTP/2] Filter TE header

### ISSUE THREAD

**Issue by alnikola** [microsoft/reverse-proxy#969]
In HTTP/2 the [TE header field is only accepted](https://datatracker.ietf.org/doc/html/rfc7540#section-8.1.2.2) if the `trailers` value is set. We need to filter out all prohibited combinations.

**Comment by karelz** [comment]
Triage: We should filter the header only when we're changing inbound HTTP 1.1 protocol to outbound HTTP/2.
