### ISSUE TITLE
Regular status updates from the YARP team 

### ISSUE THREAD

**Issue by anurse** [microsoft/reverse-proxy#97]
This issue contains status updates from the YARP team to provide insight into future plans, what the team is working on, and highlight helpful work done by the community.

We'll post a new entry approximately every 2 weeks.

If you want a low-spam way of tracking what's going on with YARP, then you should subscribe to this issue. 

### More Information
 
The YARP team uses github projects to track and prioritize work for the current release. You can find our projects here: https://github.com/microsoft/reverse-proxy/projects . The [Active Work](https://github.com/microsoft/reverse-proxy/projects/1) project shows what we're currently working on.

These updates are an effort by the YARP team to communicate in advance about plans and work going on. There's always the possibility that plans will change, or that reality will fail to live up to our expectations 👍.

Comments are disabled on this issue to reduce noise. If you have questions or want to discuss something, please open a new issue and tell us what's on your mind.

**Comment by anurse** [comment]
## April 24, 2020

## What are we doing now?

YARP is officially public! Welcome to the project! Up to now, our main focus has been around importing a prototype built by one of our partner teams at Microsoft and getting the repository ready. We're also consuming new builds of .NET 5 weekly so that we can get the latest and greatest improvements as we go.

Some of the changes we've made so far:

* Imported the "IslandGateway" prototype.
* Basic code tidy up and build system
* Refactored the proxy into a pipeline model to allow for better extensibility in the future
* Refactored the config system
* Implemented a total of four load balancing algorithms: Random, Power of Two Choices, Least Requests and First Healthy Endpoint.

### Community contributions

*Below is a list of all the community contributions between midnight on April 10, 2020 and midnight on April 24, 2020 (All times in UTC). Thanks to all our contributors for their enthusiasm and support!*

* @isaacabraham [Remove C#-specific reference](https://github.com/microsoft/reverse-proxy/pull/84)
* @Kahbazi [Use HttpMethods.IsXXX in HttpUtilities](https://github.com/microsoft/reverse-proxy/pull/76)
* @Kahbazi [Use is pattern matching with variable](https://github.com/microsoft/reverse-proxy/pull/70)
* @Kahbazi [Remove FluentAssertion](https://github.com/microsoft/reverse-proxy/pull/69)

**Comment by samsp-msft** [comment]
## June 25, 2020
## YARP Preview 2 is released

This release supports .NET Core 3.1 and .NET 5.0.0 Preview 6. See [Getting Started](https://microsoft.github.io/reverse-proxy/articles/getting_started.html).

Major changes and features:
- [Breaking Change] "Backend" has been renamed to "Cluster". See [Getting Started](https://microsoft.github.io/reverse-proxy/articles/getting_started.html) for updated config examples.
- [Session Affinity](https://microsoft.github.io/reverse-proxy/articles/session-affinity.html) - Ensure requests from a given client are always sent to the same destination server.
- [Transforms](https://microsoft.github.io/reverse-proxy/articles/transforms.html) - Modify the request sent to or the response received from the destination server.


For a complete list of changes see the [PR history](https://github.com/microsoft/reverse-proxy/pulls?q=is%3Apr+milestone%3A1.0.0-preview2+is%3Aclosed).

**Comment by Tratcher** [comment]
Closing since we've been tracking this via https://github.com/microsoft/reverse-proxy/releases.
