### ISSUE TITLE
[HTTP/2] Remove or reject all connection-specific headers from requests and responses

### ISSUE THREAD

**Issue by alnikola** [microsoft/reverse-proxy#970]
According to [RFC 7540, Section 8.1.2.2](https://tools.ietf.org/html/rfc7540#section-8.1.2.2) connection-specific headers are not allowed for HTTP/2. There are 3 cases we should handle:
1. If both of client to proxy and proxy to downstream connections are HTTP/2, we should treat a message as malformed if it contains any connection-specific header
2. If only one of connection is HTTP/2 and another is HTTP 1.1, we should remove all connection-specific headers for messages coming from HTTP 1.1 to HTTP/2 connection
3. We should keep Upgrade header in the [allowed upgrade scenarios](https://github.com/microsoft/reverse-proxy/blob/2de622a930068cdef30c1b2ef811bd98f8b01e84/src/ReverseProxy/Service/Proxy/HttpProxy.cs#L273-L277)

**Comment by Tratcher** [comment]
1) should be covered by kestrel & httpclient implementations?
2) we do this today for responses, but not requests. I don't know why we only did it in one direction.
https://github.com/microsoft/reverse-proxy/blob/80193a6c0e7d8df5ef25ae59f161c35774671ffa/src/ReverseProxy/Utilities/RequestUtilities.cs#L18-L37

**Comment by alnikola** [comment]
> 1. should be covered by kestrel & httpclient implementations?

It might be, but then it will require more scrutiny to ensure it won't break some working, though non-compliant, customer code.

**Comment by samsp-msft** [comment]
> 3. We should keep Upgrade header in the allowed upgrade scenarios
Why? The inbound and outbound protocol connections are independent. If the inbound connection wants to upgrade to Http2/3 then it can, but that should only affect the connection to the proxy, and not the connection between the proxy and destination server.

**Comment by Tratcher** [comment]
For websockets and spdy the upgrade header needs to flow through to the destination server. We should remove all values we don't support.

> If the inbound connection wants to upgrade to Http2/3 then it can

AspNetCore servers do not support that kind of upgrade for HTTP/2, you have to use ALPN.

**Comment by karelz** [comment]
Triage: We want to be explicit about what we filter in YARP, don't rely just on HttpClient/Kestrel.

**Comment by alnikola** [comment]
Duplicate of #439
