### ISSUE TITLE
Affinity conflicts between clusters

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#976]
The affinity flow looks like this:
request -> route -> cluster -> check affinity -> load balance -> proxy request -> establish affinity to destination -> proxy response

However, this can run into conflicts when you have multiple clusters.
request1 -> route1 -> cluster1 -> check affinity -> load balance -> proxy request -> establish affinity to destination1 -> proxy response
request2 -> route2 -> cluster2 -> check affinity [destination1 does not exist on this cluster] -> load balance -> proxy request -> establish affinity to destination2 [overrides affinity cookie] -> proxy response

And what's worse, `CookieSessionAffinityProviderOptions` is global, you can't even specify different cookie names per route.

**Comment by Tratcher** [comment]
This won't be a problem if the routes are host based, the cookie will be stored separately on the client per host, though I'm less sure about subdomains.

**Comment by samsp-msft** [comment]
It seems like there should be an option on a route for an affinity cookie suffix so that they can be separated for routes that have different clusters.

**Comment by Tratcher** [comment]
A suffix for the cookie name? That could work. You'd want to put it on the cluster affinity options, not the route.

Is there a default suffix we could provide for each cluster so the default case is not broken?

**Comment by Tratcher** [comment]
Proposal: Address this by addressing #236. E.g. Move the global CookieSessionAffinityProviderOptions to cluster specific config. That will allow people to change the cookie name per cluster, potentially adding your own suffix.

I'm not sure yet about how to avoid conflicts with the defaults. Today you can have affinity miss because of health state. Maybe we should add a second check on miss if that destination even exists in this cluster and hint that there may be an affinity conflict between clusters.

I'll add more notes to #236 about the proposed API changes.

**Comment by alnikola** [comment]
>I'm not sure yet about how to avoid conflicts with the defaults.

@Tratcher What do you think about adding the cluster name to the default affinity key to disambiguate that? I mean the case when `AffinityKeyName` is not set explicitly in the config.

**Comment by Tratcher** [comment]
The cluster name is private config data and the cookie/header name is given to the client in clear text, not a good combination. Also, the cluster name is likely to contain characters that aren't allowed in cookies or header names. 

We might be able to use some kind of hash derived from the cluster name though.

**Comment by alnikola** [comment]
Hash doesn't guarantee uniqueness. I'd avoid using it here.
May be we can use some kind of encryption instead of hashing? Not ideal, but it's supposed to be unique as far as I see.

**Comment by Tratcher** [comment]
Encryption is large. We don't need a strong guarantee of uniqueness, just something better than the default conflict.

**Comment by alnikola** [comment]
If we open a door for a conflict, it still can happen in 1 of 10M requests or so (just some very small probability) which would look like as a "Schrödinger" bug.

**Comment by samsp-msft** [comment]
Using a hash of the cluster name as part of the cookie name should be fine. This will be constant per cluster name, and the list of clusters should be small enough that the risk of collision is very very low. It would impact all affinity requests for those clusters and so would not appear as Schrödinger bug as it wouldn't be request dependent.

**Comment by alnikola** [comment]
Ok, makes sense. Then, I will fix this issue by adding a hashed cluster name to the **default** cookie name/custom header name.
I'm going to use SHA-256. Any objections?

**Comment by Tratcher** [comment]
We want the simplest, shortest hash we can get since we'll have to repeat it on every request to read the cookie. This isn't a security feature, we're only using it for disambiguation.

**Comment by alnikola** [comment]
Then, I'd suggest to use CRC32.

**Comment by alnikola** [comment]
>We want the simplest, shortest hash we can get since we'll have to repeat it on every request to read the cookie.

Actually, I just realized that we might avoid computing the hash each time because the cluster name changes only when the config gets updated. We can calculate it once on a config update and then store somewhere (e.g. on ClusterModel)
What do you think?

**Comment by Tratcher** [comment]
Since the value is only needed when you have affinity enabled and are using default affinity keys, lets try a cache like we do for health checks:
https://github.com/microsoft/reverse-proxy/blob/a4b85d79b17cf11d1a93e1943e5786727f0da219/src/ReverseProxy/Service/HealthChecks/ConsecutiveFailuresHealthPolicy.cs#L19
