### ISSUE TITLE
LoadBalancingPolicy = First broken in preview 11

### ISSUE THREAD

**Issue by Henery309** [microsoft/reverse-proxy#980]
### Describe the bug
Took us few hours to work this out. We deployed yarp preview 11 to prod for a small service. Worked as expected for 2 hours then service got restarted and yarp started using second destination. Previously this happened if first destination was unhealthy but with preview 11 it is random. This is not a problem with preview 10.

### To Reproduce

Create new project and use the configurations below. Then run the https://localhost:5001/todo/v1.
You'd have to run this few times by stopping the app and rebuilding it. Sometimes the configurations don't get cleared until you rebuild the solution in VS (this is a another problem). 

Here is my result I ran the project and yarp picked up second destination. If rebuild and re run few times destinations will randomly change.
![image](https://user-images.githubusercontent.com/59211495/117213942-60d32880-ae50-11eb-85e8-93ab6b533754.png)

```json
{
  "Logging": {
    "LogLevel": {
      "Default": "Debug",
      "Microsoft": "Debug",
      "Microsoft.Hosting.Lifetime": "Debug"
    }
  },
  "AllowedHosts": "*",
  "ReverseProxy": {
    "Routes": {
      "Route8": {
        "ClusterId": "cluster1",
        "Match": {
          "Methods": [ "GET" ],
          "Path": "/todo/v1"
        },
        "Transforms": [
          {
            "PathSet": ""
          },
          {
            "ResponseHeader": "Access-Control-Expose-Headers",
            "Append": "IsSuccessful",
            "When": "Always"
          },
          {
            "ResponseHeader": "Access-Control-Max-Age",
            "Append": "86400",
            "When": "Always"
          }
        ]
      }
    },
    "Clusters": {
      "cluster1": {
        "LoadBalancingPolicy": "First",
        "HealthCheck": {
          "Passive": {
            "Enabled": "true",
            "Policy": "TransportFailureRate",
            "ReactivationPeriod": "00:01:01"
          }
        },
        "HttpRequest": {
          "Timeout": "00:01:00",
          "Version": "1.1"
        },
        "Destinations": {
          "cluster1_destination1": {
            "Address": "https://jsonplaceholder.typicode.com/todos/1"
          },
          "cluster2_destination2": {
            "Address": "https://jsonplaceholder.typicode.com/todos/2"
          }
        }
      }
    }
  }
}
```
Startup

```c#
public class Startup
    {
        public IConfiguration Configuration { get; }

        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddReverseProxy().LoadFromConfig(Configuration.GetSection("ReverseProxy"));
           
            services.AddCors(options => options.AddPolicy("EnableCors", builder =>
            {
                builder.AllowAnyOrigin().SetPreflightMaxAge(TimeSpan.FromSeconds(86400));
                builder.AllowAnyMethod().SetPreflightMaxAge(TimeSpan.FromSeconds(86400));
                builder.AllowAnyHeader().SetPreflightMaxAge(TimeSpan.FromSeconds(86400));
            }));
        }

        public void Configure(IApplicationBuilder app)
        {
            //app.UseMiddleware<ExceptionMiddleware>();
            app.UseCors("EnableCors");
            app.UseRouting();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapReverseProxy();
            });

        }
    }
```

### Further technical details

- Package Yarp.ReverseProxy - 1.0.0-preview.11.*
- The platform - Windows

**Comment by Tratcher** [comment]
Is it consistently returning the same destination within one run of the app, and only changing when the app restarts?

Destinations is currently an un-ordered collection stored in various dictionary structures. The results should be stable within a run, but there's no guarantee of the order on load. I can understand that being confusing the the 'first' algorithm.

Is this on .NET 3.1 or 5.0?

We should check to see which collection is unstable across runs, and if we can provide a more predictable ordering like alphabetical, or if we need to make destinations a strictly ordered list. 'First' is the only algorithm directly impacted by order since it avoids using the second one except as fail-over.

**Comment by Henery309** [comment]
@Tratcher 

> Is it consistently returning the same destination within one run of the app, and only changing when the app restarts?

In preview 11 no - every few runs you get a random destination. In preview 10 its consistently returning first destination and 
when you restart the app the first destination is used.

> The results should be stable within a run, but there's no guarantee of the order on load.

If order cannot be guaranteed across all runs then 'First' algorithm isn't useful right? Order was enforced until preview 10 it broke in preview 11. Now we are blocked until this is fixed, can't upgrade to preview 11. 

As for solution any order will work, strict or alphabetical.

> Is this on .NET 3.1 or 5.0
5.0

**Comment by MihaZupan** [comment]
> We should check to see which collection is unstable across runs

I assume it's our use of a Dictionary here (`StringComparer.OrdinalIgnoreCase` uses a random seed for hash calculations that will change between process restarts):

https://github.com/microsoft/reverse-proxy/blob/86529c9db046bc7b5985d2827f507de537880b7a/src/ReverseProxy/Service/RuntimeModel/ClusterState.cs#L52

https://github.com/microsoft/reverse-proxy/blob/86529c9db046bc7b5985d2827f507de537880b7a/src/ReverseProxy/Service/RuntimeModel/ClusterState.cs#L88

**Comment by Tratcher** [comment]
In preview10 it was a regular Dictionary. ConcurrentDictionary seems to be less stable.
https://github.com/microsoft/reverse-proxy/blob/67a5b6d2c37f1373b5ec268ce93bbd0a572fa010/src/ReverseProxy/Service/Management/ItemManagerBase.cs#L14

**Comment by Henery309** [comment]
Will this be fixed in preview 12?

**Comment by samsp-msft** [comment]
@Henery309 To get you unblocked: Are there other features you need in preview 11, or can you rollback to preview 10?
@Tratcher - can they replace the concurrent dictionary back with a dictionary and build their own copy of preview 11?

@Henery309 - We'd also like to better understand why you are using first? Is this less of a load balancing and more of a backup mechanism - use the first destination unless there is a problem and then fallback to the others in order?

**Comment by Henery309** [comment]
> To get you unblocked: Are there other features you need in preview 11, or can you rollback to preview 10?

I have rolled back to preview 10 for now, in preview 11 I was using https://github.com/microsoft/reverse-proxy/pull/866 which is not available in preview 11

> We'd also like to better understand why you are using first? Is this less of a load balancing and more of a backup mechanism - use the first destination unless there is a problem and then fallback to the others in order?

Yep less of load balancing and more of a backup - We have a legacy service running on iis which requires a manual app pool recycle 2-3 times a week. We have yarp configured to use secondary destination incase first is down. This gives our on call staff few minutes or hours to restart the main service. 

Our legacy service currently returns a custom error code when it goes down. In preview 11 we use https://github.com/microsoft/reverse-proxy/pull/866 to interrupt the response and return http 500. 

I am also closely watching https://github.com/microsoft/reverse-proxy/issues/56 Instead of returning any errors to client when legacy services goes down. It would be better to retry the request against the second destination and return a successful response.

**Comment by Tratcher** [comment]
> We have yarp configured to use secondary destination incase first is down. 

Are you doing this with Active/passive health checks?

**Comment by Henery309** [comment]
> Are you doing this with Active/passive health checks?

Yes - we use a custom `IPassiveHealthCheckPolicy` which looks for custom error code returned from first destination and then marks the first destination as unhealthy.

```
public class CustomPassiveHealthCheckPolicy : IPassiveHealthCheckPolicy
    {
        private readonly IDestinationHealthUpdater _healthUpdater;
        private static readonly TimeSpan DefaultReactivationPeriod = TimeSpan.FromHours(1);

        public CustomPassiveHealthCheckPolicy(IDestinationHealthUpdater healthUpdater)
        {
            _healthUpdater = healthUpdater;
        }

        public void RequestProxied(ClusterInfo cluster, DestinationInfo destination, HttpContext context)
        {
            var status = context.Response.StatusCode;
            if (status == 1251 && !destination.DestinationId.Equals("cluster1_destination2"))
                _healthUpdater.SetPassive(cluster, destination, DestinationHealth.Unhealthy, DefaultReactivationPeriod);
        }

        public string Name => HealthCheckConstants.PassivePolicy.TransportFailureRate;
    }
```

**Comment by Tratcher** [comment]
While I appreciate that the customization is working for you, your scenario might be easier using IHttpProxy directly. When you're only using two destinations the routing and load balancing aren't giving you much. If you try IHttpProxy I'm curious to hear how it works for you.

**Comment by karelz** [comment]
Triage: Needs experimenting on solution to get deterministic order.

**Comment by Tratcher** [comment]
I was investigating https://github.com/microsoft/reverse-proxy/issues/83#issuecomment-844565946 which deals with the available destinations list generation and briefly considered introducing sorting there, but First is the only policy proposed so far that depends on a strict ordering.

Proposal: Redefine `First` from meaning "First available destination we find" [O(1)] to meaning "Alphabetically first available destination." [O(n)]. The implementation would change accordingly from `availableDestinations[0]` to doing a single pass scan through the list to find the first entry by name. This has the benefit of working independent of the rest of the infrastructure, and being deterministic across reloads, adds, removes, etc.. Since First is expected to be used with a small number of destinations this change shouldn't add significant overhead.

Thoughts?

Thoughts?

**Comment by karelz** [comment]
@Tratcher I like your proposal! Nice!

**Comment by MihaZupan** [comment]
Sounds reasonable. It can still be ~ O(1) if we choose to cache the "first" for a given collection

**Comment by Tratcher** [comment]
> It can still be ~ O(1) if we choose to cache the "first" for a given collection

That's tricky given the collection can be changed per request by middleware. I also wonder what the cache would cost by comparison.

**Comment by Tratcher** [comment]
@Henery309, are you interested in contributing this fix? See https://github.com/microsoft/reverse-proxy/issues/980#issuecomment-845545603.
