### ISSUE TITLE
Unable to modify the proxied response body in the custom asp.net core middleware

### ISSUE THREAD

**Issue by dotsource** [microsoft/reverse-proxy#984]
### Describe the bug
Unable to modify the proxied response body in the custom asp.net core middleware

### To Reproduce
Create a middleware, read response body, modify it and write it and it is not working! I tried custom middleware, proxy middleware, Proxy transform with no luck.

**Comment by Tratcher** [comment]
Can you show example code of what you tried?

The server does not buffer the response body, it's sent immediately to the client. You need to intercept it by either buffering or using a wrapper stream.

Consider the ResponseCompressionMiddleware that does something like this:
https://github.com/dotnet/aspnetcore/blob/main/src/Middleware/ResponseCompression/src/ResponseCompressionMiddleware.cs

**Comment by dotsource** [comment]
Thanks for the quick reply and pointing in the right direction. I will give it a try.

**Comment by karelz** [comment]
Triage: 2 weeks, no reply, still not enough info. Closing. Feel free to reopen when you have more details.
