### ISSUE TITLE
Docs / Plan for Client cert handling

### ISSUE THREAD

**Issue by samsp-msft** [microsoft/reverse-proxy#989]
If the proxy is handling the client cert how does it pass it to the back end server?
Can the proxy do cert auth with the backend so that the backend can trust connections are coming from the proxy

**Comment by Tratcher** [comment]
> If the proxy is handling the client cert how does it pass it to the back end server?

 See https://github.com/microsoft/reverse-proxy/blob/main/src/ReverseProxy/Service/RuntimeModel/Transforms/RequestHeaderClientCertTransform.cs

> Can the proxy do cert auth with the backend so that the backend can trust connections are coming from the proxy

See https://microsoft.github.io/reverse-proxy/articles/proxyhttpclientconfig.html#httpclient, though there's a proposal to remove this from the config and only support it via the extensible factory:
https://github.com/microsoft/reverse-proxy/issues/352#issuecomment-803189412

**Comment by Tratcher** [comment]
https://github.com/microsoft/reverse-proxy/issues/999
https://github.com/microsoft/reverse-proxy/pull/1031

**Comment by alnikola** [comment]
It seems #999 is moved into "Backlog" and #1031 is completed. 
@samsp-msft @Tratcher  Can we now close this issue as completed?

**Comment by Tratcher** [comment]
The 3rd question here is if https://microsoft.github.io/reverse-proxy/articles/transforms.html#clientcert is adequate documentation for flowing an external client certificate?

**Comment by samsp-msft** [comment]
No, I don't think its adequate docs... yet. I think there needs to be a bit more preamble. I'll create a PR.

**Comment by samsp-msft** [comment]
Triage: Also need to clarify how client certs should be validated.
