### ISSUE TITLE
How to: Certificate rotations

### ISSUE THREAD

**Issue by samsp-msft** [microsoft/reverse-proxy#993]
How should certs be rotated with YARP without having to stop the service? Do we detect that cert store or files on disk have changed?

**Comment by Tratcher** [comment]
Server certificates (incoming connections) or client certificates (outgoing connections)? Presumably both.

**Comment by samsp-msft** [comment]
Yes both. Also how to associate the right certs with either routes (incoming) or clusters/destinations (outgoing).

**Comment by Tratcher** [comment]
Incoming cert config is handled by the server, it's not a YARP concern. Barry is working on rotation guidance there.

For outgoing certs, see https://github.com/microsoft/reverse-proxy/issues/989#issuecomment-839366901.

**Comment by karelz** [comment]
Duplicate of #989
